### ISSUE TITLE
Display photo & nickname

### ISSUE THREAD

**Issue by NickCis** [emesene/emesene#1]
Although, in your machine, your nickname, message, and pictures are shown correctly (the nick and message are correctly taken from the msn servers). Others see them wrong.
 For example, my nickname is "Nick", my message is "I'm testing", and i've recently set up a new photo. Others, instead of seeing my nick see "N" (As it would have set up since the msn nickname bug of emesene 1.0); instead of my message they see a blank espace (as if i had no message) and finally they see that i have no display picture.
Note: if i change my nick, the nick is correctly seen by others,,, But if i disconnect and then connect, the nick others see isn't the correct one (the one that i've choosen in my previuos session, the one mesinyer display in my machine).

**Comment by NickCis** [comment]
I post the same issue on the Marianoguerra Git hub, ( http://github.com/marianoguerra/emesene/issues#issue/9 ). I don't really know where i've to post bugs and all that, in this repo?, or in the Mariano guerra's one?

**Comment by c10ud** [comment]
which library are you using? MSN or Papyon?

about posting bugs: we still have to choose our bugtracker

**Comment by NickCis** [comment]
The msn one. (Note: if you use papyon, you have the old emesene 1.0 nick bug)

**Comment by NickCis** [comment]
I've just test the last version from this repo and the bug continues. I'm testing using the MSN connect option (of the preference menu).  In this link the problem is clearly shown ( http://i.imagehost.org/view/0172/nick_bug ).
Although, Emesene show my nick correctly, people, who i am chatting with,  see them incorrectly.

**Comment by c10ud** [comment]
"msn" backend doesn't have support for display pictures yet

**Comment by NickCis** [comment]
Ok, but that is part of the bug,,, Please pay especial attention to the nicknames in the screenshot i've upload. My mesinyer says that my nickname is: "Nick {Mar, Te Amo}", and my message is: "[Minds are like parachutes. They only function when they are open.]"; but other people (see the conversation, i've opened 2 mesinyers, to test this), instead of seeing my nick, they see "N", and instead of my personal message, they see a blank space. Do you understand what i'm refering to?

**Comment by c10ud** [comment]
ok, now i saw it but emesene is still early alpha-beta and there may be heavy bugs in the libraries (both, msn and papyon) and in e3 implementations.. so i suggest to wait using emesene2 until we do more stuff, at the moment everything is quite hackish

**Comment by NickCis** [comment]
Jeje,,, i know that,,, i'm just reporting bugs, as it was suggested on the emesene blog,,, Currently i'm using Kmess2 on Kde, and on gnome the Svn version of emesene ¬¬ =P

**Comment by marianoguerra** [comment]
users with no group in order by group mode are now grouped under a special group
closed by 984d25fd79983185d56c7aa8a9bf2e2413ba4554

**Comment by marianoguerra** [comment]
NickCis, report the stuff you see so we know about the bugs, use the emesene/emesene bug tracker from now on.

thanks for reporting

**Comment by c10ud** [comment]
this is currently unimplemented in papyon, and partially in e3.msn -- i'm closing this issue because they're two missing features

greets
