### ISSUE TITLE
adium themes wtf

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#10]
open emesene2, open emesene1. 
use emesene1 to open a new conversation with emesene2.
write text, nothing will appear in the adiumtextbox, but this happens in terminal:
console message: undefined @1: ReferenceError: Can't find variable: appendMessage
console message: undefined @1: ReferenceError: Can't find variable: scrollToBottom
console message: undefined @1: ReferenceError: Can't find variable: appendMessage
console message: undefined @1: ReferenceError: Can't find variable: scrollToBottom
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.
console message: file:///home/riky/msn/emesene2/mesinyer/themes/conversations/renkoo.AdiumMessageStyle @249: TypeError: Result of expression 'insert' [null] is not an object.

if emesene2 sends a message to emesene1, the thing starts working

**Comment by cando** [comment]
yes...i confirm that!

**Comment by cando** [comment]
fixed!we can close that

**Comment by c10ud** [comment]
hell yeah
