### ISSUE TITLE
Animated imagens in user profile picture

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1002]
WLM users can use animated pictures in their user image, but emesene never supported that...

There's any way to implement?

**Comment by Sbte** [comment]
I think we do support this? Don't we?

**Comment by Stiveknx** [comment]
No, in imo.im I can see animated images, but in emesene only the first "frame" of the animated image...

**Comment by Sbte** [comment]
Wait, do you mean your own picture or contact pictures? Contact pictures really should work...

**Comment by Stiveknx** [comment]
Well, can be both, but I'm talking about contact pictures...
I don't care if I can't use animated images in my picture, but at least I would like to see the others image.

**Comment by Sbte** [comment]
Ok, I tested this: it works in the contact list, for your own picture, for conversations, everywhere. It only doesn't work when a contact is blocked.

**Comment by arielj** [comment]
are you using emesene2? or emesene1?

emesene2 supports animated avatars

**Comment by Stiveknx** [comment]
I'm using emesene2 here ...
Well, it's not working then...
My friend  it's using this image:
https://livefiles18.vo.msecnd.net/static/52

But I don't see the ball 'kicking' only the rest ...

**Comment by arielj** [comment]
Just tested using that image, it works here as my avatar and as a contact avatar.

Maybe you have something missing on your system? do you have mmm, imagemagick?

**Comment by Stiveknx** [comment]
In my image it works, but my contact image it doesn't ...

**Comment by Sbte** [comment]
Maybe you have imagemagick installed, but you have a version that doesn't support animated images?
