### ISSUE TITLE
Typing text and smileys in the same line

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1005]
Typing text and smileys in the same line is possible. However, I see it always moving (up and down, you can see a small scroll bar appearing). It's very annoying. You can fix it if you make the text area a bit higher.

**Comment by c10ud** [comment]
or you can fix it making your text area bigger than the default

2012/2/2 kingsmile
reply@reply.github.com:

**Comment by Smile4ever** [comment]
Is there an option to do that? Or do the devs need to do that?

**Comment by c10ud** [comment]
just drag the horizontal pane below the toolbar buttons to make the area bigger

**Comment by Smile4ever** [comment]
Thanks :)
---- Aan Thu, 02 Feb 2012 19:15:48 +0100 Riccardo &lt;reply@reply.github.com&gt; schreef ---- 

just drag the horizontal pane below the toolbar buttons to make the area bigger 

---
