### ISSUE TITLE
Different browsers are opened after pressing two different buttons in emesene

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1006]
Hello,

I am not sure if the title is clear, so let me explain the issue. I am using Lubuntu 11.10 in my computer, which had Chromium installed by default and then I installed Opera afterwards (which appears apparently as the default browser in the "Preferred Applications" option in the menu). 

In the emesene preferences menu, option "Live Messenger" there is a button called "Open Live Profile".  I press this button and Opera is opened. but the autologin feature doesn't work, i.e, it opens the Windows Live homepage, but still, I need to enter my username and password.

On the other hand, there is a button with the number of unread messages in the menu. I clicked it and Chromium is opened. The autologin feature works perfectly and it shows my Windows Live homepage directly, so I can check my hotmail inbox.

In consequence, I have two questions:
- Does the autologin feature is expected to work after pressing those two buttons? (so, in the case of Opera browser there is a problem? Or the problem is rather a bug in emesene?)
- Why two different browsers are opened after pressing those buttons? Is there a way to configure my OS so that the same browser is opened (perhaps emesene reads data about preferences from two different files), or is rather an issue of emesene which should be reading the same preferences file in order to choose the same browser for those actions?

Thanks for your attention

**Comment by Sbte** [comment]
What version of emesene do you use? This is supposed to be fixed in 2.11.11+

Also, the "Open Live Profile" manual login is on purpose. Otherwise it won't take you to the right page.

**Comment by Sacolevas** [comment]
Hello,

I am glad to know the Open Live Profile manual login was on purpose. I thought it would be automatic as the link to check messages. But the situation with two different browsers still happens. I am using emesene 2.12.1 (installed from the emesene PPA https://launchpad.net/~emesene-team). Thanks for your reply

**Comment by Sbte** [comment]
I think I know what's happening. The mail button uses a local file, so probably your operating system uses a different browser for opening local files. If you set the default application to open htm files to Opera, everything should be fine.

I'm not sure if we're able to fix this. We already use the most advanced way of checking for the right browser that I've seen in any application so far...

If we want to fix this anyway, we should check whether we are opening a file that can be opened with a browser, and if we can, we should use the application that opens links that start with http. But I have no clue on how to do that...

**Comment by Sacolevas** [comment]
"Sbte: The mail button uses a local file, so probably your operating system uses a different browser for opening local files. If you set the default application to open htm files to Opera, everything should be fine."

Thanks for the info about application for opening local files. I changed this as indicated and now it is working fine for the moment (i.e opening with the default application).

**Comment by Sacolevas** [comment]
Sorry, I made a click in "closed and comment" and put this as "closed". It wasn't my intention (I feel I have no authority to decide whether an issue is closed or not).

**Comment by zipatei** [comment]
Easy... change extension... hotmail.htm to hotmail.html..

**Comment by Sbte** [comment]
@zipatei that doesn't make a difference. htm and html files have the same mime type and therefore open with the same application.

**Comment by zipatei** [comment]
Have the same mime type, but ubuntu open preferencial browser html, but forget htm. Test it.

**Comment by Sbte** [comment]
I tried it, both using nautilus and using xdg-open, and both htm and html files open with the application specified for the text/html mime type.

**Comment by zipatei** [comment]
I apologize because i said without testing.

Before, ubuntu open files with the html preferred application and htm to the mime type. now is the same.

Sorry about that.

**Comment by Sbte** [comment]
@zipatei, yes, that's the main reason why we don't just use webbrowser.open anymore.

**Comment by pepeleproso** [comment]
I think we can asume this is a misconfiguration of the system, as we already have the most smart system to detect browser
