### ISSUE TITLE
Preferences at login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1008]
Reproduce:
1. Open preferences at login
2. Click advanced
3. Click again in advanced

emesene hides the content but not resize the window again ...

It is not important, but it is a way to make more professional emesene.

**Comment by lfottaviano** [comment]
lol, and what do you think If advanced is directly shown expanded... because, there is no reason to be hidden when there is no other thing to show or do.

**Comment by zipatei** [comment]
:) ya.. can be also.

**Comment by lfottaviano** [comment]
haha ok, thats simple, I am going to do it... but I dont know If everybody would accept that lol

**Comment by pepeleproso** [comment]
@sbte and @c10ud any opinions on this?

**Comment by Sbte** [comment]
Better leave it like this, because we don't want people to mess with those settings.

**Comment by lfottaviano** [comment]
and I am completely agree

**Comment by c10ud** [comment]
Same here, in the end you open that menu once or twice if everything's normal.

As for OP's issue, it's a minor ui glitch, patches welcome (?)

2012/3/23 Sven reply@reply.github.com:

**Comment by zipatei** [comment]
Another suggestion was not to hide information, and add a reset button.

**Comment by jamesaxl** [comment]
i do it :° congratulation

**Comment by zipatei** [comment]
@Sbte @jamesaxl @c10ud 

This is not all fixed.

Do not know if it was intentional, but now also appears user authentication.

In Facebook and GTalk session, if we click "use proxy" and desactivate, it's the same the original bug.

**Comment by jamesaxl** [comment]
ok i'll fix it, but it isn't a bug just gtk gui

**Comment by Sbte** [comment]
That the proxy stuff appears at all is a bug I think. Because it only disappears if you click on it twice. Maybe just not hide it at all is sufficient here.
