### ISSUE TITLE
conversation format broke while file transmit

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1009]
As this image: http://imageshack.us/photo/my-images/443/formatj.jpg/ The format is broken while file transmit.

Version: 09bc8a8b38be8af6754edd3cb3bb741c27ae22c0 and there is no plugin update.

**Comment by c10ud** [comment]
ah, this is interesting.. you sent the file and your friend accepted it and said thanks?

seems like the informative message broke the layout @pepeleproso

**Comment by moneycat** [comment]
Yes, my friend accepted it and reply "thx" to me.

**Comment by danielgomon** [comment]
I can confirm this problem, happens to me all the time.

**Comment by pepeleproso** [comment]
we need to clear ConversationStatus after each informative message, I'll make a patch for this

**Comment by moneycat** [comment]
Solution Confirmed. Thanks.
