### ISSUE TITLE
GtkWarning: A node was inserted with a parent that's not in the tree.

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1010]
I dont know this is important, but:

/home/andre/emesene/emesene/gui/gtkui/ContactList.py:654: GtkWarning: A node was inserted with a parent that's not in the tree.
This possibly means that a GtkTreeModel inserted a child node
before the parent was inserted.
  self._model[contact_row.iter] = contact_data

**Comment by zipatei** [comment]
/home/andre/emesene/emesene/gui/gtkui/ContactList.py:654: GtkWarning: _gtk_rbtree_reorder: assertion `tree->root->count == length' failed
  self._model[contact_row.iter] = contact_data

**Comment by Sbte** [comment]
Any clue how that happened? It's hard to see if there's anything obviously wrong with that code.

**Comment by zipatei** [comment]
I can only say that I login, and contacts did not appear. And it was this error in the console.

**Comment by Sbte** [comment]
What options do you use to sort the contact list?

**Comment by zipatei** [comment]
groups and order by state

**Comment by Sbte** [comment]
And under Show...?

**Comment by zipatei** [comment]
Nothing

**Comment by zipatei** [comment]
Close at moment... but appear again, reopen.
