### ISSUE TITLE
[Request] Don't try to loggin automatically if you're logged in another session

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1012]
I can open how many accounts with emesene at the same time...

But, let's say, I login in my account (acount1@hotmail.com),and I select "login automatically".
I open emesene again trying to conect to another account, but emesene tries to conect automatically in acount1@hotmail.com, which is already logged-in in that same computer, so I have to cancel and type the another account ...
It's not soo important, it's just a simple detail, but would be good if  got fixed

**Comment by Sbte** [comment]
@c10ud, do you know any way to hack this through dbus or something?

**Comment by Stiveknx** [comment]
There's any file that is touched/update when you login? Could check that in the function that login in automatically ... ;s

**Comment by Sbte** [comment]
No. Also, if we did modify a file, and emesene would crash, it would recognise emesene as being open. That's not so nice...

**Comment by c10ud** [comment]
well it can be done with some dbus hacking or adding new options to commandline like:
emesene --service msn --account account@mail

**Comment by pepeleproso** [comment]
I make a patch for this. it's here https://github.com/pepeleproso/emesene/commit/c40c50120c07fcc8510dcad591f9c60e10826dd0

please @Sbte and @c10ud take a look

**Comment by Stiveknx** [comment]
Works like a charm.

Thanks!

It's not in main code right? (I had to patch manually cause `git pull` didn't update)

**Comment by c10ud** [comment]
patch looks good to me, go ahead

2012/2/18 Stiveknx
reply@reply.github.com:

**Comment by Sbte** [comment]
Looks good to me too.
