### ISSUE TITLE
[Request, Features] Notify when specific contact goes online/offline

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1013]
Hello, 

Before using emesene, I was using Pidgin and one of the features I really liked from that program was the abiliy to notify when some contact went offline/online ("Buddy Pounces"). Are there plans to implement a similar feature in emesene2? Thanks

**Comment by pepeleproso** [comment]
this probably need to be a plugin

**Comment by c10ud** [comment]
indeed, and a simple one, here's how to do it:
- connect the online/offline signals
- get the notification extension instance
- make a config window: contact, online, offline
- in online/offline callback: if contact in selection_list then notify

**Comment by Sbte** [comment]
https://github.com/emesene/emesene-supported-plugins/issues/68
