### ISSUE TITLE
[Feature] Questions about Gtalk: Video chat, Invisibility and Check mail button

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1014]
Hello,

I have three questions about emesene with a gmail account (choosing gtalk):
- It is possible to implement video chat in emesene (we already know it is not possible for MSN at the moment, but perhaps it is possible for Gtalk)? Or the reasons video chat is not possible in MSN are the same for Gtalk?
- The following message appears in Gmail, when I am logged in from emesene simultaneously and choose "invisible" at login:

"You are not invisible because you're logged into Google Talk from another client, device, or location that doesn't support invisibility"

This means that emesene doesn't support invisibility, even if I check the "invisible" option at login? It is possible to support this feature?
- The button on the upper right corner of emesene to check email allows checking email automatically when I log in with my MSN account. With my gmail account in gtalk the autologin feature doesn't work (it opens the home page, but I have to enter my username and password). Is this the expected behavior from this function in gtalk?

Thanks for your attention

**Comment by c10ud** [comment]
1) not possible, we use a minimal xmpp library
2) no idea, probably related to 1
3) @4ndreaSt4gi 

please don't open issues for simple questions, the mailing lists should be just enough (and maybe reach a wider audience)

**Comment by astagi** [comment]
Hi,

sorry did in that way cause I really don't know what procedure Gmail uses to make the auto login.. it something similar to msn, but I need to investigate to find the exact procedure..
