### ISSUE TITLE
Not all contacts appear on-line, but shown when click on Search

### ISSUE THREAD

**Issue by the98** [emesene/emesene#1015]
I've made a screencast so you know exactly what's happening. You can download it from here: http://www.mediafire.com/?wcn8xgp4gxt4yyi

So this bug is when contacts are displayed in groups. I don't know why exactly the group is not shown when there are contacts on-line, but I think it happens when there is only one (or maybe two) contact(s) left in the group. If I were to close emesene and open it again, all on-line contacts, and groups, are shown.

As you can see in the screencast, if you click on the Search option, you can see all the groups that aren't shown, but they have on-line contacts though, and if you click on the arrow, you can see that the contact is on-line.

Thank you.

Regards.

**Comment by c10ud** [comment]
is this still happening with 2.12.3?

**Comment by Sbte** [comment]
This looks like a bug in a previous version of emesene that I already fixed. Assuming fixed by 4c2c7ec2986627d16354eec9dd2a22015c4be5fd
