### ISSUE TITLE
Blocked Contacts

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1017]
The conversation is locked, but you can get attention, you can create an icon and you can send a file.

But this should be blocked as well.

http://img638.imageshack.us/img638/6481/81530419.png

**Comment by Sbte** [comment]
Yes, we should block the toolbar with an exception to the unblock button I guess.

**Comment by lfottaviano** [comment]
i have pushed a fix for this, take a look.

**Comment by Sbte** [comment]
@lfottaviano I added some comments

**Comment by lfottaviano** [comment]
I have commited new changes. I agree with you. I had no time to check if toolbar condition could be deleted, this simplified things a lot.
And all suggestions have been considered. thx!

**Comment by zipatei** [comment]
Fixed but we still have to solve the problem of images. They have different color.

It would be nice, also add tooltip to the specific button lock / unlock and a new icon to unlock.

In order to be more intuitive.

**Comment by zipatei** [comment]
http://img99.imageshack.us/img99/3645/capturadeecraem20120225.png

**Comment by Sbte** [comment]
That's because of the self.info.set_sensitive(False). It's done on purpose, but I don't think it adds any value, so it can be removed.

**Comment by Sbte** [comment]
Actually, it does add value. When you get disconnected, you now can't click on the avatars, as that would result in a crash. So special cases for disconnection and blocking would have to be made to fix that.

**Comment by lfottaviano** [comment]
You say, adding something to the image or changing the alpha channel, to show that the contact has been blocked?

**Comment by Sbte** [comment]
No, @zipatei doesn't want the colors of the avatars to change when a contact has been blocked. Currently this does happen, because they are set to inactive. Maybe this can be fixed when a different widget is used for the avatars, but it would be easier to not set them to inactive when the contact is blocked, but do set it to inactive when the user is disconnected.

**Comment by zipatei** [comment]
exactly as @Sbte said.

**Comment by zipatei** [comment]
But the @lfottaviano idea's is also interesting. If possible put avatar in conversation and contact info with the lock icon when the contacts are locked.

**Comment by zipatei** [comment]
@lfottaviano do you has commit for block button?

**Comment by lfottaviano** [comment]
you say, the one I have shown you, that changes the block button to a green icon, when the contact is blocked?, I have this commited on another branch named "working", but I think that branch is outdated, and must be reviewed,  Will do it when i can

**Comment by zipatei** [comment]
Q: the one I have shown you, that changes the block button to a green icon, when the contact is blocked?
R: Yes. :)

**Comment by lfottaviano** [comment]
I will do it, I think tomorrow :)

**Comment by zipatei** [comment]
@lfottaviano 

Do you forget this? =))

**Comment by lfottaviano** [comment]
yes, and it looks like I have lost the branch where that commit was saved
