### ISSUE TITLE
Added "Show/Hide Avatars" button tooltips

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1018]
Is it possible to add the tooltip to the icon instead of the label?

https://github.com/emesene/emesene/pull/768

Thus it was possible to specify.

def on_toggle_avatar(self):
    '''hide or show the avatar bar'''
    if self.avatar_box_is_hidden:
        self.toolbar.toggle_avatar.set_stock_id(gtk.STOCK_GO_FORWARD)
        self.toolbar.toggle_avatar.set_tooltip_text(_('Hide avatar')) 
        self.info.show()
    else:
        self.toolbar.toggle_avatar.set_stock_id(gtk.STOCK_GO_BACK)
        self.toolbar.toggle_avatar.set_tooltip_text(_('Show avatar')) 
        self.info.hide()
    self.avatar_box_is_hidden = not self.avatar_box_is_hidden

**Comment by Sbte** [comment]
Could you make a pull request?

**Comment by zipatei** [comment]
I tried, but I have some problems in my repository ...

It is better to you to do it.

Sorry. :s
