### ISSUE TITLE
code cleanup

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1021]
Adding this so it don't get lost

<marianoguerra> someone wants to help emesene?
<marianoguerra> https://github.com/emesene/emesene/blob/master/emesene/e3/common/Signal.py#L109
<marianoguerra> change "== None" for "is None" there
<marianoguerra> another one
<marianoguerra> https://github.com/emesene/emesene/blob/master/emesene/e3/common/Signal.py#L126
<marianoguerra> change that try/except for an if using hasattr
<marianoguerra> exceptions are costly and are only for exceptional things
<marianoguerra> ➜  emesene git:(master) grep -R "== None" \* | wc -l
<marianoguerra> 21
<marianoguerra> you have 21 fixes like the first one I described
<marianoguerra> go!
<marianoguerra> another one like the second: https://github.com/emesene/emesene/blob/master/emesene/e3/common/OrderedDict.py#L30
<marianoguerra> another one: https://github.com/emesene/emesene/blob/master/emesene/e3/common/DBus.py#L86
<marianoguerra> just grep -R AttributeError \* and have fun
<marianoguerra> another one grep -R "except:" *
<marianoguerra> remove those, catch the specific exception
<pepeleproso> I'll add a new bug about this
<marianoguerra> and no, Exception isn't specific :)

**Comment by Sbte** [comment]
People should be careful with this. Some code in Signal.py depends on the `== None` and `== False` stuff. `is None` != `== None`.

**Comment by marianoguerra** [comment]
"== None" is the same as "is None"

"is None" is more idiomatic

about the == False you mean that you want False but not any other falsy value (http://docs.python.org/library/stdtypes.html#truth-value-testing) in that case it should be documented in a comment on that line. (I think you refer about checking that the result of the callback is False (but not any other falsy value), the only case I can think of is in Signal, the others should be replaced with the more idiomatic "if not value:"

thanks for reminding me of the special case :)

**Comment by jamesaxl** [comment]
could we close that ?

**Comment by Sbte** [comment]
@jamesaxl No, this is just a bug where people who want to fix some small things can get started. These are ongoing tasks

**Comment by jamesaxl** [comment]
i'll care about it after finish "the order by status when showing offline contacts"

**Comment by c10ud** [comment]
closing this
