### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by Pieeeeeee** [emesene/emesene#1023]
I'd like to report some things about the themes.
Running emesene 2.12.1 on Windows 7.
- the themes available for download are automatically loaded. That's quiet irritating when you just want to switch to an already downloaded theme. You have to wait until the downloadlist is loaded before you can proceed choosing another theme.
- Switching to another theme doesn't work very well. I have to close Emesene and open it again for changes to take effect, sometimes multiple times. One has to find out that himself, cause the program doesn't make a mention about that. It should say something like "emesene needs to restart for changes to take effect. Would you like to restart now? yes - no".
- There is no preview of the themes, so you have to download them all and apply them all to find out which one you like the most.
- The themes aren't tweakable (or I can't find it? Don't know in which folder the themes are stored)
- There's no clear difference between emesene connected to MSN and to Facebook. I have 2 instances of emesene running for both MSN and FB, but I can't tell the difference between the chatwindows.

**Comment by c10ud** [comment]
1) should be sort of fixed in 2.12.3, but i don't think you're changing themes everyday
2) one reboot should be enough, but still yes maybe that should be mentioned
3) no way to do that atm, and implementing it would be overkill
4) something like <configdir>/themes or something like that
5) good point, any idea? @sbte @pepeleproso

**Comment by Stiveknx** [comment]
For 3) a image preview is not enough?

1), it's that already fixed in 2.12.4? The themes seems to be downloaded here when I switch to that tab in preferences ...

**Comment by jstrese** [comment]
Is there a way to actually apply themes? I'm using 2.12.3 and I've selected a different theme and restarted multiple times but everything looks the same. I've tried selecting a theme and restarting with multiple themes and none of them apply. If they do apply.. well, then there's no visible differences :/

**Comment by Vistaus** [comment]
Conversation themes don't apply since a few days (running Git version with git pull every day). OS: Ubuntu 12.04 64-bit
Restarting also doesn't help.

**Comment by Sbte** [comment]
@Vistaus, works fine here using latest git. I tested it like this:

Open conversation
Type something
Check theme
Selected a different theme from Preferences->Themes->Adium themes
Close conversation
Open conversation
Type something
Check theme

**Comment by Vistaus** [comment]
That's exactly what I did and what used to work before the last few revisions...
