### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_pointer'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1026]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Tooltips.py", line 163, in show_tooltip
    x, y = self.computePosition(origCoords, view.window)
  File "/home/andre/emesene/emesene/gui/gtkui/Tooltips.py", line 184, in computePosition
    currentY = viewWindow.get_pointer()[1]
AttributeError: 'NoneType' object has no attribute 'get_pointer'

Reproduce error:
1. Use broken profile
2. Login in emesene
3. Click yes to correct profile

**Comment by Sbte** [comment]
I can't reproduce this.

**Comment by zipatei** [comment]
Sorry, but i fix profile this account when this appear.

In other accounts with brokens profiles, but #1027

But, this onl unique when appear popup to fix profile. Others not appear.

**Comment by zipatei** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=786456
