### ISSUE TITLE
Bug with avatar

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1031]
Reproduced:
1. Open avatar chooser
2. Contacts Avatar
3. Remove all
4. Close avatar chooser.
5. Drag mouse to contact list.

Tooltips appear without avatar.

**Comment by c10ud** [comment]
i guess that happens because removing all you sort of cleaned the
cache, so the avatars ain't available anymore

2012/2/25 zipatei
reply@reply.github.com:

**Comment by c10ud** [comment]
aka not an issue
