### ISSUE TITLE
Strange thing

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1037]
http://imageshack.us/photo/my-images/718/capturadeecraem20120225.png

Reproduced:
1. Check updates
2. Open conversation

Result: Contact is blinking??? Not supposed.

**Comment by Sbte** [comment]
Maybe that's because the update window is modal, but is in a different thread than the main window, so it doesn't keep focus? If so them I'm not sure it can be fixed.

**Comment by zipatei** [comment]
But you can not condition the warning only to events received? It is in this case there is no event conversation.

**Comment by Sbte** [comment]
We can't fix those bugs faster than you report them :(

Anyhow, thanks for reporting all this!

**Comment by zipatei** [comment]
You have nothing to thank.

I love the Emesene. And I like to discover all the errors. Correct is that it is more complicated for me. :)
