### ISSUE TITLE
"Show/Hide Avatars" button 2 bugs

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1038]
A) Emesene not remember the option to hide avatar.

Reproduced:
1. Open Conversation
2. Hide Avatar
3. Close Conversation
4. Open conversation

B) icon changed.

Reproduced:
1. Open Conversation
2. Hide Avatar
3. Open the same conversation in contact list (without close)

**Comment by Sbte** [comment]
self.session.config.b_show_info should be used.

**Comment by zipatei** [comment]
we have to add another condition, when the avatars are to the left.

http://imageshack.us/photo/my-images/856/capturadeecraem20120226.png

**Comment by lfottaviano** [comment]
Here are two things @zipatei requested.
- save option state 
- remain show/hide avatar button sensitive when contact is blocked.

https://github.com/lfottaviano/emesene/commit/9041d3fd2e712e055c8b692563a9c1d70d74f7a9
