### ISSUE TITLE
Adium conversation theme broken

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1039]
Reproduced:
1. Open conversation
2. Say something
3. clear conversation
4. say something

**Comment by Sbte** [comment]
It all works fine for me. Do you have a screenshot or something?

**Comment by zipatei** [comment]
http://imageshack.us/photo/my-images/804/capturadeecraem20120226.png
1. I wrote something.
2. clean conversation.
3. wrote again.. 

The result is the first phrase in image.

**Comment by Sbte** [comment]
Ah, it only happens when you clear it through RMB->Clear. The normal button works fine.
