### ISSUE TITLE
Emesene has no icon on Ubuntu Messaging Menu

### ISSUE THREAD

**Issue by ricardofcf** [emesene/emesene#104]
Pretty much what the title says. It may be a theme related bug, though; i'm using Elementary.

Screenshot:
http://img651.imageshack.us/img651/9886/workspace1002n.png

**Comment by EibrielInv** [comment]
That is because you have not Emesene installed.
Installing Emesene copies the logo to /usr/share/pixmaps/emesene.png

then, it shows..

Regards!!

**Comment by c10ud** [comment]
i submitted a patch for indicator-application, i guess messaging menu does not support loading pics from a custom path yet... -_-

**Comment by c10ud** [comment]
ok, it can be done with messaging menu:

http://bazaar.launchpad.net/~indicator-applet-developers/libindicate/trunk/annotate/head%3A/examples/im-client.py

will do

**Comment by c10ud** [comment]
seems like this sets indicator-client icon, not servers'... mmm

**Comment by c10ud** [comment]
closing this issue, you must have installed emesene from some system package in order to have the icon, it's not possible to change it atm. sorry for that
