### ISSUE TITLE
"Authentication failure" - make translatable.

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1043]
http://imageshack.us/photo/my-images/109/capturadeecraem20120226.png

"Authentication failure" - make translatable.

**Comment by lfottaviano** [comment]
This should help for this, don't know If it is necessary by this side to do something else. Or If I am missing something.

https://github.com/lfottaviano/emesene/commit/ea3bbba8db3ab50559f4c7e89ff82636580a77f2
