### ISSUE TITLE
Small toolbar - clear button

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1045]
Clean conversation (this could be the broom?)

**Comment by lfottaviano** [comment]
Isn't the broom?

**Comment by zipatei** [comment]
here not...screenshot:

http://imageshack.us/photo/my-images/52/capturadeecraem20120226.png

**Comment by lfottaviano** [comment]
Looks like thats the correspondinng icon for your current gnome icon theme

**Comment by pepeleproso** [comment]
we just pick the icon from your system's icon theme. You could change it by adding "clean-chat.png" into your emesene's image theme folder.
