### ISSUE TITLE
Set picture in facebook account

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1046]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 102, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 183, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 439, in _handle_action_set_picture
    self.my_avatars.insert_raw(avatar_data)
  File "/home/andre/emesene/emesene/e3/cache/AvatarCache.py", line 64, in insert_raw
    position = item.tell()
AttributeError: 'str' object has no attribute 'tell'

**Comment by zipatei** [comment]
http://imageshack.us/photo/my-images/849/capturadeecraem20120226.png

in empathy, automatically downloads the profile photo.

**Comment by pepeleproso** [comment]
original bug is not fixed, I have no idea on how to solve it

**Comment by zipatei** [comment]
@pepeleproso On my computer, it not took the photo of facebook.

**Comment by c10ud** [comment]
try making a StringIO out of avatar_data, it should work (iirc we do
that in papylib)

2012/3/6 jose Rostagno
reply@reply.github.com:

**Comment by pepeleproso** [comment]
@zipatei you need to enable it in preferences
@c10ud will try it, but tomorow

**Comment by zipatei** [comment]
@pepeleproso sorry. had not seen. works good. :)

**Comment by zipatei** [comment]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 791, in on_picture_change_succeed
    shutil.copy(path, last_avatar_path)
  File "/usr/lib/python2.7/shutil.py", line 117, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] Ficheiro ou directoria inexistente: '/home/andre/.config/emesene2/chat.facebook.com/sepoljoao@chat.facebook.com/sepoljoao@chat.facebook.com/avatars/32336235643930383431373334633531393737313830663732636234646434313336336466343033'

**Comment by zipatei** [comment]
@pepeleproso not fixed yet...

**Comment by pepeleproso** [comment]
please test again

**Comment by zipatei** [comment]
Now no errors. :)

But there are some problems here. For even if we change the avatar, he passed back to the previous few seconds. If there is no possibility to change the profile picture, perhaps the best is to create sensitivity as the toolbar conversation.

In avatar chooser, you can resize the image and not cut as happens now?

Another thing, the update of the avatar and the message should occur a bit later. Sometimes we're still writing the message (status message) and it automatically updates.

**Comment by pepeleproso** [comment]
I guess facebook didn't accept the new avatar so we go back to the old one.
Maybe adding sensitivity is the way to go and only allow avatar with the new integration.

"In avatar chooser, you can resize the image and not cut as happens now?" I didn't catch this one

**Comment by zipatei** [comment]
Example:

http://img193.imageshack.us/img193/1628/screenshotfrom201203072.png

Resize is possible?

**Comment by pepeleproso** [comment]
about this "Another thing, the update of the avatar and the message should occur a bit later. Sometimes we're still writing the message (status message) and it automatically updates."
I commit a patch to improve this a bit. Before we update picture and status every X seconds without checking if these have been changed or not

**Comment by pepeleproso** [comment]
I deactivate setting avatar on facebook accounts because that isn't supported by xmpp. Maybe we can implement it with facebook API later.

**Comment by zipatei** [comment]
But now we must apply some more work, I think.

Disable avatar choose, as well as their tooltips.

http://imageshack.us/photo/my-images/851/capturadetelade20120318.png
http://imageshack.us/photo/my-images/196/capturadetelade20120318.png

and I want to congratulate the great work you're doing.
