### ISSUE TITLE
'NoneType' object is not iterable  

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1047]
Reproduced:

1) live profile in msn
2) remove image and save.
3) open emesene

Result: Emesene not recognize new "none" avatar and this errors:

[03:51:05 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable

I think this #471

**Comment by c10ud** [comment]
cannot reproduce, must be something else or it's missing some step

**Comment by zipatei** [comment]
I'll send you access to my account for testing.
