### ISSUE TITLE
Audium themes not working?

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#1048]
Alright, I'm not sure what's the reason of this, but audium themes stopped working all of a sudden, now the conversation layout is of the kind
Name:
  [hh:mm:ss] message
And I can't seem to be able to change. Funny thing is, no errors are printed on the shell.

**Comment by Soulsuke** [comment]
Please, any help? It sucks being stuck with non-adium output... I've tried upgrading the themes, deleting all preferences and such, but nothing changed

**Comment by Mastergatto** [comment]
I have the same problem, and i didn't manage to fix this bug. Please fix it!

**Comment by pepeleproso** [comment]
tomorow I will have some free time to dig into this, so please be pacient

**Comment by Sbte** [comment]
Can one of you do a regression test? To see if it's an emesene problem? It could also be that your OS updated their webkit packages which caused this (for instance).

**Comment by lfottaviano** [comment]
This is working for me in the last revision. Is this what you are talking about?
http://img441.imageshack.us/img441/6960/pantallazode20120303225.png

**Comment by c10ud** [comment]
how is this new cool thing about hashtags? #gentooism

please, tell us your os and version

**Comment by Soulsuke** [comment]
Sorry for the delay... I guess this could be a webkit issue after all. As for myself, i'm running Debian Sid amd64, all the webkit packages are shown at version 1.6.3-1... So should I try to install the older versions, or is there a way to work around this issue??

**Comment by c10ud** [comment]
try opening a terminal, run and tell us the output of:

python -c "import webkit"

**Comment by Soulsuke** [comment]
Sorry for the long delay, i actually thought this bug's been closed ( a friend made me notice it isn't :p ), somehow the python-webkit package got removed for unknown reasons during an update, which caused the problem
