### ISSUE TITLE
it connects but doesn't show the contact list.

### ISSUE THREAD

**Issue by lucascastro** [emesene/emesene#1049]
Some friends asked me about that, 
and I was gonna check. 
It happens the emesene connects but doesn't show the contact list.
Sometimes emesene erase that there is no image configured on the msn profile,
and others it erase that is the same image of last avatar and just freeze and 
I noticed when change the image the contact list is loaded.

**Comment by lucascastro** [comment]
The error when there is no image. 
ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable

**Comment by zipatei** [comment]
The same issue #1047

**Comment by c10ud** [comment]
see #1047 this should now prompt the user to fix his/her profile and prevent this from happening
