### ISSUE TITLE
[box-email] number of incoming email does not match

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1052]
The number displayed in the little button with the "envelope" does not correspond to reality ... said to have 8 incoming email, then vision the gate and said that I always 8:

http://img6.imagebanana.com/img/6oo6xulo/tmpzf.jpg

does not refresh automatically every few seconds? because just restart emesene and refreshes the box

**Comment by pepeleproso** [comment]
mail check happen every x seconds. maybe something screws up? did that happen again?

**Comment by KinG-InFeT** [comment]
I could not tell what might happen, but I simply restart emesene and is back to normal ... maybe a problem with sessions?

**Comment by pepeleproso** [comment]
yeah I guess maybe a server caching error

**Comment by KinG-InFeT** [comment]
then closes for bad bugs.
