### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1054]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Window.py", line 169, in _on_delete_event
    return self.cb_on_close(self.content)
  File "/home/andre/emesene/emesene/emesene.py", line 751, in _on_conversation_window_close
    self.session.conversation_managers.remove(conv_manager)
ValueError: list.remove(x): x not in list

I don't know how.

**Comment by c10ud** [comment]
@Sbte

**Comment by Sbte** [comment]
I have no clue. This should be impossible. But we could add a check for this anyway.

**Comment by c10ud** [comment]
there was no conversation manager but still the window had something. mh

**Comment by c10ud** [comment]
assuming "fixed" due to the haxes sbte did lately, but if issue persists feel free to reopen

**Comment by Sbte** [comment]
I didn't fix anything

**Comment by c10ud** [comment]
git log v2.12.1 v2.12.3 | grep conversation

**Comment by Sbte** [comment]
That's where I added this. I didn't actually fix it...

**Comment by zipatei** [comment]
close this issue... if appear again, reopen this. ;)

**Comment by zipatei** [comment]
^CTraceback (most recent call last):
  File "/home/andre/emesene/emesene/emesene.py", line 338, in close_session
    self._on_conversation_window_close(conv_manager)
  File "/home/andre/emesene/emesene/emesene.py", line 766, in _on_conversation_window_close
    self.session.conversation_managers.remove(conv_manager)
ValueError: list.remove(x): x not in list

What i did:

1) Emesene desconnect
2) Reconnect again
3) Click cancel
4) And then I clicked the ctrl c in console. (WAS NOT INTENTIONAL)

Error appear

**Comment by Sbte** [comment]
Ok, good. So this happens when you reconnect with conversation windows open. I thought we handled that though:

https://github.com/emesene/emesene/blob/master/emesene/emesene.py#L311

**Comment by c10ud** [comment]
this traceback is a consequence of interrupting emesene with Ctrl+C so it's invalid

**Comment by Sbte** [comment]
I don't think so, because we intercept Ctrl+C. This can't be caused by some race condition because we call everything from close_session.

**Comment by c10ud** [comment]
ctrl+c is catched but closing the program can be tricky
2012/4/19 Sven reply@reply.github.com:

**Comment by Sbte** [comment]
@zipatei please see if you can reproduce this without Ctrl+c

**Comment by zipatei** [comment]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Window.py", line 176, in _on_delete_event
    return self.cb_on_close(self.content)
  File "/home/andre/emesene/emesene/emesene.py", line 779, in _on_conversation_window_close
    self.session.conversation_managers.remove(conv_manager)
ValueError: list.remove(x): x not in list

Happened for me now again:

1) Open Conversation
2) Click in add contact to conversation
3) emesene disconnect
