### ISSUE TITLE
** WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1056]
*\* WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

Error with ubuntu 12.04

**Comment by Sbte** [comment]
Apparently this is a bug in pygobject:

https://bugzilla.redhat.com/show_bug.cgi?id=790053
