### ISSUE TITLE
Show/Hide avatar bugs

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1059]
A) Problems with icon

Reproduced:

1) Open conversation
2) Hide Avatar
3) Close Conversation
4) Open conversation

Icon is wrong.

B) Avatar in left side.

Icon should be in reverse for right side.

**Comment by lfottaviano** [comment]
I have something for this, will commit tomorrow when I can.

**Comment by lfottaviano** [comment]
when you can, take a look,  i have made some tests and no problem.
https://github.com/lfottaviano/emesene/commit/b22b3cdadc4a8487669536de01d8a416c5d5737b#L1L71

**Comment by zipatei** [comment]
Good job. :)

But there is one more thing:

Reproduced:
1) Open conversation
2) Hide Avatar
3) Open another conversation
4) Show Avatar in this new conversation
5) View first conversation

The icon is wrong.

**Comment by lfottaviano** [comment]
Of course this also must happen If you change this options from Preferences while a conversation is already opened. There must be something like a signal to do that.

**Comment by zipatei** [comment]
But for me, this is great. 

thanks
