### ISSUE TITLE
doesn't show groups with all contatcs offline

### ISSUE THREAD

**Issue by DragaO** [emesene/emesene#106]
if a group have all contacts offline, the group isn't showed in the main window. even if the "show offline contacts" is checked.

but, if i check the "show empty groups" plus "show offline contacts", then the group appears

**Comment by 4javier** [comment]
Same problem here. But if I flag the "Group offline contacts" option, the group appears.

**Comment by c10ud** [comment]
"show empty groups" + "show offline contacts" now works

**Comment by DragaO** [comment]
updated a few seconds ago, and doesn't work for me

if i check "show offline contacts", and has nobody of the group online, the group still doesn't appear

how to reproduce:

go to emesene1
1. create a new test group
2. check "contacts > show > offline contacts" and uncheck "empty groups"
3. the group doesn't appear
4. now, copy/move/add a offline contact to this group
5. the group appears

now, go to emesene2:
1. check "options > show > offline contacts" and uncheck "empty groups" (like did in emesene1)
2. the group doesn't appear

i don't know if it's correct treat a group with all contacts as an empty group, but, the fact is that this is different from what happens in emesene1

excuse me for insisting on it :)
