### ISSUE TITLE
Viewport argument value "320;" for key "width" was truncated to its numeric prefix.

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1063]
*\* Message: console message: http://toworktogether.eu/emesenefb.html#access_token=AAAETMnXX46MBAAAKuNenbgbuFSf5GZCvsBssNFkueRkZCxv9e7qbmWlqyc4jON00a9ZB1ZBFx1CD1mjNV9pi2qivPd2rn6ZAaPWc5ybM1iwZDZD&expires_in=0&code=AQCPFhW9BJXJjSIlepS2GUnTUlgbFenlwFpQon3tnHhlSDDdPFdq9HTBhpT4QvmTLnq7LLDBGOa2XFFBuzU0BOxOyLeB4TmPadKJpBwDh7I_aUe9YcqA7C06ld5u46Aste006UwM1_5vZW3eXflmNq1pOFTVsCetyt0BKWN-JFOQJ_pheRH3Hy_DWPOVnNRjwcg @4: Viewport argument value "320;" for key "width" was truncated to its numeric prefix.

**Comment by c10ud** [comment]
@pepeleproso

2012/3/6 zipatei
reply@reply.github.com:

**Comment by pepeleproso** [comment]
viewing html source code you found 
< meta name="viewport" content="width=320; user-scalable=no" />

so this is an html issue. @4ndreaSt4gi you hosted that page I can't access it

**Comment by c10ud** [comment]
also, if it's a simple html webpage it's better hosting here on github so we can access it through git

**Comment by pepeleproso** [comment]
now the page is hosted in emesene.github.com/emesene but I get this error

{
   "error": {
      "message": "Invalid redirect_uri: This url is not allowed by application config.",
      "type": "OAuthException",
      "code": 191
   }
}

basically we need to autorize the new url in the facebook app but I don't have access

**Comment by c10ud** [comment]
@4ndreaSt4gi has it, i guess?

**Comment by astagi** [comment]
Sorry for the late guys... try now ^^ I changed the redirect page in emesene.github.com/emesene

**Comment by zipatei** [comment]
@pepeleproso do you see my email for this page?

**Comment by pepeleproso** [comment]
I uploaded the new page thanks for the fix, github took a while before update it
