### ISSUE TITLE
gtkui init.py error

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1064]
I started emesene from terminal and after my login onto the MSN network I had a terminal window with plenty of errors.

/usr/share/emesene/emesene/gui/gtkui/**init**.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[14:54:09 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 48 c8 38 7f 00 00 00 00 00 00 00 00
50 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
59 76 61 4d a7 20 79 05 50 01 00 00 00 00 00 00
Cannot connect to server socket err = Bestand of map bestaat niet
Cannot connect to server socket
jack server is not running or cannot be started
Cannot connect to server socket err = Bestand of map bestaat niet
Cannot connect to server socket
jack server is not running or cannot be started
[14:54:44 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6}

**Comment by c10ud** [comment]
they're "normal" except from
 Cannot connect to server socket err = Bestand of map bestaat niet
 Cannot connect to server socket
 jack server is not running or cannot be started

but i think they depend on your system configuration, i've never seen those

2012/3/7 kingsmile
reply@reply.github.com:

**Comment by Smile4ever** [comment]
Bestand of map bestaat niet = Directory or file doesn't exist.

Why there is a parse error?

---- Aan Wed, 07 Mar 2012 15:16:43 +0100 Riccardo &lt;reply@reply.github.com&gt; schreef ---- 

they're "normal" except from 
 Cannot connect to server socket err = Bestand of map bestaat niet 
 Cannot connect to server socket 
 jack server is not running or cannot be started 

but i think they depend on your system configuration, i've never seen those 

2012/3/7 kingsmile 
&lt;reply@reply.github.com&gt;: 
&gt; I started emesene from terminal and after my login onto the MSN network I had a terminal window with plenty of errors. 
&gt; 
&gt; 
&gt; /usr/share/emesene/emesene/gui/gtkui/**init**.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed 
&gt;  gtk.main() 
&gt; [14:54:09 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob 
&gt; 00 00 00 00 48 c8 38 7f 00 00 00 00 00 00 00 00 
&gt; 50 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00 
&gt; 59 76 61 4d a7 20 79 05 50 01 00 00 00 00 00 00 
&gt; Cannot connect to server socket err = Bestand of map bestaat niet 
&gt; Cannot connect to server socket 
&gt; jack server is not running or cannot be started 
&gt; Cannot connect to server socket err = Bestand of map bestaat niet 
&gt; Cannot connect to server socket 
&gt; jack server is not running or cannot be started 
&gt; [14:54:44 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6} 
&gt; 
&gt; --- 
&gt; Reply to this email directly or view it on GitHub: 
&gt; https://github.com/emesene/emesene/issues/1064 

---

**Comment by c10ud** [comment]
parse error because one of your buddies is using a client which sends malformed p2p data, but you can safely ignore that

as for the other one, i guess it's an issue with your sound system, nothing related to emesene

**Comment by Smile4ever** [comment]
Well I'm using PulseAudio. Underlying technology is not JACK but ALSA. Most Linux distributions use ALSA so why it's default on Jack?

---- Aan Wed, 07 Mar 2012 15:57:25 +0100 Riccardo&lt;reply@reply.github.com&gt; schreef ---- 

parse error because one of your buddies is using a client which sends malformed p2p data, but you can safely ignore that 

as for the other one, i guess it's an issue with your sound system, nothing related to emesene 

---

**Comment by c10ud** [comment]
we don't mess with audio, we just ask gstreamer to play sounds, if
any. so my guess there's some misconfig regarding
gstreamer-pa-alsa-jack in your system

2012/3/7 kingsmile
reply@reply.github.com:

**Comment by Smile4ever** [comment]
Ok, could be. Good afternoon.

---- Aan Wed, 07 Mar 2012 16:19:24 +0100 Riccardo&lt;reply@reply.github.com&gt; schreef ---- 

we don't mess with audio, we just ask gstreamer to play sounds, if 
any. so my guess there's some misconfig regarding 
gstreamer-pa-alsa-jack in your system 

2012/3/7 kingsmile 
&lt;reply@reply.github.com&gt;: 
&gt; Well I'm using PulseAudio. Underlying technology is not JACK but ALSA. Most Linux distributions use ALSA so why it's default on Jack? 
&gt; 
&gt; ---- Aan Wed, 07 Mar 2012 15:57:25 +0100 Riccardo&amp;lt;reply@reply.github.com&amp;gt; schreef ---- 
&gt; 
&gt; 
&gt; parse error because one of your buddies is using a client which sends malformed p2p data, but you can safely ignore that 
&gt; 
&gt; as for the other one, i guess it's an issue with your sound system, nothing related to emesene 
&gt; 
&gt; --- 
&gt; Reply to this email directly or view it on GitHub: 
&gt; https://github.com/emesene/emesene/issues/1064#issuecomment-4369355 
&gt; 
&gt; --- 
&gt; Reply to this email directly or view it on GitHub: 
&gt; https://github.com/emesene/emesene/issues/1064#issuecomment-4369411 

---

**Comment by Sbte** [comment]
I see that error too on the Debian systems at my university, but I haven't seen it at any other systems, so it's not our fault at least.
