### ISSUE TITLE
Crash when sending emoticon. 

### ISSUE THREAD

**Issue by Kiluleib** [emesene/emesene#1065]
Emesene 2.12.1, OSX 10.7.3, MBP 5,5

Python quit unexpectedly while using the libgdk-quartz-2.0.0.dylib plugin

Process:         Python [39307]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      org.python.python
Version:         2.7.1 (2.7.1)
Build Info:      python-56000000000000~121
Code Type:       X86-64 (Native)
Parent Process:  sh [39298]

PlugIn Path:       /Applications/emesene.app/Contents/Resources/gtk/inst/lib/libgdk-quartz-2.0.0.dylib
PlugIn Identifier: libgdk-quartz-2.0.0.dylib
PlugIn Version:    2401.0.0 (compatibility 2401.0.0)

Date/Time:       2012-03-07 22:35:57.854 +0200
OS Version:      Mac OS X 10.7.3 (11D50)
Report Version:  9

Interval Since Last Report:          158108 sec
Crashes Since Last Report:           2
Per-App Interval Since Last Report:  170 sec
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      E208BAFD-07C6-482F-8D5C-2D93941E2F82

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

**Comment by Sbte** [comment]
That's not very useful. Please provide your emesene version, your os and the command line output.

**Comment by Kiluleib** [comment]
Yeah, I'm sorry, I accidentally posted that before adding the crash info.

**Comment by c10ud** [comment]
i don't think we can do much, but i'll ping @joshf

**Comment by joshf** [comment]
Yeah im aware of this one. PyGTK issue on Lion, we'll have to wait for a new PyGTK build for Lion. I had a go but building it but it is a nightmare.  Perhaps detect a lion system and disable the emotion selector accordingly. Typing the symbols still works though.

**Comment by joshf** [comment]
If its any use

./emesene -vvv

http://pastebin.com/KnFCAQ4s

**Comment by Kiluleib** [comment]
OK, good to know you're already aware of this. 

Here's a -vvv. I hope this is the correct stuff, I'm pretty new to the Mac terminal business.

http://pastebin.com/ANR6Ynks

**Comment by joshf** [comment]
Something like

```
     import platform

      if not platform.release() == '11.3.0':
            self.add(self.emotes)
```

May be helpful and stop the emotion selector showing on Lion. Should still show on Snow Leopard.
