### ISSUE TITLE
Avatar problem

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1067]
Avatar contact not appear in emesene.

See:

http://imageshack.us/photo/my-images/856/screenshotfrom201203072.png/

**Comment by c10ud** [comment]
the guy is probably using a client which does bad p2p, while the
webclient uses the profile picture

2012/3/8 zipatei
reply@reply.github.com:

**Comment by pepeleproso** [comment]
Closed as per Cloud comment not a bug
