### ISSUE TITLE
"dd MMM yyyy" raw format shown in conversation

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1068]
http://imageshack.us/photo/my-images/441/screenshotat20120308154.png/

When the mouse move to the time field, the pop-up(?) message shown is the raw format. There is no update in preference window and the git info is on the right window.

**Comment by zipatei** [comment]
@pepeleproso not fixed yet for offline messages... see example:

http://imageshack.us/photo/my-images/403/capturadetelade20120317.png
