### ISSUE TITLE
[DEBUG] traceback on windows 2000 SP4

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1069]
``` python
No handlers could be found for logger "emesene.e3.common.DBus"
Traceback (most recent call last):
  File "emesene.py", line 833, in <module>
  File "emesene.py", line 830, in main
  File "gui\gtkui\__init__.pyo", line 29, in gtk_main

  File "gtk\__init__.pyo", line 40, in <module>

  File "gtk\_gtk.pyo", line 12, in <module>

  File "gtk\_gtk.pyo", line 10, in __load

ImportError: DLL load failed: Impossibile trovare la procedura specificata.
```

run on windows 2000 SP4 OS

emesene version: https://github.com/downloads/emesene/emesene/emesene-2.12.1-portable%20%20(2012-01-05).exe
: 2012-01-05 portable version

**Comment by arielj** [comment]
It looks like a gtk error, can you try running emesene from source? maybe
we are using a gtk version that's not compatible with Windows 2000

2012/3/12 Vincenzo <
reply@reply.github.com

**Comment by KinG-InFeT** [comment]
how you can use git version emesene on windows in debug mode? you may explain it briefly?

**Comment by arielj** [comment]
check here https://github.com/emesene/emesene/wiki/Windows-(New)

2012/3/13 Vincenzo <
reply@reply.github.com

**Comment by KinG-InFeT** [comment]
the link for Win32 OpenSSL v1.0.0d NOT correct, output 404 not found error
change this link : http://www.slproweb.com/download/Win32OpenSSL-1_0_0d.exe
change in
http://downloads.sourceforge.net/project/openssl1d/Win32OpenSSL-1_0_0d.exe?r=http%3A%2F%2Fen.sourceforge.jp%2Fprojects%2Fsfnet_openssl1d%2Fdownloads%2FWin32OpenSSL-1_0_0d.exe%2F&ts=1331799167&use_mirror=freefr

**Comment by KinG-InFeT** [comment]
the link of WebKitGTK+ 1.2.7 NOT correct
Change this link http://dl.dropbox.com/u/2554170/webkitgtk-1.2.7.7z

change in http://webkitgtk.org/webkit-1.2.7.tar.gz

**Comment by KinG-InFeT** [comment]
the link of PyWebKitGtk 1.1.8 NOT correct

change this link: http://dl.dropbox.com/u/2554170/pywebkitgtk-1.1.8.7z

change in: http://pywebkitgtk.googlecode.com/files/pywebkitgtk-1.1.8.tar.bz2

**Comment by KinG-InFeT** [comment]
the link of MSysGit 1.7.6 NOT correct

change this link: http://code.google.com/p/msysgit/downloads/detail?name=Git-1.7.6-preview20110708.exe&can=2&q=

change in: http://code.google.com/p/msysgit/downloads/detail?name=msysGit-fullinstall-1.7.9-preview20120201.exe&can=2&q=

NB: the link provided in the guide, is a normal version of GIT and not msysgit which was also upgraded from version 1.7.6 to 1.7.9 which fixes bugs remarkable stability.

**Comment by KinG-InFeT** [comment]
out this error with last git version

```
No handlers could be found for logger "emesene.e3.common.DBus"
Errors occurred while importing jabber backend: No module named xmpp
Traceback (most recent call last):
  File "emesene", line 34, in <module>
    emesene.main()
  File "C:\emesene\emesene\emesene\emesene.py", line 831, in main
    main_method(Controller)
  File "C:\emesene\emesene\emesene\gui\gtkui\__init__.py", line 29, in gtk_main
import gtk
  File "C:\Python26\lib\site-packages\gtk-2.0\gtk\__init__.py", line 40, in <moduule>
    from gtk import _gtk
ImportError: DLL load failed: Impossibile trovare la procedura specificata.
```

**Comment by KinG-InFeT** [comment]
@Sbte @marianoguerra help in this issue

**Comment by arielj** [comment]
check this http://faq.pygtk.org/index.py?req=show&file=faq21.001.htp

if you can't run that simple example code, you have something missing on your pygtk/gtk installation (like... do you have gtk's bin folder in your PATH environment variable?)

**Comment by KinG-InFeT** [comment]
return this traceback

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import gtk
  File "C:\Python26\lib\site-packages\gtk-2.0\gtk\__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: DLL load failed: Impossibile trovare la procedura specificata.
```

i have added only:  ;C:\Python26  As the guide is described.

My complete path list is: C:\ORANT\bin;c:\ORA_9i\jdk\jre\bin\classic;c:\ORA_9i\jdk\jre\bin;c:\ORA_9i\bin;c:\ORA_9i\jlib;c:\orawf\bin;D:\ora_6i\bin;c:\ORA91\bin;C:\ora6i\bin;C:\ora26i\bin;D:\ORAWF\bin;C:\Programmi\Oracle\jre\1.1.8\bin;c:\ORA91\jdk\jre\bin\classic;c:\ORA91\jdk\jre\bin;c:\ORA91\jlib;C:\Programmi\Oracle\jre\1.3.1\bin;C:\WINNT\system32;C:\WINNT;C:\WINNT\System32\Wbem;C:\ORANT\jdk\bin;C:\ora6i\jdk\bin;C:\Programmi\TortoiseSVN\bin;C:\Python26

**Comment by Sbte** [comment]
Not an emesene bug

**Comment by KinG-InFeT** [comment]
even if it is a bug in emesene, emesene does not mean that on a windows 2000 SP4 does not work and you should fix it even if not part of the code emesene, but still includes its dependencies are not compatible.

**Comment by arielj** [comment]
if the people behind pygtk\gtk doesn't provide packages compatible with windows 2000 sp4 we can do nothing about it, if that simple example does not work then it means it's not our fault and we can't fix it until they fix it first...

maybe you can try with different pygtk\gtk version and see if something works with windows 2000 sp4

for now we can only "fix it" saying that emesene does not work on windows 2000 due to pygtk\gtk bugs that we can't fix

**Comment by Sbte** [comment]
Windows 2000 reached end of life about two years ago, so even if this was our problem, I don't know why we should support it.

**Comment by KinG-InFeT** [comment]
I understand, thanks for the tip but still those little else to solve problems for the links to download packages from the wiki
