### ISSUE TITLE
(request) Add new emesene instance in the Unity Launcher's Quicklist

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1070]
Add new emesene instance in the Unity Launcher's Quicklist

https://wiki.ubuntu.com/Unity/LauncherAPI

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/commit/31ed5d914ae5dc49d75fb4505a558ee50129837f

**Comment by zipatei** [comment]
Sorry... not have the emesene installed, and was tested only with the console.
