### ISSUE TITLE
Emesene and Totem im-status plugin

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1072]
You can emesene work with this plugin Totem? It seems that in Emesene does not work.

**Comment by pepeleproso** [comment]
I add a new plugin to do this.
https://github.com/emesene/emesene-supported-plugins/commit/e11137002a8a9c971e570c2376d4ab624cc33f87

**Comment by zipatei** [comment]
@pepeleproso here not worked with totem. I open totem and play a video, but emesene online.

**Comment by pepeleproso** [comment]
Because the totem plugin only set busy status when it's in fullscreen mode
