### ISSUE TITLE
Link does not correct the wiki page [Windows (new)]

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1075]
In the wiki page: https://github.com/emesene/emesene/wiki/Windows-% 28New% 29

The section on "Required" are the following links to update:

1) the link for Win32 OpenSSL v1.0.0d NOT correct, output 404 not found error
change this link : http://www.slproweb.com/download/Win32OpenSSL-1_0_0d.exe
change in
http://downloads.sourceforge.net/project/openssl1d/Win32OpenSSL-1_0_0d.exe?r=http%3A%2F%2Fen.sourceforge.jp%2Fprojects%2Fsfnet_openssl1d%2Fdownloads%2FWin32OpenSSL-1_0_0d.exe%2F&ts=1331799167&use_mirror=freefr

2) the link of WebKitGTK+ 1.2.7 NOT correct
Change this link http://dl.dropbox.com/u/2554170/webkitgtk-1.2.7.7z

change in http://webkitgtk.org/webkit-1.2.7.tar.gz

3)the link of PyWebKitGtk 1.1.8 NOT correct

change this link: http://dl.dropbox.com/u/2554170/pywebkitgtk-1.1.8.7z

change in: http://pywebkitgtk.googlecode.com/files/pywebkitgtk-1.1.8.tar.bz2

4) the link of MSysGit 1.7.6 NOT correct

change this link: http://code.google.com/p/msysgit/downloads/detail?name=Git-1.7.6-preview20110708.exe&can=2&q=

change in: http://code.google.com/p/msysgit/downloads/detail?name=msysGit-fullinstall-1.7.9-preview20120201.exe&can=2&q=

NB: the link provided in the guide, is a normal version of GIT and not msysgit which was also upgraded from version 1.7.6 to 1.7.9 which fixes bugs remarkable stability.

PS: links have already been expressed in this discussion: https://github.com/emesene/emesene/issues/1069

**Comment by Sbte** [comment]
We need prebuilt pywebkitgtk and webkitgtk packages. So the source tarballs won't work...

@marianoguerra @arielj

**Comment by c10ud** [comment]
ain't wiki editable because, well, it's a wiki though?

2012/3/16 Vincenzo
reply@reply.github.com:

**Comment by KinG-InFeT** [comment]
I remember that with these packages installed successfully all on a windows 2000 SP4 and then should be fine

**Comment by Sbte** [comment]
Eh, you reported that emesene didn't start. How is that successful?

**Comment by KinG-InFeT** [comment]
emesene was started with an error due to non-compatibility of the GTK + library

**Comment by Sbte** [comment]
Yes, so you can't say if it worked or not. I suppose it didn't, because those source tarballs need to be compiled properly. Otherwise emesene will still load, but without adium themes.

**Comment by KinG-InFeT** [comment]
so what to do?

**Comment by Sbte** [comment]
Wait for someone to properly compile those libraries and host them here on github.

**Comment by KinG-InFeT** [comment]
but the ones I posted above should be the same packages that you had before the wiki page ... I just updated the link.

**Comment by Sbte** [comment]
They are not. The ones we had before were COMPILED versions, the ones you posted are the SOURCES. I said that 3 times already. Please let people who know what they're doing figure this out.

**Comment by KinG-InFeT** [comment]
forgive me but I did not understand what you mean by pre-compiled, I apologize

**Comment by c10ud** [comment]
not an emesene issue, btw if wiki is wrong just edit it directly
