### ISSUE TITLE
Facebook and jabber protocol not appear

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1076]
Facebook and jabber protocol not appear in login...

**Comment by pepeleproso** [comment]
any console output? it's working here

**Comment by zipatei** [comment]
none console output... just see image http://imageshack.us/photo/my-images/263/capturadetelade20120316.png/

**Comment by zipatei** [comment]
console have this 

Errors occurred while importing jabber backend: No module named xmpp

**Comment by pepeleproso** [comment]
you need to install xmpppy

**Comment by zipatei** [comment]
python-xmpp... fixed.. close issue. thanks...
