### ISSUE TITLE
Facebook features on OS X

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1078]
Not sure whether they are actually implemented yet, but if they are non of the features on the tab actually work on OS X.

emesene throws no errors, -vvv doesnt show anything either :/

**Comment by pepeleproso** [comment]
They are implemented so we have a problem somewhere.
When you login into emesene a popup window should appear so you can enter to facebook. Does it appear for you?
That window should only appear one time.

**Comment by joshf** [comment]
Will create a new account and test but pretty sure it didn't.
------Original Message------

**Comment by pepeleproso** [comment]
No, need to create a new account, just locate the config file and remove this key from it
 [
  "facebook_token", 
  "AAAETMnXX46yuetayZAWBfwVnuonT45PmTdPqQMf1sHo5qEZD"
 ]

**Comment by joshf** [comment]
Ok, is the login name@chat.facebook.com or is it my email? I'm out at the minute will test and report back later

------Original Message------

**Comment by pepeleproso** [comment]
it's your mail, the same as login into the facebook page

**Comment by joshf** [comment]
Okay will test when I get home
------Original Message------

**Comment by Sbte** [comment]
@pepeleproso can't we do this automatically? (note that I don't use facebook)

**Comment by pepeleproso** [comment]
I added a button to reset the token. It's in the preferences dialog.

**Comment by joshf** [comment]
I just get a connection error when i login with my email i use to login to Facebook. 

Havent got to the point where i get the facebook auth screen yet.

```
[10:37:27 DEBUG jabber.Worker] closing thread
```

**Comment by pepeleproso** [comment]
you need to:

1- login into emesene with name@chat.facebook.com
2- After you login emesene will display a popup windows asking you to login into facebook again, this time use your email

**Comment by joshf** [comment]
Getting no prompt auth window, cant see any erros in Terminal. 

## 

Josh Fradley
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by joshf** [comment]
Got this working by getting my access token manually, but never saw an auth window. Also emesene is not fetching my display picture from Facebook.

**Comment by pepeleproso** [comment]
does it fetch your status?

**Comment by joshf** [comment]
Yeah
------Original Message------

**Comment by joshf** [comment]
This still isnt working as of latest release. 

I made a guide of how to getting working http://pastebin.com/nakBS8Vg

**Comment by c10ud** [comment]
wait, emesene doesn't have webkit output working in osx right? i think the auth window uses webkit (didn't check the code)

**Comment by joshf** [comment]
@c10ud Yeah thats probably why then, couldnt we detect osx and open the facebook auth page in the default browser?

**Comment by c10ud** [comment]
http://www.macports.org/ports.php?by=library&substr=py27-webkitgtk

i don't know how you cook mac packages though ;)

**Comment by joshf** [comment]
Its a pain, will investigate when i have free time, for the meantime though where is the call made to show the auth window? thought it would be in pyfb but couldnt find it?

**Comment by c10ud** [comment]
josh, probably we can but then i don't know how to fetch the result token (i didn't code that part)

**Comment by joshf** [comment]
Hmm, surely it could be done manually. For example, link opens in browser, user give permission, redirects to emesene callback page, that page displays token, user can copy and paste into preferences or something like that

**Comment by c10ud** [comment]
@pepeleproso @4ndreaSt4gi

**Comment by astagi** [comment]
Well I used a deprecated but working library, and all the other stuff worked ok.. why did you need to change everything? Was it really necessary? I advice to restore it..

**Comment by c10ud** [comment]
i don't know what changed, but auth was done with the same method i think?

**Comment by astagi** [comment]
I don't know :) I suppose so, generating the auth url intercepting the token with the webview at the end... I just saw @pepeleproso commit that changed the lib cause the old one was deprecated, don't know what changes atm...

**Comment by pepeleproso** [comment]
I changed it because old method didn't work with the new timeline. I didn't know webkit output isn't working on mac. I add a fallback method.

**Comment by c10ud** [comment]
nice one, even if i hope someday someone will be able to use webkit in
osx and windows7 :)

@joshf if it's fixed for you, you can close the issue

2012/4/3 jose Rostagno
reply@reply.github.com:

**Comment by pepeleproso** [comment]
closing as no new issues found.
