### ISSUE TITLE
[Update Request] Update emesene in Repository Ubuntu

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1083]
There are many people to try Ubuntu 12.04.

Ideally, the updating repository emesene, so that those test ubuntu, may also test the emesene, and to report errors.

**Comment by Sbte** [comment]
We'll do a new release soon. After that we'll ask for an SRU or something. We can't just push an unstable release to Ubuntu now, because that would then also be the emesene you'd find in the final Ubuntu 12.04.

**Comment by zipatei** [comment]
Ok... close issue. :)
