### ISSUE TITLE
Facebook error?

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1084]
/home/andre/emesene/emesene/gui/gtkui/Window.py:110: Warning: /build/buildd/glib2.0-2.31.20/./gobject/gsignal.c:2572: instance `0xb17c158' has no handler with id`1231'
  self.cb_on_close = lambda *args: self.hide_on_delete()

**Comment by KinG-InFeT** [comment]
perhaps an error of the glib library?

**Comment by zipatei** [comment]
Close for now... if this appear again, i reopen. :)
