### ISSUE TITLE
first message does not show the conversation window

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#1085]
When someone talks to me for the first time after opening emesene, the conversation won't pop up on the taskbar or the desktop, the tray icon starts blinking and I can see the notification saying X person talked to me but the windows is nowhere. If I click the tray icon, the conversation popups and it's now shown on the taskbar.

Other messages from other contacts will open the conversation without problems after the first.

It also works after logging out and then logging in, the problem appears only with the first message received after we open emesene.

I don't know if it's a bug on emesene or linux mint, I don't have other system to try it... can anyone confirm this?

steps:
1-open emesene
2-loggin
3-wait for the first message to arrive (or send yourself a message using another client)

maybe related:
-use TrayIcon as the TrayIcon extension

Linux Mint 11 Katya 32bits Gnome

**Comment by c10ud** [comment]
If this is 100% reproducible with those steps i think it's something
related to the distro because i never experienced it.

We had some issues with some messages not being showed but that wasn't
the _exact_ case (i.e. it happened after some switchboard was
desync'ing with conversation managers or something like that, but sbte
could have fixed this)

2012/3/20 Ariel Juodziukynas
reply@reply.github.com:

**Comment by arielj** [comment]
I think I've found something, it happens when I check the "Start minimized/iconified" options on the Conversation tab on preferences, maybe the action shouldn't be iconify() (emesene.py#722) and we shouldn't call that twice :P

I'll try to fix it, or at least kill that ugly "call method twice" thing :P

**Comment by c10ud** [comment]
i explained why there's a double call in the commit, but are you sure this happens 100% and only when you have that option enabled?

Also, is it happening with the usual metacity/compiz/gnome-panels/unity or with some gnome3/mutter/g-shell/cinnamon thing?

**Comment by c10ud** [comment]
suggestion, if that's the case: write a small piece of python code that opens a window iconified and see what happens

**Comment by zipatei** [comment]
On most systems, you can temporarily remove the window from the screen by iconifying it. In Tk, whether or not a window is iconified is referred to as the window's state. The possible states for a window include "normal" and "iconic" (for an iconified window). There are some others too.
thestate = window.state()
window.state('normal')
window.iconify()
window.deiconify()

**Comment by arielj** [comment]
I'll close this, it looks like some pygtk+linuxmint error
