### ISSUE TITLE
[INFO] Twetter account is dead?

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1088]
The emesene twetter account is dead? not upgrade now?

**Comment by Sbte** [comment]
I have no clue what you mean. When you post something here, please try to make it as understandable as possible, because your English is quite bad...

**Comment by KinG-InFeT** [comment]
Forgive my English, I meant that the twitter account is no longer updated?

**Comment by Sbte** [comment]
Do we have one? Maybe mariano owns it?

**Comment by KinG-InFeT** [comment]
this account https://twitter.com/#!/EmeseneIM  is not updated by Monday, May 02, 2011

**Comment by Sbte** [comment]
@marianoguerra

**Comment by KinG-InFeT** [comment]
a possible solution would be to automatically connect the blog with the account twetter .. there are many guides on google about it, and then update manually each time it is, for example, fixato some major bug, or have made ​​changes radicals .... in short, things like that .... I could update it if you give me permission, and I can help here too.

**Comment by marianoguerra** [comment]
I don't own any emesene related twitter account, that twitter account used to retweet some stuff about emesene but dunno who owns it.

also, there is an empty emesene account, that of course I don't own :)

**Comment by pepeleproso** [comment]
Closing as none of the devs own that account
