### ISSUE TITLE
Error when installing emesene2-ppa2 from Eibriel's PPA.

### ISSUE THREAD

**Issue by PappBence** [emesene/emesene#109]
Error in terminal when I want to install it:

Compiling /usr/lib/pymodules/python2.6/emesene/e3/cache/CustomEmoticonsCache.py ...
Sorry: IndentationError: ('expected an indented block', ('/usr/lib/pymodules/python2.6/emesene/e3/cache/CustomEmoticonsCache.py', 22, 27, "    ''' add a new entry '''\n"))

What is it? And then I can not run emesene2 from menu.

Eibriel's PPA: https://edge.launchpad.net/~gabriel-inv/+archive/eibriel-emesene2

My system: Ubuntu 10.10 64 bit

**Comment by EibrielInv** [comment]
Now it should work...

Regards!!

**Comment by c10ud** [comment]
did you modify anything or it's fixed upstream?

**Comment by EibrielInv** [comment]
Hi! is related with:
http://github.com/emesene/emesene/issues/closed#issue/110

is already solved.
Regards!!

**Comment by c10ud** [comment]
ok, closing the issue then

**Comment by PappBence** [comment]
Now it's work.

Thanks
