### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reject_contact'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1091]
:Traceback (most recent call last):
:  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/Dialog.py", line
1722, in cb_reject
:    self.switchmail(None, -1)
:  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/Dialog.py", line
1701, in switchmail
:    self.update()
:  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/Dialog.py", line
1670, in update
:    self.hide()
:  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/Dialog.py", line
1705, in hide
:    self.callback({'accepted': self.accepted, 'rejected': self.rejected})
:  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 653, in
on_contact_added_you
:    self.session.reject_contact(account)
:AttributeError: 'NoneType' object has no attribute 'reject_contact'

**Comment by zipatei** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=804623

**Comment by c10ud** [comment]
and again
