### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'mail_client'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1093]
:Traceback (most recent call last):
:  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/Window.py", line
166, in _on_delete_event
:    return self.cb_on_close(self.content)
:  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 334, in
close_session
:    self.session.stop_mail_client()
:  File "/usr/lib/python2.7/site-packages/emesene/e3/jabber/Session.py", line
70, in stop_mail_client
:    self.mail_client.stop()
:AttributeError: 'Session' object has no attribute 'mail_client'

**Comment by zipatei** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=798785

**Comment by c10ud** [comment]
emesene-2.11.11 is outdated, unless you can reproduce with current master, i'll close the bug
