### ISSUE TITLE
Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#1094]
/home/arielau/emesene2/emesene/emesene/gui/gtkui/**init**.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()

1-Open emesene
2-Log in

Happens on Linux Mint and Windows XP

**Comment by c10ud** [comment]
this is gtk lo-level stuff, might depend on the gtk version used and since it's a warning and /i think) it doesn't interfere with normal emesene usage i think we can safely ignore it

i'll close the issue but feel free to reopen if i'm wrong

**Comment by Sbte** [comment]
Also, this existed ever since emesene 2 was put here on github (tested that a while ago), so good luck with finding the bug (if any).

**Comment by arielj** [comment]
the warning is thrown everytime a contact should be shown on the contactlist (using -W"always" to run python shows all the warnings)

something is wrong with the avatar renderer on renderers.py, this line "model.get_value(iter,0)" specifically, it's the only property of the type gobject.TYPE_OBJECT

a similar warning appears everytime an avatar is updated (if it's animated)

I'll keep looking

**Comment by arielj** [comment]
just or the record, the warning was shown once for each group except the first (if you have 2 groups, when setting the text for the second something goes wrong)

I guess it's some kind of weird pygtk/gtk issue, copying the strings char by char seems to fix it

**Comment by pepeleproso** [comment]
I think it's https://bugzilla.gnome.org/show_bug.cgi?id=653007
fixed by http://git.gnome.org/browse/pygobject/commit/?h=pygobject-2-28&id=42d871eb0b08ee6d55e95cc7e4b90844919555b9 maybe you don't have that patch?

**Comment by arielj** [comment]
more testing, it should be fixed when the element is a string, it's harder when it's a gdk.Pixbuf

**Comment by KinG-InFeT** [comment]
reopen bug

**Comment by Sbte** [comment]
No. This is a warning (harmless afaik) and it will go away when we switch to gtk3. This is a won't fix.

**Comment by KinG-InFeT** [comment]
it's ok thanks
