### ISSUE TITLE
emesene is unresponsive after logging in to MSN account

### ISSUE THREAD

**Issue by ale-carra** [emesene/emesene#1108]
After logging in to my MSN account in emesene 2.12.1, and my contacts appear, the window hangs and is almost completely unresponsive. I can close, minimize and maximize the window, but when I click anywhere else just nothing happens. If I minimize the window and later restore it, the window becomes blank. Before logging in the program behaves normally, the problem begins after I log in and my contacts show up. I have no idea what might be this issue, and it began happening after updating to the latest version. I'm currently using Debian sid, under Xfce 4.8.

**Comment by pepeleproso** [comment]
there's some openssl problems. this bug should be fixed by https://github.com/emesene/emesene/commit/bce64813cdb44111bc7bb056b3122ead160a1ea3

Please make sure you have that fix.

**Comment by ale-carra** [comment]
I got the fix and it solved the issue. Thanks!
