### ISSUE TITLE
[FEATURE] New Twetter account?

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1109]
I would like to talk to all the developers and ask: can I create a new account twetter Official and (if desired) I manage it? twetter an account would be good publicity for the project. 

what do you think?

**Comment by KinG-InFeT** [comment]
seems that the account was managed by c10ud.

As you can see from this tweet:

```
mesene development continues (!): me (c10ud) calling my friend (Homer) from my Ubuntu boxThat's it, ......
```

**Comment by KinG-InFeT** [comment]
@c10ud

**Comment by c10ud** [comment]
my personal take is that the blog is just enough for the very sporadic
news we have to tell people, don't know others
in the past we had various ways but in the end, turned out the blog
was just fine

@sbte @marianoguerra

2012/3/30 Vincenzo
reply@reply.github.com:

**Comment by c10ud** [comment]
also i'm not managing that twitter account, it looks like someone made it post from rss or something like that, that's a blogpost

**Comment by KinG-InFeT** [comment]
mmmm possible, since the old blog has been moved to blogspot ... but I repeat the question ... can I create an account twetter (official) of emesene 2 that I could handle myself? would be good publicity.

**Comment by lfottaviano** [comment]
hey if he wants to help with a new feed why not to be open and let him do his best  :D

**Comment by lfottaviano** [comment]
another thing, isn't _"twitter"_? lol

**Comment by KinG-InFeT** [comment]
yes sorry xD

**Comment by c10ud** [comment]
not an emesene bug, closing
