### ISSUE TITLE
Contact names display as source code?

### ISSUE THREAD

**Issue by Kreuger** [emesene/emesene#111]
Im just trying out the script Eibriel posted in the forums and when I ran emesene2 and logged in the contact's names are displayed as what Im guessing is the source code. For example it says 

%DISPLAY NAME%%NL%<span foreground="#AAAAAA" size="small">%BLOCKED% %ACCOUNT%%NL%%MESSAGE%</span> 

When I open up a conversation window however, the info is displayed correctly. And it shows groups in the same manner.

<b>%NAME% (%ONLINE_COUNT%/%TOTAL_COUNT%)</b> .

Also, I'm not sure if this is emesene's fault or the script but I get this displayed..

reuger@kreuger-desktop:~/Downloads/Updates/emesene2$ ./emesene-run
/home/kreuger/Downloads/Updates/emesene2/emesene/emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "gui.gtkui.Indicator"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/kreuger/Downloads/Updates/emesene2/emesene/emesene/e3/base/Logger.py", line 721, in run
    self.logger = Logger(self.path)
  File "/home/kreuger/Downloads/Updates/emesene2/emesene/emesene/e3/base/Logger.py", line 281, in __init**
    self.connection = sqlite.connect(full_path)
OperationalError: unable to open database file
    [payload]

**Comment by marianoguerra** [comment]
try moving the folder in your home at .config/emesene2/your_account to another place and starting emesene 2 again.

**Comment by c10ud** [comment]
mariano's right -- please confirm it's working as expected so we can close the issue

**Comment by c10ud** [comment]
ok, if you have the issue, reopen
