### ISSUE TITLE
Unity Launcher progress bar integration

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#1110]
Hi!

I would like to improve Emesene Unity Launcher integration with progress bar (file transfer) support. But i don't know where I start it. Wich file I need to modify?

**Comment by Sbte** [comment]
This one:

https://github.com/emesene/emesene/blob/master/emesene/gui/common/UnityLauncher.py

See here for the documentation:

https://wiki.ubuntu.com/Unity/LauncherAPI

Note that you must use the DBus API, so you might have the convert the progress to the correct DBus variable type.

**Comment by Sbte** [comment]
Also, if you want help, feel free to come to the IRC channel: #emesene on FreeNode

**Comment by rockybalboa** [comment]
Thanks.
