### ISSUE TITLE
My avatar in Facebook session

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1113]
Adium themes:

http://imageshack.us/photo/my-images/818/capturadeecrade20120403.png/

**Comment by zipatei** [comment]
@pepeleproso Still not my avatar appear in the conversation.

http://imageshack.us/photo/my-images/405/capturadeecrade20120407.png/

**Comment by zipatei** [comment]
only happens when we have no valid token, and have the avatar cache

**Comment by pepeleproso** [comment]
now we always return the cached avatar
