### ISSUE TITLE
Logger improvements and feature requests

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#1118]
Here's a list of tasks related to logging that have been requested, if you want to do them:
- # 967 Provide another implementation of logger that involves simple txt and/or html and/or xml files
- Small and external to emesene logviewer program

~~#756 Make current internal logviewer be able to show more than 1000 lines~~
~~#1044 Option to remove the chat history, selectively or entirely~~

**Comment by lfottaviano** [comment]
I have done a function that generates xml files for logger. Having an xml file, we can generate XHTML with XSLT Transform, or simply formatting with css the xml file or whatever is possible with xml files. Refs #967

commit:
https://github.com/emesene/emesene/commit/d6c8848b57d67a3c73c0ecd3c62cc545fb8005a8

**Comment by c10ud** [comment]
nice one, but i think the original feature request was something like replace entirely the sql logger with text ;) anyway, every improvement is well accepted

**Comment by lfottaviano** [comment]
I read the request at night yesterday, and I interpreted the way I want lol, sorry for that

**Comment by Fabioamd87** [comment]
https://groups.google.com/forum/?hl=it&fromgroups#!topic/emesene/LP9g7BWwVLo
https://groups.google.com/forum/?hl=it&fromgroups#!topic/emesene/eLVac1a_tOA

**Comment by c10ud** [comment]
about #756 Make current internal logviewer be able to show more than 1000 lines:
the limit is currently hardcode, is there a reason for that? can we increase to -1 or something like that? @Sbte

**Comment by Sbte** [comment]
Because loading 1000 lines takes about 10 seconds sometimes? Increasing it means that for some people it will appear like chat history is not working. This is why we display a warning if there are too may lines. If people want to see more, they can change the date scope.

**Comment by moneycat** [comment]
@Sbte In my case, the NiceBar will show after logger drawing.

**Comment by Sbte** [comment]
@moneycat that's the warning I was talking about

**Comment by c10ud** [comment]
I'm closing this issue since the remaining issues:

```
#967 Provide another implementation of logger that involves simple txt and/or html and/or xml files

Small and external to emesene logviewer program
```

#967 -> we can reccomend using the export, we cannot rely onto textfiles for logging the stuff we currently log (and need) for a session

the external logviewer, i'll open a new issue

**Comment by zipatei** [comment]
#1044 Option to remove the chat history, selectively or entirely

This issue not close. :/

**Comment by c10ud** [comment]
for 1044 we can disable the logger, the history removal cannot be made in a small panel inside the viewer, it must be integrated in an external program, i'll add to #1451

**Comment by Sbte** [comment]
@c10ud why not? We can just make a button that runs a query that removes the history for a specific contact.

**Comment by c10ud** [comment]
no moar buttons in that panel -- and such button would mean another widget for selecting when, where, etc.
if you care about your db, just encrypt your home or disable logger? or keep this advanced functionality in a specialized app?
