### ISSUE TITLE
Gif Avatar Bug

### ISSUE THREAD

**Issue by saguar** [emesene/emesene#112]
Hi, I've found a weird bug with gif avatars.... If you use a gif image as your personal avatar, you cannot send/receive messages. I've made a screencast video to make it clear:

**Comment by saguar** [comment]
http://www.youtube.com/watch?v=C-izapsusOc

**Comment by c10ud** [comment]
Fix for animated avatars. Closed by ea4f46fb07eb4d793d482964c7e40544a9bad0df
