### ISSUE TITLE
Languages should be human readable

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#1122]
I mean... language codes are not nice for users, we should display "Español" instead of "es", or "English" instead of "en".

If the language name is written in the propper language, even better (like "Español" for "es" instead of "Spanish")

It shouldn't be hard, just some dict with code => name references.

**Comment by c10ud** [comment]
problem is, there're LOTS of languages

2012/4/5 Ariel Juodziukynas
reply@reply.github.com:

**Comment by arielj** [comment]
I know, but it's easy, we only need to associate all language codes from emesene/po folder to each of the languages here https://translations.launchpad.net/emesene/trunk somewhere inside Language.py and use that dict to populate the dropdown menu.

**Comment by lfottaviano** [comment]
we can read the po file info with translation.info() function

**Comment by lfottaviano** [comment]
or read that info without gettext

**Comment by lfottaviano** [comment]
well, not all po files have `x-poedit-language` value available

**Comment by arielj** [comment]
I'm doing this with a dict, I'll try to push it today or tomorrow

**Comment by arielj** [comment]
pushed, @lfottaviano i've refactored the way we instanciate the translation (with a little doc comments), please test it on your cases to

I don't close this because yet, I will update languages to it's original pronunciation (google and wikipedia, here I goooo...)

**Comment by lfottaviano** [comment]
good to see this, works fine on windows 7 also tested on archlinux. When I can I will test this on windows xp, but shouldn't be problems.

Only one thing is there an special reason why `try except` statements are back? if you pass as parameter `fallback=True` on `gettext.translation()` function you don't need to catch IOError exceptions, neither need to assign `self._translation = gettext.NullTranslations()`

**Comment by lfottaviano** [comment]
@zipatei, if you can please, test languages module at your machine

**Comment by lfottaviano** [comment]
@zipatei what is your language code ?

**Comment by zipatei** [comment]
@lfottaviano works perfect. =)
PT-PT (Portuguese of Portugal)...

will be able to translate for example, "Portuguese" to "Português"?

**Comment by arielj** [comment]
@zipatei, I'm working on that, I'll finish the translations tomorrow

**Comment by lfottaviano** [comment]
thanks @zipatei :D, yes @arielj  is doing what you said
