### ISSUE TITLE
Invalid token Facebook

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1127]
Two popup's appeared to me to validate.

And the strange thing is that the two clicked cancel, and showed me the messages presented.

http://imageshack.us/photo/my-images/4/capturadeecrade20120407.png/

**Comment by zipatei** [comment]
@pepeleproso 

Seems to be fixed, but there's one thing I said that is the same.

If I cancel validation on facebook, emesene returns as if connected properly.

**Comment by pepeleproso** [comment]
to change that page we need some javascript code to detect that case, and change the text according to it.
