### ISSUE TITLE
Emesene copies dropbox indicator icon instead of using its own.

### ISSUE THREAD

**Issue by Malabarba** [emesene/emesene#113]
Currently, the indicator icon for emesene for me is the dropbox icon. I'm using dropbox forum builds (which is why it has an indicator applet). I'm talking here about the icon that shows up in the indicator applet, not the icon inside the messaging menu. 

It affects the "busy" and "idle" status icons.  Not the other icons.

**Comment by c10ud** [comment]
you'd better tell dropbox to fix their code sir, since we use the icon named "emesene" for indicators.

**Comment by Malabarba** [comment]
Where are the indicator icons stored? (so I might try to track down the issue)

**Comment by c10ud** [comment]
depends on emesene version you're using. latest git master (read: today, or yesterday) enables indicator only for ubuntu >= 10.10, and sets the icon path as <emesene-running-dir>/themes/images/<theme-name>/(panel, if available, otherwise it stops at theme-name)

**Comment by Malabarba** [comment]
Thanks. A bit more testing is indicating it only affects the "busy" and "idle" status icons. All other icons show up as normal. It also affects all themes, and all users.  It also only affects the indicator applet icon, icons within emesene's window show up normally. How can I tell my version? I last updated it a couple days ago from github.

**Comment by c10ud** [comment]
doing a "git pull emesene master" would surely help. however with latest version it should not have any problem.

where i can find this dropbox so i can test it out a bit?

**Comment by c10ud** [comment]
now that i think of it, i have ubuntu 10.04, so i cannot test it out :) someone with the newer rel?

**Comment by Malabarba** [comment]
Just updated and it still happens on the latest version. Here is the dropbox build http://forums.dropbox.com/topic.php?id=26207 if anyone wants to try it.

**Comment by c10ud** [comment]
just started on a Maverick virtual machine both dropbox-from-forum and emesene-latest-git, started dropbox first and then emesene...and everyone keeped its own nice icon -- try updating your emesene

**Comment by Malabarba** [comment]
I update my emesene every day. I think I tracked it down now. It only happens to me when I set Faenza or Faenza-Dark as my icon theme in Gnome (doesn't matter what global theme I'm using). All other icon themes work fine. I'm guessing it's probably a Faenza bug then?

**Comment by c10ud** [comment]
steps i did:
-install maverick
-git clone emesene
- download dropbox
- cd dropbox && ./dropbox
- cd emesene && ./emesene
- changed theme to faenza

but everything works fine..

**Comment by Malabarba** [comment]
Ok, then I'm out of ideas. Running emesene in terminal returns a few warning messages, but they are the same independent of what icon set I'm using. I get the faenza set from their ppa, and dropbox was updated today and emesene was downloaded 10 min ago.

It's probably some bug I'm getting for having transferred my gnome configs from the preivous install. I'll log in as a new user and try again, if the bug persists I'll just give up.

**Comment by c10ud** [comment]
the real wtf is that with appindicator we set the icon_path as current-emesene-working-dir/themes/blablabla and we use names different as dropbox' for icons! so this is a huge wtf :D

**Comment by Malabarba** [comment]
Yeah, that's a huge wtf =P. And the problem persisted
Here's what I did:
-Created new user  
-Logged in as new user.  
-Downloaded and isntalled latest dropbox forum build (it ran automatically when installation finished).  
-Downloaded from github and extracted emesene.  
-(Faenza was already isntalled).  
-./emesene  
-Set Appearance>Theme>Customize>Icons>Faenza  
-Changed status to Busy.  
-And it happened again.  

If you guys want me to get any more info on the issue just let me know. I don't know what else to investigate. 

Also, it's a conflict with another in-development app, that only happens with a specific icon theme, and it even has some other restiction that's causing it to happen to me but not to you. So it's probably not a top priority anyway. =)

**Comment by c10ud** [comment]
see: http://forum.emesene.org/index.php/topic,3423.msg25369.html#msg25369

I have found the soultion. It is a Faenza theme related probleme.
To solve this just remove from your faenza theme status directory the following symbolic links:

/usr/share/icons/Faenza/status/*/

rm blank.png busy2.png busy.png idle.png logo.png x.png

then restart emesene and all should work fine

**Comment by Malabarba** [comment]
Great, I guess this can be closed than.
