### ISSUE TITLE
Facebook remember login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1135]
By assuming the mail, he should also take the session.

Reproduced:

1) First login and click remember: http://imageshack.us/photo/my-images/198/capturadeecrade20120408.png/
2) Close emesene
3) Open emesene: http://imageshack.us/photo/my-images/341/capturadeecrade20120408.png/

**Comment by zipatei** [comment]
This only happens after the first time.

After the emesene remember always what is the network.

**Comment by Sbte** [comment]
I don't think this is just a facebook thing?

**Comment by pepeleproso** [comment]
I think this is a regresion, maybe the language work?

**Comment by Sbte** [comment]
@zipatei, could you try a git bisect?

**Comment by zipatei** [comment]
how?

**Comment by Sbte** [comment]
@zipatei http://wiki.winehq.org/RegressionTesting#head-efe98a3aade37d2588b7f64cb72cc2f859dddc2e

That's where I learned it from anyway. There are probably other guides out there too.

**Comment by Sbte** [comment]
Never mind. I found the issue:

self.config.d_user_service[account] should be set in config_account in LoginBase. That's easy. While at it, _update_fields should probably also call config_account. I'll do this later.
