### ISSUE TITLE
[Features Request] Block and unblock icon and tooltips

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1136]
1) Change icon when unblock contact.
2) Adapt tooltips for each type of icon.

**Comment by lfottaviano** [comment]
@zipatei plz test, thanks

**Comment by zipatei** [comment]
Fixed. =)

Good work. Thanks

**Comment by jamesaxl** [comment]
is it fixed ?

**Comment by zipatei** [comment]
yes... it is fixed
