### ISSUE TITLE
All preferences should be applied instantly

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1139]
@c10ud always wanted this:

Once a preference is changed it should be applied instantly. This can be done using signals. See for example the "Show conversation header" and "Show conversation toolbar" options.

https://github.com/emesene/emesene/blob/master/emesene/gui/base/Conversation.py#L76

(the functions are defined in gtkui)

If someone is working on this, please add a list here of the options that are done. Once it is reasonable to remove all Redraw and Apply buttons, please do so.

**Comment by c10ud** [comment]
i don't think you can do it for every preference though

**Comment by Sbte** [comment]
We can do an automatic full redraw if the Close button is pressed if one of those settings is changed.

**Comment by Sbte** [comment]
See https://github.com/Sbte/emesene/commits/instant-language-updates

If someone's going to work on that (I'm not):

Signals need to be unsubscribed in some way I think.
This needs to be done for all py files and all widgets. If you need help just ask.

**Comment by lfottaviano** [comment]
_Conversation Tab:_
- I have done for Conversation, the Escape key setting is now instantly applied 
- ConversationManager: Close tab button hiding, is now instantly applied

**Comment by jamesaxl** [comment]
what about apply plugins and extentions instantly ?

**Comment by Sbte** [comment]
@jamesaxl For themes you need to redraw the widgets. For icons that is at least. So for example the user panel, and the conversation toolbar. For the conversation themes, it should be easy to redraw the Webkit widget.

For other extensions it depends. For example for the plus<->no plus you need to redraw the userlist.

Plugins should already be applied instantly afaik.

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/issues/1139#issuecomment-5029863

just ask to people adding new settings if they can code them so they're applied instantly
