### ISSUE TITLE
[Feature Request] Status

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1146]
I think that to maintain consistency of appearance of emesene instead of the description of the state, should contain the status icons.

In order to help to each icon status, could have tooltips.

http://imageshack.us/photo/my-images/839/capturadeecrade20120411.png/

**Comment by arielj** [comment]
It does have the icons here, check your gtk config

**Comment by zipatei** [comment]
Hum .. I also found it strange .. I know what must be ... sorry ..

**Comment by arielj** [comment]
check this http://www.howtogeek.com/howto/21149/how-to-enable-icons-on-the-ubuntu-system-menu-minor-annoyances/

**Comment by zipatei** [comment]
I also thought that was it, but still does not work.
