### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1147]
I will create some issues to improve the accessibility of menus.

The first suggestion is to remove:
- Order by order by and group status
- Show offline contacts
- Show empty contacts
- Show blocked contacts
- Sort by name
- Group offline contacts

And put these options in the preferences of the Main Window.

http://imageshack.us/photo/my-images/826/capturadeecrade20120411.png/

**Comment by Smile4ever** [comment]
Good idea. You could also remove the File => Status because there's already a button for it.

**Comment by zipatei** [comment]
File => Status no. Because new HUD Ubuntu, is a good shortcut.

**Comment by Smile4ever** [comment]
Maybe it's possible to hide the menu with an right click option? I would like that.

**Comment by Sbte** [comment]
@zipatei, you have a lot of good ideas, so I was wondering if you're also able to code (or willing to learn). In that case you could just implement this or fix some of the easy bugs you submit. If you need help, you can find us in the IRC channel ;)

Anyway, if you don't think you can do this, you're still a great tester ;)

**Comment by lfottaviano** [comment]
@zipatei, yes if you join IRC you can help us, I also think you are a good tester, and your input is useful

**Comment by zipatei** [comment]
Thanks for the encouraging words.

In emesene 1.6, I help with some commits, "copying" other commits.

I'm from the area of economics. I like computers and like to help, but still could not get well in the area of programming.

But I'll accept your help. Let's see where this goes. =)

**Comment by c10ud** [comment]
I don't like this idea: certainly most of these options are one-timers but show offline or blocked could be useful sometimes, and creating another tab for this little menu (they fit better in a menu imo) is overkill

so, status: wontfix. but if you convince me with a good argument and patches i may change my mind, as usual
