### ISSUE TITLE
[Feature Request] Test Connection in login preference

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1148]
Add this test in login preference:

http://lh4.ggpht.com/-JvxFw28WLK4/T1bcQiq_EDI/AAAAAAAAEDs/P9GOE-FgfsA/como-configurar-proxy-no-windows-messenger-2011_3.jpg?imgmax=800

http://lh3.ggpht.com/-B153Z8hoCvE/T1bcSQ8rXCI/AAAAAAAAED8/PqxK1Ar0UOY/como-configurar-proxy-no-windows-mes%25255B6%25255D.jpg?imgmax=800

**Comment by KinG-InFeT** [comment]
This feature may be useful in case of non-login and login using the test could detect the problem at login

**Comment by pepeleproso** [comment]
Papyon didn't give us this feature, xmpp neither. so I didn't think we can't implement this
