### ISSUE TITLE
Contact Online/Offline notifications popup even when disable.

### ISSUE THREAD

**Issue by Malabarba** [emesene/emesene#115]
That's it really. It seems the enable/diable check-box for contact online notifications (in the options window) does nothing. The notifications always show.

**Comment by DragaO** [comment]
i disabled all the notifications and is working properly.

have you tried enable/disable all or just one?

**Comment by Malabarba** [comment]
I tried disabling both "Notify on contact online" and "Notify on contact offline" (at the same time). I've just realised though, the options didn't stick at first. I restarted emesene a couple of times and now they stuck and are working.
