### ISSUE TITLE
Update link in blog.emesene.org

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1151]
Update gentoo ebuild link in blog.emesene.org Download page

Ebuild update: http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-im/emesene/emesene-2.12.3.ebuild?view=markup

Bug link for bump: https://bugs.gentoo.org/show_bug.cgi?id=410543

**Comment by Sbte** [comment]
It already points to the place where the new version is posted. There is nothing to update...
