### ISSUE TITLE
Message is lost when window is closed while contact is typing

### ISSUE THREAD

**Issue by bellini666** [emesene/emesene#1160]
I'm reporting this issue for my wife.

She is using emesene 2.12.3 on Ubuntu Precise (12.04). She reported me that, if a contact is typing something (the message window shows that the contact is typing) and she closes the window, that message is never received.
The problem happens on msn backend.

**Comment by c10ud** [comment]
@sbte

2012/4/14 Thiago Bellini
reply@reply.github.com:
