### ISSUE TITLE
[Preferences] Refresh Extensions

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1163]
Reproduced:

1) Open Preferences Window
2) Click Extensions
3) Click other menu item
4) Click Extensions
5) Click other menu item
6) Click Extensions
.....

Emesene opens multiple windows "Refresh Extensions".

If one was open, it should not open more until it was closed ..

**Comment by Smile4ever** [comment]
Yeah, maybe checking with a python ide who is supporting breakpoints or something similar?
