### ISSUE TITLE
[Feature Request - Preferences] Option to set Notifications Off

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1165]
An option like the sounds (Mute Sounds).

**Comment by c10ud** [comment]
can't you do that already? deselect all problem solved (hint: that's what i do, no annoying notifications anymoar)

**Comment by zipatei** [comment]
The truth is that the sounds the same applies, but not allowed to make a choice for all.

Nowadays, I think that a user wants simplicity and less work.

Users of linux (our biggest market, are no longer mostly "advanced" and are now more "noobs")

And very early on that users of emesene, emesene choose therefore, for simplicity. The more we simplify the choices, the better their experience.

**Comment by zipatei** [comment]
Do not know if it's difficult, but we could begin to implement the following functionality (on / off) in the Sounds and Notifications menu.

http://2.bp.blogspot.com/-RoAy4DnTLMg/TyFH3fdMWDI/AAAAAAAACEM/OPqLgAAjTho/s1600/New+Settings+in+Ubuntu+12.04.png

**Comment by Sbte** [comment]
Not possible until we port to Gtk3

For the options:
We should probably rework the extensions in such a way that they are presented in a more convenient way. Maybe more like the plugins. But then with radio buttons...
