### ISSUE TITLE
Strange Text Output in Chat Window

### ISSUE THREAD

**Issue by inukaze** [emesene/emesene#1167]
Hi there , im recently install the lastest version for window of emesene 2.12.3 , and well tryting to chat with someone you can see thisç

http://img32.imageshack.us/img32/3527/emesene2123outputtexter.png

i can saw correctly the things i wrote before , someone have a idea how to fix it ???

**Comment by KinG-InFeT** [comment]
try changing the theme for emesene, and sets the default theme ... is likely a mistake of encoding of strings, managed badly by the theme.

**Comment by Sbte** [comment]
Did this work in previous versions of emesene? If it did could you do a regressions test/git bisect?
