### ISSUE TITLE
Option to disable sound when focus is already on that conversation

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#117]
Currently, when you have sound switched on for incoming messages, it will make a sound on every incoming message, including ones you get when the focus is already on the chat window. There should be an option to disable that.

**Comment by c10ud** [comment]
i guess that should be the default, but notifications/sounds are just a stub atm :)

**Comment by c10ud** [comment]
Play incoming message sound only if there&#39;s some message waiting. Closed by 7a38aa2bf0df43bde2d2d945663898fa1316a1e8
