### ISSUE TITLE
p2p NAKs are showed in conversation window like unreceived messages

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1171]
[removed sensible info]

**Comment by Smile4ever** [comment]
See also https://github.com/emesene/emesene/issues/1172

**Comment by zipatei** [comment]
[removed sensible info]

**Comment by c10ud** [comment]
interesting, seems like he ACKed message 7 while refusing others...mmm

**Comment by zipatei** [comment]
[removed sensible info]

**Comment by c10ud** [comment]
i think i found the "issue":

the client your friend is using doesn't understand our p2p data and sends NAK.

But we don't distinguish NAKs from messages (importants) from NAK of p2p data (useless) so we display the error.

If your friend receives all your _text_ messages then this bug is about "prevent p2p errors to show up as conversation errors in gui"

**Comment by zipatei** [comment]
Not always given. In most cases receives. 

And as we did the test, I think that is related to "not hotmail" emails.

**Comment by Smile4ever** [comment]
@c10ud This is the fix we need for this bug: If your friend receives all your text messages then this bug is about "prevent p2p errors to show up as conversation errors in gui" This fix is likely to fix #1172 also (also a NAK signal for p2p data - maybe images are handled differently in MSN 2009).

**Comment by c10ud** [comment]
p2p and text are treated the same way by papyon: put in a queue with an ID and then they check if they succeed or fail
when they're checked, there's currently no way to identify if that a was a p2p or text message

see switchboard_manager.py for reference

**Comment by c10ud** [comment]
updated desc

**Comment by c10ud** [comment]
@zipatei are you still experiencing this kind of errors? i tried cooking up a patch for this i'd like to try out

**Comment by zipatei** [comment]
[sensible data]

text messages NAKed

**Comment by zipatei** [comment]
I think different about NAK initial, offline messages

**Comment by c10ud** [comment]
this NAKs are different, they should be showed in conv because your friend's client NAKed

**Comment by c10ud** [comment]
assuming original issue fixed by 7a3fe5f

p.s. text chat NAKs must be showed in conversation, so last report was correct
