### ISSUE TITLE
Emesene makes X.org freeze

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1173]
X.org becomes frozen (or my display) when a specific contact comes online who has MSN 2009 on Windows 7. It's a @hotmail account and i'm using Linux Mint Debian as system. Using latest emesene 2.12.3 from Debian sid repo's.

Addition: he talks to me when it happens, but I don't see the text. If I type text, he can see it. A double restart of emesene is needed to close the previous session.

**Comment by Smile4ever** [comment]
In two days of testing without Adium output, it seems to work fine. There were no freezes in the past two days. @c10ud mentioned that it's a WebKit bug.

**Comment by Sbte** [comment]
It would be really nice to find out what on earth causes this...

**Comment by Smile4ever** [comment]
@Sbte It's caused by a hard disk failure. Opening my pc & plug in the hard disk cable again solves the problem. So, it's hardware related and not emesene-related. It's likely to be a bug in X.org itself.
