### ISSUE TITLE
converstaion window: font-size is really small 

### ISSUE THREAD

**Issue by DragaO** [emesene/emesene#118]
i updated emesene (git pull origin master && git submodule update) a few minutes ago

in the conversation window, my font-size it's ok (i use 10), but, my contacts font is, more or less, size 4, which is too small to read

**Comment by c10ud** [comment]
i am still trying to figure out how to get user font size from papyon --

**Comment by c10ud** [comment]
my bad, there's no such thing for received msgs..on my way for seeing how to fix it

**Comment by c10ud** [comment]
Fixed small font in AdiumTextBox, maybe it's an hack, but it works nicely (we don't get font size from the server messages). Closed by d9c2ab912a4374abad006b1383bb7ca480eb8a62
