### ISSUE TITLE
emesene direct connection

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#1183]
for fun i ported an old (2 years) patch from lfrb to implement direct connect aka fast transfers in emesene.
i created a branch and the diff is here:

@sbte @pepeleproso @lfottaviano

**Comment by c10ud** [comment]
so:
https://github.com/c10ud/emesene/commit/96e11376b2675a92f9dfb8e3d8096e0d7b271121

i created a new branch with a single commit and now emesene seems to be able to create a local direct connection with another emesene (wow m3n)

**Comment by Sbte** [comment]
Looks great. Now sure what else to say about it :P
