### ISSUE TITLE
Login bugs

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1187]
1) Emesene shouldn't remember accounts when the first time you try to login with this account, it returns an error.

2) The same email account may have MSN and Jabber protocols. Imagine emesene@emesene.org

Reproduced:
- Login with emesene@emesene.org (MSN protocol) and click remember me
- Disconnect
- Login with emesene@emesene.org (Jabber protocol) and click remember me
- Disconnect
- Login with emesene@emesene.org (MSN protocol)
- Disconnect
- Forget me with emesene@emesene.org (MSN protocol)

Now, emesene@emesene.org listed, but does not associate the correct protocol (jabber).

**Comment by Sbte** [comment]
1) What?

**Comment by zipatei** [comment]
@Sbte 1)imagine the first time you use emesene with emesene@emesene.org but instead of MSN protocol, you select facebook protocol.

You click remember me, but when click login, your email settings is wrong, and return error, but account will be recorded.

I think, in this case, should not remember the account.

**Comment by c10ud** [comment]
1) probably we save it before actually checking if the server says OK or not so i'm not sure we can change it
2) whaaaaaaaaaaaat? WHY :D

**Comment by zipatei** [comment]
2) Dont understand? :D

**Comment by c10ud** [comment]
yeah i think i understood but i think it's very unlikely the user will be caught in this issue (!) i am tempted to close this as "PLEASEDONTDOTHIS"

**Comment by moneycat** [comment]
1) We now do `config.save` at multiple places. This issue can be solved by masking the command at `
config_account` and `close_session`.

2) At latest commit version, the behaviour: The account box will be clear.

@c10ud

**Comment by c10ud** [comment]
@moneycat reducing config.save calls can be good, do you have a snippet of the code/ tested?

**Comment by moneycat** [comment]
I've no fully test for what will happen if we reduce this. We can only save config when login succeeded but lost all user changed settings atm.

**Comment by c10ud** [comment]
then i'd leave everything as it is as it works quite good :)

**Comment by moneycat** [comment]
I agree
