### ISSUE TITLE
[Patch] Indentation Error

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#119]
When Emesene precompiles:
    Sorry: IndentationError: ('expected an indented block', ('/usr/lib/pymodules/python2.6/emesene/e3/cache/CustomEmoticonsCache.py', 22, 27, "    ''' add a new entry '''\n"))

Maybe changing:
        def add_custom_emoticon(self, path, shortcut):
        ''' add a new entry '''

```
    def del_custom_emoticon(self, shortcut):
    ''' delete a custom emoticon '''

    def mod_custom_emoticon(self, path, shortcut):
    ''' modify existing path/shortcut '''
```

To:

```
    def add_custom_emoticon(self, path, shortcut):
        ''' add a new entry '''

    def del_custom_emoticon(self, shortcut):
        ''' delete a custom emoticon '''

    def mod_custom_emoticon(self, path, shortcut):
        ''' modify existing path/shortcut '''
```

**Comment by c10ud** [comment]
i think that file can be deleted safely, i'll do it asap

**Comment by marianoguerra** [comment]
I removed the file
