### ISSUE TITLE
can't append message to conversation window

### ISSUE THREAD

**Issue by chy168** [emesene/emesene#120]
When I click a user at contact list, it shown:
    [14:29:48 WARNING msn.Conversation] unknown command: 217 2

I type some message and "enter", I got:
    Traceback (most recent call last):
      File "/tmp/emesene-emesene-19a44ba/emesene/gui/gtkui/TextBox.py", line  173, in _on_key_press_event
        self.on_send_message(self.text)
      File "/tmp/emesene-emesene-19a44ba/emesene/gui/base  /Conversation.py", line 208, in _on_send_message
        text, self.emcache.parse(), self.emcache.path, self.cstyle, self.first)
    TypeError: send_message() takes exactly 7 arguments (8 given)

I set the session to "e3.msn" at login preferences, is that won't use papyon ? (is that the right way to change session?)

**Comment by chy168** [comment]
I am trying to figure out the problem ...

In Conversation gui/base/Conversation.py, line 207
How can I know when the "self.output" object is constructed ?
(How can I find the correct send_message() instant ?)

thank you very much :)

**Comment by marianoguerra** [comment]
I think C10uD fixed this, I logged in with e3.msn a minute ago and I was able to send a message, update the repo and try again.

**Comment by Sbte** [comment]
I have the same problem I guess. When you press enter, the message gets send, and via the notification area I can also see the messages I receive, but the conversation window doesn't work at all.

This wasn't present yesterday. I'll do a regression test.

**Comment by Sbte** [comment]
5025a6023cedfeb4d6d3029ff8c17f8316dc28ad is the first bad commit
commit 5025a6023cedfeb4d6d3029ff8c17f8316dc28ad
Author: Riccardo (C10uD) c10ud.dev@gmail.com
Date:   Wed Oct 27 17:01:00 2010 +0200

```
Implemented custom emoticons sending. Tested with amsn, makes emesene1 crash (some weirdness happens). Closes #96

Fixed style in incoming messages in AdiumTextBox.
Possibly broken some output backend with the add of some dict/list here and there.
```

:040000 040000 f744a74f8ff6e1649be1b812772a2a8b968ac474 ab596a813bae29bde53ebcbab9fe56665aa14f2f M  emesene

**Comment by chy168** [comment]
I confirm the HEAD version (2430501) still broken message send.

**Comment by chy168** [comment]
Sorry .... I closed the wrong issue ....... 
I'm still pending on this
