### ISSUE TITLE
[Add contact] Some problems

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1202]
Reproduce:

1) Open/login Emesene
2) Add contact emesene@emesene.org
3) emesene@emesene.org accept your invite

A) Contact continues appear offline after accept invite

B) emesene@emesene.org send message, and i receive
We send message to emesene@emesene.org but he not receive.

**Comment by zipatei** [comment]
[removed sensible info]

**Comment by c10ud** [comment]
i see the server answering with a bunch of NOTs which means there's some sort of error (which i don't know how to fix)

**Comment by c10ud** [comment]
apparently i was wrong, http://msnpiki.msnfanatic.com/index.php/Reference:Commands

still it is unknown to me why this behaviour...i'll close the issue for now, the reccomended behaviour is rebooting emesene
