### ISSUE TITLE
Open a conversation when Enter is pressed while searching

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1206]
When I'm searching, I'd like Enter to open a conversation with the topmost contact. Like for example nautilus does. It would be nice if the contact was also shown as selected.

**Comment by c10ud** [comment]
thing is, you have also groups (if you show em) so i don't think
pressing "arrow up/down" is so much of an extra step :)

2012/4/24 Sven reply@reply.github.com:

**Comment by Sbte** [comment]
Groups should be no problem, because we can check for groups. Also, if you show groups, it's possible that you have to press down like 10 times. It's just inconvenient.

**Comment by zipatei** [comment]
it would be nice, if topmost contact isnt the contact i want, but the second contact. And i press TAB (just select contacts in result of searching).

**Comment by Sbte** [comment]
We probably shouldn't override the default gtk behaviour...
