### ISSUE TITLE
[FEATURES] multiple accounts in one list

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1207]
It would be very, very useful to be able to view contacts with multiple accounts and a single list, makes her such a thing as pidgim in the picture:
http://img6.imagebanana.com/img/nu19g17k/Immagine.png

and enabling them to manage accounts and disable them such as:
http://img6.imagebanana.com/img/9unm4v7r/Immagine.png

would be a feasible thing?

**Comment by Sbte** [comment]
We could probably make tabs for each session for starters. This would mean that we would only have to rewrite emesene.py. The rest of the code could stay the same except for using a Notebook for the MainWindow.

Anyhow, this quite time-consuming and needs lots of testing. I wanted to do this for a long time now, but I don't have time to actually do it...

**Comment by lfottaviano** [comment]
Haha, you know I have an outline of the same idea, with tabs. But I could not implent it yet, because of time

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/issues/706#issuecomment-1496526

**Comment by KinG-InFeT** [comment]
understood the other topic, but I do not understand the closure of this.

**Comment by c10ud** [comment]
emesene is a single-protocol im (unfortunately? ymmv) unless someone
provides patches to do otherwise so this is not an issue or a feature
request we may consider (unless, as said before, someone steps up and
does it)

greets

2012/5/3 Vincenzo
reply@reply.github.com:
