### ISSUE TITLE
Show version before login (or even opening emesene)

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1208]
I think would be cool to have the option to show emesene's version...
the --version option when running is enough...

So a simple:
./emesene --version

Shows version information...

I would submit the patch, but... I found that emesene version is declared in 2 places: 
/home/stive/emesene/emesene/gui/base/Handler.py
and
/home/stive/emesene/setup.py

And, I also checked, in this two files the version displayed is different, in setup.py is "2.12.2-devel"  and in Handler.py is 2.12.4-dev

To implement, I think, I'd just register the option in optionprovider and in _parse_commandline if the version option is enabled shows the version
`if options.version:
            print "Version: " + EMESENE_VERSION
            sys.exit(0)`

But, that EMESENE_VERSION, should be saved in somewhere, I just don't know where...
And, when you use in setup and in handler, could use this same place, like this you don't have 3 different places to change every time you create a new version... 
So, where things like these should be saved?

```
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- HEAD
+++ Modified In Working Tree
@@ -32,6 +32,19 @@
 extension.implements('option provider')(MinimizedOption)
 extension.get_category('option provider').activate(MinimizedOption)

+class VersionOption(object):
+    '''option parser'''
+
+    def option_register(self):
+        '''register the options to parse by the command line option parser'''
+        option = optparse.Option("--version",
+            action="count", dest="version", default=False,
+            help="Shows emesene version")
+        return option
+
+extension.implements('option provider')(VersionOption)
+extension.get_category('option provider').activate(VersionOption)
+
 class SingleInstanceOption(object):
     '''option parser'''
```

```

# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- HEAD
+++ Modified In Working Tree
@@ -237,6 +237,10 @@
         if options.minimized:
             self.minimize = True

+        if options.version:
+            print "Version: " + EMESENE_VERSION
+            sys.exit(0)
+
     def start(self, account=None):
         '''the entry point to the class'''
         windowcls = extension.get_default('window frame')
```

**Comment by c10ud** [comment]
Hello, the correct version is in Handler.py.

setup.py seems to be kind of outdated but that's for packaging
purposes only, it's not part of the program

2012/4/28 Stiveknx
reply@reply.github.com:

**Comment by c10ud** [comment]
closing this, i expect to see a PR about it soon ;)

**Comment by Stiveknx** [comment]
I tried to push a PR, but I keep getting a fucking 403 error --"

Anyway, try this patch:
http://pastebin.com/U5qyu31G

Description:
Allow users to check emesene version without have to login in ...
I put all information in Info.py, I hope it's the right way ...
