### ISSUE TITLE
[FEATURE] resize avatar in contact list?

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1211]
would be more convenient and a list would be more orderly and visible when loaded avatars are smaller or rather not upload their own avatar and remain the default gray emesene

http://i.imgur.com/Q3NTB.png

**Comment by Sbte** [comment]
There's an option for that in the preferences...

**Comment by c10ud** [comment]
@Sbte that's trayicon's contact list, i guess indicators do the resize for us automagically while for the gtk trayicon the avatars need to be scaled by hand OR we're resizing for indicators and not for gtk trayicon (note: i didn't check the code)
