### ISSUE TITLE
[Feature] View/Share foto

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#1214]
There is a feature in wlm to share foto without send it to the contact.

I've just received a message that sound like:
Contact said: a photo like this
[...silence...]
I Said: like what?
Contact said: The shared photo, can't you see it?

we should at least advise the user that the contact shared a photo or automatically return an advise to the contact that the feature is not supported by our client.

**Comment by Sbte** [comment]
Maybe we are missing some capabilities? I found this:

http://msnp-sharp.googlecode.com/svn/trunk/MSNPSHARP_DEV/MSNPSharp/enums.cs

@c10ud can be somehow disable SharingEnabled in ClientCapabilitiesEx? I think we only have the normal capabilities in papyon, and I don't know how this is used in msnp#.

**Comment by c10ud** [comment]
Looks like we miss the configuration of a lot of capabilites (cfr. papyon/profile.py), i can try adding them and disabling

**Comment by c10ud** [comment]
unrelated, we may need to change our addresses:

[13:07:31 INFO papyon.gnet.HTTP] Server moved to https://local-bay.contacts.msn.com/abservice/abservice.asmx
[13:07:31 INFO papyon.gnet.HTTP] <<< HTTP/1.1 301 Moved Permanently

[13:07:31 INFO papyon.gnet.HTTP] Server moved to https://local-bay.contacts.msn.com/abservice/SharingService.asmx
[13:07:31 INFO papyon.gnet.HTTP] <<< HTTP/1.1 301 Moved Permanently
