### ISSUE TITLE
[bug] tray icon context menu

### ISSUE THREAD

**Issue by jstrese** [emesene/emesene#1232]
Version: 2.12.3
OS: Windows 7 x64

When I right click the tray icon the context menu that appears will not go away without opening Emesene. I should be able to click anywhere on my desktop, the taskbar, open another context menu, etc to get rid of Emesene's tray icon context menu.

**Comment by lfottaviano** [comment]
I have a windows 7 available, when I can I will see how to solve this, thanks for reporting this issue.

**Comment by c10ud** [comment]
this is probably a bug in gtk, not emesene tho

**Comment by c10ud** [comment]
as in #784, can running emesene in xp compat mode be a solution to this?

**Comment by jstrese** [comment]
@c10ud xp compatibility mode doesn't appear to affect this issue.

**Comment by c10ud** [comment]
thanks for the feedback, seems we need someone with w7 to see if this bug can be workarounded or it's unavoidable because of gtk..

**Comment by lfottaviano** [comment]
This also happens on Windows XP.

On windows: 
`<gtk.gdk.Event at some_memory_direction: GDK_GRAB_BROKEN>`
this event is never emitted when pressing on desktop or whatever different to your app

Making a workaround for that, is not good, I have investigated the root_window thing, and better don't do it.

pepeleproso said, this should be fixed on gtk3 and on newer gtk2 versions, not available as windows binaries yet.

**Comment by c10ud** [comment]
we could find a workaround (e.g. connect to menu area leave signal, or something like that, like we do with smiley chooser in conversation window), but i'd also like to have windows build tools updated: is there any chance we can cook a preliminary build with updated libs?

**Comment by pepeleproso** [comment]
I try with latest gtk2 build and this problem is there.

**Comment by c10ud** [comment]
the good workaround to try is   5ab39a3

**Comment by c10ud** [comment]
WORKAROUND IN emesene/master:
i am giving the user some safety before hiding the menu in his face
just like the emoticon popup in conversation window does, just faster
since you're not always accessing the trayicon menu, i hope
when you leave the area of the gtk.Menu in gtk TrayIcon it starts counting
then after a second or two, if you're not back inside the area, it hides the menu
