### ISSUE TITLE
dev version ate input method's buffer

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1236]
For current commits, the buffer of input method (what I'm using is gcin) will be discard while enter pressed. The new function of up/down key will also trigger paste the history input into emesene.

The stable version of emesene works fine with gcin.

**Comment by Sbte** [comment]
I don't really understand what you mean. Could you please elaborate?

**Comment by moneycat** [comment]
In Chinese, we type-in the word by compositing its pronounce. As this image, the word "台灣" will be assembled in the input method's pop-up window. As this image: http://hyperrate.com/gcin-preselect.png (From gcin's site).

In the stable version of emesene, the words we typed in can be send to emesene via ENTER (and then type a enter again to send it to conversation). In the latest development version, Chinese input malfunctioned. The words in input method cannot be sent to emesene via ENTER, or the words be ignored via ENTER.

If I switch IM from Chinese to English, the function in IM which will sent the words in input's buffer still be sent to emesene as usual. Another observation is since I cannot normally use the IM, there are new functions in emesene's conversation windows. I can use up/dows arrow key to switch to the input history I had type-in in emesene.

I'll take some time to find out the correct committed version of this issue.
