### ISSUE TITLE
Spell Check on Windows

### ISSUE THREAD

**Issue by Ruk33** [emesene/emesene#1237]
It would be perfect if emesene comes with spell checker on "Windows".

Greetings and thanks.

**Comment by c10ud** [comment]
windows packagers would need to add some libs to the exe, not sure on the difficulty -- i'll leave this issue open so they see this and try to do it

**Comment by c10ud** [comment]
@pepeleproso did you happend to include gtkspell in the windows binaries?

**Comment by Sbte** [comment]
http://developer.pidgin.im/wiki/BuildingWinPidgin/Pre2.7.0#GtkSpellAspell
