### ISSUE TITLE
Fast file transfer doesn't work on windows (versus a WLM2009)

### ISSUE THREAD

**Issue by Katorce** [emesene/emesene#1239]
I try fast file transfer on emesene 2.12.3 (portable) on windows 7 pro x64 with default configuration (I didn't find an option to add a port) to send a file to a windows live messenger 2009 on windows vista x86 and it didn't work.
If you need more information please tell me what I've to do.

**Comment by c10ud** [comment]
-vvv output please

**Comment by Katorce** [comment]
I think I find another problem I cannot copy from the debug windows to other program, I do control+c or RBC-copy but nothing seems to work.

**Comment by Katorce** [comment]
Here you have the log:
http://min.us/mqPrEF2W5

I replace my user with xXxX, her user with yYyYy and @hotmail. qith @hotrnail.

**Comment by c10ud** [comment]
today i updated things a bit but there's still something wrong because
transfers don't start as expected
but that happens maybe because i'm sending through virtual machines (?)

2012/5/14 Katorce
reply@reply.github.com:

**Comment by c10ud** [comment]
should be fixed in git master
