### ISSUE TITLE
Contact buddy invite

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1242]
I dont think is the best solution...

I prefer nautilus for window: http://imageshack.us/photo/my-images/824/capturadeecrade20120510.png/

**Comment by jamesaxl** [comment]
what do you mean by nautilus  ?(window decoraor) cause nautilus is file manager

**Comment by zipatei** [comment]
Srry... yes, window decorator...

**Comment by zipatei** [comment]
or, instead of a window, we can integrate on the contact list.

**Comment by jamesaxl** [comment]
i use this way just for making Buddy invite in the top of every windows running, anyway i'm going to see if your idea will good

**Comment by zipatei** [comment]
somethink like to http://imageshack.us/photo/my-images/443/capturadeecrade20120511ay.png/

**Comment by jamesaxl** [comment]
ok done that's will be nice also

**Comment by zipatei** [comment]
The creation of this space, may give new ideas, such as information of a new version for example.

**Comment by zipatei** [comment]
And sorry @jamesaxl 

Your idea is good but not like not able to move the window. :(

But my suggestion if is possible, will be great. :D

**Comment by pepeleproso** [comment]
I think a windows with a decoration is the best idea here. I don't want to make the contact list taller than it's now.

**Comment by zipatei** [comment]
If @jamesaxl are willing to do it, why not create an option in preferences? Windows with decoration (default)

**Comment by c10ud** [comment]
no preferences, just restore the good old dialog please (unfortunately we cannot keep this up with bleeding edge stuff because Precise is gonna be around for 5yrs)

**Comment by jamesaxl** [comment]
@c10ud  it is done :)
