### ISSUE TITLE
Pressing shift+enter is sending the message instead of jumping a new line...

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1243]
In previous versions of emesene (and in others chats ), when pressing shift + enter you jump a new line, now it's sending the message..
It's a bug or something changed?

I'm using latest github version ...

**Comment by pepeleproso** [comment]
Sounds like a regresion in my gtk3 port, I will investigate this.

**Comment by pepeleproso** [comment]
I have a patch for this, I'll commit tomorow

**Comment by lfottaviano** [comment]
@pepeleproso  hadn't seen your comment

**Comment by pepeleproso** [comment]
no problem
