### ISSUE TITLE
Change icon status when you got offline and when reconnecting

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1244]
First, If you got disconnected the icon keeps as if you're online, well, you're not, I think it should change...

Second, when you're connecting the tray icon should represent that ...

**Comment by c10ud** [comment]
just tested with ubuntu 12.04, both trayicon and indicator, it works as expected (emesene guy icon returns instead of status icon)

please when reporting bugs test with latest git master

**Comment by Stiveknx** [comment]
I always test with latest git, also, I wait between commits before reporting too...

Well, since I'm having problems like with #1246, I'd say that the problem it's with the indicator...
The emesene icon here appears in indicator applet complete, and the package from ubuntu repository that provides the icon is `indicator-status-provider-emesene` version 0.6.0-0ubuntu1, so, using it the icon doesn't change and the tray icon doesn't blink ...

This package, has something to do with emesene?
Otherwise, I'll look for the responsible and report the bug, or use another option

**Comment by c10ud** [comment]
indicator-status-provider-emesene is messaging menu afaik.

**Comment by c10ud** [comment]
also, the indicator does NOT support blinking, and should not be used since ubuntu policy for IM is using the messaging menu
