### ISSUE TITLE
Blink Icon in systray

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1246]
The icon is not blinking anymore when you get a new message like the older versions (I think it's 2.10 or closer) ... 

Was removed, or it's broken?

(I think there was an issue for that, but was closed and the problem, not fixed).

**Comment by pepeleproso** [comment]
This is Gtk2 or Gtk3? Blink functionality was removed from gtk3 so we need to eventually remove that code.

**Comment by Stiveknx** [comment]
Gtk2 ...
I'm using gnome3, but with fallback session ...

**Comment by c10ud** [comment]
gnome3 fallback is still gtk3

**Comment by Stiveknx** [comment]
;s
I have both libraries installed here, not sure if is using 2 or 3 than...
My window theme is using a gtk2 theme, so I assume that I'm using gtk2 ;s

**Comment by pepeleproso** [comment]
yes, you are using gtk2, gtk3 only is activated using an env var when launching emesene.

**Comment by c10ud** [comment]
looks like Indicator and gtk trayicon are sort of broken..?

**Comment by c10ud** [comment]
just tried with ubuntu 12.04, blinking works.

just remember it only works when using (gtk) Tray Icon, not Indicators or Messaging Menu.
Messaging Menu is the default in ubuntu because of its guidelines, and TrayIcon are blacklisted by default (see also #803)
