### ISSUE TITLE
Notifications option

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1248]
There's the option to notify if the contact get's offline, in preferences > notifications, User event's

If the user check the option "Notify on contact offline", should have an option to "Notify only if there's an open conversation"

I don't wanna get notifications from all users, only if the user in my conversation gets offline, it's to avoid a "flood" of notifications

**Comment by c10ud** [comment]
i dont get this, if you have an opened conversation with the guy you'll see his status icon changing to offline so you won't need the notification (?) also, there are offline messages.

**Comment by Stiveknx** [comment]
You will see if your conversation with him is open, if is not you could receive a notification about that...

**Comment by c10ud** [comment]
wontfix (patches welcome as usual)

we already have offline messages that makes the "buddy is offline" thing useless, or if it is, you'll just see the offline emblem in conv window header.

if you instead want to have selective notifications, that's another request, see #1013
