### ISSUE TITLE
gtk3 login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1249]
Status icon after click connect, appear online and not "hide".

**Comment by pepeleproso** [comment]
I don't quite undestand this, why it should be hide? It doesn't show the correct icon?

**Comment by zipatei** [comment]
Well... Not hide... icon in gtk2 have gray for example... But in GTK3 not...

Preference icon works well

**Comment by zipatei** [comment]
Forget Me button works well also.

**Comment by pepeleproso** [comment]
so it's working? then we can close this

**Comment by zipatei** [comment]
Preference icon and Forget me button works well....

But status icon dont works to expected.

**Comment by zipatei** [comment]
http://imageshack.us/photo/my-images/208/statussk.png/

http://imageshack.us/photo/my-images/687/status1a.png/

**Comment by pepeleproso** [comment]
Oh, I see. It's strange because the buttons are using the same code. Actually the status button is correctly setting sensitive to False but it's not updating the image.
No idea if it's fixable, maybe we can override the draw signal and paint it ourselves but it's too much code.

**Comment by c10ud** [comment]
maybe it's a gtk bug/"design choice"?

**Comment by c10ud** [comment]
actually if you look carefully the only thing that's not set insensitive is the status button (for the status menu) the other two are just "more visible" than gtk2, but they're set insensitive correctly

**Comment by pepeleproso** [comment]
I'm closing this as there's no way to set the alpha of that button without a huge amount of code, with no much gain.
