### ISSUE TITLE
Incoming messages don't appear once the tab is closed

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#125]
Once you close a tab with a conversation with person X, there won't appear a new tab if the same person X sends another message. You do receive the notification, but no messages will appear. Now the are two cases which seem to happen at random.
1. You'll never be able to see two messages in a conversation window.
2. When you try to start a conversation with that person X (trough the contact list), you see a whole bunch of messages you missed. 

This is quite annoying, because if you're AFK (and don't see the notifications), you can't see if someone said anything to you.

EDIT: Just thought of something that might cause it. I had "Play sound on first received message" on and "Play sound on received message" off. Switching the latter on again fixed the issue.

EDIT2: Maybe it's that you spelling incoming wrong in several places as incomming?

**Comment by c10ud** [comment]
this bug could be a consequence of #126 and/or #129 can you try again now that they should be fixed? If still have problems, feel free to reopen this issue

**Comment by Sbte** [comment]
The message window pops up now, but you can't see the first message received. So if someone says

hey
how
are
you

and you close the windows between "hey" and "how", you only see

are
you

in the window that opens, and not "how". If you want I can open a new issue for this.

**Comment by c10ud** [comment]
yes, and please specify the OutputText you're using (adium or simple text)

**Comment by Sbte** [comment]
Seems fixed now. Most likely commit  6e9391729efdc362ade8

Oh, and just so you know, you're awesome for fixing everything so fast ;)

**Comment by c10ud** [comment]
oh, this must be linked to #54 then, i still need to find out a proper solution, because some weird thing is happening behind the scene..
