### ISSUE TITLE
GTK3 Conversation Toolbar Problem

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1250]
See image: http://imageshack.us/photo/my-images/838/capturadeecrade20120511.png/

**Comment by pepeleproso** [comment]
what's the problem there?

**Comment by zipatei** [comment]
It seems out of place.
Black line (weird rectangle).

**Comment by pepeleproso** [comment]
ahhh blame the theme works with adwaita. It's because ubuntu theme hasn't the style for inline toolbars. I will revert setting that style then
