### ISSUE TITLE
[GTK3 Suggestions] Bar - Add default separator

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1256]
Preference options:

1) http://imageshack.us/photo/my-images/833/50702512.png/
2) http://imageshack.us/photo/my-images/705/capturadeecrade20120511.png/

**Comment by lfottaviano** [comment]
expound what you want please.

**Comment by zipatei** [comment]
traces to set the standard.

For example:  http://1.bp.blogspot.com/-_rrT4ZIWTtw/T6JOtV7hydI/AAAAAAAAB9I/RtMLtm5Lw5U/s1600/Appearance_012.png

**Comment by pepeleproso** [comment]
that separator only, works on gtk3 I'll try to make a patch. Also I want to clean the conversation panel a bit.

**Comment by pepeleproso** [comment]
I was wrong that mark can be implemented on gtk2 too.
