### ISSUE TITLE
GTK3 PROBLEMS

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1261]
/usr/lib/python2.7/dist-packages/gi/module.py:142: Warning: g_array_append_vals: assertion `array' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:142: Warning: g_hash_table_lookup: assertion`hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python2.7/dist-packages/gi/module.py:142: Warning: g_hash_table_insert_internal: assertion `hash_table != NULL' failed
  g_type = info.get_g_type()
**
Gtk:ERROR:/build/buildd/gtk+3.0-3.4.1/./gtk/gtkstylecontext.c:739:timeline_finished_cb: assertion failed: (info != NULL)

I can not sign.

**Comment by pepeleproso** [comment]
this is a pygobject bug. I need to test if this commit http://git.gnome.org/browse/gobject-introspection/commit/?id=d055d35a873be5978d82df3955d859399c2e30d9 fixes that

**Comment by c10ud** [comment]
i got this once but i'm not really sure how it went away (!)

**Comment by c10ud** [comment]
ah, got it again! it looks like...random!

**Comment by pepeleproso** [comment]
This is a pygobject bug, but it's harmless, so I'm closing this. Please report upstream.

**Comment by c10ud** [comment]
Do you have this in arch?

2012/5/15 jose Rostagno
reply@reply.github.com:

**Comment by pepeleproso** [comment]
yes, but not the last part 
"Gtk:ERROR:/build/buildd/gtk+3.0-3.4.1/./gtk/gtkstylecontext.c:739:timeline_finished_cb: assertion failed: (info != NULL)"

I think that last part could be a theme engine problem

**Comment by c10ud** [comment]
Problem is, that it segfaults there..if you are in touch with pygi
devs it could be worth reporting it

2012/5/16 jose Rostagno
reply@reply.github.com:
