### ISSUE TITLE
[FEATURE] single window and someone contacts me

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1265]
would be a useful thing, when someone contacts us, and emesene window is minimized, 
there also appeared (as before) on the status bar as the window flashing, 
so you have greater visibility when a new message arrives there.

**Comment by Sbte** [comment]
As far as I know this should still work. It certainly does with Unity.

**Comment by KinG-InFeT** [comment]
I use fluxbox on gentoo and almost certainly still use GTK2.

**Comment by Sbte** [comment]
But the situation is still the same as before. When we receive a message and the window is minimized, the urgency hint is set.

**Comment by KinG-InFeT** [comment]
I saw the patch is applied ... but on my system the system prirità may not work properly ... and only the small icon blinks in the system tray.

**Comment by c10ud** [comment]
tested with unity and xfce, blame fluxbox
