### ISSUE TITLE
Content roaming not working.

### ISSUE THREAD

**Issue by 4javier** [emesene/emesene#127]
Linux, python 2.7, last git emesene2, last git papyon.
Launch emesene2→Log-in→change avatar→everything's ok.→close program.
Re-launch emesene2→avatar ok→log-in→wait a couple of seconds→avatar turns into the old one, setted by emesene1.

It seems like emesene2 saves the avatar just in local, and not on the msn server. Maybe a lack of papylib?

**Comment by c10ud** [comment]
getting dp from msn server:
[17:53:27 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from blufiles.storage.msn.com:80
setting dp in msn server:
[17:52:31 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from storage.msn.com:443
[17:52:31 WARNING papyon.service] Transport Error :500

**Comment by 4javier** [comment]
Judging by timings it must be read bottom-up, right? So the problem is effectively the setting method?

**Comment by c10ud** [comment]
i'm just telling you that's failing here. both setting and getting the dp.

you can try with latest commit if anything changed, but i doubt it!

**Comment by 4javier** [comment]
I already had last commit.

**Comment by c10ud** [comment]
i changed a little thing some minute ago though

**Comment by 4javier** [comment]
Probably I didn't notice the update. However nothing's changed.

**Comment by 4javier** [comment]
Ok, now I'm sure you modified something...conversation window stay totally blank...I have been able to chat just thanks to notify-osd :D

**Comment by c10ud** [comment]
about the avatar issue: i had the same issue, turns out my msn profile was completely broken, so i logged in once with windows live messenger, changed my avatar, nick, message and now it seems fixed

**Comment by 4javier** [comment]
But, since that access with wlm, you're now able to change your avatar from emesene2?

**Comment by c10ud** [comment]
uhm, seems like papyon is still receiving a 500 response. when trying to save the display picture. it needs to be notified upstream

**Comment by c10ud** [comment]
wait, actually it seems to work even saving

**Comment by 4javier** [comment]
I have no win installation to test that, I tried with ebuddy web messenger, but it seems didn't work. Let me know.

**Comment by c10ud** [comment]
try amsn, amsn and widows live messenger are the only which can probably fix the issue. if amsn doesn't work, only wlm can

**Comment by 4javier** [comment]
Ok, i'm bored. Various msn implementations seem to be almost crap (due to closed nature of the original, of course).
This is the actual situation (at least, as I've been able to find out)
Amsn save the avatar just locally.
Emesene2 too.
Emesene1, sometimes saves it on server, sometimes not.
.........
loading:
amsn doesn't load any image from server
emesene1 seems to do it
emesene2 is wonderful: first connections, image saved with emesene1. second connection, images previous saved locally with emesene2. third connection, new image saved by emesene1. fourth connection...the old image saved hours ago with emesene1!!!!
Amsn doesn't load the image form server

**Comment by c10ud** [comment]
maybe emesene-1 or <other-client> fucked up the profile on the server, try to reach a stable situation with wlm and it should be fixed once for all, all of these clients use a different implementation of dp roaming since microsoft likes to change once in a while.

**Comment by GVisconti84** [comment]
I should check more deeply but here it seema to have c10ud's behaviour: error but still saved

**Comment by ghost** [comment]
If it not possible to save the avatar on server... emesene2 should force to use the avatar saved locally -at login- (i think) keep it simple! (sorry for my english) (because emesene2 -at login- always download it from server)

**Comment by 4javier** [comment]
This should be just a workaround. Since it's not a critical issue, I think it's better to maintain the actual behaviour and try to really fix the problem. Otherwise it would be more difficult to debug.

**Comment by c10ud** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=31528 bug reported upstream with some different traces (multiple errors with multiple accounts, yay!)

**Comment by c10ud** [comment]
i fixed some stuff in emesene and some library fixes are on their way to upstream.

however, the ultimate-profile-fixer™ is here: profile.live.com/details/Edit/Pic
just change your pic there once, reload emesene and you're done, no more errors.

i think we could include this stuff in preferences, somewhere so users can easily fix their profile? there's need of a protocol-dependant settings tab to handle this kind of stuff and possibly other things like privacy tab.. it needs discussion

**Comment by c10ud** [comment]
Fix your profile directly from preference window! Closed by 3a32c5df316db2ba930871a092ccbdee128aaa2f

**Comment by 4javier** [comment]
Confirmed! Now it works perfectly. Thanks a lot Cloud.
