### ISSUE TITLE
Enable debugger in Jabber

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1271]
If you pass the option -vvv and try to use jabber, to connect with facebook, you don't get debug informations like in MSN...

You can enable by commenting out the line 71 in emesene/e3/Jabber/Worker.py

But, since the option -vvv is too make a lot of noise, I think it should enable the debug in jabber too.

**Comment by c10ud** [comment]
i want to get rid of xmpppy, see #1204

**Comment by c10ud** [comment]
done
