### ISSUE TITLE
Missing library of gupnp-idg?

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1273]
In ubuntu 12.04, emesene commit 6c15b07874a205640f179bdac2da7d0fb5bb8243

[18:17:36 ERROR papyon.msnp2p.transport.direct] Please install gupnp-igd >= 0.1.6 to get NAT traversal functionality

But in ubuntu, it seems it installed.
$ locate gupnp
.....
/usr/lib/libgupnp-1.0.so.4
/usr/lib/libgupnp-1.0.so.4.0.0
/usr/lib/x86_64-linux-gnu/libgupnp-igd-1.0.so.4
/usr/lib/x86_64-linux-gnu/libgupnp-igd-1.0.so.4.1.0
....

**Comment by c10ud** [comment]
python-gupnp-igd

**Comment by c10ud** [comment]
btw, this is completely untested

**Comment by c10ud** [comment]
r1c0efe1

**Comment by c10ud** [comment]
1c0efe16c730d8bddfa8ebfadfb65472d074c409
