### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1279]
```
Traceback (most recent call last):
  File "/net/users/ont/ont8020/emesene/emesene/gui/gtkui/TextBox.py", line 199, in on_key_press_event
    if not self.im_context_filter_keypress(event):
AttributeError: 'InputView' object has no attribute 'im_context_filter_keypress'
```

@moneycat

**Comment by moneycat** [comment]
@Sbte I can not reproduce this error but I'll add a check before it. Could you give me some re-produce steps if possible?

**Comment by moneycat** [comment]
@Sbte Can you try this ad0415cf4c4c8ac8ded97a7c3a986cd6f89158b1 for issue. Thanks.

**Comment by Sbte** [comment]
That would probably work, but it's really ugly. 

The bug happens on a system with the latest Debian stable btw. I won't be on that system until Monday. Anyhow, gtk_text_view_im_context_filter_keypress() was added in gtk 2.22 and that system has 2.20.

**Comment by moneycat** [comment]
Yes, it is ugly and it happened 3 times in code. Maybe I should extract it as a function or any suggestions?

**Comment by Sbte** [comment]
Well, the im stuff has been implemented since 2.16, so maybe you can fetch the context and call filter_keypress on that.

**Comment by c10ud** [comment]
@moneycat i think your solution is fine, if you can make one commit and open a PR i'll pull it

**Comment by moneycat** [comment]
Sorry for late. I'm making a move recently. I'll PR later.
