### ISSUE TITLE
Offline group contains all my contacts at reboot

### ISSUE THREAD

**Issue by 4javier** [emesene/emesene#128]
Linux, python 2.7, last emsene2 git, last papyon git.

Launch emesene2→ log-in→switch on Group Offline Contacts option→everything works→close the program letting the option flagged.
Re-lauch emesene2→log-in→all my contacts are shown into the Offline Contacts group, the online ones too. Could a sleep in the offline grouping at start help?

**Comment by Mystro256** [comment]
Same issue, offline contacts are shown and group offline contacts is on

**Comment by c10ud** [comment]
Workaround b_group_offline that puts everything in the Offline group at start. Closed by 8e5601e9be8794e92bcbe5190729f0a6fbcae1ff

**Comment by 4javier** [comment]
I didn't understand what this workaround do, but it works. :P 
Massive grouping under Offline is shown just for a second. Thanks.
