### ISSUE TITLE
multiple invites windows

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1280]
If more than 1 person adds you, I think It should be grouped into one single window, cause, if, for example 10 people added you, you have now 10 windows open...

All invites should stay in one single list and use scroll if the list is really big (Like when you don't login in msn for 2 months ...)

**Comment by pepeleproso** [comment]
Invites are currently grouped, see the arrows in the dialog, problem here is we need to check if that dialog is already shown and update it, or close it and display it again.

I add a test in dummy session last week to show this.

**Comment by Stiveknx** [comment]
In which version the invites started to be grouped? gg

**Comment by pepeleproso** [comment]
I think 2.11.7 or before I need to check git blame to be sure

**Comment by c10ud** [comment]
please check before posting

**Comment by pepeleproso** [comment]
there's a real issue here:

-When you open emesene you get the invite dialog.
-if you left the dialog open and someone invites you, we show other dialog instead of update the old one, then you got two or more dialogs
