### ISSUE TITLE
SingleWindow bugs - Title and conversation width

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1281]
1 -  If you close the conversation, the title is still the same as the contact name, not just "Emesene".
Let's say: I don't have any conversations open, the title is "Emesene". I open a conversation with "Bill Gates", the title changes to "Bill Gates". I close the conversation with him, the title is still "Bill Gates", instead of just "emesene".

2 - After e05b7a1394a86b4d9fdd0fc78410e0145d61edfd , I guess, the conversation width is 0, if the window is maximized... I mean, you can't see, it's just on the right position, really small

**Comment by Sbte** [comment]
2 - Any ideas on how to handle that?

**Comment by Stiveknx** [comment]
If you close emesene (send to tray) and open again, the size is normal...

I guess, when you ask to show the window the size is checked, but when you create a new conversation it doesn't ...

**Comment by Stiveknx** [comment]
Update: When I got a new conversation (if the other user opens it), also shows in the right side ...

**Comment by c10ud** [comment]
second issue should be fixed

**Comment by Stiveknx** [comment]
Yes, fixed!

**Comment by Stiveknx** [comment]
But when you get a new conversation, emesene crashes....

[11:58:59 ERROR e3.common.Signal] Signal handler (_on_started_message._on_started_message) error: 'NoneType' object has no attribute 'members'
Traceback (most recent call last):
  File "/home/stive/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/stive/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/stive/.config/emesene2/plugins/last_said/plugin.py", line 66, in _on_started_message
    if not (conversation.members[0] is None or conversation.is_group_chat):
AttributeError: 'NoneType' object has no attribute 'members'

I disabled lastsaid plugin, sure, but, before that there wasn't any problems...

**Comment by c10ud** [comment]
that's a plugin issue, unrelated to this

**Comment by Stiveknx** [comment]
Well, I think is good to change the title when the conversation is active...
Or, set the title and remove when closing all windows, or just keep changing the title saying "person x messaged you" ...
