### ISSUE TITLE
Error when close window in non-single-window mode

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1286]
Lastest commit. Non-single window mode.

Reproduce steps:
1. open a new conversation (two more are ok)
2. use ESCAPE to close tabs
3. on the last tab, escape key will not close whole window but the tab only
4. use mouse to close the conversation window and the error arise (cannot use esc to close t he window)

Traceback (most recent call last):
  File "emesene/gui/gtkui/Window.py", line 247, in _on_delete_event
    return self.cb_on_close()
TypeError: _on_conversation_window_close() takes exactly 2 arguments (1 given)

**Comment by c10ud** [comment]
btw: correct syntax is "Closes #id" otherwise github doesn't seem to pick it up

**Comment by moneycat** [comment]
Sorry. My fault. I'll keep in mind.
