### ISSUE TITLE
Spell Checker in Windows

### ISSUE THREAD

**Issue by kios** [emesene/emesene#1292]
Hi all, sorry for my English, I'm Spanish, I'm using GoogleTranslate, you can install the spell checker on Windows 7? since I can not make it work

Hola a todos, perdon por mi ingles, soy español, estoy usando googletranslate, es posible  instalar el corrector ortografico en windows 7 ? ya que no puedo hacerlo funcionar

**Comment by c10ud** [comment]
#1237
