### ISSUE TITLE
contact-list's scrollbar very "slow"

### ISSUE THREAD

**Issue by cando** [emesene/emesene#13]
As title said....

**Comment by marianoguerra** [comment]
slow as if a lot of processing was involved?

can you check if the cpu goes up when scrolling?

**Comment by cando** [comment]
yes...cpu goes up to 80%..other thing that i've noticed is that when i open a conversation also memory goes up a lot: if i open 5-6 conversation memory goes to 70 MB!!!The problem is that if i close the conversations, memory remains as it is....

**Comment by c10ud** [comment]
did you have some pixbufanimatin (with animations, not static imgs) in there? seems like gtk doesn't like animations that much, but i may be wrong

**Comment by cando** [comment]
yes..i've some animations (and i must fix/improve them...they still have lots problem....:) ). Anyway the scrollbar is slow also without any animations...even with no avatar picture (so only with default user icon) it's slow.
