### ISSUE TITLE
OutputText: Two messages on the same line

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#130]
With Output Text, if you receive a message and send one in the same second (I think), those two messages get on the same line. Like:

Person A: Hello Person B: Bye

Instead of 

Person A: Hello
Person B: Bye

Oh, and don't think I don't like emesene2 because of the huge load of issues I report here. I just report one when I come across it, hoping to make emesene better for everyone in the future ;) If there's anything I could do to make the reports better, please tell.

**Comment by marianoguerra** [comment]
I can't reproduce this, try using the dummy backend and talking to someone, they respond instantly and the problem doesn’t seem to occur

**Comment by Sbte** [comment]
Maybe it is because, if you receive a message from someone at the same time that you send one yourself, the message you receive was sent earlier, but received later. It takes a while to make this happen, unless you maybe have two computers next to each other, and I don't really have time to test it myself.

But actually, no idea. Maybe it's fixed already. I'm currently using Adium output, because it now works better anyways.

**Comment by c10ud** [comment]
adium ftw (closing till someone manages to reproduce it easily)
