### ISSUE TITLE
[Patch] Add icons to the search entry of contacts.

### ISSUE THREAD

**Issue by matiasdelellis** [emesene/emesene#1301]
Disclaimer: I am not python's developer. =)

Well.. Only a change of appearance that improves usability.

Add two icons: gtk.STOCK_FIND and gtk.STOCK_CLEAR and when you click the second icon clears the search entry.

http://dl.dropbox.com/u/9606612/Attachments%20for%20bugs/Add-iconstosearchentryofcontactlist.patch

p.s: It would also be interesting to leave the entry always visible, even optionally.

**Comment by Sbte** [comment]
Could you turn this into a pull request?

Also, why do you need

```
+        self.entry.set_icon_activatable(1, False)
```

To me it seems to work better without that.

**Comment by matiasdelellis** [comment]
Sure..
For this have to make a fork of github?

First is desensitized, and then sensitized according if has text on the entry or not.

> entry.set_icon_activatable(1, entry.get_text_length() > 0)

**Comment by Sbte** [comment]
Yes, just fork, push, and make a pull request.

Also, does it matter whether the icon is sensitized? If the entry is empty, it will just be set to empty again if you click it. Anyhow, maybe it's nicer, so you could just leave it :P

**Comment by c10ud** [comment]
git apply ftw

**Comment by c10ud** [comment]
my bad, git am ftw ;)
