### ISSUE TITLE
Keep-alive message errors flood the chat

### ISSUE THREAD

**Issue by flaviozavan** [emesene/emesene#1303]
Enable keep-alive conversations and try to chat with someone. The chat window gets flooded with "Error delivering message" and the terminal with:

[14:29:57 ERROR papylib.Events] Error sending message: 4 1

Or

[14:21:50 DEBUG papyon.transport] >>> MSG 11 N 44^M
    Content-Type: 'text/x-keep-alive'\r\n
    \r\n
[14:21:51 DEBUG papyon.transport] <<< NAK 11
[14:21:51 ERROR papylib.Events] Error sending message: 4 1
[14:21:52 DEBUG papyon.transport] >>> MSG 6 N 44^M
    Content-Type: 'text/x-keep-alive'\r\n
    \r\n
[14:21:58 DEBUG papyon.transport] >>> MSG 12 N 44^M
    Content-Type: 'text/x-keep-alive'\r\n
    \r\n
[14:21:59 DEBUG papyon.transport] <<< NAK 12
[14:21:59 ERROR papylib.Events] Error sending message: 4 1

---

I'm not sure, but I suspect it happens only with WLM users. It can be quite annoying because it doesn't take long for the error messages to hide the actual chat.

**Comment by c10ud** [comment]
actually, errors showing in chat are correct, the client is NAKing the keepalives, could be interesting knowing which client exactly is

from the trace you provided one client is accepting them, the other is naking them

**Comment by Sbte** [comment]
Maybe we should not show the errors if their content is not an actual message? That way we could also remove the haxes for typing messages. Or can't we do that?

**Comment by c10ud** [comment]
well, the client should ACK even the keepalives..if it isn't then
there's some issue with that client, or us?

2012/5/28 Sven reply@reply.github.com:

**Comment by c10ud** [comment]
closing since OP disappeared. if there's more info feel free to post

**Comment by flaviozavan** [comment]
I'm gonna experiment with a few different clients later this week and post the results here.
