### ISSUE TITLE
[Avatar, Contact Info, Conversation window] Contact Blocked

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1306]
When a contact is blocked, we can put the proper avatar (blocked) on the contact info and conversation window (side panel)?

**Comment by Sbte** [comment]
Well, the ultimate goal is to merge all avatar classes, because currently, this is a mess. I started that a while ago, but never had time to finish it. Maybe it should wait until after 2.12.5 though... But then I'll look into it.

**Comment by c10ud** [comment]
if facebook app was working i was planning on actually releasing 2.12.5 but.... oh well

**Comment by pepeleproso** [comment]
I fix the code to use the avatar widget, now we need to implement the blocked thing on it

**Comment by lfottaviano** [comment]
Is missing instant change, when you unblock the buddy, but you didn't ask for that. ( To be done :) )

**Comment by zipatei** [comment]
Not fixed yet... is missing implement in contact info.

And lfottaviano says is true. Missing instant change as avatar contact list.

**Comment by Sbte** [comment]
It isn't instant, because we want to reflect the status on the server. We change the avatar once the server tells us the contact is blocked. If we don't do this, we might get weird race conditions...
