### ISSUE TITLE
[Feature, Contact info - History conversation] Add Inline Search

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1310]
Its possible add inline search?

**Comment by jamesaxl** [comment]
@zipatei could you explain more please

**Comment by zipatei** [comment]
Something like the main window or gedit. You write and will get you in real time searches.

**Comment by c10ud** [comment]
i don't know if this is possible to do this but the idea is connecting key-press event in webkit's webview and link to search -- provided you know how to search stuff in a webview :)

**Comment by jamesaxl** [comment]
it possible cause webkit has methos for search , but after combined between chatwindo and contact it become impossible
https://gist.github.com/890640

**Comment by Sbte** [comment]
@jamesaxl not true. This has nothing to do with the main window. Just with the Contact Information window...

**Comment by c10ud** [comment]
plus, you still have webkit in there...?

**Comment by jamesaxl** [comment]
@sbte anyway i want to see your code wehn you implement it

**Comment by c10ud** [comment]
i now see contact info already has a search entry (thanks to another issue). 
the only thing that's missing here is focusing the search entry on keypress (with webkit focused)

volunteers anyone?

**Comment by Sbte** [comment]
This is not what this issue is about. It is about inline search, not about adding focus to our search entry.

**Comment by zipatei** [comment]
This is good, but...

Look at the behavior of Gedit.

When writing in the search combobox, gedit, begins to select all the words.

The color selection should also be changed to a color more striking.
