### ISSUE TITLE
Translate plugins

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1313]
Turn plugins translatable.

**Comment by c10ud** [comment]
if plugins stay out-of-tree then they need to be managed outside emesene, i don't think it's sane to include translations for plugins inside main emesene core. but, i wouldn't know how to manage i18n for plugins outside the program, especially given the fact that they can be updated at runtime... i don't think we can do something about this unless the whole plugin arch is rewritten (?)

**Comment by Sbte** [comment]
I could fetch them in my translations update script. Just clone them all in the plugins folder and scan for translations. Then they would be updated automatically.

That is, for the supported ones, not the  community ones.

**Comment by c10ud** [comment]
@Sbte so, what are you going to do? Add to the magnificent script or nothing?

**Comment by Sbte** [comment]
Probably. Maybe this weekend or so...

**Comment by Sbte** [comment]
@c10ud I remember that there was a problem with removing the `__init__.py` file in the plugins folder. Is that problem still there? Or can I just remove it?
