### ISSUE TITLE
[Discuss] Information for Single Window in Preference

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1314]
Will it be a better user experience to pop-up a information dialog to notify user for lost options? The dialog maybe shown as "Please enable Tabbed Conversations in Conversation Window preference" when user not enable the options.

**Comment by c10ud** [comment]
as @Sbte suggested we should probably enable that automagically
without even having to tell/warn the user

just: if b_single_window: then b_tabbed_convo=true

we could even remove the text warning; in the end it's logical that
single window means no multi window (?)

2012/5/30 moneycat
reply@reply.github.com:

**Comment by moneycat** [comment]
You mean if user enable single window, the tabbed conversation will be enabled automatically, right?

I've tried to make this work, but finally it failed. I don't know how to toggle the checkbox from MainWindow instance to ConversationWindow.

**Comment by Sbte** [comment]
`b_conversation_tabs` is used only 3 times in emesene code, so we could as well just do `b_conversation_tabs or b_single_window` in those places...

**Comment by moneycat** [comment]
@Sbte It so simple that I didn't think before. :P

So there still 3 modes in the future emesene version?
1. Single window (with virtually tabbed conversation enable)
2. Main Window with Tabbed conversations
3. Main Window with separated window of conversations

Maybe 'integrated mode' is more applicable than 'single window'?

**Comment by Sbte** [comment]
Single window is clearer the first time you read it I think.

**Comment by c10ud** [comment]
@moneycat yep, 3 modes
@Sbte agree

**Comment by moneycat** [comment]
I've done a new window mode selection in my local repository. The branch and commit is here: ca953e950940e8823e14ea537b95bb41aceb4dc5. If you have nothing to do in your free time, would you please take a look whether it is suitable. Thanks. :)

**Comment by c10ud** [comment]
commented inline

**Comment by Sbte** [comment]
This combo should probably be in the Conversation preference tab

**Comment by c10ud** [comment]
not sure, i coded them divided because they involved the entire
emesene and conversation, now it's really more a global decision than
a conv-specific one (?)

either way, i don't care about it

2012/5/30 Sven reply@reply.github.com:

**Comment by Sbte** [comment]
Me neither :P

**Comment by c10ud** [comment]
moneycat decides then

**Comment by moneycat** [comment]
@Sbte @c10ud  Maybe it is a good choice to put it into Conversation Window preference where the tab position can be controlled properly like: 44929b9352aa5eb4c13f600b0c4994f4564bb24b.

**Comment by moneycat** [comment]
Sorry to bother. I've done the change. Please give me any suggestion if there could be more better. Thanks a lot. Commit: 1cbd442c8b79bb271fa24e70231d4ae8b826c665

**Comment by Sbte** [comment]
You don't need self either. You just use it in the same function as where you assign it :P

**Comment by moneycat** [comment]
@Sbte Thanks. I remove almost all 'self' indicator except for https://github.com/moneycat/emesene/commit/3920cb0d2b1b931e133785ea673e04b25ae83624#L0R698. It will arise error if I remove it. The message is "AttributeError: 'ConversationWindow' object has no attribute 'int_mode'" on line 538 "obj = getattr(obj, attr)".

**Comment by Sbte** [comment]
Ok, yes. That's the weird combo stuff... I guess you could just add back the self then, or just fix the combo stuff to accept property_name=None and a different default argument. Adding back the self is easier I guess.

Sorry for that

**Comment by moneycat** [comment]
@Sbte That ok. Now I add back. The property_name affected in fill_combo to set active that now I choose not to modify it. Anyway, Thanks for comment.

**Comment by c10ud** [comment]
looks good to me, when you want we can merge it
