### ISSUE TITLE
(Today: May 30) Button to check messages in emesene didn't work (for a moment)

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1315]
Hello,

I am a regular user of emesene under Linux and every day I use the button to check unread messages in hotmail. Until yesterday, the action was working fine, i.e, I press the button and my browser opens my hotmail page without need to login with username and password. However, for some reason, today is not working; it says that the link is incorrect and I need to try again, so I need to enter my Windows Live ID and password. 

I don't know if this just a temporary problem with hotmail, or it is a change in the protocol (or something that needs a workaround for next version) and if this problem can be fixed. 

Thanks a lot.

**Comment by c10ud** [comment]
we didn't change anything related to that so i fear there has been somekind of change server-side.

however this might be temporary, let's wait a bit and see what happens

**Comment by c10ud** [comment]
p.s. here it works

**Comment by Sacolevas** [comment]
Here this is not working (I cleared browsing data, cookies, etc, just in case). I am using chromium as my browser if this might be helpful. Thanks again

**Comment by Sacolevas** [comment]
I restarted the computer and it worked again. Apparently, and I don't know if this has relation with this issue, the computer's clock was not in the right time and then I syncronized the time with a internet server before opening emesene again after restart.

**Comment by c10ud** [comment]
url creation indeed uses system time: see _build_url_post_data_new method in ..../papyon/msnp/notification.py
most probably the server identified an invalid time and rejected the login

glad to see you solved
