### ISSUE TITLE
(Request) Remove "Login as Invisible" option when logged in to a gtalk account

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1316]
Hello,

As far as I know, emesene (and basically every IM client I know) is a program that doesn't support invisibility for chat in gmail. I am not sure if the options of "busy", "away" and "idle" are supported. In case these options are not supported, it would be better in my opinion to remove them when you are going to log in to a gtalk account, just to avoid confusion and not giving the user the false idea that you can login as invisible to a gtalk account.  The same comments apply in case the same situation happens for facebook chat (I don't know).

Thanks for your attention.

**Comment by Sbte** [comment]
This will be fixed by https://github.com/Sbte/emesene/commit/5437b298f44dc6e76ec55adcff6038ecec7c789a

I'll push it in a second
