### ISSUE TITLE
Can I chat to my facebook friends (facebook chat) in emesene without being forced to have an username?

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1317]
Hello, this question is fairly easy for the developers and I apologize if this is the wrong place to ask this. But I would like to know of there is an option to use facebook chat without being forced to create a username. For privacy reasons, if you have a username you become easier to locate for people who are not your friends. That is a powerful reason why many of us have not created a username to chat for that reason. 

But perhaps, thinking in emesene as a external application that you can "authorize" in your facebook profile (similar to what Skype or Windows Live Messenger do) it might be possible to use emesene as a chat client for facebook, regardless if you have set an username or not.

Am I dreaming? is this possible? Or this feature request has no sense at all?

Thanks for your attention

**Comment by c10ud** [comment]
I think that would be an entirely different business compared to
current facebook-chat support. In fact, current support is based on
xmpp (which requires a facebook registration for IMs, etc.).
What skype has is most probably some facebook-specific API that allows
to interact with the service, but it's not plain and simple xmpp. We
also registered the emesene app for facebook for other various tasks
(unfortunately now it's broken but @pepeleproso is working on it) but
not for chats.

so my answer is: no, not possible.

but with all the privacy features you can easily have a facebook-chat
username and keep your privacy (even if facebook and
privacy........................... ;))

greets

2012/5/30 Sacolevas
reply@reply.github.com:

**Comment by pepeleproso** [comment]
Facebook only allow you to connect having a username, so we can do nothing.
See https://www.facebook.com/sitetour/chat.php for details.
