### ISSUE TITLE
Bug: Contacts that have logged out recently from msn appear online in my chat window

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1318]
Hello, 

In my computer the following has happened: 

I use my computer and log into my msn work account, use the program and then I log out and close the program.  Then I open emesene again, log into my msn personal account (which appear as contact in my other account) and my work account appears as online in my chat window!!!   

In order to experiment further, I choose the option of "appear offline to ..." in my hotmail page (in both accounts), hoping that when I log in, my other account won't appear as online, but the same problem happened. This happens regardless if I use emesene allowing multiple instances or just a single instance. I have tested and waited for more several minutes (more than 10) to log into my second account and still the other account appears as online.

I don't have an estimate on how much minutes do I need to wait in order to see my other account as offline; usually I needed to restart my computer and open the program again to see this solved. I also don't know if this would happen if I use the accounts in different computers, but definitely, this might be considered a bug.

Thanks for your attention again, today was the day of reporting issues!

**Comment by c10ud** [comment]
are you sure you're not signed in anywhere else? with multiple points
of presence the risk of having instances left opened somewhere is
there, and i sincerely don't know, given a number of endpoints, how
papyon (our msn library) choses the status to show to the user (e.g.
i'm signed in away here and online in another machine..which status
will be chosen? idk)

2012/5/30 Sacolevas
reply@reply.github.com:

**Comment by Sbte** [comment]
Eh, I think you're not actually closing emesene, just hiding it to the system tray. If you're using Ubuntu, emesene will hide in the Messaging Menu (Envelope in the top right of your screen). To properly close emesene, you need to use the menu, or first disconnect and then close the window. You can also choose to use a different tray icon.

**Comment by c10ud** [comment]
OP disappeared, closing issue. if you have more info feel free to post it anyway
