### ISSUE TITLE
Error when toggle "Mute sounds"

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1322]
Latest commit and extensions version.

Reproduce-step:
1. Open Preferences > Sounds
2. Toggle Mute sounds

If it is a new profile (account), there is no error. It will be issued since next login.

Issue: Related options not being no sensitive.

Error arise: 
Traceback (most recent call last):
  File "/emesene/gui/gtkui/Preferences.py", line 529, in on_toggled
    self.set_attr(property_name, checkbutton.get_active())
  File "/emesene/gui/gtkui/Preferences.py", line 553, in set_attr
    setattr(obj, terms[-1], value)
  File "/emesene/e3/common/BaseConfig.py", line 53, in **setattr**
    self.notify_change(item, value)
  File "/emesene/NotificationObject.py", line 42, in notify_change
    callback(value)
  File "/emesene/WeakMethod.py", line 31, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

This is first issued on commit 12b24809c8e503df6f59055160d9bf7d2a9eaf02. I've no idea why it is happened.

**Comment by pepeleproso** [comment]
the trayicon function wasn't property disconnected when we change the trayicon extension. fixed by commit https://github.com/emesene/emesene/commit/78431ed663d79bcc7130b16bf530c1d51409ee3c

**Comment by moneycat** [comment]
@pepeleproso It is solved in 'Tray Icon' but failed in 'Message Menu' and 'Indicator'

AttributeError: 'MessagingMenu' object has no attribute 'unsubscribe'
AttributeError: 'Indicator' object has no attribute 'unsubscribe'

**Comment by moneycat** [comment]
Also failed on 'NoTrayIcon'. Need more information?
