### ISSUE TITLE
Disconnect endpoints did not set proper name

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1323]
In two different computer, login into the same account. The main menu shown blank name and it will cause two endpoints are disconnected.

There's no `PrivateEndpointData` in `_handle_UBX` function.

**Comment by c10ud** [comment]
two computers two emesene?

that could probably be a consequence of the fact we always choose "emesene" as an endpoint name and, as far as i see, that doesn't even work in papyon..............................

**Comment by moneycat** [comment]
Yes. Two computer, two emesene. We are not owner of the login account so we can not fetch Private data...strange...

**Comment by moneycat** [comment]
If I change https://github.com/emesene/emesene/blob/master/emesene/e3/papylib/papyon/papyon/profile.py#L1010 to `self.name = str(id)` the two ep will be shown and can be disconnected separately.

**Comment by c10ud** [comment]
nice find! please check that it shows webmessenger correctly and if it works it's good!

**Comment by moneycat** [comment]
@c10ud The web messenger works fine because the data is retrieved with `PrivateEndpointData`. If use `str(id)`, the name becomes an uuid...so...ugly :P

**Comment by c10ud** [comment]
oh ok, then the issue persists: emesene isn't setting endpoint name

**Comment by c10ud** [comment]
(see  
      self.profile.end_point_name = "emesene" #TODO: FIXME: This does not seem to work

in emesene/e3/papylib/Worker.py

but the bug must be in papyon

**Comment by c10ud** [comment]
Ah! maybe i found the culprit! ep name is set too early, let me check

**Comment by moneycat** [comment]
It sent UUX of EndpointData and PrivateEndpointData but failed to get the other machines' Private data.

**Comment by c10ud** [comment]
i'll add a thing in preferences so the ep name can be configured!

**Comment by moneycat** [comment]
@c10ud I think the problem not solved completely. The two computer and two emesene now has different ep name. One of the client will show a blank name and no function when click. The other one show 'emesene' and will close both client.

**Comment by c10ud** [comment]
yea i now noticed this weird thing too..

**Comment by c10ud** [comment]
i see the client receives empty endpoint name (?), and the other fails, maybe i am doing some weird thing with config?
like asking for config when it's not ready yet and setting the same name (== FAIL) ?

**Comment by c10ud** [comment]
if hardcoding a different ep name works, then it's a config issue (like..config not loaded yet...?)

**Comment by moneycat** [comment]
After the previous patch, there are private data (which is correct and it should be there). But there are duplicated guids between EndpointData and PrivateEndpointData. Is it cause the issue?

**Comment by moneycat** [comment]
Oops 2349eaa broken

**Comment by c10ud** [comment]
i think that if two endpoints have the same name everything clashes, anyway now i think that if you set different names in the two clients it should work

**Comment by c10ud** [comment]
aw sorry, i have network issues atm so i am pushing without proper testing

**Comment by moneycat** [comment]
oops...my git references are broken...let me reset it...

**Comment by c10ud** [comment]
i see now it's loading the correct ep name..but other endpoints are receiving an empty name..

**Comment by moneycat** [comment]
humm...The second login one is correct...

**Comment by moneycat** [comment]
@c10ud Maybe it is related to the timing the ep name be added into the menu?

I print the end_points[keys] each call and found there are several attempts and it is blank string in the first few call.
Now the second emesene login:
ASUS
end
ASUS
            <- got a blank
end
'  "   <-- this is printed in `endpoint_added`
ASUS
          <- second call still got a empty string
end
ASUS
I am x201
end
                    <--- the `endpoint_add` should be processed here

**Comment by c10ud** [comment]
maybe we should just ignore blanks..? what do you think? if name == "" then return

**Comment by moneycat** [comment]
It is strange that the subscribed function should be called all the time it changed. The signal in MainMenu just work once...

**Comment by c10ud** [comment]
please note papylib/Session.py
        # we fire the event for every endpoint because otherwise we lose
        # endpoints that were present before we logged in
        for endp in self.__worker.profile.end_points.values():
            self.__worker._on_profile_end_point_added(endp)

this is done once tho

**Comment by c10ud** [comment]
anyway, i see ep name is still empty when the ep notification is received from the other emesene

**Comment by moneycat** [comment]
It seems it's a complex work-flow of endpoints :(
In my console, the ep_name will be fetched in the third time UBX data received.

The codes are in the load_config section of Sessions.py, so it will be called only when emesene launched?

**Comment by c10ud** [comment]
no, after that "first pass" then it's handled by ProfileEvents in PapyEvents.py signals

but i suspect there's something wrong in papyon's code that gives emesene empty names for endpoints (see handle_UBX in papyon/msnp)

**Comment by c10ud** [comment]
precisely, looks like the issue lies after handle_UBX because if i print end_points there, the names are showed correctly but then emesene receives name = ""

**Comment by moneycat** [comment]
The handle_UBX was called more than three times and the first two are empty name.

**Comment by moneycat** [comment]
The pep data of the second login is ready in the third UBX data...interesting...

**Comment by c10ud** [comment]
[19:28:02 DEBUG papyon.transport] <<< NLN NLN 1:qwertyzx@hotmail.it qwertyzx@hotmail.it 2687500288:0 0
[19:28:02 DEBUG papyon.transport] <<< UBX 1:qwertyzx@hotmail.it 487
    [payload]
**\* emesene-tAST1338829765.48 <papyon.profile.EndPoint object at 0x34d4190> <<< NON EMPTY!
[19:28:02 INFO papyon.profile] Set contact qwertyzx@hotmail.it flags to 1

> > > added endpoint <papyon.profile.EndPoint object at 0x34d4310>  5753e587-f4f4-4bc3-a643-c9f77c0198eb
> > > [19:28:02 INFO papyon.protocol.switchboard] New end point connected, re-invite local user
> > > [19:28:02 DEBUG papyon.transport] >>> CAL 2 qwertyzx@hotmail.it
> > > [19:28:02 INFO papyon.protocol.switchboard] New end point connected, re-invite local user
> > > [19:28:02 DEBUG papyon.transport] >>> CAL 2 qwertyzx@hotmail.it
> > > [19:28:02 INFO papyon.protocol.switchboard] New end point connected, re-invite local user
> > > [19:28:02 DEBUG papyon.transport] >>> CAL 1 qwertyzx@hotmail.it
> > > [19:28:02 INFO papyon.protocol.switchboard] New end point connected, re-invite local user
> > > [19:28:02 DEBUG papyon.transport] >>> CAL 5 qwertyzx@hotmail.it
> > > **************\* ADDING ENDPOINT <empty>

**Comment by moneycat** [comment]
[01:25:39 DEBUG papyon.transport] <<< NLN NLN 1:xxxxx@live.com ooooo 2687500288:0 0
[01:25:39 DEBUG papyon.transport] <<< UBX 1:xxxxx@live.com 503
    [payload]
start
ep c665d9a2-0f3c-479d-bf8c-e95b823fe190  x
ep bb1ea26e-0e98-4568-8343-5a4c8df50cb7  x
pep bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS x
result
bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS
c665d9a2-0f3c-479d-bf8c-e95b823fe190 
end
[01:25:39 INFO papyon.profile] Set contact xxxxx@live.com flags to 1
 ;   <--- here trigger the `endpoint_added`
[01:25:39 DEBUG papyon.transport] <<< NLN NLN 1:xxxxx@live.com ooooo 2684354560:0 0
[01:25:39 DEBUG papyon.transport] <<< UBX 1:xxxxx@live.com 503
    [payload]
start
ep c665d9a2-0f3c-479d-bf8c-e95b823fe190  x
ep bb1ea26e-0e98-4568-8343-5a4c8df50cb7  x
pep bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS x
result
bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS
c665d9a2-0f3c-479d-bf8c-e95b823fe190 
end
[01:25:39 INFO papyon.profile] Set contact xxxxx@live.com flags to 1
[01:25:39 DEBUG papyon.transport] <<< UBX 1:xxxxx@live.com 678
    [payload]
start
ep c665d9a2-0f3c-479d-bf8c-e95b823fe190  x
ep bb1ea26e-0e98-4568-8343-5a4c8df50cb7  x
pep c665d9a2-0f3c-479d-bf8c-e95b823fe190 I am x201 x
pep bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS x
result
bb1ea26e-0e98-4568-8343-5a4c8df50cb7 ASUS
c665d9a2-0f3c-479d-bf8c-e95b823fe190 I am x201
end
[01:25:39 INFO papyon.profile] Set contact xxxxx@live.com flags to 1

**Comment by c10ud** [comment]
i think it's firing the endpoint-added event too early when the first UBX is received and ep doesn't have a name yet

**Comment by c10ud** [comment]
problem is that i don't know the correct procedure: papyon sends two UUX one with client_id and one with ep data.. don't know about the Windows Live Messenger way to do it (maybe THIS is the way and we need to fix papyon?)

**Comment by c10ud** [comment]
according to here http://code.google.com/p/msnp-sharp/wiki/KB_MSNC12_BinaryHeader two UUX are fine, maybe we need to instruct papyon to send the endpoint-diff message only when PrivateEndpointData is received!

**Comment by moneycat** [comment]
Monitor the PrivateEndpointData and trigger the `endpoint_added` action for menu?

**Comment by c10ud** [comment]
since for notifying emesene it's diffing between old-endpoints and new-endpoints i thought of a simple: if ep doesn't have a name and it's new remove it from ep (so when the name is reecived the notification is triggered again)

**Comment by c10ud** [comment]
```
def _server_property_changed(self, name, value):
    if name == "client-capabilities":
        value = ClientCapabilities(client_id=value)
    attr_name = "_" + name.lower().replace("-", "_")
    old_value = getattr(self, attr_name)
    if value != old_value:
        setattr(self, attr_name, value)
        self.notify(name)
    if name == "end-points":
        self._diff_end_points(old_value, value)

def _diff_end_points(self, old_eps, new_eps):
    added_eps = set(new_eps.keys()) - set(old_eps.keys())
    removed_eps = set(old_eps.keys()) - set(new_eps.keys())
    for ep in added_eps:
            self.emit("end-point-added", new_eps[ep])
    for ep in removed_eps:
        self.emit("end-point-removed", old_eps[ep])
```

i think we must check if there's an endpoint without a name and remove it from the already-received instead of emitting the signal (papyon/profile.py)

**Comment by moneycat** [comment]
I've written an untested patch of papylib: 56ddf9f9f14950bdaa05dc4871cead0a3d222e8c. I'll test it after school today.

**Comment by c10ud** [comment]
i tested it briefly and looks like it's working, well done

**Comment by moneycat** [comment]
@c10ud I'm rewriting the codes to support the same ep_name.

**Comment by moneycat** [comment]
@c10ud I've done the code. If you have time, test it please: fcfe56090bb9fbf968437c45e74512091ba81734.

There is a fool to erase the code by `reset --hard` and retyping the code again. :P

**Comment by moneycat** [comment]
force push for an error indent: d3ad9b37a76fc5296f93bef535d38f8953b99dec

**Comment by c10ud** [comment]
it's not connecting here unfortunately so i cannot test but if you tested it and it works, it's good for me

**Comment by c10ud** [comment]
what i don't particularly like is that gui receives an endpoint object, maybe a tuple (id, name) would be better

**Comment by moneycat** [comment]
@c10ud In my environment it works fine. I'll commit it sooner if there is no error arise. :)

**Comment by moneycat** [comment]
OK. f1de51d4f556761fa6797cc76273661187602c21 and it works too. Thanks for comment.

**Comment by c10ud** [comment]
looks good
