### ISSUE TITLE
Unable to translate some strings

### ISSUE THREAD

**Issue by hiunnhue** [emesene/emesene#1326]
Unable to translate some strings on Launchpad.

Preferences > Conversation Window: Layout, Appareance, Behavior ... etc.

**Comment by Sbte** [comment]
They will be made translatable after the next translation synchronization. I do those every Saturday. Making this automatic is blocked by this:

https://bugs.launchpad.net/launchpad/+bug/402814

**Comment by Sbte** [comment]
They should be translatable now
