### ISSUE TITLE
Case to broke nick and message display

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1328]
Set `')` as nick or personal message, the render will brake. The result of `format_nick` in emesene/gui/base/ContactList.py is correct.

I found that it is due to the `')` will be translate to `&apos;)` and before displaying the `;)` will be translate to an emoticon. The trsanlate emoticon procedure may be done after the `&apos;)` reverse to `')`.

**Comment by Sbte** [comment]
We can't do this easily, because we need to escape before we apply Plus tags, and we need to apply Plus tags before emoticons because we need to parse the whole string.

**Comment by moneycat** [comment]
@Sbte I've an ugly hack for this issue. Please take a look if you have free time. Thanks. Commit: 44d0dbc3ee0afec66960ba6075574f7c1a10717d.

**Comment by moneycat** [comment]
Oops, still some bug...

**Comment by moneycat** [comment]
OK, the final hack: a8cd2ac582d5d153956194ca4518dd65a394ab08

**Comment by Sbte** [comment]
With your commit the dummy session is broken.

**Comment by moneycat** [comment]
Yeah. I found some bug for rendering. it is really so hard :P

**Comment by Sbte** [comment]
Maybe we can parse only the unescaped string for emoticons and then don't escape it again, but instead escape only the emoticon strings and apply that on the original string. That should work.

**Comment by Sbte** [comment]
Btw, to do that, you can use the methods in gui.base.MarkupParser. If I get home before you get into t I'll try to fix it ;)

**Comment by moneycat** [comment]
If we first split the text by emoticons but not to do close_tags first, I have no idea how to copy the open tags to the reset substring. For example, `text='<span>0&apos;)1;)2:)3</span>'`, the text_list is `[u'<span>0&apos;)1', <gtk.gdk.Pixbuf object>, u'2', <gtk.gdk.Pixbuf object>, u'3</span>']`. If I can find a way to re-produce the open-tags in `text_list`, it should be work.

**Comment by moneycat** [comment]
@Sbte This is my test code for this issue: ca710df658f89787dd9cc51b3160e19bebe046fd

**Comment by moneycat** [comment]
remove unneeded logical for index 7df62309f0662212264b8ea8e7ab9e06fc08ff7c

**Comment by Sbte** [comment]
Breaks dummy even harder...

**Comment by moneycat** [comment]
@Sbte I think this patch could not solve this issue completely :P Another problem due to the `partition` function will cut in wrong position of escaped string and generate a wrong `text_list`.
case 1: `')")&apos;&quot;:)(H);)&quot;&apos;")')` --> correctly
case 2: `1:)2;)3')4')5;)6:)7` ---> broken

Could you give me some error message of my solution? My dummy works fine and I have no idea where it broken, thank you. :)

**Comment by moneycat** [comment]
Here is my commit: a2a0603f6bfcea1616b67384d9fd3477d3f13396, corresponding dummy test: 921088dcf714a76d1e5ad755c34222d6b387fb92 and screenshot: http://imageshack.us/photo/my-images/33/screenshotat20120609112.png/ .

**Comment by Sbte** [comment]
ten is broken with your commit

**Comment by moneycat** [comment]
@Sbte  ok, i got it.  Thanks. :)

**Comment by moneycat** [comment]
I forgot to check the overlapping. Here it works: 85702aa18eaaf47a7d44cdaabc649d2ef5c08293

**Comment by moneycat** [comment]
@c10ud Thanks to close it. I forgot to use the correct format. Sorry.
