### ISSUE TITLE
Single Window Mode: Allow conversation window to open to the left of main emesene window (contact list)

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1329]
Hello, 

I am using emesene 2.12.5 and the following situation prevents me from using the new Single Window Mode: Usually, I place the main emesene window (contact list) to the right of my screen. Consequently, if I use a docked mode, I would like to see the  chats open to the left of the main window. Otherwise, if they open to the right, the main emesene window changes its location (it moves to the left), so when the conversation is closed, the main window is located approximately in the center of my screen.

If someone puts the main window to the left of the screen, for example, this behavior is perfect, because new conversation does not change the main window location. But a lot of people, including me, doesn't act that way, So, emesene could have an option to let the user decide at what side (left, right) he/she wants conversations to open with respect to the main window.

Thanks a lot for this new version and listen to us! I feel proud to see solved some of the issues I have reported here (for example, don't allow setting status before login with xmpp). 

Thanks for your attention.

**Comment by Sacolevas** [comment]
Hello, I have seen that this topic was labeled as a "singlewindow" issue, but I don't know if this means that someone is going to work on this. And nobody has reply to this topic, so I am worried that actually no one else considers this as a problem or as a feature request. 

Thanks for your attention :)

**Comment by Sbte** [comment]
We need to fix the segfault first. Then we can start considering implementing new stuff :P

**Comment by c10ud** [comment]
it can be done, but it's not so easy mostly because the resizing code is quite obscure, other than that is just a matter of inverting the packing of the widgets

**Comment by c10ud** [comment]
I tried again, but looks like there's something in gtk itself that prevents this from working as expected, I cannot get proper positioning or resizing/growing of widgets on the left.

e.g.
https://mail.gnome.org/archives/gtkmm-list/2004-February/msg00250.html
