### ISSUE TITLE
AvatarManager class should stay in gui.base

### ISSUE THREAD

**Issue by GVisconti84** [emesene/emesene#133]
95% of this class' code is toolkit independent. I think it should be moved in gui.base, so it can be reused in other frontends.
Two abstract methods could be added, one to resize a display picture, and one to save it, in place of the following parts:

```
# Resize to 96x96
pix = pix.scale_simple(96, 96, gtk.gdk.INTERP_BILINEAR)
pix.save(fpath, 'png')
return pix, fpath
```

.
    # Save in 96x96 
    pix_96 = utils.safe_gtk_pixbuf_load(filename, (96, 96))
    pix_96.save(fpath, 'png')
    return pix_96, fpath

**Comment by marianoguerra** [comment]
agree

**Comment by GVisconti84** [comment]
Good :)
I can do this and open a pull request if you want (Tomorrow :D Now I'm going to bed ;))

**Comment by GVisconti84** [comment]
I was taking a closer look to the code, and I found that toolkit specific code is completely related to image manipulation: loading, saving, resizing, checking if animated.
So I thought that it would be better to make AvatarManager class concrete, and to create another abstract class that manipulates the images, with this interface:

```
class AbstractAvatarPictureHandler (object): 
    def __init__(self, filename):
        '''Constructor'''
        raise NotImplementedError("Method not implemented")

    def resize(self):
        '''Resizes to 96x96 the given avatar pix'''
        raise NotImplementedError("Method not implemented")

    def save(self, filename):
        '''Saves to disk the given avatar pix'''
        raise NotImplementedError("Method not implemented")

    def is_animated(self):
        raise NotImplementedError("Method not implemented")
```

I thought that this class should inherit gtk.gdk.Pixbuf in the gtk gui and QtCore.QPixmap in the Qt one. Unfortunately gtk.gdk.Pixbuff doens't have a from-filename constructor (there's a function that constructs a Pixbuff from file) so `__init__` implementation can't be straightforward and I'm not a gtk guru.

How can we solve this? Maybe we should consider a solution that considers issue 93 too, creating a PictureHandler class (name it whatever you like) instead of AbstractAvatarPictureHalder, handling loading/saving/resizing in a toolkit independent way, o in a easily subclassable way.

**Comment by c10ud** [comment]
yes gtk sucks a bit on this one... your idea is really valid (maybe it requires a little work but..)

**Comment by GVisconti84** [comment]
Seems like that the `pix` argument returned from `add_new_avatar` and `add_new_avatar_from_pix` is never used... Is that correct?
Could it be removed?
If we want to move `AvatarManager` in `gui.base` module it would be nice to have to deal just with filename in its interface (While internally it could still use the `PictureHandler-or-name-it-whatever-you-like` class I proposed previously)

**Comment by GVisconti84** [comment]
OUCH! I've closed this issue by mistake -.-'

**Comment by c10ud** [comment]
yes whisky, i've just checked and you're right (also, reopened the issue)

**Comment by GVisconti84** [comment]
In the meanwhile I've discovered that `pix` is used in `AvatarManager.set_as_avatar`, but I think that that code portion could be changed from:

```
else:
    try:
        pix_96, fpath = self.add_new_avatar(filename)

        self.session.set_picture(fpath)
        if os.path.exists(self.avatar_path):
            os.remove(self.avatar_path)
        if pix_96 != None:
            pix_96.save(self.avatar_path, 'png')
        else:
            #FIXME temporaney hack for animations
            shutil.copy(filename, self.avatar_path)
    except OSError, error:
        print error
```

to:

```
else:
    try:
        fpath = self.add_new_avatar(filename)

        self.session.set_picture(fpath)
        if os.path.exists(self.avatar_path):
            os.remove(self.avatar_path)
        shutil.copy(fpath, self.avatar_path)
    except OSError, error:
        print error
```

The picture is saved by `add_new_avatar` in the file specified in `fpath`, and that file is in cached_avatars dir, right? No need to save it again, it is enough to copy the file I think :/

Sorry if ask continuously for your advice, but when I edit other people's code I always fear to break everything in a million pieces :D I prefer to be sure ;)

**Comment by c10ud** [comment]
don't worry, just make your modifications.. if some error arises, we'll just fix it (sooner or later)

**Comment by c10ud** [comment]
so, we can close this issue
