### ISSUE TITLE
[Bug - Notifications] Online/Offline Notifications

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1331]
- First

Reproduce:

1) I'm offline.
2) Contact buddy turn online (hear the warning sound. Notification doesn't appear.)
3) Contact buddy turn offline (hear the warning sound. Notification doesn't appear.)
- Second

For greater consistency of preferences, in Sounds put user events in first and after messaging events as soon Notifications.

**Comment by Sbte** [comment]
First: You probably have "Only when available" enabled. In that case it's a feature.

**Comment by zipatei** [comment]
@Sbte Oh exactly... in this case i think we should put this option in Geral, because means for all events.
