### ISSUE TITLE
[Feature] Add Endpoint Notification

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1332]
After this https://github.com/emesene/emesene/commit/9127ad6b36bf7a00b72ead507c41566325ef0291

Is possible to add Endpoint Notification?

**Comment by Sbte** [comment]
I guess so

**Comment by matiasdelellis** [comment]
Also can hide the menu when no other connections.. =)

**Comment by moneycat** [comment]
@zipatei Do you mean popup an notification snd show "You are now login from another place" or could you give me some more detail of what you need please. :)

@matiasdelellis I've test to make the 'All other points' options masked previously but have not commit yet. Is this feasible of your need? :)

**Comment by zipatei** [comment]
@moneycat exactly. :)

**Comment by moneycat** [comment]
Hi all, please give me some suggestion of this prototype from this branch https://github.com/moneycat/emesene/commits/ep_changed/ thanks

**Comment by c10ud** [comment]
code looks good, go ahead

**Comment by matiasdelellis** [comment]
I said hide the "File > disconnect other sessions" submenu when no have other sessions.. It's just a detail, but the notifications that you already made ​​are important for security.

Thanks. =)

**Comment by moneycat** [comment]
@matiasdelellis got it. I'll close this issue and then push another commit for your request later because of the major topic of this issue.

**Comment by matiasdelellis** [comment]
I agree. The important is done.
Sorry that add off topic requests.. =)

**Comment by moneycat** [comment]
@matiasdelellis That's OK. I also want to do this for a long time. Thank you for requesting. :)

**Comment by Sacolevas** [comment]
I have a question: It is possible to add Endpoint Notification to facebook chat and close other endpoints like in msn chat? Thanks

**Comment by moneycat** [comment]
@Sacolevas It probably be when the protocol support this feature.
