### ISSUE TITLE
High CPU usage whilst connecting to Facebook

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1334]
emesene 2.12.5, OS X 10.7.4

emesene is using 110% CPU when connecting to Facebook. CPU usage is normal whilst on login screen and once connected

This is preventing me from releasing the OS X build

**Comment by pepeleproso** [comment]
This happen in the windows build too. Sleekxmpp is the culprit here, but I cannot found where the hang is.

**Comment by joshf** [comment]
Thought it might be. Should I release the OS X build anyways?
------Original Message------

**Comment by c10ud** [comment]
@joshf yes please, go ahead

@pepeleproso 100% sure it's sleek and not me haxing contactlist code in Worker? if you have tons of friends, tons of cpu will be used........?

**Comment by pepeleproso** [comment]
well I have about 150 friends, so the contactlist code could be the problem too.

**Comment by joshf** [comment]
I've around 250, so c10ud's suggestion would make sense

**Comment by c10ud** [comment]
If you could try commenting out the part in which contacts are being created and added to contact list in xmpp/Worker.py you could see if that's the culprit.

however if that's the issue i don't really see a way to solve it.. (?)

**Comment by pepeleproso** [comment]
For me it keep waiting in def _session_started(self, event): in this call self.client.get_roster(block=True). Probably because it's a big xml roster. Maybe we need to find a way to run that function while we continue with the UI loading.

**Comment by Sbte** [comment]
Doesn't the session run in a different thread?

**Comment by pepeleproso** [comment]
@joshf could you try this patch https://github.com/pepeleproso/emesene/commit/d681018c769bef2803fbb0a44ab723a956b2d908

**Comment by joshf** [comment]
@pepeleproso tried your patch. CPU still hitting 108%. The patch seems to take you to the contact list quicker, but it still takes about 20 seconds to actually load the contacts. During that time CPU is high

**Comment by c10ud** [comment]
we should probably ask the SleekXMPP guys...?

**Comment by joshf** [comment]
Agreed this makes Facebook unusable
------Original Message------
