### ISSUE TITLE
File transfers don't work for some configurations

### ISSUE THREAD

**Issue by AlineFreitas** [emesene/emesene#1335]
I'm using ubuntu and I've recently updated from the ppa to this version. before, file transfer was working smoothly

When I tried sending, got this error:[..]

**Comment by c10ud** [comment]
please run emesene -vvv so we can see what really happened. 
reading this i see a bunch of switchboard errors and some transport mismatch... but no useful information for debugging (transfers are almost untested) 
also please include if you were sending or the other party was, and which client was your buddy using

**Comment by AlineFreitas** [comment]
Sorry for the latency, I was disconnected for 2 days. But here its the output:
http://pastebin.com/MfTR3igR

**Comment by c10ud** [comment]
np, but i don't see any error in the trace, someone else maybe spot something?

2012/6/15 Aline de Oliveira Freitas
reply@reply.github.com:

**Comment by AlineFreitas** [comment]
Weird, because the file transfer WAS working pretty greatly on the previous ubuntu ppa version, but this started to happen after I upgraded my emesene version install.

**Comment by Sbte** [comment]
It's probably because of the direct transfers.

Also, your log doesn't seem to include any errors (it doesn't even contain the warnings of the original report), so that doesn't help at all.

**Comment by AlineFreitas** [comment]
Oh, right. It's there any way that I can "disable" the direct transfer? 'Cause I tend to use that feature quite often, and if it was working the way it was before..

**Comment by Sbte** [comment]
No, there isn't, because it's better to get this thing working. Because that means 600 kbps file transfers instead of 6 kbps.

What client was your contact using?

**Comment by AlineFreitas** [comment]
My contacts mainly use Windows Live 2009 or 2011.

**Comment by c10ud** [comment]
tested again, just to be sure: filetransfers work. proof: http://imgur.com/a/Wnomq

what i found out is that after first transfer they go crazy and don't work anymore for the current session, i'll edit main issue

**Comment by AlineFreitas** [comment]
Outch. But here it's STIL not working. I just tried. I push the accept button and nothing happens.

**Comment by AlineFreitas** [comment]
Here, my brother ran emesene -vvv from my notebook. http://bpaste.net/show/iQZBsdtunuh0oYhYGiB8/

**Comment by c10ud** [comment]
i believe you but the trace you provided doesn't show anything wrong,
neither my tests (other than what i've reported)

2012/6/19 Aline de Oliveira Freitas
reply@reply.github.com:

**Comment by AlineFreitas** [comment]
I'll close this issue as well, 'cause it started working again oO

**Comment by KinG-InFeT** [comment]
very strange ... I had also had problems with file transfer ... I'll do some more comprehensive tests with various IM to control the actual operation.

**Comment by Sbte** [comment]
http://pastebin.com/03VVGg2T

First filetransfer doesn't work. WLM->emesene

**Comment by c10ud** [comment]
fixed disabling direct connect
