### ISSUE TITLE
Checking email in facebook chat opens different browser than checking email in msn chat

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1336]
Hello,

I started using facebook chat and the following situation happens: When I click the button for checking facebook email (I guess autologin is not allowed), the browser that is opened is different that the browser that is opened when I check email in msn chat. 

In consequence, I would like to know if this is a problem of emesene or which mimetype I have to edit in order to ensure I keep the same program that i was using for msn chat. Thanks

**Comment by Sbte** [comment]
For msn you need to set default application for the html mime type

**Comment by Sacolevas** [comment]
And for Facebook? The issue for me is that it seems to be different the mime type ... because currently, two different browsers are opened when I press the same button.

In my case, for example, for the html mime type, I set Chromium as my default application and as expected, this browser is opened when I click the button in MSN chat.  But when I click the same button in Facebook chat, it opens 
Opera (my other installed browser). I want both to open with Chromium, so I don't know which mime type I need to look at for Facebook chat (why are different, BTW?).

**Comment by Sbte** [comment]
Facebook is a link, so it opens in your default browser.

They are different, because we need to open an html file for msn to be able to log in to your msn mail. For Facebook, we don't need to do this.

**Comment by pepeleproso** [comment]
I wonder if we can move that file into github just like the facebook one

**Comment by pepeleproso** [comment]
forgive my last comment, seeing the code is not posible

**Comment by Sbte** [comment]
@pepeleproso can't we just move the file to github and then use javascript to post stuff that we provide through the url?
