### ISSUE TITLE
 [FEATURE] [single-window] someone will contact

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1337]
When the chat is closed and reduced system-tray, if someone contacts only flashes the icon in the system-tray and displays the dialog box .... you can make it out dinuovo as with multiple windows?

**Comment by Sbte** [comment]
I doubt anyone will understand this report. 

If you report something, at least try to write something that is understandable. So far, most of your bug reports were not understandable at all.

**Comment by KinG-InFeT** [comment]
I apologize for my English.
However, simply saying:
1) someone will contact
2) only the flashing icon in system-tray

Instead you should see the conversation window.

**Comment by Sbte** [comment]
We call present as soon as someone talks to you and the conversation is not already open. I don't really see what's different. Maybe your window manager doesn't allow it.

@c10ud

**Comment by c10ud** [comment]
the conversation window is showed along with the contact list, am i missing something?

**Comment by moneycat** [comment]
@KinG-InFeT Is your issue like this:
1) Use Single Windows mode (I set it and restart emesene for pure environment)
2) Hide the main window
3) Use another contact to send message to this account
4) The main window will not show and the tray icon blanking

**Comment by KinG-InFeT** [comment]
has exactly understood the "problem"
I use fluxbox as a WM on archlinux
likely to be a problem in fluxbox?

**Comment by Sbte** [comment]
No, this is because that's how it's implemented. As soon as a message is received and there is already a conversation manager open, then the window will not be presented. Maybe we should make an exception to this for single window emesene. I'm not sure about this.

**Comment by c10ud** [comment]
do you really want the window to bump in your face?

2012/6/13 Sven reply@reply.github.com:

**Comment by Sbte** [comment]
Well, if you hide it to for example the messaging menu, then I think yes. I don't do that, so I don't need it.But maybe other people do...

**Comment by c10ud** [comment]
messaging menu is in that place for a purpose i think: not having
windows floating around if you minimize them -- if you want to open
the converastion you click the me-menu and it hopefully should open

2012/6/13 Sven reply@reply.github.com:

**Comment by c10ud** [comment]
by the way: didn't we have a START MINIMIZED thing?

**Comment by c10ud** [comment]
did anyone actually switched that preference before writing?

**Comment by KinG-InFeT** [comment]
the START MINIMIZED is interesting!

**Comment by KinG-InFeT** [comment]
why quit?
