### ISSUE TITLE
Offline group amount wrong

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1338]
1) Check `Show offline contacts`
2) Quit emesene, launch and login
3) The offline group amount wrong.

For example, I've an account where it has only my another account as friend. If my another account is online then the contact list will shown:

```
Online (1/1)
Offline (0/1)
```

It should be `Offline (0/0)` or no showing the group itself.

**Comment by c10ud** [comment]
is this a corner case? does this happen when contacts > 1?

**Comment by moneycat** [comment]
@c10ud Not corner case. Before my test account login, I've 270/404 offline contacts. Then I got a 269/404 offline contacts when my test account online.

**Comment by c10ud** [comment]
then before:
270 offline 404 total
after:
269 offline 404 total

i don't see how this is wrong (?)

**Comment by moneycat** [comment]
Ahhh...Ok I got it. I misunderstand the meaning. That's correct, sorry. :P
