### ISSUE TITLE
Endpoint menu improvement

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1339]
Refs #1332 as @matiasdelellis suggested. Due to my limited knowledge for menuitem and ui handling, I can just done like commit 16043ad3b026c7a4979f359a59b9603b7e2f633c.

Please give some suggestion of this. Thanks. :)

**Comment by c10ud** [comment]
what's missing exactly?

**Comment by moneycat** [comment]
@c10ud @matiasdelellis want to hide the whole Disconnect menu when there is no other endpoints. I have no idea how to hide the menu by default because it always show even I use `.hide()` or `set_visible(False)`. So I turn to change the words to make user know there is no other endpoints.

**Comment by c10ud** [comment]
i think the only way is deleting the items, it could require more hacking than expected..

**Comment by Sbte** [comment]
Maybe calling the detach method on the EndPointsMenu works?

**Comment by moneycat** [comment]
I think so. I will commit this patch if it works (although it is ugly). Maybe user will be misleading when there's no endpoint listing but still show an option of all others. How you think?

**Comment by moneycat** [comment]
@Sbte It will hang if I detach itself in EndPointMenus. I can detach it in FileMenu but the menuitem `ep` seems should be removed too. I'll think how to handling well...

**Comment by Sbte** [comment]
@moneycat, that's usually the hard part ;)
