### ISSUE TITLE
error when starting Emesene

### ISSUE THREAD

**Issue by gpinkston** [emesene/emesene#134]
I am getting an exception error when I start the program
You are using emesene 1.6.3 - "Uberlândia" so you're free to complain here:
http://forum.emesene.org/index.php/board,19.0.html
Check already existing tickets for duplicates first, please.
Traceback (most recent call last):

  File "/usr/share/emesene/emesenelib/soap/manager.py", line 139, in process
    return process()

  File "/usr/share/emesene/emesenelib/soap/manager.py", line 76, in process
    response.callback(response, *response.args)

  File "/usr/share/emesene/emesenelib/ProfileManager.py", line 155, in onGetProfile
    photo = response.body.split('</Photo>')[0].split('<Photo>')[1]

IndexError: list index out of range

**Comment by GVisconti84** [comment]
I'm sorry but you reported the error in the wrong place :)
This is for emesene version 2! :)
You can report this issue at the link http://forum.emesene.org/index.php/board,19.0.html as indicated in the error message you received :)

**Comment by c10ud** [comment]
as whisky said, and maybe upgrading to latest svn version should fix this issue --
