### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'do_handshake'

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1341]
```
Traceback (most recent call last):
  File "/net/users/ont/ont8020/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/ssl_socket.py", line 68, in _io_channel_handler
    self._transport.do_handshake()
  File "/usr/lib/python2.6/ssl.py", line 279, in do_handshake
    self._sslobj.do_handshake()
AttributeError: 'NoneType' object has no attribute 'do_handshake'
```

@pepeleproso

**Comment by pepeleproso** [comment]
is this happening every time you try to connect?
because self._transport is the socket, maybe we need to reopen it again.

**Comment by Sbte** [comment]
Yes, it happens every time as far as I can tell.

**Comment by Sbte** [comment]
I think this is what I'm running into:

http://bugs.python.org/file20901/ssl_connect.patch

We except in `socket.connect(self, addr)`, so `self._sslobj` stays None, where with the python 2.7 implementation the sslobj is set first, and since we use connect_ex, it is not set back to None.

**Comment by pepeleproso** [comment]
I tried patching the 2.6 ssl and it hangs so I'll revert this. We can reapply this patch once we move to python 2.7

**Comment by mk-j** [comment]
I got this error in python 2.6, when I call setblocking before connect 

``` python
ssl_socket.setblocking(0) 
ssl_socket.connect((hostname, port))
```

changing the order solves it for me.

``` python
ssl_socket.connect((hostname, port))
ssl_socket.setblocking(0) 
```

(I realize this thread is quite old, but I'm adding my comment here in case others find it helpful).
