### ISSUE TITLE
Allow emesene to be closed with keyboard on login screen

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1343]
emesene should be allowed to be closed with the keyboard on the login screen. It works for the contact list, i think it should work for login too. This could be OS X specific, not sure.

**Comment by c10ud** [comment]
same issue in ubuntu, we probably don't set accels correctly in loginwindow

**Comment by Sbte** [comment]
@c10ud we don't set them correctly because you didn't want a menu on the login screen. We set the accels on the menu, like we should. I think just showing the menu on the login screen would be the cleanest way to go here.

**Comment by c10ud** [comment]
i see -- i still don't like an useless menu there tho, but if it's the
only way then i'm okay with it (?)

2012/6/19 Sven reply@reply.github.com:

**Comment by Sbte** [comment]
Well, no, it's not the only way. We could also just copy the accels and put them on the window.
