### ISSUE TITLE
[Feature Request - Login Page] Add "Clean text" in Account 

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1351]
Add this button in account combobox when exist text: http://i.imgur.com/M1kNA.png

Another suggestion, im Search combobox, this button just should appear when exist text.

**Comment by jamesaxl** [comment]
@zipatei the link doesn't work.

**Comment by moneycat** [comment]
@jamesaxl the image is snapshot of search bar, a gtk entry element with two icon.

**Comment by jamesaxl** [comment]
@zipatei in this case we need coustom widget

**Comment by c10ud** [comment]
that's only for search entries, if i'm wrong, just tell me

**Comment by zipatei** [comment]
@c10ud kmess have this icon in combobox for account.

**Comment by zipatei** [comment]
http://imgur.com/cjmo8

**Comment by zipatei** [comment]
And this issue can not be closed because they lack the suggestion to put this icon in the combobox search only if there is text.

**Comment by c10ud** [comment]
kmess is Qt, not gtk

2012/6/26 zipatei
reply@reply.github.com:

**Comment by c10ud** [comment]
2012/6/26 Riccardo (c10ud) c10ud.dev@gmail.com:

> kmess is Qt, not gtk
> 
> 2012/6/26 zipatei
> reply@reply.github.com:
> 
> > And this issue can not be closed because they lack the suggestion to put this icon in the combobox search only if there is text.

i think that's a gtk feature, and must be taken as it is
