### ISSUE TITLE
[Feature Request] Copy Menu

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1352]
Grouping the three menu options to copy personal message, email, name.

**Comment by Sbte** [comment]
@zipatei, sounds like something you can do ;)

**Comment by jamesaxl** [comment]
Done, please close it

**Comment by c10ud** [comment]
btw if in your commit message you include "fixes #1352" or "closes #1352" then the issue will be closed automatically once the commit is pushed to emesene/emesene

**Comment by c10ud** [comment]
merged
