### ISSUE TITLE
Show emesene logo when connected to Facebook

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1353]
emesene currently shows the offline icon when connected to Facebook in menubar. As you cant actually change the Facebook status, i think it would make sense to show the emesene logo instead. Not really an issue, i'm just being pedantic!

**Comment by Sbte** [comment]
It makes more sense to display the online icon, because, well, you're online. But if it shows the offline icon that's definitely wrong.

**Comment by joshf** [comment]
Yeah i meant to say online icon, its still early here!

**Comment by Sbte** [comment]
I think it's more consistent with the msn session to have the online icon.

**Comment by Sacolevas** [comment]
Hello,

Just to comment that the same situation happens with Gtalk chat.
