### ISSUE TITLE
TLPv1 Parse Error: chunk should be at least 48 bytes

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1354]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/direct.py", line 345, in _on_data_received
    chunk = NonceChunk.parse(body)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/TLPv1.py", line 257, in parse
    raise TLPParseError(1, "chunk should be at least 48 bytes")
papyon.msnp2p.errors.TLPParseError: TLPv1 Parse Error: chunk should be at least 48 bytes

**Comment by c10ud** [comment]
i think that's a client sending BAD p2p data to emesene, what do you think?

**Comment by zipatei** [comment]
I dont know... happened me one time.

**Comment by zipatei** [comment]
Happened to me once again but i dont know to reproduce

**Comment by c10ud** [comment]
identifying which client is sending that data could be helpful -- it looks like the direct connection is failing on the first steps

**Comment by c10ud** [comment]
fixed disabling direct connect
