### ISSUE TITLE
Avatar contact buddy

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1355]
KMess can get the avatar, but emesene not.

The contact is the same.

http://imgur.com/Njf6w

**Comment by Sbte** [comment]
And you're sure that the contact actually has an avatar set? It's also possible that KMess is doing it wrong ;)

**Comment by c10ud** [comment]
possible causes: what sbte said, p2p error, cache corruption, etc.

but usually that works so..not really sure here

**Comment by zipatei** [comment]
it's funny because Emesene get a avatar from some contacts (web messenger for example). KMess get from others (application/x-msnmsgrp2p).

**Comment by c10ud** [comment]
is this #1370, just explained differently?

**Comment by c10ud** [comment]
I found out that some clients are sending bad checksum values for the data they send (e.g. avatars) or we're doing something bad and we're interpreting them in the wrong way (the weird thing is that one groups.im sends good data, the other don't !!!!)

**Comment by c10ud** [comment]
the issue i'm seeing may be related to groups.im directly, in fact i see they're sending the same data with different checksums

**Comment by c10ud** [comment]
fixed disabling direct connect and allowing clients to send bad sha1ds
