### ISSUE TITLE
[MSN] Change endpoint name on-the-fly

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1358]
A new feature for review:
1. Allow user to change endpoint information (currently, the display name) on-the-fly. 46c3661193076a7f41aeb8d445ff6464b4c11976
2. Other endpoints will pop up an notification if the user enable it. e7cfe9d665f2ffeff4453102f3367ef1ca2142b1

Any suggestions welcome. :)

**Comment by c10ud** [comment]
my suggestion is, if it works, push it! (so people try out and report eventual issues ;))

**Comment by moneycat** [comment]
@c10ud OK, i'll push it because in my case it works. Thanks.
