### ISSUE TITLE
[XMPP] Update from upstream

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1359]
Could we update XMPP from upstream to 1.1.7 or later. It seems there are much more fixes and improvement.

**Comment by moneycat** [comment]
I want to make an option to enable/disable ipv6 of XMPP if user have no ipv6 connection.

**Comment by c10ud** [comment]
yes, it needs to be done, currently i'm not at home so if someone wants to do it... (just overwrite the files and commit ;))

**Comment by moneycat** [comment]
@pepeleproso btw, i found why sleekxmpp will leave this message `[23:07:04 WARNING sleekxmpp.xmlstream.cert] Could not find pyasn1 module. SSL certificate COULD NOT BE VERIFIED.` even we installed python-pyasn1 in Ubuntu.

To import the libraries manually:
ImportError: cannot import name Any
ImportError: No module named pyasn1_modules.rfc2459
