### ISSUE TITLE
"No Group" group closed at start

### ISSUE THREAD

**Issue by 4javier** [emesene/emesene#136]
Linux, Python 2.7, last emesene2 git, last papyon git
I use Order by group option, and at start two groups are correctly expanded, but the third, "No Group", is collapsed. Not a gret issue, but annoying.
Adding a request:
possibility to sort in arbitrary order the sequence of group in main window.

**Comment by c10ud** [comment]
Fix (un)expanding of groups. Please test. Closed by 8b227eff66b61334b8ca469cad24811dfd198150

**Comment by 4javier** [comment]
Perfect. Thanks a lot.
