### ISSUE TITLE
[Bug] Contact don't receives images [WLM]

### ISSUE THREAD

**Issue by aranciaga** [emesene/emesene#1360]
When i send a image to my contact (he are using WLM 9) just don't receive. This happened with other contacts too.

Version: Emesene 2.12.5-1 (Linux version)

**Comment by Sbte** [comment]
#1335 (seeing it's about images/filetransfers)

**Comment by AlineFreitas** [comment]
Sorry to say, but this is what was happening to me. But weirdly, the same contact that just tried to send me a photo, successfully sent an mp3 less than an hour before
