### ISSUE TITLE
Warning: Ubuntu Packaging in "Emesene-Developers PPA"

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1363]
Hello,

As we are approximating to a new release (at least one with the segfault issue solved), I would like to mention some things that happened in the last packaging of emesene in Ubuntu. 

1) The emesene.desktop file in the package contained lines like "OnlyShowIn"  Unity and similarly for the option of opening a new instance. That meant that non-unity users (for example KDE, LXDE, XCFE, etc) didn't see emesene in the applications menu even if it was installed there. 

2) The emesene package forced users to install the package "indicator-status-provider-emesene" (which depends on indicator-messages), which was not necessary in 2.12.3 and it is not necessary to run emesene correctly. So probably it has some specific relation with Unity, I don't know, but certainly the packager didn't use a efficient way to package emesene with minimal dependences. So, this can be improved.

Thanks for your attention.

**Comment by c10ud** [comment]
those are packaging bugs (e.g. ubuntu specific), we cannot fix those, you'd better file bugs against ubuntu packages (in this case since i guess you're using the ppa version, i'm not really sure on waht's the best way to report them, probably contacting the mantainer directly..

also indicator-status-provider-emesene is a must for ubuntu, 2.12.3 didn't depend on that and it was an error since it made use of indicators and/or gtk tray icons which infringe the ubuntu guidelines

**Comment by c10ud** [comment]
also current .desktop file is:

[Desktop Entry]
Name=emesene
GenericName=emesene
Comment=Instant messaging client for MSN, Gtalk and Facebook
Comment[nl]=Chatprogramma voor MSN, Google Talk en Facebook
Comment[pt]=Cliente de mensagens instantâneas para MSN, Gtalk e Facebook
Comment[hu]=Azonnali üzenetküldő MSN, Gtalk és Facebook protokollokhoz
Comment[pt_BR]=Cliente de mensagens instantâneas para  MSN, Gtalk e Facebook
Comment[zh_TW]=適用於 MSN、GTalk 和 Facebook 的即時通訊軟體
Comment[tr]=MSN, Gtalk ve Facebook için anlık ileti istemcisi
Comment[ru]=Клиент обмена мгновенными сообщениями для MSN, Gtalk и Facebook
Comment[es]=Cliente de mensajería instantánea para MSN, Gtalk y Facebook
Comment[et]=MSN'i, Gtalk'i ja Facebook'i kiirsuhtlusklient
Comment[it]=Client di messaggistica istantanea per MSN, Gtalk e Facebook
Exec=emesene -s
Icon=emesene
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;InstantMessaging;
X-Ayatana-Desktop-Shortcuts=NewInstance;

[NewInstance Shortcut Group]
Name=Open a new instance
Name[nl]=Open een nieuwe instantie
Name[pt]=Abrir uma nova instância
Name[hu]=Új példány megnyitása
Name[pt_BR]=Abrir uma nova instância
Name[tr]=Yeni bir örnek aç
Name[ru]=Открыть новую копию
Name[es]=Abrir una instancia nueva
Name[et]=Ava uus eksemplar
Name[it]=Apri una nuova istanza
Exec=emesene
TargetEnvironment=Unity

**Comment by moneycat** [comment]
Some issue may be solved in develop version. You can download the snapshop
on GITHUB and test if it is solved.  :-)

**Comment by Sbte** [comment]
Bug 1 is fixed, and bug 2 is not a bug, but how it's supposed to work, as explained by c10ud.
