### ISSUE TITLE
Traceback in Signal.py and notification.py

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1364]
emesene -vvv output 

``` python


** (process:3355): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:3355): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:3355): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
[12:11:58 ERROR papyon.msnp2p.session_manager] Session_id == 0
[12:11:58 ERROR papyon.msnp2p.session_manager] Session_id == 0
/usr/share/emesene2/gui/gtkui/__init__.py:96: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[12:12:00 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[12:12:00 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[12:12:00 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[12:12:00 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[12:13:11 ERROR e3.common.Signal] Signal handler (_on_message._on_message) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "/usr/share/emesene2/e3/common/notification.py", line 158, in _on_message
    self._notify(contact, msgobj.display_name, text, msgobj.account)
  File "/usr/share/emesene2/e3/common/notification.py", line 245, in _notify
    self.notifier(title if title else '', text, uri, 'message-im', None, tooltip)
  File "/usr/share/emesene2/gui/common/PyNotification.py", line 59, in PyNotification
    notification.show()
GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[12:13:25 ERROR e3.common.Signal] Signal handler (_on_message._on_message) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "/usr/share/emesene2/e3/common/notification.py", line 158, in _on_message
    self._notify(contact, msgobj.display_name, text, msgobj.account)
  File "/usr/share/emesene2/e3/common/notification.py", line 245, in _notify
    self.notifier(title if title else '', text, uri, 'message-im', None, tooltip)
  File "/usr/share/emesene2/gui/common/PyNotification.py", line 59, in PyNotification
    notification.show()
GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[12:13:46 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
```

i install the notification-deamon in archlinux distro... but out this error...

**Comment by Sbte** [comment]
Then your OS is broken. This error just tells you that pynotify doesn't work. This is not a bug in emesene...

**Comment by KinG-InFeT** [comment]
the system is practically virgin ... most likely is the library that does not work properly, thanks anyway Information.

**Comment by Sbte** [comment]
Probably, yes. But it's not our fault. Just try to report it to Arch and see what they tell you.

**Comment by moneycat** [comment]
This could be an upstream error in which emesene could not be solved. In my
ubuntu 12.04 64bit desktop and Gentoo linux, I didn't have this problem.
Maybe you can report it to related forum/bug tracker of your os for help.

**Comment by Sbte** [comment]
@KinG-InFeT what you could do is try to find out what commit in emesene cased this (if it didn't happen in earlier versions). That might help upstream to fix this.

**Comment by c10ud** [comment]
$ python -c 'import gtk; import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'

simple command line to test the brokenness without involving emesene

**Comment by KinG-InFeT** [comment]
``` python
root@KinG-InFeT ~ $ python -c 'import gtk; import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gtk
```

qualcosa mi dice che l'import delle librerie GTK non ha avuto successo... forse xke utilizzo le GTK 3?

**Comment by moneycat** [comment]
Maybe you can try to reinstall `python-gtk2` or related packages of your os.

**Comment by c10ud** [comment]
my bad, gtk isn't needed:

$ python -c 'import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'

**Comment by KinG-InFeT** [comment]
re-test the command in line but not work

``` python
root@KinG-InFeT ~ $ python -c 'import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pynotify
```

and the python-gtk2 not exist in official repo and AUR archlinux packages....

**Comment by c10ud** [comment]
as said to Sarcolevas:

your OS is somehow messed up but i don't know where to point, you'd
better take a look at modifications you made to your system

2012/6/25 Vincenzo
reply@reply.github.com:

**Comment by moneycat** [comment]
@KinG-InFeT  <quote>`ImportError: No module named pynotify`</quote> your `pynotify` is broken (or not installed).

**Comment by KinG-InFeT** [comment]
that package does not exist in archlinux repo ... I ask @pepeleproso  to confirm

**Comment by moneycat** [comment]
@KinG-InFeT http://www.archlinux.org/packages/extra/i686/python-notify/ <- maybe this one?

**Comment by pepeleproso** [comment]
You need to be sure that you have the python2 version of the packages.
In arch python is python 3.2 so you need to launch emesene with python2. The command below should be:
python2 -c 'import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'

For libnotify configuration read: https://wiki.archlinux.org/index.php/Libnotify
Also you need the python-notify package.

**Comment by KinG-InFeT** [comment]
behold, now the command works (so to speak):

``` python
root@KinG-InFeT ~ $ python2 -c 'import pynotify; pynotify.init("thisisatesttest"); n=pynotify.Notification("hello", "test", ""); n.set_hint_string("append", "allowed"); n.show()'

** (process:1326): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:1326): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:1326): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
glib.GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

and in AUR repo the emesene2-git package container this depends

``` bash
depends=('python2' 'pygtk' 'python-dnspython' 'pylint' 'python-notify' 
         'openssl' 'papyon' 'python-imaging' 'dbus-python' 'xorg-xprop' 'libnotify')
```

update By Firetux thanks to my alert... all depends is installed...I can not understand the problem ....

**Comment by moneycat** [comment]
@KinG-InFeT This is not a bug of emesene as introduced in #1362. There must be some lost packages should be installed. I have no idea which one is, maybe @pepeleproso can help to list related packages in ArchLinux?

**Comment by pepeleproso** [comment]
did you have notification-daemon running? also you need to start dbus as a daemon. the link I gave you have the steps to setup it.

**Comment by KinG-InFeT** [comment]
the demon was not working properly ... and since I had fluxbox as WM would not start automatically ... is now solved thanks for your support.
