### ISSUE TITLE
[Feature Request] Do not ask all the time confirmation to block a contact (2.12.5)

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1366]
Hello,

This is a simple issue, but has appeared in 2.12.5. In some earlier post, I mentioned that now emesene is much faster in blocking contacts, which is a great thing. But now, it appeared that every time I tried to block a contact, it ask me for confirmation (in previous versions, this was not happening), which can be annoying it the confirmation window appears every time. Like many other programs, if you want to ask confirmation, should be a box to click saying something that "Do not ask me again". 

Thanks for your attention (and this wonderful program).

**Comment by c10ud** [comment]
we added this because users were blocking buddies by accident (?) 

no more bikeshedding on blocking contacts please
