### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1368]
Reproduce step:

1) Open emesene and open any contact
2) open the contact information window
3) Click chat history and then click other tab
4) segment fault

ps. the contact I opened is a user with more chat log with me. I guess that this issue may due to switch out the tab before query result shown.

@pepeleproso  @c10ud @Sbte  Any idea?

**Comment by Sbte** [comment]
Not reproducible here

**Comment by moneycat** [comment]
Maybe it is a special issue of me because I will wait for 30 seconds for the default range of chat history (0526~0625) to show.
At that time if I close the contact information window before the logs shown and click another tabs and click the chat history, it will be segfault.

**Comment by moneycat** [comment]
@Sbte OK, I can clarify this issue now.

1) Open contact information window for a contact
2) Click the chat history tab
3) Close the window before the log result shown (I think there is no log)
4) redo step 1, and 2
5) Segment fault

My log db is around 50mb...seems large.

**Comment by Sbte** [comment]
Ah, good one. My emesene just went BOOM ;)

**Comment by Sbte** [comment]
In AdiumTextBox replace all self.execute_script -> self._execute_script

``` python
    def _execute_script(self, function):
        if self.get_visible():
            self.execute_script(function)
```

I'd commit this if I were at home, but I'm not atm. Please test

**Comment by moneycat** [comment]
Seems work.

**Comment by Sbte** [comment]
@pepeleproso does this seem like a proper fix to you?

**Comment by moneycat** [comment]
@Sbte Is it possible to cancel/stop/abort the query execution of history?

I'm trying to add a `loading` message when execution but it will be better if the execution can be aborted.

**Comment by pepeleproso** [comment]
I have the feeling that we don't property destroy the adium widget and that's why we crash, but I need to dig into the code more to be sure.

**Comment by moneycat** [comment]
Maybe it is because the query procedure is like something async function. When we open a chat history and the query start, it bind to the current ChatWidget we create and execute query by another thread.
When we close the contactinformation window, all widget destroyed? After the query is finished and is ready to show result with `_on_chats_ready` , the `self` now is gone that the error arise?

**Comment by c10ud** [comment]
probably, that makes sense

however killing webkit properly is tricky, but @pepeleproso succeeded for conversations so maybe it's applicable here..? i don't remember his solution, sorry

**Comment by c10ud** [comment]
added some code for testing the leak 1cf4e7381b3a930e52bdc109e04d3599e02fff8d

**Comment by zipatei** [comment]
python: ../../src/xcb_io.c:528: _XAllocID: Assertion `ret != inval_id' failed.

**Comment by moneycat** [comment]
It seems your system issue.

**Comment by c10ud** [comment]
is the 1st issue still happening? i didn't get if it was fixed or not

**Comment by moneycat** [comment]
I'll try and report tomorrow. The BIG db is not in my NB so I cannot test it now. :P

**Comment by Sbte** [comment]
Easy way to reproduce this:

put `self._prepare_history()` on top of the `_on_chats_ready` method in `ContactInformation.py`
