### ISSUE TITLE
Tray icon menu when network problem

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1369]
Reproduce step:
1) open emesene and connect to MSN
2) disconnect network (eg. close wifi connection) and emesene will jump to reconnect window
3) the try icon remain the last status before disconnect

Is at this time, the tray icon and its menu should be the same as disconnected?

**Comment by Sbte** [comment]
You could try to call self.tray_icon.set_login() in on_reconnect in emesene.py
