### ISSUE TITLE
Login fail when password exceeds 16 chars (msn)

### ISSUE THREAD

**Issue by Zincr0** [emesene/emesene#137]
A netpassport account can have more than 16 chars but the msn networks can´t, so
the msn password must be cutted on login.
Adding:

password=password[:16]

to login function in Session.py, fix the problem (at last for e3.msn)...
I tried a git push but it returns error code 22.

sorry for my english, it isn´t my native language.

**Comment by GVisconti84** [comment]
Don't worry about your English, we're from all over the world :)

You can't push directly in emesene's repo, you have to fork emesene, clone your forked repo on your pc, make changes there, commit, push to your online repo, and then open a pull request. Once you get in the mechanism it isn't so hard :)

**Comment by c10ud** [comment]
pulled

**Comment by Zincr0** [comment]
Where´s the main repo -the latest version with this change and all others-? in http://github.com/dequis/emesene ?

**Comment by c10ud** [comment]
emesene/emesene
