### ISSUE TITLE
Deprecated: Using MSNObject creator to guess peer

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1370]
Whenever I get an animated icon of another contact, it will not appear, and this error message appears.

**Comment by c10ud** [comment]
what's an animated icon? gif avatar? how can we test this?

**Comment by zipatei** [comment]
this emoticons http://www.youtube.com/watch?v=uTjK-MMQf-A&feature=related

**Comment by c10ud** [comment]
that's a youtube video, i am interested in knowing if they're GIFs or
flash/other, because if that's the case, we don't support it

2012/6/26 zipatei
reply@reply.github.com:

**Comment by zipatei** [comment]
GIFs

**Comment by pepeleproso** [comment]
I fixed the warning but I don't think it's the real problem.
@c10ud to reproduce you need to receive a custom animated emote.
From my test I receive small emotes (16px) but not big (50px).
I use emesene to emesene.

**Comment by c10ud** [comment]
could it be some sort of hard limit on filesize? i remember reading somewhere there was somekind of 200KiB limit...?

**Comment by zipatei** [comment]
(12:35:17) papyon.transport:<<< MSG anaccc@hotmail.com filipa 220
    MIME-Version: '1.0'\r\n
    Content-Type: 'text/x-mms-animemoticon'\r\n
    \r\n
    lol <msnobj Creator="anaccc@hotmail.com" Type="2" SHA1D="07Y88WVReAE0yf5ZZNpEFyEicgQ=" Size="13194" Location="0" Friendly="bABvAGwAAAA="/>
(12:35:17) papyon.conversation:['lol', '<msnobj Creator="anaccc@hotmail.com" Location="0" Friendly="bABvAGwAAAA="/>', '']

**Comment by c10ud** [comment]
@pepeleproso please check if this is a consequence of file transfers not working after first transfer and/or filesize limit (you may want to disable caching code in papylib's Worker so you always get a transfer)

**Comment by c10ud** [comment]
fixed disabling direct connect
