### ISSUE TITLE
image sharing

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#1373]
I don't know how can I explain it, but I'm going to give my best

you know, when you're using the official msn, and then someone paste an image on the conversation, and open a "side window" with that image?
so you can see the image without needing to save that into your computer

is that anyway to emesene have that feature? or at least send me the file via normal tranfer, IDK

I don't know even if that's possible thought

**Comment by Navodar** [comment]
Yes, it would be nice to see some notification for that and eventually option to transfer that file if its not possible to implement sharing feature.

**Comment by lfottaviano** [comment]
I have that idea in mind, also for videolinks, i think i will implement it when i have some time.

**Comment by c10ud** [comment]
if you can find more information about the protocol specific bits of that functionality maybe we could do something but afaik that's not supported by our library (papyon) and there's no info around

**Comment by c10ud** [comment]
investigated but it's not possible to enable real sharing support without effort, patches welcome though
