### ISSUE TITLE
[Feature Request] Top 5 contacts

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1375]
It's something that already exist in browsers, another innovation in IM's.

What do you think the creation of a automatic group with 5/10 accounts most used?

It would be an optional group.

This would facilitate the lives of people who have many contacts but that did not even have time to organize them.

**Comment by c10ud** [comment]
that, my friend, is the Favorites group

please don't complicate more the already messy contact list

rejected!

**Comment by zipatei** [comment]
:D Ok @c10ud
