### ISSUE TITLE
[Search entry] Suggestions

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1376]
1. No text in Main Window:
   http://imgur.com/WWAxG
2. Text in Main Window:
   http://imgur.com/BxEi6
3. Contact Information
   http://imgur.com/3ntrp

In contact information, should we ban the search without text.

**Comment by c10ud** [comment]
i don't want UI elements to appear/disappear without no apparent reason and users mad because they cannot find a feature, let's keep "less is better" for gnome only

i hope i didn't misunderstand the issue

**Comment by zipatei** [comment]
@c10ud It's just a hint of appearance. It makes no sense, clear the button text when the text does not exist. But it is not important.

But there is something we should avoid, which was the search without text. (contact info)

**Comment by c10ud** [comment]
main window (last git): with the search entry focused press ESC, ESC and it will go away (first removes text, second hides it)

contact info: that's a viewer, it makes sense to have search always available (and makes a hell of a UI if you cannot find how to search unless you put some-other-ugly-button)

**Comment by zipatei** [comment]
@c10ud 

Contact Info: Not this...

Reproduce:
1. Open contact info - conversation history
2. Without text, click in search

we should avoid the search without text. But search entry always available. :)

**Comment by c10ud** [comment]
yes, that's what i think it's a sane UI default to have: search always
shown in there because there's no smarter way to handle it

2012/6/28 zipatei
reply@reply.github.com:
