### ISSUE TITLE
Show commit in About dialog

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1379]
Is it useful to show the commit sha1 string in About dialog when user using develop version if possible? Examples: http://imageshack.us/photo/my-images/444/devversion.png/

**Comment by c10ud** [comment]
well, if you use git i guess you know where you are, and sha hashes are weird to compare (?)

**Comment by moneycat** [comment]
Yeah...and git is lack of the feature like $id$ for whole commit. OK, discarding it. :P
