### ISSUE TITLE
[Feature Request] Offline only for contacts we choice

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1384]
On windows live messenger and Facebook is now possible to go offline for just one or the other contact to choose.

**Comment by c10ud** [comment]
i don't think that's possible with msnp18 (there's no such thing)
hence we cannot enable that feature (probably is some of the newer
protocols)
as for facebook, that chat is entirely different from what we use
(xmpp) which has a very limited and basic functionalities

2012/6/29 zipatei
reply@reply.github.com:

**Comment by zipatei** [comment]
if no possible, no problem... just a suggestion thing. ;)

**Comment by c10ud** [comment]
yes, i just wrote what i know ;)

2012/6/29 zipatei
reply@reply.github.com:
