### ISSUE TITLE
[Discuss required] Status - Two different endpoints on

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1388]
The emesene should monitor the status of other endpoints.

Reproduce:
1. Open Emesene (status offline)
2. Open webmessenger (status online)

Emesene stay offline, but your status turn online becausa webmessenger.

Windows live messenger monitors the status of WebMessenger.

**Comment by zipatei** [comment]
Note: Windows live messenger monitors the status of Emesene too...

**Comment by moneycat** [comment]
Yes it could be. There is an comment of this: https://github.com/emesene/emesene/blob/master/emesene/e3/papylib/papyon/papyon/msnp/notification.py#L480

@c10ud

**Comment by c10ud** [comment]
it could be that whoever wrote that code never tested mpop or similar, you can try enabling it but then i guess you'd need to handle it in papylib's Worker accordingly

**Comment by moneycat** [comment]
typo: We should change status in endpoint_updated signal instead of there.Trying to patch it now. ;)
