### ISSUE TITLE
TypeError: Method called on dead object _on_status_change_succeed

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1390]
Use Tray Icon by default and login -> change to indicator or messaging menu -> change back tray icon -> change status -> error

[02:50:49 ERROR e3.common.Signal] Method called on dead object: _on_status_change_succeed._on_status_change_succeed
Traceback (most recent call last):
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/WeakMethod.py", line 31, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

**Comment by moneycat** [comment]
Or use Indicator/messaging menu by default and login > change to tray icon > change status > error

**Comment by c10ud** [comment]
how about this?

```
diff --git a/emesene/emesene.py b/emesene/emesene.py
index f90f714..4eab279 100644
--- a/emesene/emesene.py
+++ b/emesene/emesene.py  
@@ -473,6 +473,7 @@ class Controller(object):
         if self.tray_icon is not None:
             if trayiconcls == self.tray_icon.__class__:
                 return
+            self.tray_icon.unsubscribe()

         handler = gui.base.TrayIconHandler(self.session, gui.theme, self.close_session)
         self.tray_icon = trayiconcls(handler, self.window)
```

**Comment by moneycat** [comment]
@c10ud It still although add `if self.tray_icon is not None: self.tray_icon.unsubscribe()` in L366

**Comment by moneycat** [comment]
It only happen in Tray Icon, not Indicator or Messaging Menu. Weird...

**Comment by moneycat** [comment]
Oh...it seems the status icon in userpanel is correct but the tray icon gone. At that time, only indicator will work correctly.

Now if I change to `No tray icon`, and change back to tray icon or messaging menu, the tray icon back.

**Comment by moneycat** [comment]
@c10ud Confirm, error is gone but another issue raised...:(
