### ISSUE TITLE
Tray icon disappear

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1392]
Thanks for @c10ud, the error dismissed when change tray icon method. Now the status of tray icon are:
- Indicator (yes) -> Tray Icon (no) / Messaging Menu (no)
- Tray Icon (yes) -> Indicator (yes) / Messaging Menu (no)
- No Tray Icon (no) -> Tray Icon (yes) / Indicator (yes) / Message Menu (no)

BTW, the messaging menu method seems broken in v2.12.15 in my PC.

**Comment by c10ud** [comment]
i don't understand what happens exactly here, i just briefly tried switching tray icons and status at runtime when fixing the other error

**Comment by moneycat** [comment]
@c10ud The tray icon will not show like there is no tray icon.

**Comment by c10ud** [comment]
that's weird, i'm trying right now and it's working as expected, maybe you're following some other path? i run emesene then open preferences and change tray icons, they all show correctly

at rev 6b823698b19a7d94abec19c0c6b322fc75c8a313

**Comment by c10ud** [comment]
gnome-shell bug

**Comment by moneycat** [comment]
Maybe it is an bug of gnome-shell. Close this ticket because there is no other errors.

**Comment by moneycat** [comment]
@c10ud could you help to test this patch 965c141 because I have no Unity machine. The issue may due to upstream of Ubuntu that the indicator packages are modified to allow showing in gnome-shell. Then it may conflict with status icon with TrayIcon because there is only one way for tray icon show in gnome-shell.

If this is no harm in your system, I'll commit it to mainstream. Thanks :)
