### ISSUE TITLE
Avatar size and position

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1397]
In dummy session.
1. MianWindow avatar: size is a small one
2. Contact list avatar: size is strange after change and the position of avatar in contact list is biased after change (32->48->64->32)
3. Conversation window: default size is 18? Size strange while change it.

**Comment by pepeleproso** [comment]
My patch fixed the Conversation window: default size is 18? and point 1.

The size change bug is still there.

**Comment by pepeleproso** [comment]
Point 3 is fixed now.
Only point 2 remain.
