### ISSUE TITLE
[Feature Request] Show group of blocked contacts

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1398]
In WLM, replaced the block contact, by appearing offline to the contact.

They created a group apart, with the contacts blocked.

**Comment by c10ud** [comment]
i don't like this, we're not wlm

but seems like @moneycat did it 5bf7e7b59eb9aebc7c2b9835433377d12c994f42

so if he wants he can push it but i find it useless

**Comment by moneycat** [comment]
@c10ud Yeah...Although I've try to implement this, there are much more logical loopholes and it is hard to solved. Then I give up so the code there is a bug one. :P

**Comment by Sbte** [comment]
Our Great Leader doesn't like it, so closing...
