### ISSUE TITLE
e3.msn, papyon, jabber, xmpp

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#14]
how about (in our ugly dropdown menu :p):

[msn/wlm]
[facebook]
[gtalk]
[generic jabber/xmpp]

with good presets?

also, do we really need to keep e3.msn since we have so little manpower?

**Comment by cando** [comment]
no,i don't think we need to keep e3.msn...we need to improve papylib but also papyon!!!

**Comment by marianoguerra** [comment]
I like the more user friendly menu, we should have a way to allow the e3 extensions to provide a set of options with defaults, jabber could have a dict with some ProtocolOptions object that contains the info to fill when the option is selected.

e3.msn is something like a reference implementation, it is the code that made the e3 api, so I think leaving it there makes no harm, the same for dummy. I don't use e3.msn nor anyone I think so setting papyon as the default msn extension and e3.msn with something like "msn (alternative)" would do.

Also it's simpler than papyon for people wanting to see how a msn library is made :)

Finally maybe some day I will start hacking it again... who knows

**Comment by marianoguerra** [comment]
done
