### ISSUE TITLE
Operations on Contact List

### ISSUE THREAD

**Issue by GVisconti84** [emesene/emesene#140]
Are operations on contact list such as adding/removing a contact, adding/removing a group... broken? 
I don't seem to be able to perform such actions :/
And if a contact adds me I get a papyon error on the console:
    [23:42:31 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
    [23:42:31 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
    [23:42:31 WARNING papyon.service] Transport Error :500
    [23:42:31 WARNING papyon.service] Transport Error :500

(that's the same error code of the login problem fixed by papyon 0.5.2)

**Comment by c10ud** [comment]
i think we should notify upstream about this -- and we need a longer trace (try with ./emesene -vvv)

**Comment by c10ud** [comment]
groups adding/removing seem working, but there's something wrong in remove callback
(19:08:29) e3.common.Signal:Signal handler (_on_remove_group._on_remove_group) error: '9a02e28f-0cc9-4d1d-b650-eea5131fab9b'

**Comment by GVisconti84** [comment]
Ok I was now working on implementing this stuff on the Qt4 frontend, and I can confirm the error when removing groups.

Moreover, I noticed that gui.base.remove_contact isn't called, either in the Gtk gui, either in the Qt4 one: the contact is actually removed but the contact list widget is not up to date :/

**Comment by c10ud** [comment]
uhm, quite strange -- it seems that the signal is correctly subscribed though (gui.base.ContactList)... i hate ContactList :|

**Comment by c10ud** [comment]
fixed add/remove group
fixed remove contact

**Comment by c10ud** [comment]
we need to test/fix add/be added from a contact

**Comment by GVisconti84** [comment]
Great! Ok, I'll start doing some test

**Comment by c10ud** [comment]
sort of fixed adding:

```
[19:27:26 INFO papylib.Events] Contact membership changed: <papyon.Contact id='503737e4-2bb6-4c5b-82b5-309370195b6f' network='1' account='mail@hotmail.com' memberships='ALLOW'>
```

receiving an added you seem not working, but papyon is quiet, so i'm unsure on this

**Comment by GVisconti84** [comment]
Ouch! I didn't even notice adding a contact was broken in the gtk gui! :P I have been using the Qt4 one, where I implemented the dialog's resonse codes looking directly at the response callbacks :P

**Comment by c10ud** [comment]
X added you should now be working

**Comment by c10ud** [comment]
i have to fix some nasty case where deleting user and readding doesn't show up the contact, but in general it should work i guess

**Comment by c10ud** [comment]
reopen with specific bugs, please
