### ISSUE TITLE
[Feature Request] Center vertically the nick in contact list.

### ISSUE THREAD

**Issue by matiasdelellis** [emesene/emesene#1401]
Only a change that improves the gui glance.

The nickname format by default is:

> [$DISPLAY_NAME][$NL][$small][C=c10ud][$MESSAGE][/C][$/small] [1]

Change the nickname format to: 

> [$DISPLAY_NAME] [$small][C=c10ud][$MESSAGE][/C][$/small]

Only remove the line break, and would expect that all text is centered vertically

See here: (The first 3 are normal, and the last, the suggestion)

https://dl.dropbox.com/u/9606612/Attachments%20for%20bugs/emesene-center-nick.png

[1] Similarly, in their original format, when the contact does not have [$MESSAGE], in the contact list displays a single line, but this is aligned to the top. I wish see centered also in this case.

Thanks for all.
Regards.

**Comment by moneycat** [comment]
@pepeleproso I made some change in RendersNew. If you have some free time, could you made verify of it? Thanks.

Then for the avatar, I've no idea how to put it vertical align when size is 18 and there are two lines in nick.

**Comment by matiasdelellis** [comment]
+1 It works great!.
Only lack to detect if the second line is empty, and remove the line break.
In others words .. When parse the format nick and found a [$NL], observe that after the jump found any valid text (not nick empty, or empty state). When it finds a valid text, add the jump and the text.

P.s: In this way also save you from count the lines, and add different alignments. Must always center the text, and add only the number of lines needed.

**Comment by moneycat** [comment]
@matiasdelellis I did not commit all changes into mainstream because we still need a better for user to handle the alignment. Now we just add the feature into emesene but not enable it.

For the [$NL] , it is a little bit complicated in current work. :P

**Comment by moneycat** [comment]
@c10ud Should we set nick and avatar render valign to middle by default? It seems the CellRendererText/CellRendererPixbuf are align at middle by default.

Or we can fix avatar to middle to make its behaviour as the status icon but leave the nick render as a configured one within Preferences?

@sbte any idea?

**Comment by c10ud** [comment]
if it's good on the eyes, then it's ok

2012/7/8 moneycat
reply@reply.github.com:

**Comment by Sbte** [comment]
I don't see why we need an option for this. If centering looks better, then just use that :P

As for the newline, that'd indeed be complicated, because we use a tag for that. Also, it'd probably look weird, because it'd be inconsistent. So just leave that.

Also, if you leave that, the only thing you'd have to do to get the text on top is adding a newline. Problem solved ;)
