### ISSUE TITLE
Concrete problem with tray icon extension ... program "dissapears" (July 4, development version)

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1406]
Hello,

For natural reasons, this incident happened by coincidence, so I will give the following steps to reproduce and see how to fix this concrete issue:

1) I open emesene and login into my messenger account.

2) In the main menu, I choose "Preferences", go to "Extensions" and in category "Tray Icon", the default selection is "Messaging Menu". I change it to "Tray Icon". 

3) Minimize (hide) the program to tray (this is important, if program is not hidden into tray, the issue doesn't happen)

4) With right click on the tray icon, I see the option to edit preferences, so I choose again "Extensions", category "Tray Icon" and revert to "Messaging Menu". 

5) The program "disappears".

What do I mean by "dissapear"? It is still running, but you can't see it, given that there is no tray icon and there is no emesene in the task bar.

That's it, thanks for your attention.

**Comment by moneycat** [comment]
This is similar with #1392. @c10ud and I have discussed somewhere before. If you are using gnome-shell, it may be a bug of gnome.

**Comment by moneycat** [comment]
OK. MessageMenu is not supported in gnome 3

**Comment by c10ud** [comment]
cannot reproduce OPs issue, which OS/Desktop are you running? Are you with latest git?

**Comment by Sacolevas** [comment]
I am using Ubuntu with LXDE and the July 04 version. I think the problem is emesene's and not related to gnome 3 or something like that. It looks like a code problem (some missing "if")

Look at the difference between these two images (minimized into tray and hidden into tray):

Image 1: http://imageshack.us/photo/my-images/507/201207081018311366x768s.png/

Image 2: http://imageshack.us/photo/my-images/824/201207081018031366x768s.png/

When I check the preferences by right-clicking the tray icon, if emesene appears in the task bar and I change the "tray icon" option to the default (messaging menu), the result is just like the following image (Image 3):

Image 3: http://imageshack.us/photo/my-images/694/201207081029451366x768s.png/

In other words, the tray icon just dissapears and nothing happens. 

However, if the situation is like in Image 2 (just the tray icon) and I apply the preferences of changing "tray icon" to "messaging menu", what happens? As emesene doesn't appear in the task bar, removing the tray icon doesn't work!! Because emesene is not there, so it would "dissapear". A conditional should say something like "if emesene doesn't appear in the task bar, then, make emesene appear in the task bar before removing the tray icon".  Probably such conditional is missing.

Another option would be to remove the option of setting the preferences when emesene is hidden into tray by right-clicking the tray icon, but I guess that is not desirable.

Thanks for your attention.

**Comment by c10ud** [comment]
if you're choosing to use messaging menu as your trayicon (and if you can use it it means you have the required libraries installed) then it's not our problem if messaging menu ain't showed/used in your OS

**Comment by Sacolevas** [comment]
No, in all images "Tray Icon" is the option chosen. What I am describing is the step of "coming back" to "messaging menu" and how it reacts depending if emesene is minimized or is hidden into tray. And I have all the required libraries :)

**Comment by Sacolevas** [comment]
I tried, taking emesene hidden into tray, to make other transitions; for example, changing from "Tray Icon" to "Indicator" and then to "messaging menu" and it worked perfectly, so it is this transition the one who doesn't work.

And in the problematic issue I am mentioned, emesene "dissapears" (by the explanation I gave before), but I have just checked and it is still running (but given that there is no tray icon and it doesn't appear in the task bar), there is no way to use it !!!!

**Comment by Sacolevas** [comment]
Hello!

UPDATE: 

This is definitely a emesene problem. Besides the problem of emesene "dissappearing" in this case described (logged in in some messenger account, emesene using "Tray icon" as the tray icon option in the extensions menu, emesene hidden in the system tray, right click on the tray icon to set preferences and change "tray icon" to the default (Messaging Menu) or the option "No tray icon"), 

...there is another problem, WHICH IS NOT PRESENT IN 2.12.3 or 2.12.5, so, it is emesene's problem.

Steps to reproduce: 
- Emesene using "Tray Icon" as the tray icon option in the extensions menu. We are logged in some account.
- Emesene hidden in the system tray.
- From there, by right clicking in the tray icon, apply "disconnect".

What happens in 2.12.3 or 2.12.5? Emesene shows correctly a new tray icon (the emesene logo) in the system tray, as we have disconnected: http://imageshack.us/photo/my-images/542/201207100820071366x768s.png/

What happens in the latest development versions? Emesene dissapears (i.e., the icon in the system tray dissapears, and given that emesene is not in the taskbar - because originally is hidden in the system tray), then we don't see emesene, but it is still running.

I will be grateful if someone can fix these issues (I am not a programmer, so I do my best as a tester), instead of saying that "is not emesene's problem", when clearly it is (otherwise it wouldn't act differently from one version to another and having the same libraries installed). 

The first issue I mentioned originally -which generated this issue several posts ago- is present in 2.12.3 too, the latter one is new, so certainly, changes in the behavior of the tray icon extension have been worsening the issues. And it is not a problem of having certain libraries installed or not. 

Have a nice day :)

from there  I have tested emesene 2.12.3 and this problem doesn't occur there, so this is emesene's issue and happened somewhere during the latest update.

**Comment by c10ud** [comment]
If you disconnect it will use the default trayicon, in this case Messaging Menu (since you have the required libs), but there's no messaging menu showed in your desktop, so yes, it "disappears". 

In order to fix it remove python-indicate from your OS

**Comment by Sacolevas** [comment]
Hello,

I removed python-indicate and there was no improvement. I also reinstalled it and nothing :(

Actually, in the latest development version, I am experiencing something worse:  I open emesene, I hide the program  into the tray icon, do nothing and eventually, messenger disappears. This doesn't happen in 2.12.3

**Comment by Sbte** [comment]
Please do a git bisect to see what commit caused this
