### ISSUE TITLE
Rewriting Growl plugin

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1407]
Basically im rewriting the growl plugin to use GNTP rather than growlnotify. I can get emesene to show a generic notification,  but i want to show different notifications depending on the event type e.g contact online, contact offline etc. This would allow user to disable certain events within growl aswell as customizing notifications. GNTP also means we can support growl on windows.

Example:

On contact online

```
if notify_type == "contactonline":
    growl.notify(
        noteType = "Contact Online",
        title = title,
        description = text,
        icon = imagepath,
        sticky = False,
        priority = 1,
    )
```

On contact offline:

```
if notify_type == "contactoffline":
    growl.notify(
        noteType = "Contact Offline",
        title = title,
        description = text,
        icon = imagepath,
        sticky = False,
        priority = 1,
    )
```

What i need to know is how do i detect different events that emesene passes to the notification pugins?

**Comment by c10ud** [comment]
currently the notification system is "centralized" and configurable through emesene, but notifiers don't know what they're notifying, all the dirty work is done in e3/common/notification.py so i'm not sure you can do what you want..

**Comment by joshf** [comment]
Is there no way to pass a varibale from notification.py to a notifier? The notifer can already recieve title, text, picture_path etc. Surely to add one more variable would not be that hard?

**Comment by c10ud** [comment]
it wouldn't be hard but atm it is useless.
you can already configure notification options through emesene, i
don't understand the duplication of controls here

2012/7/8 Josh Fradley
reply@reply.github.com:

**Comment by Sbte** [comment]
You already get it through the `const` variable. Just not the online/offline one because those are passed as message-im. If it doesn't break anything, you could change the name of those messages...

**Comment by c10ud** [comment]
not an issue
