### ISSUE TITLE
MSNObject problem - error message in text window

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1409]
The error message: "Error while delivering message"
But the text is delivered! Also, this error message shows up more than once for the same sentence.

Also, when no text sent, this also sometimes shows up.

Full emesene -vvv log: http://ultrashare.net/hosting/fl/670bfffa84/buglog

Could be related to #1171

**Comment by c10ud** [comment]
ok then this is #1171

**Comment by Smile4ever** [comment]
But that issue was closed?
Additional information:
- Latest emesene from 9 July (from Git) used
- E-mailaddress of the person who I was chatting to: **********at hotmail . com

**Comment by c10ud** [comment]
probably the fix did not work then :(

**Comment by Smile4ever** [comment]
Where is this problem situated? In which file(s)? Also, the error message can't appear 4 times for 1 thing - if that's solved that would be already a huge step forward.

**Comment by c10ud** [comment]
fixed disabling direct connect
