### ISSUE TITLE
DebugBuffer error

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1412]
Traceback (most recent call last):
  File "emesene/gui/gtkui/DebugWindow.py", line 147, in on_store_insert
    self.add_line(caller, message, level, date)
  File "emesene/gui/gtkui/DebugWindow.py", line 153, in add_line
    self.insert_with_tags_by_name(self.iter, "(%s) " % record_time, "time")
AttributeError: 'DebugBuffer' object has no attribute 'iter'
Traceback (most recent call last):
  File "emesene/gui/gtkui/DebugWindow.py", line 147, in on_store_insert
    self.add_line(caller, message, level, date)
  File "emesene/gui/gtkui/DebugWindow.py", line 153, in add_line
    self.insert_with_tags_by_name(self.iter, "(%s) " % record_time, "time")
AttributeError: 'DebugBuffer' object has no attribute 'iter'

**Comment by lfottaviano** [comment]
Hi, what have you done to get this? how can be reproduced?

**Comment by moneycat** [comment]
@lfottaviano Sorry for missing steps:

1) Open emesene with -vvv
2) Open debug window
3) I change to other catalog to see some message, then change to debug
4) Sometimes it will happen

**Comment by c10ud** [comment]
cannot reproduce here

**Comment by Sbte** [comment]
I can reproduce it here. Not sure why it happens...

**Comment by moneycat** [comment]
It seems randomly, so close it and it will reopen if I can clarify what happen.
