### ISSUE TITLE
Can't invite the right contact to a conversation

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#1414]
Somehow, since a few days I can't invite the right contacts to an existing conversation: it doesn't matter which one i choose in the list that pops up pressing the "+" button, the one in the top place in the list gets invited instead. Also, I can't seem to be able to invite more than one person at once ( even if I select more than one of them from the list ).

I'm not seeing any error message in the terminal, and I'm using latest git

**Comment by moneycat** [comment]
@Soulsuke Please test this patch 5d44b6e844e196614cd94918d5836d18bdda527a

**Comment by Soulsuke** [comment]
Just tested it, it works like a charm :D
