### ISSUE TITLE
Invisible text when receiving messages from mobile clients

### ISSUE THREAD

**Issue by TherioLZ** [emesene/emesene#1417]
Emesene version: 1.12.5
OS: Win7 64-bit

Whenever I receive a message from someone using a mobile client, the message is entirely invisible:
http://i.imgur.com/PMRf1.png

It shows up correctly in the chat log though:
http://i.imgur.com/aCRBF.png

Is this a known issue?

**Comment by c10ud** [comment]
no, it is not known, is there a way we can reproduce the issue? (also, if you could test latest development version and see if issue persists..)

**Comment by TherioLZ** [comment]
I have this issue with anyone sending me a message through a mobile client (any smartphone client like eBuddy on a phone), so that's how it's reproduced. I will try if it's the same on the latest dev version though, gimme a few minutes.

**Comment by Gwildor** [comment]
emesene 2.12.3, Ubuntu 12.04

I've never encountered this problem, and I talk daily with someone who is using eBuddy all the time. I don't know how old version 1.12.5 is, but I suggest updating to 2.12.5. Or is it, which I think of now after posting this post already, a typo and are you actually using 2.12.5? In that case I guess the problem has crept in in .4 or .5.

By the way, nice to encounter a fellow Dutchman.

**Comment by TherioLZ** [comment]
My bad, meant to write 2.12.5 yeah. Guess I'll have to try a rollback to 2.12.3 and see if it happens there.

**Comment by c10ud** [comment]
if it happens when chatting through a web service i could try it out, http://www.ebuddy.com/ ?

**Comment by Sbte** [comment]
Maybe it's in the message style they use

**Comment by Sbte** [comment]
@TherioLZ, could you please answer @c10ud's comment? It would be nice to have a way to reproduce this.

**Comment by TherioLZ** [comment]
Sorry I've been gone for a while. Web services work just fine, it's literally only mobile clients that don't work well.

**Comment by Sbte** [comment]
And what about the rollback? Did that help?

**Comment by c10ud** [comment]
Some debug would help investigating, maybe a non existant font?

**Comment by TherioLZ** [comment]
@Sbte: I haven't been able to find an older build and I haven't been able to compile a newer build either so no luck there I'm afraid.

@c10ud: That might be the case, but I have emesene set to force one specific font so I'm not sure if that's the case. The logs don't really reveal any interesting info either.

**Comment by Sbte** [comment]
@TherioLZ https://github.com/emesene/emesene/downloads

**Comment by TherioLZ** [comment]
The rollback worked. Kind of forgot about this issue but yes, rolling back to 2.12.3 fixed the issue.

**Comment by moneycat** [comment]
Please try `git bisect` to identify which commit cause this issue.

**Comment by c10ud** [comment]
wait -- now that i see it, adiumtextbox working in w7 64bit (!) looks like #784 has been fixed (?)

**Comment by c10ud** [comment]
This issue could be windows specific: i tried giving the adiumtextbox some weird and non-existant font but it still worked, if someone has access to an ebuddy mobile contact it's time to test with linux and latest git

**Comment by Sbte** [comment]
Mobile -> linux works fine

**Comment by Sbte** [comment]
Mobile -> windows 32 bit doesn't work

**Comment by Sbte** [comment]
Doesn't work in older versions of emesene either.
