### ISSUE TITLE
File transfer error

### ISSUE THREAD

**Issue by NIVAROJAS** [emesene/emesene#1418]
there is a problem when someone sends to me more than one file. i can receive just the first one correctly. what could be happening?

**Comment by c10ud** [comment]
emesene version?

2012/7/21 NIVAROJAS
reply@reply.github.com:

**Comment by NIVAROJAS** [comment]
emesene 2.12.6-dev

**Comment by c10ud** [comment]
does that mean you're using git? which revision?

2012/7/21 NIVAROJAS
reply@reply.github.com:

**Comment by NIVAROJAS** [comment]
well... i have downloaded the zip file from git yesterday... the zip name is emesene-emesene-v2.12.5-240-geebd0bb.zip

i think is the last revision...

**Comment by c10ud** [comment]
ok then it would help knowing exactly how to reproduce this. which
clients were involved exactly? sending to who?

2012/7/21 NIVAROJAS
reply@reply.github.com:

**Comment by NIVAROJAS** [comment]
my friend is using windows live messenger, he was sending to me 3 files. i could receive the first one. but when i tried to get the second nothing happened. i was waiting for a long time but nothing... i had to restart emesene and try again... and the same... i could receive the second file successfully but when i tried with the third, i couldn't.

**Comment by c10ud** [comment]
which version of wlm?

2012/7/21 NIVAROJAS
reply@reply.github.com:

**Comment by jamesaxl** [comment]
@c10ud i think 2011 cause i had some problem here before

**Comment by c10ud** [comment]
probably fixed, same issue as  #1450, should be fixed in today's emesene
