### ISSUE TITLE
remove close on left option

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1422]
This only works in ubuntu and it's not consistently with others programs like firefox or gedit.
It's difficult to port it to Gtk3 and Qt4.

**Comment by Sbte** [comment]
I wanted to do this a while ago already, but I wasn't sure back then. +1 from me.

**Comment by moneycat** [comment]
Firefox and gedit show close button at right side even in unity. Maybe we can make it an option in Preferences if user want place the button on the right side? Or to check if `os.environ.get('DESKTOP_SESSION')` is `ubuntu` and emesene started with gtk?

**Comment by Sbte** [comment]
No, better to just keep it on the right. We add unneeded complexity that is inconsistent.

**Comment by moneycat** [comment]
Got it, so we just to remove the check in TabWidget.

**Comment by c10ud** [comment]
+1 for removal, looks like noone in the desktop ui thought it was a good idea...
