### ISSUE TITLE
do not leave offline contacts

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1426]
I wanted to see my contacts offline .... but I can not find the arrow to view

http://i.imgur.com/95cxx.png

**Comment by Sbte** [comment]
What options do you have enabled?

**Comment by moneycat** [comment]
Do you have enable "Show offline contacts"?

**Comment by KinG-InFeT** [comment]
i not enabled Show offline contacts but, if you've enabled the output of the offline contacts, should not go directly to the contacts and not just the number of them?

**Comment by moneycat** [comment]
@KinG-InFeT Sorry, I don't realize what you mean. Maybe you can try to enable it because all offline contacts will hide without to SHOW them.

If you have related problem, maybe you can capture other snapshots as example? :)

**Comment by KinG-InFeT** [comment]
So ... I am simply doing this:

1) abilitanto "Group Offline Contacs"
2) having disabled "Show offline contacs"

I thought you visualizzassero the contacts and not just the group name "offline" contact with the counter.

perhaps this is not a bug.

**Comment by moneycat** [comment]
The counter seems correct, there are totally 680 contacts and 12 of them are online, then there are 668 offline contacts.

Or I still misunderstand your problem?

**Comment by KinG-InFeT** [comment]
No no you misunderstand the problem, I did not have understood that it was necessary to enable both to view the list even offline contacts, while I thought that only allow the "Group" I vislualizzasse not only the meter but also the list of offline contacts.

I apologize for the misunderstanding, and I think we can close the track.

**Comment by Sbte** [comment]
Not a bug I guess
