### ISSUE TITLE
papyon warning

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1428]
When I change my status I got this warning in console "Trying to publish an empty MSNObject".
It's harmless but It would be nice to find where it comes from.

**Comment by c10ud** [comment]
That is content roaming with incomplete args e.g. avatar none... Check papylib worker, this was done quite on purpose to update only one thing at a time, but it maybe wrong..papyon accepts optional args but i never checked how it was handling them

**Comment by c10ud** [comment]
i think, since it works, that's better to leave things as it is.
i don't know what could happen setting the whole profile everytime we change something..
if instead this thing gives issues, we'll talk about it
