### ISSUE TITLE
Mountain Lion compatibility

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1430]
Can someone with OS X 10.8 mountain lion test emesene for me. I am unable to test as my Macbook 4,1 is unsupported and i'm not getting my Pro for another month. Just want to see if it works and if not i'll try and put a fix together.

So if someone could run this: https://github.com/downloads/joshf/emesene/emesene2125.dmg and report back, it would be much appreciated.

P.S I know this in not an issue, but google groups is like a graveyard!

**Comment by astagi** [comment]
Shared on G+, will notify you if someone replies..

https://plus.google.com/u/0/b/101164429412527615231/101164429412527615231/posts/cTcXiQwToXL

On Fri, Jul 27, 2012 at 8:40 PM, Josh Fradley
reply@reply.github.com
wrote:

> Can someone with OS X 10.8 mountain lion test emesene for me. I am unable to test as my Macbook 4,1 is unsupported and i'm not getting my Pro for another month. Just want to see if it works and if not i'll try and put a fix together.
> 
> So if someone could run this: https://github.com/downloads/joshf/emesene/emesene2125.dmg and report back, it would be much appreciated.
> 
> P.S I know this in not an issue, but google groups is like a graveyard!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/1430

## 

=.4ndrea.Stagi.=

**Comment by c10ud** [comment]
Still groups have a major chance of finding users than the issue tracker imho

**Comment by Sbte** [comment]
Yes, more users are subscribed to the users group that to the issue tracker. Even if no one posts on there, they will still receive mails.

**Comment by c10ud** [comment]
posted in the users ml since noone will read tickets unless developers :D
