### ISSUE TITLE
display previous message problem

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#1431]
when the option to display previous message is enabled when starting a conversation, it should display the lasts 3 messages of the last conversation right?
but it also duplicate the first message you're recieving, so,in the end, you got the lasts 2 messages + the new one twice..
I think it should be easy to solve
I'm using the latest version from git

thank you ^^

**Comment by Sbte** [comment]
Are you also using the latest plugin version?

**Comment by pepeleproso** [comment]
This is https://github.com/emesene/emesene-supported-plugins/issues/65
Not an easy one.
