### ISSUE TITLE
Base.Logger report error

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1439]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/devil/linux/emesene/emesene/e3/base/Logger.py", line 900, in run
    quit = self._process(data)
  File "/home/devil/linux/emesene/emesene/e3/base/Logger.py", line 920, in _process
    cid=cid)
  File "/home/devil/linux/emesene/emesene/e3/base/Logger.py", line 609, in add_event
    (id_src_info, id_src_acc) = self.insert_info(src.account, src.id,
AttributeError: 'Contact' object has no attribute 'id'

**Comment by Sbte** [comment]
What did you do when this occurred?

**Comment by Sbte** [comment]
Also, in what session

**Comment by c10ud** [comment]
@sbte he's writing a new session for qq

@wxjeacen when you add a contact set an unique id for it (can be anything)

**Comment by c10ud** [comment]
wait i'm wrong: there's no such thing..mmm

**Comment by Sbte** [comment]
No, it should be a Logger.Account which can be created using the from_contact method.

**Comment by c10ud** [comment]
maybe it was prior to https://github.com/linuxqq/emesene/commit/d107df30ffa4f0fa8367968926aa00569d0a1498 ?

**Comment by shwangdev** [comment]
_That is right :)_
*
*
*Any suggestions for this issue?
*
On Sun, Aug 5, 2012 at 6:28 PM, Riccardo <
reply@reply.github.com

> wrote:
> 
> maybe it was prior to
> https://github.com/linuxqq/emesene/commit/d107df30ffa4f0fa8367968926aa00569d0a1498?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/1439#issuecomment-7509124

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by Sbte** [comment]
Well, if that was the case, then you already fixed it. so no problem. You could also do this though.

Code suggestion:

```
log_account = e3.Logger.Account.from_contact(self.session.contacts.me)
```

It does exactly the same thing as you do but with less code.

**Comment by shwangdev** [comment]
*Thanks for you suggestion :)
*
On Sun, Aug 5, 2012 at 9:50 PM, Sven <
reply@reply.github.com

> wrote:
> 
> Well, if that was the case, then you already fixed it. so no problem. You
> could also do this though.
> 
> Code suggestion:
> 
> ```
> log_account = e3.Logger.Account.from_contact(self.session.contacts.me)
> ```
> 
> It does exactly the same thing as you do but with less code.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/1439#issuecomment-7510113

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_
