### ISSUE TITLE
\ works as escape character

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#144]
I tried to send some code to someone and noticed all \n were replaced by spaces. The same holds for other standard things like \t and \r, and for all other characters it's used as escape character. The recipient does get the actual code sent so that's not a real problem, but if I receive code myself, it would be nice if I could actually see the backslash and newline chars etc. 

This was using Adium. Normal text mode works fine.

**Comment by c10ud** [comment]
Fix escaping of backslash.

Can the escape method of AdiumTheme.py be moved to MarkupParser.py for great justice? Dunno, need some confirmation. Closed by 80cb708233dd338778e6bd8500999ec76746ba95
