### ISSUE TITLE
Can't read the message of some of my contacts

### ISSUE THREAD

**Issue by dw24** [emesene/emesene#1443]
I have the version 2.12.5 and I was starting to use the program and everything started fine till I couldn't see the text of some of my contacts when they messaged me. I changed the font color to black to seee everyones message but still couldn't see it. To see it I have to copy whatever is in box and paste it somewhere else.

**Comment by moneycat** [comment]
Could you paste the text or make a snapshot you cannot read in emesene to us? Then if possible, paste some log from console or debug window with type Error. Thnaks.

**Comment by Sbte** [comment]
Duplicate of #1417. Could you please specify what OS you are using?

**Comment by dw24** [comment]
I can take a snapshot but I don't know how do the rest and I am using Win XP
