### ISSUE TITLE
Authentification failure

### ISSUE THREAD

**Issue by wardVD** [emesene/emesene#1446]
Hi there

I'm constantly getting the error 'Authentification failure' when I try to log in... I'm new in Linux and I made a few mistakes. I had the problem for the first time when I used a proxy in Chrome but then switched it off. Somehow the proxy was still active (I don't know the details, a friend helped me out) but after deleting it everything seemed ok, except for emesene.

I used the sudo apt-get autoremove to remove emesene and installed it again but the same error keeps turning up. Can somebody please help me?

**Comment by c10ud** [comment]
Hello, emesene uses the system proxy, so if you disable it from the
control-center it should connect directly to the network

greets

2012/8/11 wardVD notifications@github.com

**Comment by wardVD** [comment]
If you mean that I simply have to delete the server and port in preferences so that it can automatically connect to the correct proxy then that doesn't help...

**Comment by wardVD** [comment]
Btw, I can log in my gmailaccount...

And I can log in with my hotmailaccount in Pidgin.

Just emesene and my hotmailaccount doesn't work.

**Comment by wardVD** [comment]
Oh and I can't log in on someone else his computer on emesene while he himself can log in...

The we tried for him to log in on my emesene but it doesn't work neither. I checked my password and account so that's not the problem btw.

**Comment by moneycat** [comment]
Sorry I cannot really understand what you mean at lastest post. Do you mean you cqnnot log into your account on your friend's pc even he can log into his account on the same pc?

By the way, which emesene version you are using?

**Comment by wardVD** [comment]
I'm using the Emesene2 from March 2011. The latest I presume.

What I meant by the latest post is that on MY computer (Ubuntu 12.04, Emesene2) neither my friend and I can log in to our hotmailaccounts, but we can log in our gmails. So hotmail -> no, gmail -> yes.

On HIS computer (Ubuntu 12.04, Emesen2) he can log in to both his gmail and his hotmail (!), I can only log in to my gmail. So his hotmail -> yes, my hotmail -> no, gmail -> yes.

I don't have any problem on Pidgin, I can log in to both gmail and hotmail.

Maybe this is a bit more clear.

**Comment by Sbte** [comment]
Since you've been messing with the proxy settings, you could try to remove `~/.config/emesene2` and then try again (back up this directory if you want to keep your history etc).

**Comment by wardVD** [comment]
Already tried that, didn't help.

**Comment by c10ud** [comment]
@wardVD latest is 2.12.5, please upgrade

**Comment by c10ud** [comment]
Also, if you provide some log (running emesene -vvv we could identify the cause better)

**Comment by wardVD** [comment]
Strange thing happened. Everything worked when I used it via the terminal. Now it works even without the terminal...

Problem seems to be fixed. I'll let it know if there is a problem.

Anyway, thanks for the time.
