### ISSUE TITLE
Special smiley transfer error

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1450]
I got an error in the terminal window while sending the special smiley. The smiley was not received - a white box was instead showed at daphne's msn.

Some information:
imo.im - website, uses libpurple 2.10.3
daphnevandiest ATSIGN live.nl was the receiver
iamking ATSIGN hotmail.be - me, i sent the special smiley.

More details in this file: http://hugsmile.eu/emesene/emesenebugspecialsmiley.txt
See also: http://hugsmile.eu/emesene/emesenebugspecialsmiley2

Some smileys are fine (showed), others aren't.

Used latest version (14 August, around 2 PM CET) from git.

**Comment by Sbte** [comment]
I think this is the only relevant part:

http://pastebin.com/2BPTiXuW

No errors there. Are you sure it's not an imo.im bug?

**Comment by Sbte** [comment]
<sbte> smile, we rolled file transfers back to what we previously had, so everything should work
<sbte> it would be useful if you tried the same smiley again or if you could also test it with emesene -> pidgin and emesene -> WLM
<sbte> if the bug only occurs with imo.im it's a bug on their side
<sbte> if it happens also with pidgin it's a bug in libpurple
<sbte> if it happens with all of them it's an emesene bug

**Comment by Smile4ever** [comment]
emesene -> pidgin with outlook.com address is fine. so, no bug in libpurple. not only first working, also second, third and fourth
emesene -> WLM with live.nl address - not fine. two times a different one, only one emoticon working - maybe the first emoticon was cached, like c10ud mentioned in #emesene
emesene -> imo.im with live.nl address - not fine
emesene -> WLM with outlook.com address - fine, second and third NOT.

Thoughts?

**Comment by moneycat** [comment]
In my account (@hotmail.com), my friend cannot receive custom emoticons I sent. However, I can receive emoticons from them (static and animate all works) after rollback the directly connection.

**Comment by c10ud** [comment]
[16:21] <c10ud> then it's the same old issue: transfers after the 1st fail
[16:21] <c10ud> and i don't know what's wrong since the code is practically the same as before
[16:22] <c10ud> and also that seems to apply to send only (?)

**Comment by Smile4ever** [comment]
Well sometimes with receiving I also see a white box.. Emesene doesn't support special smileys well, that's all I know.

**Comment by Sbte** [comment]
@moneycat do you mean with current master, or with an emesene version of around 2.12.3?

**Comment by moneycat** [comment]
@sbte git master at that day

**Comment by c10ud** [comment]
looks reproducible: after 1st transfer, subsequent transfers fail

and yes, wlm2009 does p2pv2

**Comment by Smile4ever** [comment]
@c10ud: since you closed the other issue I'll post my comment here.

version of emesene 2.12.3 does the transfers described in #1464 correctly on ubuntu 64 bit :)
so it's a regression. Maybe you can compare the code.

**Comment by c10ud** [comment]
I already bisected code for another issue related to transfers, bisecting this is hard..

**Comment by Sbte** [comment]
Well, it obviously goes wrong somewhere in the new code. We should check where it does something different from the old code. I will try to help, but your understanding of this is much better.

**Comment by c10ud** [comment]
diff: http://pastebin.com/ScDQLhxY

**Comment by c10ud** [comment]
please try updating and see if issue persists

**Comment by c10ud** [comment]
mh, it looks unrelated: but if i send stuff fast enough they seem to work.... so it could be a problem when the session is closed or something like that

**Comment by c10ud** [comment]
seems to work, please try above rev

**Comment by Sbte** [comment]
Does p2pv2 also work now if you re-enable it? Just curious ;P

**Comment by c10ud** [comment]
p2pv2 is already working, if you mean direct connection via TCP and similar stuff, then i don't want to cause any more pain to myself :p

**Comment by Smile4ever** [comment]
I can now receive and send special smileys! Thanks c10ud :) Please don't break it ;)

**Comment by c10ud** [comment]
i'll try :)

@Sbte release?

**Comment by Sbte** [comment]
@c10ud Let me first upload the translations to launchpad, then wait a few days, and then do the release. Otherwise translators get angry for not having a string freeze. Oh, and we're now in string freeze. Please don't commit any string changes (unless in qt).

**Comment by Smile4ever** [comment]
@c10ud After I used a lot emoticons, some were not shown anymore to my contact. Maybe it has something to do with cache. After a restart of emesene they showed up again.

**Comment by c10ud** [comment]
Sometimes the load-signal fails, check if clicking on the blank space twice it will change to the emoticon

or maybe transfer just failed (?)

**Comment by Smile4ever** [comment]
Well that's possible. Some (cached) emoticons were still working.
