### ISSUE TITLE
AttributeError: type object 'Dialog' has no attribute 'contact_information_dialog'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1452]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/qt4ui/menus/ContactMenu.py", line 76, in <lambda>
    lambda *args: self._handler.on_view_information_selected())
  File "/home/andre/emesene/emesene/gui/base/Handler.py", line 318, in on_view_information_selected
    self.dialog.contact_information_dialog(self.session,
AttributeError: type object 'Dialog' has no attribute 'contact_information_dialog'

Reproduce in QT4:

1) Open User Menu
2) Click Contact Information

**Comment by pepeleproso** [comment]
yes, the qtui is incomplete. This, the preferences and the file transfers widgets are the biggest part unimplemented.

**Comment by c10ud** [comment]
it is entirely missing, i added a notimplemented error for better understand what's going on, but if we must open a ticket for every piece missing.. ;)
