### ISSUE TITLE
Drag user as invitation

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1458]
d5158489df7336160c7ac0744c7e5ae64516bdd4

Because Invitation Window will take a long time before display for each time. I've implement this ability but I don't know how to eliminate the text paste to input. Any idea?

**Comment by Sbte** [comment]
I fixed this for file transfers before. 

e24230fc8350099cbc60f8e912aaf5cc9e9129e1

Hope it helps

**Comment by moneycat** [comment]
@Sbte I'm using this function too, but I don't know how to do then.

**Comment by Sbte** [comment]
I think this is the problem:

```
        self.enable_model_drag_source(gtk.gdk.BUTTON1_MASK, [
                                      ('emesene-contact', 0, 0),
                                      ('text/html', 0, 1),
                                      ('text/plain', 0, 2)],
                                      gtk.gdk.ACTION_COPY)
```

We should probably set a custom drag target for the textbox

**Comment by moneycat** [comment]
Thanks @Sbte, the prototype is done
