### ISSUE TITLE
[qt4] Broke Contact List

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1463]
1) Open Conversation
2) Close Conversation

Emesene here (Ubuntu) Broke emesene (contact list not appear anymore)

**Comment by pepeleproso** [comment]
probably you have the single window option enabled and it's not implemented on qt

**Comment by zipatei** [comment]
No, i dont have the single window option enabled

See:
1) Click close conversation ( http://imgur.com/sPDhc )
2) Result ( http://imgur.com/mjftS )

**Comment by moneycat** [comment]
Please paste error log from console if there is and if you can, thanks.

**Comment by c10ud** [comment]
just tried this, and it happens, no backtrace... however it is singlewindow here

**Comment by jamesaxl** [comment]
try to disable single window from "gtkui"

**Comment by zipatei** [comment]
yes, the problem is from single window.
