### ISSUE TITLE
[feature request] Search in Conversation History

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1474]
Is possible add the same comportmant of Gedit?

http://imgur.com/DGM4B

**Comment by Sbte** [comment]
This should already be there. If you click Next or Previous next to the search entry.

**Comment by Sbte** [comment]
For me, chat history stopped working in the msn session, but it still works in the dummy session... Probably me who broke it...

**Comment by zipatei** [comment]
But, now is necessary click to Next or Previous to the search entry for one each time.

In Gedit, write something and automatically searches (not necessary click to next or previous).

Other thing, in Gedit, selects all words equal to our search (yellow) and the actual word select (orange).

**Comment by zipatei** [comment]
1   0xb2b7f8a8 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3WTF10StringImplD1Ev+0x148) [0xb2b7f8a8]
2   0xb2a4ef08 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3WTF6VectorIN3JSC10IdentifierELj64EE6shrinkEj+0x58) [0xb2a4ef08]
3   0xb2a4e853 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC11ParserArenaD1Ev+0x203) [0xb2a4e853]
4   0xb2acfbc6 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC18FunctionExecutable19produceCodeBlockForEPNS_14ScopeChainNodeENS_15CompilationKindENS_22CodeSpecializationKindERPNS_8JSObjectE+0x426) [0xb2acfbc6]
5   0xb2ad1495 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC18FunctionExecutable22compileForCallInternalEPNS_9ExecStateEPNS_14ScopeChainNodeENS_7JITCode7JITTypeE+0x55) [0xb2ad1495]
6   0xb2a2561a /usr/lib/libjavascriptcoregtk-1.0.so.0(cti_vm_lazyLinkCall+0x19a) [0xb2a2561a]
7   0xa775e0c8 [0xa775e0c8]
8   0xb29de25c /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE+0x44c) [0xb29de25c]
Falha de segmentação (imagem do núcleo gravada)

**Comment by Sbte** [comment]
Gedit doesn't have to search an entire database. This is what complicates things. If you can think of a good way to implement it, then please let us know, but we can't come up with something better right now.

About the segfault: I noticed that too...

**Comment by zipatei** [comment]
Ah ok. You are right. :) I did not think about it.

**Comment by zipatei** [comment]
Reproduce segfault:

1) Click conversation history
2) Write something in search entry
3) Click clear search

**Comment by zipatei** [comment]
*\* Message: console message:  @0: NOT_FOUND_ERR: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.

*\* Message: console message: undefined @0: TypeError: 'null' is not an object

1   0xb2c058a8 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3WTF10StringImplD1Ev+0x148) [0xb2c058a8]
2   0xb2ad4f08 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3WTF6VectorIN3JSC10IdentifierELj64EE6shrinkEj+0x58) [0xb2ad4f08]
3   0xb2ad4853 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC11ParserArenaD1Ev+0x203) [0xb2ad4853]
4   0xb2b55bc6 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC18FunctionExecutable19produceCodeBlockForEPNS_14ScopeChainNodeENS_15CompilationKindENS_22CodeSpecializationKindERPNS_8JSObjectE+0x426) [0xb2b55bc6]
5   0xb2b57495 /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC18FunctionExecutable22compileForCallInternalEPNS_9ExecStateEPNS_14ScopeChainNodeENS_7JITCode7JITTypeE+0x55) [0xb2b57495]
6   0xb2aab61a /usr/lib/libjavascriptcoregtk-1.0.so.0(cti_vm_lazyLinkCall+0x19a) [0xb2aab61a]
7   0xa70c70c8 [0xa70c70c8]
8   0xb2a6425c /usr/lib/libjavascriptcoregtk-1.0.so.0(_ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE+0x44c) [0xb2a6425c]
Falha de segmentação (imagem do núcleo gravada)

**Comment by moneycat** [comment]
The rest issue should be report as a new bug.

**Comment by c10ud** [comment]
closing this, please refer to #1477
