### ISSUE TITLE
I dont can close emesene after click disconnect in main menu

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1475]
Menu is active in it after clicking disconnect

**Comment by moneycat** [comment]
Can you paste error log or take a snapshot of it. I'm not really understand the issue you described.

**Comment by zipatei** [comment]
http://imgur.com/DNsJJ

Reproduce:
1. Login 
2. click file >> disconnect
3. click file

**Comment by moneycat** [comment]
Issue confirmed, but it ONLY affect in Unity. Gnome-shell is unaffected,

**Comment by Sbte** [comment]
Stupid global menu. This might as well be a Unity bug.
