### ISSUE TITLE
The Language setting doesn't affect stock items

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1496]
I've set the language of emesene to Dutch. However, I see untranslated messages appearing. On Launchpad Dutch is 100% complete. Maybe the string names are not correct?

Edit: With French, parts (including some of the Dutch version) are not translated. Note @ this: French is not 100% perfectly translated on LP.

**Comment by c10ud** [comment]
which strngs exactly? examples?

**Comment by Sbte** [comment]
If those are strings that you updated since the last launchpad sync, then it's because the translations are not in git yet.

**Comment by Smile4ever** [comment]
They were updated before that, I'm sure!
For example, in tray menu:
- quit
- preferences
- disconnect
- status submenu: all not translated, except for "onzichtbaar" (I think this is hidden in the English emesene)

actions => contact person => add (should be "Toevoegen")

**Comment by Sbte** [comment]
Those are stock items. I think those should be translated by your OS.

**Comment by Smile4ever** [comment]
But they aren't, since my OS is in English.

**Comment by Sbte** [comment]
This is because if you change the language through the settings we change the gettext language but not the environment language. So stock items are not translated.

**Comment by Smile4ever** [comment]
Since I have all Dutch language packs installed, emesene can take the stock items from there.
