### ISSUE TITLE
various DEBUG

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1498]
just started out this error:

``` python
/usr/share/emesene2/gui/gtkui/ContactList.py:529: GtkWarning: _gtk_rbtree_reorder: assertion `tree->root->count == length' failed
  return self._model.append(self.online_group_iter, contact_data)
```

change the sort order from state to group and get this error:

``` python
/usr/share/emesene2/gui/gtkui/__init__.py:102: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
```

**Comment by Smile4ever** [comment]
I cannot spot the second bug if there are no contacts online. So there is something wrong with ordering existing contact persons, which is weird.

**Comment by c10ud** [comment]
Unless you see direct errors don't bother: warnings are harmless
