### ISSUE TITLE
problem with the keyboard shortcut ESC (reproducible)

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1499]
and has come back the problem of the keyboard shortcut ESC ... and not out of the main window.

Riproducibile:

1)run for the first time emesene and the keyboard shortcut ESC works without problems
2)but after opening a dialog single-window mode
3)the keyboard shortcut only works to close the dialog box but not the main window.

else maybe some problems during the transition from the closing of the dialog box, the main window.

**Comment by Sbte** [comment]
This is done on purpose (if I understand correctly what you mean)

**Comment by KinG-InFeT** [comment]
NO! As I wrote above:

I open a conversation
I close with the shortcut ESC
I close the main window (but not CLOSES)

**Comment by KinG-InFeT** [comment]
why close the issue?

**Comment by Sbte** [comment]
Ah, sorry, I misunderstood the issue. I'll see if I can fix that right now

**Comment by KinG-InFeT** [comment]
quiet, test yourself and see if the bug still persists.

**Comment by KinG-InFeT** [comment]
fixed , thanks.
