### ISSUE TITLE
[qt4 - Single Window] Close Conversatio not resize window

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1501]
Reproduce:

1) Open conversation
2) Close conversation

http://imgur.com/5zCNR

**Comment by pepeleproso** [comment]
yes, resize in single windows mode is broken. this affects the login window too.

**Comment by pepeleproso** [comment]
This patch improves the situation but it doesn't fixed it completely

**Comment by c10ud** [comment]
ok, jamesaxl improved the situation
