### ISSUE TITLE
[gtk] Strings to import

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#1505]
I think the "disconnect endpoint" string (from file menu) is not translatable, please confirm. (in particular in italian git version)

also:
"sort contacts by name" (from option menu)

in preferences:
"enable spellcheck"
"weekly verify plugin update"
"mute notification"
"notify when info of signed in location is changed"
"disconnect other endpoint when loggind in"
"endpoint name"

**Comment by Sbte** [comment]
They will be translated once the translations are imported from launchpad. This doesn't happen automatically. Usually I do this every week.

**Comment by Fabioamd87** [comment]
ok but I don't think this "issue" is fixed...

**Comment by moneycat** [comment]
@Fabioamd87 You also can help to translate strings if you want: https://translations.launchpad.net/emesene/ :)

**Comment by Sbte** [comment]
This is fixed in the sense that Italian is 100% translated on launchpad.

**Comment by Fabioamd87** [comment]
waiting for the import for test if every string is translated.
