### ISSUE TITLE
Program no response

### ISSUE THREAD

**Issue by kobergkamp** [emesene/emesene#1507]
No matter I am running 2.12.3 or 2.12.5 on windows xp, emesene didn't start after double click.

the log wrote:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)
Traceback (most recent call last):
  File "emesene.py", line 56, in <module>
  File "emesene.py", line 48, in project_path
  File "os.pyo", line 420, in **setitem**

**Comment by c10ud** [comment]
Please hold on until we have a 2.12.9 binary available so you can see if issue persists

**Comment by juanraig** [comment]
Hello I have installed version 2.12.9 in windows 7 premium x64 and program does not start when I try to start.
Thanks for this great program.

**Comment by Sbte** [comment]
This error seems fixed. Please refer to #1516

**Comment by juanraig** [comment]
Hello, but where or how has it been fixed?. Installer is the same but not
working for me.
Thanks and apologizes from Juan in Barcelona (Spain)

2012/9/10 Sven notifications@github.com

**Comment by Sbte** [comment]
Because we released 2.12.9. Your version gets past the line in this issue.
