### ISSUE TITLE
Debian stable AttributeError

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1508]
Traceback (most recent call last):
  File "/net/users/ont/ont8020/emesene/emesene/gui/gtkui/Renderers.py", line 115, in on_render
    xalign, yalign = self.get_alignment()
  File "/net/users/ont/ont8020/emesene/emesene/gui/gtkui/Renderers.py", line 72, in **getattr**
    raise AttributeError, name
AttributeError: get_alignment

**Comment by Sbte** [comment]
@moneycat git blames you for this

**Comment by moneycat** [comment]
@Sbte Python 2.6?

**Comment by Sbte** [comment]
@moneycat yes, and gtk 2.20. This seems to work:

```
        # xalign, yalign = self.get_alignment()
        xalign = self.get_property('xalign')
        yalign = self.get_property('yalign')
```

**Comment by c10ud** [comment]
Is that the only issue with deb?
Il giorno 05/set/2012 10:49, "Sven" notifications@github.com ha scritto:

**Comment by Sbte** [comment]
So far, yes

**Comment by Sbte** [comment]
@moneycat please fix the issue adressed by @c10ud and push the code.
