### ISSUE TITLE
Can't send offline messages

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#151]
Got this error:

error sending message because 3 1
error sending message because 4 1
error sending message because 4 1
error sending message because 4 1
error sending message because 4 1

when sending four messages. The contact doesn't receive offline messages.

**Comment by c10ud** [comment]
i didn't implement OIMs yet, i think

**Comment by c10ud** [comment]
implemented

**Comment by Sbte** [comment]
Sending works now indeed. Thanks for the fast implementation. Should I open a new issue for receiving? Because that still doesn't work.
