### ISSUE TITLE
emesene keeps asking for facebook permission

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1511]
Every time i connect to facebook, i am prompted to reauth as emesene isnt storing the token properly. This happens in 2.12.9 but worked up until about two weeks ago i think.

```
/Applications/emesene.app/Contents/Resources/emesene/e3/xmpp/SleekXMPP/sleekxmpp/xmlstream/stanzabase.py:1188: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value is None or value == '':
```

Not sure if thats relevant or not

**Comment by c10ud** [comment]
@pepeleproso 
Anyway, the error is not related since i suspect this is the facebook integration (pyfb) instead of SleekXMPP

**Comment by pepeleproso** [comment]
please retry with current git version I update pyfb. I can't reproduce it here.

**Comment by pepeleproso** [comment]
initial message? you have to get it only the first time. I tried again and it's working fine here. maybe is mac specific?

**Comment by pepeleproso** [comment]
that's a bug in SleekXMPP, you should report that upstream.

**Comment by Sbte** [comment]
Is the original bug fixed?

**Comment by joshf** [comment]
Okay the original bug is not fixed

This error is not related to the bug

```
/Applications/emesene.app/Contents/Resources/emesene/e3/xmpp/SleekXMPP/sleekxmpp/xmlstream/stanzabase.py:1188: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value is None or value == '':
```

**Comment by Sbte** [comment]
We just updated the SleekXMPP version, so it could be that this works now.

**Comment by joshf** [comment]
Done some investigating, this issue is nothing to do with SleepXMMP the error is irrelevant. Emesene is not getting the access token properly from the fallback method where we paste the url. I tried to fix, but i had no luck.

**Comment by pepeleproso** [comment]
Problem here is that I test it with webkit. The fallback method is efectively broken. I'll make a patch in a minute
