### ISSUE TITLE
.10-dev cache is broken

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#1512]
06b0c738e9c7d43c45231d23b7c99ddab9032286 seems to be choosing the wrong directory, why is that?

**Comment by Sbte** [comment]
This is because in emesene.py the session is instantiated like this:

```
self.session = extension.get_and_instantiate('session')
```

This means that Session is created without an account, so `_set_account` is not called. `_set_account` sets the `base_dir`

**Comment by c10ud** [comment]
thank you sir
