### ISSUE TITLE
DND to send a file will be twice

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1518]
When DND a file into conversation textbox, it will show twice (and the receiver will got two file invitation).

**Comment by moneycat** [comment]
e2bc72c894df174cc20c1834e08abd120a0f0c04 is the first bad commit

I have no idea what happened there. Everything seems double in the `on_drag_data_received` in Conversation.py.

**Comment by moneycat** [comment]
@Sbte Could you please test this patch in Debian to see if it works? Thanks.

**Comment by Sbte** [comment]
Why such a huge patch? Isn't it possible to just find a better constant? It worked before right?

**Comment by moneycat** [comment]
In my environment, any file DND to textbox will be two (same, duplicate) transfer files. However the contact will be twice, but we eliminate it since we check if user is added to group or not.
My solution is to add a drag-drop function (like it did in ContactList) to finish the DND action but I add it in the way the drag_recieve_data function do. Then I also reorder the custom target setting to make it the same location as add_uri is when drag_recieve_data exists.

**Comment by Sbte** [comment]
Even with a different constant?

Anyhow, why would this not work on debian? I don't see any new functions ;)

**Comment by moneycat** [comment]
Is thee different constant you mean like "('emesene-invite', 0, 3)"? If yes, I think it is no work.
Anyhow, I just want to make sure in other desktop environment (not gnome-shell) will work. :)

**Comment by Sbte** [comment]
I mean the constant I changed in e2bc72c

**Comment by moneycat** [comment]
gtk.DEST_DEFAULT_DROP is work, and I've try to _ALL/_MOTION are useless :)

**Comment by Sbte** [comment]
Ok, really weird then. Anyhow, the reason that I changed it was because it didn't work on Gtk3. You could try to test it in Gtk3 mode.

**Comment by Sbte** [comment]
Also, I don't really care if such a feature doesn't work of really old gtk versions (Debian).

**Comment by moneycat** [comment]
ah...gtk3 broken.
Thanks for hinting.
