### ISSUE TITLE
Error when pasting more than 1 line in the send box

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#152]
*\* (emesene:2255): CRITICAL **: murrine_style_draw_box: assertion `height >= -1' failed

Way to reproduce: Open a chat window. Paste

test
test

**Comment by c10ud** [comment]
i think that's an error in the theme engine, not emesene nor gtk

**Comment by Sbte** [comment]
I thought so too, but I wasn't sure. Could have been that it was something easy to fix ;)

**Comment by c10ud** [comment]
it's an error in the gtk theme engine related to the scrollbar, i guess there's nothing we can do than forcing one particular box height, which is something i'm not willing to do, i'll close this issue since the thing doesn't crash or smth
