### ISSUE TITLE
Segfault when receiving too many notifications

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1525]
How emesene is running normally, probably too many notifications are going to crash emesene Segmentation fault.

Note: the notification daemon is started.
OS: Arch Linux
WM: Fluxbox
emesene version: last git version

Complete LOG:

http://sprunge.us/BeiE

**Comment by c10ud** [comment]
How many notification did you receive? I don't think we can spam the notification daemon that much

**Comment by KinG-InFeT** [comment]
I've had a maximum of forty
