### ISSUE TITLE
emesene 2.12.9 for windows and webcam

### ISSUE THREAD

**Issue by juanraig** [emesene/emesene#1526]
Hello I would like to know if it is possible to use webcam in the windows version of emesene.
If it is yes, can you tell me how?
Thanks and apologizes.

**Comment by Sbte** [comment]
No. This is because Microsoft uses some codec that doesn't have an open source variant. Therefore, it is impossible for us to add webcam support.

**Comment by c10ud** [comment]
Sorry but it's not possible, the old webcam support is gone, the new Audio/Video cannot be used since we don't have any free codec to use, not in windows, not in linux
