### ISSUE TITLE
contact list empty

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1527]
emesene just opened, the contact list is empty

[INFO]
OS: ArchLinux
WM: FluxBox
emesene: last git version
Screen: http://i.imgur.com/pMeCU.png

EDIT:

reappears after a few minutes (if someone contacts me, otherwise it is empty), producing errors in debug

LOG: http://sprunge.us/OPZi

**Comment by Sbte** [comment]
#1522
