### ISSUE TITLE
update plugin system

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1528]
In version 2.12.1 sbte implement metadata for plugins https://github.com/emesene/emesene/commit/21abf72bcadf5e15aba753fe93876b74cef3db71

I think we need to remove the old method we have to get plugin description to avoid the data duplication between those two methods.

Note: that only plugins with new method support plugin updates.

@c10ud  and @Sbte  I want your green light on this.

patches for emesene are in my repo, I'll update the plugins once those get merged

**Comment by c10ud** [comment]
Agreed
Il giorno 22/set/2012 01:18, "jose Rostagno" notifications@github.com ha
scritto:

**Comment by Sbte** [comment]
Should be ok I guess

**Comment by pepeleproso** [comment]
it's done now
