### ISSUE TITLE
An emesene2 model

### ISSUE THREAD

**Issue by Zincr0** [emesene/emesene#153]
An uml model (or similar) of emesene2 could be very usefull to understand the code.
At this moment for example, I ought to read all the code to find where the login function of papyon library is called to limit the password length.

**Comment by c10ud** [comment]
http://emesene.org/docs/

btw, there's no papyon documentation in that

note: it's not complete documentation, just a stub

**Comment by marianoguerra** [comment]
ask the questions you want answered in the mailing list and I will document them.

a UML diagram wont be of much help, the structure of emesene is pretty dinamic and extensible, almost everything is an extension so there is no fixed structure of classes. a list of "where can I find the code that does X?" would be more useful I guess.

just start asking questions in the mailing list :)

closing.

**Comment by Zincr0** [comment]
last week i found what i was looking for. Anyway, when i find the mail list i´ll suscribe.

**Comment by marianoguerra** [comment]
http://lists.emesene.org/
