### ISSUE TITLE
Span not ignored in message history

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1531]
See http://i49.tinypic.com/2ptcksk.jpg. Those span tags shouldn't be there. My suggestion: strip them out.

**Comment by jamesaxl** [comment]
what is the version that are you running ? and OS ?

**Comment by moneycat** [comment]
Seems the '<' did not escape before processing span tags and led the parser crazy.

**Comment by Smile4ever** [comment]
Current dev version on Bodhi Linux. (2.12.10)

---- Aan Tue, 02 Oct 2012 21:12:55 +0200 jamesaxl &lt;notifications@github.com&gt; schreef ---- 

what is the version that are you running ? and OS ?
