### ISSUE TITLE
usr/bin/emesene2: line 3:   982 Errore di segmentazione python2 /usr/share/emesene2/emesene

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1541]
LOG: http://sprunge.us/NKfK

click on "file" menu and crash

**Comment by Sbte** [comment]
Please try to run emesene in gdb and get a backtrace. This doesn't tell us anything.

**Comment by KinG-InFeT** [comment]
politely if I write the string to start it in gdb and save the output you would do me a favor.

**Comment by Sbte** [comment]
```
cd to emesene directory
gdb python
r emesene.py
wait until it segfaults
bt
```

The output you can just copy-paste. We most likely only need the output of the full backtrace.

**Comment by Sbte** [comment]
Closing, because this bug has been marked as incomplete for a month already.

**Comment by KinG-InFeT** [comment]
the problem and that is something random and not easy to spot.

**Comment by Sbte** [comment]
If you run emesene in gdb every time, you should be able to spot it as many times as you would without running gdb.

**Comment by KinG-InFeT** [comment]
In fact, I'm adjusting well, but it happens more for quite a while.
