### ISSUE TITLE
emesene disappeared

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1563]
emesene ... I started reading the mail account .... close emesene in the system tray and disappeared also being running.

LOG: http://sprunge.us/cSUV
Screen: http://i.imgur.com/pgfOJ.png

EDIT:
emesene is back after a few minutes in an infinite login.
LOG_2: http://sprunge.us/cLOW

the major errors can be found at the end of the file.

**Comment by Sbte** [comment]
#1536
