### ISSUE TITLE
Notifications flood on login

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1564]
When ever i login to facebook i get about 50 notifications, any way to stop this?

This happens with my growl plugin and with the gtk one

**Comment by c10ud** [comment]
IIRC with xmpp there's no way we can distinguish post-login presence
updates from pre-login, so the only solution is adding a timeout e.g. 30
secs and then notifications are enabled (that was the old emesene solution
afaik)

2012/11/29 Josh Fradley notifications@github.com

**Comment by Sbte** [comment]
Sounds like a good enough method to me :P
