### ISSUE TITLE
Can't receive multiple line messages

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#158]
Only happens from some users. I think it's from people not using emesene (receiving from emesene1 works too, so I can't test it), so it's maybe windows line breaking or something (or CR?)? The only message I get is this:

*\* Message: console message: undefined @1: SyntaxError: Parse error

I can see it in the notifications. It's probably Adium not handling this correctly.

**Comment by marianoguerra** [comment]
it may be that they send \r\n instead of \n

**Comment by Sbte** [comment]
Yeah, that's what I meant with CR. I thought I also missed a message from someone with a mac once, and they also use CR (and CR only, not CR LF like Windows).

**Comment by marianoguerra** [comment]
go to gui/gtkui/AdiumTextBox.py line 70

and replace:

```
    html = html.replace("\n", "<br>")
```

for:

```
    html = html.replace("\r\n", "<br>")
    html = html.replace("\r", "<br>")
    html = html.replace("\n", "<br>")
```

tell me if this works

**Comment by c10ud** [comment]
Also handle \r\n (win) and \r (osx) as newlines in AdiumTheme. Closed by 284d3e2387d0f188104a9dddf287880030b23bd2

**Comment by Sbte** [comment]
Yes, works. I would have fixed it myself, but i don't have time atm. Thanks for the fast fix. I hope I can help you guys a bit next week or so ;)

**Comment by c10ud** [comment]
mariano, i didn't read your message and fixed in another way, is that ok for you?

**Comment by marianoguerra** [comment]
yep, then you could remove the replace in AdiumTextBox it shouldn't break since that work is duplicated.
