### ISSUE TITLE
No notifications of new mails

### ISSUE THREAD

**Issue by detlilleegernsven** [emesene/emesene#1587]
Emesene 2.12.9 dosn't give me notifications of new email, iam using windows 7 64 bit and outlook.com

**Comment by dequis** [comment]
Microsoft broke it in their servers. Doesn't work in any client. See:

http://messengergeek.wordpress.com/2014/04/15/e-mail-message-count-and-notifications-broken/

(#1590 looks suspiciously similar to this)
