### ISSUE TITLE
Please create an AppData file for emesene

### ISSUE THREAD

**Issue by hughsie** [emesene/emesene#1588]
Please consider writing and installing an AppData file with the application description and some screenshots, else emesene looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by c10ud** [comment]
Richard,

thanks for your interest but emesene, due to its msn-centered nature, is at
the moment abandoned (the msn service has been shutdown) hence package
managers may as well hide it from their catalog.

Ciao,
Riccardo

2014-05-27 16:39 GMT+02:00 Richard Hughes notifications@github.com:

**Comment by hughsie** [comment]
Thanks for letting me know.
