### ISSUE TITLE
[adium themes] buddy avatar 

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#16]
with current theme the avatar is showed correctly near bubbles, however the css header doesn't show it.

how about fixing this so users (read: me :p) can hide the avatars on right?

**Comment by cando** [comment]
other issue: i can't visualize this header....

**Comment by c10ud** [comment]
or: why the hell do i have this? http://img29.imageshack.us/img29/4751/schermata2jd.png

**Comment by ivan25** [comment]
I have that header too, without buddy's image.
http://img97.imageshack.us/img97/9649/schermatafh.png (dummy session)
theme: renkoo

**Comment by cando** [comment]
why i don't have the adium theme combo in my preferences?

**Comment by c10ud** [comment]
because you must pull from his branch. now i'll push every fork back in master :D

**Comment by ivan25** [comment]
I have added that combo this afternoon (in my repo) because I didn't find where to change adium theme.

**Comment by cando** [comment]
ah ok!fine...!

**Comment by cando** [comment]
the header visualization was only a theme problem...with renkoo theme i can see this header...
(the issue remains:i can't see my avatar!)

**Comment by c10ud** [comment]
i think the header needs some other adium hax, maybe wariano can look into this

**Comment by c10ud** [comment]
or, we kill the header :p

**Comment by ivan25** [comment]
i'm for the second option (imho the header doesn't make sense, there are avatars near the messages and start time is useless/you can scroll the page to the top, and this solve an issue :p)

**Comment by cando** [comment]
i agree with ivan..

**Comment by c10ud** [comment]
i was waiting for wariano's response, maybe it's something fixable or...

**Comment by marianoguerra** [comment]
the header has no avatar because I didn't coded that yet :D

about killing the header: +1 we already have a header, we should hack the theme.

anyone?

**Comment by c10ud** [comment]
fine for removing the header
