### ISSUE TITLE
Little typo in AdiumThemes.py

### ISSUE THREAD

**Issue by adryitan** [emesene/emesene#160]
In the file "emesene/gui/base/AdiumThemes.py", line 84 (https://github.com/emesene/emesene/blob/101737320f8092eee7b245b657aef50173f7edda/emesene/gui/base/AdiumThemes.py#L84), it says "directoy", but is "directory".

```
--- AdiumThemes_git.py  2010-11-03 19:46:10.778984348 +0100
+++ AdiumThemes_fixed.py    2010-11-03 19:46:55.858985486 +0100
@@ -81,7 +81,7 @@
         '''

         if not os.path.isdir(theme_path):
-            return False, _("%s is not a directoy") % (theme_path,)
+            return False, _("%s is not a directory") % (theme_path,)

         return self.validate_structure(theme_path, REQUIRED_FILES)
```

**Comment by c10ud** [comment]
Little typo in AdiumThemes.py, thanks adryitan. Closed by 7d3f3d63454247a160d2a7a894494c4e51a03988
