### ISSUE TITLE
spell checking

### ISSUE THREAD

**Issue by underguiz** [emesene/emesene#163]
i'd like to see spell checking built into emesene2

**Comment by marianoguerra** [comment]
fixed

**Comment by underguiz** [comment]
thank you kind sir.

**Comment by Sbte** [comment]
Is it possible to make this optional, or even a plug-in? My system is in Dutch, so when I type English, everything is red :P

Of course selecting a language per contact or per chat window and possible even saving that would be even more awesome, but that's probably a bit of an overkill for now ;)

EDIT: Or even auto detection. Now THAT would be awesome xD

**Comment by marianoguerra** [comment]
right click on the input widget and you can select the language.

**Comment by Sbte** [comment]
Ah thanks. That seemed to simple to be true :P
