### ISSUE TITLE
Start Conversation Window Minimized

### ISSUE THREAD

**Issue by underguiz** [emesene/emesene#164]
We should have an option in preferences to start conversation windows minimized.

**Comment by marianoguerra** [comment]
when the other user start the conversation to avoid stealing the focus?

**Comment by underguiz** [comment]
yes, exactly.

**Comment by c10ud** [comment]
Minimizing new conversation (enabled by default, configurable). Closed by 6969e608aba20569dcd02b27c1a57329f534c09d

**Comment by underguiz** [comment]
thank you, now people around me won't be surprised with strange talks poping out of nowhere.

**Comment by Sbte** [comment]
Wow. Now it first popped up and then immediately minimized when someone started talking (so it didn't start minimized, but immediately became minimized). I really had a wtf moment right there. Is this what is supposed to happen?

**Comment by c10ud** [comment]
right, fixed
