### ISSUE TITLE
Received offline messages show the time at which you logged in

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#165]
Received offline messages show the time at which you logged in. I think they should actually display the time (and day) they were sent on. The current implementation is quite confusing.

**Comment by c10ud** [comment]
i didn't found a way to easily override the timestamp in adium themes, if someone could help

**Comment by c10ud** [comment]
Nice date/time in received offline messages. Closed by ceebf725eee07569935d682d13f62eff34bb7152

**Comment by Sbte** [comment]
Seems to work perfectly well. Thanks ;)
