### ISSUE TITLE
[appindicator] add contact list

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#17]
i'm willing to add a contact list to emesene indicator, lemme know if you have some nice idea about this

**Comment by cando** [comment]
mmm....you mean something like facebook (the contact list on the right?)

**Comment by c10ud** [comment]
kinda. i thought of a simple gtk submenu that holds all avail contacts (pixbuf+string). it would be nice since it would allow (**future**) an use without the mainwindow opened (with all memenu, messaging indicator stuff)!

anyway: not really sure on how to get/order the clist and how to/when update it

(note: i think adium already has something like that)

**Comment by cando** [comment]
ok..! +1 for this idea...anyway is there anybody working on indicator and memenu??I'm using emesene 2 on lucid and without trayicon is very unusable..:)

**Comment by c10ud** [comment]
indicator should work out of the box

NOTICE: i didn't pull latest wariano's changes, so it may need some updates (read: "how to get themes directory" changed i think)

**Comment by c10ud** [comment]
just pulled, and works (i'm on lucid x64)

**Comment by cando** [comment]
here on lucid x32...doesn't works...emesene doesn't appears in the messaging menu and the mialbox doensn't turn green when i receive a message...

**Comment by c10ud** [comment]
this is maybe offtopic in this issue but:
i think messaging menu and appindicator should team-up instead of being alternative extensions of tray icon. i know they (canonical) think IM applications shouldn't use the appindicator, but since i want to expose the contact list and maybe something else through that appindicator so users can use emesene without the main window being opened.....

**Comment by cando** [comment]
yeah...why not?we can try!!!!and if we do not like it we can return as it is now!

**Comment by c10ud** [comment]
ok, can you merge the messagingmenu with the appindicator or i do it?

**Comment by cando** [comment]
if you aren't in a hurry i can do it...but not before a few days....I'm studying for some exams...

**Comment by c10ud** [comment]
ok, things have been merged. 

contact-list-in-indicator needs to be finished
messaging menu needs to be fixed

**Comment by cando** [comment]
perfect!thanks!

**Comment by c10ud** [comment]
issue with contact-list in you tray: seems like the appindicator doesn't like gtk submenu? i'm connecting to contact-changed-something signal but nothing changes in the indicator.. need to do a small example and notify upstream

**Comment by c10ud** [comment]
http://emesene.pastebin.com/k5fBF5T2 testcase, now trying to notify upstream

**Comment by c10ud** [comment]
https://bugs.launchpad.net/ubuntu/+source/indicator-application/+bug/530138

seems like someone already reported the issue, i could go with .add() and workaround the issue :)

**Comment by c10ud** [comment]
ok, now it works quite good

```
    # TODO: show [pixbuf] [nick] instead of mail
    # TODO: some contacts send nick-changed signal 
    #       with their mail instead of nickname (even if they have one)
```

**Comment by c10ud** [comment]
need to figure out why gtk.imagemenuitem doesn't work as expected, as soon as github lets me push my code

**Comment by c10ud** [comment]
i think it's not available yet in appindicator?

**Comment by marianoguerra** [comment]
this issue seems to have a lot of feature requests, bug reports and discussion in it.

could you create separated issues and discuss the development on the mailing list?

kthxbye
