### ISSUE TITLE
Custom emoticon is not saved one first received message

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#170]
If you first message you receive from someone (the one opening a new tab) contains an emoticon, that emoticon is not saved to .config/emesene2/..../emoticons, and so it is not displayed.

Other than that custom emoticons work now. Thanks for that ;)

**Comment by c10ud** [comment]
seems like papyon isn't parsing received msn_objects at all on first switchboard message..quite strange, i'm now seeing if i can track down where shit happens (notified upstream, meanwhile)

**Comment by c10ud** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=31430

fixed locally, we'll have to wait for upstream

**Comment by c10ud** [comment]
closing, since atm there's little that can be done
