### ISSUE TITLE
Name in task bar switches to first tab's name

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#171]
When someone logs in or out and the notification is displayed (doesn't matter who logs in or out), the name in the task bar changes to the name of the one in the first tab.

Say we have two tabs open, with person A and person B. The focus is on person B. Now when someone logs in, say person C, the name in the task bar changes to A, whereas the focus stays on person B

**Comment by arielj** [comment]
I can't confirm this, I have 3 tabs opened and the taskbar is always showing the current tab title after login and logout of contacts

EDIT: I can conirm this but ONLY after reordering tabs (drag and drop tabs on different order)

**Comment by Sbte** [comment]
Or shutting down a tab (like one of three), which I think is what I did, but forgot to mention.

**Comment by c10ud** [comment]
Trying to cleanup a bit some mess in conversation/conversationmanager code. Hopefully closed by 2c45913a9ce789ce3f2da70d115e0246d6a71f38

Please test, kthxbi

**Comment by Sbte** [comment]
Yep, works :D
