### ISSUE TITLE
Empty Contactlist

### ISSUE THREAD

**Issue by huuhaa** [emesene/emesene#172]
For a while by now emesene 2 started to show empty contact list. I've been using Empathy lately (partly cause dual mode msn & facebook) so I haven't check updates so often, so can't really say when exactly this started. I just tried to update with git pull and got updates, but still not working. Here is output:

python -d emesene.py
No handlers could be found for logger "papylib.Worker"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/username/emesene/emesene/e3/base/Logger.py", line 721, in run
    self.logger = Logger(self.path)
  File "/home/username/emesene/emesene/e3/base/Logger.py", line 281, in __init**
    self.connection = sqlite.connect(full_path)
OperationalError: unable to open database file

[22:17:54 WARNING papyon.protocol] Notification unhandled command : GCF 0 5521
    [payload]
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/papyon/client.py", line 385, in state_changed
    self._state = ClientState.OPEN
  File "/usr/lib/pymodules/python2.6/papyon/client.py", line 278, in fset
    self._dispatch("on_client_state_changed", state)
  File "/usr/lib/pymodules/python2.6/papyon/event/__init__.py", line 44, in _dispatch

I'm using emesene in ubuntu 10.4 (64bit if that's matters, but I think it doesn't.) Python version ios 2.6.5 and I'm using gnome (but you already know about that, since I said ubuntu and not kubuntu or something like that).

**Comment by c10ud** [comment]
update your papyon copy to 0.5.2 and it will work, and oh, just cd to emesene dir and ./emesene

**Comment by huuhaa** [comment]
Stupid question, but what is the recommended way to update papyon? After all it's only version 0.5.1 in ubuntu 10.10 repos, and as said, I use 10.04 (have used enough those "betas", but this comes to OS, sure beta version of app, as emesene is intresting :D)

http://packages.ubuntu.com/search?lang=fi&arch=amd64&searchon=names&keywords=papyon

PS. Feels quite uncomfortable to write in the github, since feels like you should be way more experienced before writing anything here. In forums it's easier to ask stupid question like these. :D

**Comment by c10ud** [comment]
if you want to use emesene2, just follow these instructions:

http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

**Comment by huuhaa** [comment]
Damn, now I feel even more stupid. :D I though that git pull would updgrade all necessary things, but now my information is updated. Working great, Thanks!

Now I'll switch finally back to emesene again (even when it's beta), just have to look if there is easy way to import emesene1.x custom smiles (= copying custom smilies folder or something) to emesene 2.x. Anyway thank you for your great work, and your patience to answer also these stupid questions!
