### ISSUE TITLE
Emesene does not seem to be able to connect to the internet

### ISSUE THREAD

**Issue by Dinopaterno22** [emesene/emesene#176]
i had a few problems and was forced to reinstall ubuntu. after i installed emesene, i tried to get online, however, it wasn't able to do it. i thought i had to reboot and i did so, yet it did not work. i don't know what to do, because i can use other internet apps and even empathy (which i don't like), yet the one app i need, doesn't seem to work :S

**Comment by c10ud** [comment]
which emesene, version, library, etc.?

if emesene2 just run ./emesene -vvv and paste the output

**Comment by marianoguerra** [comment]
I think this is "old papyon version" related, if not we would have a lot of tickets like this..

I think you should try to download the latest version of emesene 2 from the instructions in the blog and reopen if it still a problem.
