### ISSUE TITLE
Poor documentation [minor issue]

### ISSUE THREAD

**Issue by cristodcgomez** [emesene/emesene#18]
Hello!, well, I decided start to help in this proyect, and I found that Emesene git needs documentation for "newbies", I think that this is a issue, because people that wants to help in the proyect will have mistakes, and the purpose of this git should be have more developers.
I decided help with the wiki for the moment, because I don't know develop under python very well, and I'll try to add documentation of the structure of the proyect (besides xmind image in mesinyer/doc).
Greetings!

PS: I'm spanish, sorry if i have mistakes in the text.

**Comment by marianoguerra** [comment]
hi, thanks for the help! we really need documentation, so your help is more than welcome, if you can encourage more people to help documenting, that would be awesome.

If you want to ask some things, or want to point out which things should be documented first, just say it, we will try to help.

btw Im from argentina, so spanish here too

a litle tip, it is "project" :)

**Comment by boyska** [comment]
You could find this useful:
http://emesene.org/doc/
You could even add more explicative/complete documentations on class and methods where the current one is not

**Comment by cristodcgomez** [comment]
ok! now i'm busy at the moment (university exams), once i finished it, i'll be active again!
Greetings!

**Comment by Maverick87Shaka** [comment]
Hi to all,
I'm just new on github, and really i don't know anything about programming a software ( i have just a little of confidence with html such php and mysql database )
But I'm here just to give my contribute for translation ( english => italian ) of documentation or software part. 
I'm really new on this kind of contribution, but I hope to give my little contribution!

**Comment by boyska** [comment]
Hi Maverick87Shaka, and thanks for your proposal of help.
If you hava confidence with php, and thus with a bit of programming, you could help greatly.
Read http://wiki.github.com/emesene/emesene/githowto
With this help, you are ready to add code or documentation.
If you like, you could add docstrings to the code.
I wrote this wiki page to help you http://wiki.github.com/emesene/emesene/howtocontribute
Hope you find it useful, Otherwise, just ask ;)

**Comment by marianoguerra** [comment]
I added the high level documentation here http://emesene.org/docs/

it's the result of doing "make html" in docs (you need sphinx)

I did a scp to the server, we could automatize this, but I don't think a lot of people will document that fast to need automation ;)

if you want to collaborate, add documentation in docs.

**Comment by c10ud** [comment]
i guess we can close the issue then, wariano, your pleasure

**Comment by marianoguerra** [comment]
I will close it but please, ask for meaninful documentation, I will try to cover them.

**Comment by boyska** [comment]
Do you think it would be possible to get not-so-good coders to do decent documentation? I think that documenting something is great to better understanding, so it could be good for people not willing to code or learn python, but that know something of programming.
What do you think? Is this too hard?

**Comment by marianoguerra** [comment]
It's easier to review and correct documentation than code, so if they do the main structure and fill with some details I could enhance or correct it.

documenting is a good way to learn how things work.
