### ISSUE TITLE
Preferences does not work after 2 times

### ISSUE THREAD

**Issue by gustavodeandrade** [emesene/emesene#181]
Option - > Preferences . Don't work after open/close 2 times. Necessary reboot.

**Comment by Sbte** [comment]
Confirmed. I had this too, but forgot to report

**Comment by flavioribeiro** [comment]
It seems I fixed this bug adding one line at gui/gtkui/Preferences.py. 

Since it was just one line, i though that make a patch to be applied would be too burocratic. The diff is here http://pastebin.ca/1986710

**Comment by ghost** [comment]
This patch works here!

**Comment by c10ud** [comment]
closing, ty
