### ISSUE TITLE
Nick and  PM lost after reboot

### ISSUE THREAD

**Issue by gustavodeandrade** [emesene/emesene#182]
Nick and  PM always lost after reboot.

**Comment by arielj** [comment]
which backend are you using? msn or e3.msn?

**Comment by c10ud** [comment]
if msn, it's the same issue as "avatar not saved" which means: profile fucked up.

**Comment by ricsipontaz** [comment]
I can confirm this and I use msn backend.

**Comment by c10ud** [comment]
let's use only issue #127
