### ISSUE TITLE
Offline messages and DST?

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#183]
When I received a message at today at 20:04:13, the message said

@ 09-11-10 19:04:13

so probably something went wrong with the recent DST changes?

**Comment by c10ud** [comment]
no idea, i just show what i get with %x %X

if there's something it's either in servers or library

**Comment by c10ud** [comment]
seems like papyon doesn't fix the timezone, a viable workaround could be:

[code]            def utc_to_local(t):
                secs = calendar.timegm(t)
                return time.localtime(secs)
            l_time = utc_to_local(msg.timestamp.timetuple()) #time.struct_time
            print l_time
            d_time = datetime.datetime(time.mktime(l_time))
            template = template.replace('%time%', 
                escape(d_time.strftime('%x %X')))[/code]

**Comment by c10ud** [comment]
this should fix the issue, at least till papyon doesn't fix on its own http://bit.ly/aCz2HO
