### ISSUE TITLE
Music plugin: "Set song cover as avatar" option

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#186]
Music plugin always set song as avatar even if the option is unchecked...

I am with audacious... but i try with others music players (mpd,exaile...) and still happens.

EDIT: Try with Music On Console and the same issue.

**Comment by kirotawa** [comment]
Here in my ubuntu  when I set my musci plugin the main screen of emesene stay gray , no list contacts, nothing is shown.But Dbus continues to show the contacts in and out. I use rhythmbox.

**Comment by ghost** [comment]
Debug:
- Stopping plugin music and starting: http://pastebin.com/9h9dt2S2
- Configurin plugin music: http://pastebin.com/uGexJCwX
- Changing song in Exaile: http://pastebin.com/W865Fsb0

**Comment by Mystro256** [comment]
Same avatar issue with me, using banshee, very annoying, music plugin period seems glitchy

also there should be a button to turn on and off the plugin as well, like in emesene versions prior to emesene 2

**Comment by ghost** [comment]
EDIT:

Pulled with latest commits:

When I start plugin music or configuring it: [23:17:58 INFO extension] extension id None not registered on option provider + TypeError: an integer is required http://pastebin.com/gstuf6gx

When I play a song on exaile: http://pastebin.com/84MXGzFR

In step 2 music plugin set the cover and pm fine but breaks the content roaming ([23:08:55 ERROR papyon.gnet.HTTP] Received error code 400 (Bad Request) from storage.msn.com:443
[23:08:55 WARNING papyon.service] Transport Error :400 [23:08:55 ERROR papyon.gnet.HTTP] Received error code 400 (Bad Request) from storage.msn.com:443) I fix the content roaming changing the pm by hand after this.

So two problems here: i dont want to set cover as avatar and not nice content roaming broken.

**Comment by marianoguerra** [comment]
issues with plugin system and specially with the music plugin should be fixed, open new individual issues if some things don't work

**Comment by ghost** [comment]
Nice!
