### ISSUE TITLE
Logger and timestamps fail

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#189]
as i wrote before the great github fall, there are some issues with timestamps and logger-viewer

since i'm using the adium output, when reading the conversation the timestamp for received messages is using a format i added for conversation's offline messages. and that format also contains an utc-to-localtime conversion since i received utc time from papylib.. i can move the conversion to other places, but still i need to use a different format for OIMs (%x %X because i need date too.) and this must be differenciated from received msgs in the logger viewer. However gui.base.message doesn't have the type property (so in adium i could do: if type is offline message, use %x %X, otherwise, self.timefrmt) so i wouldn't know how to properly fix this

**Comment by arielj** [comment]
gui.base.message has the "status" attribute, can't you use that? if status == offline: an offline message

I know we can have conversations with offline people, but hey, those are offline messages too :P

option 2: can't you just add that "type" property/attribute?
