### ISSUE TITLE
Exception on Logger.py

### ISSUE THREAD

**Issue by ericho** [emesene/emesene#19]
When i start the program i get this exception. 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/erich/programacion/emesene/mesinyer/e3/base/Logger.py", line 719, in run
    self.logger = Logger(self.path)
  File "/home/erich/programacion/emesene/mesinyer/e3/base/Logger.py", line 279, in __init**
    self.connection = sqlite.connect(path)
OperationalError: unable to open database file

i'm using ubuntu 10.04

**Comment by marianoguerra** [comment]
which is the output of the following command?

ls -l ~/.config/emesene2/messenger.hotmail.com/

**Comment by ericho** [comment]
this is the output of the command 
erich@erich-cctuv:~$ ls -l ~/.config/emesene2/messenger.hotmail.com/
total 12
drwxr-xr-x 233 erich erich 12288 2010-05-11 12:49 ecordobam@hotmail.com

i tested this exception in two computer, both with ubuntu 10.04

**Comment by ericho** [comment]
self.path  variable points to  /home/erich/.config/emesene2/messenger.hotmail.com/erich.cordoba@ieee.org/log 
but log is an empty directory.

**Comment by ericho** [comment]
Adding a DB filename to the path on Logger.py something like 

```
    self.connection = sqlite.connect(path + "/base.db")
```

on Logger class solves this issue. I don't know if this is a correct way but it work for me.

**Comment by c10ud** [comment]
can you fork and make this modification?

(also: please use proper os commands since / isn't portable :))

**Comment by c10ud** [comment]
nvm, applied. next time fork and thanks for the fix!
