### ISSUE TITLE
Music plugin doesn't work with exaile

### ISSUE THREAD

**Issue by 4javier** [emesene/emesene#192]
with exaile music plugin doesn't work with this error
18:37:04) pluginmanager:starting plugin "%s"
(18:37:04) extension:extension id None not registered on option provider
I've seen that inside emesene/plugins/music/plugin.py, into the body of extension_register function there's nothing about exaile handler, but I've not been able to solve the problem.

**Comment by c10ud** [comment]
Exaile handler plugged in, closed by 859657229598d47045a720950b4b4e9b062f877c

**Comment by 4javier** [comment]
I had already made that two editing in your commit by myself, but those don't solve the problem. Same error message. Bugreport isn't closed.

**Comment by ghost** [comment]
Dont work with exaile 0.2.14 here. But with 0.3.2 works fine. Can you test it?

**Comment by c10ud** [comment]
if it works with latest version, it's fine for me-- we do not want to support 9999 player versions

**Comment by ghost** [comment]
With latest version works here. Fine for me too. Closing?

**Comment by c10ud** [comment]
fine

**Comment by 4javier** [comment]
I use wxaile 0.3.2.0 and last commit of emesene, and the issue is still present. Please, I opened this bug, wait for my feedback before closing it.

**Comment by c10ud** [comment]
sir dosis up here confirmed it working, what's broken for you?

**Comment by 4javier** [comment]
@cloud
the same that was broken before last commit. Situation is identical to first post in this bugtracking.
@dosis
I'm on arch linux.

**Comment by ghost** [comment]
I am on debian sid/experimental and work fine. Exaile package was upgraded on 15 Oct 2010 on unstable. The only problem i see is the "Set song cover as avatar" option (other issue). Previous package of exaile package here in debian doesnt work for me...

**Comment by c10ud** [comment]
i guess you didn't pulled the new code well if you have the same error as if exaile handler wasn't activated...try getting fresh code

**Comment by ghost** [comment]
- Stopping plugin music and starting: http://pastebin.com/9h9dt2S2
- Configurin plugin music: http://pastebin.com/uGexJCwX
- Changing song in Exaile: http://pastebin.com/W865Fsb0

I will copy this debug on 186 issue.
With Exaile works here.

**Comment by c10ud** [comment]
last error you must fix your Live Profile throuhg the Preference window (Live Messenger tab)

**Comment by ghost** [comment]
But papyon not have your changes applied even https://bugs.freedesktop.org/buglist.cgi?product=papyon I will try anyway...

**Comment by ghost** [comment]
@c10ud the fix in my Live Profile only works with your changes on papyon. No problem for me. I will wait to pull papyon... they are lazy :P

EDIT: I tested it for days... dont know at now... I will test again.

**Comment by 4javier** [comment]
I'm going crazy, now problem changed. I'm able to select exaile form extensions→listening to
but this is the message when I redraw the main screen
[14:00:31 INFO extension] extension id None not registered on option provider
In fact nothing change, I cannot see my song displayed.

**Comment by ghost** [comment]
@4javier: delete config files first... and then try to select listen to: exaile.

**Comment by 4javier** [comment]
nothing's changed

**Comment by ghost** [comment]
If you want test it on Virtualbox or similar... I am on Debian Sid and works. 

extension id None not registered on option provider too here (pastebin)

**Comment by 4javier** [comment]
do you see your playing song in place of your personal message?

**Comment by ghost** [comment]
Yep

**Comment by 4javier** [comment]
last commits (which closed at least 4 bugs in an hour, I think cloud is on cocaine...and I like that if this is the result!!!) did bring back situation in this way
pluginmanager:starting plugin "%s"
(22:14:20) extension:extension id None not registered on option provider
(22:14:21) pluginmanager:configuring plugin "%s"
(22:14:21) extension:extension id None not registered on option provider
(22:14:29) extension:extension id None not registered on option provider
Dosis, for you is the same?

**Comment by ghost** [comment]
Pulled with latest commits:
1. When I start plugin music or configuring it: [23:17:58 INFO extension] extension id None not registered on option provider + TypeError: an integer is required http://pastebin.com/gstuf6gx
2. When I play a song on exaile: http://pastebin.com/84MXGzFR

In step 2 music plugin set the cover and pm fine but breaks the content roaming ([23:08:55 ERROR papyon.gnet.HTTP] Received error code 400 (Bad Request) from storage.msn.com:443
[23:08:55 WARNING papyon.service] Transport Error :400
[23:08:55 ERROR papyon.gnet.HTTP] Received error code 400 (Bad Request) from storage.msn.com:443) I fix the content roaming changing the pm by hand.

**Comment by ghost** [comment]
By the way with other music players (moc, mpd...) debug show the same: extension id None not registered on option provider...

**Comment by 4javier** [comment]
I keep getting different behaviour. Plugin doesn't work at all
enabling:
pluginmanager:starting plugin "%s"
unflagging cover as avatar
 pluginmanager:configuring plugin "%s"
selecting exaile in extension tab and redrawing main window
 extension:extension id None not registered on option provider

**Comment by ghost** [comment]
No idea... here, music plugin is buggy at now with all players that i have tested (exaile, mpd, moc, audacious...) but about your issue... I can say that work with exaile (latest version on debian system)
