### ISSUE TITLE
Remove All Avatars

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#193]
The remove all avatar button just opens a frozen confirmation window. Can't click on yes or no. Once Avatar Chooser window is closed, the confirmation window unfreezes but yes action does not remove avatars.

**Comment by c10ud** [comment]
Fix unresponsive yes/no dialogs. Closed by 13460013e8aa743bd57cbd3917a277d50172b992

From now on, you can&#39;t escape from yes/no dialogs.
