### ISSUE TITLE
Annoyance: Unexpanding of Groups

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#194]
When you have a group expanded and you search for someone in the bar, it will unexpand the group if no one is found. I have all my groups expanded to see all my online contacts, and I search for a friend who is offline to send him an offline message, it will unexpand all the groups and after I erase my search, I have to re-expand all the groups to see them again.

This is a big annoyance for me, as I use the search bar a lot to find people, offline or not.

**Comment by DragaO** [comment]
just to confirm: same thing with me

**Comment by c10ud** [comment]
Restore group status after searching. Closed by 441bbdde334b2a8847aac74e23356f2bfaaaf7f6

**Comment by DragaO** [comment]
thanks c10ud :D

**Comment by Mystro256** [comment]
I'm still having this issue with the latest source :S
