### ISSUE TITLE
Filetransfers need testing

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#197]
i am sure there's some issue, find it and report here with details, please

**Comment by wchancao** [comment]
I could't find issues when sending to and receiving from Windows Live Messenger. Files where transfered without problems. The only detail I could see was the timing...

Time elapsed: 21502347:09??? WTF???
Estimated time left: -243:34??? WTF???

**Comment by gustavodeandrade** [comment]
The transfer speed
 remains low, as in version 1.x?

**Comment by c10ud** [comment]
yes

**Comment by GVisconti84** [comment]
Is there, by any chance, anything that can be done about it?

**Comment by c10ud** [comment]
i am pushing papyon developers to merge an experimental branch which should support it, but first they have to commit a bunch of fixed i asked for one week ago..and judging from the git log they're very quiet

**Comment by wchancao** [comment]
yes, its still slow...

**Comment by c10ud** [comment]
by the way, in case it wasn't clear: it's not speed that needs testing.

**Comment by gustavodeandrade** [comment]
c10ud

Sorry my question here, but if open port in firewall, as in others messengers, speed is don't increase?

**Comment by GVisconti84** [comment]
No, If the patches c10ud was talking about aren't committed, opening ports won't help :(

**Comment by c10ud** [comment]
i am stating this very clear. this issue is NOT about speed or whatsoever fancy feature you might expect. 

this is about bugs in filetransfers like: widget appearing in wrong conversations, filetransfers breaking entire conversations, files disappearing somewhere, etc. 

please test the "real world" stuff that can break the program, speed is not something we can (want to) look after

**Comment by gustavodeandrade** [comment]
You were very clear. I had no attention after the topic title.
For now only the problem presented by ChineseGeek. But I will listen to the terminal from now on.

Returning for Earth... :)

**Comment by c10ud** [comment]
Fix file transfers a bit. Closed by 839acb3895fb9e584917a4253c65318e43673e13
