### ISSUE TITLE
Contacts connected from mobile devices don't appear connected.

### ISSUE THREAD

**Issue by wchancao** [emesene/emesene#198]
The contacts connected from mobile devices don't appear connected on emesene2. I have checked with another IM clients (aMSN, Windows Live Messenger) and they appear connected there.

**Comment by GVisconti84** [comment]
Uhm.... I am able to see people connected through eBuddy for Android, and eBuddy for iPhone

**Comment by c10ud** [comment]
which backend? e3.msn? papyon (msn)?

**Comment by c10ud** [comment]
ping or closing

**Comment by c10ud** [comment]
fixing madness, closing issue -- use papyon backend (msn)
