### ISSUE TITLE
emesene starts with ~20 error messages (Windows 7)

### ISSUE THREAD

**Issue by olof-nord** [emesene/emesene#199]
When starting i get a lot of error saying that files are missing, but after pressing ok on all of these, emesene works.

attaching two logs, one made by running emesene_debug.exe > log.txt:
http://ubuntuone.com/p/Q1B/
and one from copy paste from cmd output:
http://ubuntuone.com/p/Q1A/

**Comment by olof-nord** [comment]
seems like the first link does not work, something adds "%20%20" to the end when clicked - the link works if copy and pasting it.

**Comment by GVisconti84** [comment]
It's probably because gstreamer is missing. This issue could be due to commit 58acb1ad41569000fecb, if so windows installation instructions should be updated

**Comment by olof-nord** [comment]
ok, I tried checking for updates through windows update, and it did not find any.
How to get gstreamer?

**Comment by c10ud** [comment]
emesene-2 only issues here, that's emesene-1, and sorry i don't think there's gstreamer for windows
