### ISSUE TITLE
Appindicator should be used when MessagingMenu cannot...

### ISSUE THREAD

**Issue by sledgehammer999** [emesene/emesene#20]
I have removed the indicator-message package from my machine, because I don't like the Messaging menu. Current head uses the messagingmenu, but if it isn't present(like my machine) nothing is displayed in the tray. Not the old trayicon and not the new trayicon(appindicator).

I tried to detect if messaging menu isn't available, but I failed(still a noob). So I open this bug.

**Comment by c10ud** [comment]
i think they should be one single estension, see http://github.com/emesene/emesene/issues#issue/17

then we can disable some feature if you don't have some indicator available

**Comment by sledgehammer999** [comment]
Ok. I await the merge of the two extensions then.

**Comment by c10ud** [comment]
ok, if you pull from my branch this issue should have been fixed :)

**Comment by sledgehammer999** [comment]
I pulled it locally and it works for me that I don't have the messaging-menu present. Didn't test it though with the messaging-menu present.
Closing the issue.

**Comment by cando** [comment]
i'm working on messaging-menu...atm it works partially...
