### ISSUE TITLE
contacts blocked in group count

### ISSUE THREAD

**Issue by DragaO** [emesene/emesene#200]
for example:
i have an group with only one contact, but, appears something like "MyGroupName (1/3)"

then i exapand the group, and have just one contact here

then i go and check the "show blocked contacts" and appears more two contacts
this group _never_ have more than one contact (i know, a group for a contact is a little weird, but anyway :P)

**Comment by c10ud** [comment]
if they're in that group i guess they belong to it...i can't find any other answer to this

**Comment by c10ud** [comment]
i don't think this is a bug, can you check with amsn please?

**Comment by DragaO** [comment]
did some tests

on amsn 0.98.3 shows only one contact on that group; correct
on emesene 1.6.3 appears 1/1 (one online, one in group); correct
on emesene2, updated a few seconds ago, appears 1/3 (one online, two disconnected); wrong

i checked in "privacy" tab on emesene1 and i realized they are deleted , then, they doesn't (should) belong to any group

i don't know python to confirm, but, i think somewhere "deleted contacts" are being treated as "blocked contacts". just a guess.

can i help with some debug info? (if "yes", how?)

**Comment by GVisconti84** [comment]
Ohhhh I finally understood DragaO's issue! And I confirm it! 
emesene2 shows deleted contacts in the contact list, and the "blocked" status could be because they were "blocked and deleted" (but I'm not sure)

**Comment by c10ud** [comment]
i'll check if there's somekind of property we can check to prevent this contacts from appearing or it's a "normal" thing

**Comment by GVisconti84** [comment]
If it can help: aMSN shows this kind of contact outside of any group, with a different icon (a letter envelope icon If I rembember well)

**Comment by c10ud** [comment]
papylib: do not add to contact list people that don&#39;t belong to it but are still in the address book. Closed by efee2df1d7386b10556235c0831e972d6e30dcc0
