### ISSUE TITLE
Emesene1 and Emesene2 incompatibility

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#201]
Thinking Emesene2 like a whole different program at Emesene1 have some common files and that is wrong:
docs/man/emsene.1 should be renamed as emesene2.1
data/pixmaps/emesene.png should be renamed as emesene2.png
data/pixmaps/emesene.xpm should be renamed as emesene2.xpm
data/share/applications/emesene.desktop should be renamed as data/share/applications/emesene2.desktop

changing that ensure the installation of emesene1.6 and emesene2 packages at same time without conflicts.

Going deeper:
- changing the emesene folder to emesene2
- changing emesene script to emesene2
- changing the following lines on setup.py:

.

```
setup_info = dict(name = 'emesene',
```

to

```
setup_info = dict(name = 'emesene2',
```

.
            ext_package = "emesene",
to
            ext_package = "emesene2",
.
            package_data = {"emesene" : ['themes/conversations/_/_/_/_/_',
to
            package_data = {"emesene2" : ['themes/conversations/_/_/_/_/_',
.
and:

.

```
('share/applications', ['emesene/data/share/applications/emesene.desktop']),
```

to

```
('share/applications', ['emesene/data/share/applications/emesene2.desktop']),
```

.
        ('share/man/man1', ['docs/man/emesene.1'])
to
        ('share/man/man1', ['docs/man/emesene2.1'])

**Comment by marianoguerra** [comment]
all the changes made in c4d07359361a6d2a0bfb, the ones that I didn't made to avoid breakage are renaming the folder to emesene2 and renaming the script to emesene2,

if cloud is ok with this then we start breaking :D

**Comment by EibrielInv** [comment]
:):) great!!! then the packaging process will be easier!

**Comment by c10ud** [comment]
oh, i now read this issue. i do not like this, seriously. i don't want to sound harsh, but if you want to use emesene version 2 (as written in mariano's commit) you mustn't use the old-broken emesene-1. if distro packagers want to hax their distro providing multiple version of a program (= madness) it's up to them, but i think we must be very clear this is what we "support" and want people to use. having both installed and/or used leads to serious confusion..

**Comment by c10ud** [comment]
therefore my opinion is that we should revert the big rename commit and bring emesene back to its real name, without version numbers etc.

**Comment by EibrielInv** [comment]
All depends if you are thinking Emesene2 as a different program than Emesene1.
If is the same but a different version then the renaming process is not necessary.. but I think until Emesene2 don't have all the features of Emesene1, both installations must be allowed, but in this case the renaming is responsibility of the packager.
I think it is a similar process that have Blender with the new 2.5 series.

**Comment by c10ud** [comment]
i reverted the commit because i want to deprecate emesene-1 _soon_. if you want to make separate packages is now up to you, i personally wouldn't allow that, but you have the choice :p

**Comment by EibrielInv** [comment]
Ok if that is the development politic, will be the mine too, but I'll wait a couple of days before make explicitly incompatible the packages renaming it from emesene2 to emesene.

Regards!!!
