### ISSUE TITLE
Bug in tray icon?

### ISSUE THREAD

**Issue by saguar** [emesene/emesene#202]
I'm the only one who's getting a non correct tray icon for emesene 2??

Screenshots:
http://dl.dropbox.com/u/230145/bug_icon1.png

http://dl.dropbox.com/u/230145/bug_icon2.png

**Comment by Sbte** [comment]
This is probably issue #113

This means that it's a bug in your theme, not in emesene2.

**Comment by c10ud** [comment]
use a theme which doesn't bring bugs along with iphone icons
