### ISSUE TITLE
Name, Picture and message not saved at logout

### ISSUE THREAD

**Issue by thedutchrockstar** [emesene/emesene#203]
Everytime I login, I have to reset my Name, Picture and Second Message,
Because my contacts see my email add, Default MSN picture and no second message, when I dont.
I don't imagine it would be a very hard fix... or am I the only one with this problem?

**Comment by GVisconti84** [comment]
Uhm, which backend are you using? papyon(msn)? e3.msn? Could you first try the "fix your profile" button in preferences?

**Comment by thedutchrockstar** [comment]
Oh sorry I simply didnt see that button before =S

Must have been in an update sometime, well it fixed the problem thank you =D
