### ISSUE TITLE
ampercent character code characters followed by a ")" give a smiley

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#204]
for example &) is displayed as &;), where ;) is a smiley.

**Comment by c10ud** [comment]
right, right, not nice indeed...let me take a look

**Comment by c10ud** [comment]
we must exclude matches that start with:
(?<!&quot)(?<!&apos)(?<!&amp)(?<!&gt)(?<!&lt)

i'll ask ademilsonfp if he can take a look

**Comment by c10ud** [comment]
Fix html entities making troubles in the emoticon parser. Thanks to our mighty regexp guy ademilsonfp. Closed by ced7e6a9401aef821a50ba45c1dd690f0396c718
