### ISSUE TITLE
Emesene unusable!

### ISSUE THREAD

**Issue by 4javier** [emesene/emesene#205]
After last commit, if I double click on a contact to start a conversation, the window that shows up is completely empty. Like just a gtk frame decorated by window manager.

**Comment by c10ud** [comment]
error?

**Comment by 4javier** [comment]
Sorry, when I filed the bug I was in hurry. Error found: 

/emesene2/emesene/emesene/gui/gtkui/TextBox.py", line 167
    logger.warning("Could not load spell-check: %s" % e)
the object previously created is named log not logger, changing in 
   log.warning("Could not load spell-check: %s" % e)

seems to solve the issue.
Bye :)

**Comment by c10ud** [comment]
oh, ok sorry for that -- will push to my branch and merge as soon as we handle the rename issue
