### ISSUE TITLE
Order by Names

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#208]
We currently have 'Order by Group' and 'Order by Status'. However, when using both of these options contacts are ultimately sorted by their status. The usability issue is that if I am looking for a certain contact to message, I have to skim the available section, then the idle section, and finally the busy section.

I propose an 'Order by Name' option that will sort contacts focusing only on their contact names. This will allow users to find the contact they want without needing to anticipate the contact's current status.

P.D: If 'Order by Group' is supposed to behave this way, it is not doing so correctly. In my installation, there is no real difference between Order by Group and Order by Status.

**Comment by marianoguerra** [comment]
I think the search tool is for that, having an ordering option to optimize human search doesn't make a lot of sense to me.

the contact list already has a lot of code to handle all the possible combination of options, this option will make the code event more complex (we already have lot of issues opened against the contact list).

when I coded the contact list the way it worked was:

when ordered by status:
- order by status
- then by name

when ordered by grouo:
- order by group
- in each group by status
- in each status by name

if it doesn't work like this now then it's a bug and we should open an issue for that.

cloud?

**Comment by Ancanus** [comment]
I forgot to mention, I only have one group. Given that, both Ordered by Status and Ordered by Group will behave in the same way by design.

Sadly, I do not keep enough contacts to make the search tool viable: at any given time, I do not have more than 20 contacts online. As such, it is more efficient for me to swipe through the names with my mouse wheel than using the search routine (click magnificent glass, switch to keyboard, type contact name and hope they have not changed it, switch to mouse.)

I understand the rationale behind forsaking human search in favor of the search tool given a large amount of contacts. However, in the "Order by Group case": what benefit is there to separate contacts in groups, if the main way of locating them will be by using the Search Tool? Given that by ordering by groups one seeks organization, would it be not more organized to prioritize naming criteria over the volatile status states?

In order to not increase the contact list complexity, I propose re-ordering the criteria of "Order by Group" from ::Group:Status:Name:: to ::Group:Name:Status:: for the reasons described above and to cover the Name-criteria ordering that "Order By Status" does not.

I hope you find my criticism constructive and of neutral tone.

**Comment by c10ud** [comment]
i think this is just a NotImplemented feature -- the current order by group/status feature means it will group:
group: each contact in their respective group
status: connected contacts in online group, everyone else, offline

that said, everything can be done but as you can see from the issue tracker the ContactList is an ugly beast which noone wants to touch.. that's why it receives little love (and we're short on manpower)

about this issue, we should decide if we should keep complex feature requests at this stage too

**Comment by Ancanus** [comment]
It seems to me that the other contact list issues on the tracker (and this one, to a lesser extent) are being blocked by design constraints created by the current contact list implementation.

Would it be a good idea to change the design of the contact list? By design I merely mean the Order By *, Show \* dilemmas. It seems to me that if we re-wrote them with extendibility in mind, we could fix all the issues related in one shot.

Naturally, this is a "complex" (I would call it Low Importance) matter, so you guys (main developers reading this thread) will probably want to prioritize the more vital segments of emesene. However, I would like to hear your input on whether it would be a welcomed addition to re-organize the contact list display criterias. 

If it is, I will proceed to open a new meta-issue which will be used to discuss the requirements for a new contact list display criteria. I took a look at ContactList.py and I believe I could potentially implement this (given that doing so wouldn't break many dependencies.)

**Comment by c10ud** [comment]
if you feel like you can do better and/or add some feature, just fork and if your code doesn't break and it's not an hack it will be likely merged :)

**Comment by c10ud** [comment]
Coding Spree! Closed by 7d0bfb5d776e85206b0b15c6873ffeb1343871e2

See additional FIXME comments in the code for minor caveats
