### ISSUE TITLE
Option to enable notify sound with other (not just online) status too

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#209]
In emesene 1.x there is an option to enable notify sound with other (not online) status too. Any chance to someone coding this?

**Comment by c10ud** [comment]
where is that option?

**Comment by c10ud** [comment]
better: in emesene1 you can choose online and offline, same thing in emesene2...what are you missing?

**Comment by c10ud** [comment]
Fix sounds when contacts get on/offline. Closed by 6fd5bac4a9313d05cdbc4bd5dd44c09312870074

**Comment by rockybalboa** [comment]
Thanks. I think that issue!
