### ISSUE TITLE
papyon submodule won't update

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#213]
As introduced by f09ac0f1807fcaa4cb0255d4bc2363721a3b3816

http://cgit.freedesktop.org/papyon/commit/?id=8067b9cf173251fea4e54c3f8b8e21ff20da3649

doesn't exist.

**Comment by c10ud** [comment]
Revert papyon version to HEAD (sorry, was using some neat hidden branch) Closed by e4e443f567d5020bc57b5015ffb471dcbdaaf56c

**Comment by Sbte** [comment]
http://cgit.freedesktop.org/papyon/commit/?id=e0b0fc353829674da0a90a424918acf043618133

is papyon 0.5.0 instead of 0.5.2, so now emesene doesn't work at all.
