### ISSUE TITLE
Offline, no icon in notification bar

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#214]
When I'm not signed in, the notification area for emesene does not have an icon until I sign in, then which it becomes an icon that representing my status. I'm not sure if this is intentional but it's very annoying because I can't see if emesene is open or not unless I'm signed in; I figure it should probably have the generic emesene icon when not signed in/have been disconnected.

**Comment by c10ud** [comment]
gtk trayicon or appindicator?

**Comment by c10ud** [comment]
operative system?

**Comment by Mystro256** [comment]
Ubuntu 10.10, on Indicator Applet (0.4.6), on GNOME Panel (2.30.2)

Used the latest source (emesene-emesene-8b227ef)

**Comment by Mystro256** [comment]
I think I by accident closed this issue, can you reopen?

**Comment by c10ud** [comment]
fixed
