### ISSUE TITLE
No picture frozen window

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#217]
By accident, I did not select a picture when I was in the Avatar chooser and it came up with "Error!: No picture selected," but the window was sitting there frozen; I couldn't click the close button until I closed the Avatar chooser.

Similar to Issue 193

**Comment by edualberice** [comment]
I had the same problem, but the first time it happened when I clicked "close" it opened a new error dialog box and again and again. I needed to kill the program to stop it.

**Comment by c10ud** [comment]
Modal dialogs. Closed by c8eb4b247e2487d77e46af91f5e6fdaf2b81e3ab
