### ISSUE TITLE
Avatar Manager dialog box problem

### ISSUE THREAD

**Issue by edualberice** [emesene/emesene#218]
I was trying to change my avatar, everything was ok, my new picture was there to be used, but I didn't click the new picture and clicked OK. The error dialog box appeared saying "No picture selected". When I clicked the close button, it opened a new "No picture selected" box, I clicked close again and a new box opened.
Now I tested twice, the box hasn't opened more boxes, but it doesn't close.
I will not try to solve it because I don't know python yet =/

**Comment by c10ud** [comment]
don't open duplicates please

**Comment by c10ud** [comment]
closing
