### ISSUE TITLE
Sending large messages causes message to not be sent

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#219]
For my use case, I pasted the contents of this forum post to a contact: http://ubuntuforums.org/showpost.php?p=8713204&postcount=2
and sent it. It shows no errors on my screen or in the terminal.

However, they never received it. I tried alternating between sending them the pasted message, along with "test" messages and they only received the test message. It seems to me that large messages are not going through.

**Comment by c10ud** [comment]
e3.msn or papyon?

**Comment by Ancanus** [comment]
No idea, I pulled from git using these instructions:
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

How can I check/switch?

**Comment by c10ud** [comment]
Handle uberbig messages in papylib. Closed by 19c55a42d81c1baa44072943c74a45b1aaf879c6
