### ISSUE TITLE
Online contacts are being grouped with offline contacts

### ISSUE THREAD

**Issue by edualberice** [emesene/emesene#221]
Hello people, sorry if I'm wrong creating this new issue. I hope this time I'm right in what I'm doing. I doublechecked before opening this issue =D
Well, I like to be able to see all the contacts I have, online and offline. Because of this I chose in my emesene to show the offline contacts and to group them together in the Offline Group. Cool! But, when a contact goes online he's grouped within the Offline Group and not in the correct group.
I just noticed that the group counter of online contacts is correct, but the new contact is shown in the wrong group.

**Comment by edualberice** [comment]
Just to complement my observations: I just noticed that when a contact goes offline, it stays together with the online contacts of its group.

**Comment by c10ud** [comment]
where did you get your emesene copy? this has been fixed already afaik

**Comment by edualberice** [comment]
Hello! I got my emesene copy following this how-to: http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html
It's been 2 days ago only.

**Comment by c10ud** [comment]
then, update.
