### ISSUE TITLE
Parsing of URL's within Conversation Windows

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#222]
If I type something like "wwwwwwwow!" or "wwwwwwwwwtf!" it gets parsed as an URL.

I suggest changing the recognition pattern of URLS to "www." instead of "www"

**Comment by c10ud** [comment]
right, right

**Comment by c10ud** [comment]
Add the dot to the www url regexp. Closed by 2ac0e337b35ac8a46d3c23e5eb36ac0e24cb5128
