### ISSUE TITLE
"Order by status" does not hide groups

### ISSUE THREAD

**Issue by arekinath** [emesene/emesene#223]
On latest git, when choosing "Order by status" from the Options menu, after a delay, a group appears in the list named "Online" with all online contacts in it. However, other groups (such as "Family", etc) remain in the list and have counts, and do not disappear. I would expect them to disappear and the status groupings to be the only ones in the list.

I had a poke around in emesene/gui/base/ContactList.py, and it seems like the way groups are stored will probably have to be reworked a bit to fix this... not too sure though.

**Comment by c10ud** [comment]
Don&#39;t add user groups when ordering by status. Closed by 24903d7cbea75d6afe121169cdeb8ce5a4125583
