### ISSUE TITLE
XML entities in MSN display name after restart

### ISSUE THREAD

**Issue by arekinath** [emesene/emesene#224]
In latest git, when I enter a character into my display name such as a "less-than" sign, '<', it displays correctly at first, but upon restarting emesene, the name now appears with '&lt;' instead of '<' in it. The name seems to appear correctly to other users after the restart, and if I log in with another client (pidgin, kopete or older emesene builds even) it displays correctly.

If I set a name containing a "less-than" sign in another client (such as Kopete) and then close it and start emesene from git, it also produces the same XML entity behaviour, with '&lt;' appearing in place of the '<' sign.

**Comment by arekinath** [comment]
Github turned my '& l t ;' (remove spaces) into < for all of them. It's meant to be the XML entity for <.

**Comment by c10ud** [comment]
Escape nickname before sending to content roaming. Closed by 6b5192542834531785c23c3cfa1d6a77672e8854

**Comment by arekinath** [comment]
Same symptoms still evident after applying 6b51925 and 016c0cc

**Comment by c10ud** [comment]
i think you could have a bug in a bug -- you could have a broken profile, try fixing it first:
Preferences - Live Messenger and follow the instructions 

p.s. i am using a test account which has a nick beginning with <<< :p

**Comment by c10ud** [comment]
ofcourse you must use "msn" backend when connecting, not "e3.msn"

**Comment by arekinath** [comment]
Ok... sorry to ask the obvious, but how do I get to the MSN backend? I can only see "e3.msn" in the list, both on the startup screen and in the Preferences window. And no "Live Messenger" option in Preferences that I can see at the moment...

**Comment by c10ud** [comment]
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

see the "submodule" part

probably we should disable e3.msn.........

**Comment by arekinath** [comment]
Yes, I followed those instructions exactly, the submodule cloned successfully and I can see files in emesene/e3/papylib/papyon/, but still no "msn" in the list, only "e3.msn". I've also deleted my ~/.config/emesene2 directory and same result. Should this be a separate bug? :P

**Comment by arekinath** [comment]
Ah, I didn't have pyopenssl installed. Now it gives me the "msn" session option correctly. All seems to be good now.

**Comment by c10ud** [comment]
great!
