### ISSUE TITLE
File Transfer Issue Pack

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#225]
Alright, I noticed five anomalies while receiving a file from a contact.

1) A contact sent me a file, but the Receive File box did not open, and there were no indications in the debug window, or in the console.
2) I asked him to re-send the file and tell me as soon as he did. When he did, it took like 7 seconds for the file bar to be displayed. Also I received a message in the console:

<pre><code>
/home/ancanus/Programs/emesene/emesene/gui/gtkui/FileTransferWidget.py:65: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)
</code></pre>

3) Following this, every message that he sends me is repeated twice.
4) Clicking the green checkmark to accept the file transfer does nothing.
5) Clicking the red X to deny the file transfer removes the file box (ok) but causes this error in the console:

<pre><code>
Traceback (most recent call last):
  File "/home/ancanus/Programs/emesene/emesene/gui/gtkui/FileTransferWidget.py", line 250, in show_tooltip
    self.update()
  File "/home/ancanus/Programs/emesene/emesene/gui/gtkui/FileTransferWidget.py", line 258, in update
    bps = self.transfer.get_speed()
  File "/home/ancanus/Programs/emesene/emesene/e3/base/Transfer.py", line 63, in get_speed
    return (self.received_data / self.get_time())
ZeroDivisionError: integer division or modulo by zero
</code></pre>

**Comment by Sbte** [comment]
I also get that last error, but then when clicking the green checkmark for the first time. At least it didn't work.

**Comment by c10ud** [comment]
Filetransfers small update.
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
