### ISSUE TITLE
 ImportError: No module named sqlite3.dbapi2

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#226]
on gentoo system
kernel 2.6.35.8

emesene version 2
error after run ./emesene (source on github)
[code]
KinG-InFeT emesene # ./emesene
Traceback (most recent call last):
  File "./emesene", line 32, in <module>
    import emesene
  File "/root/emesene/emesene/emesene.py", line 22, in <module>
    from e3.common.utils import project_path
  File "/root/emesene/emesene/e3/**init**.py", line 1, in <module>
    from base import *
  File "/root/emesene/emesene/e3/base/**init**.py", line 24, in <module>
    from Worker import Worker
  File "/root/emesene/emesene/e3/base/Worker.py", line 24, in <module>
    import Logger
  File "/root/emesene/emesene/e3/base/Logger.py", line 23, in <module>
    import sqlite3.dbapi2 as sqlite
ImportError: No module named sqlite3.dbapi2[/code]

**Comment by marianoguerra** [comment]
do you compiled python from source? I think you didn't added the flags to compile sqlite builtin.

or you have a really old version of python (which I don't think since you are using gentoo)

check the flags you passed to emerge when building python

anyway, this isn't an emesene bug, you seem to have a broken python build.

**Comment by c10ud** [comment]
indeed

**Comment by KinG-InFeT** [comment]
mmm
Then how should I do?

**Comment by marianoguerra** [comment]
long time since I don't use gentoo but something like

export USE="sqlite"
emerge python

should work

**Comment by c10ud** [comment]
just for the record, this is not the first time gentoo-and-emesene users bring their os-specific issues on the table. maybe i'm just flaming but i'd suggest to choose carefully your distribution

greets
