### ISSUE TITLE
Webcam Support

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#228]
Though its not something to be fixed now, as it's not the highest priority, it is something that must be accounted for eventually.

I would hope that emesene 2.0 or 2.1 will have webcam support when it comes out, along with all, if not most, the functionality that came with emesene 1.6.3

**Comment by c10ud** [comment]
i think i don't need to explain, even if the fancy tags are there

**Comment by Mystro256** [comment]
As long as it's considered, that's all I care about. I'll just stick with emesene 1.6.3 until the support comes for such features
