### ISSUE TITLE
Issue 194 not fixed

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#229]
I may I a problem but on both of my computers, 194 has not been solved for the latest source.
My desktop is Ubuntu 10.10, my laptop is Ubuntu 10.04 LTS

To re-summarize the issue, when I use the search bar to search for a contact, any groups with no matches, which were open/expanded, will be collapsed/unexpanded when search query is erased.

**Comment by c10ud** [comment]
i think you don't have the latest git head

**Comment by marianoguerra** [comment]
please confirm this bug with latest git revision

**Comment by Mystro256** [comment]
I installed emesene 2 using these instructions here: http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html.

I just updated an hour ago using the command:

git pull origin master
git submodule update

Just like the instructions said, but the problem still exists on both computers

**Comment by c10ud** [comment]
you are aware that they're restored soon after the widget is hidden, are you?

**Comment by c10ud** [comment]
my point is, if you think that they should do something like real-time update, that's a feature request more than a bug

**Comment by Mystro256** [comment]
Oh I getcha, I didn't realize that a real-time update wasn't implemented; I misunderstood how it worked, sorry.
Although, I would like a feature request on that, because I see myself and others favouring to keep the widget open for convenience and easy use.

**Comment by c10ud** [comment]
(un)expand groups when searching in contact list also on keypresses. Closed by 9fe6683b01a9a2a4d426049cdeecd6d083dd6fc6
