### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#23]
we need a proper setup.py so we can start i.e. making a PPA with unstable builds from hell and gain moar attention.

**Comment by sledgehammer999** [comment]
I made a setup.py based on the code of emesene 1.6 and by reading online docs. It seems to work for most files, but not entirely. When doing a "python setup.py sdist" the resulting tarball doesn't include all the files I specify in package_data. I really cannot find out why this is happening. Anyway, I've pushed my initial attempt. I hope someone else improves it.

**Comment by c10ud** [comment]
well done! i will pull in emesene/emesene asap so everyone can try it and find what's wrong (if any ;))

**Comment by sledgehammer999** [comment]
Well thanks, but you did most of the work. I don't think I did something, except give you motivation to finish this :p

**Comment by sledgehammer999** [comment]
so do we have an ETA on ppa packages being available?

**Comment by c10ud** [comment]
no, sorry, but i will talk to current emesene1-ppa mantainer to see if he can do something.. the best thing would be an automatized script that pulls from emesene/emesene, updates the papyon git submodule, packages the stuff and then upload to launchpad! :p

**Comment by sledgehammer999** [comment]
OK. If anything happens, please update the issue so I'll take notice.

**Comment by c10ud** [comment]
closing down the issue, since now we have it. in case of bugs, open another :)

**Comment by c10ud** [comment]
whoops
