### ISSUE TITLE
OIM issue

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#230]
I was talking with a friend and I changed my state to offline. After this, my friend sent something to me and this is the screenshoot: http://img808.imageshack.us/i/pantallazo0.png/

Debug: http://pastebin.com/8s6BrxFe

Server Error or papylib/papyon issue?

**Comment by c10ud** [comment]
i don't know for sure, but let's wait for fixes to be merged in papyon first (there's a load of them in queue) anyhow, it's either papyon or server, i (we) just show what i get from the callbacks. i'll close the issue for now
