### ISSUE TITLE
Music plugin and PM

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#233]
Seems to work fine now but when i stop a playlist PM shows: not playing...
... is there a way to recover the "original" PM? (an option for this or similar would be great)

**Comment by tomfool85** [comment]
I have a problem using this plugin,every time the song changes the main emesene's screen freezes till it changes the song in the bar,it takes almost 20 second.

**Comment by ghost** [comment]
O.K. with redraw main screen option (extensions preference) PM back to original.
Anyway, my suggestion is:

When playing any song: Show it in PM.
When not playing: original PM.

Thanks for your work! :D

EDIT: by the way in songretriever.py (line 64): glib.timeout_add_seconds(15, self.check_song)
Why 15 seconds to check songs? (cpu or memory usage?)

**Comment by c10ud** [comment]
15 secs because, powersaving

**Comment by Fabioamd87** [comment]
When playing any song: Show it in PM.
When not playing: original PM.

ps: what player are supported right now? thanks.

**Comment by matiasdelellis** [comment]
Within this request, I would like to make a plugin mrpis2 generic, almost any modern players now have this interface (But even since the Ubuntu Sound menu).

**Comment by rockybalboa** [comment]
Any progress with this issue?

**Comment by c10ud** [comment]
@matiasdelellis i think the current plugin is based on a standard mpris2 implementation

@rockybalboa nope, but it should be fairly easy, it just needs to save the pm somewhere and restore it after

**Comment by rockybalboa** [comment]
I tried it about two weeks ago (cloned it from emesene-supported-plugins) but when I activated the plugin I got an error message. Today I'll give it a try again.

**Comment by yuetenshi** [comment]
Uso Rhythmbox y el plugin no me funciona. Aparece en la lista de plug-ins y esta marcado, pero tampoco puedo acceder a las preferencias. El plugin para el Emesene 1 estaba copado, incluso con el botoncito al lado del status para activar o desactivar...

El NickSaver, aparece en la lista pero ni siquiera lo puedo marcar... Lo cual es muy molesto que el nick y estado se reseteen cada vez que inicio... Lo mismo pasa con la imagen de perfil, que cada vez q inicio sesión tengo q volverla a elegir para que aparezca.

Y me gustaría que actualicen el plugin de Groups IM porque utilizo esos grupos y no puedo distinguir quien habla.

Gracias.

**Comment by arielj** [comment]
yuetenshi, tu problema con el nick, pm y avatar es porque te falta arreglar el perfil online: preferencias > live messenger > cambiá tu avatar online y no vuelvas a usar emesene 1.6.x (rompe el perfil), el plugin nicksaver no funciona

I'll close this, use the plugins repo to report plugins issues and suggestions https://github.com/emesene/emesene-supported-plugins
