### ISSUE TITLE
Contacts both on Allow List and Block list: Not removed.

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#237]
Everytime I start emesene, I get a bunch of these pop up:

<code>
[15:39:45 WARNING papyon.protocol.notification] Contact is on both Allow and Block list; removing from Allow list (xxxxxxxx@hotmail.com)
</code>

It says that it removes them from the Allow list, but this message keeps appearing every time emesene starts, so I assume it is not really removing them from the Allow List.

**Comment by c10ud** [comment]
try blocking-unblocking (btw, your Live Addressbook is fucked up, if you get this kind of messages)

**Comment by c10ud** [comment]
anyway, it's worth opening a bug report here, so it gets fixed upstream: https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by Ancanus** [comment]
Upstream bug report:
https://bugs.freedesktop.org/show_bug.cgi?id=31981

Reply:

<pre>

How things are working:

- You receive the contacts from your address book (web service)
- You receive contacts memberships (Allow, Block, Pending) (another web
service)
- You connect to messenger server and send your contact list with memberships

So the Allow membership is only removed from the final contact list we sent to
the Live Messenger server (that is sent each time you connect) but not from the
Address Book (permanent storage for contacts).

Conclusion: that's a harmless warning and I still prefer not to screw up the
address book.
</pre>
