### ISSUE TITLE
Two Right Click Menus in Conversation Window

### ISSUE THREAD

**Issue by luqmana** [emesene/emesene#238]
In the conversation window, if you have multiple convos open and try to right click in the area which displays the contact's email and personal message it calls up two menus.

You can see it in this screenshot: http://imgur.com/HXHXz.png

**Comment by philss** [comment]
The user configuration named "b_conv_tab_popup" have to be set to false to avoid this bug. Maybe the notebook area have some problem, becouse header and tabs share the same area. Sorry if I said something wrong. I'm new here! =)

**Comment by Sbte** [comment]
It'd probably be easier to remove the b_conv_tab_popup and make a Menu specifically for only the output box (or whatever that popup is supposed to be for). self.popup_enable() enables popups for the whole Notebook. But I'm not sure about the right way to do this.

**Comment by c10ud** [comment]
fixed by zipatei
