### ISSUE TITLE
Sound and notifications preferences are not saved

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#239]
Always that I start emesene2 I must set "Mute sound" and Disable notifications because their state is not saved between sesions.

**Comment by edualberice** [comment]
In this preferences issue, I would like to add my case: I like to have my offline contacts in a separated group. For this, I set "options/show/show offline contacts" and "options/group offline contacts" OK. But when I close the emesene and reopen this configuration must be redone, and sometimes it pisses me off hehehehe.
I believe it's something interesting to be implemented =D

**Comment by Mystro256** [comment]
Hmmm well I don't like how it notifies you when someone goes offline (not entirely sure why that's on by default), so I turn the sound and notification off, but annoyingly enough, sometimes this needs to be reset. Always figured it was because I have it auto-update via git and it reset every time it updated.

**Comment by c10ud** [comment]
i always had all notifications off, are you sure of this bugreport?

**Comment by Mystro256** [comment]
Well I can't verify it; I just know my settings were reset at least once, although I'm not sure if it was the fault of emesene, most likely something else. Although I can say for sure that my settings are saving between sessions.

In my opinion, I think this should probably be closed, the original poster most likely had an issue with his filesystem or whatever, ie the configuration file of emesene was unable to be writen to/saved or something along those lines.

**Comment by c10ud** [comment]
fine, closing for now. reopen if issue persists or pop out again
