### ISSUE TITLE
Tray Icon blinking

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#241]
Pulled with last commits and https://github.com/emesene/emesene/issues/closed#issue/162 is not fixed here.

When i am talking, systray icon is blinking when a message is recived and the only way that i have to stop it is with Hide/show emesene option (on tray icon).

Sorry for my english... i am spanish... :D

**Comment by edualberice** [comment]
I had the same problem

**Comment by c10ud** [comment]
please update&test, will reopen if issue persists

**Comment by ghost** [comment]
sir c10ud: Tested and perfect!

**Comment by ghost** [comment]
Partially fixed:

-When you open a conversation window... seems to work fine. (You start the conversation)

-When your contact open the conversation... bug still present.

**Comment by c10ud** [comment]
this should only happen the 2nd (or later) time the contact open a conversation with you -- which unfortunately make iconify not work too .. not sure why

**Comment by ghost** [comment]
Issue should be reopened

Not sure... but I think that the problem appeared with these commits: https://github.com/emesene/emesene/pull/235 (November 28, 2010)

Can you take a look?

Thanks in advance

**Comment by arielj** [comment]
I can't reproduce this, can anyone else confirm this?

**Comment by c10ud** [comment]
there's been a lot of changes meanwhile, maybe it's just gone (?)

**Comment by c10ud** [comment]
i'll close it -- reopen if issue comes back
