### ISSUE TITLE
Can not load and set nick name of contact (contact alias)

### ISSUE THREAD

**Issue by bdejin** [emesene/emesene#243]
First, for all my contact I have nick name for them, some are set in windows live messenger, some are set in emesene 1.x, I can see them without any problem, but not in emesene 2.

Second, I tried to set contact alias in emesene 2, but nothings happens after I give a name and hit ok button. I tried for both online and offline contact, and I tried to restart emesene, none of these works.

**Comment by jadabreu** [comment]
yes, that functionality isn't working.. i know basic python programming, how can i help to fix that issue?

**Comment by c10ud** [comment]
i think it's not in papylib yet, so it's not implemented

**Comment by c10ud** [comment]
my bad, implemented
