### ISSUE TITLE
Font bold setting not working

### ISSUE THREAD

**Issue by godlike64** [emesene/emesene#244]
Using emesene2 (pull of 2010-11-29), when I set the font to be bold, I can see it bold as I type but do not see it so when I send the message. Tested this with MSN, and I am not sure if the other person sees it as bold.

**Comment by c10ud** [comment]
with adiumtextoutput works, so i guess this must be some textoutput issue..not sure if we (want to) support it

**Comment by godlike64** [comment]
Mariano says he will fix it some day :P so please leave this open. Thanks.

**Comment by c10ud** [comment]
fixed with msn backend
