### ISSUE TITLE
papyon P2P errors

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#245]
Getting 
<code>
[23:19:40 ERROR papyon.msnp2p.session_manager] Session_id == 0
</code>

I read in another issue that these occur due to "multiple points of presence", but these are showing up even though I'm only logging in from my laptop (Session_id == 0 does not seem harmless though). If it's not relevant, then it's a dead code issue?

**Comment by c10ud** [comment]
let's say this is "normal", no need to worry
