### ISSUE TITLE
One windows emesene

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#246]
I love it...

http://www.omgubuntu.co.uk/2010/12/one-window-empathy-boy-would-it-simplify-my-life/

 could be?

**Comment by c10ud** [comment]
http://emesene.pastebin.com/1UiLDWDn

an idea if you or someone else wants to hack on this... should be easy but i have no time

**Comment by c10ud** [comment]
.

**Comment by andreskru** [comment]
Come on!!! Its a nice feature!
