### ISSUE TITLE
Segmentation Fault: DBus Menu

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#247]
<code>

<pre>
(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed

(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed

(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed
Segmentation fault

</pre>

</code>

<code>
[47696.024911] emesene[1687]: segfault at 4c ip 0695d9e9 sp bfac9310 error 4 in libdbusmenu-glib.so.1.0.17[695a000+e000]
</code>

This seems to be #232 all over again, only happening in a different .so file.

Fishing for a trace now....

**Comment by c10ud** [comment]
uhm, do you have a path that can be followed for reproducing 100%?

**Comment by c10ud** [comment]
.
