### ISSUE TITLE
emesene crash suddently

### ISSUE THREAD

**Issue by cristodcgomez** [emesene/emesene#250]
Hi!, when i'm closing a  chat window, and my friend write me again, emesene crashes and close... I'm trying to find a error code, but emesene now works fine (this error happened 5 - 6 times since last update on ubuntu). I'll put the error message later!
EDIT: This is the last code before crashing...

<EndpointData id="{f68f049d-f961-4e44-8dfc-994e6ef0c092}"><Capabilities>2789003580:2550273072</Capabilities></EndpointData></Data>
TypeError: can't convert return value to desired type
Fallo de segmentación

**Comment by c10ud** [comment]
issues cleanup.
