### ISSUE TITLE
Cannot start emesene 2.0 to use MSN

### ISSUE THREAD

**Issue by x6465** [emesene/emesene#252]
When I click on preferences, there is no MSN session, just facebook, gtalk and dummy. Here a error message.

Python 2.6.5 (r265:79063, Jul 14 2010, 11:36:05) 
[GCC 4.4.4 20100630 (Red Hat 4.4.4-10)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import e3.papyon
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named papyon
> > > import e3.papylib
> > > No handlers could be found for logger "papylib.Worker"
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "e3/papylib/**init**.py", line 21, in <module>
> > >     from Session import Session
> > >   File "e3/papylib/Session.py", line 22, in <module>
> > >     from Worker import Worker
> > >   File "e3/papylib/Worker.py", line 63, in <module>
> > >     from PapyEvents import *
> > >   File "e3/papylib/PapyEvents.py", line 23, in <module>
> > >     import papyon.event
> > >   File "/home/sabinom/applications/source/emesene/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
> > >     from client import *
> > >   File "/home/sabinom/applications/source/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
> > >     import papyon.profile as profile
> > > AttributeError: 'module' object has no attribute 'profile'

**Comment by c10ud** [comment]
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

please use the submodule otherwise it won't work

**Comment by x6465** [comment]
I already followed this steps but with no success.

**Comment by c10ud** [comment]
importing manually random modules won't help, you just have to make sure you have either at system level or in emesene/e3/papylib/papyon the entire papyon 0.5.4 tree

**Comment by x6465** [comment]
Problem solved. I need to install python-crypto and pyOpenSSL. Thanks for your help. ;)
