### ISSUE TITLE
File transfer cancelation message box issue

### ISSUE THREAD

**Issue by rccanovas** [emesene/emesene#255]
When you send a file to a contact, if you press the hotkey ESC to close the conversation before or during the transference it will ask you if you really wanna exit and cancel the transference, but it opens many message boxes, not just one, more than 10 message boxes once

**Comment by c10ud** [comment]
i think this is emesene-1 and here we have emesene-2 issues only

**Comment by rccanovas** [comment]
Sorry, I thought emesene-2 was totally based on emesene-1
