### ISSUE TITLE
document plugin how to

### ISSUE THREAD

**Issue by marianoguerra** [emesene/emesene#257]
document how to do a hello world plugin

**Comment by arielj** [comment]
Can we close this?? can we close this?? can we close this??

Is there some way to highlight syntax?

https://github.com/emesene/emesene/wiki/Plugin-How-To

**Comment by marianoguerra** [comment]
On Wed, Jun 8, 2011 at 11:33 PM, arielj
reply@reply.github.com
wrote:

> Can we close this?? can we close this?? can we close this??
> 
> Is there some way to highlight syntax?
> 
> https://github.com/emesene/emesene/wiki/Plugin-How-To

AFAIK, no, you could put them on a gist and link them or put them on a
folder in emesene's repo and linkt ther (docs/examples/plugins/ or
somthing like that)

**Comment by arielj** [comment]
I've found it, github gives us a "`python" sentence before the code and "`" after the code to highlight python code ;)

I'm closing this

EDIT: githubs ates it's own tags :P, check the plugin how to page code as a reference of the code used
