### ISSUE TITLE
"Protocol error"? More like "Authentication Error"!

### ISSUE THREAD

**Issue by sszperling** [emesene/emesene#258]
I cannot login at all. I get a "Protocol error" message. Also, terminal shows this
[(timestamp) WARNING papyon.client] alreay logged out

If I try with HTTP method, I also get "Protocol error", plus:
[(timestamp) WARNING papyon.gnet.HTTP] Recieved response but wasn't waiting for one

Maybe I must change server or port?

Tee-hee, my mistake. I realized I was typing a different password. However, I should point out "Protocol error" is inaccurate.

**Comment by c10ud** [comment]
issues cleanup.
