### ISSUE TITLE
Preference -> Notifications config doesn't work

### ISSUE THREAD

**Issue by RickySu** [emesene/emesene#26]
Notify on contact online / offline config option doesn't work.
I fix it.

diff --git a/mesinyer/e3/common/notification.py b/mesinyer/e3/common/notification.py
index d2b03cc..78e811a 100644
--- a/mesinyer/e3/common/notification.py
+++ b/mesinyer/e3/common/notification.py
@@ -49,11 +49,13 @@ class Notification():
         if not contact:
             return
         if contact.status == status.ONLINE:
-            text = _('is online')
-            self._notify(contact, contact.nick , text)
-           if self.session.config.get_or_set('b_notify_contact_online',True):
-              text = _('is online')
-              self._notify(contact, contact.nick , text)
       if contact.status == status.OFFLINE:
-            text = _('is offline')
-            self._notify(contact, contact.nick , text)
-           if self.session.config.get_or_set('b_notify_contact_offline',True):  
-              text = _('is offline')
- ```
           self._notify(contact, contact.nick , text)
  ```
  
   def _notify(self, contact, title, text):

**Comment by c10ud** [comment]
thanks, i'll apply this patch asap. sure you don't want to make your own branch? :)

**Comment by c10ud** [comment]
applied in my branch
