### ISSUE TITLE
Main window font color

### ISSUE THREAD

**Issue by hit** [emesene/emesene#260]
This should be system's font color to match with window color and be readable, not only hardcoded black.

**Comment by c10ud** [comment]
where exactly is font color hardcoded?

**Comment by c10ud** [comment]
issues cleanup.

**Comment by hit** [comment]
Sorry for not ansfering for a long time, but with dark gtk theme, while all fonts are white, the emesene main window still uses black. This applies only to userlist.

Edit: AND for conversation window too (used Adium before with no problems).
