### ISSUE TITLE
Feature-request: A option for the color of incoming messages - OR - Paint incoming messages in the color the GTK style suggests

### ISSUE THREAD

**Issue by Taxi** [emesene/emesene#262]
The Title says all, i hope.
The reason for that is that I'm using a dark GTK Style and it's hard to read black text on dark-grey background.

P.S. Sorry for my bad english. :)

**Comment by hit** [comment]
dupe #260

**Comment by c10ud** [comment]
implemented https://github.com/emesene/emesene/commit/c08624690810ff13905e622d85fa403c6598a2b9
