### ISSUE TITLE
Feature-request: Save the size of the GTK-Window

### ISSUE THREAD

**Issue by Taxi** [emesene/emesene#263]
I noticed on my netbook that the login/main window is larger than the screen, so I have to resize it.
But it doesn't save the changes after quitting, so I have to resize it after everytime I restart emesene.

**Comment by Sbte** [comment]
It saves the size for me. Are you sure you closed emesene properly? Right mouse button on the tray icon, and then quit.

**Comment by Taxi** [comment]
I closed it exactly the way you told but when I resatart it it's still higher than my screen. Maybe it has a minimum resolution couse I'm in front of a netbook (1024x576)

**Comment by Sbte** [comment]
I have a netbook too and it works for me. I also tried it here on my pc and when I restarted emesene, it was like 1/3 of my screen. My screen is 1050px high, so I guess it should work. I guess no useful terminal output is produced too right?

**Comment by Taxi** [comment]
I tried it again and now I'm sure there is a minimum resolution but only at the login screen!
Bevore I log in I can't resize the window very much (minimum seems to be around 280x580 - which is a bit higher than my netbook screen and don't forget the panel...)

**Comment by Sbte** [comment]
But it saves that size right? Or resizes to that size after you made it smaller on the contact list.

So this is more a request for being able to make the login screen smaller. For example by having an option to disable the login picture or by making the login screen scrollable.

Edit: I think I see an easy way to save 24px at least, so I'll look into that tomorrow.

**Comment by Taxi** [comment]
> But it saves that size right?
> Yes.
> 
> So this is more a request for being able to make the login screen smaller.
> True, I wished I noticed that earlier :)
> 
> or by making the login screen scrollable.
> ...if it's smaller than the minimum now? That would be nice.
> 
> Edit: I think I see an easy way to save 24px at least, so I'll look into that tomorrow.
> Thanks, but I think you could save more space by minimizing space between the different boxes. To show what I mean I made a screenshot, marking areas which could be smaller red: http://img822.imageshack.us/img822/7244/emesene.png

**Comment by Sbte** [comment]
Ah, that's emesene 1. This bug tracker is for emesene 2. Emesene 2 is also a lot smaller than emesene 1 and will easily fit on your screen (like I said, 1050/3=350),  so I guess this issue can be closed. 

I will still try to get rid of those 24 px though ;)

**Comment by c10ud** [comment]
neat, closing
