### ISSUE TITLE
logger exception

### ISSUE THREAD

**Issue by ivan25** [emesene/emesene#27]
At emesene startup i get this:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/ivan/SVN/emesene2/mesinyer/e3/base/Logger.py", line 720, in run
    self.logger = Logger(self.path)
  File "/home/ivan/SVN/emesene2/mesinyer/e3/base/Logger.py", line 280, in __init**
    self.connection = sqlite.connect(os.path.join(path, "base.db"))
OperationalError: unable to open database file

steps to reproduce: start emesene

**Comment by marianoguerra** [comment]
try updating and trying again, should be fixed

http://github.com/emesene/emesene/issues/issue/19
http://github.com/c10ud/emesene/commit/148119f1fe16277f525549851075f7074e3283b6

**Comment by ivan25** [comment]
i'm using that revision

ps: if this can help... 
ivan@bigwave ~/ $ ls -l ~/.config/emesene2/messenger.hotmail.com/
totale 12
drwxr-xr-x  5 ivan users 4096 16 mag 18.26 asd
drwxr-xr-x  8 ivan users 4096 16 mag 16.06 ###@hotmail.it
drwxr-xr-x 65 ivan users 4096 16 mag 20.20 ###1@hotmail.it
ivan@bigwave ~/ $ ls -l ~/.config/emesene2/dummy.server.com/
totale 12
drwxr-xr-x 5 ivan users 4096 16 mag 17.44 asd
drwxr-xr-x 5 ivan users 4096 16 mag 16.05 ###@hotmail.it
drwxr-xr-x 2 ivan users 4096 19 apr 01.03 ###1@hotmail.it

**Comment by marianoguerra** [comment]
try moving the file "old" to "old.bak" on your account inside ~/.config/emesene2/messenger.hotmail.com/youraccount@server.com/

**Comment by ivan25** [comment]
i have no 'old' file in that folder :S

this is the tree of my emesene2 config directory:  http://pastebin.com/Z4RPMpNh

**Comment by marianoguerra** [comment]
sorry 'log', not old :D

**Comment by marianoguerra** [comment]
I fixed the problem in two accounts doing 

```
mv log log.bak
mkdir log
mv log.bak log/base.db
```

**Comment by ivan25** [comment]
yes, this fixed the problem
