### ISSUE TITLE
Empty Files cause Deb installation errors

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#270]
Please, fill the following files with some comment, cause the 0 lenght files are not installed:

```
/e3/hotmail/__init__.py
/plugin/music/__init__.py
/plugin/ye_old_status_combo/__init__.py
```

Thanks!!

**Comment by c10ud** [comment]
Add useless comments to some **init** file. closed by 139a96f25e2802bbcaba12f03028a8eed52bb484
