### ISSUE TITLE
Emesene doesn't disconect when resume from suspend 

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#271]
When i resume my notebook from a suspend status emesene show the contact list as when it has online, like a photography of that moment. I think that it should disconnect after resume.

**Comment by Mystro256** [comment]
As well, when I use it, if I try to send a message after resuming from suspend, it instantly disconnects, even after 10 minutes from resume, unless I manually reconnect after resume.

This also seems to happen when my modem and/or router and/or wireless card malfunctions and temporally cuts my internet connection. It doesn't seem to disconnect automatically at all, from what I've seen.

**Comment by c10ud** [comment]
need a way to detect disconnection (especially with papyon). not sure how's that handled from i.e. telepathy

**Comment by Mystro256** [comment]
Hmmm well that's a bit of an issue, how did emesene 1 detect disconnect?

I might as well look into it anyway to help out, but I don't have much experience with papyon, so I'm not sure I can be much help though :P

**Comment by c10ud** [comment]
fixed:
https://github.com/emesene/emesene/commit/d36ed0bfb262a7d5515b537655471c9f2b16ac9e

ofcourse, as soon as networkmanager signals the disconnection, and i guess this is the case :D

**Comment by Mystro256** [comment]
Make sense, thanks :)
