### ISSUE TITLE
Emesene close conversation windows when it disconnect

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#272]
Emesene close conversation windows when it disconnect. I think that this behaviour is wrong. When emesene disconnect it must dislable text box and buttons in conversation window, no close it. Thanks.

**Comment by lfottaviano** [comment]
Thats a good and interesting feature, and it would be good to make something like a checkbox to enable/disable this option. I will develop this feature  if someone with autorithy aproves this. Otherwise i'll focalise on things suggested to be of higher priority, to the growth of the project itself.

**Comment by c10ud** [comment]
if you're willing to tackle this issue, i approve.. it shouldn't be too hard since we have a quite-good abstraction of gui-protocol, even if i don't have clear in my mind a path to follow, so you're alone i guess

**Comment by Sbte** [comment]
@lfottaviano, any news on this?

**Comment by Sbte** [comment]
@lfottaviano, are you still willing to do this? This bug is starting to annoy me ;)

**Comment by hit** [comment]
I quess someone may take this one over. Three months for a quite major disfeature is too much.

**Comment by Mystro256** [comment]
I would but I'm not too sure how this would be done with a plugin

**Comment by Sbte** [comment]
I think this deserves to be the default feature, not a plugin. People expect this to work (so do I :P). So I'd say just implement it in emesene itself.

**Comment by Mystro256** [comment]
yeah, I agree; there should be an option in preferences for this and/or perhaps a dialog asking to close all or not to when disconnecting, along an option to remember your choice.

**Comment by Sbte** [comment]
Go implement this first. After that you can start thinking about the 'making it optional' part ;)

**Comment by Mystro256** [comment]
Haha true say, that would make more sense.

I'll probably look into this tomorrow, I'll have to go hunting through the code and docs because I'm sort of shooting blind lol

**Comment by c10ud** [comment]
[21:11] <c10ud> i think you can do it:
[21:11] <c10ud> - don't destroy conversation manager on disconnection
[21:11] <c10ud> - remove all signals
[21:11] <c10ud> - when connecting check for alive conversation manager, and if user != conv_manager user destroy else reuse
[21:12] <c10ud> setting to inactive is a matter of adding a method or two
[21:12] <sbte> i think you can just call reuse_conversation?
[21:12] <c10ud> don't remember actual code though
[21:13] <c10ud> maybe it needs something from session like connecting new signals or whatever

**Comment by c10ud** [comment]
some work towards it, but it excepts...patches welcome

https://github.com/c10ud/emesene/commit/2e9e435a947a14a2b6969c122fa8f6d418934886

**Comment by Sbte** [comment]
https://github.com/Sbte/emesene/commits/keep-conversations-opened

Only thing left to be done is closing the windows when opening a different session I think?

køøl m3n

**Comment by Mystro256** [comment]
Nice work! Works great :)

Although, maybe the text boxes shouldn't be activated until the log in is fully complete, ie soon after the contact list is drawn?

Oh and of course removing that ugly button haha ;P

**Comment by Sbte** [comment]
Mystro, I think as soon as the session is loaded, they work, which is at the moment we enable them. No need to wait for the contactlist.

**Comment by c10ud** [comment]
i think the keep-conversations-opened branch is mature enough to be merged. i'm unsure if we want to do this in time for 2.11.7, maybe we can, in the end we don't break anything else....?

**Comment by Sbte** [comment]
Ok, more fixes done. Everyone test this NAO! if you want this in 2.11.7. MOAR TESTING IS MOAR BETTER!

https://github.com/Sbte/emesene/commits/keep-conversations-opened

**Comment by Mystro256** [comment]
@Sbte
Oh okay, if so, never mind to my comment then

@c10ud
Seems stable enough, and could be merged as is, although I'm gonna do some crazy testing, because I want to see it in 2.11.7 :). I'll report here if I see anything.

**Comment by Sbte** [comment]
Actually there's a bug. Working on a fix right now.

**Comment by Sbte** [comment]
Fixed in my repo. To test it, just uncomment lines 98 to 104 in UserPanel.py and push the button.

And then...

BOOM

**Comment by Mystro256** [comment]
Looks good, seems like you already fixed one of the two issues I found.

My second issue was that it seemed somewhat confusing and crowded with conversations (or at least I would speculate for a test case), if the user logs in as another account after unwanted disconnect.

Since the purpose of this, to my understanding, is not to close conversation window(s) when experiencing a unwanted disconnect (ie not by user's choice thus not causing unwanted discard), wouldn't it make sense to discard the conversations if another session is started with another user/account? I would think that would be a good enough sign the user doesn't care about their convos anymore, thus there is little worry to keep them.

Else wise, can't see anything else that could be fixed or changed.

**Comment by Sbte** [comment]
Mystro, did you actually test the logging in with a different account? For me it closes when I log in with a different account or session.

**Comment by hit** [comment]
Logging in with different MSN account closes all open conversations.

**Comment by Mystro256** [comment]
Really? That's not what I got; all the windows were still open. I tested it on Arch, lemme see if Ubuntu does any different.

**Comment by hit** [comment]
Arch here too and yes they were closed.

**Comment by Sbte** [comment]
Mystro, we check self.session.account.account and self.session.account.service. So it SHOULD work. In an older version it didn't however. Can you check with latest master? I pushed the changes this morning.

**Comment by Mystro256** [comment]
Oh I must have had it at the wrong commit then, I just tested an it works great in Ubuntu.

**Comment by Sbte** [comment]
Ok' I'll close this issue. Please let us know if you find something else, so we can fix it before the release ;)
