### ISSUE TITLE
Feature Request: Ubuntu Integration

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#273]
Just a request: I think it would be very useful if emesene could be integrated right into ubuntu, like empathy, perhaps via an extension/plugin.

Specifically, when I click the email/letter indicator icon thing at the top, emesene appears in that list, along with chat (empathy) but the integration I'm referring to is the status changer next to the power button on the top right (plus anything else that can be thought of). Pidgin has this feature, and I think it would be useful if emesene did too.

**Comment by c10ud** [comment]
issues cleanup.
