### ISSUE TITLE
Client got an error handling addressbook: 3 0

### ISSUE THREAD

**Issue by emartinez** [emesene/emesene#274]
I'm trying to run emesene 2 on Fedora 13 from the source code downloaded from Github, but I get the above error message in the terminal. After this error I wait a couple of minutes but emesene does not log in. The progress bar just keeps going. The whole output:

[esteban@localhost emesene]$ python emesene.py
No handlers could be found for logger "papylib.Worker"
/home/esteban/downloads/internet/emesene-emesene-d30eb84/emesene/gui/gtkui/**init**.py:94: GtkWarning: gdkdrawable-x11.c:952 drawable is not a pixmap or window
  gtk.main()
[15:10:28 WARNING papyon.protocol] Notification unhandled command : GCF 0 5664
    [payload]
/usr/lib64/python2.6/site-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
[15:10:37 ERROR papylib.Events] Client got an error handling addressbook: 3 0
[15:10:37 ERROR papylib.Events] Client got an error handling addressbook: 3 0

However, I don't really know if the above is the correct way of running emesene 2. I've also tried building and installing with setup.py, but I can't find any created binaries. Thanks.

**Comment by c10ud** [comment]
it could be some issue with the servers, or there's that randpool thing i've never seen before....mmm anyway the preferred way to launch emesene-2 is ./emesene script
