### ISSUE TITLE
Actions -> Profile -> Change Profile does nothing

### ISSUE THREAD

**Issue by marianoguerra** [emesene/emesene#28]
what should it do?

before that submenu was for setting nick and personal message in case you hided the Account Panel, not I don't know what it should do and it doesn't work.

**Comment by ivan25** [comment]
that window changes avatar/pm/nick, and i ported it from emesene1.6

avatar and pm are correctly changed (for me, works), only nick doesn't work

to change nick i used: «self.session.set_nick(new_nick)» but it doesn't change the nick while «self.session.set_message(new_pm)» works.

**Comment by marianoguerra** [comment]
it was a bug that was not displaying the dialog.

btw, the dialogs go in gui/gtkui/Dialog.py there shouldn't be gui code in gui/base/*
