### ISSUE TITLE
The limit in get_chats_between in e3.base.Logger works on the wrong side

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#284]
What it's supposed to do:

'''return the last # sent from src to dest or from dest to src ,
        where # is the limit value

but instead it displays the FIRST # sent messages between the given dates. The limit should work backward (so the last messages should be displayed). 

I first thought the database was broken, but this was the cause of me not being able to find some messages :P

**Comment by Sbte** [comment]
To fix this you'd have to do something like

```
 ORDER BY tmstp DESC LIMIT ?;
```

instead of 

```
 ORDER BY tmstp LIMIT ?;
```

This would actually fix the problem, but it would mean that it's sorted in the wrong order. If this was php you could create another query or something, but no clue how to do it properly in python. Maybe it's easier to sort it with python? But wouldn't that make it even slower?

**Comment by c10ud** [comment]
we need mariano here, i don't know about dbs or logger :D
