### ISSUE TITLE
Control + F does nothing of use (+ suggestion)

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#285]
Oddly enough, if you were to press control + F with the the contact window in focus, it brings up a search field with no apparent use or function. I figure this is just a feature that was never developed and was never removed.

On that note, I would suggest the key combination should be set to toggle the contact search instead, ie the keyboard equivalent/alternative to the magnifying glass button on the top right. I think this idea would make the most sense since control + F is always the keyboard shortcut to find things in most programs.

**Comment by marianoguerra** [comment]
ctrl+F does (or at least did) trigger the search contact list feature.

if it doesn't work then someone broke it, because I implemented that feature long time ago :)

**Comment by Sbte** [comment]
This hasn't worked for as long as I'm using emesene 2.

**Comment by Mystro256** [comment]
Ah I see, well I guess it needs to be re-implemented then

**Comment by Mystro256** [comment]
:/ Damn I just hit comment and close by accident
