### ISSUE TITLE
Control + F doesn't work

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#288]
I by accident closed issue 285, this is a re-post

marianoguerra said that Control + F should open the search field for contacts but it seems to be broken; it currently just opens a search field that doesn't nothing of apparent use instead.

**Comment by nenemfromhell** [comment]
Yes, Control + F is only working at the start of the nickname. And colored nicks are accessible with the <i><b>[</b></i>  char and it puts the selection on the first group.

**Comment by c10ud** [comment]
i'm using ctrl+F and it shows up the bar for searching contacts, just type letters and matching contacts will appear. i have a friend whose name is [color]...something and typing "some" shows him up, so what is happening?

**Comment by c10ud** [comment]
i pushed a nicer behaviour in emesene/master, please try and close this issue..it shoudl work as expected. 

NOTE: it shows up searches in EXPANDED groups only. otherwise you'll see the group is unexpanded but it has something in it

**Comment by nenemfromhell** [comment]
Nice!

**Comment by Mystro256** [comment]
Well wouldn't it make more sense to just have the one search function, rather then that magnifying glass and the control + F? Comparing to empathy, control + F has similar function to the magnifying glass, which is very useful for finding contacts who are offline, ie for offline messaging/talking with people appear offline. I'm sure I could enable the option to show offline contacts, but i find this takes away from ascetic value and it's just too many people to look through honestly lol.

I think there should be at least a keyboard shortcut to the magnifying glass button, because I, for one and i'm sure many others, use this function all the time and find it annoying not to have a shortcut via keyboard

**Comment by c10ud** [comment]
i guess you didn't even bother to try emesene, since the ctrl+f did that before, and since today does it better...hence i'm closing this issue

**Comment by Mystro256** [comment]
I did, try it, i was merely suggesting something better, brainstorming in a sense.

**Comment by Sbte** [comment]
It think you ran into the bug that I just fixed. Could you try again with current git and see if this was what you meant?
