### ISSUE TITLE
emesene 2 proxy connection error

### ISSUE THREAD

**Issue by theseas** [emesene/emesene#289]
&nbsp;&nbsp;&nbsp;I download the fresh code from git and I tried to connect throw my proxy but I never made it, I had adjust the options in the option dialog to use http method and to use my proxy's ip and port, when I clicked connect it seems to load but it never connects it just stucks in the loading window. <br />
<br />
 The bash output was:
 <pre><code>Traceback (most recent call last):
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/gui/gtkui/Login.py", line 571, in _on_connect_clicked
    self.do_connect()
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/gui/gtkui/Login.py", line 366, in do_connect
    self.server_host, self.server_port)
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/emesene.py", line 461, in on_login_connect
    proxy, host, port, use_http)
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/Session.py", line 49, in login
    self.__worker = Worker('emesene2', self, proxy, use_http)
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/Worker.py", line 87, in __init__
    self, server, get_proxies(), HTTPPollConnection, version=18)
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/PapyConvert.py", line 82, in get_proxies
    result[type] = papyon.Proxy(url)
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/papyon/papyon/gnet/proxy/proxy_infos.py", line 89, in from_string
    return ProxyInfos(host, port, proxy_type, auth[0], auth[1])
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/papyon/papyon/gnet/proxy/proxy_infos.py", line 56, in **init**
    self.type = type
  File "/home/theseas/Programs/emesene/emesene_repo/emesene/emesene/e3/papylib/papyon/papyon/gnet/proxy/proxy_infos.py", line 101, in __set_type
    assert(type in ('http', 'https', 'socks', 'socks4', 'socks5'))
AssertionError
</code></pre>

I use Ubuntu 10.04 LTS and my Python's version is 2.6.5.

<p align="right">English isn't my native language so if you don't<br/>understand something or you need more info tell me!</p>

**Comment by c10ud** [comment]
currently, i don't know how it's handled, it needs a rework from someone who can use proxies

**Comment by c10ud** [comment]
papyon and xmppy already support it, if someone that has access to a proxy can hack the GUI out of it, it would be gr8

**Comment by ammarabdulsalam** [comment]
Hi, I'm new to python and to this site too :-), I have tried to remove:
    if 'https' not in proxies and \
            'http' in proxies:
        url = proxies['http'].replace("http://", "https://")
        result['https'] = papyon.Proxy(url)
    for type, url in proxies.items():
        if type == 'no': continue
        if type == 'https' and url.startswith('http://'):
            url = url.replace('http://', 'https://', 1)
        result[type] = papyon.Proxy(url)

from emesene/e3/papylib/PapyConvert.py and it worked fine.

Hope it could help.

**Comment by c10ud** [comment]
if we remove that it will return an empty proxy (!) and anyway it won't use the proxy the user is asking to use in preferences!

**Comment by ammarabdulsalam** [comment]
I've tried to debug the code and my proxy type was ftp(don't know why), so I tried to replace the protocol with http and it worked.
        if type == 'ftp' and url.startswith('ftp://'):
            url = url.replace('ftp://', 'https://',

**Comment by c10ud** [comment]
thanks i uploaded this modification.

btw now we need to put in protocol preferences a checkbox with "Try to resolve proxy automatically" and use get_proxies() otherwise sort out what the user set and pass it to papyon

**Comment by masatodaniele** [comment]
I'm not sure whether the above modification is correct, although it works. It looks to me that proxies.items() contains the list of all proxies set in the system, and ftp is one of them (In Ubuntu, the same list appears in the Network proxy setting window). However, because assert(type in ('http', 'https', 'socks', 'socks4', 'socks5')) does not contain ftp, emesene does not proceed with the connection because of the failed assertion. I changed that into assert(type in ('http', 'https', 'ftp', 'socks', 'socks4', 'socks5')) and it works.

**Comment by c10ud** [comment]
yes, but in order to use that function we should present a clear
choice to the user whether he's using system's or emesene's proxy. atm
you can set something in emesene but it's not used because it
automagically falls back to system's default.

2011/3/27 masatodaniele
reply@reply.github.com:
