### ISSUE TITLE
Papyon don't receive files

### ISSUE THREAD

**Issue by cando** [emesene/emesene#29]
I get this papyon exception when i try to receive a file:

[11:47:54 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {5D3E02AB-6190-11D3-BBBB-00C04F795683}

**Comment by c10ud** [comment]
now we're using upstream version of papyon instead of a custom modification of mine, so file transfer isn't there yet. we must tell lfrb to merge soon, he's working on that and msnp18

http://git.collabora.co.uk/?p=user/lfrb/papyon/.git;a=summary

i'll close the issue because it's not ours :P

**Comment by cando** [comment]
fine!
