### ISSUE TITLE
Suggestion Nick/Group Format

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#291]
This is just a suggestion.

Under the "theme tab" in the settings, there's two buttons that say "Clear." I think it would be clearer and make more sense if they said "Reset" or something along those lines. I say this because the first time I read this, I was confused whether it would clear the text boxes or not until I tested them.

As well, is there a guide for the syntax of these fields? Perhaps a help button, which launches a window describing the syntax would help: just an idea.

**Comment by Sbte** [comment]
I think this is a good idea, and it's quite easy to fix this. Maybe when I have time I'll look into it.

Something that probably also has to be looked at:

ContactList.py in both base and gtkui contain similar functions regarding this (like format_nick), but it appears that only the ones in gtkui are used. So this can probably be cleaned up a little.

**Comment by Sbte** [comment]
Should be fixed by 66d52b28537db16971e6a194db3d9a81dba7b3a6

**Comment by Sbte** [comment]
Clean-up also done by fb3f99009a9d7f6fb3973e78bc3059f186d0f026

**Comment by c10ud** [comment]
closed
