### ISSUE TITLE
create a emesene 1 to emesene 2 log exported

### ISSUE THREAD

**Issue by marianoguerra** [emesene/emesene#292]
create a script that loads the logs from emesene 1 sqlite log database and transform it to emesene 2 sqlite log database format

**Comment by c10ud** [comment]
is andrea's work ready and working?

**Comment by astagi** [comment]
No, it's not ready yet :) I have to call it in another way ( not through a button ) and manage multiple conversations logs..

**Comment by c10ud** [comment]
ok

2011/3/26 4ndreaSt4gi
reply@reply.github.com:

**Comment by c10ud** [comment]
status update requested :D

**Comment by astagi** [comment]
What do you mean with status update??? all the status change events??

**Comment by c10ud** [comment]
no i mean: can we close this issue? :D

2011/4/9 4ndreaSt4gi
reply@reply.github.com:

**Comment by Sbte** [comment]
No, he just wants to know if you're done yet :P

**Comment by astagi** [comment]
Fiuuuuuh :D  yaya, I'll close right now...
