### ISSUE TITLE
file transfer speed at 0

### ISSUE THREAD

**Issue by marianoguerra** [emesene/emesene#294]
reported by aqua to my mail:

noticed that when I send a file to my friend there is no speed, but it's 0,00 KiB/s. When I download a file from a contact it shows correctly the speed.

maybe it's better to you to see a picture of it http://upload.centerzone.it/images/50056519502164751566.png

Some info:
emesene 2.0, build of 2011-01-24
python-papyon 0.5.4
OS is Linux Mint Debian Edition x86

**Comment by Sbte** [comment]
Think I found it. accepted in FileTransferHandler is never called, so time_start is never set to the actual start time. What you then get is that get_time gives back a huge number, so the speed is close to 0.

Actually, I think files you send never get a different state other than WAITING, like I said about RECEIVED in #277.

**Comment by c10ud** [comment]
Filetransfers small update.
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
Closed by 103a33c3087b1d98dbacd491de886ea1e577c898
