### ISSUE TITLE
Mail opens in wrong browser

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#296]
Since I installed Google Chrome, the mail has opened in Chrome rather than Firefox, which is my default browser. I should note that when I installed chrome, I set it as default when it asked me but I changed it back.

Furthermore, running "gnome-open http://www.google.ca" opens in firefox, so I know its default for gnome.

**Comment by c10ud** [comment]
change the default browser for html files

**Comment by Mystro256** [comment]
Fixed
