### ISSUE TITLE
avatar are OLD?

### ISSUE THREAD

**Issue by smarliecy** [emesene/emesene#299]
just switched to emesene from msn live but found out that some of my contacts' avatar are very old(weeks to months). both the pic/profile on webpage of msn and msn live have been updated for  long, but not in emesene...

**Comment by Sbte** [comment]
Confirming I guess. Inside the terminal I see a link to the right avatar under the name Url1, but the avatar displayed inside emesene is a different one.

**Comment by c10ud** [comment]
let's talk in #309, even if this is a papyon issue..

**Comment by c10ud** [comment]
whoops, i meant #308
