### ISSUE TITLE
Content roaming doesn't work in papyon

### ISSUE THREAD

**Issue by cando** [emesene/emesene#30]
I get this soap fault when papyon try to get my roaming profile:
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">soap:Bodysoap:Fault<faultcode xmlns:q0="http://schemas.microsoft.com/passport/IDS">q0:BadContextToken</faultcode><faultstring>Authentication failed on a call with a ticket token present</faultstring><faultactor>http://storage.msn.com:82/StorageService/v/schematizedstore.w10.asmx</faultactor><detail><errorcode xmlns="http://www.msn.com/webservices/storage/v1">PassportAuthFail</errorcode><errorstring xmlns="http://www.msn.com/webservices/storage/v1">Passport Authorization Failed</errorstring><RequiredAuthPolicy xmlns="http://schemas.microsoft.com/passport/IDS">MBI</RequiredAuthPolicy><RPSVersion xmlns="http://schemas.microsoft.com/passport/IDS">6.0.5286.0</RPSVersion></detail>/soap:Fault/soap:Body/soap:Envelope

(14:23:14) papyon.service:Unhandled SOAPFault to GetProfile

**Comment by marianoguerra** [comment]
emesene 1.6 has a similar problem

**Comment by cando** [comment]
yes...in emesene 1.6.1 we have the problem of cache key....i'm near to the solution but i've still some problems..i hope i can resolve it quickly...

**Comment by c10ud** [comment]
autosolved

**Comment by cando** [comment]
here still doesn't works...

**Comment by c10ud** [comment]
did you pull from master and updated the papyon git submodule?

**Comment by cando** [comment]
yes...both done...

**Comment by c10ud** [comment]
then i think this is account-specific, i have a test account and it works :|

**Comment by cando** [comment]
mmm...ok

**Comment by cando** [comment]
solved...i was using the "old" system-installed version..

**Comment by c10ud** [comment]
uhm, emesene should prefer the built-in version. if it's not doing that, then we must fix it :P
