### ISSUE TITLE
LIBDBUSMENU-GLIB-CRITICAL

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#301]
After some time that emesene is running halt with this error:

```
(emesene:2546): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed
Violación de segmento
```

**Comment by c10ud** [comment]
until proven differently, i firmly believe this is a bug in the appindicator stuff. see also https://bugs.launchpad.net/unity/+bug/711046

**Comment by c10ud** [comment]
this should have been fixed (see emesene in natty). reopen if problem persists
