### ISSUE TITLE
Search option and Status 

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#302]
After last 4ndreaSt4gis pull, these buttons (on main contact list) are disabled...

Other thing... bug 241 should be reopened https://github.com/emesene/emesene/issues/issue/241

**Comment by Sbte** [comment]
Confirming. Everything on the top of he contact list doesn't work any more (like search, setting your nickname, etc..)

Edit: Regression testing pointed to 

07fa04cf54123a6a030dad62a4ef437a0546a767

**Comment by c10ud** [comment]
fixed
