### ISSUE TITLE
Can not login with papyon session

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#303]
Pulled with latest commits and there is no option to select papyon session... only dummy, facebook and gtalk.

I have papyon inside papylib folder with "git clone git://anongit.freedesktop.org/papyon" and nothing... something is broken :-(

**Comment by astagi** [comment]
Yes, a file in papylib is missed....try to fetch again from emesene/emesene, now it works :) Anyway let me know...

**Comment by ghost** [comment]
I pulled from emesene/emesene and no lucky

**Comment by astagi** [comment]
Uhm...Try to reclone emesene...I had the same problem today, and I noticed that in e3/papylib file PreviewFactory.py missed...I added it and all worked :)

**Comment by ghost** [comment]
Yes, now works again... Thanks

Closing
