### ISSUE TITLE
No MSN session available

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#305]
I have access to the Dummy, GTalk and Facebook sessions, but the MSN session isn't even displayed in the drop-down list.
The papyon submodule is installed though, as well as python-dnspython, openssl and pycrypto.

This is not a duplicate of this bug report, since e3/papylib/PreviewFactory.py file is present: https://github.com/emesene/emesene/issues/closed/#issue/303 (I just git-cloned).
Removing ~/.config/emesene2/ didn't help either.

**Comment by astagi** [comment]
Maybe you don't have one of the modules imported in PreviewFactory.py.. They should be present by default in your system, but in this case doesn't seem so, and this may generate your problem :) Try and let me know :) Imported packages are:

import Image
import hashlib
import tempfile

**Comment by fgoujeon** [comment]
You're right, I do have hashlib and tempfile, but I don't have Image:

```
florian@flobox:~$ python2
Python 2.7.1 (r271:86832, Jan  6 2011, 11:45:30) 
[GCC 4.5.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> import tempfile
>>> import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Image
```

Such an output may have been more helpful. The only output emesene2 produces is the following:

```
florian@flobox:~$ emesene2
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"
```

Anyway, I installed python-imaging and the MSN session is finally available.
Thank you for such a quick answer, Andrea!

**Comment by astagi** [comment]
You're welcome..yes, an import error in modules causes an exception that makes the papy session unusable... keep on debugging emesene 2 ;) 

Regards

**Comment by ghost** [comment]
So... python-imaging is now mandatory, isnt it?

**Comment by astagi** [comment]
Yes, I think that is the best way to manipulate images keeping papylib GUI indipendent ( first solution was made using gtk )... Generally is a good library :)

**Comment by ghost** [comment]
O.K. so... add it to Depends. :)

**Comment by c10ud** [comment]
wait wait wait python-imaging mandatory? no wai

**Comment by c10ud** [comment]
please make it optional with a quick and dirty try...except at least

**Comment by astagi** [comment]
?

**Comment by astagi** [comment]
We need it to see preview during file transfer :) It can't be optinal...If I make a try catch I would exclude who hasn't pil frmo this feature...

**Comment by astagi** [comment]
Another suggestion to manipulate images?? I found only this solution , but requires pil...

**Comment by c10ud** [comment]
we fought for years in order to keep PIL out from the mandatory deps, if pil is not available just don't send(?) preview

**Comment by astagi** [comment]
ok I' don't understand your motivations but I'll make it optional...I need PIL to manipulate the image to send as preview...But who hasn't PIL will be excluded from this feature..Another time, if you know a better solution that not requires further libraries please let me know...
