### ISSUE TITLE
Incorrect default selection of the session drop-down list

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#307]
Follow these steps to reproduce the bug:
- disconnect
- select "dummy" session
- uncheck "remember me"
- connect
- disconnect

Now, the first item of the session drop-down list (i.e. "msn") is selected. However, the actual selected session is still "dummy": when one tries to connect to an MSN session, emesene opens a dummy session.
One has to select another session (say GTalk) then select "msn" back to actually select the MSN session.

**Comment by Sbte** [comment]
This is probably because the service you login with is fetched from the login account, but since you switched remember me off, there is no login account, so the default service is used, which is msn. I'll see if I can fix this tomorrow or so.

I just post this here so I won't forget :P

**Comment by c10ud** [comment]
sbte fixed it
