### ISSUE TITLE
Tab bar not hidden when "tabbed conversations" option is off

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#312]
The tab bar of the conversation window is visible even if the "tabbed conversations" option is disabled.

**Comment by Sbte** [comment]
I think this is so you can still see the name an status of your contact. It would be quite annoying in you couldn't see the status of a contact I guess. I think this is more a feature than a bug. Or am I missing something?

**Comment by fgoujeon** [comment]
Oh, I didn't know it was done on purpose. In this case, yes, it's more a feature request than a bug report.

In the case where there's only one tab per window, the tab bar and the title bar are redundant (except for the status of the contact, as you said). Vertical space is occupied for (almost) nothing, all the more so as the status of the contact could be displayed on the conversation header.
But that's just my humble opinion. Maybe this is a matter of taste.

**Comment by c10ud** [comment]
done on purpose, we can recycle the same interface for tabbed conversations and single window ones
