### ISSUE TITLE
add login tooltips

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#313]
- self.btn_status.set_tooltip_text(_('Status'))
- self.b_preferences.set_tooltip_text(_('Preferences'))

**Comment by zipatei** [comment]
- self.cmb_account.set_tooltip_text(_('Account'))
- self.txt_password.set_tooltip_text(_('Password'))

**Comment by Sbte** [comment]
Since you have your own fork of emesene, you could try to make a pull request yourself with those changes in it. Then you'll also be given credit in the commit log. But I'm happy to do it if you don't want to ;)

**Comment by zipatei** [comment]
I want but don't know how. :(

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/wiki/GitHowTo

Maybe that helps?

**Comment by zipatei** [comment]
I've got this error

andre@Portatil:~$ git clone git@github.com:zipatei/emesene.git emesene
Initialized empty Git repository in /home/andre/emesene/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by Sbte** [comment]
I think you must add a ssh key first to get access from your pc. Go to account setting -> ssh public keys to do that.

**Comment by zipatei** [comment]
I do everything, but I get the time to:

git push origin master

No change in the repository.

**Comment by Sbte** [comment]
And you did fix your ssh key? Otherwise it won't accept anything you push.

**Comment by zipatei** [comment]
No... just http. not enough?

**Comment by Sbte** [comment]
No, you can't push through http.

**Comment by zipatei** [comment]
solved but:

andre@Portatil:~/emesene$ git checkout master
M   emesene/gui/gtkui/Login.py
Already on 'master'
andre@Portatil:~/emesene$ git push origin master
Everything up-to-date

**Comment by Sbte** [comment]
Great. Now you have to commit your changes first:

git commit -a

and enter a description there. When you've done that, you can push it.

**Comment by zipatei** [comment]
I did it again but not assumed.

**Comment by zipatei** [comment]
i did it... 

thanks

**Comment by Sbte** [comment]
Great. Now you can make a pull request so it can go into this upstream tree.

**Comment by c10ud** [comment]
thanks, merged!
