### ISSUE TITLE
"&" becomes "&amp;amp;amp;amp;amp;" in contacts' nicknames

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#314]
The nickname of one of my contacts is "- Joey & Joey associés -".
Emesene 2 displays "- Joey &amp; Joey associés -" or "- Joey &amp;amp;amp;amp;amp; Joey associés -" instead.

I don't know whether the other XML special chars are also displayed that way.

**Comment by Sbte** [comment]
This should be fixed in today's git version. It was broken yesterday only.

**Comment by c10ud** [comment]
indeed
