### ISSUE TITLE
We need to tell the user when sending the message failed

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#317]
I sometimes get messages like this:

[00:07:29 ERROR papylib.Events] Error sending message: 4 1
[00:07:30 ERROR papylib.Events] Error sending message: 4 1
[00:07:30 ERROR papylib.Events] Error sending message: 4 1
[00:07:30 ERROR papylib.Events] Error sending message: 4 1

When I get those errors, the messages are not received by the contact. This can be fixed by closing the tab and opening a new conversation. Messages don't appear in the chat history either. I have no idea where it comes from, and it would be good if there was at least a warning inside the chat window (if it can't be fixed).

The contact I talked to this time (or at least trying to) was using Adium.

**Comment by c10ud** [comment]
it is possible that adium does really bad things with switchboards (bad, bad purple..). however since we have the notification it could be worth providing to the user a notification the message didn't get delivered. still i wonder why papyon doesn't decide to open a new switchboard and send the messages..

**Comment by c10ud** [comment]
on my way to fix this within papyon. Still, we should display some warning to the user directly in the conversation when sending a message fails.

**Comment by arielj** [comment]
does anyone know how to force an error sending a message? :P

I want to inform the user that the message failed, but all my messages arrive safely to my contacts!!!

**Comment by c10ud** [comment]
mmm hijack the send_message method to call the error function instead XD
