### ISSUE TITLE
All conversation windows are highlighted when receiving a new message

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#318]
When several conversation windows are opened (the option "tabbed conversations" must be disabled), all of these windows are highlighted (i.e. their corresponding buttons in the desktop's window list blink) when one of the contacts sends a message, even when the other contacts say nothing.

**Comment by c10ud** [comment]
i pulled arielj's fix in emesene/master. can anyone try it?

**Comment by Sbte** [comment]
Works for me. Also tested without the commit, and then it didn't work. So fixed I guess. Maybe arielj can confirm that "Trying to fix" actually means "Fixes" ;)

**Comment by c10ud** [comment]
fine, closing
