### ISSUE TITLE
Name and Personal message problem still

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#321]
Hi!

First, my emesene (git, submodule...etc) is up-to-dated. But I have got the name&personal message error still. I login and set my name (Rocky), then I logout. But after the second login, my display name is my real first name (Rocko) again and the personal message is empty. The picture is okay.

**Comment by c10ud** [comment]
fix your profile: preferences-live messenger-follow the instructions

**Comment by rockybalboa** [comment]
Now it is okay. But before this try, it isn't works. Thanks.
