### ISSUE TITLE
Nickname at contactlist and in chat window differ

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#323]
Weird stuff. Nickname in contact information is the same as the one in the chat window. This one seems to be the wrong one. The one in the contact list seems to be the right one (according to my contact and to someone else who has him in his list).

**Comment by c10ud** [comment]
mmm maybe they're not using display_name but nick instead?

i don't know why, but seems like nick is wrong and display_name is correct

**Comment by Sbte** [comment]
Well, the conversation title is wrong, and Conversation.py in gui.base does this to set the title:

```
        if contact:
            text = contact.display_name
        else:
            text = self.members[0]
```

So display_name is used there.

**Comment by c10ud** [comment]
mmm gui/gtkui/Conversation.py is using contact.nick in  def update_group_information(self):

i didn't investigate any further but i guess that could be a good match

**Comment by Sbte** [comment]
I suppose that is what replaces the email of the contact if you have a group chat? In that case this DOES contain the right contact name (just tested). So here nick seems to be better than display_name.

**Comment by Sbte** [comment]
Now I think of it. ContactList uses contact.nick only (through the format_nick function I edited a while back). Should display_name be replaced by nick? And why is display_name even there?

**Comment by c10ud** [comment]
mmm recently i changed some of this stuff in contactlist if i remember correctly, because something was wrong with one of them..not sure which one exactly though

**Comment by c10ud** [comment]
interesting: gui/gtkui/Conversation.py has
    def update_tab(self):
        '''update the values of the tab'''
        self.tab_label.set_image(self.icon)
        self.tab_label.set_text(self.text)

```
    if self.show_avatar_in_taskbar:
        self.update_window(self.text, self.his_avatar.filename, self.tab_index)
    else:
        self.update_window(self.text, self.icon, self.tab_index)
```

but i can't find where that damn self.text is from

**Comment by c10ud** [comment]
btw i see 
    def _markup_escape_contact(self, contact):
        '''return contact with escaped markup'''
        return gobject.markup_escape_text(contact.nick), \
            gobject.markup_escape_text(contact.message)

so display_name use should be discouraged

fixed and uploaded

**Comment by Sbte** [comment]
Now I'm onto something:

The contact's display name is apparently the same as the alias if set. Now it appears that the alias is set for EVERY contact (I think to the one the had the first time I logged into emesene 2). This is also why the name in the adiumtextbox still differs even after replacing every occurrence of display_name with nick. Here I mean this one: "name @ 22:14". This appears to be still set to the alias instead of the nick.

**Comment by Sbte** [comment]
set_contact_alias in Dialog.py actually uses a default value, alias, which is different to the alias uses if you SET the alias using exactly that dialog. Setting the alias there actually works everywhere inside emesene but in the places where the weird display name is still used, like in the example above.

**Comment by c10ud** [comment]
i think "alias" has priority over "nick". probably alias was thought as a client-side naming, but i think we can easily remove it (e3/base/Contact.py?) and keep "nick" only

wdyt?

**Comment by Sbte** [comment]
Well, you want to keep the possibility to make an alias for someone right? So then this is not possible? I don't really understand what you mean.

**Comment by c10ud** [comment]
right, my bad then i didn't get the problem you're having
