### ISSUE TITLE
Only connects via gtalk, facebook or dummy.

### ISSUE THREAD

**Issue by tobyjwebb** [emesene/emesene#324]
When main login window comes up, the protocol switch only provides gtalk, facebook and dummy.

I don't know if this has been done on purpose or not (!), but it means I can't connect via the MSN protocol.

I am keen to help fix this, but I don't know where to start looking :S

**Comment by Sbte** [comment]
I guess you don't have papyon. To get it, do

git submodule init

And to update it

git submodule update

**Comment by c10ud** [comment]
^
