### ISSUE TITLE
remember me should remember also protocol

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#33]
when we choose to remember a mail, we should add also the protocol assigned with that mail.

The problem is when a mail is multi-protocol...

I use a gmail account and a hotmail account, everytime I should change protocol...

**Comment by marianoguerra** [comment]
isn't this fixed?

I use my account for msn and gtalk and it seems to work

**Comment by Fabioamd87** [comment]
no, for example i've 2 mail one @gmail and one @hotmail 
I select my hotmail mail and set papyon, then i switch to gmail in login window and set jabber, when i re-switch to hotmail it is set to jabber.

i hope you understand the example

in a few word it remember the last protocol.

**Comment by marianoguerra** [comment]
I get it now, I have the same mail for both protocols, so I misunderstood the explanation.

I will try to fix it when I have some time.

**Comment by Fabioamd87** [comment]
I understand, thanks.

**Comment by marianoguerra** [comment]
should be working on my repo

**Comment by Fabioamd87** [comment]
with the last commit, when i click on preferences, nothing happen..

**Comment by c10ud** [comment]
rm -rf ~/config/emesene2 and don't use bleeding edge unless you know what you're doing

**Comment by Fabioamd87** [comment]
I don't know if it help in testing, but I made your command but nothing change.
in terminal I get

Traceback (most recent call last):
  File "/home/fabio/emesene2/emesene/gui/gtkui/Login.py", line 509, in _on_preferences_selected
    service = self.config.d_user_service[account]
KeyError: 'xxxxxxxxx@gmail.com'

**Comment by Fabioamd87** [comment]
now it remember the protocol (msn) but if you try to connect use xmpp:

An error occurred while looking up _xmpp-client._tcp.messenger.hotmail.com
An error occurred while looking up _xmpp-client._tcp.messenger.hotmail.com
