### ISSUE TITLE
contact messages are retained in memenu when disconnect

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#330]
To reproduce:
1- Receive a new message and don't click indicator
2- Disconnect from emesene2
3- Go to memenu and you'll see the message are still there.

**Comment by c10ud** [comment]
cool, i don't know how messaging menu works, but i commented on your solution on the issue

**Comment by c10ud** [comment]
Closed by 0b4225b842b458e9841fc801ca7ab8693b9a5898. Thanks pepeleproso for the idea
