### ISSUE TITLE
Issue 302 again after marianos branch merge...

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#331]
https://github.com/emesene/emesene/issues/closed#issue/302

Fix: 

https://github.com/emesene/emesene/commit/bd12b4a757212026b3ba52cffb45365ea13ba986

**Comment by c10ud** [comment]
No insensitive buttons aka don&#39;t move calls around without a good reason II - Thanks dosis for pointing out the offending lines. Closed by 93fef3d8f3a55eb94a4c37d6a4923a19affc46fd
