### ISSUE TITLE
Emesene crashes randomly

### ISSUE THREAD

**Issue by eroge** [emesene/emesene#332]
Simple, emesene crahes in any moment, without any reason.

This happens in ubuntu. I didn't test it in any other distribution.

I test emesene 2 at a long time ago in ubuntu 10.04. Later, in ubuntu 10.10, in my desktop PC and in my netbook, this issue is the reason that I don't use emesene 2 constantly, just sometimes, to test it.

(Sorry my english)

**Comment by Sbte** [comment]
Do you get any relevant output when running it from a terminal?

**Comment by eroge** [comment]
/home/eroge/Descargas/emesene-emesene-fd921ae/emesene/gui/gtkui/**init**.py:96: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()

Just that.
