### ISSUE TITLE
Emesene crashes randomly

### ISSUE THREAD

**Issue by eroge** [emesene/emesene#333]
Simple, emesene crahes in any moment, without any reason.

This happens in ubuntu. I didn't test it in any other distribution.

I test emesene 2 at a long time ago in ubuntu 10.04. Later, in ubuntu 10.10, in my desktop PC and in my netbook, this issue is the reason that I don't use emesene 2 constantly, just sometimes, to test it.

This is the terminal output:

/home/eroge/Descargas/emesene-emesene-fd921ae/emesene/gui/gtkui/init.py:96: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed gtk.main()

(Sorry my english)

**Comment by c10ud** [comment]
it crashes without any output other than that?

**Comment by zipatei** [comment]
/home/andre/emesene/emesene/gui/gtkui/**init**.py:101: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()

here too the same warning but not crash

**Comment by eroge** [comment]
c10ud: nop, that's all

**Comment by c10ud** [comment]
i wonder if that was caused by the emesene indicator. now we're using the memenu only, did you get crashes lately?

**Comment by eroge** [comment]
Oh, I download the latest source, now it doesn't crashes!

**Comment by c10ud** [comment]
great and thanks for the prompt response!

**Comment by eroge** [comment]
Oh... It crashes again u.u. When a contact send to me a emoticon

**Comment by c10ud** [comment]
no message in terminal?

so:
ubuntu 10.10
crashes when receving a normal emoticon (or custom?)
default themes etc.?
no console messages?

try running it with ./emesene -vvv and paste the output when crashing

**Comment by eroge** [comment]
Ubuntu 10.10, LXDE at this moment
Crashes when receving a custom emoticon
Default theme

Output of ./emesene -vvv 

16c2c3d15}>\r\n
    Via: MSNSLP/1.0/TLP ;branch={28a5ad1e-1ce7-483b-a78b-3b66be272a40}\r\n
    CSeq: 0\r\n
    Call-ID: {6c6168d8-edd8-4c7d-b561-9d606d378152}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionclosebody\r\n
    Content-Length: 44\r\n
    \r\n
    SessionID: 1417247389\r\n
    SChannelState: 0\r\n
    \r\n
    \x00
[19:16:59 DEBUG papyon.transport] >>> MSG 16 D 254
    P2P-Src: 'erogeschooldays@hotmail.com;{96b2fbb0-81fb-4e3f-ae61-af516c2c3d15}'\r\n
    P2P-Dest: 'pil.-@hotmail.com;{b44b814a-0585-4eb0-a825-dd18afec94b1}'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (524 bytes)]
[19:16:59 INFO papyon.msnp2p.session] Session 1417247389 disposed

Thanks for all!

**Comment by c10ud** [comment]
it just...closes without any further message? what you posted is "normal", i need scary stuff :D

**Comment by c10ud** [comment]
are you sure you have papyon >=0.5.4?

**Comment by eroge** [comment]
Oh... I had 0.5.1!!!!! But now I installed 0.5.4, and emesene doesn't crashes (By the moment, if later it crash, I tell it to you)

Sorry my poor english!

**Comment by astagi** [comment]
Closing
