### ISSUE TITLE
Custom emoticon problem

### ISSUE THREAD

**Issue by wupper** [emesene/emesene#335]
When someone sends a custom emoticon with a ' in them they wont be displayed (i.e :') or g'D).
All other custom emoticons like :/ ;p etc work just fine.

**Comment by arielj** [comment]
I guess we need to scape those ' (replace all ' with \')

as a side note, custom emoticons are not even working with the text output (I can't use the adium output on windows...)

**Comment by c10ud** [comment]
@arielj: text output is really unmantained (so chances it's broken are really high). you need python-webkit if you want to use the adium output, not sure how to do that in windows..

about 's, it mightn't be that easy, we really had a hard time sorting out this stuff, last time i looked into it was 2010 so my memory is a bit rusty :s

**Comment by rolandixor** [comment]
how hard would it be for someone who hasn't coded in python in years to work on the text output?

**Comment by c10ud** [comment]
depends on the task, just try hacking something out and see if it works ;)

2011/3/17 rolandixor
reply@reply.github.com:

**Comment by arielj** [comment]
Check mariano's github, he made adium themes work on windows!
http://emesene-msn.blogspot.com/2011/03/i-will-leave-this-here.html

2011/3/17 c10ud <
reply@reply.github.com>

**Comment by c10ud** [comment]
i'll pull mariano's changes asap so you can use that too!

**Comment by rolandixor** [comment]
Okay I'll take a look at it :D, this should be interesting

**Comment by rolandixor** [comment]
Sorry I took so long - lot of things got in the way :P - glad to see someone else jumped in ^^
