### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#339]
Many this warnings: "TypeError: an integer is required".

Not error or problem, just many warnings in console.

**Comment by c10ud** [comment]
when doing what? that's an error, not a warning though

**Comment by zipatei** [comment]
1. Turn off "sort by name" in main menu
2. Close Emesene.
3. Log in

**Comment by c10ud** [comment]
ok, i'm getting the bug here too!

**Comment by c10ud** [comment]
Hello TypeErrors, again. Closed by b2c8f428ec4708d457d11803922cc812f0a79599
