### ISSUE TITLE
Tray icon preference doesn't work

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#340]
Setting if you want to use the normal Tray Icon or the Indicator in the preferences doesn't work. This seems to be because the tray icon is set before you login, and the tray icon preference is stored in the config of an account (session.config). It should probably be set in the global config file.

**Comment by c10ud** [comment]
need wariano here^

**Comment by c10ud** [comment]
we need to move the config out of user prefs otherwise the trayicon is instanciated before i guess.. we have the userconfig after loggin in right?

**Comment by Sbte** [comment]
Yes, it's loaded upon login.

But there are two settings files. One global and one for the account. Saving it to the global one would fix it, but atm, no extension preferences are stored in the global config file.

Something else that could be done is only instantiate the tray icon after logging in. This would also fix #382 I guess.

Now something else. Other apps seem to be able to switch the tray icon on and off while you're using the program. That should be possible with emesene too right? Or isn't that how the memenu works?

**Comment by c10ud** [comment]
it's possible, but it's ugly -- also, 99% of users won't need to
change the default pref :p
i think a special case for the trayicon could be ok: its preference
saved in global conf. in the end, our systems are already per-user..
#382 needs some ideas, i wouldn't link it to this bug..

2011/4/11 Sbte reply@reply.github.com:

**Comment by c10ud** [comment]
moving this to 2.1 -- in the end every OS will get the trayicon it deserves automagically, so it's not critical. but still if it's choosable, it _should_ do what it's asked to do

**Comment by zipatei** [comment]
Can you create un option to disable trayicon in preferences?

**Comment by Mystro256** [comment]
This seems to be fixed in the latest git and working just fine for me. Unless it's still not working for others, I figure it should be closed now.

**Comment by Sbte** [comment]
Well, the messaging menu entry is still there even if I hide() it. It just seems to become inactive. Oh well, that's probably not something to worry about. Also, I just found that the state has to be changed upon changing the preference (so it doesn't become the icon you have when you're logged out). I'll see what I can do about that. I'll close this issue as soon as that's done, and I have implemented a no tray icon option for zipatei.

**Comment by Sbte** [comment]
@zipatei, done

**Comment by zipatei** [comment]
Thanks Sbte, but.... I didn't see the option to disable the tray icon. Where is it?

**Comment by Sbte** [comment]
Preferences -> Extensions -> tray icon -> No tray icon

**Comment by zipatei** [comment]
Ah... :) Thanks
