### ISSUE TITLE
Personal Information for version 2

### ISSUE THREAD

**Issue by ez1to3** [emesene/emesene#341]
When I log on to emesene, it does not bring my personal information i.e. personal message or Nick. instead there is a blank personal message and my email is in the nick area. This did not happen in emesene 1

**Comment by c10ud** [comment]
this particular error triggers when you have a broken profile (and yes, emesene1 breaks profiles, so you shouldn't use it anymore).

In order to fix your profile just login with emesene2, Preferences - Live Messenger and follow the instructions.

**Comment by c10ud** [comment]
.

**Comment by ez1to3** [comment]
no this does not work. I have tried this sever times. in fact i tried this before I posted this topic. I do not believe that this is the main problem because while my personal information does not load, It is also the settings in the messenger it self which randomly decide not to load. for example 1 out of ever 12 aprx. my personal information will load correctly. and the setting for messenger i.e. when to display the notifications will work consecutively for about a few login's and it will revert to default settings. This get's annoying because for the chat i have to disable the side bar and make the tool bar small every time this occurs. 

overall i just want to say that I know that this is a beta and that problems will occur (I've used beta's before) but If there is a solution currently to this, please let me know. I appreciate your help. :)

**Comment by ez1to3** [comment]
okay so update: The name is working picture is working, after trying the previous mentioned way a couple of times. The settings still are returning to default however.

**Comment by c10ud** [comment]
the defaults returning are a known problem that happens when emesene reconnects automatically, see #322
