### ISSUE TITLE
Papyon Error On OSX

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#344]
I managed to get emesene 2 running on os x, the dummy account works fine
But when i try to create a new msn session i get an error.

I've installed Papyon and Pycrypto, any ideas whats wrong?

**Comment by c10ud** [comment]
try commenting

```
   def __init__(self, client):
    papyon.event.BaseEventInterface.__init__(self, client)
```

in emesene/e3/papylib/PapyEvents.py (lines 257,258)

**Comment by ghost** [comment]
Issue fixed, trashed pref files and it worked
