### ISSUE TITLE
Can I create some user docs? (Can I? Can?)

### ISSUE THREAD

**Issue by rolandixor** [emesene/emesene#345]
Emesene could do with some user documentation, and seeing as I would love to give back to some open source application projects (apart from diving into making my own) - I would like to do it, or help do it :) - is that okay? (I know this is not exactly - a bug report, but... yeah...)

**Comment by marianoguerra** [comment]
yep, that would be cool, do you have some part you would like to document? or are you asking what to do?

I think a getting started guide, a plugin guide and an extension guide will be really helpful if you are looking for ideas.

and while you make the guides you will learn about how to do it yourself ;)

what do you think?

**Comment by rolandixor** [comment]
I would like to document as much as possible, but basically create a getting started guide to begin with.

**Comment by marianoguerra** [comment]
great, do you need something?

we use sphinx for the documentation:

http://sphinx.pocoo.org/

the documenation is on the docs folder on the emesene repository so you should fork the repo and start documenting and do pull requests.

if the format fits we could make parts and publish them in the blog.

tell me what you think.

**Comment by rolandixor** [comment]
Lol, I was thinking more doing something like a simple pdf with screen shots for **users**.

**Comment by marianoguerra** [comment]
shure, whatever you want
