### ISSUE TITLE
Conversation notifications

### ISSUE THREAD

**Issue by yuengdelahoz** [emesene/emesene#346]
I've noticed that when I have several tabs opened, the notifications are not properly poping up. Sometimes, I am talking to two friends or more at the same time and I have to switch between tabs to see if something has been written. This only happens when I am chatting, if the program is minimized I get the proper message alert.

Hope it helps

**Comment by c10ud** [comment]
please try to reproduce, i changed how the notifications work. now it should work as expected, reopen if still present. (in order to test it you'll need last git master)
