### ISSUE TITLE
Error: Conversation tabs has a timeout

### ISSUE THREAD

**Issue by yuengdelahoz** [emesene/emesene#347]
If I leave the chat tabs opened and do not use them for a while, the connection between the parties crashes. For instance, I am chatting with two friends and I got busy on something else so I stop using emesene for a while BUT I leave the two conversation tabs opened (My two friends stop chatting too). When I try to resume the conversations (using the same tabs), the messages fail to be sent, either I see a "message sent failed" or my friends tell me (by phone) that they didn't get any message. It seems the conversation tabs have a timeout. I don't know if this is a general problem in the interface but this happens in the current version and the in-development one (version 2).

Hope it helps.

**Comment by c10ud** [comment]
we are probably using papyon the wrong way, or, papyon is behaving
strangely.. probably sending a conversation.leave() after being idle
for a while could fix the issue

2011/3/17 yueng
reply@reply.github.com:

**Comment by yuengdelahoz** [comment]
Hi

You're stating this posible solution as a personal thought or a possible 
way FOR ME to solve it. I don't have the expertise to do this.

## Best regards,

_Yueng De La Hoz_
Telecom Consultant
Email: yuengdelahoz@hotmail.com mailto:yuengdelahoz@hotmail.com
IM: yuengdelahoz@hotmail.com mailto:yuengdelahoz@hotmail.com
Phone 1 : 57 300 7555091
Phone 2 : 57 5 3627166

**Comment by c10ud** [comment]
i'll try to hack something in the next days

**Comment by c10ud** [comment]
see https://bugs.freedesktop.org/show_bug.cgi?id=35703
i hope to get it reviewed and merged soon with papyon!

**Comment by yuengdelahoz** [comment]
```
THanks.
  Best regards,

  ---------------------------------------------------

    Yueng De La Hoz

    Telecom Consultant

    Email: yuengdelahoz@hotmail.com

    IM: yuengdelahoz@hotmail.com

    Phone 1 : 57 300 7555091

    Phone 2 : 57 5 3627166



On 03/27/2011 09:13 AM, c10ud wrote:

  see https://bugs.freedesktop.org/show_bug.cgi?id=35703
```

i hope to get it reviewed and merged soon with papyon!

**Comment by c10ud** [comment]
fix landed upstream, update submodule!

**Comment by yuengdelahoz** [comment]
```
how and where do I update the submodule?
  Best regards,

  ---------------------------------------------------

    Yueng De La Hoz

    Telecom Consultant

    Email: yuengdelahoz@hotmail.com

    IM: yuengdelahoz@hotmail.com

    Phone 1 : 57 300 7555091

    Phone 2 : 57 5 3627166



On 04/13/2011 07:46 AM, c10ud wrote:

  fix landed upstream, update submodule!
```

**Comment by c10ud** [comment]
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

2011/4/13 yueng
reply@reply.github.com:
