### ISSUE TITLE
All contact offline

### ISSUE THREAD

**Issue by tomfool85** [emesene/emesene#35]
It's normal that al contacts are offline?

**Comment by c10ud** [comment]
maybe http://bugs.freedesktop.org/show_bug.cgi?id=28278 ?

**Comment by tomfool85** [comment]
But i don't have this bug on emesene 1.6.2

**Comment by tomfool85** [comment]
Suming-up,if i use papyon 0.46 it shows me the real status of my contacts but i does'nt remember me,while using 0.47 it remembers me.

**Comment by c10ud** [comment]
then i think i'll just bump the required version to .4.7 or .4.8 :)

**Comment by tomfool85** [comment]
cool!When??!!

**Comment by c10ud** [comment]
asap! but i'll just tell emesene to refuse using papyon if version is too old :p

**Comment by tomfool85** [comment]
Well!But so i think that u use papyon 0.47,why don't u have the same problem?!

**Comment by c10ud** [comment]
i'm not testing since a while, maybe microsoft changed something.. :(

**Comment by tomfool85** [comment]
Fixed!using papyon 0.48!

**Comment by c10ud** [comment]
bumped requiremetns to 0.4.8 in master
