### ISSUE TITLE
Strange Contact not mine

### ISSUE THREAD

**Issue by vartanjean** [emesene/emesene#350]
This is one problème :

[img]http://img864.imageshack.us/img864/8366/captureu.png[/img]

**Comment by marianoguerra** [comment]
you selected the dummy session, that is used for testing, you should select msn, gtalk or facebook

**Comment by Sbte** [comment]
You're logged into a dummy session. Please log into an msn session (if that's what you're looking for). You can select it in the login window.

**Comment by c10ud** [comment]
only one contact?

connect choosing "msn" instead of "dummy"

2011/3/19 vartanjean
reply@reply.github.com:
