### ISSUE TITLE
ruta de los emoticones

### ISSUE THREAD

**Issue by abelorian** [emesene/emesene#352]
Hola, tengo una duda. No sé si en emesene2 será igual.
Lo que pasa es que en emesene1.x se guardan los emoticones y se mapea la ruta de los gif pero de forma absoluta y no relativa. Entonces si uso un respaldo de la carpeta ./config/emesene1.0  -por ejemplo - como son rutas absolutas no los reconoce si el usuario es distinto.

Saludos
PD: Sorry por no escribirlo en Inglés.

**Comment by marianoguerra** [comment]
kind of translation:

Hi, I have a doubt I don't know if in emesene 2 would be the same.

in emesene 1.x the emoticons are saved and they are mapped with an absolute path.

then if I backup the config folder since the paths are absolute it doesn't recognize them if the user is different.

**Comment by c10ud** [comment]
$ ls /home/name/.config/emesene2/messenger.hotmail.com/mail@hotmail.com/mail@hotmail.com/emoticons/
249a530fb891a60d4965ca645fa79428fb5469ab  emoticons.info

and

$ cat /home/name/.config/emesene2/messenger.hotmail.com/mail@hotmail.com/mail@hotmail.com/emoticons/emoticons.info 
asd 249a530fb891a60d4965ca645fa79428fb5469ab

no, we don't use abs paths :D

no, we
