### ISSUE TITLE
Sounds on OS X

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#354]
OS X port is almost complete nearly everything works, except sounds. Both sign in sounds, message sounds etc do not play.

Debug output just says: can't play themes/sounds/default/online.wav

What does emesene use to play sounds?

**Comment by c10ud** [comment]
see emesene/e3/common/play_sound.py

   elif os.name == 'mac':
    from AppKit import NSSound
    def play(path):
        """
        play a sound using mac api
        """
        macsound = NSSound.alloc()
        macsound.initWithContentsOfFile_byReference_(path, True)
        macsound.play()

maybe os.name isn't "mac"? or the calls are wrong?

**Comment by ghost** [comment]
os.name is "posix" not "mac"

If you change to "posix" sounds work!

**Comment by c10ud** [comment]
i'll try to change the code a bit so we handle that case (importing
mac stuff in posix systems but non mac-ish would be bad), just a sec..

2011/3/25 joshf
reply@reply.github.com:

**Comment by c10ud** [comment]
please try this change [1]: if you confirm it's working, i'll push it
to emesene/master

[1] - https://github.com/c10ud/emesene/commit/d0bba6b83e16d75e94a484e4f33113972cfa1cb2

2011/3/25 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by ghost** [comment]
It works!

**Comment by c10ud** [comment]
ok, pushing to emesene/master :)

2011/3/25 joshf
reply@reply.github.com:
