### ISSUE TITLE
Emesene steals focus

### ISSUE THREAD

**Issue by khepani** [emesene/emesene#357]
If I am using an application different from emesene, and I receive a message from one of my contacts, the emesene window steals the focus of my application (even when I have the 'unavailable' state). I think It is easy to fix, but i dont know how. Please help

**Comment by c10ud** [comment]
unfortunately, you think wrong. could you provide the window manager
you're currently using along with os version?

2011/3/27 khepani
reply@reply.github.com:

**Comment by c10ud** [comment]
i tried to fix it in git master, please try it

**Comment by khepani** [comment]
Thkns c10ud, 
I have Ubuntu 10.10, I am using GNOME with Compiz enabled, but the same thing happens with Compiz disabled

**Comment by c10ud** [comment]
try updating it should be fixed now

2011/3/27 khepani
reply@reply.github.com:

**Comment by khepani** [comment]
thank you! It works!
