### ISSUE TITLE
Multiple conversations not visible into chat history

### ISSUE THREAD

**Issue by astagi** [emesene/emesene#358]
Hi all,

I noticed that multiple conversations are not visible when I try to see a contact chat history, but only message between me and the other contact.. I think that there's something wrong in the query, we should load other contacts message that join that conversation..

**Comment by arielj** [comment]
I think that the logger is not saving any reference that there was a multiple conversation

maybe we can log the cid of the conversation on the insert_fact_event too and then we can get all the messages that comes from the contact AND all messages whose cid matches any cid from the message of that contact...

I guess that will break current fact table...

other ideas?

**Comment by marianoguerra** [comment]
I made a change today so all messages from a group chat have the same id_time, this is to avoid having a new field.

that is, if you are A, and you are chating with B and C and say

A: 1 5p33k l1k3 a h4ck3r

it will be stored as two messages

A -> B
A -> C

so you can find them when you look for "messages I sent to C" but both have the same time_id (because both are the same message in fact) so you can know they are the same message in a group chat.

maybe we will have to add a boolean is_group_chat so it's easier to get the results back, but for now at least we are registering that they are in group chat.

andrea will look into it and integrate it in the repo.

**Comment by astagi** [comment]
Mariano, I thought this: if A say something, this message is registered as A -> B and A -> C ... That's ok, but if C say something and B say something in the same conversation how can I recognize that are talking in the same chat?? :) I think we should duplicate their message event too or add ( T_T ) another field...

**Comment by astagi** [comment]
A better idea could be add a field called conversation_id to group all the message of the same conversation.. Obviously can't be a primary key, it's like a foreign key, but we don't have a table "conversations" ;) Only for grouping this messages..in this case we should revert the same time_id, but it should easier to catch multiple conversations...

**Comment by astagi** [comment]
Added an id for every conversation... Now it should be easy to group them...See my last commits ;)

**Comment by c10ud** [comment]
if it works and doesn't except, you can close this issue

**Comment by astagi** [comment]
No no, was only an update :) At the moment conversations are well stored, but not right shown in chat history yet.. Workin on ;)

**Comment by c10ud** [comment]
well, for the record:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/riky/msn/emesene2/emesene/e3/base/Logger.py", line 778, in run
    quit = self._process(data)
  File "/home/riky/msn/emesene2/emesene/e3/base/Logger.py", line 798, in _process
    self.logger.add_event(event, status, payload, src, dest, new_time, cid = cid)
  File "/home/riky/msn/emesene2/emesene/e3/base/Logger.py", line 582, in add_event
    id_src_acc, id_dest_acc, status, payload, timestamp, cid)
  File "/home/riky/msn/emesene2/emesene/e3/base/Logger.py", line 481, in insert_fact_event
    id_dest_acc, status, unicode(payload), timestamp, cid))
  File "/home/riky/msn/emesene2/emesene/e3/base/Logger.py", line 553, in execute
    self.cursor.execute(query, args)
OperationalError: table fact_event has no column named cid

:P

**Comment by astagi** [comment]
yes, I'm writing the cleaner script ;)

**Comment by astagi** [comment]
Ready ;) Remains to work on GUI ...

**Comment by c10ud** [comment]
great!
