### ISSUE TITLE
Download avatars on first time seen

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#359]
Don't wait for dp-changed when downloading avatars. Just do it when a contact was not seen online before. This is mainly a problem the first time you login on emesene. Avatars won't get downloaded for anyone unless they login or change their avatar.

**Comment by Sbte** [comment]
Btw, it DOES download avatars from other emesene1/2 contacts and even pidgin contacts I guess. It just doesn't work for about any other contact.

**Comment by c10ud** [comment]
for now i'll close it. we'll see if shit happens in future

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/commit/dab73e5a0beb1deaa9ed460579999c1df9e05578
