### ISSUE TITLE
Avatars that have been used before are not seen as new avatars

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#360]
If a contact has an avatar, sets a different one, and then goes back to the first one, this avatar is not seen as a new one, so the second one will be used (it was the last new one).

Way to test:

Open two instances of emesene with two accounts.
In one account: Set avatar. Set different avatar. Set avatar back to the first avatar.
In other account: Check the avatar. It's the second one, not the third/first.

**Comment by c10ud** [comment]
Fix avatars not being updated if already in cache. Closed by 0d5d1604bf910bbc46fed242bb5dbea99b02a793
