### ISSUE TITLE
Move to group / Copy to group

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#361]
I just realized, when i wanted to move Sbte's test account from "NoGroup" to "emesene" that we don't have yet a "Move to group" and "Copy to group" option in emesene.

Seems like actions in papylib are already implemented, but there's no GUI for calling them! (lol)

(Action.ACTION_MOVE_TO_GROUP, Action.ACTION_REMOVE_FROM_GROUP, etc.)

Please someone do it! Both right-click menu and Actions menu bar, kthxbi

**Comment by ghost** [comment]
i too have this problem.....can´t move or copy contact.

**Comment by Sbte** [comment]
I'll see what I can do.

**Comment by Sbte** [comment]
Ok, this is a lot more complicated than it seems (at least for me it is). I won't spend any more time on this until after my exams, so if anyone else wants to do it, feel free to do so.

**Comment by c10ud** [comment]
implemented gui. we need to sort out the remaining bugs as stated in the commit i made before it can be used

**Comment by c10ud** [comment]
copy -- done
(re)move -- not done, need to find a way to identify the "caller" group

**Comment by c10ud** [comment]
remove - done

now only move is remaining.

protip: add helper function to contactlist.py (gtk) that goes from the get_contact() up to the first group found, that's the src group. the dst group is already done.

**Comment by c10ud** [comment]
almost done..

**Comment by c10ud** [comment]
bang, done

**Comment by Sbte** [comment]
Move to group doesn't work for me. 

Also, if removed from all groups, no group should be refreshed.

And if you move from no group, you get

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/sven/emesene-dev/emesene/e3/papylib/Worker.py", line 131, in run
    self._process_action(action)
  File "/home/sven/emesene-dev/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/sven/emesene-dev/emesene/e3/papylib/Worker.py", line 892, in _handle_action_move_to_group
    if group.id == self.session.groups[src_gid].identifier:
KeyError: '0'
```

Reopening, because it's not 'really' done yet.

**Comment by c10ud** [comment]
ah, corner cases. i didn't have contacts in NoGroup group. are you
using the right click menu right?

is "doesn't work" limited to the two cases you just wrote?

reminder for me: if src_gid is 0 i guess i just need to copy the
contact instead of moving.
as for the refresh of nogroup.. i'll see what i can do, i need to see
the code :(

2011/4/13 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
Oh, it does seem to work now. Maybe it just doesn't work after the move from no group failed. Testing...

Yes, that seems to be it indeed.

**Comment by c10ud** [comment]
ddddddddone
