### ISSUE TITLE
Webkit, custom emoticons, Windows

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#362]
An update, I can use webkit now and avatars and my custom emoticons are shown!

I'm not sure why I still can not view my contact's custom emoticons, the paths are right and the html code is right, but there's no image :P

I have 2 problems besides that:
1- If I use a big image to create a custom emoticon, the emoticon is created with the fullsize image and webkit loads it at it's original size (ie: 640x480px)
As a fix for this we can just set a fixed "width" or "height" on the img style attribute and is resized... but...

1b- If I set a fixed width/height for emoticons with a style attribute, when I click the emoticon it's replaces with the original text, and if I click the original text again, the emoticon is displayed, again, on it's original size!!

2- At least on my pc, all image paths must be something like this to work: file://localhost/c:/etc...". I guess it's needed because my emesene2 folder is on drive D and my config folder is on drive C, if I don't set that "localhost/C:" string, it assumes everything's on D: and never find the images.

Does that "file://localhost/" thing work on linux too? if so we can just use localhost always and forget about that ;)

I've pushed some changes, can anybody test my changes on linux? Just send a custom emoticon and tellme if it's shown or not.

**Comment by c10ud** [comment]
1. yes, that's an unfeature (resizing gifs non supported)
   1b. webkit bug (?)
2. i'll try it.. but i guess keeping it as a windows only is safer, we
   don't know how mac/bsd/etc. would behave..

p.s. i've seen you have quite a mess in there (commits). If you could
reset HEAD^ a bit and give me a single commit against
emesene/master...

2011/3/29 arielj
reply@reply.github.com:

**Comment by c10ud** [comment]
btw, i prefer having the nt-only modification as a single commit, let me know

**Comment by arielj** [comment]
I've made reverts and pulled again and it's looking worst now :P...

should I make a new fork? I don't know how to fix it, what commands should I run? I just want to keep my last commit and remove the others

about 1, i'm not using a gif, i'm using a jpeg image, is that also not supported?

**Comment by c10ud** [comment]
ouch ouch ouch.. anyway: i see you just edited two files in the end:
emesene/gui/base/AdiumTheme.py
emesene/gui/base/MarkupParser.py

save these files somewhere, then do git reset HEAD^ (yes ^ included)
until you get the "I like the two guys just too much, i want them in
the default theme :(" commit. (this will kill one commit at the time)
once you reached this commit, just do git reset --hard which will
clear your uncommited changes.
Then, git pull emesene master to get back in sync with emesene/master
then overwrite the two files you edited and commit the result (note
that since your local repo will be different from your remote, you'll
have to push using the -f switch in order to force the overwrite
remotely)

2011/3/30 arielj
reply@reply.github.com:

**Comment by arielj** [comment]
done! thanks so much

I was missing the "git push -f" thing, I was just pushing, git hub complained about some "fast-forward" change and made my retrieve everything again from the server and then applied my changes, that's why I was getting the old commits again, check it now :D

I'd still like a confirmation that it doesn't break it for other users with windows, if there's another windows developer/tester, try this and tell me if it works!

**Comment by c10ud** [comment]
applied cleanly, you had to use -f (force) because there wasn't a direct corrispondence anymore between your local and remote branch :D glad to see you solved and improved git skillz!

i'm closing the issue till next windows user problem comes out, thanks
