### ISSUE TITLE
Major image/visual glitch

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#363]
The email icon, status icons (the status chooser button on the main window), and the "no display picture" image doesn't appear in the main window. Excluding the latter, all those images are replaced by the gnome "no icon" image (the black screen with the red circle and a cross through it).

Also on a related note, the users that have no display picture, also give a blank window rather than a chat window when I click on them. I thought it was coincidence but appears not after may trials.

I'm using the latest git and ubuntu 10.10

**Comment by Sbte** [comment]
I have no clue why this is happening, but if it is, there must be some error in your terminal right?

**Comment by c10ud** [comment]
your copy is broken and missing files, please clone again (or fix it)

2011/3/29 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
I followed the instructions here: http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

It's just in my home folder, so there's no permission issue. I cloned 3 times with the instructions above, once 2 weeks ago, a week ago and just now; the issue still occurs and seems to be consistent. I also have emesene 1.6.3 installed, if that's relevant.

All the images are in ~/emesene/emesene/themes/images/default, so there's nothing missing I guess. Perhaps it's a configuration issue, e.g. the theme is set to something else than default.Maybe an incompatibility with an older git? Or perhaps the configuration corrupted through other means unrelated.

I'll give that a shot but I'm not entirely sure where the config files are, I'll go look for them, shouldn't be too hard.

**Comment by Mystro256** [comment]
Yep that seemed to fix it

**Comment by ez1to3** [comment]
Hi, I have the same problem. I have followed the instruction from http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html and cloned emesene several times. This visual bug still persists. I am currently using Ubuntu 11.04.

**Comment by Mystro256** [comment]
You need to purge the emesene 2 configuration (rm ~/.config/emesene2/config), or at least that's what I did and it fixed it

**Comment by ez1to3** [comment]
yes, you're right. That's what I missed. to bad that I have to remove my settings to fix this. no worries, it take like a min to restore it. :)

Thanks

**Comment by Mystro256** [comment]
No problem
