### ISSUE TITLE
Feature-request: Ubuntu status changer support

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#364]
Ubuntu status changing via the session indicator would be awesome. Pidgin started supporting this a while ago, thus it would only be fit too add this in emesene too if possible.

**Comment by c10ud** [comment]
already implemented by cando in ubuntu11.04. yes, this requires ubuntu
to implement it, so no 10.10

2011/3/29 Mystro256
reply@reply.github.com:

**Comment by c10ud** [comment]
closing the issue https://bugs.launchpad.net/indicator-me/+bug/741163

**Comment by Mystro256** [comment]
Awesome, thanks
