### ISSUE TITLE
emesene crashes while logging-in

### ISSUE THREAD

**Issue by Taxi** [emesene/emesene#366]
Hi,
Today I finally managed to update the unmaintained gentoo ebuild for the git version of emesene2 so that it's working. I was very happy and of course used it to install emesene2.
But now I have a problem: emesene crashes when I try to log me in.
This is the console output (newline added at the moment msn is crashing):
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
/usr/share/emesene/build/lib/emesene/gui/gtkui/**init**.py:119: GtkWarning: Im Modulpfad »clearlooks« konnte keine Themen-Engine gefunden werden,
  gtk.settings_get_default().set_property("gtk-error-bell", False)
/usr/share/emesene/build/lib/emesene/gui/gtkui/**init**.py:119: GtkWarning: Im Modulpfad »mist« konnte keine Themen-Engine gefunden werden,
  gtk.settings_get_default().set_property("gtk-error-bell", False)

/usr/lib/python2.6/site-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
[1]    4646 segmentation fault  emesene

I'm using Python 2.6.6

**Comment by c10ud** [comment]
i'm sorry this is an issue with your python installation, you're on your own with this issue (more precisely, if this is crypto-related, it's a gentoo-specific issue regarding python-papyon, not emesene)

**Comment by marianoguerra** [comment]
check if changing to a default gtk theme fixes it.

**Comment by Taxi** [comment]
@c10ud: Are you sure? Every other python script (including emesene 1.X) is working fine.

@marianoguerra: No it don't.

@All: how can I track down when _exactly_ (which script and which line in that script) the crash happens?

**Comment by c10ud** [comment]
@TAXI: unfortunately, i'm almost sure (can't say 100% but..). at least this is the standard issue with gentooists, 90% of problems they have is their distro causing it (unfortunately i have an history of this stuff..with multiple problems regarding multiple modules from gtk to languages, strange compile-time switches etc.)

**Comment by c10ud** [comment]
since emesene2 for msn hard depeds on papyon, this could be papyon related, so the fact that emesene1 et al. is running doesn't give much info..

**Comment by Taxi** [comment]
c10ud: I'm using gentoo since many years now. I'm only using save CFLAGS and think I can handle my system. Also, my experience is the exact opposite of yours: 90% of bugs are caused of errors in source codes.
That's why I'm reporting bugs almost ever upstream and not to gentoo.

But to better track this it would be usefull to see where _exactly_ the crash happens. Couse of that I asked the question before: How can I find that out?

**Comment by c10ud** [comment]
No idea with python (for the record, the only Segmentation fault found
so far was an ubuntu-specific thing (indicators))

2011/3/30 TAXI reply@reply.github.com:

**Comment by marianoguerra** [comment]
a segmentation fault is caused when someone accesses a segment of memory that isn't valid. This can only be done with languages that handle memory manually (like C)

we can't cause a segmentation fault from python, it's a bug in some library.

the problem with segmentation faults is that the operating system ends the process abruptly so you will never know where it happens other than debugging with something like gdb which is really hard.

you could try running emesene 2 with other session like gtalk or dummy and doing the things that make emesene 2 crash, if it doesnt crash then it's papyon.

if it crash try changing the conversation output extension from webkit to gtk and trying again.

I think that papyon or webkit are responsible, maybe gtk but It's more unlikely

**Comment by Taxi** [comment]
> you could try running emesene 2 with other session like gtalk or dummy and doing the things that make emesene 2 crash, if it doesnt crash then it's papyon.

For that I must know what emesene is doing, so I need a debugger which is showing me what's going on. I tried it with pdb (edited the main python file to include and load it) but as soon as the GUI is there it doesn't show anything new.
The last line I can see is the call to emesene_main() :(

**Comment by Taxi** [comment]
oh, sorry, I should really read before I post. I tried it with dummy and it's not crashing!
So I should have a look at papyon. I don't know what it is and whaat it does right now. ;)

**Comment by Taxi** [comment]
And I tried a wrong password for msn. Also no crash. So it seems to happen after the login verification

**Comment by Taxi** [comment]
Okay, it's definitive not a bug in emesene, sorry for that. I tried the test.py script from papyon and it's crashing, too.

But if anybody can help me by figuring out where exactly it happens, please write here. :)
