### ISSUE TITLE
Offline instead of Invisible, Ubuntu 11.04 + emesene

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#367]
It's a minor glitch, but it's definitely worth noting. I tested emesene on the beta version of Ubuntu 11.04 today and the status changer shows offline instead of invisible. All other statuses seem to work normally though. I did notice that when I clicked on invisible, it switched to offline, instead of invisible.

I figure this may have been done on purpose due to emesene calling the invisible status "offline", but it seems to be a bit of an anti-feature because I'm pretty sure the offline option was put in the ubuntu status menu to allow the user to easily disconnect without opening the main window of the messenger.

Also I'm suggesting this is an issue because it creates inconsistency of the GUI versus other messengers on Ubuntu. It doesn't bother me that much but I can see some users complaining about it being different when 11.04 comes out :(

**Comment by c10ud** [comment]
ok moved online to available and offline to invisible, next round of translation updates you will see it i guess

**Comment by Mystro256** [comment]
thanks

**Comment by Mystro256** [comment]
I'll have to test it when 11.04 comes out, it's too buggy to use right now.
