### ISSUE TITLE
adium textbox text formatting and emoticons

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#37]
- please kill the webkit right-click menu ->DONE
- support font formatting please

**Comment by sledgehammer999** [comment]
My ab7807be9 commit fixes the first element.

**Comment by hit** [comment]
Does clickable link count as formatting?

**Comment by c10ud** [comment]
uhm, i guess we need custom handlers for links otherwise i think the webkit backend will try to open them inside the conversation window, and that would be really bad

**Comment by marianoguerra** [comment]
both implemented, cloud, rebase them to emesene :D
