### ISSUE TITLE
Double click on group list doesn't work

### ISSUE THREAD

**Issue by zephyr91** [emesene/emesene#370]
I just updated my Debian Squeeze to Wheezy, and emesene was updated to 2.0, after that the double click on group list stop working and i thougth that this is a problem cuz i dont want to click on the arrow at the side, i want to click anywhere in the group-name to open it.

So I'm reporting this issue.

Sincerly.

**Comment by Sbte** [comment]
Fixed by Jose Rostagno: 02af438db3ca7643785a305a6325cb5d118027a0

**Comment by zephyr91** [comment]
if i add this lines, it wont open the emesene and in terminal he says this

"
/usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha,base64,random,dispatcher,re
/usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Traceback (most recent call last):
  File "/usr/bin/emesene", line 34, in <module>
    emesene.main()
  File "/usr/share/emesene/emesene/emesene.py", line 701, in main
    main_method(Controller)
  File "/usr/share/emesene/emesene/gui/gtkui/**init**.py", line 40, in gtk_main
    import ContactList
  File "/usr/share/emesene/emesene/gui/gtkui/ContactList.py", line 252
    if self.row_expanded(path):
    ^
IndentationError: unexpected indent
"
