### ISSUE TITLE
emesene won't load on Kubuntu 11.04 beta 1

### ISSUE THREAD

**Issue by medeirosdez** [emesene/emesene#371]
After installing following the instructions on the website, I get the following lines on Terminal. I have never managed to get emesene up and running on Kubuntu 11.04 beta 1, and it is the first app that is giving me problems.
# ./emesene

ERROR: Could not load classifier cascade /usr/share/opencv/haarcascades/haarcascade_frontalface_alt2.xml
ERROR: Could not load classifier cascade /usr/share/opencv/haarcascades/haarcascade_frontalface_alt2.xml
No protocol specified
/usr/lib/pymodules/python2.7/gtk-2.0/gtk/**init**.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
No handlers could be found for logger "gui.gtkui.Indicator"
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/home/usuarios/emesene/emesene/emesene.py", line 705, in main
    main_method(Controller)
  File "/home/usuarios/emesene/emesene/gui/gtkui/__init__.py", line 95, in gtk_main
    setup()
  File "/home/usuarios/emesene/emesene/gui/gtkui/**init**.py", line 120, in setup
    gtk.settings_get_default().set_property("gtk-error-bell", False)
AttributeError: 'NoneType' object has no attribute 'set_property'

**Comment by c10ud** [comment]
first app or first gtk app? do you have the deps? try installing
emesene from the repos so it takes care of all the deps, then you can
use the updated copy from git being sure it's not a dep problem.

2011/4/5 medeirosdez
reply@reply.github.com:

**Comment by medeirosdez** [comment]
I did install current stable version first, before trying the development one. Kubuntu took care of all dependencies and, yet, emesene was not able to load. The updated git version gave me that output when I called it through terminal when I was logged as root. As soon as I logged as normal user, I eventually got it to run successfully, which isn't the case of the stable version.

By the way, I've noticed that it still has a very poor translation to my language, Brazilian Portuguese. I'd love to help translating as many things as my time allows me to. If you have any suggestion on where should I go to help, I'd appretiate it.

Thank you for your reply and support.

**Comment by c10ud** [comment]
i'm updating translations as soon as i can, but iirc pt_br should now
be almost complete

as for the other issues, running emesene as root is bad because your
contacts could break your system. i think i'll prevent emesene from
running as root just like we did for emesene1 (well, emesene1 could
run with a special switch, but still that was bad..)

2011/4/5 medeirosdez
reply@reply.github.com:
