### ISSUE TITLE
Ctrl+tab, ctrl+shift+tab doesnt work...

### ISSUE THREAD

**Issue by zephyr91** [emesene/emesene#372]
Ctrl+tab, ctrl+shift+tab doesnt work... switching between the tabs of the chat window..

is there any code that i need to add into some file ??

sincerly

**Comment by c10ud** [comment]
emesene/gui/gtkui/ConversationManager.py @ lines 39, 40. It should
work but some bug is preventing it from correctly working.

2011/4/5 zephyr91
reply@reply.github.com:

**Comment by zephyr91** [comment]
hummmm, any ideias of what could be ??, and thank you for your answer.

**Comment by c10ud** [comment]
well, if i had it, i would already have it fixed

**Comment by sebastianlacuesta** [comment]
Ctrl+q neither work.

**Comment by c10ud** [comment]
this is offtopic but... you should read this:
http://blogs.gnome.org/otte/2008/03/17/help-ctrl-q-die/

2011/4/6 sebastianlacuesta
reply@reply.github.com:

**Comment by sebastianlacuesta** [comment]
More offtopic: I read it, and I agree with Calvin Walton (see comments):
"
ctrl-w: Close the current document [a conversation tab]
ctrl-q: Quit the application [current emesene app, since I like to have
multiple emesene's open :P]
alt-f4: Close the current window (wm-dependant)
"
Anyways it was just a suggestion. I'm glad to see you answered.
Thanks!

2011/4/6 c10ud <
reply@reply.github.com>

**Comment by c10ud** [comment]
i see your point.. not sure about it though (i don't even use shortcuts) but i guess adding more wouldn't hurt anyone.. i'll leave this easy TODO with the heavy bug up here then

**Comment by zephyr91** [comment]
well, i find out that the ctrl+pgup and ctrl+pgdown works, but its not worth these keys, i think it could be implemented like the last version that has the ctrl+tab

**Comment by Sbte** [comment]
No it can't. We tried that before, but it was taken out (because it was a bit broken I think). This is why it currently doesn't work. Someone must find a better way for catching key events first.

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/issues/116

**Comment by c10ud** [comment]
also, https://github.com/emesene/emesene/commit/47c727ad067d35c0dae7af4fbb3ba9d81a7b4131

**Comment by Mystro256** [comment]
if it's any relevance, all ctrl+tab (and shift) does for me is switch between the conversation box and each of the conversation toolbar buttons.

**Comment by marianoguerra** [comment]
can we close this? ctrl+tab and ctro+shift+tab is used by gtk, using it in your program is a hack, we tried it, it worked weird.

I vote for closing it.

**Comment by Sbte** [comment]
I vote for keeping it. People expect this to work. At least I did, and I'm a person, so yeah...

**Comment by c10ud** [comment]
i don't personally care, ctrl+pgup(down) is enough for me. the damn
browsers abuse this feature, maybe we can just move it to 2.1 if
someone finds a way to frak gtk and make it work..?

2011/4/15 Sbte reply@reply.github.com:

**Comment by Mystro256** [comment]
Well the issue with page up and down is with smaller keyboards that require you hold function key (the fn key) and hit another key to use page up and down (e.g. a laptop keyboard), making it more possibly/arguably more inconvenient for some. As well, there is also the argument of inconsistency and lack of keyboard short cut standards over different applications. I personally don't care, I think page up and down is enough, and don't think it's required for 2.0 anyway, but it could be considered for 2.1 if too many complaints arise.

**Comment by zephyr91** [comment]
but why take off one shortcut key that was already working in the last stable version ?? doesnt make any sense ! it could just add the feature to the window control,

if i was able to program something like that i would have the pleasure to put in the source code, but i cant unfortunately !

**Comment by c10ud** [comment]
if i was able to make it work, i would have the pleasure to enable
this, but i can't unfortunately..i guess it's the same for the other
devs.

2011/4/16 zephyr91
reply@reply.github.com:

**Comment by Sbte** [comment]
Fixed in my tree (at least for me). I just have to wait for the emesene 2.11.4 packages to arrive...
