### ISSUE TITLE
Mute from systray icon menu

### ISSUE THREAD

**Issue by sebastianlacuesta** [emesene/emesene#374]
It would be nice to have a quick option to mute emesene from the systray icon menu.

**Comment by c10ud** [comment]
i thought setting the busy status was just enough, since emesene is
not a media player (yet)

2011/4/6 sebastianlacuesta
reply@reply.github.com:

**Comment by sebastianlacuesta** [comment]
Ooop, I didn't know that, since I almost never use the busy status. I just
(I now it's kind of antisocial) don't reply messages when I'm busy :P. This
sounds good. Thanks for the reply!

2011/4/6 c10ud <
reply@reply.github.com>

**Comment by c10ud** [comment]
no problem

2011/4/6 sebastianlacuesta
reply@reply.github.com:

**Comment by c10ud** [comment]
closing
