### ISSUE TITLE
Emesene2 won't accept incoming downloads

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#375]
I knew emesene's file transfert speed was terrible (throigh I heard this was going to be fixed for emesene2), but now, it seems like it's impossible to download files directly from your contacts.
The apparent cause? The "Accept" button doesn't do anything.

/home/user/emesene/emesene/gui/gtkui/FileTransferWidget.py:69: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)
[16:04:49 ERROR papylib.Events] Error sending message: 4 1

Steps to reproduce:
(tested and confirmed on revision 7b2ee35)
-Open a conversation with any of your contacts
-Ask him to send you a file
-Try to accept the download infitation
-Fail at doing so

**Comment by c10ud** [comment]
[16:04:49 ERROR papylib.Events] Error sending message: 4 1

seems like your contact isn't acknowledging your request. are you
using emesene git with papyon submodule? or some fixed papyon version?
there were some issues with papyon that have been solved in latest
master

2011/4/6 Riboshom
reply@reply.github.com:

**Comment by sm-Fifteen** [comment]
That's a very good question, but I really have no idea of my papyon version...
Any way I could get the latest/git version?

And are you still planning to implement direct dl for emesene2? I couldn't find the issue related to that.

**Comment by c10ud** [comment]
direct connect: it's up to the underlying library now, that is,
papyon. (it was already implemented but not merged into master -- you
should ask on their bugzilla on why, i never known the exact reason)

papyon version..depends on where you did get your emesene copy.. if
you followed the tutorial for testers you should have the latest,
otherwise, it depends on the OS you're using

2011/4/7 Riboshom
reply@reply.github.com:

**Comment by sm-Fifteen** [comment]
How could I replace the packaged version with the git version?
I mean, how could I get emesene to use instead of the bundled version?
Is there a function that probes emesene's own folder for a "papyon" folder and refers to it if there's one?
Cause that would be pretty darn useful!

**Comment by c10ud** [comment]
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

**Comment by sm-Fifteen** [comment]
You mean papyon is included in emesene's git?

**Comment by c10ud** [comment]
as a submodule,yes

**Comment by sm-Fifteen** [comment]
Nothing have changed since I've filed this bug:
/home/user/emesene/emesene/gui/gtkui/FileTransferWidget.py:69: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)
[17:14:03 ERROR papylib.Events] Error sending message: 4 1
[17:14:03 ERROR papylib.Events] Error sending message: 4 1
I updated my git revision at 17:00, so the file-transfer module must effectively be broken.

**Comment by c10ud** [comment]
actually, that is your friend refusing your p2p messages. we should
probably print a better error but that's the culprit. if you could
provide a big log running ./emesene -vvv to the papyon developers that
would be great (remember to obscure mails first)

2011/4/8 Riboshom
reply@reply.github.com:

**Comment by sm-Fifteen** [comment]
[17:26:08 INFO papyon.msnp2p.transport] Registering transport <SwitchboardP2PTransport peer="XXXXXXXX@live.com" guid="a0d4c580-baa5-4781-a716-1c5c28b8562f">
[17:26:08 DEBUG papyon.msnp2p.transport.switchboard] >>> TLPv2 chunk 0x3a326f17: blob 0, RAK, SYN, SLP Message
    MSNSLP/1.0 200 OK\r\n
    To: msnmsgr:XXXXXXXX@live.com;{a0d4c580-baa5-4781-a716-1c5c28b8562f}\r\n
    From: msnmsgr:riboshom@hotmail.com;{31fdcad2-07e6-4af9-b555-eb5648d000d6}\r\n
    Via: MSNSLP/1.0/TLP ;branch={66A51C77-CAE2-4CA0-816D-479DD9B5B413}\r\n
    CSeq: 1\r\n
    Call-ID: {D6BE4166-0D2F-40AA-8753-F4C9C2AF2088}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 26\r\n
    \r\n
    SessionID: 4029949266\r\n
    \r\n
    \x00
[17:26:08 INFO papyon.protocol.switchboard_manager] Requesting switchboard for participant(s) XXXXXXX@live.com
[17:26:08 INFO papyon.protocol.switchboard_manager] Using already opened switchboard 200284056.415860.8110846
[17:26:08 INFO papyon.protocol.switchboard_manager] Handler <SwitchboardP2PTransport peer="XXXXXXX@live.com" guid="a0d4c580-baa5-4781-a716-1c5c28b8562f"> attached to switchboard 200284056.415860.8110846
[17:26:08 DEBUG papyon.transport] >>> MSG 11 D 243
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    P2P-Src: 'riboshom@hotmail.com;{31fdcad2-07e6-4af9-b555-eb5648d000d6}'\r\n
    P2P-Dest: 'XXXXXXXX@live.com;{a0d4c580-baa5-4781-a716-1c5c28b8562f}'\r\n
    [P2P message (439 bytes)]
[17:26:08 DEBUG papyon.transport] >>> MSG 11 D 243
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    P2P-Src: 'riboshom@hotmail.com;{31fdcad2-07e6-4af9-b555-eb5648d000d6}'\r\n
    P2P-Dest: 'XXXXXXXXX@live.com;{a0d4c580-baa5-4781-a716-1c5c28b8562f}'\r\n
    [P2P message (439 bytes)]
[17:26:08 DEBUG papyon.transport] <<< NAK 11
[17:26:08 ERROR papylib.Events] Error sending message: 4 1
[17:26:08 INFO papyon.msnp2p.transport.switchboard] Received error: 1 (type=4)
[17:26:08 INFO papyon.msnp2p.transport] Unregistering transport <SwitchboardP2PTransport peer="XXXXXXXX@live.com" guid="a0d4c580-baa5-4781-a716-1c5c28b8562f">
[17:26:08 INFO papyon.protocol.switchboard_manager] Closing switchboard handler <SwitchboardP2PTransport peer="XXXXXXXX@live.com" guid="a0d4c580-baa5-4781-a716-1c5c28b8562f">
[17:26:08 DEBUG papyon.transport] <<< NAK 11
[17:26:08 ERROR papylib.Events] Error sending message: 4 1

**Comment by c10ud** [comment]
thanks, i'll pass this msg to the papyon devs and see what they tell us

2011/4/8 Riboshom
reply@reply.github.com:

**Comment by c10ud** [comment]
ok, they asked for a longer debug trace if you could have it -- they need to see what was happening in the switchboard before the file transfer, because it's using an already existing one that could be closed or smth. please paste the debug in pastebin.com andgive the link here so it's easier to read :) 

p.s. i'm shutting down here, i'll see if i can get a reply tomorrow

**Comment by sm-Fifteen** [comment]
There you go :D
http://pastebin.com/137KU7jh
Just so you know:
-AAA, BBB, CCC, DDD, and EEE are just online contacts
-XXX is the sender.
-Riboshom is, well, me, the receiver
-I haven't accepted the download at any time (mostly because it wouldn't show up, I'll file a bug about that)

**Comment by c10ud** [comment]
is this still happening? there have been papyon updates, see http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html to see how to update with the papyon submodule

**Comment by astagi** [comment]
Which client do you use to send files to emesene2??

**Comment by c10ud** [comment]
cleanup for 2.0
