### ISSUE TITLE
About the double click on the contaclist..

### ISSUE THREAD

**Issue by zephyr91** [emesene/emesene#378]
if i add this lines, it wont open the emesene and in terminal he says this

if i remove the 4 lines in the other post, emesene opens fine, i think some package is missing... any ideas??

" /usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead import sha,base64,random,dispatcher,re /usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead import md5 Traceback (most recent call last):
File "/usr/bin/emesene", line 34, in

emesene.main()

File "/usr/share/emesene/emesene/emesene.py", line 701, in main

main_method(Controller)

File "/usr/share/emesene/emesene/gui/gtkui/init.py", line 40, in gtk_main

import ContactList

File "/usr/share/emesene/emesene/gui/gtkui/ContactList.py", line 252

if self.row_expanded(path):
^

IndentationError: unexpected indent
"

**Comment by astagi** [comment]
Try to reclone emesene 2...

**Comment by zephyr91** [comment]
reclone ??/ i didint get it ..

**Comment by astagi** [comment]
How did you get emesene 2?? On line 252 there's another instruction so please reclone emesene 2 ( git://github.com/emesene/emesene.git  )

**Comment by zephyr91** [comment]
i get it through apt-get in debian wheezy, it was working until i format my notebook, and now i cant figure out what is missing... =\

edit: still didnt understand what you say 4ndreast4gi

the line 252 its the code i have to add to ContacList.py to the double click work.

**Comment by Sbte** [comment]
You clearly did something wrong. If you want to get the latest version of emesene, follow these instructions:

http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

Otherwise just wait for a new version of emesene to get into Debian wheezy. Please don't change files manually if you have no clue what you are doing.

To make emesene working again (but without double click) just reinstall emesene I guess.

**Comment by c10ud** [comment]
Sbte is right, i couldn't have said better
