### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by JuszR** [emesene/emesene#380]
I get an error while trying to run emesene on Gentoo:

Traceback (most recent call last):
  File "./emesene", line 29, in <module>
    from emesene import Controller
ImportError: No module named emesene

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./emesene", line 31, in <module>
    import Controller
  File "/home/leo/Downloads/emesene-1.6.3/Controller.py", line 109
    self.COMMENT = _('A client for the WLM%s network') % u'\u2122'
                                                                 ^
SyntaxError: invalid syntax

**Comment by arielj** [comment]
That's a valid syntax, can you try reinstalling python?

Anyway, it won't work if you can't fix the first exception: ImportError: No module named emesene

You have some issues with python, I don't have gentoo to test it

**Comment by c10ud** [comment]
arielj is right -- simply skipping the first import won't help with the rest. also, this tracker is only for emesene2 which is our current focus of development

**Comment by JuszR** [comment]
it didn't work. I have python 3.1.3 and emesene 1.6.3.

**Comment by c10ud** [comment]
emesene doens't work with python3

**Comment by Sbte** [comment]
...yet ;)

**Comment by c10ud** [comment]
pygtk doesn't work with py3k, i guess it requires a complete port of
emesene+papyon to py3k and pygtk to pygi :) not something doable in
the next days, eheh

2011/4/15 Sbte reply@reply.github.com:

**Comment by JuszR** [comment]
ok. solved (changing python interpreter to 2.6)

[q grande che nunca pense q mariano podria llegar tan lejos con esto, suerte ;)]
