### ISSUE TITLE
No way to quit application when not logged in (Ubuntu messaging menu)

### ISSUE THREAD

**Issue by Richardprins** [emesene/emesene#382]
When you're not logged in, and for some reason are not able to, there is no clear way to quit the application. It stays active in the messaging menu. There's no menu bar so you can't select file > quit

**Comment by Sbte** [comment]
This is what I found too, but I usually just kill it, or close the terminal I run it from. This shouldn't be necessary though, so any ideas as to where to put the close button?

**Comment by Richardprins** [comment]
Maybe a menu bar, or maybe a button below the "connect" button? I'd prefer a button instead of a menu entry so everybody can easily find it. Maybe there also needs to be a clear button when logged in, so new users can spot it easily.

**Comment by c10ud** [comment]
mm the new ubuntu policy seems to suggest to avoid closing apps -- but, i also think a close button would be welcomed. not sure on where to put it. i don't think a menubar is a good option. and a button would just look ugly..maybe we should just close the program if the X in the window decorations is pressed when we're not logged in........?

**Comment by Sbte** [comment]
It's possible, but it's probably also unexpected behavior.

**Comment by c10ud** [comment]
i need ideas then, adding a gtk Menu is not an option imo

2011/4/11 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
I myself like the idea of having the close button to actually close it, but it's different from the other chat clients and also not consistent with what it does the rest of the time.

Maybe we could just implement it and hope no one complains?

**Comment by c10ud** [comment]
in the end, an IM not logged in is useless.. we can try i guess.. are
you willing to tackle this?

2011/4/12 Sbte reply@reply.github.com:

**Comment by Richardprins** [comment]
I agree with having the close button close, because unlike empathy (If I'm not mistaken), emesene allows you to open multiple instances. I often have multiple emesene's open in my messaging menu, not logged in, and it's not so easy to close them.
