### ISSUE TITLE
emesene moved from main screen if a second screen is connected and disconnected 

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#384]
Sometimes when I start emenese it does not appear on my main screen, even if it is the only screen currently connected. It happens if I have had my second screen plugged in (tv connected via hdmi cable) while emesene was open, and then I close emesene while the 2nd screen is plugged in. The next time I open up emesene with the 2nd screen disconnected, it does not open on my main screen. emesene is never moved to the 2nd screen by me, it does it on its on.

I found it in both 1.6 and 2.0 (found at http://www.blogger.com/comment.g?blogID=28704147&postID=7891698072256276861) on windows 7.

**Comment by c10ud** [comment]
i think this is a bug in your window manager -- that is -- windows 7
window manager. we don't choose where to place our windows, it's up to
the window manager

2011/4/11 syst3mfailur3
reply@reply.github.com:

**Comment by ghost** [comment]
Out of the programs I use, this problem only happens with emenene. The only way to restore the window to the main screen is to maximize the window from the preview in the taskbar.

**Comment by arian** [comment]
I've got something similar on Ubuntu, where it opens in my second workspace. (using 2.0.25~ppa1~ubuntu1)

**Comment by Sbte** [comment]
Do you have a good way to reproduce this? It always opens in the same spot for me. The only thing I can think of is that it happens is if you don't close emesene properly.

**Comment by arian** [comment]
Ok, I usually put emesene in my 2nd workspace. Mostly after a reboot I start emesene again (from my first workspace) and it opens in my 2nd workspace (wouldn't expect that, all other applications open in the current (first) workspace). But if go to my second workspace first and then open emesene, it opens in my third workspace, which I wouldn't expect at all.

**Comment by ghost** [comment]
1. Start with only main screen connected (using laptop)
2. Open emesen (http://i51.tinypic.com/16bagav.png)
3. Connect 2nd screen (using hdmi cable)
4. Close emesene
5. Disconnect 2nd screen
6. Open emesene (http://i53.tinypic.com/153pjzl.png)

Emesene now does not open on the main screen, but is open. Only way to restore to main screen is to Maximize emenese by right-clicking on the preview.

**Comment by marianoguerra** [comment]
emesene stores the position of the window when it's closed and resptores the position on initialization.

so when you unplug the second screen emesene still opens in that position.

maybe we should do a check for the resolution of the screen? I don't know an easy way to handle this.

maybe set the position only if it's between a range of something like 1280x1024?

**Comment by ghost** [comment]
The problem with that, if I'm understanding you correctly, is that if
someone has a 2+ screen setup at all times they wouldn't beable to have
their screen position saved.

On Mon, Apr 11, 2011 at 8:03 PM, marianoguerra <
reply@reply.github.com>wrote:

> emesene stores the position of the window when it's closed and resptores
> the position on initialization.
> 
> so when you unplug the second screen emesene still opens in that position.
> 
> maybe we should do a check for the resolution of the screen? I don't know
> an easy way to handle this.
> 
> maybe set the position only if it's between a range of something like
> 1280x1024?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/384#comment_986870

## 
- Shawn

**Comment by marianoguerra** [comment]
import gtk
window = gtk.Window()
screen = window.get_screen()
screen.get_width(), screen.get_height()
(1440, 900)

just a matter of adding an if to check if the stored size is bigger than the screen resolution

**Comment by c10ud** [comment]
cool, didn't know that -- will you do this? or, where is this
restoring performed? (aka lazy internet "grep --mariano")

2011/4/12 marianoguerra
reply@reply.github.com:

**Comment by marianoguerra** [comment]
On Tue, Apr 12, 2011 at 10:59 AM, c10ud
reply@reply.github.com
wrote:

> cool, didn't know that -- will you do this? or, where is this
> restoring performed? (aka lazy internet "grep --mariano")

emesene.py _set_location method

**Comment by c10ud** [comment]
wdyt

```
    screen = window.get_screen()
    pwidth, pheight = screen.get_width(), screen.get_height()
    if posx > pwidth or posy > pheight:
        posx, posy = posx - pwidth, posy - pheight

    window.set_location(width, height, posx, posy)
```

2011/4/12 marianoguerra
reply@reply.github.com:

**Comment by c10ud** [comment]
whoops, i guess i need to do two different checks otherwise window
could go anywhere (if posy is > pheight but x isn't)

2011/4/12 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by c10ud** [comment]
```
    screen = window.get_screen()
    pwidth, pheight = screen.get_width(), screen.get_height()
    if posx > pwidth:
        posx = posx - pwidth
    if posy > pheight:
        posy = posy - pheight

    window.set_location(width, height, posx, posy)
```

2011/4/12 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by marianoguerra** [comment]
On Tue, Apr 12, 2011 at 11:44 AM, c10ud
reply@reply.github.com
wrote:

> screen = window.get_screen()
>        pwidth, pheight = screen.get_width(), screen.get_height()
>        if posx > pwidth:
>            posx = posx - pwidth
>        if posy > pheight:
>            posy = posy - pheight
> 
>        window.set_location(width, height, posx, posy)

what if posx is 2000 and pwidth is 800?

posx = 2000 - 800 = 1200 = fail ;)

i think if the pos is > than the screen size set it centered, any
other position is just guessing

**Comment by c10ud** [comment]
yeah right i'm stupid -- so you say posx = posx / 2 and posy = posy/2
if something like this happen? being a corner case, i think it should
be fair enough (?)

2011/4/12 marianoguerra
reply@reply.github.com:

**Comment by marianoguerra** [comment]
On Tue, Apr 12, 2011 at 1:07 PM, Mariano Guerra
luismarianoguerra@gmail.com wrote:

> On Tue, Apr 12, 2011 at 1:02 PM, c10ud
> reply@reply.github.com
> wrote:
> 
> > yeah right i'm stupid -- so you say posx = posx / 2 and posy = posy/2
> > if something like this happen? being a corner case, i think it should
> > be fair enough (?)
> 
> yep, enough for me

posx = pwidth  // 2
posy = pheight // 2

the ones you show (posx = posx / 2) still fail if the current
resolution is less than half of the stored value :D

**Comment by marianoguerra** [comment]
On Tue, Apr 12, 2011 at 1:02 PM, c10ud
reply@reply.github.com
wrote:

> yeah right i'm stupid -- so you say posx = posx / 2 and posy = posy/2
> if something like this happen? being a corner case, i think it should
> be fair enough (?)

yep, enough for me
