### ISSUE TITLE
Preferences dialog doesn't have close button on gnome3

### ISSUE THREAD

**Issue by diega** [emesene/emesene#385]
gnome3 by default removes close button in dialogs. Likely the HIG will have some points about how new dialogs should be organized.
I link to a screenshot of the Preferences dialog on gnome3 and in gnome2.
http://img819.imageshack.us/i/preferencesgnome3.png

**Comment by c10ud** [comment]
> > gnome3 by default removes close button in dialogs.

is there a reason for having this fuckedup behaviour?
unfortunately i don't think they will fix this, so i guess we'll just have to fix their mess..

**Comment by diega** [comment]
I don't think they gonna fix it b/c is on this way by design. I don't have an official answer but I personally prefer some explicit close button, even I miss the _old fashioned_ cancel behavior :).
Here is a short analysis of what will be needed for apps to stay close to gnome3 guidelines (it mentions some things about dialogs)
http://blogs.fedoraproject.org/wp/mclasen/2011/01/19/gnome-3-and-you/

**Comment by c10ud** [comment]
the only thing i can think of is a big ugly "close" button in bottom
left of the dialog. but i'd like to show it only with gnome3.. i guess
i need to search how to identify if it's running

2011/4/11 diega
reply@reply.github.com:

**Comment by Sbte** [comment]
What would be possible is a series of Apply/OK/Close buttons, like most programs have, but that would require a total rework of how the preferences work.

Maybe you could change the preferences to a non-dialog window? You'd just have to switch off the dialog flag I guess.

**Comment by c10ud** [comment]
i changed from WINDOW_TYPE_HINT_DIALOG to WINDOW_TYPE_HINT_MENU please try it

2011/4/12 Sbte reply@reply.github.com:

**Comment by diega** [comment]
works well.
here u have how it looks right now http://img845.imageshack.us/i/preferencesgnome3.png/
Tnx!
