### ISSUE TITLE
Close emesene, unopened account (Cerrar emesene, sin abrir cuenta)

### ISSUE THREAD

**Issue by javijec** [emesene/emesene#390]
There is no way to close the emesene if you open an account
(No existe la forma de cerrar el emesene si no abrís una cuenta)

Google Traductor

**Comment by Sbte** [comment]
Archivo -> Quit

You can quit it like that. it's on purpose that you can't do it by clicking the red x ;)

**Comment by javijec** [comment]
With global menu of Ubuntu 11.04, do not see "Archivo" until you connect to an account

(Con el global menu de Ubuntu 11.04, no aparece "Archivo" hasta que no te conectas a una cuenta)

**Comment by Sbte** [comment]
True, but before you're logged in, you CAN close with the red x. But that's since yesterday. If you didn't update emesene yet, you won't have that feature.

**Comment by javijec** [comment]
ok
