### ISSUE TITLE
In file transfer emesene 2 only can send pictures

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#393]
If I am select an other filetype nothing happen, just works with pictures.

**Comment by rockybalboa** [comment]
And a feature request: Please add notes to both contact (sender, reciever) the file sending request status (accept, dismiss)

**Comment by Sbte** [comment]
I'll look into the first bug. That's a recent regression.

Just open a new issue for the feature request ;)

**Comment by Sbte** [comment]
Damn you c10ud!

**Comment by rockybalboa** [comment]
Thanks guys! You are very fast! :D
