### ISSUE TITLE
Feature Request: Notify both contact (sender, reciever) of the file transfer's status

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#394]
Write a notify to both contact's conversation window ot the file transfer's status. If the reciever accept, sent a message:
"XYZ accept your file transfer request".  And so on.

**Comment by c10ud** [comment]
andrea fixed this, why reopen?

**Comment by rockybalboa** [comment]
Thanks for your work. But there two error.
1. If I am reject the file transfer nothing happen (no notitfy, and the other contact wait for my response to accept it)
2. The sender got the "File transfel completed!" message twice.

**Comment by astagi** [comment]
1. No, because you don't need to know this :) If you reject the file, you don't see the file transfer active...
2. I don't know why, I think that papyon emit te signal twice... I'll take a look...

Can I close? :)

**Comment by c10ud** [comment]
yeah 1) is not an issue while 2) if you want to take a look...anyway the feature is implemented

**Comment by rockybalboa** [comment]
1. No, If I am reject it, the sender don't see anything.

**Comment by c10ud** [comment]
i'll try it, but if that happens, that's a bug in papyon

**Comment by astagi** [comment]
Yep, or a bug in the other client if you use something else...

**Comment by rockybalboa** [comment]
I tried it with emesene 2 too.
