### ISSUE TITLE
Contact list goes blank

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#397]
I have noticed that occasionally the contact list comes completely blank, without anyway to restore it aside from restarting emesene. Its happened a few times over the last few days and I think a few different things are triggering it. I only know of one of them.
1. Open emesene and login
2. Open Preferences
3. Log out (not exit) of emsene
4. Blank contact list/login screen

**Comment by ghost** [comment]
Found on windows btw.

**Comment by astagi** [comment]
Did you have the last version with Sbte last commits??

**Comment by ghost** [comment]
If from earlier today, then no. I'm using a version from yesterday.
I'll compile a new exe with the latest now,

**Comment by c10ud** [comment]
doesn't happen here (tried what you said) can you try pulling latest updates? maybe it's windows specific?
@arielj ^

**Comment by ghost** [comment]
Will do. 
This is a pic of what was happening.
http://img546.imageshack.us/i/blankcontactlist.png/

**Comment by c10ud** [comment]
a debug trace would be better, try running emesene from terminal (cmd in windows?) and reproduce to see what happens (if still happens with latest commits)

**Comment by ghost** [comment]
No idea how to to that. 

And just try a newer version Sbte's last commits, it still happening.

**Comment by ghost** [comment]
Related to this issue.
If you exit emesene with the preferences open, preferences remains open but stops responding.
http://img155.imageshack.us/i/preferencescrash.png/

A band-aid fix to this might be disabling the contact list while preferences is open. But then the same issues might occur if a user uses the tray icon to disconnect or exit.

**Comment by arielj** [comment]
Yeah, it's a windows specific bug, Python thinks that "D:\programas\emesene.png", translated to absolute path, is "D programas emesene png" (with all those spaces), problems with backslashes.

My pull request fixes this

**Comment by ghost** [comment]
It seems works, the contact list/login menu is no longer blank. The problem now is that Preferences remains open.

**Comment by arielj** [comment]
I'll close this and leave the other issue open.
