### ISSUE TITLE
Issues with Right click Menu

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#398]
When #238 was fixed (double right click menu), instead of merging the two menus, one of the menus was just deleted. Though not a critical feature, because control+C still works, but there's no option to copy text in the conversation area or the email at the top. All I get clicking any where is Page 1, Page 2, etc.

This leads to another related issue; if either display picture is right clicked, you get the right click menu and the window both showing (the window is either the contact info or avatar chooser depending on which one you click)

**Comment by c10ud** [comment]
doubleclicking the personal-message and email area shows up the copy... menu

as for text, we need to hax webkit i think, and it's hard

right clicking.. it's what the gtk.Notebook does i think. I know it's
not nice but then it's a matter of discussing and choosing if keeping
its functionality is worth it or not..

2011/4/13 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
Hmm I see, I'm not sure if its worth it to be honest. My only argument is that the lack of copy in the menu may confuse less computer strong individuals; having an option for choosing tabs/pages seems a little pointless, considering that you can just left click a tab just as easy. I think the only reason this could be useful is as a keyboard shortcut because of the issue with ctrl+tab.

Thoughts?

**Comment by Sbte** [comment]
Let's fix the ctrl+tab and replace this right click menu with a copy menu. That's what I'd say.

**Comment by Mystro256** [comment]
Yeah, that does seem like the best idea, especially for the easily confused ;)

**Comment by c10ud** [comment]
@sbte: if let's == you then i'm perfectly fine with it!

2011/4/13 Mystro256
reply@reply.github.com:

**Comment by arielj** [comment]
Just in case someone wants to dig on this, webkit.WebView has a "populate-popup" signal that returns the menu, we need to connect to that signal and modify that menu and add the options we want (what do we want? ideas? copy/select all/clear conversation/save contact's custom emoticon/what else?)

**Comment by c10ud** [comment]
we'll do this after 2.0, but i guess that's all we need sir :D

**Comment by Sbte** [comment]
Format windows partition seems like a nice option. Good luck on testing it ;)
