### ISSUE TITLE
Link in About doesn't work

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#399]
When you try to click on the link in the About window you get the following message:

"Could not show link
No application is registered as handling this file"

And when you click on the email links in Credits you get:

"Could not show link
Error stating file 'c:\Users\Shawn\emesene\emesene\mailto:EMAIL%40DOMAIN.com': No such file or directory"

**Comment by astagi** [comment]
Do you mean email links?

**Comment by ghost** [comment]
Oops, I meant to say the About window. But the email links in the credits also don't work.
Edited the original post to include email links.

**Comment by astagi** [comment]
Ok, I'll take a look soon, it's not so important at the moment ;) but thanks anyway...

**Comment by Sbte** [comment]
Andrea, this is Windows only I guess. Seems to work fine in Ubuntu...

**Comment by astagi** [comment]
Yep, we should try to find a solution for every system ( if possible ) ;)

**Comment by c10ud** [comment]
@arielj does the pull i made from you fix this too?

**Comment by arielj** [comment]
Nope, i'm working on that, gtk.AboutDialog is buggy I guess...

EDIT: please, pull my last commit

**Comment by ghost** [comment]
Works.
