### ISSUE TITLE
Message received by another contact

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#4]
I answered some message, but the answer is received by another contact...
I had not opened a window or tab with this other contact.

**Comment by cando** [comment]
what backend are you using???msn?Payon?

**Comment by EibrielInv** [comment]
I'm sorry. Papyon. Is the only one available...

**Comment by cando** [comment]
mmm..ok..i haven't this problem...however this could be a problem of papyon backend...
i'll try to reproduce your problem..

**Comment by c10ud** [comment]
bump? eibriel?

**Comment by EibrielInv** [comment]
The problem don't repeat recently, apparently is fixed :D

**Comment by c10ud** [comment]
ok
