### ISSUE TITLE
[papyon backend] nice segfault

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#40]
i don't think it's papyon related, someone with l33t debugging sk1llz should take a look:
- start a papyon session
- before your display picture is showed, open a conversation with someone
- segfault

**Comment by c10ud** [comment]
this does not seem to happen with my "official" account.

however, when opening some conversation windows the correct (self) avatar isn't showed. something weird is going on here (?)

**Comment by c10ud** [comment]
seems like is gone, i think arielj fixed this with some magic (?)

**Comment by c10ud** [comment]
not gone, i think it's related to content roaming and something, but i haven't been able to debug this :(

**Comment by arielj** [comment]
I can't reproduce this, it's like... random? :P

**Comment by c10ud** [comment]
seems like so O_o, i'll try cleaning the folder a bit :|

**Comment by marianoguerra** [comment]
does this happen doing the same in papyon?

I mean, is this a papyon bug? or papylib bug?

**Comment by c10ud** [comment]
nice question - all i get is a nice Segfault lol

i have "myself" in the contact list, i'm starting to think to some recursion bug, if you wanna try out i'll send you privately the test account stuff

**Comment by c10ud** [comment]
with a rm -rf ~/.config/emesene2 after "the big pull"™ it seems gone. i'll reopen in case of new positives

**Comment by c10ud** [comment]
close
