### ISSUE TITLE
group actions untranslatable

### ISSUE THREAD

**Issue by Richardprins** [emesene/emesene#401]
When you right click on a contact, you see the options "move to group" etc. These three group actions aren't translatable. Furthermore, it seems the default names of the suggested groups aren't translatable either (Though I'm not sure if this is emesene's fault or my default windows live account's fault).

**Comment by c10ud** [comment]
they are
       self.move_to_group = gtk.ImageMenuItem(_('Move to group'))
        self.move_to_group.set_image(gtk.image_new_from_stock(gtk.STOCK_GO_FORWARD,
            gtk.ICON_SIZE_MENU))
        self.move_to_group.connect('activate',
                    lambda *args: self.on_move_to_group())
        self.move_to_group.set_submenu(self.move_groups_submenu)

```
    self.copy_to_group = gtk.ImageMenuItem(_('Copy to group'))
    self.copy_to_group.set_image(gtk.image_new_from_stock(gtk.STOCK_COPY,
        gtk.ICON_SIZE_MENU))
    self.copy_to_group.connect('activate',
                lambda *args: self.on_copy_to_group())
    self.copy_to_group.set_submenu(self.copy_groups_submenu)

    self.remove_from_group = gtk.ImageMenuItem(_('Remove from group'))
```

maybe the updated template isn't loaded in launchpad yet! group names
depend on your address book afaik

2011/4/13 Richardprins
reply@reply.github.com:

**Comment by c10ud** [comment]
oh wait--GROUP actions!
well, we just control rename and it's there...the others use GTK stock
actions...you'll get the translation only if you have the
correspondent gtk language pack!

```
    self.add = gtk.ImageMenuItem(gtk.STOCK_ADD)
    self.add.connect('activate',
        lambda *args: self.handler.on_add_group_selected())

    self.remove = gtk.ImageMenuItem(gtk.STOCK_REMOVE)
    self.remove.connect('activate',
        lambda *args: self.handler.on_remove_group_selected())

    self.rename = gtk.ImageMenuItem(_('Rename'))
```

2011/4/13 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by c10ud** [comment]
tried, they're translatable (and translated...tried with LANGUAGE=it)
