### ISSUE TITLE
Template(?) shows for PM for contacts with emoticons if preferences has been opened

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#403]
Another contact list/preferences issue.

If you open preferences, then hover over some contacts the template becomes visible. 
All contacts effected had either an emoticon in their name or PM.

Everytime I would hover over one of the effected contacts I would get this in the git terminal thing:

[21:38:53 ERROR gtkui.Renderers] this nick: 'CONTACT DISPLAY NAME
[$small][C=c10ud]CONTACT PERSONAL MESSAGE[/C][$/small]' made the parser go crazy,
 striping. Error: 'NoneType' object is unsubscriptable

And this on the contact list:
http://img860.imageshack.us/i/contactlistpreferencesi.png/
http://img222.imageshack.us/i/blankchat.png/

Steps to reproduce:
1. Start emesene and login
2. Open preferences
3. Hover over contacts, only some will be affected

Full text from git terminal:
http://pastebin.com/9r36y4Rq

Tested on Windows 7.

**Comment by Sbte** [comment]
And if you change your nick template to

```
[$DISPLAY_NAME][$NL][$small][$COLOR=696969][$MESSAGE][$/COLOR][$/small]
```

(can be done in Preferences -> Theme). Make sure you have emesene from today or later, because I think I fixed the COLOR tag yesterday (before that names with smileys didn't work). Also check if the other bug is fixed too then. Just in case :P

**Comment by ghost** [comment]
When I hit Apply, the contact list went blank.

**Comment by ghost** [comment]
The template is still being shown in the personal message after opening preferences.
The only thing that seems to be semi-fixed is that when you apply new template through preferences, when you hit apply it no longer causes  the contact list to go blank. It resets the display name though.

If you have windows, I have a recent package (includes ur last commit) at http://www.filefactory.com/f/52afa73e20b1d9ec/.
emesene2p - 20110414 (1445).exe is the most recent  portable version.
