### ISSUE TITLE
Emesene main window set to screen size at start up occasionally

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#406]
Possibly related to https://github.com/emesene/emesene/issues/384.

Sometimes, but not too often, when I start up emesene it has somehow been set to the size of the screen or something close to it. Its huge, with the top slightly pushed off screen (might be due to the taskbar at the bottom). Have not played around with 2nd screen, so thats not to blame.

I don't remember experiencing it before the fix for #384.

On Windows 7.

**Comment by c10ud** [comment]
well the resizing code didn't change, #384 only calculates a new
position in case of emesene being offscreen..this could be a different
issue

2011/4/14 syst3mfailur3
reply@reply.github.com:

**Comment by ghost** [comment]
Just a thought, since I don't remember it happening before #384.

**Comment by kidonaipe** [comment]
it happens to me the same thing on ubuntu maverick .

**Comment by ghost** [comment]
Since posting this, I don't think I have had it happen again.
I'll keep an eye on it tho.

**Comment by c10ud** [comment]
ok, i'll close this issue meanwhile, to have a clearer view on what's left
