### ISSUE TITLE
Emoticons disappear when hovered over after preferences has been opened

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#407]
Related to #403 and 0541a3f75dedb535b630198b096d51710f5b6163.

After opening and closing preferences, when you hover over contacts the emoticons turn into there shortcuts. New contacts that login after appear with the shortcuts.

Steps to reproduce:
1. Start emesene and login
2. Open preferences
3. Exit preferences
4. Hover over contacts, Emoticons turn to shortcuts (  :D :P etc )

On Windows 7.

**Comment by Sbte** [comment]
And with emesene from a day ago it works?

Anyway, something is seriously wrong with the preferences on windows...

**Comment by ghost** [comment]
I'm going to try 2 older builds. One from April 12, and one from March 17th. They are the oldest I have.

**Comment by ghost** [comment]
April 12, the emoticons disappear completely with no shortcuts. Links, including the first one if multiple in a PM are blue and underlined. No Template shown.

March 17, the same as April 12 as far as i can see.

**Comment by Sbte** [comment]
Can you test from my repo? I have no clue what this change does :P

https://github.com/Sbte/emesene/commits/

**Comment by ghost** [comment]
I can't right now. I will either later today or tomorrow.

**Comment by ghost** [comment]
Did not work. In fact now I don't see the emoticon at all in the contact list. Still though, when I open preferences the shortcuts appear.

Prefences + Windows = Hate

**Comment by Sbte** [comment]
Yeah, I already thought that'd break stuff. That's why I didn't push it. Anyway, I'll just revert it now.
