### ISSUE TITLE
Icon in topbar looks bad

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#408]
The icon in the topbar, upper left, looks jagged and looks bad in comparison to emesene1. Same icon, just one looks bad.

Pic:
http://img705.imageshack.us/i/iconvho.png/

On windows 7.

**Comment by c10ud** [comment]
maybe it's using the wrong icon? @arielj can you confirm this?

**Comment by ghost** [comment]
Was also present with the old icon.
http://img859.imageshack.us/i/oldicon.png/

**Comment by arielj** [comment]
Emesene 1 uses 4 different size version of the logo, so gtk don't have to do that ugly resize, i'll add that and a fallback in case the theme don't have those resized version. Check my pull request.

**Comment by ghost** [comment]
I just tried it, and it looks much better.
Problem is it seems its only affecting the main window. About, Preferences, and any others I may have missed are still using the gtk resize.

**Comment by arielj** [comment]
Fixed those two too!, if you find another window tell me.

**Comment by ghost** [comment]
Actions > Contact > *
Actions > Group > *
Avatar Chooser (Clicking user avatar)
