### ISSUE TITLE
emesene and groups

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#41]
am i the only one that doesn't get his opened groups remembered?

**Comment by c10ud** [comment]
in contact list, i mean

**Comment by cando** [comment]
me too...

**Comment by hit** [comment]
True, not remembered.

**Comment by marianoguerra** [comment]
the question is not wheter emesene2 remembers group status, but why on earth do you use group view?! :P

PS: I just pushed the feature test it, I don't use that view

**Comment by c10ud** [comment]
how we divide faggots and cool then? lol
