### ISSUE TITLE
Ctrl + c in Console

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#412]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/emesene.py", line 654, in on_close
    self.close_session()
  File "/home/andre/emesene/emesene/emesene.py", line 282, in close_session
    for conv_manager in self.conversations:
KeyboardInterrupt

**Comment by arielj** [comment]
Why would you type ctrl+c on a terminal? :S

It's not an emesene issue, you are forcing the console/terminal to terminate the excecution of emesene

**Comment by c10ud** [comment]
we don't have a clean way to exit when SIGINT is received -- OTOH i need to know what GNOME and other DEs send to emesene when closing the session. So we can intercept that signal and exit gracefully (with preferences saved, etc.)
