### ISSUE TITLE
Contact pictures not working in Avatar chooser

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#413]
Contact pictures not working in Avatar chooser.

no images in contact pictures

**Comment by astagi** [comment]
Be more explicit please...What OS do you use?? Which steps reproduce the problem??

**Comment by Sbte** [comment]
I think he means Avatar chooser -> Contact pictures is empty. So it's not doing what it's supposed to do.

**Comment by zipatei** [comment]
Yes. Thanks Sbte

**Comment by c10ud** [comment]
what is this section supposed to show? i have no idea lol

**Comment by rockybalboa** [comment]
In the Avatar chooser there are 3 categories and the Contact pictures is one of them. If you want to use one of your contact's avatar, you can choose it from this section.

**Comment by arielj** [comment]
Just commited a fix for this
