### ISSUE TITLE
Plus Characters Interpretation Error

### ISSUE THREAD

**Issue by kidonaipe** [emesene/emesene#415]
Some plus characters on the contact's nickname are not correctly shown. 

On Ubuntu Maverick Meerkat . 

http://www.ironpic.com.ar/pictures/6f14c47d144b6c7c9e14ee93c5ed7df1.jpg

**Comment by Sbte** [comment]
Could you ask them for the exact name they set? Even the dummy can't reproduce that..

**Comment by c10ud** [comment]
seems like the tag that says foreground =00000 in the second nick hasn't been closed therefore there's a wrong </span>

**Comment by c10ud** [comment]
the first one is more complex, but i guess the problem is the same.. 

yes, the old parser took care of this crappy situations (:P)

**Comment by Sbte** [comment]
The new one can too. I just need a nick to reproduce it (and place in the dummy).

**Comment by c10ud** [comment]
also: did it work with previous versions of emesene-git?

**Comment by Sbte** [comment]
Also, if you changed your nick template, please post that too. But I mainly need the exact name the contact set.

**Comment by kidonaipe** [comment]
The first nickname goes like this : '     [i][b][c=1]S[/b][u]oo[/u]lc[/c][b][c=#FF0080]ë[/c][/b][/i]    ~      that's the first part until the peace symbol in the first nickname. The contact is not online at the moment so i have to copy the nick in the gedit. 
It seems the program understands plus coding like html . well, when the contacts conect i will upload more stuff.

**Comment by Sbte** [comment]
That part works fine here. I guess it's the last part of the nick that broke it. That, or you don't have the latest version of emesene.

Edit: Actually, that part works better in my new parser than it did in the emesene 1 parser. Now give us some breakage ;)

**Comment by kidonaipe** [comment]
the second part its this : ·$1♥I could really use a wish right now!. | love yourself first.   (its the subnick)  . i just have updated from the repo . if it happens to me again i will reported.

i have a question : emesene2 is related to the Live messenger service like windows live messenger 2011 ? cause everytime i log in i have the same damn nickname  wich i've set it as name in the live account.

**Comment by Sbte** [comment]
Still doesn't break for me.

About the nickname: maybe your profile is broken. Go to Preferences -> Live Messenger and follow the instructions. If it's broken, that should fix it.

Edit: Btw, with repo, you mean this git repo I suppose? ;)

**Comment by Sbte** [comment]
Also, if the parser breaks down (and I suppose that is the case here), there should be a huge amount of terminal output. If you could post that somewhere, that would be awesome.

**Comment by kidonaipe** [comment]
yes, the git repo :P

**Comment by kidonaipe** [comment]
sorry for my ignorance. what's the parser? im from Argentina, & i've studied english although there are some words i don't understand, and im a noob in the programming stuff :P

**Comment by Sbte** [comment]
Nothing you should know about. It's just that if one of those contacts come online, there should be a lot of output in your terminal (when you run emesene from a terminal). If you could paste that somewhere, this bug would be easier for me to fix (I hope).

**Comment by kidonaipe** [comment]
understood 100% !

**Comment by kidonaipe** [comment]
Hey! figured it out . the break down it is produced when you used the old colorized characters. for example : ·$1 Hello, this is m nick name  . Try it , & if it happens to you too i'll paste the output.

**Comment by Sbte** [comment]
Ah, got it. Thanks. I tried it before, but it only seems to happen when it's in the nickname, not when it's in the personal message. I'll see if I can find a fix ;)

**Comment by Sbte** [comment]
Ah, it happens when you have it two times. Do you know by any chance if ·$1 both opens and closes the tag?

**Comment by kidonaipe** [comment]
if you use it in the personal message at the end of the status it says : "no-more-color" . Anyway its only when you used the old colorize characters . i dont give a f*ck . lol . hey i have a question about a issue wich freezes me the log in for a couple of seconds. can i ask u about that? or should i open a new topic?

**Comment by Sbte** [comment]
Yes, please open a new issue.

**Comment by Sbte** [comment]
Fixed now, I hope. If something else pop up, just tell us ;)

@c10ud, seems it was not my parser. It was most likely a bug in the Plus parser, but I'm not going to dig into that. This fix more or less haxes around it, but also makes sure that other stuff won't break either :D

**Comment by c10ud** [comment]
great to read!

2011/4/15 Sbte reply@reply.github.com:
