### ISSUE TITLE
Preferences breaks things on Windows

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#417]
I don't know why, but entering preferences on windows creates a lot of problems, after closing the preferences window:

-You can't logout > login, emesene crashes with no error
-Hover over contacts in contact list delete's emoticons
-You can't open new conversations most of the times
-You can't apply some settings
-Emoticon paths are changed in some way (i'm not sure why or how, but they are modified, some commands like abspath crashes with emoticon paths after preferences)

Now I have to know what's doing wrong the preferences window, this main issue should fix a few Windows issues.

EDIT: it should fix this https://github.com/emesene/emesene/issues/407 and some other issues already fixed with some hacky code.

**Comment by ghost** [comment]
So far so everything seems to be working fine. Emoticons display, editing the template works, etc.
Only preferences issue that need needs to be fixed as far as i know now is #416
