### ISSUE TITLE
Display emoticons in tooltip in contact list

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#419]
Just  noticed that emoticons aren't displayed in the tooltip in the contact menu. I don't know if this is by design, but I didn't see any reference to emoticons in Tooltips.py.

Not so much an issue as a request.

**Comment by c10ud** [comment]
i did this on purpose, to keep tooltips text-only apart from the
avatar. it's easy to change, but i'm not sure i want to do it. it's
nice now, without emoticons -- especially when system themes can have
strange colors for tooltips

2011/4/15 syst3mfailur3
reply@reply.github.com:

**Comment by Sbte** [comment]
I think I like them better without emoticons too

**Comment by ghost** [comment]
@c10ud Didn't think of that. 
Its not really a big deal, so whatevers best I guess.

**Comment by ghost** [comment]
Just wondering if the same thing applies for the notifications?

**Comment by Sbte** [comment]
Yes, I don't think they even support images inside the text area. In Ubuntu I mean. If someone using windows wants them, they should go ahead and implement them ;)

**Comment by ghost** [comment]
Ok, so no point keeping this open.

**Comment by c10ud** [comment]
notifications -- wouldn't know, maybe it depends on the type (e.g.
ubuntu notifications don't support this, maybe we could with
gtknotifications) but really it's not worth it imho

2011/4/15 syst3mfailur3
reply@reply.github.com:
