### ISSUE TITLE
avatars in contact list

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#42]
avatars in contact list does not claim (allocate) their space in the contact list.

just try making a one-line or a two-line template for the contacts in contact list and the vertical size will be based on the text, it won't care about vertical avatar space so it will be cut.

**Comment by arielj** [comment]
It should be fixed with this commit of mine http://github.com/arielj/emesene/commit/df431c9a4483c6649af79db181410eafbc09cdd6

**Comment by c10ud** [comment]
will pull soon, great job
