### ISSUE TITLE
Hitting Apply in Preference/Theme shows emoticons shortcut in user PM

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#420]
Related to #417.

When you open up preferences and hit apply in the theme menu, it causes any emoticons in the users PM to become the shortcuts. When you click on the PM, everything is deleted. By reentering PM with emoticon, emoticon is shown until process is repeated.

Contacts are NOT effected. All other preferences/contactlist issues seem to be fixed though.

Windows.

**Comment by Sbte** [comment]
Yes, on_redraw_main_screen does something weird. Clicking it also causes the No group group to be minimized. I guess it should call the same functions as when logging in, but apparently it doesn't. Maybe the No group group being minimized is a different issue with a wrong config variable being set btw. Don't know.

The issue reported in the OP is windows only btw.

**Comment by arielj** [comment]
check my repo, this should be fixed (only the message part, the group minimization is not fixed, we should open a new issue with that)

**Comment by c10ud** [comment]
the message thing is enough, refreshing the contact list is not something the user should do every day

**Comment by arielj** [comment]
When you hit the Apply button, the contact list is automatically refreshed, here, the "connected" group gets minimized (which is not good, the offline people are all visible and the online people is hidden :P)
