### ISSUE TITLE
Chat log (Registro de conversaciones)

### ISSUE THREAD

**Issue by javijec** [emesene/emesene#423]
Would be nice to have a record of all conversations
(Estaria bueno tener un registro de todas las conversaciones)

**Comment by marianoguerra** [comment]
ya existe, click derecho en un contacto en la lista de contactos.
already exists, right click on a contact in the contact list

**Comment by javijec** [comment]
El 16/04/11 20:04, marianoguerra escribió:

> ya existe, click derecho en un contacto en la lista de contactos.
> already exists, right click on a contact in the contact list
> 
> Y verlo en el chat, como esta en el emesene 1, que se puede ver las 
> ultimas 8 lineas.
> Yo lo recomiendo por cuando se cierra la ventana poder seguir la 
> conversación.

Andsee it inthechat,like thisin theemesene1,you canseethe last8lines.
Irecommend it becausewhen youclosethewindowtocontinuethe conversation.

**Comment by marianoguerra** [comment]
podria ser un plugin

could be a plugin

**Comment by marianoguerra** [comment]
https://github.com/emesene/emesene-supported-plugins/issues

podes pedir el plugin ahi, actualmente estamos tratando de estabilizar el codigo para el release 2.0

you can ask for the plugin there, right now we are trying yo stabilize the code for the 2.0 release

**Comment by c10ud** [comment]
did you ever try emesene?

2011/4/17 javijec
reply@reply.github.com:

**Comment by c10ud** [comment]
oh, github didn't sent me all the replies, anyway..

2011/4/17 Riccardo (C10uD) c10ud.dev@gmail.com:
