### ISSUE TITLE
File transfer reject doesn't work.

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#424]
The accept is okay, but if the reciever choose the reject nothing happen.

**Comment by c10ud** [comment]
@andreastagi

2011/4/18 rockybalboa
reply@reply.github.com:

**Comment by c10ud** [comment]
whoops, @4ndreast4gi

2011/4/18 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by astagi** [comment]
It works with the right other client... using emesene1 doesn't work, I tried with aMsn and it works.. Sorry but not seems to be an emesene2 problem...

**Comment by c10ud** [comment]
if it works with amsn, then it's ok, since it's the only client with a reliable protocol implementation. closing the issue

**Comment by rockybalboa** [comment]
In my test both clients are emesene2. So I don't understand why it isn't work for me...

**Comment by c10ud** [comment]
maybe when we reject we don't send the reject signal, or papyon
doesn't do it. it should be tested with amsn

2011/4/18 rockybalboa
reply@reply.github.com:

**Comment by astagi** [comment]
The signal is right send because aMsn catch it... I don't know why between emesene clients doesn't work...

**Comment by c10ud** [comment]
well, papyon could be flawed, not a big deal though
