### ISSUE TITLE
issue: gif emoticons move too fast

### ISSUE THREAD

**Issue by camos13** [emesene/emesene#425]
I can't say much more... i created some custom emoticons out of gif images, the thing is they move TOO fast... 2 or 3 times normal speed i would say.

anyone out there who had this problem too?

**Comment by c10ud** [comment]
in conversation window? or contact list? also, i never experienced this.

2011/4/18 camos13
reply@reply.github.com:

**Comment by c10ud** [comment]
can't reproduce and lack of further infos, closing the issue.
