### ISSUE TITLE
[Suggestion] Change font of PM in contact tooltip

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#431]
The current font of the PM in the tooltip can be somewhat confusing, as it is the same as the contacts name. With contacts that have both a long display name and a PM, it can be somewhat hard to see what is the PM and what is still the name. It might look better if it was made to be more consistent with the styling of how the PM is displayed in the contact list, size and colour.

**Comment by c10ud** [comment]
can't, we don't know tooltip's color and we don't want to hax the theme. also, putting a color in clist is bad, but we do it because 99% of users will have it blank
