### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#433]
I'm not sure if this is the intended result, but the sounds in the themes folder, in "emesene/themes/sounds/default", they sound "crackly," almost like the sound is bad quality or something. The nudge.wav sound seems to be the only one not effected.

Edit: This actually seems to be an issue with playing wav files period. Maybe the sounds shouldn't be in this format?

**Comment by Mystro256** [comment]
I just confirmed that it's not an issue with the sound but actually an issue with gstreamer :/

**Comment by Mystro256** [comment]
Maybe the sounds shouldn't be *.wav format? This crackling seems quite undesirable.

**Comment by Sbte** [comment]
I never had any problems with this. Maybe it's your gstreamer version or anything? I really have no idea, so just throwing an idea out there ;)

**Comment by Mystro256** [comment]
Oddly enough, I used audacity an converted "online.wav" to a bunch of formats (ogg, flac, aiff, mp3) and only mp3 (128 kbps) seemed to sound normal. Although it's even weirder because I converted that MP3 back to WAV, and the new wav file sounded just like the mp3. It seemed by converting the audio to mp3 and back fixed it, and was an issue with the file not gstreamer i guess.

I've had this issue for a long while with emesene (different computer, all with Ubuntu but various releases and different emesene versions), but only decided to mention it now. I'm not sure what the issue is to be honest :S

**Comment by Sbte** [comment]
Maybe you could convert them all with no loss of quality and push them?

**Comment by Mystro256** [comment]
I just did that, how do I push them? I'm not too familiar with pushing with git

**Comment by Sbte** [comment]
@git push@

But that only works if you didn't use one of the read-only ways to clone git. And if you have your ssh key attached to your github account.

**Comment by Mystro256** [comment]
I'm a little confuse what you mean, I used this to clone the git: http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

How would make a push? Do I have to fork emesene?

**Comment by Sbte** [comment]
Yes, but as far as I can see, you already did that.

You should probably read this:

https://github.com/emesene/emesene/wiki/GitHowTo

**Comment by Mystro256** [comment]
Yeah I did, in attempt to figure it out, I'll push it when I figure it out, I have to learn how to use git someday
