### ISSUE TITLE
Chat window theme lacking

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#437]
On windows, the chat window does not show properly. Part of the border around the text box is missing, the background of the window is white, and the avatar placeholder and border don't match with the background colour.

From a version from earlier today:
http://img848.imageshack.us/i/themeu.png/

XP (from a month ago):
https://lh4.googleusercontent.com/-rUTWP4LeUZU/TYFqXd2trJI/AAAAAAAAHdU/_0l2JxQ3X7I/s1600/Screen+shot+2011-03-17+at+01.51.46.png

Edited by: Arielj, Reason: Change title

**Comment by arielj** [comment]
This only happen using the "post 2000" theme on window, with the classic look it looks ok
http://www.freeimagehosting.net/uploads/fa00b491c8.jpg

maybe we are using os theme instead of the gtk's theme?

**Comment by c10ud** [comment]
usually gtk themes do nasty stuff, you should force some known-working one, like clearlooks or similar

**Comment by andresro14** [comment]
Sorry but, what is the theme of ther conversation that you use? 
I want it!

**Comment by arielj** [comment]
It's one of the default conversation themes of emesene 2.0

**Comment by arielj** [comment]
any idea? I have no clue why emesene1 uses a gtk theme and emesene2 uses a windows theme, both runing from source, I can't find anything relevant on the source either.

mariano?

**Comment by c10ud** [comment]
we dont' choose themes in our code, that's up to gtk and the configuration

**Comment by ghost** [comment]
fixed?

**Comment by c10ud** [comment]
nope, the fix is: "use a proper gtk theme", we cannot hax the themes
if they're broken

2011/5/5 syst3mfailur3
reply@reply.github.com:

**Comment by marianoguerra** [comment]
when I made the package I used the gtk windows theme (I think that it's on the guides I wrote) check with that and tell me if it works.

about the conversation theme, put some prints to know the paths you are using on AdiumTheme and related files, see if you are using some absolute path or relative path with something wrong.

does the problem appears with the packaged version or running it from source?

**Comment by marianoguerra** [comment]
if you are talking about the background on the display pictures, I think it's because we are using a custom widget for that (as far as I remember) maybe it  doesn't paint the correct background or doesn't use a translucent background, if you refer to that, we can fall back to gtk.Image for the display pictures.

**Comment by ghost** [comment]
The problem appears in both packaged and source.
The border on right and bottom of the input area aren't there.
The background of the chat window is white, when it should be the system colour.
