### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#439]
When you exit emesene2 on windows you get an error at close. 

Image:
http://img200.imageshack.us/i/exitm.png/

emesesne.exe.log:
No handlers could be found for logger "emesene.e3.common.DBus"
C:\Users\Shawn\Desktop\emesene\Packages\Portable.\Crypto\Util\randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken

**Comment by arielj** [comment]
I think it's a papyon issue, not emesene's.

EDIT: oh, you meant the popup, not the error itself :P

**Comment by marianoguerra** [comment]
we need to patch py2exe like we did on emesene 1 to avoid the ugly message at close

**Comment by marianoguerra** [comment]
http://emesene.svn.sourceforge.net/viewvc/emesene/trunk/windows/boot_common.py?revision=2467&view=markup

see the commented lines starting in line 56, we have to patch boot_commons.py from py2exe to comment those lines, so we don't get the annoying error message

**Comment by ghost** [comment]
So is this something I have to do during packaging? Not really sure what i'm suppose to do here.
Don't know python, and have just been following your guide to build the packages.

**Comment by marianoguerra** [comment]
I will update the gide when I have some time, to explain what is needed to solve this.

btw, I downloaded the portable version and webkit worked:

http://i.imgur.com/q7Tl6.jpg

the version I downloaded is on the screenshot.

maybe some dlls conflicting?

**Comment by ghost** [comment]
That would be much appreciated.
You also seem to have fixed the theme from the looks of it?

**Comment by c10ud** [comment]
ololol don emesene

**Comment by marianoguerra** [comment]
the documentation to close this issue is available and I fixed for myself ona test build.

closing
