### ISSUE TITLE
Sort Contacts issues

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#44]
Emesene seems to have issues sorting offline contacts and will not order contacts into an offline group. When the status-ordered is selected and offline contacts unhidden, it puts all the contacts into one group called online, with no offline folder.

Edit: see my comment

**Comment by arielj** [comment]
I can confirm some werid behavior, contacts that were offline on the "offline" group don't reorder after they get online.

I also had 2 "offline" groups, some contacts were online on one offline group and some contacts were online on the other.

**Comment by Mystro256** [comment]
Using the lastest source, there definately is some issue with with groups; they occasionally disappear when I log in, until I change the sorting method (and change it back).

**Comment by c10ud** [comment]
ping wariano

**Comment by Mystro256** [comment]
I never got this before but now online contacts are showing up in the offline folder :P

**Comment by lfottaviano** [comment]
see issue #78, there, is explained.

**Comment by c10ud** [comment]
closing this issue, please refer to #78 for further comments
