### ISSUE TITLE
Message indicator

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#440]
Hello,
Message indicator showing wrong number of inbox  messages.
when start emesene it shows 0 message.
later when messages arrives while it still open, it start counting from 1.
-Sorry for bad English-
Regards,

**Comment by Sbte** [comment]
I don't really get what you mean. Are you talking about mails, the memenu, or the notifications? Or maybe something else?

Whatever it is that you're saying, it should be fixed! :D

**Comment by ammarabdulsalam** [comment]
sorry, I mean the message icon in the top right panel next to search icon showing wrong number of messages.

**Comment by Sbte** [comment]
Ok, I know exactly what you mean now, thanks! But I don't use hotmail or anything, so I guess someone else should have a look at this. 

@4ndreaSt4gi, you wrote this code right? Maybe you could have a look? And could you also disable it completely when someone uses a non-live mail address while you're at it (hotmail.x/msn.com/live.com, see emesene 1). :D

**Comment by astagi** [comment]
Yes, I'll do soon ;) it's just a string parsing, thanks for the tip..

**Comment by Sbte** [comment]
@4ndreaSt4gi, this doesn't fix the original bug I guess. Just my side note ;)

**Comment by Sbte** [comment]
Oh, and 

[00:10:23 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'Session' object has no attribute 'get_profile'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), _arg)
  File "/home/sven/emesene/emesene/emesene.py", line 469, in on_login_succeed
    self.draw_main_screen()
  File "/home/sven/emesene/emesene/emesene.py", line 416, in draw_main_screen
    self.on_new_conversation, self.on_close, self.on_user_disconnect)
  File "/home/sven/emesene/emesene/gui/gtkui/Window.py", line 98, in go_main
    on_close, on_disconnect)
  File "/home/sven/emesene/emesene/gui/gtkui/MainWindow.py", line 43, in **init**
    self.**hotmail = Hotmail(self.session)
  File "/home/sven/emesene/emesene/e3/hotmail/Hotmail.py", line 34, in __init**
    self.profile=self.session.get_profile()
AttributeError: 'Session' object has no attribute 'get_profile'
[00:10:23 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/emesene.py", line 564, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'

**Comment by Sbte** [comment]
@ammarabdulsalam, it always shows the right amount of messages for me. No matter if I log in or out or do anything. Maybe you could help us with an exact way to reproduce the issue?

**Comment by astagi** [comment]
@Sbte fixed the crash, now I consider the session type too ;) tnx 4 the tip... Ok, I solved another type of bug in a bug :D

@ammarabdulsalam You wrote this:

"" when start emesene it shows 0 message.
later when messages arrives while it still open, it start counting from 1. ""

I think that is the correct behavior :) When an email comes, counter is incremented and note: counter only counts unread messages, not received messages ... If this is not the problem, as Sbte said, explain your steps ;)

**Comment by ammarabdulsalam** [comment]
what I mean is:
When I open hotmail in web browser I see 5 unread messages.
When I login in to messenger using emesene I see 0 new messages.
While I'm online and a message arrives emesene shows 1 new message, while hotmail shows 6 new messages.
I hope this can help.

**Comment by astagi** [comment]
Yep...a very strange behavior...don't know what could cause this o.O Maybe a messenger error... Now if you have 6 message unread, if you try to login again, you see 0 messages again in counter??

**Comment by ammarabdulsalam** [comment]
yes, when I login again it shows 0 new message.
I have tried another account (@msn.com, @live.com.au) and it works fine.
it's just @hotmail.com.
by the way I looked into debug window and there was no information at all about mail count in @hotmail.com account, while it shows papylib.Events:Mailbox count changed (initial? True): 1 (the right number) an the other accounts.
hope this could help.

**Comment by c10ud** [comment]
my accounts are @hotmail.com and they work, maybe you're logging in with some upper-case like you wrote "Hotmail.com"? and andrea is checking with == thus breaking the comparison?

**Comment by Sbte** [comment]
Nah, that == is for something else. I tried to login to my accounts with caps too (though they are live accounts). Maybe a bug in papyon?

**Comment by c10ud** [comment]
well, maybe in emesene, we should give the lowercased account from gui to papylib

**Comment by Sbte** [comment]
I didn't seem to have any difficulty with capsed accounts, so that doesn't seem to be the issue.

**Comment by ammarabdulsalam** [comment]
I have tried another hotmail account and it works fine, I don't know why this happen.
I'll try to fix this issue with my account.
Regards,

**Comment by Sbte** [comment]
Make sure your profile isn't broken? i.e. follow the instructions under Preferences-> Live Messenger. Hope it helps ;)
