### ISSUE TITLE
Status history

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#441]
Hello,
Status history in contact information not working at all.

**Comment by Sbte** [comment]
Yes, don't really see why it's there either. It's not all that useful I guess.

**Comment by arielj** [comment]
I've found how to fix this (the worker of papylib is not logging the status changes) but now I see that when a contact changes it's status from away to busy, it loggs away > online > busy, not away > busy, should I try to prevent this? or leave it like it is? :P

It's fixed but not pushed yet, I just want to know what do you think about that tiny "bug" before.

**Comment by c10ud** [comment]
if there's a bug, fix it! :D

**Comment by arielj** [comment]
That "bug" that I was talking was actually an emesene1 bug :P!!!!!!!!!!!!!!!

On emesene1, when you click the status icon on the user panel, it automatically change the status to online!

Just pushed a fix for this.
