### ISSUE TITLE
Problem with current song plugin

### ISSUE THREAD

**Issue by cognhuepan** [emesene/emesene#442]
I use current song with mpd, but when mpd server is not available, I loose control over emesene.

Plugin configs:

server: my-server.no-ip.org
password:
port: 6600

the leakdebug shows 

soap.manager.put(<SoapRequest DeleteRelationships>)
soap.manager makeSoapRequest(): <SoapRequest DeleteRelationships>
PASSPORT begin
200 OK
soap.manager makeSoapRequest(): <SoapRequest DeleteRelationships>
PASSPORT begin
200 OK
 .
 .
 .
until it can connect to the server.

Options for mpd plugin

meanwhile the window is not responding.

emesene 1.6.3 - "Uberlândia"
kernel 2.6.35-28-generic
gnome 2.32.0
Ubuntu 10.10 - Maverick Meerkat

**Comment by c10ud** [comment]
emesene-1 is currently abandoned, sorry
