### ISSUE TITLE
Timeouts keeps working after changing extension

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#444]
I encountered this issue with the music plugins:

All the extensions extends a base music handler class that launches a timeout to check the song every X seconds, the problem is that, if we change the used extension, the timeout of the previous one keeps going on and on (put a print or a log on the check song method of the MusicHandler class inside songretriever and your console will show that)

If we change beetween 2 or 3 extensions for the music plugin, we have 3 threads checking if a player is playing a song.

We need to "unload" an extension if we change it on preferences, the unload method should handle what to do for every extension, the music plugin extensions should stop that timeout for example, others extension could delete something to free some memory and those things...

I don't know if there's something already implemented for that, but I couldn't find how to do that.

**Comment by Sbte** [comment]
You just have to do something like

self.timer = glib.timeout_add_seconds(.....)

and when you want to get rid of it

glib.source_remove(whatever_handler_was_loaded.timer)

I guess you can just call this when you change extensions.

**Comment by arielj** [comment]
yeah, I know that, i've already made a commit with the self.timer = glib.timeout_add_seconds(.....) part but I don't know the best way to implement the "unload" thing (where the source remove will be)

I mean, where should I call that "unload" method? on preferences when I change an extension (i guess)? should we implement that on every extension? what can we do? maybe we can do a try: extensions.unload(extension) catch Exception: pass? any idea? maybe the "unload" method of the extensions class could do that try catch thing?

**Comment by c10ud** [comment]
@marianoguerra

**Comment by marianoguerra** [comment]
I think a function on_unload should be implemented on evey extension and be called when an extension is changed for another one.

**Comment by marianoguerra** [comment]
right now the changes of extensions are made on the preference dialog, maybe we should move that code outside the preference dialog so it's not dependent on the ui (and other frontends can use it).

**Comment by Sbte** [comment]
Maybe you could add a destructor? Seems to work here

```
#!/usr/bin/env python

class FooClass(object):
    def __init__(self, id):
        self.id = id
        print self.id, 'born'

    def __del__(self):
        print self.id, 'died'

def main():
    foo = FooClass(1)
    foo = None
    foo = FooClass(2)

if __name__ == '__main__':
    main()
```

I never actually learned properly how to program in python, so I don't know if it's bad practice, but it seems to work here. You can just call source_remove in there I guess.

**Comment by marianoguerra** [comment]
On Sun, Jun 5, 2011 at 10:47 PM, Sbte
reply@reply.github.com
wrote:

> Maybe you could add a destructor? Seems to work here
> 
> ```
> #!/usr/bin/env python
> 
> class FooClass(object):
>    def __init__(self, id):
>        self.id = id
>        print self.id, 'born'
> 
>    def __del__(self):
>        print self.id, 'died'
> 
> def main():
>    foo = FooClass(1)
>    foo = None
>    foo = FooClass(2)
> 
> if __name__ == '__main__':
>    main()
> ```
> 
> I never actually learned properly how to program in python, so I don't know if it's bad practice, but it seems to work here. You can just call source_remove in there I guess.

the thing is that if there is still a reference somewhere the signal
wont be removed and we will still have the bug.

also, if for some reason the garbage collector takes some time to run
we will get some more calls to the signal

**Comment by arielj** [comment]
I like the idea of moving it outside, the extension class should know what to do when a new extension is selected on preferences.

But what about extensions that are already instantiated and in use? like... we change adium output to text output with a window opened? we can't just destroy or unload it, we should use some signal/something to inform that an extension was changed and the class that uses it should do something... like... "extensions.on_listen_to_changed" and the music plugin should observe that signal and remove the old extension before using the new one. What do you think?

**Comment by marianoguerra** [comment]
On Mon, Jun 6, 2011 at 12:26 AM, arielj
reply@reply.github.com
wrote:

> I like the idea of moving it outside, the extension class should know what to do when a new extension is selected on preferences.
> 
> But what about extensions that are already instantiated and in use? like... we change adium output to text output with a window opened? we can't just destroy or unload it, we should use some signal/something to inform that an extension was changed and the class that uses it should do something... like... "extensions.on_listen_to_changed" and the music plugin should observe that signal and remove the old extension before using the new one. What do you think?

the current instances of an extension should disconnect the signals
when they are no longer needed (when the conversation is closed) as
usual.

**Comment by arielj** [comment]
What I mean is... the extensions class shouldn't handle the unload of an extension, because the extension may be in use, I think that the extensions class should inform that an extension was changed to all the objects that uses that extension and that object should be in charge of removing or deleting or disconnecting depending that object's need.

A conversation object shouldn't destroy an AdiumOutput extensions just because someone changed it, but the listen_to plugin should stop the timeout of the old extension or even destroy/delete the object. Maybe I'm not being clear in english :P.

Lo que quiero decir es que no debería ser la clase Extensions la que decida qué hacer con la extensión vieja, porque esa clase no sabe para que se usa una extensión, solamente sabe que otros objetos la usan, cada objeto sabe qué hacer con las extensiones desseleccionadas, la clase Extensions debería informar mediante una señal o algo que se cambió cierta extensión y cada objeto que le interese se debería conectar a esa señal para manejar los cambios.

Capaz estoy diciendo algo obvio y yo entendí mal, entendí como que la extensión misma o que la classe Extensios debería simplemente destruirla? eso es lo que me parece que no está "bien".

**Comment by marianoguerra** [comment]
On Mon, Jun 6, 2011 at 12:52 AM, arielj
reply@reply.github.com
wrote:

> What I mean is... the extensions class shouldn't handle the unload of an extension, because the extension may be in use, I think that the extensions class should inform that an extension was changed to all the objects that uses that extension and that object should be in charge of removing or deleting or disconnecting depending that object's need.
> 
> A conversation object shouldn't destroy an AdiumOutput extensions just because someone changed it, but the listen_to plugin should stop the timeout of the old extension or even destroy/delete the object. Maybe I'm not being clear in english :P.
> 
> Lo que quiero decir es que no debería ser la clase Extensions la que decida qué hacer con la extensión vieja, porque esa clase no sabe para que se usa una extensión, solamente sabe que otros objetos la usan, cada objeto sabe qué hacer con las extensiones desseleccionadas, la clase Extensions debería informar mediante una señal o algo que se cambió cierta extensión y cada objeto que le interese se debería conectar a esa señal para manejar los cambios.
> 
> Capaz estoy diciendo algo obvio y yo entendí mal, entendí como que la extensión misma o que la classe Extensios debería simplemente destruirla? eso es lo que me parece que no está "bien".

the idea of the on_unload call is to inform the extension that the
default extension for a given category changed, what the extension
does on the signal is up to them, it could change the extension on the
fly, or do nothing.

this would allow to update extensions without drawing the whole main
window again explicitly.

@arielj: I think we are saying the same :)

**Comment by c10ud** [comment]
guys, any news on this?

**Comment by c10ud** [comment]
ping @arielj

**Comment by arielj** [comment]
I don't have time to hack emesene, though it's still a bug, but it's hard. I don't know if we should close this, maybe some brave developer could try this... if it's closed noone will try

**Comment by c10ud** [comment]
Then the bug would be "add on_unload method in extensions" because
this timeout thing is not an everyday issue and atm only one extension
could cause eventual issues afaik?

2012/5/5 Ariel Juodziukynas
reply@reply.github.com:

**Comment by pepeleproso** [comment]
I'll will try to fix this when have enought time, so we can remove the redraw main window button
