### ISSUE TITLE
Make login mails case-insensitive

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#445]
This to make sure everything works correctly (hotmail utility) and to make sure you don't get a lot of duplicate folders in .config every time you use different upper case letters. This sounds quite trivial, but can probably break things. So I'm just filing this issue for now. We can fix this after 2.0.

**Comment by arielj** [comment]
this should be an easy fix, just change the text on the input field to lowercase

am I right, maybe i'm not understandig this, windows is case insensitive :P

**Comment by Sbte** [comment]
I think so, but I'm just worried that it will break things so soon before the release (things with case sensitivity in folders on linux).

**Comment by arielj** [comment]
shouldn't we fix this before 2.0 release? so we don't have folders with mixed case for the next release

if we don't fix this, next we'll need to change the strings to lowercase AND check the case of the folder already created, just a tought, so we have less work later

what do you think? a quick milestone?

**Comment by Sbte** [comment]
Probably a good idea then, yes. We could always revert things. If someone doesn't do it before this afternoon, I'll do it.

**Comment by c10ud** [comment]
did you actually try this? i mean, connecting with uppercased stuff and seen new dirs etc.? if it happens, a .lowercase() or similar won't hurt -- today i'd like to release though, but that modification is ok
