### ISSUE TITLE
The status should be set to "away" automaticly

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#446]
While this used to be a plugin for emesene1, this feature doesn't seem to be avilable anymore in emesene2.
Having this implemented in the actual software instead of a third party plugin would be nice, when you realize that's it's been part of MSN Vanilla forever and that even on a clean install, the plug-in screen is kinda bloated.

Suggestions:
Set a checkbox in the Desktop Integration tab under the Preferences menu: "Set status to away after X minutes"
Set a sub-checkbox to the previous one: "Rely on screen-saver activity" that would override (gray out) the X field.
The screensaver activity would probably be determined by sending prompts every 5 or 10 seconds to either xscreensaver or gscreensaver's daemon.
The time-out setting would probably do the same with... whatever daemon tracks the activity of the mouse and keyboard

Edited by: Arielj, Reason: Change title

**Comment by arielj** [comment]
you can't depend on xscreensaver or gscreensaver, the best way is to use XLib (like the emesene1's plugin), because not every system has gscreensaver (kde, englightenment, what do they use?). We should haver XLib as the default method for unix and the screensaver method as a fallback in case the user doesn't want to install that library, and after that, gtk's own mouse and keyboard movement events as another fallback on systems that don't have a supported screensaver.

Windows support is a lot easier, Windows saves the time of the last mouse/keyboard event, so we just need to calculate the difference.

Use emesene1's plugin as a reference.

**Comment by sm-Fifteen** [comment]
Humm...
That would be a nice thing to integrate in linux too (the time recoreder thingy). Of course, that should be done upstream, but...
Do you think this is the kind of thing that could be integrated in Xorg, or if it should be included in a separate extension instead? Maybe in Wayland?

As of the diversity of screensaver systems, would it really be this hard to probe for, say, the 5 most popular systems out there during launch, and if one of them is active, monitor it? (And if two or more are active, print an error and fall back on Xlib)

**Comment by c10ud** [comment]
as soon as there's an extension or a plugin for this, everyone can add his/her favourite os

**Comment by pengshao** [comment]
After a while emesene2 indicates that my status is still available, but from other clients like MSN messenger in Windows, my status is "offline" ... wish this can be implemented as soon as possible:)

**Comment by c10ud** [comment]
@shallpion the issue you're referring to, it's related to the
python-papyon package (if you're using ubuntu, just enable the
natty-proposed repository or use our stable ppa and it will be gone)
https://launchpad.net/~emesene-team/+archive/emesene-stable

2011/5/4 shallpion
reply@reply.github.com:

**Comment by pengshao** [comment]
@c10ud thanks for the advice, I am using gentoo :( did you mean that I need a patched python-papyon? My current version of papyon is 0.5.4 on my machine. Thanks

**Comment by c10ud** [comment]
you must use 0.5.5 with a patch: https://bugs.launchpad.net/ubuntu/natty/+source/papyon/+bug/768974

**Comment by pengshao** [comment]
@c10ue Thanks :) I will try to report this to gentoo maintainer to apply this patch in future.

**Comment by arielj** [comment]
There's a base plugin for this feature on the plugin's repo, someone should implement the detection of screensavers on linux. I'm closing this, maybe you can reopen this on the plugins repo.
