### ISSUE TITLE
Window size should not be remembered if closed while maximized

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#448]
When I maximize a conversation window and close it, it remembers the size of the maximized window, which can be quite annoying sometimes when opening a conversation and having a big window take up the entire screen. It should remember the size of the window when not maximized or at least not remember the size if it was closed while maximized and revert to the size of previous sessions.

**Comment by ghost** [comment]
This is the same as #406, but I couldn't figure out what was causing it at the time.

**Comment by arielj** [comment]
I think I had to do something about it for emesene1.

We can ask the gtk.Window's internal gdk.Window about it's state (http://www.moeraki.com/pygtkreference/pygtk2reference/class-gdkwindow.html#method-gdkwindow--get-state) and, if maximized, don't save the window's dimensions.

I'll do this when I get some free time if noone do it before (some free time may be next week or something like that... :P)

**Comment by Mystro256** [comment]
cool thanks for your help :)
