### ISSUE TITLE
_() function not defined

### ISSUE THREAD

**Issue by zodman** [emesene/emesene#449]
```
andres-vargas $  python 
Python 2.6.6 (r266:84292, Sep  2 2010, 12:58:15) 
[GCC 4.1.2 20070626 (rPath Inc.)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import e3.jabber  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e3/__init__.py", line 1, in <module>
    from base import *
  File "e3/base/__init__.py", line 24, in <module>
    from Worker import Worker
  File "e3/base/Worker.py", line 25, in <module>
    import Logger
  File "e3/base/Logger.py", line 26, in <module>
    import status as pstatus
  File "e3/base/status.py", line 25, in <module>
    STATUS[ONLINE] = _("Available")
NameError: name '_' is not defined
```

this happend and pass "inarvertido" because on https://github.com/emesene/emesene/blob/master/emesene/emesene.py#L64 to #89

Its better create a lambda for all _() functions

**Comment by arielj** [comment]
how are you running emesene? are you running python and then running the emesene file? it's not the right way, just execute the file (./emesene on a terminal) and it should run fine, the "_('text')" is not a function, it's the method used to translate strings

how are you running emesene? and what system are you using? what distro and version?

**Comment by c10ud** [comment]
also, i already seen this issue, it's been fixed a while ago

**Comment by c10ud** [comment]
closing, invalid.

**Comment by zodman** [comment]
agreed! close it
