### ISSUE TITLE
 Multiple avatar chooser window instances

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#45]
When i click in my avatar in the main window a avatar choose window its open, if click again in my avatar in the main window it open another avatar choose window. Its that ok?
I have multiple instances of avatar chooser window at same time.

**Comment by hit** [comment]
Fixed in main window, but not when you go to Actions -> Profile -> Change profile.

**Comment by marianoguerra** [comment]
made AvatarChooser ImageChooser Preferences and Profile modal dialogs

should be fixed

**Comment by hit** [comment]
Both fixed.

**Comment by andreskru** [comment]
Great!
