### ISSUE TITLE
The emesene1 syncronisation script erases emesene2 history

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#451]
Since that synchronization script have been pulled in the master branch, I keep getting synchronization prompts every time I fire up emesene. When I accept it, it just shows a progress bar at 0% saying "Synchronization successful" and next thing I know, my conversation history is now blank for all of my contacts.
So it looks like this part still needs a bit of improvement.

Expected behaviour:
-The progress bar should actually progress
-The script should be able to tell if the syncronisation was sucessful or not instead of tricking the user, and also print an error message if it's the case

On a side question, where does emesene2 stores it's conversations?
I once wanted to add sync emesene1 with emesene2 manually, but never figured out where emesene2 hides them.

**Comment by sm-Fifteen** [comment]
-The script should also make a back-up copy of the current history before trying to modify it, and revert it back upon failure

**Comment by astagi** [comment]
Sync does a backup copy :) conversation are stored in your_home/.config/emesene2/your_account/log ... What OS are you using?? Windows?? It's a strange behavior..

**Comment by c10ud** [comment]
i think you have an old tree, it works good here

**Comment by sm-Fifteen** [comment]
I'm running Linux Mint 10
Well, it happenned the 13th on april and the 25th of april respectively, both times with a fresh git build (I update on a regular basis, maybe once every 3 or 4 days)

**Comment by astagi** [comment]
Do you have some conversation logged in your emesene 1 db or only events??? Can you take a look??

**Comment by Sbte** [comment]
Riboshom, are you sure your database wasn't locked? I sometimes have an empty chat history too, but that's usually fixed by restarting emesene. Just throwing a random idea out there ;)

**Comment by sm-Fifteen** [comment]
The permissions for both base.db and base-db.journal are set to 644.
All of my logs are stored in /home/user/.config/emesene1.0/html_logs
What's odd is that there's also an empty log folder in the emesene1.0 folder...
Maybe that could be the cause?

**Comment by Sbte** [comment]
No, that's normal

**Comment by astagi** [comment]
html_logs?? I have no folder called html_logs in emesene 1 config...is that normal?

**Comment by sm-Fifteen** [comment]
I used the plug-in that came packaged with emesene 1.5, without further trying to configure it. I was also using the "last said" plug-in, it it changes anything.

**Comment by Sbte** [comment]
Just wondering, andrea, do you even check if the logger plugin was enabled in emesene1? Because I think that if it wasn't there won't be any logs. Maybe that breaks it.

**Comment by astagi** [comment]
Maby could be that... But no, I didn't know anything about that plugin, sorry, I supposed that all conversation was stored in the db... I'll fix soon..

**Comment by astagi** [comment]
Here again :) @Ribosohom retry now with emesene synch, maybe something is changed... I tried to do what you did, but for me all works well... If the emesene 1 conversation db exists, synch scripts starts and store all conversations in emesene2 db, otherwise if db is empty nothing is stored and synch ends successfully...in your case html_plugin is activated but emesene 1 db exists and can be fetched...

**Comment by sm-Fifteen** [comment]
Well, it did sync my emoticons and my avatars, but the history past october 2010 (when I started using emesene2) is still blank.
Is there anything I could send, a key file maybe, or a log?

**Comment by astagi** [comment]
Uhm, maybe it's the logger... No don't send me anything if db contains personal messages and contacts, better control by yourself... please do these steps:
1. install Sqliteman, is a graphic tool to see a db content...
2. Open with Sqliteman the file stored in tour_home/.config/emesene1.0/your_account/cache/your_account_db.db
3. In the table conversation_event you see all your conversation... If this table is empty maybe the logger doesn't work :|

Let me know ;)

**Comment by sm-Fifteen** [comment]
Well, conversations/events/ is effectively empty.
Actually, the DB is almost entierly empty, save for System_catalog/sqlite_master
That's really really weird.
BTW, it that might be useful, the structure of HTML log goes like this:

html_logs
\
-someone_irarely_chat_with@hotmail.com.html
-acciedentalgroupchatmember1@hotmail.com-acciedentalgroupchatmember2@hotmail.com.html
#movember 2012
-\
--chattinalldaylong@hotmail.com.html
--son@hotmail.com-father@hotmail.com-holyspirit@hotmail.com.html
%
#January 1970
-\
--chattinalldaylong@hotmail.com.html
--son@hotmail.com-father@hotmail.com-holyspirit@hotmail.com.html
%

Etcetera.

**Comment by c10ud** [comment]
i think andrea's extension only imports the conversations from the DB, not that custom plugin..

**Comment by c10ud** [comment]
also, i guess it would be just too much importing from that plugin also

**Comment by sm-Fifteen** [comment]
Well, it asked me to enable that custom plugin when I wanted to enable "last said", and I can't live without this feature, so...
Maybe it's a bit more mainstream than you think...

**Comment by c10ud** [comment]
maybe, but we cannot cover every user-made thing. maybe original authors will be able to contribute, or andrea will, meanwhile i'll consider this issue as closed.
