### ISSUE TITLE
Drag and drop doesn't initiate file transfer anymore

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#453]
Current behaviour:
-When dragging a file over emesene2's text input field,  the file's path is copied in it.

Expected behaviour
-Dragging a file over the chat window should initiate file transfer with the currently focused contact, and dragging the file over a tab should do the same with this other contact instead.

Edited by: Arielj, Reason: Change title

**Comment by c10ud** [comment]
regression? i don't think someone ever implemented this (yet)

**Comment by Sbte** [comment]
Regression from emesene 1 yes...

**Comment by Sbte** [comment]
Tried to implement this, but for some reason I can't get it to work on the input box. I can however get it to work on the output box or on the borders of the input box if I disable the input. Weird stuff...

**Comment by c10ud** [comment]
nenem started working on this https://github.com/nenemfromhell/emesene/commit/3c722861fe804751490bccd5a3947ec9aa147e32
