### ISSUE TITLE
Login to hotmail not working

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#456]
I have a hotmail account, and after the last commit, I failed to get into my hotmail account after clicking the icon.

Account: agostinho.carvalho@sapo.pt
pass: **********
thanks

**Comment by marianoguerra** [comment]
maybe because of the domain?

**Comment by zipatei** [comment]
I think this too ... but despite being @sapo.pt I get emails in hotmail account.

**Comment by Sbte** [comment]
I don't understand how that is possible :S

But it's the domain for sure.

**Comment by c10ud** [comment]
don't put your password on the internets!

also, i guess this is because of the restriction of mail stuff to hotmail-msn accounts. i guess a "check this account mail" option would be good (enabled by default when mail is recognized, disabled but with the option to enable elsewhere)

**Comment by astagi** [comment]
Yes it's the domain...we made a restriction in last commits... We should make something like c10ud says..

**Comment by zipatei** [comment]
I agree with the c10ud's idea.

In other accounts that are not recognized, besides the option of activating it, we could choose from Hotmail or POP account and choose the website by clicking on the icon of the email.

This would be something like a plugin for emesene 1, but working directly on the icon of the email.

Do not know if it's possible, but I think it is something useful for some users.

**Comment by astagi** [comment]
I'll work on ;)

**Comment by Sbte** [comment]
Andrea, just an idea, maybe you could also enable it if it's not in the list but still has more than 0 mails. That means it must actually be working right? :P

**Comment by astagi** [comment]
Yes, but this is not enough to say if his account works or not...he could have 0 unread mail and a non hotmail but working account...

**Comment by Sbte** [comment]
I know, but it helps ;)

That or you could just enable it for all accounts :P

**Comment by astagi** [comment]
Yep, I think that we should enable for all accounts too :) ... It's simpler... I haven't verified if you control that username is a mail yet, especially in dummy sessions, so you could movin' out the regular parsing... Rewind :P

**Comment by tsaimsbond** [comment]
For Windows users the issue is that the file "..hotmlog.htm" is missing!!! Entire "..\emesene2\data" folder is missing actually!! And i make 3 times clean install in Windows XP and 7.
Anyway i did download this "https://github.com/emesene/emesene/zipball/v2.11.7" and i manually copy-paste the missing folder!
Now it works fine!

Sorry for my English..i'm from Greece.

**Comment by c10ud** [comment]
thanks for noticing, i am currently not at home but if someone could notify the windows packager so we don't forget about this... :)

**Comment by ghost** [comment]
Ill take a look when I get a new pc.

**Comment by tsaimsbond** [comment]
I upgraded today in the latest version (2.11.11)...and the issue of  missing "..\emesene2\data" folder is still there...!!
See my first post.

**Comment by Sbte** [comment]
Please open a new issue. No one will see it here.
