### ISSUE TITLE
[Logger] Unable to open database file

### ISSUE THREAD

**Issue by hit** [emesene/emesene#46]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/hit/Apps/emesene2/emesene/e3/base/Logger.py", line 721, in run
    self.logger = Logger(self.path)
  File "/home/hit/Apps/emesene2/emesene/e3/base/Logger.py", line 281, in __init**
    self.connection = sqlite.connect(full_path)
OperationalError: unable to open database file

**Comment by marianoguerra** [comment]
can you put a "print full_path" before "self.connection = sqlite.connect(full_path)"

and give me a ls -l of the directory that contains the database and the database itself?

I need the permissions of both the directory and the database file (check if adding write permissions to both fix the problem)

to do it:
cd $HOME/.config/emesene2/[protocol]/[account]/log

(change [protocol]/[account] to the correct values)

ls -ld .

ls -l base.db

to test if the permissions fix the problem in the same directory do:

chmod u+w .
chmod u+w base.db

**Comment by hit** [comment]
Problem found. "log" wasn't a directory, but a plain file. So I removed it and created directory "log".

**Comment by marianoguerra** [comment]
that was a change that someone did to the configuration directory structure, it will happen only to users that tested emesene from some time ago.

I will close this bug since new users wont have this problem
