### ISSUE TITLE
My avatar not appear in conversation history

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#461]
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://img690.imageshack.us/i/capturaecra8d.png/'><img src='http://img690.imageshack.us/img690/1969/capturaecra8d.png' border='0'/></a>

Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

**Comment by Sbte** [comment]
Same as with the other bug I guess. Fix your profile. Preferences -> Live Messenger

**Comment by zipatei** [comment]
The account of my uncle hasn't broken the profile, and not appears own avatar.

**Comment by Sbte** [comment]
It has.

**Comment by zipatei** [comment]
Bug confirmed with profile fixed.

**Comment by Sbte** [comment]
I can't reproduce it here

**Comment by Sbte** [comment]
Fixed. Sorry for assuming it was your broken profile first. Thanks for reporting!

**Comment by zipatei** [comment]
No problem... thanks
