### ISSUE TITLE
Special smileys don't work

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#463]
Special smileys aren't working in emesene 2. Only see ugly box. please help me.

**Comment by Sbte** [comment]
What operating system do you use? For what smileys does it not work?

**Comment by Smile4ever** [comment]
Using bohdi with lxde. Ubuntu 10.04 based. I mean custom smileys that can be used with msn.---- On 28, Apr 2011 reply@reply.github.com wrote ----What operating system do you use? For what smileys does it not work? -- Reply to this email directly or view it on GitHub: https://github.com/emesene/emesene/issues/463#comment_1071334

**Comment by Sbte** [comment]
What exact version do you use? And what filetype for the smiley? Maybe you can give us a link to the smiley to test with?

**Comment by Smile4ever** [comment]
i'm using emesene 2.11.4 and you can make a emoticon from this one: http://i53.tinypic.com/1esvus.png

it's PNG :)
greetz,
geoffrey

---- Aan Fri, 29 Apr 2011 21:45:54 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

What exact version do you use? And what filetype for the smiley? Maybe you can give us a link to the smiley to test with? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1076932

**Comment by Sbte** [comment]
It works fine here. Maybe there's an error message if you run it from a terminal? Also, does it happen if you receive or send?

**Comment by Sbte** [comment]
Also, are you using Output Text of Adium?

**Comment by c10ud** [comment]
maybe lxwhatever doesn't have python-webkit by default, try installing it

**Comment by Smile4ever** [comment]
What do you mean with Output text of adium? 

---- Aan Sun, 01 May 2011 12:32:41 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

Also, are you using Output Text of Adium? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1082949

**Comment by pjalegria** [comment]
Lubuntu 11.04, i can have tray icon, just a ugly box, someone help me please

**Comment by Sbte** [comment]
Preferences->Extensions->conversation output. It either says Adium Output or Output Text. Adium Output is better.

But do you have python-webkit installed?

**Comment by Smile4ever** [comment]
just a crash:
40) papyon.protocol.switchboard_manager:Requesting switchboard for participant(s) matthijs_KM@hotmail.com
(11:11:40) papyon.protocol.switchboard_manager:Requesting new switchboard
(11:11:40) papyon.transport:&gt;&gt;&gt; XFR 20 SB
(11:11:40) papyon.transport:&lt;&lt;&lt; XFR 20 SB 64.4.61.110:1863 CKI 924023575.140242124.23015820 U messenger.msn.com 1
(11:11:40) papyon.protocol.switchboard:New switchboard session 924023575.140242124.23015820
(11:11:40) papyon.transport:&lt;-&gt; Connecting to 64.4.61.110:1863
(11:11:40) papyon.transport:&gt;&gt;&gt; USR 0 iamking@hotmail.be;{e655213e-f4a9-4d23-8ff7-00f2189ec04f} 924023575.140242124.23015820
(11:11:41) papyon.transport:&lt;&lt;&lt; USR 0 OK iamking@hotmail.be;{e655213e-f4a9-4d23-8ff7-00f2189ec04f} iamking@hotmail.be
(11:11:41) papyon.protocol.switchboard_manager:Handler &lt;SwitchboardP2PTransport peer="matthijs_KM@hotmail.com" guid="71a37443-5648-40ac-ae36-e131dc299ece"&gt; attached to switchboard 924023575.140242124.23015820
(11:11:41) papyon.transport:&gt;&gt;&gt; CAL 1 iamking@hotmail.be
(11:11:41) papyon.transport:&gt;&gt;&gt; CAL 2 matthijs_KM@hotmail.com
(11:11:51) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:11:51) papyon.protocol.switchboard:Leaving switchboard 1258163659.107158241.117114203
(11:11:51) papyon.transport:&gt;&gt;&gt; OUT 7
(11:11:51) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:11:51) papyon.protocol.switchboard:Leaving switchboard 749657661.16177106.3414689
(11:11:51) papyon.transport:&gt;&gt;&gt; OUT 8
(11:11:51) papyon.transport:&lt;&lt;&lt; CAL 1 RINGING 924023575
(11:11:51) papyon.transport:&lt;&lt;&lt; JOI iamking@hotmail.be iamking@hotmail.be 2754609424:2550273072
(11:11:51) papyon.transport:&lt;&lt;&lt; CAL 2 RINGING 924023575
(11:11:51) papyon.transport:&lt;&lt;&lt; JOI matthijs_km@hotmail.com;{71a37443-5648-40ac-ae36-e131dc299ece} Matthijs 2788999484:2550273072
(11:11:51) papyon.transport:&lt;&lt;&lt; JOI matthijs_km@hotmail.com Matthijs 2788999484:2550273072
(11:11:51) papylib.Events:Contact's client capabilities changed: &lt;papyon.Contact id='0bdbc87e-e7d2-4020-8d78-be8fe74aeaad' network='1' account='matthijs_KM@hotmail.com' memberships='FORWARD | ALLOW'&gt;
(11:11:51) papyon.transport:&gt;&gt;&gt; MSG 3 D 251 
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    P2P-Src: 'iamking@hotmail.be;{e655213e-f4a9-4d23-8ff7-00f2189ec04f}'\r\n
    P2P-Dest: 'matthijs_KM@hotmail.com;{71a37443-5648-40ac-ae36-e131dc299ece}'\r\n
    [P2P message (852 bytes)](11:11:51) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardConversation participants="jana_gortz41@live.nl"&gt;
(11:11:51) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardConversation participants="jana_gortz41@live.nl"&gt;
(11:11:51) papyon.protocol.switchboard:Disconnected (1258163659.107158241.117114203)
(11:11:51) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="marieke__horseslover@live.nl" guid="bd09ab05-22f7-4b6e-9eaa-e8bc16c806a7"&gt;
(11:11:51) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="marieke__horseslover@live.nl" guid="bd09ab05-22f7-4b6e-9eaa-e8bc16c806a7"&gt;
(11:11:51) papyon.protocol.switchboard:Disconnected (749657661.16177106.3414689)
(11:11:51) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="emily.schilperoort@xs4all.nl" guid="8489434c-2a95-43a2-9b39-2aebf9d06f93"&gt;
(11:11:51) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="emily.schilperoort@xs4all.nl" guid="8489434c-2a95-43a2-9b39-2aebf9d06f93"&gt;
(11:11:51) papyon.transport:&lt;&lt;&lt; NAK 3
(11:11:51) papyon.msnp2p.transport.switchboard:Received error: 1 (type=4)
(11:11:51) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="matthijs_KM@hotmail.com" guid="71a37443-5648-40ac-ae36-e131dc299ece"&gt;
(11:11:51) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="matthijs_KM@hotmail.com" guid="71a37443-5648-40ac-ae36-e131dc299ece"&gt;
(11:11:51) papyon.protocol.switchboard:Leaving switchboard 924023575.140242124.23015820
(11:11:51) papyon.transport:&gt;&gt;&gt; OUT 4
(11:11:52) papyon.protocol.switchboard:Disconnected (924023575.140242124.23015820)
(11:11:53) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:11:53) papyon.protocol.switchboard:Leaving switchboard 977179716.20217740.1617634
(11:11:53) papyon.transport:&gt;&gt;&gt; OUT 7
(11:11:53) papyon.protocol.switchboard:Disconnected (977179716.20217740.1617634)
(11:11:53) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="babygirl_stefanie_123@hotmail.com" guid="54579bb9-6f70-40f9-8241-b65c45133403"&gt;
(11:11:53) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="babygirl_stefanie_123@hotmail.com" guid="54579bb9-6f70-40f9-8241-b65c45133403"&gt;
(11:11:56) papyon.protocol.switchboard_manager:Requesting switchboard for participant(s) jana_gortz41@live.nl
(11:11:56) papyon.protocol.switchboard_manager:Requesting new switchboard
(11:11:56) papyon.transport:&gt;&gt;&gt; XFR 21 SB
(11:11:57) papyon.transport:&lt;&lt;&lt; XFR 21 SB 207.46.124.143:1863 CKI 23761493.11250175.2095210 U messenger.msn.com 1
(11:11:57) papyon.protocol.switchboard:New switchboard session 23761493.11250175.2095210
(11:11:57) papyon.transport:&lt;-&gt; Connecting to 207.46.124.143:1863
(11:11:57) papyon.transport:&gt;&gt;&gt; USR 0 iamking@hotmail.be;{e655213e-f4a9-4d23-8ff7-00f2189ec04f} 23761493.11250175.2095210
(11:11:57) papyon.transport:&lt;&lt;&lt; USR 0 OK iamking@hotmail.be;{e655213e-f4a9-4d23-8ff7-00f2189ec04f} iamking@hotmail.be
(11:11:57) papyon.protocol.switchboard_manager:Handler &lt;SwitchboardConversation participants="jana_gortz41@live.nl"&gt; attached to switchboard 23761493.11250175.2095210
(11:11:57) papyon.transport:&gt;&gt;&gt; CAL 1 iamking@hotmail.be
(11:11:57) papyon.transport:&gt;&gt;&gt; CAL 2 jana_gortz41@live.nl
(11:11:57) papyon.transport:&lt;&lt;&lt; CAL 1 RINGING 23761493
(11:11:57) papyon.transport:&lt;&lt;&lt; JOI iamking@hotmail.be iamking@hotmail.be 2754609424:2550273072
(11:11:57) papyon.transport:&lt;&lt;&lt; CAL 2 RINGING 23761493
(11:11:58) papyon.transport:&lt;&lt;&lt; JOI jana_gortz41@live.nl;{f552d7cd-afeb-4773-94b2-65350b660c88} Janaaa%20' 2789003564:2550273072
(11:11:58) papyon.transport:&lt;&lt;&lt; JOI jana_gortz41@live.nl Janaaa%20' 2789003564:2550273072
(11:11:58) papylib.Events:Contact's client capabilities changed: &lt;papyon.Contact id='1363c6ac-00e9-4bac-a695-3f3de03978e8' network='1' account='jana_gortz41@live.nl' memberships='FORWARD | ALLOW'&gt;
(11:11:58) papyon.transport:&gt;&gt;&gt; MSG 3 N 146 
    X-MMS-IM-Format: 'FN=Sans; EF=; CO=000000; CS=1; PF=00'\r\n
    Content-Type: 'text/plain; charset=utf-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    hoi :p
(11:12:02) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 118 
    TypingUser: 'jana_gortz41@live.nl'\r\n
    Content-Type: 'text/x-msmsgscontrol'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    \r\n
(11:12:03) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:12:03) papyon.protocol.switchboard:Leaving switchboard 1065827137
(11:12:03) papyon.transport:&gt;&gt;&gt; OUT 3
(11:12:03) papyon.protocol.switchboard:Disconnected (1065827137)
(11:12:03) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="xniemand@hotmail.com" guid="83842413-2905-4728-86d9-01c5c2c5fbba"&gt;
(11:12:03) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="xniemand@hotmail.com" guid="83842413-2905-4728-86d9-01c5c2c5fbba"&gt;
(11:12:04) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 206 
    Content-Type: 'text/x-mms-emoticon'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    ;f    &lt;msnobj Creator="jana_gortz41@live.nl" Type="2" SHA1D="TDvJ4J//FJF+Zf87C8m9laNyGEE=" Size="773" Location="0" Friendly="OwBGAAAA"/&gt;
(11:12:04) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 157 
    X-MMS-IM-Format: 'FN=Century%20Gothic; EF=; CO=d; CS=0; PF=22'\r\n
    Content-Type: 'text/plain; charset=UTF-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    haaaaay ;f
(11:12:06) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:12:06) papyon.protocol.switchboard:Leaving switchboard 2058430310.320170.1624960
(11:12:06) papyon.transport:&gt;&gt;&gt; OUT 7
(11:12:06) papyon.protocol.switchboard:Disconnected (2058430310.320170.1624960)
(11:12:06) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="pleun-amiabel@hotmail.com" guid="7842ef71-9d36-482e-9229-a84f934fd4e9"&gt;
(11:12:06) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="pleun-amiabel@hotmail.com" guid="7842ef71-9d36-482e-9229-a84f934fd4e9"&gt;
(11:12:08) papyon.transport:&gt;&gt;&gt; MSG 4 N 173 
    X-MMS-IM-Format: 'FN=Sans; EF=; CO=000000; CS=1; PF=00'\r\n
    Content-Type: 'text/plain; charset=utf-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    geef eens een speciale smiley? :p
(11:12:13) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:12:13) papyon.protocol.switchboard:Leaving switchboard 1106607346.2357319.229189187
(11:12:13) papyon.transport:&gt;&gt;&gt; OUT 6
(11:12:13) papyon.protocol.switchboard:Disconnected (1106607346.2357319.229189187)
(11:12:13) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="xniemand@hotmail.com" guid="83842413-2905-4728-86d9-01c5c2c5fbba"&gt;
(11:12:13) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="xniemand@hotmail.com" guid="83842413-2905-4728-86d9-01c5c2c5fbba"&gt;
(11:12:15) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 118 
    TypingUser: 'jana_gortz41@live.nl'\r\n
    Content-Type: 'text/x-msmsgscontrol'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    \r\n
(11:12:15) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 216 
    Content-Type: 'text/x-mms-animemoticon'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    ;::    &lt;msnobj Creator="jana_gortz41@live.nl" Type="2" SHA1D="yzWkNl1ZbVZZqLSgfoYSN7N7O4k=" Size="1727" Location="0" Friendly="OwA6ADoAAAA="/&gt;
(11:12:16) papyon.transport:&lt;&lt;&lt; MSG jana_gortz41@live.nl Janaaa%20' 150 
    X-MMS-IM-Format: 'FN=Century%20Gothic; EF=; CO=d; CS=0; PF=22'\r\n
    Content-Type: 'text/plain; charset=UTF-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    ;::
(11:12:20) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:12:20) papyon.protocol.switchboard:Leaving switchboard 1469845657.2231159.204241247
(11:12:20) papyon.transport:&gt;&gt;&gt; OUT 7
(11:12:20) papyon.protocol.switchboard:Switchboard timed out. Going to leave it.
(11:12:20) papyon.protocol.switchboard:Leaving switchboard 1868548281.189204154.174239147
(11:12:20) papyon.transport:&gt;&gt;&gt; OUT 5
(11:12:20) papyon.protocol.switchboard:Disconnected (1868548281.189204154.174239147)
(11:12:20) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="sambux@hotmail.com" guid="8983f291-de5e-48ba-9f1f-84938fc05125"&gt;
(11:12:20) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="sambux@hotmail.com" guid="8983f291-de5e-48ba-9f1f-84938fc05125"&gt;
(11:12:20) papyon.protocol.switchboard:Disconnected (1469845657.2231159.204241247)
(11:12:20) papyon.protocol.switchboard_manager:Closing switchboard handler &lt;SwitchboardP2PTransport peer="vanbogaertlaura@hotmail.com" guid="8e515b6c-f886-49ed-ba6a-aa1c6319a74b"&gt;
(11:12:20) papyon.msnp2p.transport:Unregistering transport &lt;SwitchboardP2PTransport peer="vanbogaertlaura@hotmail.com" guid="8e515b6c-f886-49ed-ba6a-aa1c6319a74b"&gt;

emoticons are different when i take fresh emesene install. (but they don't show..) 

what to do? 

---- Aan Sun, 01 May 2011 13:01:43 +0200 c10ud &lt;reply@reply.github.com&gt; schreef ---- 

maybe lxwhatever doesn't have python-webkit by default, try installing it 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1082990

**Comment by Smile4ever** [comment]
it happens when i recieve it and when i send it.
---- Aan Sun, 01 May 2011 12:23:43 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

It works fine here. Maybe there's an error message if you run it from a terminal? Also, does it happen if you receive or send? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1082937

**Comment by Smile4ever** [comment]
python-webkit installed

---- Aan Sun, 01 May 2011 13:16:04 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

Preferences-&gt;Extensions-&gt;conversation output. It either says Adium Output or Output Text. Adium Output is better. 

But do you have python-webkit installed? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083018

**Comment by Smile4ever** [comment]
adium output is on

---- Aan Sun, 01 May 2011 13:16:04 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

Preferences-&gt;Extensions-&gt;conversation output. It either says Adium Output or Output Text. Adium Output is better. 

But do you have python-webkit installed? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083018

**Comment by Smile4ever** [comment]
king@king-desktop:~$ emesene
/usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha,base64,random,dispatcher,re
/usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
No handlers could be found for logger "gui.gtkui.Indicator"
[13:32:36 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[13:32:36 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[13:32:36 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[13:32:36 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[13:32:37 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from blufiles.storage.msn.com:80
[13:32:38 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from blufiles.storage.msn.com:80
[13:32:38 ERROR papyon.service.content_roaming] Content Roaming service got error: HTTP Error (404): Not Found
[13:32:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

i see the smileys now, but i can't add them and they disappear when i double click on it.

---- Aan Sun, 01 May 2011 13:16:04 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

Preferences-&gt;Extensions-&gt;conversation output. It either says Adium Output or Output Text. Adium Output is better. 

But do you have python-webkit installed? 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083018

**Comment by Sbte** [comment]
What did you do to fix it? The other bugs are #466 and #476

**Comment by Smile4ever** [comment]
i've just restarted emesene (two times the same smiley tested)i tried it with the upgraded copy and there it also works. but you have to first give the smiley to emesene, quit and then restart emesene. you see them the second time someone use the smiley.

---- Aan Sun, 01 May 2011 14:43:41 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

What did you do to fix it? The other bugs are #466 and #476 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083155

**Comment by c10ud** [comment]
the smilies disappearing are an adium "feature" to see the underlying
text. we still have to implement stealing custom emoticons from other
contacts

2011/5/1 kingsmile
reply@reply.github.com:

**Comment by Smile4ever** [comment]
okay. you can't take a screenshot for smileys? or screenshots over a time of 10s and then merge it in a gif or png and automatically make a emoticon of it?

---- Aan Sun, 01 May 2011 18:30:51 +0200 c10ud &lt;reply@reply.github.com&gt; schreef ---- 

the smilies disappearing are an adium "feature" to see the underlying 
text. we still have to implement stealing custom emoticons from other 
contacts 

2011/5/1 kingsmile 
&lt;reply@reply.github.com&gt;: 
&gt; i've just restarted emesene (two times the same smiley tested)i tried it with the upgraded copy and there it also works. but you have to first give the smiley to emesene, quit and then restart emesene. you see them the second time someone use the smiley. 
&gt; 
&gt; ---- Aan Sun, 01 May 2011 14:43:41 +0200 Sbte &amp;lt;reply@reply.github.com&amp;gt; schreef ---- 
&gt; 
&gt; 
&gt; What did you do to fix it? The other bugs are #466 and #476 
&gt; 
&gt; -- 
&gt; Reply to this email directly or view it on GitHub: 
&gt; https://github.com/emesene/emesene/issues/463#comment_1083155 
&gt; 
&gt; -- 
&gt; Reply to this email directly or view it on GitHub: 
&gt; https://github.com/emesene/emesene/issues/463#comment_1083369 
&gt; 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083596

**Comment by c10ud** [comment]
no, we need a proper solution like we had in emesene1, but noone coded that yet

**Comment by Smile4ever** [comment]
can you port it from emesene 1.6.3? it's important for me.

---- Aan Sun, 01 May 2011 18:36:34 +0200 c10ud &lt;reply@reply.github.com&gt; schreef ---- 

no, we need a proper solution like we had in emesene1, but noone coded that yet 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083606

**Comment by c10ud** [comment]
no, because the text output widget is entirely different, it must be rewritten

**Comment by Smile4ever** [comment]
when it will happen?

---- Aan Sun, 01 May 2011 18:39:56 +0200 c10ud &lt;reply@reply.github.com&gt; schreef ---- 

no, because the text output widget is entirely different, it must be rewritten 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083614

**Comment by c10ud** [comment]
i don't know, when it happens you'll surely notice the change, but i guess it won't happen anytime soon

**Comment by c10ud** [comment]
unless ofcourse someone is willing to take the job

**Comment by Smile4ever** [comment]
then i'll downgrade to 1.6.3

---- Aan Sun, 01 May 2011 18:42:57 +0200 c10ud &lt;reply@reply.github.com&gt; schreef ---- 

i don't know, when it happens you'll surely notice the change, but i guess it won't happen anytime soon 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1083620

**Comment by Sbte** [comment]
arielj seems to be working on it. Just letting you know.

**Comment by Smile4ever** [comment]
nice! :D

---- Aan Sun, 01 May 2011 23:26:07 +0200 Sbte &lt;reply@reply.github.com&gt; schreef ---- 

arielj seems to be working on it. Just letting you know. 

## 

Reply to this email directly or view it on GitHub: 
https://github.com/emesene/emesene/issues/463#comment_1084340
