### ISSUE TITLE
No way to restore GUI after minimize on KDE 

### ISSUE THREAD

**Issue by nxgtrturbo** [emesene/emesene#465]
When clicking the upper right button [X], the default behavior is to minimize the app, which works good, but theres no way to bring back the app since there is no tray icon or task-bar tab to show again the GUI.

Workaround: kill the process, re-open the app.

emesene 2.11.4
kde 4.6.2
distro Kubuntu 11.04 AMD64

**Comment by el-dias** [comment]
I don't find option to activate tray icon, only indicator-applet is avaliable. This case, I will have problems to use emesene2 in LXDE =(

**Comment by Sbte** [comment]
It's sitting in the memenu. And the tray icon preferences are broken as reported by me in #340. I suppose Kubuntu has the memenu too?

**Comment by c10ud** [comment]
if you use ubuntu, you don't see any tray icon or indicator because
emesene uses the Messaging Menu. if you want to bring it back, just
click the corresponding entry in the Messaging Menu (i don't have
11.04 but i think it works like this)

2011/4/29 nxgtrturbo
reply@reply.github.com:

**Comment by Mystro256** [comment]
This seems like a glitch because I don't think Kubuntu has a messaging menu, to my knowledge only the gnome/unity version of Ubuntu has it, i.e. not Kubuntu, Xubuntu or Lubuntu. Maybe adding an option to use the classic notification area icon instead would be a good idea?

**Comment by Sbte** [comment]
There is one, see #340.

But the memenu extension shouldn't be loaded if the memenu is not present. I don't quite understand what's going on here.

EDIT: Looked at some Kubuntu screenshots and saw a white envelope in the right bottom of the screen. If that's not a memenu, then what is it?

**Comment by Mystro256** [comment]
It doesn't seem to make sense but this could be a Ubuntu/Kubuntu bug. In that case the only way around that is to fix the tray icon preference :/

**Comment by c10ud** [comment]
the only bug we have is that the "trayicon" extension preference isn't working because we should move it to the "global" config.

other than that, people who use ubuntu and like the messaging menu should get used to this stuff, we made it for better integration, this ain't no bug.

**Comment by Mystro256** [comment]
there's a messaging menu on kubuntu?

**Comment by c10ud** [comment]
https://wiki.kubuntu.org/Kubuntu/Specs/LucidAyatanaIntegration

**Comment by Mystro256** [comment]
Oh really? I didn't know about that, thanks cl0ud!
