### ISSUE TITLE
[Regression]Toggling smileys between text and image mode is broken

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#466]
I've been observing this in my build from yesterday, you can turn a smiley to text by clicking on it, but reclicking turns it into a broken link (missing file/picture icon displayed).

I've just updated and it haven't changed.

**Comment by c10ud** [comment]
i _think_ it's an issue in adium themes, i once read about it :s not
100% sure though

2011/4/29 Riboshom
reply@reply.github.com:

**Comment by pepeleproso** [comment]
There's a comment about that in adium sources

**Comment by Sbte** [comment]
6ca18e1ae0923ec8298bbe0bc2a145a7f84d53a1 is the first bad commit
commit 6ca18e1ae0923ec8298bbe0bc2a145a7f84d53a1
Author: Jose Rostagno joserostagno@vijona.com.ar
Date:   Sun Apr 17 17:33:02 2011 -0300

```
Fix adium themes with custom Template.html
```

:040000 040000 2630ecc87e0c364b54cc876ffb45bc5e2def66cf 6c5e33f34c6a5f98cb8fce17f893b8b28e67d752 M  emesene

**Comment by Sbte** [comment]
@pepeleproso, you break a lot of things, sir :P

Could you try to fix it? :D

**Comment by Sbte** [comment]
Seems to be fixed by fec6ccd2c72cde6f8f19d8edb1cee7113c46483a

Thanks pepeleproso
