### ISSUE TITLE
problem with chats of Groups.im in Adium Output extension

### ISSUE THREAD

**Issue by el-dias** [emesene/emesene#467]
Hello!

I am a frequent user of chatgroups in Groups.im, but, I don't view the members' nickname when I use the Adium Output extension. Only with Output Text.

**Comment by Sbte** [comment]
I'm not sure what you mean :S

**Comment by c10ud** [comment]
i think groups.im stuff is some sort of a group chat except you're talking with a unique account. everytime someone speaks you receive a msg from that account, but with a different display name. i guess adium textoutput should check if nickname == last_nickname when appending a new consecutive received message other than mail

**Comment by el-dias** [comment]
I updated from the git, and the fix don't works for me =(

**Comment by c10ud** [comment]
how can i test it?

**Comment by pjalegria** [comment]
I have de same problem... dont work for me too

**Comment by c10ud** [comment]
how can i test it?

**Comment by pjalegria** [comment]
On emesene 1 there are a option "MSN Group support" that fix the problem, cant be implemented in emesene 2?

**Comment by c10ud** [comment]
reminder: when receiving a message, the contact display_name will remain the same, in order to support this it must be checked if the on_message_received supports the p4-context'd nickname and pass it to the e3.Message eventually (?) just throwing ideas

**Comment by el-dias** [comment]
=(

http://img819.imageshack.us/i/emesene2groupsimchatgro.jpg/

**Comment by c10ud** [comment]
http://img814.imageshack.us/img814/9118/screenshottdj.png

next time, upgrade and try

**Comment by pjalegria** [comment]
how can i upgrade?

**Comment by Sbte** [comment]
http://blog.emesene.org/2010/10/instructions-for-testers.html

Or wait until the next release.

**Comment by pjalegria** [comment]
There are no PPA? :( ...i think im going to wait, anyway thanks

**Comment by Sbte** [comment]
There's a ppa here: https://launchpad.net/~emesene-team/+archive/emesene-stable

But it only contains the stable releases. A bug in launchpad prevents us from having a daily ppa.

**Comment by pjalegria** [comment]
Can it be upload to natty-proposed?

**Comment by Sbte** [comment]
That depends on the ubuntu devs. It'll be on the ppa (for sure) ;)
