### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#468]
When selecting the wrench and inputting proxy settings 'Host' and 'Port' and pressing OK.

The next time the wrench is selected the 'Server' and 'Port' settings is replaced by the input from 'Host' and 'Port' under proxy settings and the 'Host' and 'Port' are left blank.

I believe this is what is restricting me from connecting through a proxy.

**Comment by c10ud** [comment]
yes, we use the system proxy by default, noone had a proxy to test
that dialog, so it remained broken :(

2011/4/29 seedling11
reply@reply.github.com:

**Comment by ghost** [comment]
I am connected to the internet through a proxy server at my university. The previous version of emesene used to have proxy settings available, with a http method option similar to current proxy settings. The only difference is you were not able to specify the messenger server. That worked perfect for me

Currently however, even if I set up the proxy using the global proxy settings, and then ticking only http or both http and use proxy: it still doesn't connect. Any advice on this would be much appreciated.

**Comment by c10ud** [comment]
maybe i haven't been clear: current emesene proxy dialog does nothing,
it needs to be fixed and completed

however if your system has a proxy set at system level it should work

2011/4/29 seedling11
reply@reply.github.com:

**Comment by ghost** [comment]
I understand. Just letting you know that in my case the system level proxy does allow me to connect. Running Ubuntu 11.04.

I'll just wait until this gets fixed.
thanx

**Comment by c10ud** [comment]
closing but not fixed -- see #684
