### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by hit** [emesene/emesene#469]
Maybe also sync emoticons? Would be more useful than logs imho :p

**Comment by Sbte** [comment]
@4ndreaSt4gi, did you add a way yet so people who want this can just press sync without having their logs etc imported twice?

**Comment by astagi** [comment]
No I'm workin on it too... I should only set a config variable for every feature ( conversations, avatars, emoticons... )... At the moment the only way to duplicate items is deleting the configuration...
