### ISSUE TITLE
Avatar in the contact list has wrong size

### ISSUE THREAD

**Issue by bardok** [emesene/emesene#472]
Hello,

I changed the size (64 against 32)  of the avatar in the contact list but they are displayed with the old size.

In conversation it's ok.

Thks. Bardok

**Comment by Sbte** [comment]
Yes, I saw this a while ago. You can make them smaller but not larger.

**Comment by Sbte** [comment]
Fixed, but I still don't understand why there are two avatar renderers. One in Renderers.py and one in Avatar.py.
