### ISSUE TITLE
Speak into emesene

### ISSUE THREAD

**Issue by Haulier** [emesene/emesene#475]
Hello,

I have upgrade my ubuntu with 11.04
In this version i have emesene 2, all is good i can connect with my account but i can't speak with my contact and my cantact cant speak with me. I use a http method.

Thx 
Sorry for my english i 'm french

**Comment by arielj** [comment]
Can you run emesene on a terminal? maybe it's showing some error there

Also, check emesene menu, help > debug

**Comment by Haulier** [comment]
Hello thx for ur post.
I dont have try, but i have do some test.
I have try with another messenger, that work.
I speak on ubuntu forum and the problem is maybe with ubuntu some package exist with the old version 10.04 and i have install 11.04 without reinstall then now i try with the new install of ubuntu. If that work or not i come on here for reply.

Sorry again for my english

**Comment by c10ud** [comment]
feedback, or i'll close the issue
