### ISSUE TITLE
No way to save received custom emoticons by right clicking them

### ISSUE THREAD

**Issue by socar1106** [emesene/emesene#476]
Well... here I will tell you, no, I will try 'cause I don't dominate english.
On my ubuntu 11.04, my favorite MSN client, is emesene 2.0, great.
But, when a buddy send me some custom emoticons, I can't save this! D:
Why?!
When I press Right Button on my mouse, on the custom emoticon, just say: "Page 1", and, "Page 2", but "Add" doesn't appear. What's up with that? I will appreciate if you can help me, thank you.
Excuse me, for my mistakes on the languaje :P

**Comment by Sbte** [comment]
This is not implemented yet in emesene 2. So you'll just have to wait for someone to do it. Or do it yourself ;)

**Comment by socar1106** [comment]
Sbte... how I can do that? By myself?

**Comment by socar1106** [comment]
Oh, I think I already know how, thank you. Do you know when emesene will implement the custom emoticone's save?

**Comment by Sbte** [comment]
When it's done :P

Or you can of course try to implement it yourself. But for now I think you can use the cache and grab it from there.

**Comment by socar1106** [comment]
Oh thank you, am, can you tell me... where is the cache of emesene? :/

**Comment by Sbte** [comment]
~/.config/emesene2/protocol_type/email/contact/emoticons

**Comment by socar1106** [comment]
I tried, when you say ~, that's the place where I will put my user right?

**Comment by socar1106** [comment]
Thanks, I found it.

**Comment by arielj** [comment]
I'm working on this, just telling so nobody looses time doing this too :P

**Comment by sm-Fifteen** [comment]
@arielj
Don't forget to add copy and paste too!

**Comment by arielj** [comment]
We shouldn't paste in the output, and pasting is already possible on the input widget.

Copy was already implemented by webkit (I still need to find how to copy emoticon's shortcuts) but I was removed unintentionally I guess trying to remove unwanted items.
