### ISSUE TITLE
No way to disable the logger

### ISSUE THREAD

**Issue by moekad** [emesene/emesene#477]
hey,
Thanks for the New emesene i like it =)

my problem is not consider as an issue but how i can disable the Chat history?

I'm using ubuntu, i have installed it using the :apt-get install emesene seems they include it in the repository 

also i have a question, how i can import a plugin, when i click on Plugins there's no option to import!!

Thanks in advance

**Comment by c10ud** [comment]
there's no option to disable logging yet (afaik)
and there's no plugin to import, hence no import button :D

**Comment by arielj** [comment]
Should we make a "no log" logger extension? one that doesn't do anything, just blank methods (just the main method used to log doing nothing), that would disable the logger and it's a really easy task

**Comment by Sbte** [comment]
Yeah, just like the NoTrayIcon :D

**Comment by Sbte** [comment]
Anyway, it's probably not that easy. You'd need to have dummy functions for every function in logger. That it's only referenced directly in common.Worker and common.Session makes it easier though.

**Comment by c10ud** [comment]
nice idea, is anyone working on this already?

**Comment by Sbte** [comment]
If arielj isn't, then no I guess. I can probably do it if you want.

**Comment by c10ud** [comment]
i'm not at home, if you want to lose 10mins... :)

**Comment by arielj** [comment]
I'm not doing it, I'm not home until tomorrow.

Even if you have to make a dummy method of all methods, it's trivial, just copy the actual logger and remove the content of every method, change it's description and name and we are done, maybe the hardest part is to integrate this into the code (I think we are just importing the logger class instead of using an extension for it)

**Comment by Sbte** [comment]
I don't think I'll have enough time either. To do it, you'll need one class from which everything is loaded. Atm, there are also global functions like log_message. And at least LoggerProcess has to be made an extension. Maybe the global functions have to be put in there, then that class has to be made into an extension, and then you need to save the logger in your session, and use that from all of the workers.
