### ISSUE TITLE
"No Picture" button in Avatar Chooser not working

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#479]
Try:
1. Open Avatar Chooser
2, Click in "No Picture" button

Result: Avatar no change
Expect: Avatar change for none.

**Comment by Sbte** [comment]
It currently has the same action as clicking Cancel indeed.

**Comment by Sbte** [comment]
How it's currently implemented in papylib also makes it really hard to implement this, so I don't think I'll be able to do this.

**Comment by c10ud** [comment]
see #471
