### ISSUE TITLE
Login transition

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#48]
the small preference button disappearing causes a movement of the widgets when you click on connect. is this avoidable? gtk experts, it's up to YOU

**Comment by marianoguerra** [comment]
wow, if we are having this kind of bugs that means that e2 (short for emesene2, it's too long :D) is advancing

I like this kind of reports, they make e3 look polished even when you don't know why.

**Comment by arielj** [comment]
maybe we can just leave the preferences icon there without sensitivity

**Comment by c10ud** [comment]
i tried some solution with login widgets - maybe is a better option inheriting from unconnected window and modifying existing widgets? otherwise there's just a too big move imo -- gui changes just too much

**Comment by marianoguerra** [comment]
build some kind of spacer and put it along the preference button with the same size? I don't know how to do it, but I think it can be done

**Comment by c10ud** [comment]
i've put the button with the same alignment in a vbox and it moved, but, i was thinking if inheriting from "main login window" for "connecting login window" wasn't a good idea... i don't see much CONs...

**Comment by c10ud** [comment]
now connecting alignment inherits from login alignment. there's a small issue with widgets moving a bit when the throbber and connecting message appear (i vote for removing the connecting message, btw) other than that, it seems OK.

**Comment by marianoguerra** [comment]
+1 to remove the connecting label

**Comment by c10ud** [comment]
removed, now if only someone could fix the widgets moving around when the throbber is showed.........

**Comment by c10ud** [comment]
another TODO:
when autologin is enabled, fix this:
/home/riky/msn/emesene2/emesene/gui/gtkui/Window.py:55: GtkWarning: Attempting to add a widget with type GtkAlignment to a GtkWindow, but as a GtkBin subclass a GtkWindow can only contain one widget at a time; it already contains a widget of type GtkAlignment
  self.add(self.content)

**Comment by c10ud** [comment]
lfottaviano rocks and fixed this last issue!!!
