### ISSUE TITLE
No tray icon picture in Lubuntu

### ISSUE THREAD

**Issue by pjalegria** [emesene/emesene#480]
Hi

I am using Lubuntu 11.04 on my netbook after install Emesene 2 i dont have emesene tray icon, just the symbol of no picture!!! how can i fix that???

Thank you

**Comment by Sbte** [comment]
If you run it from terminal, what does it say?

**Comment by c10ud** [comment]
doesnt lubuntu make use of the messaging menu?

**Comment by pjalegria** [comment]
It says : No handlers could be found for logger "gui.gtkui.Indicator"

**Comment by Sbte** [comment]
lubuntu uses lxde right? Might be the same as #463 then.

**Comment by pjalegria** [comment]
I think not

**Comment by pjalegria** [comment]
lubuntu dont make use of the messaging menu

**Comment by pjalegria** [comment]
can someone help me, please

**Comment by Sbte** [comment]
do sudo apt-get install python-webkit. Does that help?

**Comment by pjalegria** [comment]
I already have installed python-webkit. still not working. I think i have to downgrade to emesene 1.6.3 :(

**Comment by pjalegria** [comment]
Problem solved :) ... sudo install indicator-applet 

Thanks anyway

**Comment by c10ud** [comment]
really strange though..
