### ISSUE TITLE
MSN group support

### ISSUE THREAD

**Issue by pjalegria** [emesene/emesene#481]
Does Emesene 2 have MSN support groups?

**Comment by Mystro256** [comment]
Do you mean contact groups? If so, it does. Does it not for you?

**Comment by pjalegria** [comment]
Im talking about IM groups, no it doesnt

**Comment by c10ud** [comment]
if you mean groups.im - alike, just update to current git and it will work

**Comment by pjalegria** [comment]
Not working again

**Comment by c10ud** [comment]
they work with emesene 2.11.5

**Comment by pjalegria** [comment]
they work, but now they stop working... im using 2.11.5 ;)
