### ISSUE TITLE
error applying preferences

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#484]
1- change adium theme
2- press apply button
3- open a conversation and you will get

  File "/home/pepe/emesene2/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/pepe/emesene2/emesene/e3/common/Signal.py", line 109, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

any ideas wellcome

**Comment by c10ud** [comment]
works here with latest git head, sure it's the way to reproduce it?

**Comment by pepeleproso** [comment]
Trying with fresh git, didn't show the error. It must be a problem in my tree, related to adium-variants changes. Sorry for noise.

**Comment by c10ud** [comment]
no probs
