### ISSUE TITLE
Changes name back to email address

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#486]
It seems when I log in using anything but emesene (such as pidgin, empathy, web messenger and even the emesene 2 on my fedora 15 install) and log back in via my ubuntu emesene, my display name is set to my email, rather than what I had it as before. I think it also happens randomly when I log in, but I can't confirm that.

**Comment by Sbte** [comment]
Fix your profile by following the instructions under Preferences->Live messenger in emesene2. And don't use emesene 1, or it will break again.

**Comment by Mystro256** [comment]
This only seems to explain how to fix the picture issue, not the nick issue :S, did I miss something?

**Comment by Sbte** [comment]
It fixes everything. Do it! ;)

**Comment by Mystro256** [comment]
Hmmm okay i'll give it a shot. I'll re-open this if the issue persists
