### ISSUE TITLE
Features: Add Group and Add alias in contact request

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#487]
Features are present in Emesene 1.6.3

Is possible portable to Emesene 2?

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://img714.imageshack.us/i/capturaecra1g.png/'><img src='http://img714.imageshack.us/img714/8846/capturaecra1g.png' border='0'/></a>

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://img405.imageshack.us/i/capturaecra2p.png/'><img src='http://img405.imageshack.us/img405/5720/capturaecra2p.png' border='0'/></a>

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://img198.imageshack.us/i/capturaecra3.png/'><img src='http://img198.imageshack.us/img198/9595/capturaecra3.png' border='0'/></a>

**Comment by c10ud** [comment]
~implemented, there's some bug though #543

**Comment by zipatei** [comment]
Add alias not implemented.

**Comment by c10ud** [comment]
Actions > Contact > Set alias

it's not the same i know, but i fear adding alias to a contact not-really-added-yet could require with current design too many nested callbacks (actually two, but they have to be checked in add-contact callback so..quite an hassle to code)
