### ISSUE TITLE
[Misc]Pronouncing "emesene"?

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#488]
(Allright, I know this should rather post that in the forums, but last time I checked, they'd been dead for 2 weeks. Please take this with a grain of salt, ok?)

I've remarked that no one in the emesene community really knows how to pronounce emesene, and that's a very serious bug since it confuses users about the identity of the software.

I've seen people calling it [imisin], [εmεsεn](same as MSN, leads to confusion) and even [œmœsœnœ], but nobody ever seemed to really know. Linux fixed that a long while ago, but what about us?
I've even stopped talking about emesene in public because I was too afraid of saying it the wrong way and mislead people.
We must come to agreement about the final and definitive, cross-language pronounciation of emesene.
This is a matter of life and death.

**Comment by ghost** [comment]
eMeSeNe = MSN

Im pretty sure at least.

**Comment by arielj** [comment]
Emesene is the spanish pronunciation of the letters "M" "S" and "N" joined and with duplicated removed

"M"=eme
"S"=ese
"N"=ene

Go here http://text-to-speech.imtranslator.net/, choose spanish and type emesene, then click on "Say it"

(Personally, I say it the way it sound if you type "émeséne", with those accentuations)

I guess, as Mariano is from Argentina (like me), this is the "right" way to pronounce it.

**Comment by marianoguerra** [comment]
yep, it's how msn is pronounced in spanish

**Comment by sm-Fifteen** [comment]
@Arielj
Allright, but wouldn't that lead people to mix up MSN and emesene?
And also, I'm personally French, and the pronounciation that came to mi mind when I saw the word [œmœsœnœ] is placeholder (type eumeuseuneu in your text2speech engine in french mode).

**Comment by marianoguerra** [comment]
this project started as a joke to my brother, a joke name was the right choise back then ;)

**Comment by c10ud** [comment]
i think this is quite a good pronunciation:
http://translate.google.it/?hl=it&tab=wT#es|it|emesene

2011/5/2 Riboshom
reply@reply.github.com:

**Comment by arielj** [comment]
Here, MSN sounds like "eme ese ene" (check that on the text to speech online app).

Anyway, most people will be confused if you tell them about Pidgin, Kmess or any other weird name if they never heard about that software, "emesene" (at least here) sound "familiar" and give people a clue about what's emesene about.

**Comment by marianoguerra** [comment]
On Mon, May 2, 2011 at 7:44 AM, arielj
reply@reply.github.com
wrote:

> Here, MSN sounds like "eme ese ene" (check that on the text to speech online app).
> 
> Anyway, most people will be confused if you tell them about Pidgin, Kmess or any other weird name if they never heard about that software, "emesene" (at least here) sound "familiar" and give people a clue about what's emesene about.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/488#comment_1087469
> 
> msn for linux?

emesene for linux?

the open source msn client?

the open source emesene client?

maybe if we add more context we can differentiate from the oficial client

**Comment by Sbte** [comment]
yeah, you could call it amsn....

emesene is good as it is ;)

**Comment by sm-Fifteen** [comment]
Allright, so...
arielj suggests [εmεsεn](Same pronounciation as MSN)
Cloud prefers [emesene](éméséné)
Mariano supports [εmεsεn](because that's the pronounciation he originally intended)
I'm personally in favour of a new pronounciation, so we can differentiate it from the Vanilla client

Maybe [emεsεn]? (émesen, no "e" at the end)
Btw, can you guys read phonetic writing? That would avoid a lot of anbiguity (in spanish, you may not use accents as we do in french, so my retranscription may sound different)

**Comment by marianoguerra** [comment]
On Mon, May 2, 2011 at 12:10 PM, Riboshom
reply@reply.github.com
wrote:

> Allright, so...
> arielj suggests [εmεsεn]  (Same pronounciation as MSN)
> Cloud prefers [emesene]  (éméséné)
> Mariano supports [εmεsεn]  (because that's the pronounciation he originally intended)
> I'm personally in favour of a new pronounciation, so we can differentiate it from the Vanilla client
> 
> Maybe [emεsεn]? (émesen, no "e" at the end)
> Btw, can you guys read phonetic writing? That would avoid a lot of anbiguity (in spanish, you may not use accents as we do in french, so my retranscription may sound different)

I suport emesene (with the last e explicit, it think in french it
would be éméséné), because that is how it sounds in spanish, and in
that way it distinguish itself in english from msn (not in spanish :P)

**Comment by sm-Fifteen** [comment]
Well, I kinda like pronouncing it like MSN (em es en) with an [e] at the beginning (émesen). Btw, trying that in a text2speech engine doesn't seem to work unfortunately (it says [emezεn]), but you get the idea.

**Comment by diega** [comment]
I would like to see in the about page a little play button with some of the developers pronouncing it well xD

**Comment by Mystro256** [comment]
I personally have always pronounced it em-meh-zen (almost with a french-ish accent from the back of the throat) when recommending it to others, for whatever reason lol :)

**Comment by sm-Fifteen** [comment]
arielj (Spanish) : [εmεsεn]
Mariano (Spanish) & Cloud (Italian) : [emesene]
Me (French) : [emεsεn]
Mystro (Unknown) : [εmεzεn]

Just as a guideline, so I can stop incorectly translate pronetic speech into "normal text":
[e] is the E from Emulator (In french, it's noted é)
[ε] it the E from problEm (a flat, normal e)

**Comment by arielj** [comment]
I'm from argentina like Mariano, so it's Spanish too, I pronounce this the same way as cloud's google-translate link.

**Comment by sm-Fifteen** [comment]
Why was the issue closed, we still haven't agreed on what the real pronounciation should be!
Sure, the "official" one may be [emesene], but it doesn't make sense for anyone that doesn't speak spanish.

**Comment by Sbte** [comment]
Well, it was probably closed to get all issues on one page again.

Now at the topic, everyone who's actively developing emesene seems to be in favor of [emesene], so yeah... I guess you can still pronounce it as whatever you like. Names rarely sound the same in every language. Even if people try to pronounce it right.
