### ISSUE TITLE
Audio/Video Call Button

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#490]
The Audio Video Chat button is the same as the Voice call button. Maybe overlaying the video call and voice call icons would be better? Like so:

<img src=http://i.imgur.com/8KWhi.png>

**Comment by astagi** [comment]
Nice for me :) You could make a pull request...

**Comment by Mystro256** [comment]
Well I was making sure it didn't look dumb ;)

I'll make a pull request when I have a moment

**Comment by rockybalboa** [comment]
Very nice icon. :)

other: Yesterday, I tried the Call function, but it isn't works with my webcam, any advice why it isn't?

**Comment by astagi** [comment]
@rockybalboa please open a new issue :)

**Comment by c10ud** [comment]
pulled

**Comment by c10ud** [comment]
p.s. no issues about webcam, only fixes/patches

**Comment by Mystro256** [comment]
thanks for the pull :)
