### ISSUE TITLE
Focus automatically changes on conversation window

### ISSUE THREAD

**Issue by Fabio-pereira** [emesene/emesene#493]
When in a tabbed conversation window, the focus on the text input box automatically changes to the tab which received the last message. This is annoying as you start writing a text on one tab (the person you want to talk to) and after a new message is received on another tab, the remaining text you enter is written on the other input text box (frequently you end up sending a message to the wrong person).

OS.: Ubuntu 11.04
Emesene: 2.11.4

**Comment by ricsipontaz** [comment]
Same here.

**Comment by rockybalboa** [comment]
Yes, this is a very annoying bug.

**Comment by c10ud** [comment]
..and tough to fix

**Comment by Sbte** [comment]
@c10ud, is this a recent regression or has it always been there? I have never experienced it myself, but maybe I just don't talk enough.

**Comment by c10ud** [comment]
i think it has always been there, with tabbed chatting, etc.

**Comment by Sbte** [comment]
Just tested, doesn't happen here. So I guess I never had it. Lucid ftw?

**Comment by c10ud** [comment]
i have it iirc, you must be writing when you receive a new message that triggers a new tab

**Comment by hit** [comment]
For me, this happens quite frequently. And yes, focus seems to get lost when someone said something in other window while typing, but not always.
There's also another anomaly related: when typing and message(s) is/are received in another tab, this another tab won't flash. You see contact typing, but no flashing icon after the message has arrived.

--EDIT
Noticed something in debug after losing focus:

/home/hit/Apps/emesene/emesene/gui/gtkui/**init**.py:114: GtkWarning: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
  gtk.main()

Related to this or something new?

--EDIT2

That warning mentioned seemed to only happen once...

**Comment by c10ud** [comment]
try with latest git master b85115080207e521edb5 i should have fixed it

**Comment by c10ud** [comment]
relevant commits:
952a9b96040acb35404d2ac59163cb3022e91d7d
bed60eb44148b3af013cd7f2596a2e649ca31930

**Comment by rockybalboa** [comment]
I don't experiencing this problem now, but someone should take a look at it too.

**Comment by c10ud** [comment]
ok then i'm closing this, if someone notices a regression please reopen

**Comment by ricsipontaz** [comment]
I tried it and it is works well. Nice job. ;)
