### ISSUE TITLE
Closing Trouble

### ISSUE THREAD

**Issue by chesaro** [emesene/emesene#497]
Hi there, i think it has been done a great improvement to the emesene interface and functionality, i'm starting to prefer it instead of pidgin XD.
Well my problem it's very simple but it's been a headache since the installation, i'm using ubuntu 11.04 natty narwhal, and when i'm using emesene it works perfectly, but when i logout from any type of account the menu to close it just disapear, and it wouldn't close (well terminate) it still apear at the e-mail, messenger, etc shortuct (and of course at the gnome-system-monitor it's still running), i don't know if its because the tray icon's where removed but i just can't close it correctly once i started (and sometimes it makes some weird thing if closed with an open session)... that's all :D.

Excellent work and it really was a change for good

**Comment by Sbte** [comment]
You should enable natty-proposed or use our ppa at https://launchpad.net/~emesene-team/+archive/emesene-stable

This was fixed in 2.11.4.

:D

**Comment by chesaro** [comment]
:O, gracias, no pense en el ppa jeje
