### ISSUE TITLE
opened conversations and disconnect

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#50]
bad things happen, not so bad, but they're not nice for sure

**Comment by arielj** [comment]
I made a commit to remove the empty window frame after logout, any other bad thing?

We shouldn't close opened conversations if the server disconnects us, right?

**Comment by c10ud** [comment]
i think they should stay open, and re-update their status upon a "good" reconnection, otherwise they just close (i.e. connect to other account)

**Comment by marianoguerra** [comment]
I think the main problem of this bug is closed, create a new more specific one with details if the problem persists
