### ISSUE TITLE
Preferences not saved when session is shutdown

### ISSUE THREAD

**Issue by Fabio-pereira** [emesene/emesene#500]
Hi,

I noticed that almost (it not all) changes in preferences (even window sizes) are not being saved when the user shutdown the session. If you close emesene before shutting down the session, then the changes are saved.

OS.: Ubuntu 11.04
Emesene: 2.11.4

**Comment by Sbte** [comment]
Should be fixed in git by 0b691dffb115b69673aa66169cd476471d0f8ee6
