### ISSUE TITLE
Multichat improvements

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#501]
Multichats could be improved a little, with inline notifications such as "foo has left the chat"/foo has joined this chat" and maybe showing a side window with a list of the participants with their avatars, to make it easier to keep track of what's going on

**Comment by rockybalboa** [comment]
User left/joined the channel string is a very good idea. I think the participants manage is very good at the new version, it's rotate the contacts avatars every x seconds.

**Comment by Soulsuke** [comment]
It's a nice feature, but it can get annoying in multichats with a lot of participants, since you can get an idea of who's in there with just a quick glance at the avatars list... Maybe an option to choose which one of the two ways of displaying the avatars could come handy, much like the tray icon/indicator thing

**Comment by arielj** [comment]
the avatars list should be a new extension of the same kind of the ContactInfo object, it shouldn't be hard to do this, just some gtk training.

the "joined"/"left" messages should be easier too, we already have callbacks for those events inside base/Conversation.py, someone just need to tell the conversation to display some message and we are done

**Comment by pepeleproso** [comment]
I implement left/join messages in my tree

**Comment by c10ud** [comment]
thanks pepe, as for the side window, i don't think we want to do it..
