### ISSUE TITLE
Problems with Ubuntu Lucid Línx 11.04.2 LTS

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#502]
Hi all!

Somebody can test emesene (git & 2.11.4 too) on Ubuntu 11.04? For me it is a lot of bugs with it.
I can edit my name and PM. I can't click into the textbox, if I click on it nothing happens. If I am change my picture nothing happen. But with newer emesene everything works fine.

**Comment by marianoguerra** [comment]
maybe you have an old papyon version?

**Comment by rockybalboa** [comment]
I am installed it again. Now it is okay. But have an another graphical problem. No icon for mail and status:

Screenshot: http://noob.hu/2011/05/04/1_10.png

Any idea?

**Comment by Mystro256** [comment]
try deleting ~/.config/emesene2/config, this seems to fix the image issuing when reinstalling

**Comment by rockybalboa** [comment]
Cool, it is now works! Thanks!

**Comment by Mystro256** [comment]
No problem
