### ISSUE TITLE
Chat window opens blank, KeyError: u'\xe9'

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#503]
There is an issue about  u'\xe9' in unicode, which is "é".
Clicking on a contact just opens a blank window and throws an error (details below)

Changing "def path_to_url(path):" in "emesene/gtk/utils.py" to :

def path_to_url(path):
    if os.name == "nt":
        # on windows os.path.join uses backslashes
        path = path.replace("\", "/")
        path = path[2:]
    path=path.encode("iso-8859-1" ) 
    path = urllib.quote(path)
    path = "file://" + path

```
return path
```

solves the problem.
You should change this in source code. Just my two cents.

Error: 
TypeError: **common_errback() takes at least 3 arguments (2 given)
/usr/lib/python2.6/urllib.py:1224: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  res = map(safe_map.__getitem**, s)
[20:13:49 WARNING e3.common.Signal] Signal handler (_on_contact_selected._on_contact_selected) error: u'\xe9'
Traceback (most recent call last):
[...]
  File "/home/echo/Téléchargements/emesene/emesene-emesene-116549a/emesene/gui/gtkui/utils.py", line 203, in path_to_url
    path = urllib.quote(path)
  File "/usr/lib/python2.6/urllib.py", line 1224, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\xe9'

PS: notice indentation is broken.
Just add  "    path=path.encode("iso-8859-1" ) "

And emesene/gui/base/MarkupParser.py", line 176 must also be changed. Or maybe there is a better fix.

**Comment by arielj** [comment]
maybe we can change the string to unicode? I think it's a better solution, try:

path = unicode(path)

**Comment by c10ud** [comment]
waiting feedback

**Comment by EchoUSB** [comment]
path = unicode(path) gives
"/usr/lib/python2.7/urllib.py:1238: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
[...]
KeyError: u'xe9'"
too.

Converting to iso seems OK but it might bring new problems...

**Comment by Sbte** [comment]
It might gives problems with for example chinese locales.

**Comment by c10ud** [comment]
right, sbte is right. we need to find a better solution for this
