### ISSUE TITLE
NO TRAY ICON UBUNTU 11.04 CLASSIC UBUNTU

### ISSUE THREAD

**Issue by webmaker703** [emesene/emesene#504]
i dont know is this is a bug of ubuntu or emesene but the tray icon of emesene2 its not being showed on the notification area as skype and fusion icon..

i've tryied with phyton-gtk-extras but doesnt appear.. so.. here its my report

by the way... thank you to much for emesene2 i really like emesene!!

**Comment by arielj** [comment]
did you choose the trayicon's extension on preferences > extensions?

**Comment by Mirkilin** [comment]
Same problem, no tray icon

**Comment by Fabio-pereira** [comment]
For me emesene appears on the messaging menu (the one with the small letter icon)

**Comment by Mystro256** [comment]
This is a duplicate of #340 and/or an extension of it :P

**Comment by Sbte** [comment]
Ubuntu has the memenu. It's in there. Other than that, it's a duplicate of #340, because there should be an option to get the old tray icon back, but that option doesn't work.

**Comment by c10ud** [comment]
the messaging menu is still there even with classic ubuntu, i guess.

2011/5/5 webmaker703
reply@reply.github.com:

**Comment by Mystro256** [comment]
Yeah the classic is based off of Maverick but with updated versions and the complete indicator applet

**Comment by pjalegria** [comment]
installing indicator-applet and indicator-applications solved for me
