### ISSUE TITLE
If 2 screens connected, emesene starts on 2nd screen

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#505]
I currently am using my tv as a second screen, and every time I open up emesene it opens on the tv (second screen) instead of the main screen. A fix for this would probably also be better fix for #384.

Using Windows 7 and am not sure if this is present on any other OS.

**Comment by Mystro256** [comment]
I can confirm this on Ubuntu 11.04 as well

**Comment by ghost** [comment]
Also, notifications also appear on the 2nd screen.

**Comment by rockybalboa** [comment]
Confirmed too.

**Comment by Mika56** [comment]
I think this should be an option. I can confirm too, but that's the wanted behaviour for me.

Mika.

**Comment by c10ud** [comment]
window manager bug? did you try with 2.11.7? please give feedback

**Comment by ghost** [comment]
I can't try atm, no computer. Once I get one though I will update.

**Comment by ricsipontaz** [comment]
Intresting, it is works well for me with emesene 2.11.7 (and 2.11.4 too).
Ubuntu 11.04, Nvidia with Twinview

Youtube:
http://youtu.be/BqQbMCV4Fxk?hd=1

**Comment by c10ud** [comment]
nice! we probably fixed this when we fixed window positioning.. i'll close, we'll reopen in case the bug persists and it's emesene dependant

thanks ricsipontaz for the testing and the awesome screencast :p
