### ISSUE TITLE
Minimum window size for the main window

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#506]
Minimum window size for the main window are all over the place. 
- If logged in and you set the width to the minimum or under a certain size, when you click on your display name it increases the the width. Clicking the personal message does not have the same effect.
- If logged in and you set the width or height to the minimum or under a certain size, when you log out or disconnected it increases. When you log back in, the sizes you set are lost.
- The minimum size for the login screen is increased when disconnected (due to loss of connection) to to make room for the reconnection message.

Tested on both windows 7 and xubuntu 11.04.

**Comment by Sbte** [comment]
So, what do you suggest? I think it would involve even more bad settings and gtk hacking to save the size of the main window different from the login window. Should we just increase the minimum of the main window to the minimum of the login window?

**Comment by ghost** [comment]
That could be one solution,though some might like to have a smaller main window even if the size doesn't get remembered. That part isn't really that big of an issue.

Having one minimum size for the login window would probably make more sense though. Right now the size difference doesn't really make much sense, because the extra space on the disconnected login window isn't really being used.
http://imageshack.us/photo/my-images/683/windowsize.png/

**Comment by Mystro256** [comment]
Agreed, it's size consistency that's the issue. As well, I doubt hacking gtk to allow smaller windows is very practical or valuable, the minimum window size should just be increased to create a consistent minimum window size between the contact list/log in screen (and any other scenarios).
