### ISSUE TITLE
1.6.3 knows when user logs in as Invisible in emesene2

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#507]
I have still been using 1.6.3 since there is still no stable windows package, but while using the 2 at the same time I found that 1.6.3 knows when a user using emesene2 logs in and out. Not sure if its a problem with emesene2 or if 1.6.3 just has privacy invading powers. Doesn't seem to happen when I ran 2 instances of emesene2 though.
1. Have 2 accounts that have each other added.
2. Log in on 1.6.3 with any status (I used online)
3. Log in as invisible with 2.11.5-devel
4. 1.6.3 plays sound (and shows notification if enabled) that 2.11.5-devel user "is Offline"
5. Log out of 2.11.5-devel
6. 1.6.3 plays sound (and shows notification if enabled) that 2.11.5-devel user "is Offline"

Tested only on windows 7.

**Comment by Mystro256** [comment]
Well the point is that you shouldn't know, hence why it's called being invisible. It would be a bug or an anti-feature if such a thing existed. I do believe this is a bug in emesene 1.6.3

**Comment by ghost** [comment]
Wasn't sure if it was 1.6.3, 2, or both. Just figured I'd share just incase.

**Comment by Mystro256** [comment]
Since you have windows, are you able to test it with emesene 1.6.3 and the official client? I'm almost certain its a emesene 1.6.3 glitch but better safe than sorry.

**Comment by ghost** [comment]
Will do.

I was thinking that even if it is only 1.6.3 that is playing/showing notifications when it happens, emesene2 might still sending out something that triggers it.

**Comment by ghost** [comment]
Installed official WLM, defiantly a 1.6.3 problem.
WLM 2011 and emesene2 acted the same way.

**Comment by Mystro256** [comment]
Yep, it's exactly what I thought it was, thanks for your help.

**Comment by c10ud** [comment]
as you said, emesene1.6.3 has privacy invading powers :)

thing is, microsoft sends notifications about other clients always,
it's up to the client discarding whose which are ininfluent (e.g.
offline-to-offline, which is the case you pointed)

also, don't use emesene1.6.3 as it breaks your profile

p.s. you could be the one making windows packages!

2011/5/5 syst3mfailur3
reply@reply.github.com:

**Comment by ghost** [comment]
I wouldn't mind making the windows packages if I knew how to do them without all the errors.

**Comment by Mystro256** [comment]
Speaking of packaging, I should probably be making myself useful and packaging 2.11.4 for various Linux's ;)
I keep messing the packages up though...

**Comment by marianoguerra** [comment]
@Mystro: which distros would those be? ;)

**Comment by Mystro256** [comment]
I was trying to make it for Fedora and perhaps SUSE because I use Ubuntu and Fedora only my computers and the fedora packages have yet to be made (i haven't looked into SUSE), but I'm not too good with rpm's and I haven't had a lot of free time as of late :/

EDIT: There doesn't seem to be an openSUSE package in development to my knowledge, not entirely sure, but I should be free all Monday, so I'll try to get a working rpm that will work with Fedora and openSUSE. I assume the copying the ubuntu *.deb dependant packages' versions should suffice?
