### ISSUE TITLE
Tray menu icons

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#508]
Currently there is no icon for Contacts and Hide/Show in the tray icon menu. The contacts icon can be borrowed from the contacts menu in the main window. Don't really know what would be good for Hide/Show, but being empty is a bit boring.

Also on Xubuntu 11.04, its extremely hard to see the Disconnect icon.

**Comment by Mystro256** [comment]
Are you referring to the contact window? I don't understand what you mean

**Comment by ghost** [comment]
sorry if it wasn't clear. I was talking about the menu when u click on the tray icon.
it lists:
Hide/Show emesene (No icon)
Status (Has icon)
Contacts (No icon) 
Disconnect (Has Icon, but hard to see in Xubuntu 11.04)
Quit (Has Icon)

https://github.com/emesene/emesene/blob/master/emesene/themes/images/default/chat.png would be good for the Contacts menu I think.

**Comment by Mystro256** [comment]
Oh I see, that seems like a good idea. I'll look into implementing it.

**Comment by ghost** [comment]
For the Hide/Show, I came up with a rough idea for the icon in paint.
http://i55.tinypic.com/2mwwjdv.png

**Comment by Mystro256** [comment]
Hmm... Well contacts definitely seems out of place, but maybe it would better to keep hide/show without an icon to make it stand out, no? Not to mention, the text is longest of the group, so adding an icon would make the menu wider, adding space, I'm not sure if this is ideal.

**Comment by ghost** [comment]
I guess it does make it stand out a bit, but at the same time adding a icon would go with the flow of the rest. Since its at one of the ends, it can really go either way. 

On windows at least, it doesn't seem like it would add anymore space. The space for the icon seems to be already there.
http://imageshack.us/photo/my-images/594/traymenu.png/

I'll check out the tray menu on xubuntu again tomorrow.

**Comment by Mystro256** [comment]
Yeah, I'm currently using Ubuntu with the messaging menu instead of the tray icon, so I'll have to get back to you on that too; It's been a while since I've used any other distro and can't remember what it looked like.

**Comment by Sbte** [comment]
Preferably use one of those and don't add (useless) new icons ;)

http://www.pygtk.org/docs/pygtk/gtk-stock-items.html

**Comment by Sbte** [comment]
Oh, and Mystro, if you want the old tray icon, you could probably just set PYNOTIFYERROR = True in gui.gtkui.**init**.py

**Comment by c10ud** [comment]
i don't believe we should put icons in the indicator and/or tray icon because:
a) nearly every distro that has indicator also has the messaging menu hence indicator isn't (wanted) used
b) hide/show should be like a checkbox so..

**Comment by Sbte** [comment]
Well, apparently they show up on windows. And for consistency, they should either all have it, or none should have it. See

https://github.com/emesene/emesene/issues/508#issuecomment-1103717

**Comment by c10ud** [comment]
oh, maybe it was the old emesene that had the checkbox? anyway, trivial to fix, left as an exercise for the reader

**Comment by Mystro256** [comment]
I think it looks find with just this fix, opinions?

Unless you want to put the emesene icon or gtk.STOCK_LEAVE_FULLSCREEN, etc.
but it seems fine without.

**Comment by c10ud** [comment]
fine for me, i'll close this then
