### ISSUE TITLE
Custom smilies not working without adium output

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#509]
File "/home/echo/Téléchargements/emesene-emesene-95c71d3/emesene/gui/base/MarkupParser.py", line 128, in replace_emotes
    path = os.path.join(cedir, cedict[shortcut])
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

When the conversation output is set to "output text", custom smilies are not working
I tried printing "cedir" in MarkupParser, it is "None"

And for Adium output smilies are working, but I think it's not supposed to look this way, right? :
http://www.noelshack.com/1/1/2011-05-05-145140_1366x768_scrot-70b32ece86.png

**Comment by EchoUSB** [comment]
In gui/gtkui/TextBox.py, line 356
text = MarkupParser.replace_emotes(text, cedict)
It only requires to add the third parameter which is the path of the emoticons, but I don't know how to fetch it from config.

**Comment by Sbte** [comment]
I hope that that fixes it. It passes the path now at least.

Also, this is what Adium is supposed to look like

https://lh5.googleusercontent.com/-O7Rej0j8wi4/TXGH2l3F1gI/AAAAAAAAHcU/2PhTiAu36CE/s1600/emesene2-conversation.png

so something is really messed up. Maybe this also has something to do with your weird path?
