### ISSUE TITLE
Problems preventing Windows Package

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#512]
Here are a list of things that I have experienced that are preventing a stable Windows package from being made.
- crash when chat window opens or sometimes when user sends first messsage (#414)
- gtk theme problem (#437)
- [SOLVED] error on exit (#439)
- [SOLVED] My packages don't seem to be working on XP, dont know about vista

I don't mind making the package since I have a windows system, but having problems with the above.
Don't really know what to do here beyond what the windows guide says.

I have access to both windows 7 and windows xp (VM).

**Comment by marianoguerra** [comment]
I commented on the respective issues

**Comment by ghost** [comment]
- Seem to have gotten my packages to work on XP and 7 now.
- The crash in the chat window seems to be caused when using adium output. It works fine with regular textoutput.

Currently building 2.11.5-devel packages, but once the issues are solved i'll build 2.11.4 i guess.
my testing packages can be found at http://www.fileserve.com/list/3sn6UZV

**Comment by c10ud** [comment]
mariano seems to be fixed all the stuff :D

**Comment by ghost** [comment]
Going to build a 2.11.5-devel package to test em all, just to double check.
If all goes well, I'll get 2.11.4 tomorrow.
Just a question about that, how do I clone only upto the 2.11.4 stuff via git?

**Comment by marianoguerra** [comment]
I think you should do the build with the latest code, since it's only bug fixing from the release day until now.

this would avoid repeated bug reports that we already fixed.

**Comment by ghost** [comment]
Ok, that makes it a bit easier I guess.
I just have to follow the updated guide right? Nothing special since its the final 2.11.4(and a bit)?

**Comment by marianoguerra** [comment]
follow the guide, if you find some problem with the guide let me know so I update it.

ps: thanks for your work!

**Comment by ghost** [comment]
I don't have time right now, but ill build and test sometime later today and let you guys know the results.
Then I'll post it. I'll probably name it 2.11.4.1 or something since its more then just 2.11.4.

**Comment by marianoguerra** [comment]
On Sat, May 7, 2011 at 11:51 AM, syst3mfailur3
reply@reply.github.com
wrote:

> I don't have time right now, but ill build and test sometime later today and let you guys know the results.
> Then I'll post it. I'll probably name it 2.11.4.1 or something since its more then just 2.11.4.

sure, now that we are at it, cloud: do we have some other packages to
release with the windows package?

so we can generate more noice on the blog.

I didn't got any news of new packages, of course, debian/ubuntu may
have  updates when we release 2.11.4.1

we could make a "tell us if you saw an emesene package on your distro"

maybe fedora already has it and we don't know it, ditto for arch and
similar distros.

I would like to update the download page with instructions per distro,
but we still don't know where it's available.

**Comment by ghost** [comment]
I think @Mystro256 said he was going to help package for other distros.
https://github.com/emesene/emesene/issues/507#issuecomment-1106248

**Comment by c10ud** [comment]
since we changed lots of stuff, i guess we can go with 2.11.5 -- i guess windows could release a fake 2.11.4, or just wait for a real release (?)

**Comment by Mystro256** [comment]
The Ubuntu stable ppa should definitely be added too :)

**Comment by ghost** [comment]
@marianoguerra in the guide, found a small error.
cp windows/boot_common.py /c/Python26/Lib/site-packages/py2exe/
should be 
cp ../windows/boot_common.py /c/Python26/Lib/site-packages/py2exe/
i think.

**Comment by ghost** [comment]
@c10ud @marianoguerra
emesene 2.11.4.1 packaged and uploaded.
installer: http://www.fileserve.com/file/NHsMWwT
portable: http://www.fileserve.com/file/up2avrE

**Comment by Mystro256** [comment]
@c10ud @marianoguerra I just finished packaging a RPM for emesene, which is made to work with fedora, suse and variants of the two. I have only been able to test fedora, I'll have to virtualbox openSUSE to figure out if that works though.

Who's in charge of the website, who should I send it off to?

**Comment by marianoguerra** [comment]
On Sun, May 8, 2011 at 7:10 AM, syst3mfailur3
reply@reply.github.com
wrote:

> @marianoguerra in the guide, found a small error.
> cp windows/boot_common.py /c/Python26/Lib/site-packages/py2exe/
> should be
> cp ../windows/boot_common.py /c/Python26/Lib/site-packages/py2exe/
> i think.

fixed, thanks!

**Comment by marianoguerra** [comment]
On Mon, May 9, 2011 at 11:52 PM, Mystro256
reply@reply.github.com
wrote:

> I just finished packaging a RPM for emesene, which is made to work with fedora, suse and variants of the two. I have only been able to test fedora, I'll have to virtualbox openSUSE to figure out if that works though.
> 
> Who's in charge of the website, who should I send it off to?

me and cloud manage the blog so you can send the urls to us or publish
them here.

will they be available on the repos?

I thought emesene 2 was on fedora repos, am I wrong?

**Comment by Mystro256** [comment]
@marianoguerra According to this: http://koji.fedoraproject.org/koji/packageinfo?packageID=5730
Fedora either hasn't recognized emesene 2 as released or haven't gotten someone to build it.
OpenSuse seems to be the same: https://build.opensuse.org/package/binaries?package=emesene&project=server%3Amessaging&repository=openSUSE_Factory

I built 2 rpm's, one for fedora, one for suse. Unfortunately theres just one line that causes issue on suse, so I had to make another rpm to work with suse. I'll post the RPM's on this thread once I test suse with my new rpm. I could also send a message to either distributor to make the packages themselves if you would prefer that.

**Comment by marianoguerra** [comment]
the best solution is for the distributions to package it and have it on the repos, we can have a custom package until they make their own.

if you can start the process to ask for the oficial package it would be great, until then we could add some links on the download section to the packages you made

**Comment by Mystro256** [comment]
@c10ud @marianoguerra Okay, that sounds great. I'll post a request to package it for both distributions later today. For the time being, here's my packages:
Fedora: http://www.2shared.com/file/915ensoJ/emesene-2114-1fc15noarch.html
OpenSuse: http://www.2shared.com/file/HRIDACug/emesene-2114-1susenoarch.html

It should work on all currently supported versions of each distributions.

I would like to note: the fedora package is made for fedora 15 because prior to 15 doesn't make the optional requirement of papyon version 0.5.4. Although due it's optional requirement, I set it so it doesn't require that version in particular, thus it should still be able to install but may suffer from any issues associated with using emesene 2 with papyon version < 0.5.4.

**Comment by Mystro256** [comment]
Fedora has accepted emesene 2 as an official package. I've been informed the package has been updated to meet fedora standards, they just need to fix the locale handling issues with fedora, along with informing the upstream about the licence update requirements.
