### ISSUE TITLE
Support for webcam in emesene2

### ISSUE THREAD

**Issue by yermandu** [emesene/emesene#515]
Will have support for webcam in msn protocol? 

Regards,

**Comment by arielj** [comment]
Receiving your contact's webcam is available on latest developer version (not the stable 2.11.4 release), only receiving and only *nix systems for now, but it should be implemented in the future (don't know when, just the future :P)

**Comment by yermandu** [comment]
Tanks arielj! we expect anxious for this feature, apropos im in nix, but my 97% my contacts under win\* (family msn users). I will testing each time to accomplish evolution, tell us new news =) 

Good lucky

**Comment by c10ud** [comment]
i did what's already there and i don't think it will improve unless someone steps up and take the job, i don't have the time/knowledge to dig into gstreamer to implement A/V sending (and receiving in other platforms than linux)
