### ISSUE TITLE
Nickname and PM dont keep!!!

### ISSUE THREAD

**Issue by pjalegria** [emesene/emesene#517]
Hi 

After i change my nickname and Personal message and saved, when i logoff and then login i have to do it again :( what im doing wrong?

Thanks

**Comment by c10ud** [comment]
Preference-Live Messenger follow instructions

**Comment by pjalegria** [comment]
after do that, same problem

**Comment by c10ud** [comment]
do the procedure with emesene closed

2011/5/7 pjalegria
reply@reply.github.com:

**Comment by pjalegria** [comment]
stlll not solved

**Comment by Sbte** [comment]
Did you actually change the avatar?

**Comment by pjalegria** [comment]
the problem is with nickname and personal messenger

**Comment by Sbte** [comment]
Yes, but to fix it you have to follow the instructions under Live Messenger, which says you should change your avatar on the live messenger website. If you don't set the avatar on the live messenger website it won't get fixed for sure.

**Comment by pjalegria** [comment]
I did set the avatar

**Comment by arielj** [comment]
Also, try to set your profile with Firefox or Google Chrome, if you are on Windows try it with IE, Windows Live Profiles are not browser friendly.

Also... do you have a common @hotmail/live/msn account? or is it something using passport.net?

**Comment by pjalegria** [comment]
Im on Lubuntu 11.04 with Chromium browser and i have gmail account,.
I have tried something, if i open my account profile before i logon in emesene, it works...

**Comment by arielj** [comment]
hmmm, maybe this happens because of the gmail thing? I have a gmail test account too, I'll try that later when I get home.

**Comment by c10ud** [comment]
last time i write it:
- CLOSE emesene, whatever version
- open your live profile and set a new dp/name/whatever and save it
- open emesene2 and don't open emesene1 or any other faulty client anymore

it will work, 100% tested on multiple accounts suffering the same issue. if you can't fix it, then it's your problem
