### ISSUE TITLE
Debian maintainer contact

### ISSUE THREAD

**Issue by diega** [emesene/emesene#519]
In Debian already exists an assigned maintainer, according to the debian/control file. His name is Devid Antonio Filoni d.filoni@ubuntu.com and he is uploading his debian specific files to http://svn.debian.org/viewsvn/python-apps/packages/emesene/trunk/
Dunno how u have in mind to deal with distro specific files If you prefer to keep them in your side (maybe in a synchronized branch named as each distribution(?)) or in each distro repositories.
In any case I think is worth to add the maintainers (in this case Mr. Filoni) to the release loop.

This issue is mostly informative.

Regards.

**Comment by marianoguerra** [comment]
I think we can keep folders with files, scripts and diffs for each distro, we did that for debian and windows on emesene 1

**Comment by c10ud** [comment]
i'd avoid distro specific files in the repo, but if someone tells me to pull them i'd do it. anyway, we are already in touch with debian and ubuntu developers, and that's the main reason on why we had to hurry with the release
