### ISSUE TITLE
I can't resize input box in conversation window

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#52]
I can't resize input box in conversation window below 4 lines of text (with default font). I use a small text box.

**Comment by marianoguerra** [comment]
I can, can you give us more information? operating system, version etc etc?

steps to rerpoduce? I just drag the bar to the bottom, I can hide the input box completely

**Comment by andreskru** [comment]
Using last Git in Fedora 13.
I open a new conversation window, i drag the bar down but it stop near the avatar high,

**Comment by marianoguerra** [comment]
is this emesene 2? can you post a screenshot?

sounds weird

**Comment by andreskru** [comment]
http://img810.imageshack.us/img810/7136/pantallazol.png

**Comment by c10ud** [comment]
http://github.com/emesene/emesene/commit/7f1ff8506a12a15d5d0fcea715805555bcc1b01a

maybe?

**Comment by c10ud** [comment]
i'm reopening 49, if you need a fix again
