### ISSUE TITLE
Logged in 2 locations at the same time with the same account

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#520]
I am currently having a convo with me (1.6.3, testing account, windows 7), myself (2.11.5-devel, main account, windows 7) and I (2.11.4, main account, xubuntu 11.04).

Both 2.11.4 on xubuntu and 2.11.5-devel on windows are logged into the same account, and are all connected in a conversation started on another account logged in on 1.6.3.

Not sure if this is the intended function, but if it is there should be a message that lets the user know that they have been logged in somewhere else.

Message sent from 2.11.5 on windows didn't show up on 2.11.4 on xubuntu.

Windows
http://imageshack.us/photo/my-images/695/memyselfandib.png/

Xubuntu
http://img192.imageshack.us/i/memyselfandi2.png/

**Comment by marianoguerra** [comment]
multiple logins is a feature :)

closing

**Comment by ghost** [comment]
Since it is a feature, to expand on it there should be a message saying that the user was logged in at a different location. 
Just in case it isnt the user who was the one that logged in at a different location, they would know. No one likes being watched without knowing.

**Comment by marianoguerra** [comment]
I don't know if that possible, we should check if the protocol notifies us and if papyon supports that

**Comment by ghost** [comment]
Im not sure, but I think its in the official WLM. Don't know about papyon though.
