### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#521]
i'm using emesene 2 for a while, and i've noted some bugs..

here they are

1) The pictures don't save, i mean, MINE picture, i need to change everytime i sing in again
2) Sometimes, it just stop working... I don't recieve anything, and i don't send too, but there's nothing to say that it's happening, it just happen.. suddenly
3) I can't change the group of my contacts, i add them in one group, it goes to Ungrouped people, and i can put it on the right one
4) When i'm using the version that each conversation has a different window, the first window I open, and someone came talk to me, open a new tab on the first one, and there keep all what the other person say to me, and there's another window too... I can talk to the person on that tab either
5) When a person say something to me, ALL the windows keep flashing, and i don't know who is haha
6) One person, one day, send me a picture of how my conversation was going.. the sentences go half bold, and half normal.. '-'
7) I can't accept files that the other send to me, at least with images... i can see the preview, but can save it on my computer, the only thing I can see is the preview...

that's all, by now...

and suggestions now...

1) some kind of plugin to show what i'm listening
2) save my contacts emoticons
3) some kind of "msn plus" to see the other's nick with that code [c=#000000]Name...[/c]

**Comment by Sbte** [comment]
Some of your problems might be solved by updating papyon and emesene if you haven't already done that. What versions do you have? And what OS do you use?

Also, you might want to fix your profile. You can do that by following the instructions under Preferences -> Live Messenger

Plus should be supported, and plugins are here: https://github.com/emesene/emesene-supported-plugins

Saving emoticons is implemented in the latest development version I think. The same holds for the copy/move to group stuff. But that's also implemented in emesene 2.11.4 stable.

**Comment by alexandre596** [comment]
i upgraded papyon and almost everything i solved 
THANKS

i'm gonna do it to change my avatar picutre
the group, everything..

i only can't add emoticon, but it's better now, cause i can save the picture on my computer, and then add ;P

thanks a lot
