### ISSUE TITLE
bugs!

### ISSUE THREAD

**Issue by YaPeL** [emesene/emesene#522]
using: emesene 2.11.4 os: natty narwhal

1) Groups conversations: there is no way to block the group unless using the command //b (which is kind of annoing, since it only works for 2 hrs)
2) No contextual menu over the conversation ( instead of copy it shows "pagina 1" and it does nothing)
3) I lose my nickname very often

in spanish:

1) Conversaciones de grupos (grpups@xxxxx.com): no hay forma de bloquear los grupos, la unica manera es con el comando /b (y es muy molesto porque solo funciona por unas 2 horas)
2) no hay menu contextual para copiar el texto de una conversacion (the muestra algo asi como "pagina 1" y no hace nada)
3) Pierdo el nick bastante seguido

**Comment by arielj** [comment]
1- I don't know, never used that groups@xxx.com
2-It's fixed on the developer version
3-Did you fix your profile on preferences > live messenger?

1-Ni idea, nunca usé eso de los grupos
2-Está arreglado en la versión en desarrollo, si podés usar el código de github en lugar de la versión de los respositorios va a funcionarte bien
3-Arreglaste tu perfil en Preferencias > Live messenger? suele pasar eso si no está arreglado el perfil

**Comment by pepeleproso** [comment]
for point 3 you must go to Preferences-Live Messenger and follow instructions.
point 2 is already fixed in git master.

**Comment by YaPeL** [comment]
1) www.messengergroupchat.com there are several bugs with this.

2), 3) ok-

**Comment by c10ud** [comment]
duplicate issue, i don't remember the other one, so just search it
