### ISSUE TITLE
Docky helper

### ISSUE THREAD

**Issue by R2D221** [emesene/emesene#524]
Hi, I have recently upgraded to emesene 2, and I tried to use the Docky helper found at http://www.omgubuntu.co.uk/2010/09/improved-emesene-pidgin-docky-helpers/ , but it no longer works. Is there a way to make the helper compatible with emesene 2?
Or, if I modify it myself, where can I see the documentation I need?

**Comment by c10ud** [comment]
i don't know if there's a way to make that thing work, but i guess you'll find more answers in docky website, since i have no idea on what's that all about :)
