### ISSUE TITLE
Change icon on system tray

### ISSUE THREAD

**Issue by ferrannp** [emesene/emesene#525]
Hello!

First, sorry for my bad English.

I have a simple question, is it possible to chance the icon from inside the message botton to system tray (red circle):

<img src="http://i54.tinypic.com/2416xzo.png" border="0"></a>

like emesene 1.6.3-1?

It is to find my contacts faster than now, I can not do that,

Thanks!

**Comment by R2D221** [comment]
As I see it, the behavior in 1.6.3 was incorrect, and I think version 2 now uses the Messaging Menu correctly. The idea is to merge all messaging applications in one place, and show unread mail/IM/tweets/etc

**Comment by Sbte** [comment]
There is an option to change it in the Preferences, but it currently doesn't work properly. See #340.

Closing as a duplicate.
