### ISSUE TITLE
Display pic dialog resize screen too big

### ISSUE THREAD

**Issue by Kreuger** [emesene/emesene#526]
When I try to add a photo to my account for a display picture, the resize window is too big as in it goes down past my taskbar and I cant click on the ok button. Also, why can't emesene just autoresize the image to fit? I hate that I have to crop my picture down to size.

**Comment by ghost** [comment]
Checkout #494, similar issue that has already been fixed in the 2.11.5-devel.

**Comment by Sbte** [comment]
Yes, already fixed by f206808c9c8b05b5217062935c65d4723dce5a21
