### ISSUE TITLE
emesene offline messages

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#527]
hi

i can't sent offline messages to my offline contacts.

and i sent any offline messages to my appear-offline contacts if they don't sent me message before i sent to them.

i'm using emesene 1.6.3 and it's turkish version on ubuntu 10.10.

how can i solve it?

**Comment by c10ud** [comment]
upgrade to emesene2, you can use this ppa: https://launchpad.net/~emesene-team/+archive/emesene-stable

**Comment by ghost** [comment]
how can i do it =/
