### ISSUE TITLE
Doesn't have a msn protocal under windows?

### ISSUE THREAD

**Issue by shuhaowu** [emesene/emesene#532]
I currently got the latest development version and was testing it out. I'm getting the message: No module named papyon
There's no protocal other than dummy.

Do I have to do something or is this a bug?

**Comment by Sbte** [comment]
If you use git, do

git submodule init
git submodule update

Or use this

https://github.com/emesene/emesene/issues/512#issuecomment-1118555

**Comment by marianoguerra** [comment]
and you need to install all the required packages described on the guides to install in windows available on the blog

**Comment by ghost** [comment]
If you were using https://github.com/emesene/emesene/issues/512#issuecomment-1118555 let me know.
