### ISSUE TITLE
Links invisible when they contain "&"

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#535]
If I send a link containing an "&" to a friend, he'll receive  it but it won't show anything in the chat windows, just an empty message
For example: http://www.youtube.com/watch?v=CD2LRROpph0&feature=related doen't work, http://www.youtube.com/watch?v=CD2LRROpph0 works.
Same thing happens when sending a link, I don't see the link I just sent if there is "&" inside it.
I'm using the classic text ouput, I don't know about Adium.

The link is correctly sent, i can get it from papyon debug, but it is really annoying.

And there is no error message.

**Comment by c10ud** [comment]
works in adium

2011/5/10 EchoUSB
reply@reply.github.com:

**Comment by Sbte** [comment]
This should do. Not sure if the link really works though. I couldn't get it to work in Natty, even without the ampersand.
