### ISSUE TITLE
Profile settings not kept

### ISSUE THREAD

**Issue by OldMarc** [emesene/emesene#536]
When I set my profile nickname and PM to something, it's fine until I close emesene. When I next start it, my email addy is my nick again and there is no pm.

Emesene 2.11.4
Ubuntu 11.04
On MSN protocol.

**Comment by Sbte** [comment]
Your profile is broken. Preferences -> Live Messenger. Follow the instructions there. If it doesn't work, try again with emesene closed.

@c10ud, is there a place where we can post this instruction? Most bugs are about broken profiles. Maybe put it on the blog above the link to github? Make a FAQ page? Something like that?

**Comment by OldMarc** [comment]
Ok, thanks for that. :)
