### ISSUE TITLE
Emesene not showing in launcher and multiple windows showing

### ISSUE THREAD

**Issue by OldMarc** [emesene/emesene#537]
This could be another simple issue, but emesene isn't showing in the Unity Launcher, and when someone messages me, it opens 5 windows.

Emesene = 2.11.4
Ubuntu 11.04

**Comment by Sbte** [comment]
That's weird. I'll install Natty today, and see what's wrong.

**Comment by Sbte** [comment]
It works fine here...

**Comment by OldMarc** [comment]
Hmm, I'll try a purge and reinstall.

**Comment by OldMarc** [comment]
The issue seems to arise when I select 'keep in launcher' and then restart emesene.

**Comment by Sbte** [comment]
Ah, I guess you didn't close it properly. You probably still have like 5 sessions of emesene open in the messaging menu (envelope on the right top of your screen). 

If you want, you could choose a different tray icon under Preferences->Extensions->tray icon (probably Indicator), or you could run emesene with the -s option to make sure you can open only one session.
