### ISSUE TITLE
Emoticon Issue

### ISSUE THREAD

**Issue by ez1to3** [emesene/emesene#538]
I updated on Tuesday May 10th. and some emoticons, when revived, come with file path. picture here http://img804.imageshack.us/img804/7526/screenshot1i.png

**Comment by Sbte** [comment]
Is this adium?

**Comment by arielj** [comment]
please don't use imageshack, it's always showing "blocked site" at leas for me :S

try freeimagehosting.net or any other hosting site

**Comment by Sbte** [comment]
arielj, then you probably blocked imageshack. Or someone else did it for you. It works fine for the rest of the world (except for China and North Korea perhaps) ;)

**Comment by arielj** [comment]
I didn't, I've used 3 different pc's with 2 different connections and 3 different browsers, maybe ImageShack just hates me (?)

Maybe it hates argentina (?)

**Comment by Sbte** [comment]
We can probably add Argentina to the list with North Korea and China then ;)

**Comment by ez1to3** [comment]
Yes, This is adium, Ravenant.
And I uploaded it to that other site as well, seems slow but http://www.freeimagehosting.net/image.php?cc965360f9.png :)

**Comment by arielj** [comment]
Open the file gui/gtkui/AdiumTextBox.py and add this code on line 114

<pre>
        print html
</pre>


this will show you the html code on the terminal, paste it on pastebin.com and put the link here so we can see what's wrong.

**Comment by arielj** [comment]
Any update on this issue?

**Comment by ez1to3** [comment]
Well i tested it on a second Ubuntu computer. it doesn't occur there. I'm looking to see why. When i get to that computer tonight, I'll look at it. Will update it one more time, to see if there are any changes. will let you know.

**Comment by Sbte** [comment]
And how did it go? Also, does it happen when you don't use Ravenant?

**Comment by ez1to3** [comment]
Yeah, I apologize about the slow replies. University is a lot of work. so after the update, the text as show in the picture does not come. they (the emoticons) load MOST of the time. other times it will bring the 'no image' icon, and once that's clicked it show's texts and one more click brings the actual emoticon back. that is, the problem is fixed / walk around.

**Comment by ez1to3** [comment]
I'll check with the 'print html' and see what happens

**Comment by ez1to3** [comment]
okay so where you told me to put the print, that's for me sending not receiving. that original error occurred when i received a message. Also, to update on what i said before, about the walk around, I'm guessing that when the 'no image' icon comes is because my chat box did not receive the icon fast enough, so when I reload it, it arrives. I assume it because of this, because once it's revived, and used again, this error does not occur. on the other hand, when the 'no image' icon comes, this is what is printed in the terminal. 

[22:38:14 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[22:38:14 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[22:38:15 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:38:15 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

hope that helps.

**Comment by Sbte** [comment]
AH! I think I know what you mean now. Does it happen when you receive custom emoticons for the first time, and for the first time only?

**Comment by ez1to3** [comment]
Yes, so for most of the custom emoticons, it works but then for a few the 'no icon' will appear. Once I cycle through the icon and text, it loads the second time. after this, the 'no icon' does not occur for that emoticon, and neither does the warning in the terminal. At this moment, I cannot see the similarities between the ones that do come and the ones that do not come.

**Comment by Sbte** [comment]
You receive them for the first time, so they're not yet downloaded when emesene is already trying to use them in the chat window.

A solution would be adding a timer that refreshes the emoticon until it's there, with a maximum of 30 timer or so, but I have no clue how you can refresh just one emoticon. I'll try to look into it later.

**Comment by c10ud** [comment]
already taken care of this, there's a signal that's fired when a p2p transfer is finished (e.g. emoticon). The adium-ed conversation receives the signal and tells webkit to reload the image with some javascript hax. unfortunately i found out (iirc) there's a bug in adium themes (adium too) that prevents it to correct updating, but a doubleclick on the image usually works.

feel free to make some more tests though

**Comment by Sbte** [comment]
Force a double click simulation?

**Comment by c10ud** [comment]
no sir, there are specific js hax that must work, and we're doing them, if it don't work there's either a small bug i don't know of, or a bug in adium (like i recalled b4)

**Comment by Sbte** [comment]
Yes, but since that doesn't work, can't we try to simulate whatever the double click does?

**Comment by c10ud** [comment]
no, but you can use your lazy finger to doubleclick the new emoticon you receive once a while, if you really want to see it NAO

**Comment by c10ud** [comment]
any further info about original issue?

**Comment by c10ud** [comment]
i mean, persists, gone, etc.?

**Comment by ez1to3** [comment]
it occurred yesterday, but the double clicking walk around works. I'll update emesene again and see if it occurs.

**Comment by c10ud** [comment]
wait: the emoticon not showing (because it's loading) and the need of doubleclicking when fully loaded is ok.
what it's not is the conversation showing stuff like name="whatever" alt="etc" as showed by your first screenshot, did that occur again?

**Comment by ez1to3** [comment]
No, that problem is solved. I tested it on two computer. with Ubuntu. that original error hasn't occurred. and seems to be fixed. in the picture, its the 'no icon' and then the text, now if it doesn't load, there's no text, just the 'no icon' but it usually loads in a matter of seconds. I haven't tested it heavily, but from what i see, it's fixed.

**Comment by lainiwaku** [comment]
hey i have this bug 
but the emoticon perso. doesn't show not only the first time !
