### ISSUE TITLE
Gnome Shell integration,

### ISSUE THREAD

**Issue by SweetthD3ViL** [emesene/emesene#539]
Hi all,

And first of all thank you for Emesene2 it's running very smoothly on archlinux ^^.

I know I do not bring a bug or something new, but I would like to know what your thought on creating the integration into Gnome shell in order to use the DBUS system? 

Looking forward for your reply,

SweetthD3ViL 

A long time use ;)

**Comment by c10ud** [comment]
no, gnome-shell integration (how, btw?) is not in our plans

**Comment by SweetthD3ViL** [comment]
With the latest released of Gnome 3 (with gnome shell) the top bar interact with the instant message software (empathy - for the time being).
I am not a dev, far from it, but from what I have read on the web simple dbus interface will do the trick, so gnome will be able to show instant message arriving - the ability to change status from the use menu (gnome menu) 

I think it will be a great addition, and certainly put emesene on top of the scene ;)

**Comment by c10ud** [comment]
i don't think gnome wants anyone to play with their desktop unless they want to -- anyway, if someone's interested can use/extend cando's dbus code. i'm not running g-s so..

**Comment by SweetthD3ViL** [comment]
Fair point if you aren't interested in making emesene experience better with gnome.

But gnome are using dbus integration especially so other dev and software can interact with gnome.

**Comment by marianoguerra** [comment]
I think this can be asily done as an extension/plugin, someone can find the documentation for that and post it here for future reference?

**Comment by hit** [comment]
http://developer.gnome.org/notification-spec/
https://github.com/kagesenshi/gnome-shell-extensions-pidgin
