### ISSUE TITLE
Double Messages on Chat Window

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#54]
In an apparently random time, the contact messages appear two times on Chat Window, or appear only one, but the sound plays two times.

Unfortunately I can not find what causes this behavior. But only happens when the Chat Window is open for a long time, and only happens with one Contact on the Chat Window, Closing and opening the window don't solve the issue.

Regards!

**Comment by EibrielInv** [comment]
Well, I think I know now from where comes the problem.
If I'm chatting with X and X start a new session in another MSN (closing the old session, or not, I don't know yet) then his messages arrives Doubles. If then X start a new session in another MSN then the messages arrives Triple (Now I'm receiving Quadrules messages at once :O )

Regards!!!

**Comment by c10ud** [comment]
ok, so we're not disconnecting signals well, thanks for debugging :D

**Comment by Sbte** [comment]
I can confirm that this is still there.

**Comment by c10ud** [comment]
Kill signals/conversations when user lefts the conversation (only single convs) in papylib. Closed by aca7c3125acf5612c2454426ade6bd928edc593b

**Comment by c10ud** [comment]
please let me know if you can reproduce the issue, i cannot anymore :s

**Comment by Sbte** [comment]
I tried to reproduce it earlier today (after you reverted the comment that was supposed to fix this) and I couldn't reproduce it either, whereas I could consistently reproduce it before. So indeed fixed I think.

**Comment by EibrielInv** [comment]
No, I can't reproduce it.
Closinggg

**Comment by c10ud** [comment]
ok, if it happens again please reopen (and hopefully i can reproduce it too :))
