### ISSUE TITLE
cant start in ubuntu 11.04

### ISSUE THREAD

**Issue by kiovanx** [emesene/emesene#540]
Traceback (most recent call last):
  File "/usr/bin/emesene", line 32, in <module>
    import emesene
  File "/usr/share/emesene/emesene/emesene.py", line 51, in <module>
    import glib
ImportError: No module named glib

i get this error anyone know how to solve it??

**Comment by c10ud** [comment]
i guess you broke your system, or maybe you're with kubuntu or something?

2011/5/11 kiovanx
reply@reply.github.com:

**Comment by kiovanx** [comment]
no im in ubuntu 11.04 my system is working ok

**Comment by arielj** [comment]
Emesene can't find the glib module, try reinstalling python-gobject (it includes the bindings for glib)

**Comment by c10ud** [comment]
also, the ubuntu software center also imports glib, so..if you're able to start it, you should be able to start emesene too. feedback or i'll close the issue :D

**Comment by kiovanx** [comment]
i reinstalled ubuntu the first thing i did was install amsn and it worked, tx
