### ISSUE TITLE
custom emoticons issues

### ISSUE THREAD

**Issue by mgaiarsa** [emesene/emesene#541]
I've migrated from Win7 to Ubuntu recently, and installed emesene because I've looked up and found it to be the most suited to my uses (custom emoticons). However, when I receive/send custom emoticons, a square will show up instead of the emoticons with a paper looking icon. I've looked up everywhere, got the Adium output, but yet I have found no success in doing that. 
Any light on that issue?
Much appreciated,
Mario

**Comment by ez1to3** [comment]
this might be similar to my post https://github.com/emesene/emesene/issues/538. except, it also displays the emoticon file path.

**Comment by arielj** [comment]
Run emesene from a terminal and see if you get some error there.

**Comment by Sbte** [comment]
Any update on this?

**Comment by c10ud** [comment]
incomplete, closing
