### ISSUE TITLE
Group deleting while in changing statuses

### ISSUE THREAD

**Issue by scottnguyen** [emesene/emesene#544]
I'm currently using emesene 2.11.5-devel.

I've noticed while changing my status or nickname to something on the client, I would press DEL to remove my old status or nickname and it would also prompt me if I wanted to delete one of my previously selected groups. Is this a bug or a feature?

**Comment by Sbte** [comment]
It's a bug I think, see 6309a56d0628b7baae16a848e04e2deaf1afb03a

@nenemfromhell, you probably don't want to set the accelerator for the whole main window. Not sure if that's possible though.

**Comment by arielj** [comment]
Isn't this fixed? https://github.com/emesene/emesene/commit/9f8b0611a6623714745741e65617d3b105f109bf

@scottnguyen, can you update us on the issue? so we can close it.
