### ISSUE TITLE
Window moves to the right when clicking connect

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#545]
In Natty, the login window moved to the right when clicking connect, and stays there. So say my window is on the left the first time I click connect and I connect 400 more times, the window will be on the other side of the screen. WTF really.

Using dual screen with twinview (don't know if that matters).

**Comment by c10ud** [comment]
try printing out x,y coords and see what they say

**Comment by Sbte** [comment]
(635, 24)
(640, 24)
(645, 24)
(650, 24)
(655, 24)
(660, 24)
(665, 24)
(670, 24)
(675, 24)
(680, 24)
(685, 24)
(690, 24)
(695, 24)
(700, 24)
(705, 24)
(710, 24)
(715, 24)
(720, 24)

When clicking Connect and Cancel repeatedly. Did this in _set_location (emesene.py).

**Comment by Sbte** [comment]
Calling 

```
        print self.get_position()
        print (self.set_or_get_posx(posx), self.set_or_get_posy(posy))
        self.move(self.set_or_get_posx(posx), self.set_or_get_posy(posy))
        print (self.set_or_get_posx(posx), self.set_or_get_posy(posy))
        print self.get_position()
```

in 

set_location

gives

(884, 24)
(884, 24)
(884, 24)
(884, 24)
(889, 24)
(884, 24)
(884, 24)
(889, 24)

So it's called twice, and the second time, it has been moved.

**Comment by Sbte** [comment]
Now I get

(590, 54)
(590, 54)
(590, 54)
(595, 54)
(595, 54)
(590, 54)
(590, 54)
(595, 54)

So the position is different after calling move.

**Comment by Sbte** [comment]
When I remove the calls in go_login and on_login_connect, the window gets moved to the left once, and when I restart emesene, it's 5 px to the right.

**Comment by c10ud** [comment]
i wouldn't know if the damn window manager has something to do with it... argh

**Comment by Sbte** [comment]
Probably some natty fail...

**Comment by jjnilton** [comment]
same problem here, i'm using emesene 1.6.3, so much better!

**Comment by Sbte** [comment]
It's also happening with emesene 1.6.3. Just not when you click login, but every time you restart emesene 1.6.3, it will be 5 pixels to the right. It's clearly a Natty bug.

Also, don't use emesene 1. It breaks your profile.

**Comment by jjnilton** [comment]
here, emesene 2 open always in the left side of screen, close to the edge, emsene 1 it opens where i closed last time...

how does it can break my profile?

**Comment by Sbte** [comment]
Shouldn't happen with emesene 2. Do you close it properly?

emesene 1 breaks your live profile. If you use an other messenger (like Empathy, emesene 2,..) after using emesene 1, your avatar, pm and nickname won't be saved. emesene 1 is really bad.

On topic: Bug reported upstream with a test case:

https://bugs.launchpad.net/ubuntu/+source/unity/+bug/785233

**Comment by jjnilton** [comment]
I tried to use emesene 1.6.3 and after I used WLM 11, and it seemed to be  
OK...  I see new features in emesene 2 but I think it doesn't worth  
because it's very unsteady...  i'll wait for a more steady version of  
emesene before using it... i'll try emesene 1.6.3 or pidgin for now, both  
of them connect only in one local, i get less angry with them, i think.

Em Thu, 19 May 2011 12:15:55 -0300, Sbte  
reply@reply.github.com  
escreveu:

> Shouldn't happen with emesene 2. Do you close it properly?
> 
> emesene 1 breaks your live profile. If you use an other messenger (like  
> Empathy, emesene 2,..) after using emesene 1, your avatar, pm and  
> nickname won't be saved. emesene 1 is really bad.
> 
> On topic: Bug reported upstream with a test case:
> 
> https://bugs.launchpad.net/ubuntu/+source/unity/+bug/785233

**Comment by jjnilton** [comment]
ok, you're right, emesene 1 broke my nickname, how do i get it back :(

Em Thu, 19 May 2011 12:15:55 -0300, Sbte  
reply@reply.github.com  
escreveu:

> Shouldn't happen with emesene 2. Do you close it properly?
> 
> emesene 1 breaks your live profile. If you use an other messenger (like  
> Empathy, emesene 2,..) after using emesene 1, your avatar, pm and  
> nickname won't be saved. emesene 1 is really bad.
> 
> On topic: Bug reported upstream with a test case:
> 
> https://bugs.launchpad.net/ubuntu/+source/unity/+bug/785233

**Comment by Sbte** [comment]
Preferences -> Live Messenger. Follow the instructions.

**Comment by c10ud** [comment]
@Sbte you could try tell smspillaz about this
