### ISSUE TITLE
Doesn't allow to selec one image in my computer and set it as my avatar

### ISSUE THREAD

**Issue by anatanootosan** [emesene/emesene#546]
I am a "Windows 7 Professional" user, and have this problem:
Using emesene v.2.11.4.1 i tried to select one image from my computer, the image was normal and everything was like going to be ok, but when I draw the rectangle and click "Ok", appears one message in the debug console:

WindowsError: [Error 32] El proceso no tiene acceso al archivo porque esta siendo utilizado por otro proceso: 'c:\users\%username%\appdata\local\temp\emsnpictn_dky'

hope this helps, i really want Emesene 2 to get better...
sorry for bad english

**Comment by arielj** [comment]
Maybe you don't have enough privileges to write in that directory?

**Comment by c10ud** [comment]
i guess no other process could take over a temporary file made by emesene, so arielj maybe right

**Comment by arielj** [comment]
Just got the error, I guess it's some kind of race condition (maybe our code tries to use the image while it's being written).

The image appears on the avatar selector window after that tough, the error appears at the cropping window, but the avatar can be used anyway after that.
