### ISSUE TITLE
Settings are reset when closing while connecting

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#547]
This settings loading and saving stuff shouldn't be done so damn often...

**Comment by arielj** [comment]
I vote for a "Save" button on preferences, it's clearer that way and the config gets saved when the user want it and not always (we can have a check like "save windows size an position at logout" so users can also choose that).

I know we'll have to recode a lot of things on preferences and add some checks outside preferences too, but I have always felt that not having a "cancel / save" option on preferences was weird.

**Comment by marianoguerra** [comment]
how often are they made now? when I implemented them they loaded on login and saved on logout/close

**Comment by Sbte** [comment]
Also when making a change to preferences and sometimes when settings get loaded from the global config to the account config I think. Also when the login settings are loaded when reconnecting (I already disabled saving there).

The problem probably is that they get saved every time close_session is called, and that's also when you close while logging in. By then, the user settings were not loaded yet, because that's done on drawing the main window IIRC. So settings should be saved only after loading the session was completed. When that's done, we can also get rid of the stuff in 609b6e82dc1653f7cbf8a0738610f35bc8ba6061 

@arielj, true, but we also need to save the stuff done in the contact list and in the conv window (expanded groups, window size, etc...)

**Comment by Sbte** [comment]
Got a fix in my head, coding it right now...

**Comment by Sbte** [comment]
That should fix that problem once and for all...

Now that Apply button would be an awesome idea, but that's a different, much harder bug.
