### ISSUE TITLE
Apply button in preferences

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#548]
@arielj on #547:

""I vote for a "Save" button on preferences, it's clearer that way and the config gets saved when the user want it and not always (we can have a check like "save windows size an position at logout" so users can also choose that).

I know we'll have to recode a lot of things on preferences and add some checks outside preferences too, but I have always felt that not having a "cancel / save" option on preferences was weird.""

It might be not that hard. We just need to put all the settings in variables at start, and just use set_default and draw_main_screen when clicking apply.

**Comment by arielj** [comment]
We can also do this on a different extension (like "AutoPreferences" and I don't know... "ConservativePreferences" (?)), I guess some people like the way it is now.

**Comment by Sbte** [comment]
Maybe it's too much effort for one extra click those people have to do?

**Comment by arielj** [comment]
I don't know, the actual preferences are already there, it's not that much effort, I like the idea of Cancel/Save/Apply buttons, but I don't know if everyone agrees on that.

**Comment by ghost** [comment]
Having all 3 Cancel/Save/Apply is a bit overkill. All you need is Save and Close.
When you press save, I think that maybe it should me grayed-out/disabled until another change is made. That way the user knows that it saved there changes or that there are unsaved changes.

**Comment by Sbte** [comment]
Most applications have Apply, Cancel and Apply + Close or OK I think.

**Comment by el-dias** [comment]
http://developer.gnome.org/hig-book/3.0/controls-buttons.html.en

**Comment by c10ud** [comment]
iirc currently the preference window changes things on the fly, which is nice. not sure on when it's saving settings to disk (never got into it) but the current behaviour seems cool to me. also, once i setup emesene i don't ever change the config again so.. (why would anyone want to do that?)

**Comment by Sbte** [comment]
Because there are awesome settings no one knows of.

Settings are saved to disk when you close emesene.

The basic idea is that you either have to click Redraw Mainscreen, or you have to restart emesene to apply the settings. People assume that because nothing changes inside emesene, their settings are not saved, because that's how it usually works.

**Comment by c10ud** [comment]
we have the close button now, can we close this issue?

**Comment by Sbte** [comment]
If you want to keep the save only on proper closure of emesene policy, or you can fix the closing signal catch, then sure. If you want users to be able to save their preferences without closing emesene properly, then no.

Edit: Maybe make the close button a save and close button?

**Comment by c10ud** [comment]
we could add to the close button the method that actually gets called by emesene when it's closed properly

**Comment by Mystro256** [comment]
I think having the close button also save the current configuration to disk seems like a good idea. That would definitely reduce confusion on the behalf of the users unaware of the proper closure policy, or even users unaware that emesene isn't closed properly.
