### ISSUE TITLE
Can't start emesene 2 on Mac 10.6.7

### ISSUE THREAD

**Issue by ninquewylia** [emesene/emesene#549]
I just downloaded, but it won't start. Instead, a TXT file named "emesene 2 Error Log" is created in my desktop containing this:

Error: 1. Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/emesene.py", line 51, in <module>
    import glib
  File "/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/**init**.py", line 22, in <module>
    from glib._glib import *
ImportError: dlopen(/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/_glib.so, 2): no suitable image found.  Did find:
    /Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/_glib.so: mach-o, but wrong architecture

Could anyone help, please?

**Comment by c10ud** [comment]
open a terminal and write:
defaults write com.apple.versioner.python Prefer-32-Bit -bool no

done. NOTE: it could break some 32bit python app you needed, because after this command osx will prefer 64bit version (emesene works on built-in 64bit)

**Comment by ninquewylia** [comment]
Still the exact same error.
What's wrong with the system?
