### ISSUE TITLE
A little about conversation and contact window

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#55]
"We" want that if I press Ctrl + up arrow in conversation windows it should show me the last lines that i wrote.
I don't like when I open several tabs, appear some arrows at the corners of the tab bar, its not "productive".
In the contact list i have some contacs with things like <span> or <small> the nick name of this contacs have many "space" stroke.
Mute sound and disable notifications its not save when I close emesene2.
And... we want blink tray icon with a new message.

Community: Thanks for this space
Keep Hacking.

**Comment by c10ud** [comment]
which os are you using? in ubuntu, the messaging menu should warn you

**Comment by andreskru** [comment]
I'm using Fedora 13, and when i receive a message appear a notification globe using the notification system of fedora that i disable from preference > notificaciones, because is annoying,  and the icon in avant window navigator blinks, but not the tray icon.

**Comment by c10ud** [comment]
doesn't fedora include the ubuntu indicators?

**Comment by andreskru** [comment]
No.

**Comment by marianoguerra** [comment]
message history implemented here: http://github.com/emesene/emesene/commit/b7553de4c2de2a613ad2c9a96fdd4046df56e78e

about the arrows in tabs, this is default behaviour in gtk, any idea on how to imrpove it?

I don't understand the "space" stroke one.

now will work on the sound state not saved.

thanks, for the report, next time open a ticket  for each request.

**Comment by andreskru** [comment]
About arrows in tab I would like too see a chromium behaviour, but the behaviour of emesene1, without the arrows, its ok.

Names in contacts list its almost solved.

Thanks.

**Comment by c10ud** [comment]
i find this mozilla-like tabs very nice for being fixed width, etc. don't you? ;_;

**Comment by andreskru** [comment]
I don't  like that when I have several conversations and some of them go hide, and i must click in the lateral arrows or enlarge the conversation window.

**Comment by EibrielInv** [comment]
@andreskru +1
configurable behaviour?

**Comment by SWOriginal** [comment]
for the blinking icon i think the best solution is to include a "indicate.png" in the themes panel folders so when a new message arrive the icon turns green such as Ubuntu messaging menu, i find the flashing icon too annoying and intrusive and is not needed when using ubuntu 10.04 onwards.

@c10ud could you enable the messeging menu and indicator now that the theme issue is fixed  :)

**Comment by c10ud** [comment]
but i'm not using maverick yet :(

**Comment by SWOriginal** [comment]
@c10ud, ok dont worry then lol :) just wanted to confirm its working :P

**Comment by marianoguerra** [comment]
please reopen an issue with each of the still open requests, I can't track which are still open,

thanks!

**Comment by andreskru** [comment]
Done

**Comment by marianoguerra** [comment]
thanks!
