### ISSUE TITLE
Can't start emesene 2 on Mac 10.6.7

### ISSUE THREAD

**Issue by ninquewylia** [emesene/emesene#550]
Well, I was here for help because of this:

Error: 1. Traceback (most recent call last):
File "/Applications/emesene.app/Contents/Resources/emesene/emesene.py", line 51, in 
import glib
File "/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/init.py", line 22, in 
from glib._glib import *
ImportError: dlopen(/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/_glib.so, 2): no suitable image found. Did find:
/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages/gtk-2.0/glib/_glib.so: mach-o, but wrong architecture

then c10ud said to do this:

"open a terminal and write:
defaults write com.apple.versioner.python Prefer-32-Bit -bool no

done. NOTE: it could break some 32bit python app you needed, because after this command osx will prefer 64bit version (emesene works on built-in 64bit)"

and closed the issue.
Well, it's not loading yet, and the exact same error continues...

**Comment by marianoguerra** [comment]
I think the compiled gtk libraries are for 32/64 bits and your achitecture is the other one

**Comment by ninquewylia** [comment]
Well, I never used Python. I have a late 09 Intel Macbook with Snow Leopard installed.
I don't know what could be possibly wrong about that.

**Comment by ninquewylia** [comment]
Would anyone help? I'd really like to use emesene!

**Comment by ghost** [comment]
Run this in terminal:
mv ~/Library/Preferences/com.apple.versioner.python.plist ~/Library/Preferences/com.apple.versioner.python.old

If it doesnt work, try unistalling emesene and reinstalling

**Comment by ninquewylia** [comment]
Did not work, I got the exact same error as before.
OK, why the f is this happening? I never changed anything on my mac installation or Python's.
I tried installing Python 3.2, but it had no impact.

And one thing... Why is emesene looking for Python files inside the emesene.app? As far as I understand the program is trying to find some python files inside emesene.app contents, right?
Isn't it supposed to look for python files in my system instead?

**Comment by ghost** [comment]
Python looks inside emesene.app, because the GUI is written in PyGTK which does not come on OS X by default. The application bundle contains a 64bit version of PyGTK and some theme engines.

The only thing i can think of is that emesene is trying to use Python 2.5
Try running: defaults write com.apple.versioner.python Version 2.6

The issue is definitely something to do with your system's architecture, as i was able to reproduce the issue by setting mine to 32bit.

Are your running OS X is pure 64bit mode?

**Comment by ninquewylia** [comment]
This one did not work as well.
Returned the same error log...

Well, I don't know if I'm running OS X in 64bit mode. How can I know?
The only thing I can tell is that I'm using OS 10.6.7 on the latest Macbook.

**Comment by ghost** [comment]
I am completely out of ideas. I was able to reproduce the exact error message and the commands i gave you should have fixed it.

Have you any experience with terminal and Xcode? If so you could try building your own PyGTK.

**Comment by ninquewylia** [comment]
No, I don't.
Well, thank you anyway. I just wanted to click and run...
I made the emesene run by using the python 2.7 packages inside the emesene.app contents... I put it there it went ok, but... It only shows facebook and google mail... and some tummy thing I never heard of.

**Comment by ghost** [comment]
Python 2.7 is not system Python, so that probably why its not working.

To get MSN working you need papyon:

Open Terminal and run:

curl -o papyon.tar.gz http://www.freedesktop.org/software/papyon/releases/papyon-0.5.5.tar.gz
tar -xf papyon.tar.gz
cp -R papyon-0.5.5/ /Applications/emesene.app/Contents/Resources/emesene/e3/papylib (adjust if your running emesene from somewhere else)

**Comment by ninquewylia** [comment]
Just tried.
Exact same error...

**Comment by ghost** [comment]
"I made the emesene run by using the python 2.7 packages inside the emesene.app content"

What files did you copy and what what the folder you put the files in?

**Comment by ninquewylia** [comment]
I copied the "python2.7" folder into the lib folder.
I think I used its 'site-packages' folder in the python 2.6 folder. I dunno... I was trying to find some 64bit glib... I know nothing about programming, I was just guessing and it worked, but badly, since I could not see the MSN option to log in, just the facebook, tammy and gmail...

**Comment by ninquewylia** [comment]
This is the new error log:

Error: 1. Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/emesene.py", line 51, in <module>
    import glib
  File "/Library/Python/2.6/site-packages/gtk-2.0/glib/**init**.py", line 22, in <module>
    from glib._glib import *
ImportError: dlopen(/Library/Python/2.6/site-packages/gtk-2.0/glib/_glib.so, 2): no suitable image found.  Did find:
    /Library/Python/2.6/site-packages/gtk-2.0/glib/_glib.so: mach-o, but wrong architecture

**Comment by ghost** [comment]
How do you have Python 2.7 when system Python is 2.6?

**Comment by ninquewylia** [comment]
I downloaded it from python.org and used its 'site-packages'.

The problem is that I was not able to log in through msn.

**Comment by c10ud** [comment]
messed up system, not an emesene issue (google group should be better for this kind of things)
