### ISSUE TITLE
New webpage - missing previous build links

### ISSUE THREAD

**Issue by pguridi** [emesene/emesene#552]
I could not find any better place to submit a bug report about the new emesene page(blog), so I apologise If this is not the correct place.

With the previous webpage, it was really easy to google and download the latest emesene 1.6.x for windows,
specially for the end users, so it was easy to suggest people to change to emesene.
Now with the new page, I could not find any link to the same builds... it doesnt explain either what happened with the
previous content. Did it disappear?. Deleted? , Or can I download still emesene 1.6.x?  Where? (Until emesene2 is stable in all platforms, I think it is reasonable providing the actual stable builds.).
I know that I can download the .exe from sourceforge .., but for most non-tech end users, that is almost the same than delete the files.
Would be nice to have in the download page of the new blog, a brief explanation of what is going on with emesene/emesene2, and inform properly that I have two options.. download the latest emesene 1.6.x stable, or testing the future version.

Regards
Pedro Guridi

**Comment by c10ud** [comment]
thing is, emesene-1.6.3 is not stable as emesene2 technically
speaking, so it's reccomended everyone upgrades to the new version

2011/5/17 pguridi
reply@reply.github.com:

**Comment by pguridi** [comment]
According to the blog:
"Windows: experimental package here: http://www.fileserve.com/list/3sn6UZV
This is a test versions only and do come with some issues. One of these is that it will crash if 'adium output' is selected. Use 'OUTPUT TEXT' in Preference > Extensions." 

It does not sounds too stable. Which for me makes sense, because latest emesene2 is really recent.
Considering that comment from the blog.., are you saying that the emesene2 experimental package, is more stable than the previously available emesene 1.6.x packages?.

However.., wouldnt be reasonable to provide links to all builds and previous versions (like all open source projects do), than hide them from the project webpage?. So the user can decide which version wants to use?.
I dont know if Im the only one who see it this way, but for me makes sense to provide both versions, and more now during the transition emesene2. For example I use emesene2 on linux, but on windows I still prefer emesene 1.6.x.

Regards

**Comment by c10ud** [comment]
emesene-2 is stable, it's just the windows packagers didn't find how
to fix that issue till now (seems like it's some weird dll breaking
things) and yes, i am saying that. i don't want people to use 1.6.x
anymore because it breaks user profiles and leads to strange bugs when
using valid clients like emesene2.

2011/5/17 pguridi
reply@reply.github.com:

**Comment by arielj** [comment]
@pguridi, can you try the newest package? it will help, if we find this works on more computers we can put a non experimental exe to download and everyone's happy :P

http://www.mediafire.com/?bizvmartggtajpa

**Comment by ghost** [comment]
@arielj anything changes in the packaging process that I need to know about? dlls?

Also I also kind of mess the old front page but understand wanting to get people to read the latest news directly.

**Comment by arielj** [comment]
I just didn't do this command from mariano's guide

cp ../dlls/\* .

the rest is exactly the same

I have to check those dll's agains mines, because I don't need them to run emesene, I already got some dll's inside python's folders

**Comment by pguridi** [comment]
@arielj:
This ticket is not about any issue regarding emesene2. Probably I was not clear in my comment, but it was about what i think is an _usability_ issue on the webpage, not any packaging or programming bug.
That right know, i find difficult to just say to any non-tech friend "hey, switch emesene is great.. google it and download it", when before it was very clear and easy to download it, now it became much more difficult..

Beside that, I tried emesene2 on windows, but after having some issues with the build ( anyway i think i tried not the one you posted now, the previous one), I just downloaded the sources and made a build for me, with my dlls and worked fine.
But again, that is not my point..., i can do it , but i can not expect a normal user, with no experience in such technical stuff, to be able to do it.
I think emesene is a great client, and is on the right way, but that small issues like the one I post, can have a negative effect on userbase quantity, which I think, due the status of emesene, could be much more.

Regards

**Comment by c10ud** [comment]
we don't seek for consensus, we do it for ourselves (i guess..?).
given that, there's a windows build out there, if you can make a
better one why didn't you share it? until someone provides a better
windows download, we'll stick with it

2011/5/18 pguridi
reply@reply.github.com:
