### ISSUE TITLE
ctrl+tab shortcut

### ISSUE THREAD

**Issue by veribaka** [emesene/emesene#553]
Not sure if this is an issue, maybe more of a small inconvenience. Emesene used to switch tabs when I used ctrl+tab, and it doesn't atm. Besides that, it's a little bit annoying that it doesn't memorise the place where I moved the main window to, so it will always pop up on the left after moving it to the right. That's not something I absolutely need, it's another minor convenience :)

Thank you for the good work on this program, it's been a great aid to fight work boredom :D

**Comment by Sbte** [comment]
Ctrl+Tab is implemented in the latest development version. 

To save your window position, you have to properly exit emesene (go to File->Quit). In the latest development version, this should also be fixed.

**Comment by mahmoudhossam** [comment]
I have 2.11.4, I don't know if that's the latest development version or not, but Ctrl+Tab isn't working.

**Comment by Sbte** [comment]
It's not, the development version is 2.11.5-devel. 

Instructions on how to install it using git are here:

http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html

Or you could just wait for a new release.

**Comment by c10ud** [comment]
all of this, fixed in git master :)

2011/5/18 veribaka
reply@reply.github.com:

**Comment by veribaka** [comment]
Just installed 2.11.5. Everything is fine so far, will try to notify if I find anything else that might not be working as intended.

Thank you very much! :)
