### ISSUE TITLE
Emoticone Issue

### ISSUE THREAD

**Issue by ernesto96** [emesene/emesene#556]
I cant see personalized emoticons or the default ones =S i can see in version 2 but i cant in version 1.6.x i reinstalled and it didnt work

No puedo ver los emoticonos personalizados o los normales, los puedo ver en la version 2 pero no en la 1.6.x lo reinstale y sigue teniendo el mismo problema

https://lh3.googleusercontent.com/_AxxdKqBO1cA/TdRmHmkQm3I/AAAAAAAAAMg/L8eamFXblOc/Captura2.PNG

**Comment by arielj** [comment]
Sólo errores de emesene2.

Revisá la configuración de tu emesene1, hay una opción para ver emoticones, si no quizás sea un plugin.

Si sigue sin andar te conviene usar usar el emesene2
