### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ernesto96** [emesene/emesene#557]
Links doesn't work. i click it but a page didn't show up. i actually use Windows 7 ultimate 64bits with predeterminated web browser mozilla firefox 4.0 

Los links no sirven. le doy click pero no me abre ninguna pagina, uso windows 7 ultimate 64 bits con firefox 4.0 como navegador predeterminado

(En emesene 2 claro)

**Comment by arielj** [comment]
Hi, what output extension are you using? Adium or Text? (check on preferences > extensions)

Hola, qué extensión estás usando para la conversaciones? AdiumOutput o TextOutput? (fijate en preferencias > extensiones).

Revisá la terminal a ver si da algún error o algo.

**Comment by ernesto96** [comment]
Al arecer hay un error en el manejando el explorador y use el "audio o text" es la misma 
https://lh6.googleusercontent.com/_AxxdKqBO1cA/TdWVv18ZKRI/AAAAAAAAANA/SAs_jxepXkQ/errorlink.png

**Comment by arielj** [comment]
Hola, el link me funciona correctamente a mi con Windows XP, al parecer es un problema de tu explorer, que no tiene bien asignado el programa para usar para abrir páginas web.

Probá cambiar de navegador por lo menos para probar los links, yo acá uso XP y Opera 11.5 y lo abre sin problemas.

**Comment by arielj** [comment]
@ernesto96, alguna novedad?

**Comment by ernesto96** [comment]
Pues, Sigue sin dejarme pero no le eh hecho la lucha, realmente, y ahorita ando bastante ocupado en otras cosas, gracias por la atencion
