### ISSUE TITLE
Emesene remembers the same password for different protocols

### ISSUE THREAD

**Issue by jpcristian** [emesene/emesene#558]
Si tengo un msn que es sas@gmail.com osea, asociada y a mi cuenta passport de msn

y ademas una cuenta en gmail que sea igual.

No puedo iniciar sesion si recuerdo contraseña de alguna de las 2. y mucho menos recordar sesion de ambas.

Edited by: Arielj
Reason: Title, Description, English

I have the same email address for both gtalk and msn networks but with different passwords. Emesene saves the same password for both, when it should save a password for each account for each different protocol.

I think it's a regression, I believe it worked ok some time ago...

**Comment by arielj** [comment]
Te da algún error? algo? sin más información no podemos hacer nada

**Comment by jpcristian** [comment]
No es que de error. Si yo pongo mi cuenta asd@gmail.com en msn y guardo contraseña.
No voy a poder poner asd@gmail.com en modo google talk y abrir esa cuenta ya que recuerda la de msn y puedo no tener la misma contraseña en ambas cuentas.

**Comment by arielj** [comment]
Hola, ya entendí bien el problema, te edito el post principal así lo pongo bien explicado y en inglés, así puede ayudar más gente.
