### ISSUE TITLE
Slider refuses to stay present when adding a new avatar

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#559]
To reproduce, select a new avatar by going to avatar chooser and look for a new image. If the box ("Image chooser") listing your folders for selecting a new image is too small to list all available folders, in ubuntu 11.04 by default the slider will appear on the right hand side to scroll with.
The bug is that if you try to actually use the slider, it fades before allowing you to scroll. The only work around is to make the image chooser window larger, so you can see the rest of your folders.

**Comment by Antonius-git** [comment]
http://www.imageupload.org/?d=40022B131 is where the problem occurs.

**Comment by Mankeke** [comment]
Hi, I tried to reproduce the error you had (using Slackware 13.37 and the latest git version of emesene ) but in my case the problem doesn't happen, I can use the slider perfectly, it doesn't fade away. However, i'm not using gnome as my window manager but xfce 4.8.

**Comment by EchoUSB** [comment]
I think it's not an emesene related issue, it's just about ubuntu/gnome , isn't it ?

**Comment by arielj** [comment]
I don't think it's an emesene bug... Can someone with Ubuntu 11.04 check that? I guess it's a bug on that new feature

**Comment by EchoUSB** [comment]
I don't have this bug in ubuntu 11.04, but I'm not using gnome so I don't know.

**Comment by Sbte** [comment]
It's an ubuntu bug for sure, but maybe there's a way to work around it...

**Comment by Antonius-git** [comment]
I've posted a bug about this on launchpad (https://bugs.launchpad.net/ubuntu/+source/overlay-scrollbar/+bug/786556), hopefully someone will be able to fix it soon :)

**Comment by c10ud** [comment]
not an emesene bug
