### ISSUE TITLE
tray/ indicator uses the wrong icons 

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#56]
when using other image themes emesene uses the indicator/tray icons from the _default_ theme instead this needs to be fixed using the following solution

_solution_

1 - we should use a separate folder for panel icons...

This would work best for custom themes using a dark panel background with a light window background ( ambiance theme ).

The Ambiance theme requires light icons for the panel and dark icons for the window

the best solution would be to make the indicator/tray use icons from a seperate folder included in the theme

so icons for the window should stay _/emesene/themes/images/"theme-name"/_

but icons for the panel should be  _/emesene/themes/images/"theme-name"/panel/_

**Comment by c10ud** [comment]
we didn't decide what to show in the tray/indicator yet (i think) so there's still to discuss here, thanks for the ideas

**Comment by SWOriginal** [comment]
ok i think my suggestion is good as people could change the icons based on what theme there using and also use the adium menu bar icons from adium xtras.

im currently making a themes suite for emesene 2  and the only way to change the icons are to rename the default theme and make a new default theme with the panel icons im using.

i have little programming skills so i doubt id get anywhere if i tried to do this myself.

**Comment by c10ud** [comment]
working on that, i'm stuck since appindicators don't allow changing theme path while running, but it should work for gtk tray icon

**Comment by SWOriginal** [comment]
its progress :), is there not away to automatically create links from the /panel folder from the chosen theme to the default theme folder?

**Comment by c10ud** [comment]
symlinks, but they're unavailable in windows. anyway if the panel folder doesn't exists emesene will use the "standard" ones

**Comment by SWOriginal** [comment]
i still cant get it to use the icons from _theme_/panel/

it now just uses the icons from default/panel/

this isnt a problem as i could just replace the icons in default/panel but average users would like to set the theme and expect the panel icons to change aswell without going into system folders

**Comment by c10ud** [comment]
it's an unfeature in appindicator. 
once we load the indicator with a given theme folder we can't change it, so since we load emesene with a given theme (default), the indicator keeps getting the icons from the default theme.

we can fix this two ways:
- save latest theme used and load it
- ask appindicator developers to add a way to change theme directory while an indicator is running (i tried patching it, but i can't build it since the build system is fucked up) 

the first option is the easiest, but how about different accounts with different themes? maybe we shouldn't care about this... i could make this as a temporary workaround though.

**Comment by SWOriginal** [comment]
the first option seems to be the best solution, i suppose the account problem would be an issue with most users tho. 

would there be a way to end and restart the appindicator on sign in/out ? that way there could be a config file in the users home/.config/emesene2/ directory that determines which panel icon theme to use based on account

its so annoying ubuntu developers have really complicated things with the appindicators

**Comment by c10ud** [comment]
https://bugs.launchpad.net/indicator-application/+bug/607831

**Comment by c10ud** [comment]
i worked in team with an ubuntu member and we fixed this issue in indicator-applications! now we just hope to get this accepted and pushed in mainline so users from maverick can benefit of this feature! 

https://bugs.launchpad.net/indicator-application/+bug/607831

**Comment by c10ud** [comment]
Now, if someone wants to "port" this feature to the "normal" gtk trayicon........it should work already :)

**Comment by c10ud** [comment]
I disabled Indicator support until we get that bug reviewed and fixed upstream. Meanwhile you can play theming the usual gtk.TrayIcon :)

**Comment by c10ud** [comment]
closing the issue for now

**Comment by SWOriginal** [comment]
ok thanks :D, it works using tray icons so hopefully theres nomore issues when you activate indicator again :)

**Comment by c10ud** [comment]
:)

**Comment by c10ud** [comment]
closing for now
