### ISSUE TITLE
Problemas con la transferencia de archivos

### ISSUE THREAD

**Issue by invazor** [emesene/emesene#561]
Hola.

Tengo emesene 2.11.4, y cuando mis contactos me envían un archivo, este no lo recibo, y a mis contactos les indica que cancele la descarga. el programa no indica que estoy recibiendo el archivo ni nada, pero yo si puedo enviar archivos a mis contactos.

esto pasa en Ubuntu Natty y también en Maverick.

por su atención gracias.

**Comment by arielj** [comment]
Usás una ventana de conversación con pestañas o ventanas separadas para cada contacto?

Parece un duplicado de #499

**Comment by invazor** [comment]
Hola arelj.
Lo he intentado de las dos maneras, pero el error sigue en cualquiera de las configuraciones.
Y si como comentas parece un duplicado de #499, y al final mencionan lo de las ventanas separadas pero a mi me sigue sin funcionar.

**Comment by arielj** [comment]
Si corrés emesene desde una terminal te marca algún error o algo?

**Comment by c10ud** [comment]
see #499

**Comment by invazor** [comment]
disculpas,pero tuve problemas con mi proveedor de internet.
Esto me pone en la terminal. saludos y gracias.

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"
