### ISSUE TITLE
emesene crashes with blank window

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#565]
Just using emesene, the windows become blank, and I have to kill it (screen:  http://www.noelshack.com/1/1/2011-05-21-214826_1366x768_scrot-15b8bd1914.png )
Error:

<pre>
(emesene:2018): GStreamer-CRITICAL **: Failed to deactivate pad wavparse8:sink, very bad

(emesene:2018): GStreamer-CRITICAL **: Failed to deactivate pad typefind:src, very bad

(emesene:2018): GStreamer-CRITICAL **: 
Trying to dispose element typefind, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

(emesene:2018): GStreamer-CRITICAL **: 
Trying to dispose element decodebin8, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.
</pre>

**Comment by c10ud** [comment]
your gstreamer is broken, not an emesene bug
