### ISSUE TITLE
suggestion: search as we type

### ISSUE THREAD

**Issue by jjnilton** [emesene/emesene#566]
just a suggestion to avoid use ctrl+f everytime to search a contact...

**Comment by Sbte** [comment]
And what about hiding then? Most people would probably not expect ctrl+f to work since they didn't have to use it for the search box to pop up, so they could find it annoying to get it away.

Maybe it's better to keep it the way it is.

**Comment by Mystro256** [comment]
yeah I agree with @Sbte, this is a functionality from the official client I find quite annoying. Especial when you misclick. I really don't find it that troublesome to hit ctrl+F or click the search button.

Maybe as a plugin or option in preferences?

**Comment by jjnilton** [comment]
so, put a fixed search form option, would be a alternative

2011/6/13 Mystro256 <
reply@reply.github.com>

> yeah I agree with @Sbte, this is a functionality from the official client I
> find quite annoying. Especial when you misclick. I really don't find it that
> troublesome to hit ctrl+F or click the search button.
> 
> Maybe as a plugin or option in preferences?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/566#issuecomment-1361283

## 

_Jos Nilton R. Junior_

**Comment by Sbte** [comment]
So then you'd have to use the mouse to click it. Either that, or you click the search button on the top as it is right now. 

Someone could probably write a plug-in that forces the search field to load by default or even make it have focus, but I don't think this belongs in the main tree
