### ISSUE TITLE
Unable to connect to msn network

### ISSUE THREAD

**Issue by conscript93** [emesene/emesene#567]
upgraded to emesene 2 today and i'm unable to connect to the msn network. I'm using ubuntu 10.04 on an acer aspire one. While trying to connect using emesene 2 it stays in a loop. running it from a console I get:

[21:30:43 WARNING papyon.protocol] Notification unhandled command : GCF 0 5700
    [payload]
<Data><UserTileLocation>0</UserTileLocation><FriendlyName>Ygor</FriendlyName><RUM></RUM><PSM></PSM><MachineGuid>81571660-298C-6C09-1537-556819672610</MachineGuid><DDP></DDP><CurrentMedia></CurrentMedia><EndpointData id="{81571660-298c-6c09-1537-556819672610}"><Capabilities>2416181284:2147619840</Capabilities></EndpointData><PrivateEndpointData id="{81571660-298c-6c09-1537-556819672610}"><EpName>pidgin</EpName><Idle>false</Idle><ClientType>1</ClientType><State>NLN</State></PrivateEndpointData></Data>
[21:30:46 WARNING papyon.p2p] Invalid MSNObject: 0
[21:30:49 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
[21:30:49 WARNING papyon.service] Transport Error :500
[21:30:49 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
[21:30:49 WARNING papyon.service] Transport Error :500

is it something wrong with my system? I've read a little about it and found something related to python-papyon. I've upgraded the package and it's now version 0.5.5-1ubuntu1.2, the latest for my distro.

ps.: sorry about the english... i'm brazilian.

**Comment by c10ud** [comment]
papyon should be ok, it's just the server is not sending you your contact list, etc. maybe it's a temporary network issue, do other client work?

**Comment by conscript93** [comment]
It doesn't seems to be temporary. I've switched back to emesene 1.6 and it works perfectly. also an old version of pidgin i have installed here worked right.

**Comment by c10ud** [comment]
iirc emesene1 works even without receiving the contact list from the server, i don't remember so well though

**Comment by c10ud** [comment]
i had this issue when using python-papyon 0.5.4, please make sure you have the latest version

**Comment by Sbte** [comment]
It's in here:

https://launchpad.net/~emesene-team/+archive/emesene-stable

**Comment by conscript93** [comment]
it's been some time, sorry. Now i've installed the new papyon and emesene2 packages, still unable to connect, but the error looks different. On the console it just writes 

[17:17:00 WARNING papyon.client] already logged out

and it keeps trying to connect. Using HTTP mode it is able to connect, but with some problems about offline messaging.

**Comment by c10ud** [comment]
original issue should be fixed now

try with papyon-0.5.6 (currently unreleased) we will probably make emesene-2.11.8 dependent on that version
