### ISSUE TITLE
Improvement suggestion: allow own email address as contact to mirror your current status.

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#568]
Allow me to explain - In  emesene 1.6.*, if you have your own email address as one of your contacts, you showed up in your contact list with the same status, avatar and personal message etc  
It's a really good way of seeing how you come across on other people's contact list.
Right now, i still have my address as one of my contacts, but regardless of my status, it shows me always offline. Obviously, i'm not looking to have a conversation with myself lol But it was a good feature because it made it easier to see if you needed to tweak your name/personal message sightly.

Could you implement this feature in emesene 2 please?

**Comment by Sbte** [comment]
I looked into this a while ago I think, and IIRC it was a bug in papyon.

**Comment by c10ud** [comment]
bug in papyon, please report upstream: https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by c10ud** [comment]
not possible with current WLM changes
