### ISSUE TITLE
Improvement suggestion: Some form of tool/gui to add colour/font effects to your name/personal message

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#569]
I noticed when i logged in to a 'dummy' session that contact names can not only have colours but even a colour gradient (i.e. varying shades of one colour to another). I remembered back to when i used to use Windows live messenger with messenger plus and i see the tags are the same :) 

For example, i tried: [c=#3369F7]blue?[/c] yep. lol [c=#F00000]red?[/c]  And they worked :)  

( I had to go to the gnome colour wheel to find that #3369F7 is a kind of blue of course lol.)

So....what would be a cool new feature is some sort of screen to select a colour for highlighted words in the personal message or name section. I.e. you highlight the word(s) you want, click a nearby button, choose the colour you want and then "ok"/"apply" to change it.  Maybe add some effects too? Like "rainbow coloured" or "colour gradient" and of course the typical "bold", "italic", "underline" and "strike through". 

You can already change the colour/font of the text you enter in a message window, so this seems like a good step forward. :D

**Comment by marianoguerra** [comment]
you should ask this as a plugins since it's a msnplus specific thing (it's not even natively supported by msn)
