### ISSUE TITLE
unable to logout to use another service

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#57]
i think its a problem with auto login, when signing out it signs me straight back in again so i cannot use another service, also on startup when pressing the cancel button it continues to sign in

**Comment by arielj** [comment]
the cancel problem should be fixed on one of my commits, wait for someone to push it here, the autologin problem... I don't know :P

**Comment by SWOriginal** [comment]
Ok thats good to know, hopefully this should be fixed soon
