### ISSUE TITLE
Window not responding, but still receiving messages

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#570]
Sometimes the chat window stops working. I still receive messages but I can't click buttons or write anymore.
There is no error when it happens, only this one when closing the buggy window:

<pre>
/home/echo/Téléchargements/emesene-emesene-95c71d3/emesene/gui/gtkui/__init__.py:102: GtkWarning: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
  gtk.main()
</pre>

Same for the main window, so I have to kill the process.

**Comment by Sbte** [comment]
Does it happen randomly, or at certain events?

**Comment by EchoUSB** [comment]
Randomly. I didn't notice any special event at this time.
A friend sent a message about 30 secs ago, trying to answer and.. the window's not working.
It happened a few times already, I noticed nothing special

**Comment by Sbte** [comment]
You just made an update to TextBox, so just wondering. Does it also happen with Adium?

**Comment by EchoUSB** [comment]
I don't know.
I'll use Adium for a few days to see if it happens, but it doesn't happen very often, so ... I'll need some time to be sure

**Comment by EchoUSB** [comment]
It doesn't happen with Adium.

**Comment by Sbte** [comment]
Since this bug is kinda vague, it could have been fixed by recent nudge or subscription fixes. Could you maybe try again in latest git? Or just keep using Adium instead ;)

**Comment by c10ud** [comment]
lets' close this till new info is avail, this is too generic and btw adium output is way better :D
