### ISSUE TITLE
how to download images of contacts?

### ISSUE THREAD

**Issue by jjnilton** [emesene/emesene#574]
clicking i can see the history of avatars of my contacts but i don't know how to download it, when i click with left button of mouse nothing happens.

**Comment by Sbte** [comment]
They are in .config/emesene2/.....

If you want to use them as your own avatar, you can select them from Avatar chooser -> Contact pictures.

**Comment by jjnilton** [comment]
So, I let the suggestion to put "save to" in avatar history or something
like it.

Em Dom, 2011-05-22 às 12:46 -0700, Sbte escreveu:

> They are in .config/emesene2/.....
> 
> If you want to use them as your own avatar, you can select them from Avatar chooser -> Contact pictures.

**Comment by jjnilton** [comment]
Em Dom, 2011-05-22 às 12:46 -0700, Sbte escreveu:

> They are in .config/emesene2/.....
> 
> If you want to use them as your own avatar, you can select them from Avatar chooser -> Contact pictures.
