### ISSUE TITLE
too many emoticons freezes emesene

### ISSUE THREAD

**Issue by felip3** [emesene/emesene#575]
everytime i press the emoticon button in a conversation window it freezes for a couple minutes until it start to show it all moving way too slow, of course its caused cuz i have 100+ gif emotes. but there is no workaround this? maybe displaying them as stills instead of animated??

**Comment by c10ud** [comment]
emesene/gui/gtkui/Dialog.py -- line ~ 1250 probably the _get_emo_image(self, path, size) method should be replaced with something in gui/gtkui/utils.py that does a little caching so it remembers the emoticons once you open the dialog once...

**Comment by c10ud** [comment]
oh wait, we are already doing that for static images

```
def _get_emo_image(self, path, size):
    '''try to return an image from path
    '''
    width, height = size
    try:
        animation = gtk.gdk.PixbufAnimation(path)
    except gobject.GError:
        return None

    if animation.is_static_image():
        pix = utils.gtk_pixbuf_load(path, (width, height))
        picture = gtk.image_new_from_pixbuf(pix)
    else:
        myanimation = utils.simple_animation_scale(path, width, height)
        picture = gtk.image_new_from_animation(myanimation)

    return picture
```

the trick is with animated emoticons -- probably we should use static pics instead of resized gifs....
