### ISSUE TITLE
TextBox not scrolling to end

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#576]
Screenshots will explain better. Right window is using the current source, left window is a quick fix.
http://www.noelshack.com/1/1/2011-05-23-094515_1366x768_scrot-c42d954963.png
http://www.noelshack.com/1/1/2011-05-23-094538_1366x768_scrot-9e4f5fb959.png
http://www.noelshack.com/1/1/2011-05-23-094601_1366x768_scrot-ebaa234d29.png
http://www.noelshack.com/1/1/2011-05-23-094623_1366x768_scrot-409302b38.png
http://www.noelshack.com/1/1/2011-05-23-094638_1366x768_scrot-4c96b61d12.png

Obviously, the window is not scrolling enough.

In emesene/gtkui/TextBox.py, I changed 

<pre>    def scroll_to_end(self):
        '''scroll to the end of the content'''
        end_iter = self._buffer.get_end_iter()
        self._textbox.scroll_to_iter(end_iter, 0.0, yalign=1.0)</pre>

to

<pre>    def scroll_to_end(self):
        '''scroll to the end of the content'''
        self._textbox.scroll_mark_onscreen(self._buffer.get_insert())</pre>

and it seems to be OK now. (I've seen this in the PyGTK FAQ)
The only  problem with my fix is , if you click inside the text, it will scroll to this point, no more to the end. (Clicking the end of the text solves it)

So I don't know, maybe there is a better way to fix it, but this one is already better

**Comment by Sbte** [comment]
Sounds like what emesene 1 did, so yes, I guess that would be the correct fix. Go ahead and make a pull request if you want ;)
