### ISSUE TITLE
contactos desadmitidos y offline

### ISSUE THREAD

**Issue by andresdegano** [emesene/emesene#582]
espero alguien pueda ayudarme. de un momento a otro me apareció toda la lista de contactos desadmitida. entonces volvi a admitir a todos los contactos uno por uno. y cuando reinicie emesene todos los contactos me aparecen offline. en windosw live si me aparecen correctamente.
estoy usando fedora 14  y emesene 1.6.3 - "Uberlândia"

muchas gracias

**Comment by Sbte** [comment]
Emesene 1.6 is deprecated. Please use emesene 2.

Instructions on how to get the latest git version here:

http://blog.emesene.org/2010/10/instructions-for-testers.html

There's also a Fedora package somewhere for 2.11.4, but there should probably be a new one in a few days when we release emesene 2.11.5.
