### ISSUE TITLE
Problem connecting msn&gtalk

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#583]
When click the 'connect' button almost inmediatly appears the 'reconnecting in 29 seconds' message. Also if i type a wrong password!

I have installed:
emesene to latest git version (git pull origin master && git submodule update)
papyon-0.5.5
python-2.6.6
pygtk-2.24.0
gtk+-2.24.3
networkmanager-0.8.4.0
xmpppy-0.5.0_rc1

the only message in console is:
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)

**Comment by c10ud** [comment]
is your networkmanager connected? we're checking against it

**Comment by ivanalejandro0** [comment]
i've added the networkmanager version because i saw a closed issue in wich appears.
I'm not really using it, to connect to my wireless network i'm using wicd (and wicd-client-kde which blocks knetworkmanager).
from command line detected that nm is running but isn't connected despite i'm online :S.

what could i do?

**Comment by c10ud** [comment]
connect with network manager, or uninstall it :D or patch emesene to don't support it anymore :(

**Comment by Sbte** [comment]
Or make an extension that supports wicd?

**Comment by ivanalejandro0** [comment]
i've uninstalled networkmanager but the problem persists, I think the choice boils down to do a patch or make an extension for wicd :) (to me is the best choice)
I'll study the emesene code to try to resolve and i let you know if achieve someting.

**Comment by Sbte** [comment]
If you want to try to find out if that's the problem, just set 

DBusNetworkChecker = None

in emesene.py at line 77 or so.

**Comment by ivanalejandro0** [comment]
indeed, that's was the problem...
there should be an option to disable the connection status through NetworkManager for users who don't need? or maybe to select the connection client (NetworkManager, wicd, etc)?
should i create a new issue with this info?

**Comment by Sbte** [comment]
ivanalejandro0, does it come further with the latest commits? I made some recent changes, so maybe it just works now. If not, we should probably check in the NetworkMananger is even running.

**Comment by ivanalejandro0** [comment]
I wasn't using the latest commits, i kept trying to solve the problem in the same scenario.
Sbte, with your commits it works great!
if i'm connected and the NetworkManager daemon is not running (it doesn't matter if its installed) just works :)

**Comment by Sbte** [comment]
Accidental fixes are awesome, yay!
