### ISSUE TITLE
no icon in the lower right corner

### ISSUE THREAD

**Issue by detlilleegernsven** [emesene/emesene#585]
Can't se any icon in the right lower corner(the blue icon that looks like a person) and when minimising emesene 2.11.4 by clicking on the x, emesnene desapears and theres is no way to open it again, i have to let it be in my taskbar(only minimising it ,not clicking on x) along with all my other aps that i have open. Using mint 11 64 bit

**Comment by Sbte** [comment]
Do you have the tray icon enabled in Preferences->Extensions->tray icon?

**Comment by detlilleegernsven** [comment]
I think it's on, but don't no how to see if it's on or off. With my wifes laptop mint 10 and emesene 1.6.3 theres is no problem

**Comment by Sbte** [comment]
Oh, sorry, in 2.11.4 there was no option yet to switch it off. Does linux mint have the messaging menu by any chance?

**Comment by detlilleegernsven** [comment]
message menu ?  (using a danish ver of mint 11 64bit9

**Comment by Sbte** [comment]
It's something used in ubuntu where mail clients, messaging clients etc are. I'm not sure if linux mint uses it. Probably not. But if it's there, that would explain where the icon went...

**Comment by detlilleegernsven** [comment]
still not sure if theres a message menu, no how to translate message menu to danish, but i can't seem to find something relateted to message menu

**Comment by detlilleegernsven** [comment]
would the 1.6.3 ver that works with mint 10 be something i could try to se if it's emesene that causes the problem ?

**Comment by Sbte** [comment]
It's a white envelope in the tray icon area.

Anyway, is the emesene process still running when you close it? Or did it stop running? 

Also, did you try to close it while logged in or while logged out?

**Comment by Sbte** [comment]
emesene 1.6.3 is something totally different. emesene 2 is a build from scratch.

**Comment by detlilleegernsven** [comment]
no  white  envelope (don't think i deleted it)
Yes the emesene proces is still running when i close it using x in emesene
Tried closing emensene while logged in (i never see the blue tray icon, with emesene 2.11.4)

Mint 11 64 bit works verry good dispite the fact that it hasn't be released as a final, stable version.

**Comment by Sbte** [comment]
Does running it from a terminal tell you anything?

**Comment by detlilleegernsven** [comment]
emesene
/usr/share/emesene/emesene/gui/gtkui/**init**.py:102: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[11:40:29 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[11:40:29 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[11:40:29 ERROR papyon.service.content_roaming] Content Roaming service got error: HTTP Error (404): Not Found

**Comment by detlilleegernsven** [comment]
But emesene works fine(except for the tary icon/ minimizing problem)  don't even have to ad something to make i start automatic like i have to do with aMSN

**Comment by Sbte** [comment]
Weird. I suppose it should be there. Maybe you could try emesene 1.6.3 to see if it's not your fault? Btw, don't log in with emesene 1.6.3. It breaks your profile.

**Comment by c10ud** [comment]
maybe in mint there's the messaging menu, but disabled. however, if you could run emesene from git selecting the "normal" tray icon works. we plan to release a new version soon btw

**Comment by detlilleegernsven** [comment]
:) tried to install emesne 1.6.3 but me and tar gz files don' match so well så have to use emesene 2.11.4 or mabye aMSN i dont no..... prefer emesene

**Comment by detlilleegernsven** [comment]
when will the new version be released

**Comment by Sbte** [comment]
If everything goes well, this weekend.

**Comment by detlilleegernsven** [comment]
wauuuw

**Comment by andresql** [comment]
In having the same problem, if i run emesene in the terminal I get:

andres@andres-Mint ~ $ emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
/usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha,base64,random,dispatcher,re
/usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
[00:12:37 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from blufiles.storage.msn.com:80
[00:13:41 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6}
[00:13:41 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6}
[00:13:43 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6}

**Comment by detlilleegernsven** [comment]
andresql  whar os er you using also min 11 64 bit like me ?

**Comment by detlilleegernsven** [comment]
Stil getting the same ERROR starting emesene in the terminal and much like the problems as andresql

emesene
/usr/share/emesene/emesene/gui/gtkui/**init**.py:102: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[09:42:04 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[09:42:04 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[09:42:05 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[09:42:06 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[09:42:06 ERROR papyon.service.content_roaming] Content Roaming service got error: HTTP Error (404): Not Found

**Comment by c10ud** [comment]
this error is completely unrelated to this issue. anyway, you can fix it by following the instructions in Preferences-Live Messenger. remember to close emesene while doing it

**Comment by c10ud** [comment]
ok, 2.11.5 coming out soon, and the trayicon issue is fixed (you can choose a tray icon from the extension tab in preferences) check out the blog for further updates

**Comment by Sbte** [comment]
I don't think I have fixed this, but let's hope I did...

**Comment by detlilleegernsven** [comment]
nice (you can choose a tray icon from the extension tab in preferences)

**Comment by andresql** [comment]
hi detlilleegernsven, im using mint 10 32 bit, tomorrow or when I can get a blanck dvd will be updating to mint 11

**Comment by detlilleegernsven** [comment]
andresql 

No problem hwit the old 1.6.4 on my wifes laptop with mint 10 64 bit, mabye it's a mint problem ???

(by the way detlilleegernsven means the little squirrel's freind)

**Comment by andresql** [comment]
now is working fine with a fresh install of mint 11! thanks for the help

**Comment by detlilleegernsven** [comment]
Still not working for mee with mint 11 64 but i am also terrible at installing tar gz files so i am only using emesene 2.11.4

**Comment by c10ud** [comment]
Preferences, Extensions, Tray Icon and choose "tray icon"

2011/6/1 detlilleegernsven
reply@reply.github.com:

**Comment by c10ud** [comment]
in emesene 2.11.5 of course -- you can install emesene from our ppa,
or extract the tgz and run the emesene script, no need to install
anything

2011/6/1 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by detlilleegernsven** [comment]
in emesene 2.11.5 of course -- you can install emesene from our ppa, or extract the tgz and run the emesene script, no need to install anything  lost not good at using tar gz and the ppa is ?

**Comment by Sbte** [comment]
https://launchpad.net/~emesene-team/+archive/emesene-stable

And if you want to use the tgz, you just have to extract it, go to the emesene directory and run ./emesene

**Comment by detlilleegernsven** [comment]
adding ppa:emesene-team/emesene-stable (2.11.5) to my software source dosn't give me emesene 2.11.5

**Comment by detlilleegernsven** [comment]
Now i am using mint 11 64 bit and emesene 2.11.5 still no icon, with mint 10  and mint debian 64 bit i had an icon in my right lower corner (taskbar) mint debian a green circle /dot and mint 11 a blue icon that looks like a person. have to reboot but currently transfering som files so i don't no if a reboote would help.

**Comment by detlilleegernsven** [comment]
Problem solved works now
