### ISSUE TITLE
Qt4 GUI: Character coding issues

### ISSUE THREAD

**Issue by ricsipontaz** [emesene/emesene#586]
There is a problem with the character coding with Qt4 interface:

Screenshot:
http://noob.hu/2011/05/25/emesene2-qt4.png

**Comment by GVisconti84** [comment]
Does it happen with contacts' names too?
What happens if you try to set a word with non-ascii characters as your nick?

**Comment by ricsipontaz** [comment]
No it is works well with contact names and I can use it in my display name too…

**Comment by GVisconti84** [comment]
Ok, as I expected! I'll fix it this evening.

**Comment by GVisconti84** [comment]
Could you pull last commits and try now? It should be fixed! Thanks ;)

**Comment by ricsipontaz** [comment]
I tried it, the group names are now okay, but in the status changer and in the preferences there are still problem.

Screenshot:
http://noob.hu/2011/05/26/emesene2_qt4.png

**Comment by GVisconti84** [comment]
Ouch! :) Which locale are you using? I want to run emesene with that locale, to have a reference :)

**Comment by ricsipontaz** [comment]
Hungarian

**Comment by GVisconti84** [comment]
Ok, could you try again now?

**Comment by ricsipontaz** [comment]
Thanks, now it's okay. ;)

**Comment by GVisconti84** [comment]
Good! Thank you!
