### ISSUE TITLE
Feature: Link not ckickable in contact information and PM

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#588]
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://img822.imageshack.us/i/capturaecra9.png/'><img src='http://img822.imageshack.us/img822/5152/capturaecra9.png' border='0'/></a>

**Comment by Sbte** [comment]
The was done on purpose in the contact list. Contact information could probably be done.

**Comment by c10ud** [comment]
workaround: 
- open conversation
- left click on personal message
- copy personal message

patches for clickable links in view informations and conversation headers welcome (i personally don't like them, but i'll accept them)

**Comment by c10ud** [comment]
```
        from gui.base import MarkupParser
        parsed_list = [ MarkupParser.urlify(part) if type(part) == unicode \
                        else part for part in message_list ]
```

unfortunately SmileyLabel does NOT support hyperlinks (uses pango markup), this means that if we have smilies we can't have hyperlinks...

**Comment by c10ud** [comment]
issue becomes "add support for hyperlinks to SmileyLabel" but i don't think it's easy (or even doable...?)

sorry but WONTFIX

**Comment by marianoguerra** [comment]
maybe the good old link submenu when right click on a contact in the contact list?
