### ISSUE TITLE
gtk/gobject import on emesene.py

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#59]
emesene.py uses gobject to add timeout but I shouldn't, since gobject is part of gtk, we should use python threading.Timer for that

emesene.py also NEEDS the gtk import and the gtkui import or it won't work, any idea?

maybe we need to fix this things before it's too late, or nobody will want to make another gui :P

**Comment by c10ud** [comment]
the gtk import can be made optional, as for gobject i think now gobject is part of glib and it's not gtk-only anymore (i think) in fact we could replace all those gobject calls with glib (if i'm not wrong)

**Comment by arielj** [comment]
I changed the gobject imports with glib imports on classes outside gtkui (some gtkui classes uses gobjects constants, we can change the gobjects.timout_add only)

The gtk import can be removed removing two lines on close_session, but I'm not sure what it does. Maybe mariano knows what to do.

**Comment by c10ud** [comment]
ping wariano

**Comment by c10ud** [comment]
fixd
