### ISSUE TITLE
DebugWindow

### ISSUE THREAD

**Issue by GVisconti84** [emesene/emesene#591]
how to reproduce:
1. start emesene with the gtk gui
2. connect
3. open a debug window
4. disconnect
5. reconnect
6. push close button in debug window

Debug window doesn't close, and this exception is raised:

```
Traceback (most recent call last):
    File "/home/fastfading/src/emesene/emesene/gui/gtkui/DebugWindow.py", line 102, in on_close
        self.safely_close()
    File "/home/fastfading/src/emesene/emesene/gui/gtkui/DebugWindow.py", line 93, in safely_close
        self.window.hide()
AttributeError: 'DebugWindow' object has no attribute 'window'
```

**Comment by c10ud** [comment]
seems like the safely_close is not so safe after all

**Comment by GVisconti84** [comment]
Kinda weird, since `DebugWindow` _has_ a `window` attribute... insn't it?
What could be happening? If somehow the `DebugWindow.window` object gets garbage-collected by the Python runtime it should say something like: `The underlying C/C++ object has been deleted`, right? Am I missing some PyGtk specific mechanism?

**Comment by c10ud** [comment]
gtk usually doesn't say anything, unfortunately.. now debugwindow is really a gtk.window, this little hack seem to work
