### ISSUE TITLE
Qt4 GUI: Empty conversation window

### ISSUE THREAD

**Issue by ricsipontaz** [emesene/emesene#592]
If I want to start a conversation with my contacts, only an empty window opened:

(the same story if somebody wants start with me, I only see an empty window)

screenshot:

http://noob.hu/2011/05/26/emeseneemptywindow.png

**Comment by GVisconti84** [comment]
There's a commit pushed today which changes the way emote themes are managed :P This breaks qt4 gui :P
It will be fixed soon :P

**Comment by c10ud** [comment]
sorry for that, but it fixes some long-standing (hidden) issue with themes, hope it doesn't cause too much trouble

**Comment by ricsipontaz** [comment]
Okay, thanks.

**Comment by c10ud** [comment]
also, seems like pepeleproso fixed the issue, i tried to test but i have some other issue with contactlist so.. 

Traceback (most recent call last):
  File emesene/gui/qt4ui/widgets/ContactListDelegate.py", line 100, in paint
    option, painter, option.widget)
AttributeError: 'QStyleOptionViewItem' object has no attribute 'widget'

**Comment by c10ud** [comment]
https://github.com/pepeleproso/emesene/commit/c23ec47f27834289cb3436f7bac88f5d9304ee8d

https://github.com/pepeleproso/emesene/commit/f4167697417ffcdf5a0f2c3cdc90da0ab876e6c3

**Comment by GVisconti84** [comment]
Mmmmh, tried Pepeleproso's code, and it works fine for me :/

**Comment by ricsipontaz** [comment]
I tried it, but it still not works for me (with Pepeleporoso's code too).

**Comment by GVisconti84** [comment]
Ric, do you get the same message as c10ud?

**Comment by ricsipontaz** [comment]
Here is my error:
http://pastebin.ubuntu.com/613396/

**Comment by GVisconti84** [comment]
EDIT: didn't see your asnwer :) there's a fix ready for that ;)

Oh, are you by chance getting an exception complaining about a float value used instead of an integer value?
That's a known problem related to python version 2.7 (my fault: I ignored the deprecation warnings python 2.6 gave me) and I have a fix ready

**Comment by c10ud** [comment]
ok then, pushed pepe's changes in emesene/master, from now on he has
commit access too :)

2011/5/26 Whisky84
reply@reply.github.com:

**Comment by GVisconti84** [comment]
Great :)
Ric, c10ud, could you guys try again now?

**Comment by c10ud** [comment]
with latest git master i still get 

Traceback (most recent call last):
  File emesene/gui/qt4ui/widgets/ContactListDelegate.py", line 100, in paint
    option, painter, option.widget)
AttributeError: 'QStyleOptionViewItem' object has no attribute 'widget'
QPainter::end: Painter ended with 19 saved states

**Comment by GVisconti84** [comment]
did it work previously? What version of Qt/PyQt are you using? :/

**Comment by c10ud** [comment]
mm nope, but i have stock ubuntu lucid versions

$ apt-cache show python-qt4
Package: python-qt4
Priority: optional
Section: python
Installed-Size: 11620
Maintainer: Kubuntu Developers kubuntu-devel@lists.ubuntu.com
Original-Maintainer: Debian Python Modules Team python-modules-team@lists.alioth.debian.org
Architecture: amd64
Version: 4.7.2-0ubuntu1
Replaces: python-qt4-common, python-qt4-dev (<< 4.4.4-3~)
Provides: python2.6-qt4

**Comment by c10ud** [comment]
BTW my issue is that i don't see the contact list

**Comment by GVisconti84** [comment]
What does it say if you put `print option` just before line 100?
It seems like `option` is an instance of `QStyleOptionViewItem` class, while it should be an instance of `QStyleOptionViewItemV4` :/

**Comment by c10ud** [comment]
ehm, i did nothing and now it works...:WTF

**Comment by c10ud** [comment]
joking

**Comment by c10ud** [comment]
<PyQt4.QtGui.QStyleOptionViewItem object at 0x2ff31f0>

PyQt4.QtGui.QStyleOptionViewItem object at 0x2ff31f0

**Comment by GVisconti84** [comment]
Ok, found a simple workaround to make it work even if that parameter is mysteriously an instance of `QStyleOptionViewItem` :)

@c10ud, @ricsipontaz, let me know if everything works now

**Comment by c10ud** [comment]
ok, works good now...great!

**Comment by c10ud** [comment]
whoops, i closed this issue but the problem was another, well, if original issue persists ricsipontiaz please reopen it

**Comment by ricsipontaz** [comment]
No problem, it is works well too. ;) Thanks.

**Comment by GVisconti84** [comment]
Good :)
