### ISSUE TITLE
Another File Mirros for Windows build

### ISSUE THREAD

**Issue by km307** [emesene/emesene#594]
This is actually not an issue about emesene itself but an issue about the file mirror server (http://www.fileserve.com/list/3sn6UZV).
fileserve.com has block the IP from my region and so we cannot download the experimental Windows build for testing.

So, if possible, please kindly use another file mirror so we can download and test the package. By the way, Megaupload has also block the IP form our region,so, please don't use it to host the package.

Thanks for all your hard work!

**Comment by arielj** [comment]
Does mediafire works?

maybe we should use some github, google or sourceforge link?

**Comment by ghost** [comment]
I can try mediafire. but I was having problems with sharing folders in the past.
Update: I have started uploading to http://www.mediafire.com/emesene

@marianoguerra @c10ud Can you add this as a mirror or just replace it?

**Comment by c10ud** [comment]
the good ol' sf.net should do the trick, for the next version we'll upload to that so we'll have free bandwidth and no hassles like ads or something

**Comment by km307** [comment]
mediafire works, I can download the test build form http://www.mediafire.com/emesene.
Thank you!

**Comment by ghost** [comment]
A new official windows link is on http://blog.emesene.org/p/downloads.html. It should be more friendly then fileserve.

http://www.mediafire.com/emesene is just my personal mirror with my own test builds, but if works for you then ok.

**Comment by c10ud** [comment]
syst3mfailur3 is right, closing the issue :)
