### ISSUE TITLE
appear not to install the plugin

### ISSUE THREAD

**Issue by GabrielEP** [emesene/emesene#595]
I updated ubuntu 11.4. and the preferences plugins tab is empty
I can not from synaptic

**Comment by Sbte** [comment]
There are only two plugins at the moment, and they will most likely be included in the next release. The release will happen this weekend if everything goes right.

Plugins can also be found here:

https://github.com/emesene/emesene-supported-plugins
https://github.com/emesene/emesene-community-plugins

**Comment by GabrielEP** [comment]
ok. pero tampoco veo esos dos.
but if you say that I updated the weekend I'll wait
I have also problems with the theme that I open the window if someone talks to me. is another matter, but not how search

**Comment by Sbte** [comment]
What problem is that?
