### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by hwoarang** [emesene/emesene#597]
Hi

I am packaging emesene-2 for Gentoo linux. Currently is in my personal overlay[1] but I plan to move it to main tree soon. You may want to update your website to list Gentoo on supported distributions

Thanks for all your work.

[1] http://git.overlays.gentoo.org/gitweb/?p=dev/hwoarang.git;a=tree;f=net-im/emesene;h=20dfa13331cf6938af22e57d784ec5f3cd88bec6;hb=bea7f83f41c2229178392082a66e885d0d60ce5c

**Comment by c10ud** [comment]
thank you, will do it asap (we'll release 2.11.5 soon)

**Comment by hwoarang** [comment]
This is now on Gentoo official tree

http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-im/emesene/

**Comment by c10ud** [comment]
added to download page, thanks

**Comment by c10ud** [comment]
http://blog.emesene.org/p/downloads.html
