### ISSUE TITLE
Invisible status and offline messages

### ISSUE THREAD

**Issue by Lagg3r** [emesene/emesene#598]
If I start a conversation with a contact being invisible, when I login next time, Emesene shows me a conversation window with the same messages that I received before, while I chatting as invisible. It's like if Emesene try to notify about messages received while offline, but don't differenciate between "offline" and "invisible" status.

Español:
Si hablo con un contacto mientras estoy como invisible, cuando vuelvo a iniciar sesión, Emesene me abre una ventana de conversación con todos los mensajes que recibí mientras estaba hablando como invisible. Es como si quisiera notificarme de mensajes que recibí mientras estaba desconectado.

Emesene version: Latest git
Protocol: MSN
OS: Ubuntu 11.04

**Comment by ammarabdulsalam** [comment]
I have reported this issue before, and it was papyon bug.
I'm still waiting to fix it.

**Comment by Lagg3r** [comment]
Thanks, I didn't know. Closed.
