### ISSUE TITLE
[papylib] file transfer doesn't work

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#60]
i cant receive a file from a user at all, im not sure if it implemented or not yet but nothing happens when they send me something, not even anything asking me to accept.

**Comment by c10ud** [comment]
filetransfers requires papyon >= 0.4.8 installed either system-wide or in emesene/e3/papylib/papyon

**Comment by SWOriginal** [comment]
i have it papyon installed, im running emesene from source so perhaps that the problem? the papyon folder in the source is empty should it be?

**Comment by c10ud** [comment]
it's ok, but the papyon version must support file transfers and you must chose the correct backend in emesene

**Comment by SWOriginal** [comment]
So i still cant manage to get this to work, ive updated the source re-installed papyon 0.4.8 n still its a no go

the person trying to send me something is on wlm on windows7 if that anything to do with it

**Comment by c10ud** [comment]
just tried emesene1-to-emesene2 and it worked, it just needs a conversation window opened (i guess we must fix this)

**Comment by SWOriginal** [comment]
considering most users use wlm on windows id say this is a big issue that needs to be fixed, im ok with telling people to not send me things as its not implemented yet but this should be fixed by the first few betas so we can test if theres any issues with it

**Comment by c10ud** [comment]
@ariel did you try this out in windoze?

**Comment by SWOriginal** [comment]
i tried this out in ubuntu but the user who sends me things is using windows, i'll try again with the latest source in a sec :)

**Comment by arielj** [comment]
Receiving:
when the transfer is finished I get this message on the terminal:
argument 1 must be string or buffer, not cStringIO.StringO

with no traceback or anythin....

the "papy_ft_completed" method is never called and the temp file is created but it's empty.

Sending:
The transfer starts and it advances faster on the receiver client and it gets stuck around 10% without messages on the terminal.

I algo get a GtkWarning on FileTransferWidget.py, line 65 on both cases:
GtkWarning: gtk_box_pack: assertion "child -> parent == NULL" failed
self.pack_start(self.menu)

**Comment by c10ud** [comment]
ok, i edited the title, i'll take a look at this

**Comment by SWOriginal** [comment]
@c10ud has there been any progress on this issue?

**Comment by c10ud** [comment]
Traceback (most recent call last):
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 364, in _sb_message_received
    handler._on_message_received(message)
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/switchboard.py", line 74, in _on_message_received
    self._on_chunk_received(chunk)
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 103, in _on_chunk_received
    self._send_ack(chunk)
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 159, in _send_ack
    self.send(ack_blob)
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 73, in send
    self._process_send_queues()
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 144, in _process_send_queues
    self._send_chunk(chunk)
  File "/home/riky/msn/emesene2/emesene/e3/papylib/papyon/papyon/msnp2p/transport/switchboard.py", line 65, in _send_chunk
    headers = {'P2P-Dest': self.peer.account}
AttributeError: 'NoneType' object has no attribute 'account'

**Comment by c10ud** [comment]
(papyon 0.5, needs work upstream)

**Comment by c10ud** [comment]
in 0.5.1 should work mostly, i'll close this bug
