### ISSUE TITLE
Animated emoticons issue

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#601]
I'm having troubles with animated emotions. When i send it, i see the image blinking or still; when someone sends me an animated emoticon i only see a kind of placeholder (like a papersheet or something).

in console i get this errors when someone sends me an animated emo:
[16:18:47 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[16:18:47 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[16:18:48 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[16:18:48 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

I'm using git emesene2 version pulled today.
python-2.6.6
gtk+-2.24.3
pygtk-2.24.0
papyon-0.5.5
webkit-gtk-1.2.7
pywebkitgtk-1.1.8

note: custom emoticons without movement (i.e. still images) works fine :)

**Comment by Sbte** [comment]
If you click on the emoticon twice, does it work then?

**Comment by ivanalejandro0** [comment]
i didn't realized of that behavior... i like it :)
with one click switches between the 'placeholder' and text, one more click and i see the emoticon.

Now only remains the blinking problem, the image doesn't "move", only blinks.

**Comment by Lagg3r** [comment]
I tried to install a custom Adium icon set and it worked fine, except for the animated icons (gif). When I send or receive one, Emesene only shows a shorcut instead of image.

**Comment by c10ud** [comment]
example? (i.e. screenshot?)

**Comment by Sbte** [comment]
Also, putting the emoticon here would help too.

**Comment by ivanalejandro0** [comment]
I uploaded a small video with the problem and the 2 emoticons i show in video.
http://www.mediafire.com/file/6ixs9cnfed2nhw6/emesene2_emo_blink.7z
(~45kib)

**Comment by c10ud** [comment]
looks like a webkit bug. which os are you using?

also, doublecheck the images for validity

2011/5/30 ivanalejandro0
reply@reply.github.com:

**Comment by ivanalejandro0** [comment]
i have Gentoo.
I used the same images long time ago (in aMSN, emesene 1.x, emesene 2)

i tested webkit-gtk and qt-webkit (4.7.3) with this examples:
http://marianoguerra.blogspot.com/2009/11/browser-en-pygtk-con-webkit-en-unas.html (i removed the adding of 'http://' from code)
http://lateral.netmanagers.com.ar/weblog/posts/BB948.html

The problem only appears in webkit-gtk based browser.

**Comment by c10ud** [comment]
ok, i suspected it, the issue is then within webkit -- you might want to report that upstream, i bet the gif decoder is broken or something like that..

**Comment by c10ud** [comment]
i mean, webkit-gtk

**Comment by ivanalejandro0** [comment]
thanks for help, i've made a report to upstream.

**Comment by ivanalejandro0** [comment]
it's solved now in gentoo :)
