### ISSUE TITLE
Can't see aMSN user's avatar

### ISSUE THREAD

**Issue by the98** [emesene/emesene#602]
Emesene version: 2.11.4
OS: Debian Sid
Emesene installed from Debian Sid's repository (so version actually is 2.11.4+dfsg-1)

What happens is that when chatting to a contact that's using aMSN (Windows version) I can't see his/her avatar. It never loads. This does not happen on emesene 1.6.3 - "Uberlândia" on a Debian Squeeze installation. In that case, avatar loads normally.
# 

Emesene instalado en un Debian Sid a través del repositorio de Debian Sid.

Ocurre que al chatear con un contacto que usa la versión de Windows de aMSN, su avatar nunca carga. Esto no pasa en emsene 1.6.3 - "Uberlândia", donde la imagen se visualiza con normalidad en una instalación de Debian Squeeze.

**Comment by ghost** [comment]
If your coming from 1.6.3, try going to PREFERENCES -> LIVE MESSENGER and following the instructions there. Make sure to restart emesene2 after doing that.

**Comment by the98** [comment]
Hi. I'm not coming from 1.6.3. It's installed on another machine and I haven't imported config files or anything.

**Comment by ghost** [comment]
Are you using the same account as you used with 1.6.3? If you are then your profile (on the msn server) is broken.
The instructions in PREFERENCES -> LIVE MESSENGER will fix your profile if it is broken, which might solve your problem.

**Comment by the98** [comment]
I use the same account. So every time I use emesene 1.6.3 and then use emesene 2 I have to "fix" my broken profile?

How do I know if my profile is actually broken?

And last but not least, why does this happen with contacts using aMSN?

Thanks!

**Comment by ghost** [comment]
Unfortunately yes, emesene 1.6.3 breaks your profiles every time you login using it. A broken profile will cause problems with your avatar, display name, and personal message. This may not be a broken profile issue, but a lot of the issues reported are so its always best to check. 

You know you have a broken profile when you get 404 errors in the debug window or while running the terminal.
They will look something like this: http://pastebin.com/t3M5YhWB

Not sure. Could be a bug, it could be a broken profile, it could be aMSN. Developer will have to answer that.

**Comment by the98** [comment]
Ok, so I've fixed my profile (I was getting 404 errors in my Terminal). I restarted emesene. I was using an account with aMSN in my desktop computer and a different msn account with Emesene 2 on my laptop. I wasn't able to see the avatar of the account using aMSN.

I also noticed that whenever you fix your profile, all your config goes back to default and you have to configure Emesene 2 again :-S

I don't think it's aMSN issue. But I'm not a coder so I would know for sure!

**Comment by c10ud** [comment]
make sure you have python-papyon=>0.5.5

**Comment by the98** [comment]
Hi, I think that's not the problem. Sid's package python-papyon version is 0.5.5.

Maybe you should try the bug for yourselves using 2 different accounts. I think it's a minor bug which does not make the software unusable, and it might be aMSN's fault.

Kind regards.

**Comment by the98** [comment]
I've just notice that this also happens with user's using MSN (WLM or whatever it's called now).

This is the output I get when I clic on debug, maybe it helps figuring out the problem:

(23:24:38) papyon.transport:<<< JOI Contact'sMail@hotmail.com Agustin 2788999468:2550273072
(23:24:38) papylib.Events:Contact's client capabilities changed: <papyon.Contact id='8c86ca1f-16b4-4017-8b5e-3165dea39ce6' network='1' account='Contact'sMail@hotmail.com' memberships='FORWARD | ALLOW | REVERSE'>
(23:24:38) papyon.transport:>>> MSG 3 D 252

```
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
P2P-Src: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
P2P-Dest: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
[P2P message (942 bytes)]
```

(23:24:38) papyon.transport:<<< ACK 3
(23:24:39) papyon.transport:<<< MSG Contact'sMail@hotmail.com Agustin 251

```
P2P-Src: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
P2P-Dest: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (28 bytes)]
```

(23:24:39) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfccd4d61: blob 0, ACK 0x1b615f9a, RAK, SYN,
(23:24:39) papyon.msnp2p.transport.switchboard:>>> TLPv2 chunk 0x1b615f9a: blob 0, ACK 0xfccd4d61,
(23:24:39) papyon.transport:>>> MSG 4 D 251

```
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
P2P-Src: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
P2P-Dest: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
[P2P message (16 bytes)]
```

(23:24:39) papyon.transport:<<< MSG Contact'sMail@hotmail.com Agustin 252

```
P2P-Src: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
P2P-Dest: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (432 bytes)]
```

(23:24:39) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfccd4d61: blob 0, SLP Message
    MSNSLP/1.0 200 OK\r\n
    To: msnmsgr:MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}\r\n
    From: <msnmsgr:Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}>\r\n
    Via: MSNSLP/1.0/TLP ;branch={dea2c87a-ed57-41fa-a685-b060f036cf75}\r\n
    CSeq: 1 \r\n
    Call-ID: {eb536745-eece-4dca-8da6-0462f72c666c}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 25\r\n
    \r\n
    SessionID: 868144819\r\n
    \r\n
    \x00
(23:24:39) papyon.p2p:Keeping only session 868144819 in meta session
(23:24:39) papyon.transport:<<< MSG Contact'sMail@hotmail.com Agustin 251

```
P2P-Src: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
P2P-Dest: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (20 bytes)]
```

(23:24:39) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfccd4f09: blob 0, session 868144819, data [4 bytes](23:24:39) papyon.transport:<<< MSG Contact'sMail@hotmail.com Agustin 252

```
P2P-Src: 'Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}'\r\n
P2P-Dest: 'MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (500 bytes)]
```

(23:24:39) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfccd4f15: blob 1, SLP Message
    BYE MSNMSGR:MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207} MSNSLP/1.0\r\n
    To: msnmsgr:MyMail@hotmail.com;{d36fcbbe-d101-4618-aeee-654f8201d207}\r\n
    From: <msnmsgr:Contact'sMail@hotmail.com;{ce880c6b-3040-4279-9222-b4d4e97ee578}>\r\n
    Via: MSNSLP/1.0/TLP ;branch={60A38374-9901-4B74-BDFF-CEB878CB27C7}\r\n
    CSeq: 0 \r\n
    Call-ID: {EB536745-EECE-4DCA-8DA6-0462F72C666C}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionclosebody\r\n
    Content-Length: 25\r\n
    \r\n
    SessionID: 868144819\r\n
    \r\n
    \x00

**Comment by c10ud** [comment]
need more feedback on this from others, i don't have access to a wlm2011, as for amsn it works here, maybe it's some old version?

the trace looks good though.. try 2.11.5 and cleaning your config folder (rm -rf ~/.config/emesene2)

**Comment by Sbte** [comment]
Maybe this is the same issue I had when you committed dab73e5a0beb1deaa9ed460579999c1df9e05578, because that still doesn't seem fixed.

**Comment by c10ud** [comment]
nope, now it checks for a new avatar everytime it adds a contact to the contact list, which means every login the whole contact list's avatars are rechecked

**Comment by the98** [comment]
I've updated to 2.11.5. Removed my config dir, but this has made the problem worse because now I can see even less avatars than before.

This is an example of the debug output I get:

(13:08:21) papyon.msnp2p.transport:Registering transport <SwitchboardP2PTransport peer="FriendsEMail@hotmail.com" guid="d5831a3d-aeaf-48ac-a8a0-26d3e23abb15">
(13:08:21) papyon.msnp2p.transport.switchboard:>>> TLPv1 chunk 0x6666f896: blob 2058957350, SLP Message
    INVITE MSNMSGR:FriendsEMail@hotmail.com MSNSLP/1.0\r\n
    To: msnmsgr:FriendsEMail@hotmail.com\r\n
    From: msnmsgr:MyEMail@hotmail.com\r\n
    Via: MSNSLP/1.0/TLP ;branch={a4238c1d-4801-4202-b3cd-15bf1aceb282}\r\n
    CSeq: 0\r\n
    Call-ID: {72ce4ba3-148d-4138-8543-4f465581e1cd}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 454\r\n
    \r\n
    SessionID: 202051966\r\n
    SChannelState: 0\r\n
    Capabilities-Flags: 1\r\n
    EUF-GUID: {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}\r\n
    AppID: 12\r\n
    Context: PG1zbm9iaiBDcmVhdG9yPSJyb2RyaWdvY2hfNUBob3RtYWlsLmNvbSIgU2l6ZT0iMjg3MCIgVHlwZT0iMyIgU0hBMUQ9InJxMVBoc2MrK05zd2QyTzFHMGVmZERtSEdhWT0iIFVybD0iIiBVcmwxPSJodHRwOi8vYmx1ZmlsZXMuc3RvcmFnZS5tc24uY29tL3kxbVNEZzh5aEJPU1dyNmJHaVBRVFBZSlZxeFZfRWpoOFl5bzduMm5abXFDUXk2akFjYTJGQ1BUc0ViRDlabnpwNlhhR3duR0tIOWhhZy1EYnpnWm1SdU9nIi8+\r\n
    \r\n
    \x00
(13:08:21) papyon.protocol.switchboard_manager:Requesting switchboard for participant(s) FriendsEMail@hotmail.com
(13:08:21) papyon.protocol.switchboard_manager:Requesting new switchboard

By the way, according to aMSN, the contact I've previously reported is running WLM 2009.

Regarding to aMSN, I can't see the avatar of that contact, even under ver 2.11.5. And another thing I've noticed is that the contact running aMSN I can't see my avatar either (running emesene 2). This doesn't happen when running emesene 1 with the other account and running emesene 2 with my account (they can both see each other avatars), so maybe it's an aMSN issue.

Hope this helps.

**Comment by Sbte** [comment]
@the98 That last problem with other users not seeing your avatar indicates a broken profile. Follow the instructions under Preferences->Live messenger and don't use emesene 1 ever again ;)

**Comment by the98** [comment]
Done that a long time ago. No improvement...

**Comment by Sbte** [comment]
If you logged in with emesene 1 in between it broke again. So, yeah... Just sayin'

**Comment by the98** [comment]
Yes... I "fix"my profile every time I log in to emesene 2. You can tell it's broken because you can't see your PM and when chatting to a contact you see your e-mail adress instead of your nick name. So yeah, I fix every time (which I think it's something that could be done every time you log into emesene 2 automatically, just saying).

**Comment by c10ud** [comment]
it can't be done automagically, and if you really fix it, it's a one-timer

**Comment by the98** [comment]
Well, the thing is I usually switch between a Debian Squeeze PC and a Debian Sid PC. The first one has emesene 1.6, while the second emesene 2. So my profile gets broken every time I log in with emesene 1.6.

Are you sure there is no way to check if you have an avatar on your profile and then remove it? How did emesene 1.6 used to change the avatar in the profile before? If I can change it, I'm guessing it can also be removed... But then again, I'm just guessing.

**Comment by Sbte** [comment]
Even if that fixed the problem, having no avatar or setting no avatar is currently not supported in papyon. Feel free to post a bug here:

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by c10ud** [comment]
with current papyon there's no way to fix profiles, and i doubt noone
ever will add this feature since most of profiles are already fixed
and to fix them is a one-timer

2011/7/3 Sbte reply@reply.github.com:

**Comment by Mystro256** [comment]
@the98

Why can't you install emesene 2 in your Squeeze computer? Sure it's not in the official debian repo but that doesn't mean it won't work in squeeze.

**Comment by the98** [comment]
That won't solve the bug posted here.

Besides, upgrading means that I have to upgrade a few libraries and packages. I don't feel like doing that just for Emesene. And for the record, I like emesene 1.6 better.

**Comment by bardok** [comment]
Hello,

i've got the same bug with some contacts. One of them is under emesene 2.11.4, the other one is under wlm2011.

My profile is not broken, i don't have any message

I use emesene 2.11.5 under Ubuntu Natty with ppa repositery.

I noticed that if my contact change is avatar, emesene see it and display it. With no change i don't have the avatar.

How i can help to solve this bug ?

Bardok.

**Comment by Sbte** [comment]
@c10ud, should we really add a glib timeout so the msnobj are actually there when we ask for them? I'll leave this for you to fix, say... tomorrow? :P

**Comment by bardok** [comment]
I still have the bug. I run emesene 2.11.6 devel downloaded today.

**Comment by Sbte** [comment]
Report it here:

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

There's nothing we can do now.
