### ISSUE TITLE
Adium textbox doesn't get destroyed properly

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#604]
When I close a conversation window, the adium textbox keeps existing. Way to test:

Send nudge
Receiver sees 
*\* Message: console message: undefined @0: TypeError: 'null' is not an object
once.
Receiver closes conversation
Send nudge
Receiver sees the error twice
Receiver closes conversation
Send nudge
Receiver sees the error trice

and so on....

**Comment by arielj** [comment]
Are we discconnecting the signals? we almost never remove the objects (we are too lazy, since the garbage collector does that), we should at least remember to disconnect the signals :P

I know I've disconnected some signals and timeouts, check the conversation class, we should call a output.destroy or something like that on that same method and add that destroy/delete/disconnect method on the adium class

**Comment by arielj** [comment]
I don't know if it's a bug on emesene or papyon, but _on_message method is being called multiple times. Just put a "print cid, account, message" at the begining of _on_message (line 65 on base/ConversationManager.py) and you'll see that, it's not only with nudges and adium, all messages are arriving more times than expected.

I didn't test with gtalk yet.

**Comment by arielj** [comment]
There's something wrong with session signals, it's not unsubscribing functions, session.conv_message.unsubscribe is called and the callback shouldn't be called after that, but it's still on signal._subscribers hash.

**Comment by Sbte** [comment]
Apparently, the callback is formatted in such a way, that the callback is never found in self._subscribers when you want to remove it. So it never gets inside the if statement.

**Comment by Sbte** [comment]
Removing WeakMethod() fixes the problem. What does it even do? @marianoguerra

**Comment by Sbte** [comment]
How about his:

https://github.com/Sbte/emesene/commit/02274c9de595b97348ca2c698e3200602695b1ce

**Comment by marianoguerra** [comment]
On Thu, Jun 2, 2011 at 1:35 PM, Sbte
reply@reply.github.com
wrote:

> How about his:
> 
> https://github.com/Sbte/emesene/commit/02274c9de595b97348ca2c698e3200602695b1ce

makes sense, did you checked if the equality works?

like printing something when unsubscribing to know that it's actually
unsubscribing.

**Comment by Sbte** [comment]
Yes, before this change nothing was unsubscribed, now everything is as far as I could tell.

**Comment by marianoguerra** [comment]
On Thu, Jun 2, 2011 at 2:20 PM, Sbte
reply@reply.github.com
wrote:

> Yes, before this change nothing was unsubscribed, now everything is as far as I could tell.

great, nice catch!

**Comment by Sbte** [comment]
Thanks arielj for all the research ;)
