### ISSUE TITLE
v2.11.5 and current git code does not build

### ISSUE THREAD

**Issue by hwoarang** [emesene/emesene#605]
Hi

I get the following error when installing emesen

running install_data
creating /var/tmp/portage/net-im/emesene-2.11.5/temp/images/2.7/usr/share
creating /var/tmp/portage/net-im/emesene-2.11.5/temp/images/2.7/usr/share/icons
creating /var/tmp/portage/net-im/emesene-2.11.5/temp/images/2.7/usr/share/icons/scalable
creating /var/tmp/portage/net-im/emesene-2.11.5/temp/images/2.7/usr/share/icons/scalable/apps
error: can't copy 'emesene/data/icons/scalable/apps/emesene.svg': doesn't exist or not a regular file

Indeed, there is not such file, seems like it was moved to /icons/hicolor/scalable/apps/

**Comment by hwoarang** [comment]
This is the fixed I will apply for Gentoo linux

# Index: emesene-emesene-5cf77b3/setup.py

--- emesene-emesene-5cf77b3.orig/setup.py
+++ emesene-emesene-5cf77b3/setup.py
@@ -105,7 +105,7 @@ if os.name == "nt":
 else:
     # Data files to be installed to the system
     _data_files = [
-        ("share/icons/scalable/apps", ["emesene/data/icons/scalable/apps/emesene.svg"]),
-        ("share/icons/hicolor/scalable/apps", ["emesene/data/icons/hicolor/scalable/apps/emesene.svg"]),
       ("share/icons/hicolor/16x16/apps", ["emesene/data/icons/hicolor/16x16/apps/emesene.png"]),
       ("share/icons/hicolor/22x22/apps", ["emesene/data/icons/hicolor/22x22/apps/emesene.png"]),
       ("share/icons/hicolor/24x24/apps", ["emesene/data/icons/hicolor/24x24/apps/emesene.png"]),

**Comment by c10ud** [comment]
sorry, updated the tarball now, try again!

2011/5/30 hwoarang
reply@reply.github.com:

**Comment by c10ud** [comment]
i rewrote history (bad thing to do, i know), now v2.11.5 is ok! :)

**Comment by c10ud** [comment]
thanks again for reporting so fast

**Comment by hwoarang** [comment]
Looks good. Thanks for being so fast :)
