### ISSUE TITLE
2.11.5 will not run properly on OS X

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#606]
emesene will launch, but the contact list will not display

> [19:45:58 WARNING emesene.e3.common.DBus] Failed some import on dbus: No module named dbus
> [19:45:58 WARNING emesene] Errors occurred while importing jabber backend: No module named xmpp
> [19:45:58 WARNING emesene] Errors occurred while importing msn backend: No module named papyon.profile
> [19:45:59 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'Session' object has  > no  attribute 'get_profile'
> [19:45:59 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'Session' object has no > attribute 'get_profile'
> Traceback (most recent call last):
>  File "/Users/Josh/Desktop/emesene/e3/common/Signal.py", line 64, in emit
>    if callback(_args, *_kwargs) == False:
>  File "/Users/Josh/Desktop/emesene/e3/common/Signal.py", line 111, in **call**
>   self.f(self.c(), _arg)
>  File "/Users/Josh/Desktop/emesene/emesene.py", line 512, in on_login_succeed
>    self.draw_main_screen()
>  File "/Users/Josh/Desktop/emesene/emesene.py", line 436, in draw_main_screen
>    self.tray_icon.quit_on_close)
>  File "/Users/Josh/Desktop/emesene/gui/gtkui/Window.py", line 101, in go_main
>    on_close, on_disconnect)
>  File "/Users/Josh/Desktop/emesene/gui/gtkui/MainWindow.py", line 43, in **init**
>    self.**hotmail = Hotmail(self.session)
>  File "/Users/Josh/Desktop/emesene/e3/hotmail/Hotmail.py", line 47, in __init**
>   self.profile = self.session.get_profile()
> AttributeError: 'Session' object has no attribute 'get_profile'
> [19:38:47 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType'     > object has no attribute 'contact_list'
> [19:38:47 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType'      > object has no attribute 'contact_list'
> Traceback (most recent call last):
>  File "/Users/Josh/Desktop/emesene/e3/common/Signal.py", line 64, in emit
>    if callback(_args, **kwargs) == False:
>  File "/Users/Josh/Desktop/emesene/e3/common/Signal.py", line 111, in **call**
>    self.f(self.c(), *arg)
>  File "/Users/Josh/Desktop/emesene/emesene.py", line 612, in on_contact_list_ready
>    self.window.content.contact_list.fill()

I gathered emesene could not find Papyon, but Papyon is in e3/papylib/papyon. Has it moved?

**Comment by GVisconti84** [comment]
Did you checkout the tag, or download the tarball?
Here (Snow Leopard, `git checkout v2.11.5`) it's working

**Comment by ghost** [comment]
Yeah git checkout worked. Tarball doesnt

**Comment by GVisconti84** [comment]
that's because in the tarball there isn't papyon, as it is a different project (Infact, here in the repo it is linked as a submodule)

**Comment by ghost** [comment]
I knew that, i copied papyon into the directory but it still didnt work :/

**Comment by c10ud** [comment]
make sure you have 

$ ls emesene/e3/papylib/papyon/papyon/
client.py         event         msnp2p       sip
client.pyc        gnet          p2p.py       switchboard_manager.py
conversation.py   **init**.py   p2p.pyc      switchboard_manager.pyc
conversation.pyc  **init**.pyc  profile.py   transport.py
errors.py         media         profile.pyc  transport.pyc
errors.pyc        msnp          service      util

**Comment by GVisconti84** [comment]
@joshf sorry, my fault: didn't read your stack trace deeply, it says you're connecting, so it says you added papyon :)
However I've tried to copy papyon in the stuff extracted from the tarball and it works

**Comment by ghost** [comment]
Don't worry. Main thing is its working now :)
