### ISSUE TITLE
Settings are lost when closing while conecting

### ISSUE THREAD

**Issue by leandro0012** [emesene/emesene#607]
If you close emesene while is conecting, your settings will be lost. I tested this many times, I had muted emesene and I had disabled notifications. Then I did a clean-close (Emesene>File>Quit). When I started emesene and conected again, all the settings were kept, so I did another clean-close and I started it again. Finally, when it was connecting I closed it and I opened it again. I connect to my MSN account and all the settings were not kept.

I am using emesene 2.1.1.4

I Hope you fix this in your next release.

PS: Sorry for my bad english

**Comment by c10ud** [comment]
can you try with 2.11.5?

2011/5/30 leandro0012
reply@reply.github.com:

**Comment by Sbte** [comment]
Fixed in 2.11.5

**Comment by leandro0012** [comment]
How Can I install emesene 2.1.1.5 in ubuntu?

**Comment by c10ud** [comment]
http://blog.emesene.org/p/downloads.html
