### ISSUE TITLE
Importing from emesene1 + close contact info -> segmentation fault

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#608]
This issue happens to me every time i tried to import my old emesene 1 configuration like this:
When the importing dialog is open if i open the contact information dialog, when i close it emesene breaks with a 'Segmentation fault' message in console.

My solution was not opening the contact information until it finishes to import everything :P
I haven't another acount to test this behavior again.

**Comment by c10ud** [comment]
@4ndreast4gi

anyway, since this should be a one-timer, we should write somewhere not to touch anywhere :D

**Comment by astagi** [comment]
I don't know what happens to throw a segmentation fault, I'll try to do some test... Anyway I could block other windows till the log hasn't finished his work, what about?

**Comment by c10ud** [comment]
maybe making it modal is good, in the end it's a one-timer (hopefully)

2011/6/3 4ndreaSt4gi
reply@reply.github.com:

**Comment by astagi** [comment]
well, nope ^^ to introduce new features I made it callable anytime u want going to Extensions -> synch with emesene1 ..

**Comment by Sbte** [comment]
Probably accessing the database while it's being written. Just an idea.

**Comment by astagi** [comment]
uhm, I access to db through the logger, avoiding to overload it, so it should be safe ^^ I'll have a deep look at this, alternatively I'll use modal windows...
