### ISSUE TITLE
Sometimes when cycling through conversations, text doesn't get focused

### ISSUE THREAD

**Issue by mgonto** [emesene/emesene#611]
I have a set of people I'm talking to.
I have them each in a different tab.

When I'm talking to one of them and I cycle through the windows the text focus works great but when i Focus the Emesene from another process the text doesn't get automatically focused and I need to click it. I try not to use the Mouse whereas I can.
It's kind of annoying.

Thanks!

**Comment by Sbte** [comment]
What operating system do you use and what version of emesene? If you have anything below 2.11.5, please upgrade. 

This has always worked fine for me using Ubuntu btw.

**Comment by mgonto** [comment]
Hey,

I have Ubuntu 11.04 and Just added the PPA for Stable version today because of the new release.

I have the version: emesene 2.11.5.

So I don't have it fixed for some reason :S

Do you want me to run it in debug and copy some stuff here?

**Comment by Sbte** [comment]
An exact way to reproduce it would help.

**Comment by mgonto** [comment]
I changed the Emesene Indicator to the Tray Icon.

For example when the Tray Icon starts blinking when I get a new message and I click it, the conversation window maximzes but the text isn't focused.

**Comment by Sbte** [comment]
Eh, tray icons don't work in Ubuntu 11.04. If you're using the Indicator, it'll show you a menu upon clicking, not a window. I don't really understand what you mean...

**Comment by mgonto** [comment]
You can enable tray icons on ubuntu 11.04. However, this is not the default.

Please run the following command and then put the Tray Icon: gsettings set com.canonical.Unity.Panel systray-whitelist " [ 'all' ] "

Regards

**Comment by mgonto** [comment]
The logout and You'll see the tray icon

**Comment by Sbte** [comment]
Does it happen with lucid too? Because it could just be a bug in unity or so. Any chance you could test that?

**Comment by c10ud** [comment]
i think the focus on the text entry is set only when the window is added/shown, if you manually focus the emesene window, you must take care of choosing the text entry because you can focus other things such as closing and toolbar buttons

**Comment by c10ud** [comment]
just tried with current git and it works (?) invalid issue (or already fixed) i think
