### ISSUE TITLE
2.11.5 - translations

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#612]
In launchpad there are only two 100% translations for emesene 2.11.5. Are you plan to update the source (or packages) a couple of days later when will be more fully translated languages. 

(sorry for bad english)

**Comment by Sbte** [comment]
We could release 2.11.5.1 when more translations are ready, and when arielj can turn his adium crash test fix into a package. @c10ud

**Comment by c10ud** [comment]
i'd go directly for 2.11.6 when it's time, there's no point in releasing like hell with such small changes.. translators had their time, as packagers:)

**Comment by c10ud** [comment]
anyway for this kind of questions please use the mailing list or similar, because they're not really "bugs" and clutter the tracker leading to lazy developers skipping real bugs!

**Comment by Sbte** [comment]
Ah, why did you tell him that? I need more excuses...

**Comment by marianoguerra** [comment]
On Tue, May 31, 2011 at 4:25 PM, rockybalboa
reply@reply.github.com
wrote:

> In launchpad there are only two 100% translations for emesene 2.11.5. Are you plan to update the source (or packages) a couple of days later when will be more fully translated languages.
> 
> (sorry for bad english)

I expect people to update the languages and then make a new release.

I think we should make a call for translators again.

thanks!
