### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#613]
With issue #414 being fixed (lets hope for good) one day after release and a possible re-release for windows coming, I think that it would be a good idea to add a "Check for updates" feature. It doesn't have to be an auto-installing one, but just a simple notification that a newer release is available. I know joshf had something like this in for the mac version, but that actually installed the newer version.

**Comment by c10ud** [comment]
i'd like also to add a system-uuid getter and some page that tracks the number of install/oses so we can have an idea of the number of users and the oses we need to improve support.

anyway, as for the "check for updates" that can be added in mainline code basing on josh's patch with the following modifications:
if linux and windows and others: update is available and link to main website
if mac: update is available and link to website and offer direct upgrade

the "alert" could run everytime emesene logs in unless the user disables the feature from the preferences
the check in "help" can remain in every case

we need to decide where to put this info: probably a simple VERSION file in github can do the trick for now. then we can always change to something else

**Comment by ghost** [comment]
I think this is a great idea. My updater is currently written in shell, so doesn't really fit in with the rest of emesene, a Python one would be better. However an OS X update needs to be direct and pain free as possible, so if these changes go ahead the updater needs to install the update directly i.e download a patched emesene directly and copy into to the application bundle

**Comment by c10ud** [comment]
well, it depends on the modifications we need to make in order to support osx update: we can already download stuff directly from github, i guess we could start integrating your updater changes with support to "check for updates" and "alert on new update" only, then we can move on and see how we can add code to directly update the osx without too much shell power

**Comment by ghost** [comment]
I can create a git diff and upload a patch. If the updater could download the patch and apply it using patch -p1 would only require one or two shell commands

**Comment by c10ud** [comment]
looks good, in case of different version the updater would have then to look in your website for the patch file and apply it.. 

if you can bring back the changes you did in the code for making emesene look for updates, we could start taking a look and see how to integrate them

**Comment by ghost** [comment]
Yeah will do, i really messed up my repo so i deleted it. Will fork and try again

**Comment by c10ud** [comment]
ok, pulled it joshf changes, now i am accepting ideas on what to do next in order to make other platforms take benefit of this "check for updates" option -- VERSION file? parsing of emesene/gui/base/Handler.py? 

i am still not sure

**Comment by marianoguerra** [comment]
what if we put a file on the repo with the version number and the client does a GET of the file and compares with the version it has locally.

other ways would be considered "calling home" and should be opt-in and not opt-out.

**Comment by Sbte** [comment]
That's about the same as what c10ud just implemented

**Comment by marianoguerra** [comment]
sorry, somewhere I read something like "get the OS version and count users" and wanted to be clar about the opt-in stuff

that happens when you read stuff at work :P

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/commit/54006dd352e33ae062300bbc1d84ffda81eaf8a6

and

https://github.com/emesene/emesene/commit/1af8129579771e6e7464a3cef750cc90b9361307

2011/6/3 marianoguerra
reply@reply.github.com:

**Comment by c10ud** [comment]
well, collecting stuff could be interesting, but requires a good server capable to handle > 100k requests per day (low estimate of emeseners), unfortunately github doesn't allow to view page hits... i don't really think we would be stealing anyone privacy (good number of apps do this) but in the end i don't care too much, so the current "solution" is quite ok to me
