### ISSUE TITLE
plugins?

### ISSUE THREAD

**Issue by andresql** [emesene/emesene#614]
Is any way to use the plugins thar where available for the previous verion? i realy liked importan user plugin, that opens a conversation window ass son as some one comes online

**Comment by arielj** [comment]
They are not compatible, emesene2 was built from scratch with a different design

You can fill plugin suggestions here https://github.com/emesene/emesene-supported-plugins and wait until someone port or implement that plugin.

**Comment by andresql** [comment]
ok thanks!

**Comment by pjalegria** [comment]
can someone tell me how to install plugins?

**Comment by arielj** [comment]
For now, you can only download the only few plugins from here https://github.com/emesene/emesene-supported-plugins and copy them inside emesene's plugin folder, there are not many plugins yet, so nobody got into doing a better installer, I think someone is working on that.

**Comment by andresql** [comment]
where can I find emesene's plugin folder? in the .config/emesene2 theres none plugin folder..

**Comment by arielj** [comment]
There should be a plugins folder on emesene's installation folder, I don't know where's that on linux, I'm on windows, check where is emesene installer on your package manager.

**Comment by pjalegria** [comment]
i can find it...

**Comment by Sbte** [comment]
In emesene 2.11.6-devel, there's now a plugins folder in .config/emesene2

If you have emesene installed, it should be in usr/share/emesene/emesene
