### ISSUE TITLE
No Fedora and Suse Packaging/Info on site

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#616]
There's no info in the download section about Fedora and SUSE. I've looked into it myself and contacted both distributions and I made some 2.11.5 packages to distribute in the meantime until they decide to start officially packaging it.
The following is a reposted comment, I figured it would be better to put it here ;)

I contacted fedora and OpenSUSE 3 weeks ago about packaging 2.11.4. Looks like fedora has put it on hold, probably because of the release of fedora 15. Suse on the other hand hasn't acknowledged my request at all.

Anyway, I made some packages for 2.11.5:
Fedora 15 and later (made to official Fedora Guidelines): http://www.2shared.com/file/GaIgcBEW/emesene-2115-1fc15noarch.html
OpenSUSE (latest release): http://www.2shared.com/file/wM158p7-/emesene-2115-1susenoarch.html

**Comment by c10ud** [comment]
we want to avoid having to worry about every single distro packages, i'm happy to add links and stuff, but that really needs to be done "upstream"... if they don't want emesene2 or whatever, it's up to them

**Comment by Mystro256** [comment]
Well fedora has interest in it, they're just taking a while to release it. To quote the message I got from the maintainer: "I still need to fix locale files handling and inform upstream about the license updates required."
Fedora has very high standards for packages put in the official repository, thus it might take a while. I just thought I could package it as a "for the time being," as a quick fix.

Although I don't think OpenSUSE has interest or at least not now, but it's not to hard to modify the fedora package to work with SUSE. I just figured I might as well make both anyway as it's only a few lines to modify.

**Comment by c10ud** [comment]
closing issue because they're too much to track, when new info is available just drop a line here, in the ML or blog comments, thanks

**Comment by Mystro256** [comment]
Can I get my packages linked on the downloads page (marked as unofficial packages)? I'm sure they will be of use at least to some.

**Comment by c10ud** [comment]
done http://blog.emesene.org/p/downloads.html

2011/6/4 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
Thanks, I'll post here when I hear from them
