### ISSUE TITLE
Error notifying nudges

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#617]
The conv_message signal sends None as the msgobj.display_name and notifications crashes there, i've workaround this, checking if the value is None to do something else, but I'm not sure if msgobj.display_name should be None or not.

Reproduce:
1-Send a nudge to a contact
2-The contact should see an error on the terminal about text being none that can't be decoded
(The nudge should fire a notification for the bug to appear, like starting a new conversation)

If you do something like this on notifications.py -> _on_message
                display = msgobj.display_name or msgobj.account
                text = _('%s just sent you a nudge!') % (display)

it works

should msgobj.display_name be None?

**Comment by c10ud** [comment]
could be? if the contact doesn't have a display_name..?

2011/6/1 arielj
reply@reply.github.com:

**Comment by arielj** [comment]
The sender of the nudge has a display name, it has a nick name and the profile is not broken, other messages has the right display_name, the problem only happens when I receive a nudge.

**Comment by c10ud** [comment]
see on_conversation_nudge_received(self, papycontact, pyconvevent):
        ''' handle received nudges '''

seems like we're not setting message.display_name in there, it must be
fixed in there :D

2011/6/1 arielj
reply@reply.github.com:
