### ISSUE TITLE
Chat group stop working

### ISSUE THREAD

**Issue by pjalegria** [emesene/emesene#618]
Chat group stop working on 2.11.5 :(

**Comment by astagi** [comment]
details?? something shown in the terminal??

**Comment by pjalegria** [comment]
i got this:

/usr/share/emesene/emesene/gui/gtkui/**init**.py:107: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()

**Comment by Sbte** [comment]
What exactly is not working? And what kind of group chat?

**Comment by pjalegria** [comment]
You can see the nickname of the person that is talking to you, only de group name

**Comment by Sbte** [comment]
Ah, that's probably my fault then.

Could you check if it worked here:

https://github.com/emesene/emesene/commit/1009e395e57660f63c4d7a54faa1b853c0ab67f9

And broke here:

https://github.com/emesene/emesene/commit/547acdbe7397790c5ac0c0676aa4f861ed8f0e3c

If you're using git, just use git checkout. If not, start using git, and use git checkout.

**Comment by pjalegria** [comment]
sorry, i don t use git... its possible to fix this on the repository version?

**Comment by pjalegria** [comment]
This is really a big problem for me because I use every day an msn group, I was very delighted when the update to version 2.11.5 and finally saw that this problem was solved , but unfortunately only worked two days :( although this emesene remains has my favorite IM and i wont to congratulate the team of developers by the excellent work done :) thanks

I hope that "soon" be able to solve this problem... ;)

sorry for my english

**Comment by Sbte** [comment]
I have no clue if that's actually the problem, and I also have no clue on how to reproduce it. And I won't start changing random things until I know if that's the thing that caused it...

Anyway, how did it work in 2.11.5 at first, but later didn't? We can't change anything to the version you have installed right?

**Comment by pjalegria** [comment]
clould it be msn servers problem??? i dont now, one day is working well, next day stop working

**Comment by c10ud** [comment]
@sbte: from what i see your change affects notifications only so.. (and it looks correct)

i'll try again the account with groups.im chats, but noone touched anything so..

**Comment by c10ud** [comment]
tested right now and they work: 
http://img849.imageshack.us/img849/3047/screenshothim.png

**Comment by pjalegria** [comment]
could it be something on preferences?? could you tell me how do you have your configuration?
thats mine 
http://img707.imageshack.us/content_round.php?page=done&l=img707/5850/screenshotbr.jpg#
thanks

**Comment by c10ud** [comment]
no preference at all, just install emesene2.11.5 and it works

**Comment by c10ud** [comment]
p.s. that was groups.im

**Comment by pjalegria** [comment]
I have emesene2.11.5 installed

**Comment by c10ud** [comment]
can we have a screenshot of what's not functioning please?

**Comment by pjalegria** [comment]
only group name
http://img11.imageshack.us/i/screen2qd.png/

**Comment by c10ud** [comment]
are you sure you're running the latest emesene? try downloading from
here: https://github.com/emesene/emesene/tarball/master

extract and run the emesene script

2011/6/3 pjalegria
reply@reply.github.com:

**Comment by pjalegria** [comment]
emesene 2.11.5

http://img217.imageshack.us/i/screen3dq.png/

**Comment by c10ud** [comment]
i tried installing from the ppa and they work :s can you try using the ppa?

2011/6/3 pjalegria
reply@reply.github.com:

**Comment by pjalegria** [comment]
Im using PPA version

must be any configuration...

**Comment by Sbte** [comment]
You could try to back up and delete .config/emesene2 and see what happens. That'll delete all your settings though.

If that fixed it, it would probably be useful if you could find the differences in the config file between the not working and the working version.

**Comment by pjalegria** [comment]
I have uninstalled emesene... reboot 
delete all configuration files... reboot
install emesene from PPA... and is working...

yupiiiiiiiiiii

**Comment by Sbte** [comment]
And is there any chance that you also found what caused this? If it's something in your configuration, then it could be a bug, but if there were still some leftover files from an old version of emesene or something (if that's possible), then it's not of course.

**Comment by c10ud** [comment]
maybe you set an alias for that group.im (?)

**Comment by Sbte** [comment]
Aliases are saved on the ms server iirc, so probably not.

**Comment by c10ud** [comment]
just throwing ideas, i didn't actually try that out...

2011/6/3 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
I'm throwing them back ;)

A diff of the config file would really help.

**Comment by pjalegria** [comment]
I have deleted all... for now is working ok :D

**Comment by Sbte** [comment]
Let's close this issue then. Please tell us exactly what settings etc. you changed if this happens again. I don't think we can help you otherwise.
