### ISSUE TITLE
Emesene 2 theme lost

### ISSUE THREAD

**Issue by mvargasn** [emesene/emesene#619]
First: excuse me for my english.. I am not very studied in english

My problem is that in Extension section of Prefecerences I clicked on Sync with Emesene 1 and after of these the theme of conversation window isn't the Adium (emesene 2 default) rather than is the emesene 1 old theme..

I would have the emesene 2 conversation theme again

**Comment by c10ud** [comment]
i don't think the sync too touches themes... @4ndreast4gi

**Comment by hit** [comment]
same here, no adium themes for me.
http://www.upload.ee/image/1389477/Kuvatommis-Eelistused.png

**Comment by pepeleproso** [comment]
hit go to:
1- extensions
2. In categories combo select "conversation output"
3. On second combo select adium output
4- click redraw main screen button

**Comment by hit** [comment]
pepeleproso: no such extension there, it's gone :s it got lost somehow and i don't know why.

**Comment by astagi** [comment]
nope, synch doesn't touch themes at all ^^

**Comment by pepeleproso** [comment]
do you have python webkit installed?

**Comment by Sbte** [comment]
@mvargasn, you probably also accidentally changed the conversation output while you were in the Extensions tab. Just change conversation output back to Adium and everything should be fine.

**Comment by hit** [comment]
i do now and themes are also back, no idea why i had webkit uninstalled :o thank you!

**Comment by mvargasn** [comment]
pepeleproso: I did exactly what you say and does'nt worked, the conversation theme continue like emesene 1.6.X

**Comment by mvargasn** [comment]
I have reinstalled the app many times and the problem continues, something left in the registry (I think)

**Comment by mvargasn** [comment]
jeje SOLVED ISSUE.. thank you to all
