### ISSUE TITLE
ValueError: empty separator

### ISSUE THREAD

**Issue by hit** [emesene/emesene#622]
Pressing enter in chat window produces this:

Traceback (most recent call last):
  File "/home/hit/Apps/emesene/emesene/gui/gtkui/TextBox.py", line 203, in _on_message_send
    self.on_send_message(self.text)
  File "/home/hit/Apps/emesene/emesene/gui/base/Conversation.py", line 265, in _on_send_message
    custom_emoticons = gui.base.MarkupParser.get_custom_emotes(text, self.emcache.parse())
  File "/home/hit/Apps/emesene/emesene/gui/base/MarkupParser.py", line 156, in get_custom_emotes
    parts = chunk.split(shortcut)
ValueError: empty separator

Also the message won't be sent.

**Comment by c10ud** [comment]
version?

**Comment by hit** [comment]
version is git. sorry for closing, wrong button.

**Comment by c10ud** [comment]
are you sending something unusual? any (custom) emoticon?

**Comment by hit** [comment]
doesn't matter, i just can't send anything. even plain text.
seems like some fancy custom emoticon shortcut problem(?). bunch of them were imported from emesene 1.x. if i only knew which is the troubling one, 'cause there are many of them.

**Comment by c10ud** [comment]
could be, seems like you have an empty entry in shortcuts

**Comment by hit** [comment]
indeed, found that emoticon now. one of them had indeed empty entry there so it's fixed now. but shouldn't sending messages be still available regardless emoticon errors?

**Comment by c10ud** [comment]
it should, but usually empty emoticons aren't allowed

2011/6/3 hit reply@reply.github.com:

**Comment by c10ud** [comment]
i'll close this issue, we'll fix it if someone else faces this problem..
