### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#623]
Traceback (most recent call last):
  File "/home/riky/msn/emesene2/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riky/msn/emesene2/emesene/e3/common/Signal.py", line 111, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

@sbte

**Comment by Sbte** [comment]
c10ud, that has been there ever since I used emesene I think. Still no clue. I'll try to make it more informative.

**Comment by marianoguerra** [comment]
On Fri, Jun 3, 2011 at 10:55 AM, c10ud
reply@reply.github.com
wrote:

> Traceback (most recent call last):
>  File "/home/riky/msn/emesene2/emesene/e3/common/Signal.py", line 66, in emit
>    if callback(_args, *_kwargs) == False:
>  File "/home/riky/msn/emesene2/emesene/e3/common/Signal.py", line 111, in **call**
>    raise TypeError('Method called on dead object')
> TypeError: Method called on dead object
> 
> @sbte

we should catch that and unsubscribe the signal.

that means that the object of the method was garbage collected so the
signal should be unsubscribed then (that's what weak references are
for)

**Comment by Sbte** [comment]
That, or we could just fix the error message, and see what function it was from an unsubscribe it properly. Or both.

**Comment by marianoguerra** [comment]
On Fri, Jun 3, 2011 at 11:10 AM, Sbte
reply@reply.github.com
wrote:

> That, or we could just fix the error message, and see what function it was from an unsubscribe it properly. Or both.

I think the idea of using weak references for signals is to avoid
consuming memory because the only reference left is the one fron the
signal handler, of course the best solution is to unsuscribe all the
handlers when it's due, but ht eweakreferences are there to help us
when we forget.

maybe log + unsubscribe would be useful, we avoid having dead signal
handlers and we are notified about them

**Comment by Sbte** [comment]
```
        except TypeError:
            to_remove.append(callback)
```

on line 68. It's already there, but the error is still raised because of 

```
            traceback.print_exc()
```

I'll turn that into a more informative warning.

**Comment by marianoguerra** [comment]
On Fri, Jun 3, 2011 at 11:54 AM, Sbte
reply@reply.github.com
wrote:

> except TypeError:
>                to_remove.append(callback)
> 
> on line 68. It's already there, but the error is still raised because of
> 
>                traceback.print_exc()
> 
> I'll turn that into a more informative warning.

ok, I didn't read the code, that is not a raise but just a print of
the exception raised, it must been left while developing it.

**Comment by Sbte** [comment]
This should help right?

https://github.com/Sbte/emesene/commit/2d79b212c103e2dc7ea5f946b1696cf72a8bc67a

**Comment by marianoguerra** [comment]
On Fri, Jun 3, 2011 at 12:04 PM, Sbte
reply@reply.github.com
wrote:

> This should help right?
> 
> https://github.com/Sbte/emesene/commit/2d79b212c103e2dc7ea5f946b1696cf72a8bc67a

yep, but sill, it's not a warning, it's expected behaviour, we should
just keep the message to add the unsubscribe calls where missing.

**Comment by marianoguerra** [comment]
On Fri, Jun 3, 2011 at 1:08 PM, Mariano Guerra
luismarianoguerra@gmail.com wrote:

> On Fri, Jun 3, 2011 at 12:04 PM, Sbte
> reply@reply.github.com
> wrote:
> 
> > This should help right?
> > 
> > https://github.com/Sbte/emesene/commit/2d79b212c103e2dc7ea5f946b1696cf72a8bc67a
> 
> yep, but sill, it's not a warning, it's expected behaviour, we should
> just keep the message to add the unsubscribe calls where missing.

or it's a warning because we should unsubscribe :P

I think it's fine

thanks!

**Comment by Sbte** [comment]
Yes, so it's a warning right? It's nothing critical, but still something we want to fix. If not, then what is it? Debug? Hard to notice them then if they happen rarely like this error and papyon is spamming 1000 lines a second :P

**Comment by Sbte** [comment]
Ok, I'll push it

**Comment by c10ud** [comment]
great, then we'll see where the "issues" are :D
