### ISSUE TITLE
Install plugins

### ISSUE THREAD

**Issue by pjalegria** [emesene/emesene#624]
Can someone tell me how to install plguins???

thx

**Comment by arielj** [comment]
Read here https://github.com/emesene/emesene/issues/614

Only music plugin is available for emesene2 https://github.com/emesene/emesene-supported-plugins

copy those files inside emesene's plugins folder (inside emesene's installation path)

**Comment by Sbte** [comment]
Or now in git master into .config/emesene2/plugins

Seems more user-friendly to me.
