### ISSUE TITLE
Improvement suggestion: bring support to the characters of Messenger Plus! for Emesene

### ISSUE THREAD

**Issue by leonardo-lemos** [emesene/emesene#626]
Messenger Plus! is an extension for Windows Live Messenger that adds new functions to the program, one of these functions is the ability to generate special characters (codes) that give an effect more in words and nicknames, such as the use of the gradient in words, color background in the words, colorful words and so on. Messenger Plus! is used by 62 million people worldwide and has been downloaded over 500 million times, including support for special characters is laborious, but will leave Emesene much more complete.

References:

Messenger Plus! Website: http://www.msgplus.net/
Gradient Nickname by Messenger Plus! image: http://i54.tinypic.com/24bj76u.jpg

**Comment by arielj** [comment]
Gradients are already supported, just use [c=1]text[/c=5] and you'll have a gradient around the word text.

Maybe Plus! handles uses another keyword, but [c=X] is supported on the official client.

What else can you do to your nick with plus?

I also think background colors for text is supported but I don't know what's the keyword for that.

EDIT: for background colors do [a=#startcolor]text[/a=#endcolor] and you'll have a gradient background

**Comment by c10ud** [comment]
we support this from like.. emesene1.0...but we don't want to encourage the use of it since it breaks people with other clients such as pidgin, empathy, web-messengers, etc.

as arielj said though, emesene already supports plus colors etc.
