### ISSUE TITLE
Little request: load themes from config dir

### ISSUE THREAD

**Issue by Lagg3r** [emesene/emesene#627]
I know this may be an obvious request but, please, make it possible to load themes (conversations, emotes, sounds, etc) from ".config/emesene2" dir.

**Comment by Sbte** [comment]
I was working on this yesterday, bit it's a lot harder than the plugins. We'd probably need a class similar to the AdiumEmoteThemes class. Maybe a base class overloaded for the other themes, so we can easily add a path config_dir/themes/... .

@pepeleproso

**Comment by pepeleproso** [comment]
I will start it in a separate branch and told you when it's ready

**Comment by Lagg3r** [comment]
That's great, thanks! :)

**Comment by pepeleproso** [comment]
done in my repo. It's working but I need to fix QT UI, before merging.

**Comment by Lagg3r** [comment]
Yes! That's exactly what I was talking about. Thanks!

**Comment by Sbte** [comment]
pepe, don't you have to make the same changes in gtk? It uses gui.theme.user all over the place for example.

**Comment by pepeleproso** [comment]
I fixed gtkui while i was doing the changes. The reason a mention qt is because i don't have qt libraries in my system so I can't test. Now the work it's complete. If I don't find any issues I'll merge this today.

**Comment by Sbte** [comment]
Where did the other 4 commits go?

**Comment by pepeleproso** [comment]
Done. I have to fix the plugins repo too.
