### ISSUE TITLE
message disorder in group chat

### ISSUE THREAD

**Issue by marianoguerra** [emesene/emesene#63]
a user reported that with group chat the messages seem to appear dissordered or from different users, I think it may happen with the addium widget since I never tested that.

**Comment by SWOriginal** [comment]
i think this only happens if your using a different adium theme that has disabled the user pictures

i cant recreate the issue using the included renkoo theme

**Comment by c10ud** [comment]
@mariano: i didn't check the code (yet), but is adiumtextbox capable of knowing that a different user wrote last-received-yet-consecutive message already?

i mean:
me writes: hai
x writes: hai sir
y writes: hy guises

in this case y is a consecutive incoming message, but it can't be treated like a consecutive message incoming from x. is this option built in already? if so, can you do it or point out where to look at? (not@home now)

**Comment by marianoguerra** [comment]
e3.common.MessageFormatter

**Comment by c10ud** [comment]
Fix incoming messages from different users with AdiumTextBox in multichat. Closed by d978dffff512149b5488fc911989f78c45ace612
