### ISSUE TITLE
Add Luxembourgish Translation

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#630]
Emesene was in the past fully translated into Luxembourgish on Launchpad, but wasn't added. Now I translated it fully in Luxembourgish again. Here is the ISO-Code "lb". https://translations.launchpad.net/emesene/trunk/+pots/emesene/lb/+translate

**Comment by Sbte** [comment]
It's already there afaik

https://github.com/emesene/emesene/tree/master/emesene/po/lb/LC_MESSAGES

I added it a week ago or so, so it should be in 2.11.5. It'll be updated again next time we pull the translations from launchpad.

**Comment by ghost** [comment]
Sorry there happened something wrong certainly when I updated emesene from the git repository. Thanks by the way for adding it ;)
