### ISSUE TITLE
emesene closes when i send a message

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#632]
I've got a pc with Windows XP installed.

I've just insltalled emesene in that PC and it runs perfectly, i can login, even i can see my contac list, but when i select one to have a private conversation., and hit Enter or Send to send a message the whole program shuts itself down.

No error log, no message

What can i do....

**Comment by arielj** [comment]
What version are you using?

**Comment by ghost** [comment]
Windows: (2.11.5)

**Comment by arielj** [comment]
Damn, we thougth we had that fixed :P.

Let me check again the installers...

**Comment by ghost** [comment]
Right... Let me know when fixed... I'm using the Linux version in this computer right now and it works fine... The problem is the one with Windows XP

**Comment by ghost** [comment]
The dll fix didn't make it into 2.11.5. For the time being you have 2 easy options. Use text output instead of adium. You will find this in extension in preferences. OR you can try an experimental 2.11.6-devel package from http://mediafire.com/emesene to use adium themes.

@arielj the installer wasn't swapped with yours as far as I know. The problem should be fixed.

**Comment by ghost** [comment]
It solved it for the moment, thnx...

When it's fixed let me know i'm closing this then....

Thank you very much for your help!

**Comment by ghost** [comment]
@javiertroya I am currently uploading a new 2.11.6-devel package that includes most of the features and fixes up until today. It includes a improved installer if ur interested in testing it out.

**Comment by ghost** [comment]
thnx i'll test it right away....

**Comment by arielj** [comment]
javiertroya, what did you do to solve it for the moment?

**Comment by ghost** [comment]
I use text Output instead of Adium in the Extensions tab....
