### ISSUE TITLE
can't remenber expanded status of group with special chars

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#633]
how to reproduce:
1- in dummy session change "pirates" group to "pirätes"
2- expand group
3- close emesene and reopen
4- group it's unexpanded.

**Comment by c10ud** [comment]
i guess the special chars are badly interpreted when written/read from emesene json config..

**Comment by Sbte** [comment]
pepe, how are you able to rename dummy stuff?

**Comment by c10ud** [comment]
i guess good ol' src code..?

2011/7/1 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
Yeah, but not in emesene right? :P

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/blob/master/emesene/e3/dummy/Worker.py#L98

2011/7/2 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
yeyeyeye, but I'm just wondering if papyon even allowed that for example. And if dummy simulates that. I'll just use my test account instead next time I try it. Unless someone else fixes it of course.

**Comment by pepeleproso** [comment]
I change source code to try that

**Comment by c10ud** [comment]
update?
