### ISSUE TITLE
No option to turn blinking tray off

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#640]
For any non-unity or ubuntu classic users, the tray blinking may not want to be used but theres no way to turn it off. Personally, I use ubuntu with gnome 3 and gnome shell, and the blinking doesn't work too well with gnome-shell and is virtually pointless, thus I would want to turn it off (though I can live with it). Theres also non-ubuntu users which find this too distracting. Either way it's not like adding more customization to the user creates any issues.

Perhaps adding an extra option to the tray icon menu (in extensions) called "Tray Icon Without Blinking" and rename the current to "Tray Icon With Blinking" would be the best implementation.

Any thoughts?

**Comment by arielj** [comment]
Another extension? I don't know, I'd rather choose a config value or a plugin, the difference is so tiny that I don't think it justifies all the duplicated code that will be on both extensions.

**Comment by Mystro256** [comment]
Fair enough, you have a good point. I really don't understand how half of the emesene code works to be honest, so I wouldn't be able to have the liberty to have much say.

**Comment by Mystro256** [comment]
I personally don't care too much about this anymore, so I'm going to close this. If it really bothers me I'll make a commit or two, but unless someone else cares, theres no need to have this open.
