### ISSUE TITLE
No contacts list

### ISSUE THREAD

**Issue by Madeco** [emesene/emesene#642]
I'm trying emesene 2.11.5 on Windows 7, but if I login with an msn account, google account or facebook account, emesene doesn't show the contacts list, so I have a blank window

I make a screenshot about the issue
http://img689.imageshack.us/img689/8467/emesenex.png

**Comment by ghost** [comment]
Try sort by status. Also enable show offline contacts and blocked contacts.

**Comment by arielj** [comment]
Can you run emesene using the emesene_debug.exe file? (if you are running emesene from source just run emesene from a cmd)

Check if you have some error on the console about the contact list.

**Comment by c10ud** [comment]
seems like the user isn't interested in solving the issue, closing
