### ISSUE TITLE
Problem with group conversation

### ISSUE THREAD

**Issue by ExtremeMultiman** [emesene/emesene#643]
I'm Italian, Using emesene 2.11.5 on ubuntu 10.10.
Got this problem with audium plugin.
If no chat windows are open a new windows with "Conversazione di gruppo"(group conversation) title full gray pops up.
If a chat windows is open no tab with that title get open.
Can't send message cause can't see message zone or users and users message in multichat window.
But I get notices from ubuntu with message I receive from other users.
Closing all the chat windows get me out of multichat.

Does audium not work with multichat?

**Comment by ExtremeMultiman** [comment]
ok, correction, it happens also with text output... seems one of users in list makes it not work... cause I opened another multichat with diffrent ppl and it does work...

**Comment by ExtremeMultiman** [comment]
ok other correction... it happens only when someone is in pending.

**Comment by Sbte** [comment]
pending?

**Comment by ExtremeMultiman** [comment]
When you invite someone in multichat and Windows live messenger try to contact it but somehow it fails even if the contact is online, the client make it stay in a "limbo" status where the user in the multichat but wlm is awaiting some kind of confirmation that never happens so he can't read or send messages.

I wasn't in a pending status, but some other user was and my chat wasn't working for it. I couldn't see it from emesene, someone with last wlm told me and recreate the room without the pending contact.

ps: can you open group chat from emesene right now?

**Comment by c10ud** [comment]
probably there's some hidden uncaught exception, maybe already fixed in 2.11.6-devel, please try it out

**Comment by c10ud** [comment]
try with 2.11.7 or we assume this bug is gone

**Comment by c10ud** [comment]
no response
