### ISSUE TITLE
Problem with Preference window closing

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#644]
If i open the preference window (GTK), leave it for a few seconds and then try to close it, it  will not close. It will not respond to me clicking the close button. Its not a major problem, it just annoying.

emesene 2.11.6-devel
OS X SL 10.6.7

**Comment by arielj** [comment]
I can't confirm this on Windows XP, maybe it's some mac only bug?

Do you have some error on the terminal? something?

**Comment by ghost** [comment]
No error output, probs a GTK bug. The preference window floats above every other window, which is pretty weird. I think that is what is causing the problem. Not sure if that was intentional by design or not?

**Comment by Mystro256** [comment]
I can't confirm this on Ubuntu either, perhaps the GTK port/build for Mac has issues with the specific window class? The preference window floating over other windows happens in my ubuntu install too, so I would figure this is the intention, not a mac issue.

**Comment by c10ud** [comment]
we had to change the window hint because it was causing the window decoration to not appear in gnome-shell.. i guess gtk-osx handles this weird gtk window hint we set in some mysterious way? could be

**Comment by Sbte** [comment]
So, maybe you could try this joshf?

Change

https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/Preferences.py#L65

to

```
        self.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DIALOG)
```

**Comment by ghost** [comment]
Seems to be fixed with that change:

```
    if sys.platform == 'darwin':
        self.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DIALOG)
    else:
        self.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_MENU)
```

**Comment by c10ud** [comment]
no, we need to find a good hint..or keep dialog and add a close button for those who like to play with window decorations.. that's good as a temp workaround if you want to make a new package though

**Comment by Mystro256** [comment]
Maybe just add a close button on the bottom left? (ie @c10ud 's idea)

edit: Here's a screeeny of what I mean:
<img src=http://i53.tinypic.com/2yyup9k.png>

**Comment by ghost** [comment]
Have reuploaded my OS X build with a temporary fix. I think the close button is a pretty good idea.

**Comment by pepeleproso** [comment]
Seeing the code close button it's already there but isn't packed in the dialog

**Comment by pepeleproso** [comment]
close button it's now there. Could we close this?

**Comment by Mystro256** [comment]
yep, seems valid to do so, as there's no reason to use the problematic dialog type and has since been reverted.

**Comment by c10ud** [comment]
don't be afraid to close issues :D
