### ISSUE TITLE
Preferences not being stored on Emesene 2.11.4

### ISSUE THREAD

**Issue by toastwaffle** [emesene/emesene#646]
On Ubuntu 11.04, Kernel 2.6.38.8, emesene doesn't remember preferences such as muting sounds, displaying contacts by group etc.

**Comment by c10ud** [comment]
use latest version http://blog.emesene.org/p/downloads.html

**Comment by toastwaffle** [comment]
I have the ppa, 2.11.4 is the latest version available

**Edit - My Bad, didn't reload the repos**

**Comment by c10ud** [comment]
Published in:    natty
1 → 2 of 2 results    First • Previous • Next • Last
Package
Version
Uploaded by
 emesene     2.11.5-0+emesene1  Devid Antonio Filoni (2011-05-30)
 papyon  0.5.5-1ubuntu1.2   Omer Akram (2011-04-30)

https://launchpad.net/~emesene-team/+archive/emesene-stable?field.series_filter=natty

2011/6/10 toastwaffle
reply@reply.github.com:
