### ISSUE TITLE
(GTalk) emesene crashes when you try to change the avatar

### ISSUE THREAD

**Issue by sparklewind** [emesene/emesene#649]
Log in, and click on your avatar in the main window. emesene will crash immediately, instead of opening a window where you can select an image. It should be easy to reproduce. I am on Windows 7 (emesene 2.11.6-devel). The protocol I'm trying to use with emesene is GTalk.

**Comment by ghost** [comment]
I can confirm this happening in with the GTalk protocol.

Logging into GTalk for the first time, with no gtalk configs, it doesn't crash. You can change the avatar, but it doesn't appear to take affect. When you logging next time, the avatar appears.

After the first login and the config is created, clicking on the avatar in the user panel crashes emesene.

**Comment by astagi** [comment]
Nothing happens for me... are u workin with Qt??

**Comment by arielj** [comment]
I can't confirm this either, tried with and empty config folder and nothing happens, tried after that with a config and an avatar set and also nothing happens.

Does the Gtalk implementation support avatars and nicks? I have no idea, the avatar is never set.

**Comment by sparklewind** [comment]
I just downloaded the installer syst3m pointed me to. I doubt it's the Qt version.

**Comment by sparklewind** [comment]
I'm pretty sure both are supported in the protocol.

**Comment by c10ud** [comment]
http://yabfog.com/blog/2009/06/03/xmpp-vcard-python-script

reference

**Comment by c10ud** [comment]
it does NOT work, but i put some code in jabber in case someone wants to try fixing it:

https://github.com/emesene/emesene/commit/59d6cef2b180f97681c4a83cd6c7895b8275a230

closing the issue as it's not the focus of the development
