### ISSUE TITLE
TypeError: integer argument expected, got float  

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#651]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/IconView.py", line 97, in pop_up
    path = self.iconview.get_path_at_pos(event.x, event.y)
TypeError: integer argument expected, got float

I don't know to reproduce

**Comment by Sbte** [comment]
View information -> Avatar history -> Right click on an avatar

**Comment by Sbte** [comment]
Same in avatar chooser

**Comment by zipatei** [comment]
Confirm!!!
