### ISSUE TITLE
click block contact in conversation

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#653]
/home/andre/emesene/emesene/gui/gtkui/ContactList.py:739: GtkWarning: IA__gtk_tree_view_expand_row: assertion `tree_view->priv->model != NULL' failed
  self.expand_row(path, False)

**Comment by arielj** [comment]
I can't reproduce this

Does it happen to every contact? what are your settings to display contacts? are those contacts inside a particular group? is that group expanded?
