### ISSUE TITLE
Nick with RTL chars

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#654]
Problems with this nick... 

[c=1]کílviα Cяυz[/c=11]

**Comment by Sbte** [comment]
Could you check if it works with emesene from around January? Something like 

git checkout 77c11662b0221cd85a4db10bd884d868fce2e333

Sorry if that breaks something, but I'm going to bed ;)

**Comment by zipatei** [comment]
In January was worse... :)

**Comment by Sbte** [comment]
Good, then it wasn't me who broke it. I'll look into it later

**Comment by Sbte** [comment]
Seems like it's somewhere in the Renderers chaos, not in the parser. The list retrieved from the parser is in the right order. Needs deep digging.

```
plustolist
[c=1]کílviα Cяυz[/c=11]
[$small][C=c10ud][/C][$/small]
<span foreground="#000000">ک</span><span foreground="#001919">í</span><span foreground="#003333">l</span><span foreground="#004C4C">v</span><span foreground="#006666">i</span><span foreground="#007F7F">α</span><span foreground="#009999"> </span><span foreground="#00B2B2">C</span><span foreground="#00CCCC">я</span><span foreground="#00E5E5">υ</span><span foreground="#00FFFF">z</span>
[$small]<span foreground="#696969"></span>[$/small]
[u'<span foreground="#000000">\u06a9</span><span foreground="#001919">\xed</span><span foreground="#003333">l</span><span foreground="#004C4C">v</span><span foreground="#006666">i</span><span foreground="#007F7F">\u03b1</span><span foreground="#009999"> </span><span foreground="#00B2B2">C</span><span foreground="#00CCCC">\u044f</span><span foreground="#00E5E5">\u03c5</span><span foreground="#00FFFF">z</span>\n<span size="small"><span foreground="#696969"></span></span>']
```

**Comment by c10ud** [comment]
i think the first character which is like an S is triggering some weird RTL thing, and since noone in the dev team uses RTL, we don't know what's wrong and how to fix it (i think it's an arabic character)

**Comment by Sbte** [comment]
http://en.wiktionary.org/wiki/%DA%A9

Yep. I don't think there's a way to handle this without breaking RTL support...

**Comment by c10ud** [comment]
cannot "fix" this. if that character similar to a S is the first, it triggers RTL and i guess that's what expect people who actually use them for real.
