### ISSUE TITLE
Webcam facility on emesene2?

### ISSUE THREAD

**Issue by ceeveebee** [emesene/emesene#655]
Hi i've just updated to the 2.11.4 version of emesene and I can't seem to find anyway of using my webcam.

I don't see an icon to start the cam nor do I see any webcam facility under the Preferences option

I take it that means there is no way of using my webcam? or am I missing a trick?

**Comment by ghost** [comment]
The current version of emesene (2.11.5) has what little webcam support it has enabled, but its far from complete. Currently there aren't really plans on fixing and polishing webcam support, not until someone that is interested in doing so comes along.

Read http://blog.emesene.org/2011/04/emesene-development-continues.html for more info.

**Comment by ceeveebee** [comment]
thank you syst3mfailur3 

I will get back to searching for an alternative - if there is one!

**Comment by c10ud** [comment]
afaik no other client has webcam because microsoft with wlm2011 forced some video codec that's not supported anywhere but their dlls
