### ISSUE TITLE
Can you make Emesene's 1.6 plugins work on Emesene 2? (Not an issue)

### ISSUE THREAD

**Issue by the98** [emesene/emesene#657]
Hi, I didn't know where I should post this question.

I have a plugin called "Status History Plus", which is capable of logging every contact that goes on-line and off-line. It's even able to log users that connect off-line (Invisible feature). I wanted to know if there was a way to make it work under Emesene 2. It's a great plugin I'd love for it to work.

I don't know anything about python, but maybe I'll be to make it work if I know what I should import from Emesene 2. This is what the plugin needs on Emesene 1.6:

import Plugin, Theme
import string, random, os.path, datetime

import gtk
import gobject
import pango

from time import *
from emesenelib.common import unescap

Maybe there are some equivalents and that's enough to make it work. Or maybe it needs to be re-written from scratch. Since I don't know anything about coding, I'm not sure, but if you say it can be done, I'll do some experiments.

Kind regards.

**Comment by c10ud** [comment]
it must be rewritten from scratch. @arielj is working on an emesene-2 "dummy" plugin that does nothing, so people can take a look and take it as a base for deploying the new plugins

**Comment by pepeleproso** [comment]
emesene 2 log status changes, you could see it in contact information window.
emesene 1.6 has a combo at the bottom whitch logs every contact status change, I made a plugin for emesene2 with the same functionality, it's in the plugins repo

**Comment by Sbte** [comment]
Also, the invisible mode was a 'bug', but I guess you could still make a plugin that checks whether a contact changes its status from offline to offline. I guess just subscribing the contact_attr_change signal and checking it would do.

**Comment by the98** [comment]
Invisible mode might have been a bug, but it was awesome because you could see if someone was online but in invisible mode.

Where is the plugin repo, pepecanalla? (I'm kidding, pepeleproso)

**Comment by pepeleproso** [comment]
https://github.com/emesene/emesene-supported-plugins

**Comment by Sbte** [comment]
@the98, if you like it, it's easy enough to turn it into a plugin
