### ISSUE TITLE
i18n: support for translations

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#66]
someone could start checking strings we use and wrap them with _( ) so we're ready for eventual translations

example:

"Preferences"
becomes
_("Preferences")

**Comment by andreskru** [comment]
Spanish traslator here.

**Comment by c10ud** [comment]
it's not a call for translators, it's a "call for people willing to dig the source and find tranlatable string and make them translatable" :)

**Comment by andreskru** [comment]
I understand. Anyway, spanish traslator here. :)
Sorry about the expectation.

**Comment by rockybalboa** [comment]
When we can start translate? Many of users would like to try it, but they can't because the language difficulty. :P

**Comment by Sbte** [comment]
I'll try to get this task done after my exams (in two weeks) if no one else manages to do it between now and then. That should at least mean a step forward.

But a question. How can people test it and properly report issues if they can't even read English? It's not that it's really stable already or anything ;)

**Comment by ricsipontaz** [comment]
If the task is only mean to change strings like this:

"Avatar chooser" -> _("Avatar chooser")

I can help do it.

**Comment by c10ud** [comment]
exactly, just fork, add _(" ") in the right places and ask for pulling :)

**Comment by ricsipontaz** [comment]
Okay, thanks, I started.

**Comment by c10ud** [comment]
ok, thanks to ricsipontaz we can close this issue

**Comment by rockybalboa** [comment]
Okay, thanks everyone. What is the next step? When it can be translatable on Launchpad?

**Comment by c10ud** [comment]
as soon as we approach something usable :P

**Comment by rockybalboa** [comment]
OK. If I can help just write it.
