### ISSUE TITLE
Login window contents should resize with window

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#662]
When maximized or just re-sized, the contents in the login window should change to match the size of the window. It looks weird to have a large window with a small username and password field.

**Comment by c10ud** [comment]
err.. you'd like to have a 1920px wide input box for your username?

2011/6/14 syst3mfailur3
reply@reply.github.com:

**Comment by Sbte** [comment]
I think it would look worse if we did this. Don't like the idea...

**Comment by ghost** [comment]
1.6.3 had it this way, and I personally liked it. It made the window look not empty.
If the rest of you don't like it, I'll close this.

emesene2 and emesene 1.6.3 side by side
http://i.imgur.com/BmUtA.png

**Comment by Sbte** [comment]
If anyone else is in favor of this change, just reopen. I'll just close it for now, since it's taking up issue space ;)
