### ISSUE TITLE
What is the source files for webcam in emesene 2.11.6-devel. (?)

### ISSUE THREAD

**Issue by andreas122** [emesene/emesene#664]
Emesene 2 is written in python, i downloaded the 2.11.6-devel and i see the webcam icons, i have not tested yet, but i want to learn what source files has to do with the webcam, so i can see how they work. (and meaby edit them).

So in emesene folder what are this source files that have to do with the webcam?

**Comment by c10ud** [comment]
http://groups.google.com/group/emesene/browse_thread/thread/537879648783ac08#

**Comment by andreas122** [comment]
in this link that you write, it dosent write where is this source files, and it writes: that WLM2011 use a new codec that is not avaible in the opensource, but so how emesene get working with the webcam?

**Comment by c10ud** [comment]
if you click the webcam button you should see an advice for devs, anyway see arielj response on that discussion:

To potential developers: check e3/papylib/PapyConference.py and gui/ 
gtkui/CallWidget.py if you want to try something.
