### ISSUE TITLE
Problem with chating check this

### ISSUE THREAD

**Issue by xXDestroyerGRXx** [emesene/emesene#667]
Hello im on ubuntu 10.10 and when i send talk to someone the messages come back to me in a new window and the avatars of every person is flickering,

**Comment by Sbte** [comment]
Seems like you have multiple instances of emesene opened. Clicking the x button hides emesene to the messaging menu (white/green envelope), doesn't close it.

If you want a different tray icon you can select it from preferences->extensions->tray icon
