### ISSUE TITLE
Toolbar uses blurry icons

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#67]
the toolbar in chat window uses icons from the emote theme and stretches them or shrinks them depending on your settings which makes theme hard to see when they're stretched beyond blurred, i think the toolbar should use icons from its own folder in the emote theme or from the default theme folder

*/toolbar/small

*/toolbar/normal

**Comment by c10ud** [comment]
if you think it's worth theming the toolbar, i can put a solution similar to the panel one, a specific subfolder. currently it's using a mix of emoticons and gtk stock icons. but we could convert all to custom images from themes

**Comment by SWOriginal** [comment]
yeah i think that would be best, at the moment it just looks inconsistent it wouldn't be so noticeable id it weren't for the scaling/stretching issue

in the toolbar themes i think its necessary  for */small & */large folders to fix this blurred  issue :)

**Comment by c10ud** [comment]
create a directory in themes/images/theme-name, like we did with panel...example:
themes/images/theme-name/toolbar and then put inside it seven icons with the names below:

```
    toolbar_path = os.path.join(self.theme_path, "toolbar")        
    if os.path.exists(toolbar_path):
        self.toolbar_path = toolbar_path
        self.tool_font = os.path.join(self.toolbar_path, "font.png")
        self.tool_font_color = os.path.join(self.toolbar_path, "font-color.png")
        self.tool_emotes = os.path.join(self.toolbar_path, "emotes.png")
        self.tool_nudge = os.path.join(self.toolbar_path, "nudge.png")
        self.tool_invite = os.path.join(self.toolbar_path, "invite.png")
        self.tool_clean = os.path.join(self.toolbar_path, "clean-chat.png")
        self.tool_file_transfer = os.path.join(self.toolbar_path, "file-transfer.png")
```

just make them "big" and the small version is created at runtime, if needed

```
    if toolbar_small:
        size = gtk.ICON_SIZE_MENU ------------> small version
    else:
        size = gtk.ICON_SIZE_LARGE_TOOLBAR --------> big version
```

lemme know if you have problems with this

**Comment by SWOriginal** [comment]
its much better now :), if possible could you enable it to use .svg aswell? i wasnt planning to use svg but since it will make it clearer ive re-done the toolbar theme in .svg

**Comment by c10ud** [comment]
well, just renaming them while keeping their format to svg _should_ do the trick. however i'm unsure of the impact on performances using svgs instead of pngs

**Comment by SWOriginal** [comment]
i thought about doing that but weren't sure if emesene would handle it properly, now everythings set up perfectly i'll have to work on the themes daily :)

i haven't noticed any performance issues whilst using them
