### ISSUE TITLE
Emesene dosn't open hotmail in browser

### ISSUE THREAD

**Issue by detlilleegernsven** [emesene/emesene#670]
I have installed mint debian 64 bit and it is working better then the normal linux mint 11 64 bit, my problem now is that when i want to se my mail i normally click on the icon in emesene (2.11.4) and hotmail should open, but it  dosn't open in firefox,only thunderbird opens and that's not good, because thunderbird takes a lot longer to open then hotmail in my browser

What to do ?

**Comment by c10ud** [comment]
tell your system to open html files in a browser :)

**Comment by detlilleegernsven** [comment]
Have choisen to make firefox opened my hotmail as default mail program (how it's been opened) but it's been opened not in firefox next the other windows i have opend but in full screen, in something that looks like a minimal version of firefox, but i want my hotmail to bee opend next to the other windows i have opened.

How to do that ?

**Comment by c10ud** [comment]
no idea, emesene just asks to open an html file..then it's up to the system configuration the decision on how to open it..you might want to ask in your distribution help forums

**Comment by detlilleegernsven** [comment]
Problem solved
