### ISSUE TITLE
Copy is not working in personal message

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#672]
When I try copying text from my own personal message in the main window, nothing happens. Both the keyboard shortcut and menu do nothing. Cut and paste are both working fine though.

I was also having some trouble with text in the output text in the chat window too, but i managed to get it to work after a bit. Don't know what happened it get it to work though.

2.11.6-devel on Win7.

**Comment by c10ud** [comment]
the custom widgets we use aren't really handling correctly the right clicks, i guess..

ctrl+c/v work here though
