### ISSUE TITLE
Can't send/receive messages in invisible status

### ISSUE THREAD

**Issue by marcosviv** [emesene/emesene#674]
Ubuntu 10.10, emesene 2.11.5 
Problem: There is no error reported. I can't send or receive messages while "offline". The program shows no error or problem, but the messages can't be sent/received

**Comment by marcosviv** [comment]
The same problem goes with being offline and logging in. Messages that have being sent to me don't get through. Messages I send to users offline don't get through either

**Comment by Mystro256** [comment]
i seem to get this issue as well. It never happened before but just started doing it recently. Maybe a change in Microsoft's Servers/Protocol?

**Comment by Mystro256** [comment]
for me it seems I only get messages from someone offline if I talk to them first. Any messages sent by the other party prior to my first message to them is never received. Messages sent to me while I'm disconnect are not received either.

<b>EDIT:</b> tried running emesene -vvv but I got no output when I tested a message.

**Comment by Mystro256** [comment]
After much testing, it's definately an issue with receiving, the sender doesn't matter if its libpurple (pidgin), papyon or the official client (tested via virtualbox), I still can't get offline messages, and when i'm invisible I can't get messages until I first send them a message.

**Comment by marcosviv** [comment]
Yes sir. Exactly the same problem. I've tried with pidgin, empathy, etc. I have the EXACT same problem. I'm not that into programming or computers, so if you do find a solution, please post!!!

**Comment by Sbte** [comment]
So the problem is that you can't receive offline messages? Does this same problem happen with pidgin or empathy (when they receive)? Just wondering, because it worked before, so it might as well be a regression in emesene somewhere.

**Comment by marcosviv** [comment]
I don't know if pidgin or empathy can receive messages offline, but this problem started right after I updated my emesene to emesene 2.0 (PPA-20110118)

**Comment by Mystro256** [comment]
I confirmed the issue on my computer being a problem with the package "network-manager"

I had version 0.8.9997, but downgrading to 0.8.4~git.20110319t175609.d14809b-0ubuntu3 (in natty repository), seemed to rid me of the bug completely.

Regardless, I wouldn't say it's a regression because I didn't have this issue with 2.11.5, but now I do. If @marcosviv also has a later version of network manager, then I can confirm this as a bug or issue with later versions of network manager.

**Comment by Sbte** [comment]
I'm wondering how that is even possible...

**Comment by Mystro256** [comment]
No idea :/

I downgraded the package because pidgin was having issues with it for whatever reason, but after testing with pidgin, virtualbox, and 2 sessions of emesene, it seemed to have disappeared completely after downgrading. Unless it's an issue wtih natty specifically? As I said, pidgin was having issues with it, I could be some sort of package conflict or something.... I'll need to test emesene with Oneric to be sure.

**Comment by Mystro256** [comment]
Hmm the issue seemed to still occur <b><i>sometimes</i></b> in virtualbox (with WLM)
Unless it's an issue with strange network configurations? It's quite baffling to be honest.

**Comment by marcosviv** [comment]
I've got maverik, and I've been having issues with network manager ... so I'll check in the repositories for a later version and check.

**Comment by marcosviv** [comment]
I've got NM 0.8.1 but can't find repositories ... help!

**Comment by Mystro256** [comment]
Well it should be fine then.... The versions of network manager I was referring to was the version provided in Oneric, thus you shouldn't be effected by the same issue I was having :(

There goes my working theory :P

I'm gonna try some more tests...

**Comment by marcosviv** [comment]
Well, good luck, I'd help if I knew what to do but I've done everythin I can :(

**Comment by Mystro256** [comment]
Well any testing you can do to narrow down what's causing the issue would help... I don't seem to have the issue anymore with my live.com or hotmail.com account.

Who knows, it may have just been a temporary issue with the messaging server (ie MSN's issue), conveniently fixed just before I downgrading network manager haha ;)

**Comment by marcosviv** [comment]
I still got it ... my version is emesene 2.0 (PPA-20110118). Is that 2.11.5?

**Comment by Mystro256** [comment]
@marcosviv
If you added the PPA (ppa:emesene-team/emesene-stable), then it will update to the latest in the update manager. If you check the ubuntu software centre, it should say "2.11.5-0+emesene2~maverick1" if you have the latest.

If I'm not mistaken, you have a beta version, the version 2.11.5 refers to the month and year (May 2011) apposed to what you have (Jan 2011). The PPA also should update papyon, which is a good idea, as it fixes a lot of issues.

@Sbte
I'm going to download Oneric Alpha, because there maybe a serious bug in Network Manager. This issue probably should be closed for now, unless upgrading doesn't fix marcosviv's issue or it starts to recur with someone else.

**Comment by marcosviv** [comment]
Well, if I go to the software center it says 2.11.5-0+emesene2~maverick1 (emesene), so I guess I got the latest version ... But if I click on Emesene-Help-About it says PPA-20110118

**Comment by Mystro256** [comment]
hmmm... try opening synaptic and see what it says

**Comment by marcosviv** [comment]
emesene2 is checked (version20110118) and emesene version 2.5.11 is unchecked. Should I uncheck the one unchecked and check the 2.11.5?

**Comment by Mystro256** [comment]
Yeah, I would assume you have the B.J. Stobiecki ppa added? (ppa:bjfs/ppa)

If so, you should remove it because it's depreciated, and conflicting with the stable ppa.

**Comment by marcosviv** [comment]
I have no idea, but Ima gonna do that!! maybe problem solved

**Comment by marcosviv** [comment]
WTF!! hmmm it removed emesene Stobiecki or somethin, now I have the 2.11.5 ... But it didn't download more than 500 K or somethin ... why?

**Comment by marcosviv** [comment]
Well now I have emesene 2.5.11 and some offline messages get through to me, but some others don't ... It seems its something related to if I speak first or the other does

**Comment by Mystro256** [comment]
hmmm, I still get this issue with the official client over virtualbox but only on a seldom basis. It seems to work fine with another computer I have with windows on it.

How are you testing it? Which client is the other end using? Can you narrow down the specific situation that you don't get a message?

**Comment by marcosviv** [comment]
Yeah, I tried with pidgin in my same computer, and I can only get the messages in offline status if I speak first
If the other end tries to speak to me or leave me an offline message it wont get through. Only if I do it first.

**Comment by Mystro256** [comment]
Yeah, sound like the same issue I was having but I don't seem to have it anymore... hmmm

**Comment by Mystro256** [comment]
Does it also happen with pidgin? ie log in invisible with pidgin using the account you used on emesene

**Comment by marcosviv** [comment]
Some offline messages get through, some don't (on pdgin).

**Comment by marcosviv** [comment]
More or less the same

**Comment by Mystro256** [comment]
This seems like it's not an emesene problem but rather an issue with MSN itself or your account. I may have fixed it for my accounts when I logged in using the official client via virtualbox... Unless it's an issue that just conveniently fixed itself
If so, this could also be a protocol bug, which MSN would be in the process of fixing.

Unfortunately I can't offer anymore help

**Comment by Mystro256** [comment]
I can confirm this an not an issue with Network Manager, which makes things make more sense. My downgrade was just a coincidence.

**Comment by marcosviv** [comment]
Allright then, I'll login with the official MSN client and see what happens ...

**Comment by marcosviv** [comment]
Well, I tried with a friend's MSN client in Windows. He can get all my messages, no matter if I'm offline or away, etc. I've tried sending myself messages while being offline (really offline) ... I tiped 1 (enter) 2 (enter) 3, 4, 5 and when I logged in I just got the "3". And if I'm invisible I don't get anything ... Or maybe sometimes one out of many.

**Comment by Mystro256** [comment]
I can confirm some messages lost between WLM and emesene, but seldom for me. I also would like to note this doesn't happen for me between emesene and pidgin, though I'm not denoting that it doesn't happen.

Anyway, this is obviously a papyon issue from what I can see, and the papyon dev's should be notified if not done so already, but I'm not really sure how to contact them myself to be honest. Sorry :(

**Comment by marcosviv** [comment]
Well, when is somebody "in charge" gonna say anything?!?! No admins readin'?

**Comment by Sbte** [comment]
https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

There you go

**Comment by Mystro256** [comment]
thanks Sbte

**Comment by Mystro256** [comment]
the bug has been posted here: https://bugs.freedesktop.org/show_bug.cgi?id=38607

**Comment by c10ud** [comment]
sometimes not all messages are saved in the server for some unknown reasons, so not all of them are delivered (example: adium receiving from WLM -> if the adium user is appearing offline and the wlm user tries to send OIMs they'll fail ..unknown reason)

**Comment by marcosviv** [comment]
I don't know what adium is, but I know in emesene you can choose to use it. I'm not using adium

**Comment by Mystro256** [comment]
I'm pretty sure he meant the msn client "adium" not the message theme style.

@c10ud
I take this is MSN's issue then? :(

**Comment by c10ud** [comment]
weird papyon issue, should happen with empathy too.. :(

2011/6/28 Mystro256
reply@reply.github.com:

**Comment by marcosviv** [comment]
So now all we can do is wait for MSN to solve it? Or are we done? ha

**Comment by Mystro256** [comment]
Well it's either papyon or MSN in general, either way it's out of the emesene developers hands and it's a bit of a waiting game to be honest.

As I said above, the bug I submitted for papyon is here: https://bugs.freedesktop.org/show_bug.cgi?id=38607
You can watch for activity there, or add yourself to the CC list to get updates via email.

**Comment by c10ud** [comment]
with further reading of this issue i think that:
"Please consider sometimes microsoft's servers tend to reply with nice
500s with no apparent reason, we should consider this"

is a reasonable answer for this. I've been unable to talk with a person for some days because of this 500 errors. I think they could depend on that person not clearing his/her OIM queue, so this is not an emesene bug (and probably not papyons too)
