### ISSUE TITLE
Issue with choosing directory for downloads

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#676]
Two bugs I've noticed:
the first one is very annoying, whenever i set the file transfer directory to /home/xxx/.config/emesene2/messenger.hotmail.com/xxx@gmail.com/trasfers in the options menu, it gets changed back to /home/xxx after i restart emesene2, but setting it in the config file (home/xxx/.config/emesene2/messenger.hotmail.com/xxx@gmail.com/config) with a text editor seems to fix that
As for the second one... While i my avatar gets saved (but not actually changed on my live profile, which I actually like), I still have to set my nick and personal message manually. Yes, I've tried setting them manually on my live profile, and while the personal message keeps appearing blank, the nickname is randomly set to my email addres or to a rather old nickname I haven't used for months. Not sure if this matters, but i'm using a gmail address to sign in on wlm.

**Comment by Sbte** [comment]
As for the last issue. You probably have a broken profile. Follow the instructions under Preferences -> Live Messenger. And never use emesene1.x again, or it will break.

**Comment by Sbte** [comment]
Also, do you close emesene properly? If you don't close it through 'file -> quit', or click 'redraw main screen' in the preference window, the preferences won't get saved. That'd explain the first issue.

**Comment by Soulsuke** [comment]
Changing every setting on my live page seems to have fixed the nick issue, i guess that leaving the old avatar unchanged somehow caused all that trouble with nickname and personal message, but the other bug is still there.
I usually close emesene2 with right click on the tray icon>quit, but I've tried it again using file>quit (although i guess they are the same thing). The redraw option isn't on the options tab that lets me chose the directory for file transfers, but here's some new info: setting a folder like /home/xxx/Desktop works fine and it gets saved, but using a path containing a .hidden folder doesn't, and the old path gets set back the next time i start emesene2 again

**Comment by Sbte** [comment]
It works fine here. I set it to /home/sven/.config/emesene2/messenger.hotmail.com/xxx@live.com/transfers. I really don't see what's going wrong for you...

**Comment by Soulsuke** [comment]
Did you try to restart emesene2 and see if the setting has been actually saved or if it's been reverted to the one it was set to before you've changed it?

**Comment by Sbte** [comment]
Yes. Multiple times. I also set it to different folders and to any of the parent folders of this transfer folder. I didn't fail to save it once. Maybe it's your version of emesene? Which one do you use?

**Comment by Soulsuke** [comment]
Latest git, and I'm still having this issue... I really dunno what is causing this problem, then

**Comment by Sbte** [comment]
Maybe it's a weird character somewhere? Could you try setting it folder by folder? So first /home/xxx, then /home/xxx/.config, then /home/xxx/.config/emesene2, and so on...

**Comment by Soulsuke** [comment]
i tried with just .config and it hasn't been saved, no illegal characters in the user name, just lowercase letters..

**Comment by Sbte** [comment]
What distro do you use? Maybe it's a distro bug, or a bug in your python version, or whatever... :P

**Comment by Soulsuke** [comment]
Guess that'd be a valid explanation for that problem, if no one else is experiencing it
I'm on Debian Sid amd66 by the way

**Comment by Soulsuke** [comment]
Looks like I have some new information: if I add the directory clicking (ctrl-h to show hidden folders, then clicking) it gets saved, but if i write it down the path (using autocomplete, of course) it doesn't. Could you try that as well please?

**Comment by c10ud** [comment]
that would be a gtk-dialog issue or nonfeature, i guess

**Comment by Sbte** [comment]
Actually, the issue seems to be that it doesn't work for any folder you type out. Also non-hidden folders. Can you confirm this?

**Comment by Soulsuke** [comment]
Yes, it doesn't seem to work for any folder typed in

**Comment by Sbte** [comment]
That makes things more logical. Thanks!
