### ISSUE TITLE
Problems with file transfers

### ISSUE THREAD

**Issue by MauricioGlz** [emesene/emesene#677]
The bug is that I cant send or recive any kind of data by the Window of the contact, it appears the button for recive, but this dosnt respond.
In the reminal it dosent show an error, so if you want that show the promp just tell me.

I'm Using emesene 2.11.5 on Ubuntu 11.04 
my email is mauricioandres288@gmail.com

**Comment by Mystro256** [comment]
You could try running emesene -vvv and see if an error comes up

**Comment by zadoryzsolt** [comment]
I had the same problem. Strangely when I disabled logger it started to work.

**Comment by zipatei** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 132, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1363, in _handle_action_ft_cancel
    self.rfiletransfers[t].cancel()
KeyError: <e3.base.Transfer.FileTransfer object at 0xa9db72c>

**Comment by pepeleproso** [comment]
Could you retry with current git?
@zipatei your problem is bug #702

**Comment by zadoryzsolt** [comment]
After further testing with current version, it seems that only the first file arrives for certain after a clean start. Best case I got 3 files received.

I've got these lines during transfers:
/usr/share/emesene2/gui/gtkui/FileTransferWidget.py:69: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)
[14:25:04 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

**Comment by pepeleproso** [comment]
@belaba are you using emesene 2.11.5? or current git?

**Comment by zadoryzsolt** [comment]
I used git version from arch's aur repo. It was freshly installed after you asked for it.

**Comment by Sbte** [comment]
There's no current git version in AUR. Here are some instructions on how to get it:

http://blog.emesene.org/2010/10/instructions-for-testers.html

**Comment by zadoryzsolt** [comment]
Not on the website, but with using yaourt (package manager for aur) it automatically downloads the latest files from git. It's more convenient for me but I can do it the other way.

**Comment by Sbte** [comment]
Ok, sorry. I'm not really into Arch ;)

**Comment by c10ud** [comment]
the whole cid stuff should have fixed this, try with 2.11.7
