### ISSUE TITLE
API Documentation lacking

### ISSUE THREAD

**Issue by shuhaowu** [emesene/emesene#678]
Emesene is currently lacking documentations of its API that's accessible with plugins. This severely limits developers to only develop very simple plugins.

**Comment by c10ud** [comment]
@marianoguerra still have the docgen thing?

**Comment by marianoguerra** [comment]
On Mon, Jun 27, 2011 at 11:59 PM, c10ud
reply@reply.github.com
wrote:

> @marianoguerra still have the docgen thing?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/678#issuecomment-1451098

it's here:

https://github.com/emesene/emesene/tree/master/docs

just install sphinx and run make html

it was on emesene.org/docs but the DNS magic that we did for blogger
made it unaccesible, maybe we can put it on

emesene.github.com?

aka github pages

**Comment by shuhaowu** [comment]
That would be a good idea.

**Comment by shuhaowu** [comment]
Oops, accidentally clicked close.

**Comment by Mystro256** [comment]
It should probably be documented on the wiki and linked to the plugin wiki (https://github.com/emesene/emesene/wiki/Plugin-How-To)

**Comment by c10ud** [comment]
oh, github pages, cool stuff! i'll dig into it if noone does and see
what can be done

2011/6/28 Mystro256
reply@reply.github.com:

**Comment by marianoguerra** [comment]
On Tue, Jun 28, 2011 at 9:23 AM, c10ud
reply@reply.github.com
wrote:

> oh, github pages, cool stuff! i'll dig into it if noone does and see
> what can be done

ok, here is until you make the github page:
http://marianoguerra.com.ar/emesene/docs/

**Comment by marianoguerra** [comment]
api documentation generated with doxygen from the source code: http://marianoguerra.com.ar/emesene/api/

**Comment by c10ud** [comment]
http://emesene.github.com/emesene-docs/

**Comment by Mystro256** [comment]
Also I added it to the wiki and plugin how to

**Comment by shuhaowu** [comment]
Still got some issues. For example:  I still don't know what session is for the start method.

**Comment by shuhaowu** [comment]
Or a list of signals.. etc. Even though I could find them in the API docs, there are still things that's not documented, especially since everything in python is duct typing and dynamic, it's especially hard to keep track of type, member variables etc.

Makes it difficult to even start a plugin without a lot of work digging into emesene's source first.

**Comment by marianoguerra** [comment]
On Sat, Jul 2, 2011 at 10:54 PM, ultimatebuster
reply@reply.github.com
wrote:

> Or a list of signals.. etc. Even though I could find them in the API docs, there are still things that's not documented, especially since everything in python is duct typing and dynamic, it's especially hard to keep track of type, member variables etc.
> 
> Makes it difficult to even start a plugin without a lot of work digging into emesene's source first.

do you know what kind of plugin you want to do?

you don't need all the source documented to do a simple plugin, just
ask "how do I..." on the mailing list and we will provide answers

**Comment by shuhaowu** [comment]
Yeah. Last said plugin. Remember what someone last said and display it when
I open up a conversation with them.
On 2011-07-02 6:08 PM, "marianoguerra" <
reply@reply.github.com>
wrote:

**Comment by Mystro256** [comment]
There is also this if it helps (the mainpage is blank but the other pages have some good info): http://marianoguerra.com.ar/emesene/api/
