### ISSUE TITLE
Another update to the download page

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#679]
Emesene 2.11.4 is now included in natty-updates:

http://packages.ubuntu.com/natty-updates/emesene

I just noticed it earlier today

**Comment by marianoguerra** [comment]
check the page, is it ok?

**Comment by Mystro256** [comment]
Yep, that should be good :)

Although, if you want to post the package website as well, like the what was done other distributions, the link is here: http://packages.ubuntu.com/natty-updates/emesene

**Comment by marianoguerra** [comment]
On Sat, Jun 25, 2011 at 8:33 PM, Mystro256
reply@reply.github.com
wrote:

> Yep, that should be good :)
> 
> Although, if you want to post the package website as well, like the what was done other distributions, the link is here: http://packages.ubuntu.com/natty-updates/emesene

done

thanks!

**Comment by Mystro256** [comment]
Looks good, thanks.
