### ISSUE TITLE
Invite a friend dialog, shows display names as "%DISPLAY NAME%"...

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#68]
the invite a friend dialog shows no specific information about the contact other than there display image (if they have one)

there display name is marked as "%DISPLAY NAME%"
and there personal message is marked as "< span foreground= "#AAAAAA" size="small" > "

**Comment by c10ud** [comment]
as soon as we sort out issue #8, this will be gone :P

**Comment by arielj** [comment]
The problem was that emesene2 used "%display_name%" tags and now it uses [$display_name] tags, it's fixed on my fork :D

**Comment by c10ud** [comment]
pulled

**Comment by SWOriginal** [comment]
ok' that was fixed quick! :D
