### ISSUE TITLE
Plugin doesn't woks

### ISSUE THREAD

**Issue by magaro** [emesene/emesene#680]
Hi people.

I have emesene 2.11.4 installed on ubuntu 11.04,  How can add plugins like 'listen now', 'custom status', 'antiboss' etc....I downloaded the songretriever.py, CustomStatus.py, Handler_banshee.py, and others, I put those on usr/share/emesene/emesene/plugins, now they appears on complements but they don't work, i can't select any of them, the preferences boton and run boton don't work.

Is theres some missconfiguration? How can I fix it?

**Comment by Mystro256** [comment]
Did you click on one and hit execute? Also you may also have to redraw the screen after activating a plugin (under the extension tab) or restart emesene.

@ whomever can answer
On a side note, would it seem like a good idea to redraw the screen when a plugin is activated? Or does doing so cause issue?

**Comment by Sbte** [comment]
Well, in my opinion the whole plugin window should redone and integrated with Andrea's plugin fetcher

**Comment by ghost** [comment]
I think those are emesene1 plugins, and if they are they wont work with emesene2.

**Comment by Mystro256** [comment]
Are you using the plugins from here: https://github.com/emesene/emesene-supported-plugins ?

**Comment by magaro** [comment]
Hi people, thanks a lot for your reply :)

Mystro256:  
Did you click on one and hit execute?:  Yes but it does anything and after any changes, I click on 'preferences', execute, stop, but these butons don't work.....I restarted emesene but it is still the same.

Are you using the plugins from here.......: yes, i've downloaded from https://github.com/emesene/emesene-supported-plugins

Sbte:  I can't following you, what means "...integrated with Andrea's plugin fetcher"?

syst3mfailur3:  those are from emesene 2 .

Again thanks a lot, emesene is my prefered messenger client and i want to keep continue using it.

**Comment by Mystro256** [comment]
@magaro

Is the check marks even working noting they have been executed? Some plugins, if not all, don't seem to work properly until you redraw the screen or restart emesene with them executed. Also Andrea made a plugin downloader and Sbte was just noting he thinks it should be integrated, which I personally have yet to test, but none the less sounds like a very good idea.

**Comment by magaro** [comment]
I think you can write in spanish jajaja, if yes, I apreciate that.

The check doesn't works, when i click on the box of any of the plugins, nothing happens, there is no flag in the box, try to select one of them then click on the 'ejecutar' but nothing happens :(.... how can I run any of them?.

I uninstalled emesene, erase all the folders, installed again, extract plugins in the 'plugins' folder but nothing happens.

The redraw item is in the extensions menu, but what is it for? is not clear for me even the extensions menu.

**Comment by magaro** [comment]
On debug window i have:

11:48:25) pluginmanager:starting plugin "songretriever"
(11:48:25) pluginmanager:error creating instance for "songretriever": 'NoneType' object has no attribute 'Plugin'
(11:48:25) pluginmanager:starting plugin "handler_banshee"
(11:48:25) pluginmanager:error creating instance for "handler_banshee": 'NoneType' object has no attribute 'Plugin'
(11:48:25) pluginmanager:starting plugin "handler_rhythmbox"
(11:48:25) pluginmanager:error creating instance for "handler_rhythmbox": 'NoneType' object has no attribute 'Plugin'
(11:48:25) pluginmanager:starting plugin "DBusBase"
(11:48:25) pluginmanager:error creating instance for "DBusBase": 'NoneType' object has no attribute 'Plugin'
(11:48:25) extension:extension id None not registered on option provider

**Comment by Sbte** [comment]
The checkbox isn't supposed to do anything IIRC. You need to use the Execute button. 

I'll try to merge the Execute and Stop buttons into the checkbox if possible some day...

**Comment by Mystro256** [comment]
I don't think he understands because the button doesn't say execute in spanish... what is execute in spanish? executar perhaps? Eitherway, @magaro, you have it hit the button to enable it.

**Comment by magaro** [comment]
Yes, i think so, anyway, i hit the button but there is nothing happening.

Sorry about all of this but i will made a downgrade to emesene 1, is more easy to set up than the new one, the extensions menu is so smart for me hahahaha, i don't know what is them for.

Thanks to all of you for your help, im not a developer, just a final user, I like to custom my ubuntu but this time i think I go back 

 :).....stay free!!!

**Comment by pepeleproso** [comment]
@sbte I made a patch to allow activate/desactivate plugins clicking the checkbutton, it's in my tree.

**Comment by Sbte** [comment]
Awesome :D

**Comment by Mystro256** [comment]
This should probably be closed because of the posters lack of interest and the lack details to reproduce this... is this even a bug or just a communication issue?

**Comment by Sbte** [comment]
pepe, are you going to push those changes?

**Comment by pepeleproso** [comment]
I don't have access to my pc now. Tomorow i'll push them

**Comment by pepeleproso** [comment]
Done

**Comment by c10ud** [comment]
incomplete
