### ISSUE TITLE
Can't cancel autologin

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#69]
If I set an account to autologin, I can cancel that, the login screen starts again and the autologin is triggered so it starts to login again.

I have to manually edit the config file and change the b_remembers value to something different to 3.

---

maybe related, when I start emesene, a warning about trying to add a widget to the main window with a widget already added appears (line 54 of Window.py)

**Comment by c10ud** [comment]
seems like rewriting the login alignments i borked this, problem is i can't find out what's going on and my head is spinning lol

i'll see if i can do something tomorrow :s

**Comment by arielj** [comment]
I think that the Login is being created again and then the **init** method calls the "check_autologin" method and starts logging in again.

We can try setting the b_remembers config of the current account to 2 instead of 3 before going back to the login window. Or use a new parameter and do "if do_autologin: check_autologin()".

EDIT: also, "connect now" button is insensitive on reconnection, making it useless :P

**Comment by c10ud** [comment]
maybe connect now is now ok, as for the other, i can't find the correct callback when clicking cancel :s (if the signal is correctly fired)

**Comment by c10ud** [comment]
Closed by 8282d24e34a2d4c402e31d828468f270ad814ad3
