### ISSUE TITLE
Tray Icon Not showing up

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#691]
There seems to be an issue with the Tray Icon not showing up (when tray icon extension is set to tray icon)
When I connect, the icon doesn't appear but appears after I redraw the screen. The screen has to be redraw every time I connect. I did notice the tray icon setting reverts to messaging menu every time I switch between 2.11.5 and 2.11.6 dev.

Also I have tried purging my config before opening 2.11.6 to avoid conflict with 2.11.5 (for whatever reason)

This seems to be a recession in 2.11.6 dev, because it doesn't exist in 2.11.5 stable.

**Comment by c10ud** [comment]
@sbte

2011/6/28 Mystro256
reply@reply.github.com:

**Comment by Sbte** [comment]
Could you do a git bisect? I have no clue why it's happening, because connecting and redrawing the main screen use the same method.

**Comment by Mystro256** [comment]
hmmm, odd... I'll have to do a bisect when I have time a little later.

**Comment by Mystro256** [comment]
Found it, it's caused by f8922e2

Edit: I added a note for the line in particular that gave me issue. I'm not sure what the line does, so I'm hesitant to pull my commit: https://github.com/Mystro256/emesene/commit/54d42c728fbaec1910daf3b208b81c1d0c52d876

**Comment by pepeleproso** [comment]
you can readd it, with no issues thought, I just move it into _setup_plugins method

**Comment by Mystro256** [comment]
Okay, I'll make a pull request, assuming my commit is all right, see #698

**Comment by zipatei** [comment]
Here not fixed.

**Comment by zipatei** [comment]
fixed
