### ISSUE TITLE
Media Message is not shown

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#692]
Showing the media messages (listening to messages) of your contacts has yet to be implemented in emesene, ie show what your contacts are listening to instead or along with personal messages.

Probably not of high importance but should be implemented.

**Comment by c10ud** [comment]
ah - interesting - we probably must fix this in papylib?

**Comment by Mystro256** [comment]
Well I figured it wasn't even implemented, though to be honest, I haven't looked into it. Doesn't papyon even support it yet?

To clarify what I was trying to say: using emesene, I send out and let people what I'm listening to, but I can't see what others are listening to.

I would take a shot at it, but I'm shooting blind with the papyon stuff.

I figure you could just replace the [$MESSAGE] with the media message instead of the personal message while someone has a media message available. I guess it can also be added to the view information window

**Comment by c10ud** [comment]
yes, exactly -- and i don't think it's necessary to add to the view information window

wanna take the job? :D

**Comment by Mystro256** [comment]
Lol I want to but how do I grab the info from papy?

**Comment by c10ud** [comment]
```
def _on_contact_media_changed(self, papycontact):
```

in papylib/Worker.py

seems like an event is fired but nothing handles it in the gui code!

**Comment by c10ud** [comment]
also, seems like that method has a wrong logic

**Comment by Mystro256** [comment]
hmmm ic, I guess I'll try playing with it. Also, what do you mean by "wrong logic"?

**Comment by c10ud** [comment]
correct method should be:

```
def _on_contact_media_changed(self, papycontact):
    contact = self.session.contacts.contacts.get(papycontact.account, None)
    if not contact:
        return
    account = contact.account
    old_media = contact.media
    contact.media = papycontact.current_media

    if old_media == contact.media:
        return

    self.session.contact_attr_changed(account, 'media', old_media)
    # TODO: log the media change?
```

**Comment by Mystro256** [comment]
You beat me to it I guess ;)

**Comment by c10ud** [comment]
you bet! :D

2011/8/11 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
haha I was just about to push it to my git ;)
