### ISSUE TITLE
Problem with another login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#694]
Reproduce:
1) login in emesene
2) disconnect emesene
3) login with another account

Emesene connect with same first login.

**Comment by ghost** [comment]
Just tried it and its happening to me to.

**Comment by ghost** [comment]
This happens to me too :(

**Comment by Sbte** [comment]
Debugging this right now. It's still right at emesene.py 604

**Comment by Sbte** [comment]
Wtf, self.session.account.account is also the right one...

**Comment by Sbte** [comment]
Ok, it's a regression. Makes things easier...

**Comment by Sbte** [comment]
1e0e7f3cb4c6d397fe88228ca487c28bffcf5f9e is the first bad commit
commit 1e0e7f3cb4c6d397fe88228ca487c28bffcf5f9e
Author: ariel arieljuod@gmail.com
Date:   Sun Jun 12 23:23:32 2011 -0300

```
Make gtkui's MainWindow a single instance extension.
```

:040000 040000 06b5c1bd95a4e23399d16329dcc24f7f408967c9 e6e3d2516c88324b56b1657d489dc94992156d3e M  emesene

**Comment by Sbte** [comment]
@arielj please fix or revert this commit. Thanks!

**Comment by arielj** [comment]
Reverted!
