### ISSUE TITLE
Status tray-icon not the same emesene

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#695]
Reproduce:

1) Change status in tray icon.. 

http://imageshack.us/photo/my-images/535/capturaecra14.png/

**Comment by Sbte** [comment]
That should already be fixed in git. Maybe it's a leftover on your system of an old version?

**Comment by arielj** [comment]
I can not confirm this, I'm using latest git and when I change the status from the tray icon or the main window, both icons are the same.

Any update on this, @zipatei ?

**Comment by Mystro256** [comment]
I cannot confirm this either; I tested with both gnome 2 and gnome 3 (shell). Although I do come up with this error in the terminal when I change status:

```
[15:26:41 WARNING papyon.p2p] Trying to publish an empty MSNObject
```

**Comment by zipatei** [comment]
I don't know, because tray icon not appear now...

**Comment by Sbte** [comment]
Preferences -> Extensions -> tray icon

**Comment by Mystro256** [comment]
Something in 2.11.6 causes the setting to revert, but it only happens when you switch from the old to the new, not continuously.

**Comment by Sbte** [comment]
I didn't have any issues with it...

:S

Hopefully it was a temporary issue then.

**Comment by zipatei** [comment]
Yes... i dit it (Preferences -> Extensions -> tray icon) but not work

**Comment by Sbte** [comment]
Did you also try to change it to indicator?

**Comment by zipatei** [comment]
yes.. it same thing

**Comment by Sbte** [comment]
It was broken for some time. Are you using latest git?

**Comment by zipatei** [comment]
I do a clean install .. wait a minute

**Comment by zipatei** [comment]
sorry... fixed
