### ISSUE TITLE
URLs made the parser go crazy,

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#70]
Hi!
I get this error, and the conversation window don't render, with some Nicks:

http://www.pasteall.org/14566

**Comment by arielj** [comment]
I've already made a commit for this, wait for C10ud to merge my changes here or pull from by repo ;)

EDIT: I don't know if we can set something like a clickable link using pango markup, for now I've only set a blue and underlined look to it :P

**Comment by c10ud** [comment]
pulled kthxbi

**Comment by EibrielInv** [comment]
Thanks!, works now.
