### ISSUE TITLE
Notifications take too long to desapear.

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#71]
In a long conversation the new notifications on Ubuntu take too much time to go... even a lot of minutes...
I'm prety sure you know this issue, but...

Why the messages do not concatenate like old Emsene? Fills the screen?
I know there are some problems or limitations to make to apear more than one Notification at once. Still exist on new Ubuntu?

**Comment by arielj** [comment]
they don't concatenate because it's not implemented yet on PyNoticiations, it's implemented on the GtkNotifications

I think that the limitation of only one notification at a time is a limitation of pynotify.

**Comment by marianoguerra** [comment]
this is default behaviour of the library, I don't think we can do much about it.

**Comment by arielj** [comment]
there should be some n.set_timeout(pynotify.EXPIRES_NEVER) for the notifications

check this http://ubuntuforums.org/showthread.php?t=447613

Emesene1 should be helpfull to fix this issues, it concatenates messages and there's no problem with the timeout
