### ISSUE TITLE
Timestamp in logs

### ISSUE THREAD

**Issue by hit** [emesene/emesene#711]
Timestamp is wrong. Although it says "EET" (should be even "EEST [Eastern European Summer Time]") there, it's still UTC, which is 3 hrs behind from local time.

Ex:
  Log - Mon 04 July 2011 17:15:13 EET
  IRL - Mon 04 July 2011 20:15:13 EEST

**Comment by Sbte** [comment]
I think I fixed this a while ago, it still works for me, and the format even adjusts itself to your locale. Are you sure you're using a recent version of emesene 2.11.5+?

**Comment by hit** [comment]
I've never used a non-svn/git emesene.. and yes, it's still there. Chat logs are ok, but everything else (status, pm, nick) is incorrect.

**Comment by Sbte** [comment]
Ah, I thought you were talking about chat logs
