### ISSUE TITLE
No way to "steal" custom emoticons

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#715]
In emesene 1 I used to right click a custom emoticon I received in a chat and then add it to my account.
Now that option vanished... Any plan to readd it? (:

**Comment by pepeleproso** [comment]
duplicate of #709

**Comment by Mystro256** [comment]
As pepe said, this a duplicate of #709 and should be closed.

Although I would like to note that the issue isn't that it wasn't added in emesene 2, but rather it "disappeared" due to regression and will be fixed as soon as the source of the regression is found.

**Comment by igorsantos07** [comment]
Thank you both for your quick anwer (:
