### ISSUE TITLE
File transfer bar doesn't disappear when empty

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#717]
I've sent a file to a contact, and after finishing the transfer, I clicked the clear button.
The file disappeared from the lower bar, but the bar is still there, empty, with only the two arrows in the left and right corners.

**Comment by pepeleproso** [comment]
are you using emesene 2.11.5?
i think this is fixed in git master

**Comment by igorsantos07** [comment]
Yes I am, installed via package manager.

**Comment by ghost** [comment]
Its been fixed in the current git (2.11.6-devel) I believe.

**Comment by pepeleproso** [comment]
yes, I make some fixes to file tranfers last week. use git version or wait for emesene 2.11.6

**Comment by igorsantos07** [comment]
Ok, thank you pepe (:
