### ISSUE TITLE
Problem with status icon -

### ISSUE THREAD

**Issue by marcosviv** [emesene/emesene#718]
Hi, this is a problem I created ... I accidentaly "removed from the upper panel" the Emesene 2 status logo, so now I only have a small red circle, like the ones in "Don't smoke". I tried reinstalling the program ... didn't work ... 
Help!!!

**Comment by Sbte** [comment]
Eh, what? Where did you remove what logo from? A screenshot would be nice, because I'm not really sure what you removed and how you were able to remove it.

**Comment by marcosviv** [comment]
Allright, yes, you're right. Here's a screenshot: http://img834.imageshack.us/i/screenshotazl.png/ 
This is Ubuntu 10.10. You can see in the upper panel that where the Emesene status icon should be, right next to the NetworkManager WIFI signal, you can only see a "banned" icon, because I accidentally right clicked it and "deleted from panel". Now I don't know how to put it back.
And I can't right click on it to get some options displayed, as I could when the icon was there :S (I can left-clik to get the Emesene options)

**Comment by Mystro256** [comment]
This isn't an emesene issue; I believe you just removed either indicator applet. You can add it back by right clicking the panel, click add to panel, then add the indicator applet.

**Comment by marcosviv** [comment]
Ha, man, you did it ... I just added the indicator applet and wala!!! solved 
Thanks!!!
