### ISSUE TITLE
emesene2 search for /usr/lib64/python.../emesene2/config instead local one

### ISSUE THREAD

**Issue by Otamay** [emesene/emesene#719]
emesene2 searchs for /usr/lib64/python2.7/site-packages/emesene/emesene2/config instead local one in ~ (home directory). This is because python sys.platform returns linux2 for kernels <3.0 and linux3 for linux>=3.0, and the function in emesene does not work with 3.0 kernels . Changing a conditional in e3/common/ConfigDir.py  resolves the issue:

--- ConfigDir.py    2011-07-10 02:15:02.977000010 -0500
+++ ConfigDir.py2   2011-07-10 02:15:21.926000010 -0500
@@ -60,7 +60,7 @@

```
 def _get_default_base_dir(self):
     '''return the default base dir for configuration according to the OS'''
```
-        if sys.platform == 'linux2':
-        if sys.platform == 'linux2' or sys.platform=='linux3':
           return os.path.expanduser(os.path.join('~', '.config',
               self.app_name))
       elif sys.platform == 'win32':

(diff doesn't shows properly, well.. is only changing "if sys.platform == 'linux2':" with " if sys.platform == 'linux2' or sys.platform=='linux3':"

Saludos!

**Comment by Sbte** [comment]
One more place:

emesene/e3/common/ConfigDir.py:        if sys.platform == 'linux2':
emesene/gui/gtkui/TrayIcon.py:        if os.name == 'mac' or sys.platform == 'linux2':

**Comment by ghost** [comment]
https://github.com/emesene/emesene/pull/721 should fix this
