### ISSUE TITLE
REQUEST: enable the use of larger toolbar *if* toolbar theme is present

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#72]
could someone _Please_ do some much appreciated coding and enable the toolbar icons to be 32px, but only if toolbar folder is present in theme. 

you may think there's no point in wasting time but its needed when using detailed icons :D

i will push the toolbar theme to one of the themes when there completed to an extent if you wish to experiment with the toolbar size, but i think minimum of 32px when toolbar theme is included would be best :D

**Comment by c10ud** [comment]
will try to do it asap

**Comment by SWOriginal** [comment]
WOO! thanks :)

**Comment by c10ud** [comment]
i tried but-- don't you think 32x32 is just too big? :O

**Comment by SWOriginal** [comment]
if you have done it could you send me the source so i could see what it looks like.

i do think 32 is large but compared to most other im clients its relatively small.
if you feel like it should remain the same i have no problem,

i weren't planning on adding a toolbar theme by default as the icons would be inconsistent with many users gtk themes it was really just for designers to be able to create icons without compromising detail :D

**Comment by c10ud** [comment]
in emesene/gui/gtkui/ConversationToolbar.py
search:
        whsize = gtk.icon_size_lookup(size)
and substitute with:
        whsize = (32, 32)

**Comment by SWOriginal** [comment]
i agree with you it does look to large when using default icons, if the toolbar was on top and the tabs where at the bottom it wouldnt look so bad :P, its best if we just leave the size as they are :)

**Comment by c10ud** [comment]
ok :)
