### ISSUE TITLE
Links do not open in OS X

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#723]
Links received in conversation, aswell as the links in the extension selector do not open on OS X. Strangely the link on the about dialog does work.

> /Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/**init**.py:114: GtkWarning: Unable to show
> 'http://www.youtube.com/watch?v=oBIxScJ5rlY&feature=related': Operation not supported
> gtk.main()

This works (used for link on about dialog):

import webbrowser

THESITE= "http://www.youtube.com/watch?v=oBIxScJ5rlY&feature=related"
webbrowser.open(THESITE)

Don't know where to change in the code though

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/blob/7b878b72e9b39c34cd7e7a74732d2075bf97fc35/emesene/gui/gtkui/AdiumTextBox.py#L178

Go fix it tiger ;)

**Comment by ghost** [comment]
Where is it for the non adium output?

**Comment by Sbte** [comment]
It's done by pango. 

```
#!/usr/bin/env python

import gtk

window = gtk.Window()
label2 = gtk.Label()
label2.set_markup('<a href="http://www.google.com">google.com</a>')
window.add(label2)
window.set_default_size(100, 50)
window.show_all()
gtk.main()
```

should create a working link.

**Comment by ghost** [comment]
It doesnt, same error. The links show, but when you click them nothing happens.

**Comment by Sbte** [comment]
Here you go:

```
#!/usr/bin/env python

import gtk
import webbrowser

def on_activate_link(label, uri):
    webbrowser.open_new_tab(uri)
    return True

window = gtk.Window()
label2 = gtk.Label()
label2.connect('activate-link', on_activate_link)
label2.set_markup('<a href="http://www.google.com">google.com</a>')
window.add(label2)
window.set_default_size(100, 50)
window.show_all()
gtk.main()
```

**Comment by ghost** [comment]
Yeah that works, where would i have to add the code in emesene though?

**Comment by Sbte** [comment]
Here:

https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/RichBuffer.py#L92

I can also do it if you want, now I know it works for you.

**Comment by ghost** [comment]
Yeah if you could it would be great, got quite a lot of other stuff to do atm :)

**Comment by Sbte** [comment]
I got the patch, but can't seem to push to github...

**Comment by ghost** [comment]
```
    def put_link(self, link):
        '''insert a link at the current position'''

        def on_activate_link(label, uri):
            webbrowser.open_new_tab(uri)
            return True

        lnk = gtk.Label()
        lnk.connect('activate-link', on_activate_link)
        lnk.set_markup(MarkupParser.urlify(MarkupParser.escape(link)))
        lnk.show()
        self.put_widget(lnk)
```

Is that right? if so i will push :)

**Comment by Sbte** [comment]
Yes, that should do it

**Comment by ghost** [comment]
Done. https://github.com/joshf/emesene/commit/895e34006a4be54d6768e96b4b82e4a28600d1b3

Will send a pull request too.

**Comment by Sbte** [comment]
Hmm, it worked now, but I have to fill in my passphrase every time. Weird stuff...
