### ISSUE TITLE
New Chat Windows opening with same contact

### ISSUE THREAD

**Issue by mahvin** [emesene/emesene#724]
During every chat session (using Ubuntu 11.04 Natty 64 bit and emesene 2.11.5) additional chat windows will open during the conversation, containing the same text, sometimes up to 5 windows per session. Windows Live is not open, nor is there more than one chat program open.

**Comment by Sbte** [comment]
In the top right of your screen, there is a white envelope. That's the MessagingMenu. Every time you open a new instance of emesene, it goes there. Once you 'close' emesene, it hides in the MessagingMenu. What you did, is open a new instance of emesene every time you hid it. So then you got a chat window from every instance you had open.

**Comment by mahvin** [comment]
Thank you for pointing that out. I did try to find the reason for this
occurring, to no avail.
