### ISSUE TITLE
Updates to download page

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#729]
Just another change needed to be done on the download page:

Emesene 2.11.5 is now in the community repo for Arch: http://www.archlinux.org/packages/?sort=&q=emesene&maintainer=&last_update=&flagged=&limit=50

As for the version in the AUR, it is not suggested to use and probably should be removed from the download page.

Also, if it would be better to post these updates somewhere else, please let me know :)

**Comment by Mystro256** [comment]
The AUR package also causes messages to be send either multiple times or sometimes not at all.

**Comment by c10ud** [comment]
done, we really should move the download page to sort of a wiki...mmmm

**Comment by Sbte** [comment]
What you could do is moving to github pages and using it also as a blog using Yekyll, see 

http://tom.preston-werner.com/
https://github.com/mojombo/mojombo.github.com
https://github.com/mojombo/jekyll/

it'd allow anyone who's an emesene organization member here on github to post and Mystro can make pull requests every time he wants to change something ;)

And it'd allow me to finally make a FAQ.

**Comment by c10ud** [comment]
raise to ML, and we'll see

2011/7/15 Sbte reply@reply.github.com:
