### ISSUE TITLE
Adding Contact issue

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#73]
When another person adds me to their contact list and I hit add, it adds the contact to my list but continues to ask me to add or ignore the request despite I already have added the contact. Furthermore, if I hit add again, it errors and says the contact is already on your contact list.

I usually have to sign on with Amsn (or whatever) and hit the add contact button to stop it from coming up in emesene

**Comment by c10ud** [comment]
afaik there's no window yet in emesene2

**Comment by Mystro256** [comment]
Its a problem with Uberlândia, I assumed there code were related or based off the same idea

**Comment by c10ud** [comment]
sorry sir, it's not :)

**Comment by Mystro256** [comment]
haha sorry, dont mind me then :P
