### ISSUE TITLE
Message sending issue without PyGStreamer

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#730]
I noticed when I tried to install emesene on Arch via the community repo and the AUR, the message box in the conversation window doesn't clear after sending a message. In other words, the message is sent but it never erases it from the text box. It seemed to be fixed when I installed the gstreamer python bindings.

If I were to make a guess, I would assume emesene is using gstreamer to play sounds (although I have no idea if it does or not) and the script that sends-message/plays-sound/erase-string-from-text-box would keep crashing at the sound part before erasing the message.

I've only tested and confirmed this in Arch, but the arch packages don't seem to be missing any dependencies, so it doesn't look like an issue with Arch. Also, gstreamer, less the python bindings, was installed prior to installing emesene.

**Comment by Sbte** [comment]
Is the no command line output?

**Comment by Mystro256** [comment]
Oh yeah, I forgot about that :P

Here:

```
Traceback (most recent call last):
  File "/usr/share/emesene/gui/gtkui/TextBox.py", line 203, in _on_message_send
    self.on_send_message(self.text)
  File "/usr/share/emesene/gui/base/Conversation.py", line 272, in _on_send_message
    self.play_send()
  File "/usr/share/emesene/gui/base/Conversation.py", line 456, in play_send
    self.soundPlayer.play(gui.theme.sound_send)
  File "/usr/share/emesene/e3/common/Sounds.py", line 83, in play
    self._play(path)
AttributeError: 'SoundPlayer' object has no attribute '_play'
```

**Comment by Sbte** [comment]
Could you try adding

```
            else:
                self._play = self.dummy_play
```

after this line

https://github.com/emesene/emesene/blob/master/emesene/e3/common/Sounds.py#L76

The other else case doesn't catch this.

**Comment by Sbte** [comment]
I just pushed it since you didn't reply. Shouldn't crash now.

**Comment by Mystro256** [comment]
Oh sorry about that, I didn't mean to leave you hanging, I've been out of town for the last 10 days. :P

And yep it doesn't crash now,
Thanks for the help :)

**Comment by Sbte** [comment]
No worries. I just didn't want any crashes in the upcoming release if possible :P
