### ISSUE TITLE
Pango Warning

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#731]
This error is thrown every time a message is sent:

> /Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/**init**.py:114: PangoWarning: couldn't load font
> "'Rockwell Extra Bold' 12", falling back to "Sans 12", expect ugly output.
> gtk.main()

This happens for every font btw.

Notice the extra ' ' marks, i think thats whats causing the issue as it cannot find the font with the extra quotes in the name. If you point us to where the font is loaded from, i will fix it myself.

**Comment by c10ud** [comment]
adium output or simple text output?

**Comment by ghost** [comment]
Simple text output, i know that not the main focus of development, but its the only one that works on OS X

**Comment by c10ud** [comment]
should be:
emesene/gui/gtkui/TextBox.py

middle = e3.common.add_style_to_message(middle, message.style, False)
and
middle = e3.common.add_style_to_message(message.body, message.style)

then we go searching for add_style_to_message:
$ grep -ri "add_style_to_message" *
[..]
emesene/e3/common/utils.py:def add_style_to_message(text, stl, escape=True):

and in that file:

```
if stl.font:
    style += "font-family: '%s'; " % (stl.font, )
```

have fun :D

2011/7/15 joshf
reply@reply.github.com:

**Comment by ghost** [comment]
Fixed
https://github.com/joshf/emesene/commit/5100f79c0be9d1a95eb661353c5bbc30f919cbe1
