### ISSUE TITLE
Redrawing main screen causes memory leak

### ISSUE THREAD

**Issue by LexLythius** [emesene/emesene#733]
Hitting the "Redraw main screen" button in Preferences > Extensions consistently increases memory consumption by some 5 mb.
This memory does not seem to be ever reclaimed.

**Comment by Sbte** [comment]
So does opening a new conversation window, or opening a new session, or about anything you do. If you happen to know someone who's an expert at python memory usage, then please tell us, because I've spent quite a few days already on trying to debug this without being able to figure out why something in the main method keeps references to everything.

**Comment by marianoguerra** [comment]
On Fri, Jul 15, 2011 at 4:14 PM, LexLythius
reply@reply.github.com
wrote:

> Hitting the "Redraw main screen" button in Preferences > Extensions consistently increases memory consumption by some 5 mb.
> This memory does not seem to be ever reclaimed.

another good reason to stop using "redraw screen" as a way to update
the extensions.

PS: this is a comment to the devs :)

**Comment by Sbte** [comment]
Or a good reason to fix emesene not releasing ANY memory after an object gets out of scope...

**Comment by marianoguerra** [comment]
On Fri, Jul 15, 2011 at 4:21 PM, Sbte
reply@reply.github.com
wrote:

> Or a good reason to fix emesene not releasing ANY memory after an object gets out of scope...

that's a bigger task ;)

the memory leaks on emesene 1 all tended to be on objects holding
unnesessary reference to other objects

like some plugin holding a reference to a conversation when it could
take it from an event

we should start by removing unnecesary reference and using weakrefs
when it makes sense (mainly on stuff referencing temporary objects
like conversations)

**Comment by Sbte** [comment]
I tried that but couldn't get it to work. When I tried to use weakrefs, the object was seen as a weakref, not the object itself. Using the fancy WeakMethod class only seems to work only for functions, because it uses the **call** method. You still can't do something like object.method(), because then it complains that the object of type weakref doesn't have a function method().

If you have any clue on how to fix this, then we're done, because I manage to actually destroy and remove the windows everything is contained in (where the conversation manager is constructed, and the preference window/main window are made). If that's the only object holding the object, then of course all of the memory will be freed.

**Comment by marianoguerra** [comment]
On Fri, Jul 15, 2011 at 4:56 PM, Sbte
reply@reply.github.com
wrote:

> I tried that but couldn't get it to work. When I tried to use weakrefs, the object was seen as a weakref, not the object itself. Using the fancy WeakMethod class only seems to work only for functions, because it uses the **call** method. You still can't do something like object.method(), because then it complains that the object of type weakref doesn't have a function method().
> 
> If you have any clue on how to fix this, then we're done, because I manage to actually destroy and remove the windows everything is contained in (where the conversation manager is constructed, and the preference window/main window are made). If that's the only object holding the object, then of course all of the memory will be freed.
> 
> > > import weakref
> > > class IamAHappyObject(object):
> > > ...     pass
> > > ...
> > > o = IamAHappyObject()
> > > def deleted(*args):
> > > ...     print "object deleted", args
> > > ...
> > > r = weakref.ref(o, deleted)
> > > r()
> > > <**main**.IamAHappyObject object at 0xb77b9fac>
> > > del o
> > > r()
> > > <**main**.IamAHappyObject object at 0xb77b9fac>
> > > r
> > > object deleted (<weakref at 0xb77bacac; dead>,)
> > > <weakref at 0xb77bacac; dead>
> > > r()

docs here: http://docs.python.org/library/weakref.html

it takes some time since the del o until the object is garbage
collected but you get the idea

**Comment by LexLythius** [comment]
Forgot to add this in case it helps:
Ubuntu 10.04 LTS (lucid)
emesene 2.11.4 
Downloaded emesene and python-papyon from the Ubuntu/natty repository.

**Comment by LexLythius** [comment]
I know next to nothing about Python, but in Java these kind of object lifecycle problems can sometimes be solved by using weak references.
For what I can see, Python has a similar feature: http://docs.python.org/release/2.5.2/lib/module-weakref.html
I'm talking from a 10,000 meter view here, but anyway...

**Comment by Sbte** [comment]
Mariano, I know how weakrefs work, but we'd have to change the code everywhere to use reffedobject() instead of reffedobject. In the WeakMethod call, you implemented **call** to do thing for functions, but is there also a way to do this for objects, so we don't have to change all the code?

**Comment by Sbte** [comment]
Even if I do this, everything still works:

```
        ConversationManager = extension.get_default('conversation window')
        conv_manager = ConversationManager(session, self._on_last_tab_close)
        del ConversationManager
        self.content = weakref.ref(conv_manager)
        del conv_manager
        self.add(self.content())
```

I deleted the conv_manager, but for some reason it's still alive.

**Comment by Sbte** [comment]
And if I do this

```
ConversationManager = extension.get_default('conversation window')
        conv_manager = ConversationManager(session, self._on_last_tab_close)
        del ConversationManager
        self.content = weakref.ref(conv_manager)
        conv_manager.close_all()
        conv_manager.hide()
        conv_manager.destroy()
        del conv_manager
        self.add(self.content())
```

It finally stops working.

**Comment by Sbte** [comment]
If I implement this in the close mechanism however, it doesn't help to destroy the ConversationManager object

**Comment by Sbte** [comment]
Actually, as soon as self.connect('focus-in-event', self.content._on_focus) is called in Window.py, it won't get destroyed properly anymore. Is there a way to disconnect something?

**Comment by Sbte** [comment]
Ok, I got rid of that using WeakMethods, but even deleting the conv_manager after adding it to the window 

```
        conv_manager = ConversationManager(session, self._on_last_tab_close)
        self.content = weakref.ref(conv_manager)
        self.add(self.content())
        del conv_manager
```

doesn't destroy the object. Removing (self.remove)only helps if you do it within this function.

**Comment by c10ud** [comment]
2.11.7 addresses these issues, we cleanup lots of stuff now, but we're unable to go further, hence i close this issue
