### ISSUE TITLE
Sync Gtalk/Gmail avatar

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#734]
Is possible to have emesene to automatically retreive our avatar from google servers?

**Comment by astagi** [comment]
Well some time ago I asked the same question to @marianoguerra ... it's possible extending xmpp, alternatively we could use google api if they support something like getting an avatar given a contact... I'm very busy now and I didn't have time to have a deep look before, sorry, but I'll try as soon as I can ^^

**Comment by Fabioamd87** [comment]
Thanks!

**Comment by marianoguerra** [comment]
can someone try this example? (ports blocked here)

http://collincode.wordpress.com/2009/01/31/xmpp-jabber-photo-module-2/

**Comment by astagi** [comment]
It works...downloads a new a photo everytime I launch the script...is it normal??

**Comment by Sbte** [comment]
```
#request the photo only if we don't have it already
if not get_photo(photo):
    request_vcard(session, JID)
```

probably not?

**Comment by marianoguerra** [comment]
On Mon, Jul 18, 2011 at 12:07 PM, 4ndreaSt4gi
reply@reply.github.com
wrote:

> It works...downloads a new a photo everytime I launch the script...is it normal??

it;s just a demo, we should adapt it to e3/jabber but it's a good start :)

**Comment by astagi** [comment]
@marianoguerra yep that's great!! I'll start development during this week ^^ @Sbte sorry just launch the example, didn't have a look at the code yet ^^

**Comment by astagi** [comment]
Just integrated in emesene worker and....IT WORKS :D :D :D Soon the commit ^^ ^^ ^^ ^^

**Comment by marianoguerra** [comment]
On Mon, Jul 18, 2011 at 1:09 PM, 4ndreaSt4gi
reply@reply.github.com
wrote:

> Just integrated in emesene worker and....IT WORKS :D :D :D Soon the commit ^^ ^^ ^^ ^^

does it behave similar than the e3.papylib counterpart? in terms of
where it stores the files, the names, signals etc?

just ot make sure we don't get different behaviours depending on the protocol.

**Comment by astagi** [comment]
At the moment I store images in an external folder just to try, and yes I'm working on jabber worker to make it behaving like the papylib one ^^

**Comment by marianoguerra** [comment]
On Mon, Jul 18, 2011 at 1:19 PM, 4ndreaSt4gi
reply@reply.github.com
wrote:

> At the moment I store images in an external folder just to try, and yes I'm working on jabber worker to make it behaving like the papylib one ^^

greate!

when done, this deserves a blog post :)

**Comment by astagi** [comment]
^^ ^^ ok!!

**Comment by Fabioamd87** [comment]
WOW really FAST!

this means that gtalk, gmail, google+ and emesene avatar are syncronized?

**Comment by astagi** [comment]
Will be, and so Facebook ^^ I'll close the issue when I'm done.. stay tuned ^^

**Comment by Fabioamd87** [comment]
why Facebook? It's not Google related

**Comment by astagi** [comment]
because it runs on the same protocol of gtalk ... for Gmail will work on, for Google+ I was thinking about a plugin when apis will be released...

**Comment by Fabioamd87** [comment]
AH OK SORRY.
I was confused... you mean facebook account on emesene... I understand sync gtalk account of emesene with facebook image that didn't have sense.

PS: Gmail/gtalk itself didn't sync with Google+?

**Comment by Sbte** [comment]
I assume that they will merge it with the gmail avatar by then.

**Comment by Fabioamd87** [comment]
Ah ok, so for now that plugin isn't really important and in future if things goes like you said will no longer have sense :)

**Comment by astagi** [comment]
yes, but for the moment we have to wait ^^ ^^

**Comment by Fabioamd87** [comment]
but the important is that gmail/gtalk avatar are syncronized with emesene :)
