### ISSUE TITLE
Quit problem on OS X

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#736]
Theres a major problem on OS X when you try to quit emesene sometimes the Python crash reporter shows up saying that Python has crashed. 

Basically sometimes when quit is selected from the file menu or tray icon, Python hangs then display the crash reporter. But sometimes emesene will quit fine, its really weird.

./emesene -vvv simply states that the error was a "segmentation fault"

I guess its something to do with on_quit in Handler.py

This problem does not exist in 2.11.5 only in 2.11.6-devel

Here the crash report from Python http://pastebin.com/M5FVZy4r

**Comment by Sbte** [comment]
Could you try to do a git bisect?

**Comment by ghost** [comment]
I tried, as the error is not always reproducible a bisect its hard. I'll keep trying, but i have a feeling this could be a gtk error rather than emesene.

**Comment by ghost** [comment]
Fixed: wasn't a emesene problem. 

Turns out python does not like passing it output to a log file. That was causing a segmentation error as Python tried to write to the log on exit. Weird huh?
