### ISSUE TITLE
History log timestamp problem

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#737]
Looking the conversation log through contact->view information->chat history
The timestamp of every message appears as the current time :S (of the moment when i look at it every time).

**Comment by ivanalejandro0** [comment]
oh, i forget to say that i'm using git version.

**Comment by Sbte** [comment]
It works fine here. Can you show a screenshot maybe? And give the uppermost commit `git log` is telling you?

**Comment by ivanalejandro0** [comment]
~ $ git log | head -n6
commit 3e053734db119271fc8bd9aa6f811ec8d4bb1e18
Author: Sven (Sbte) svenb.linux@gmail.com
Date:   Mon Jul 18 19:04:05 2011 +0200

```
jabber: Add the jpg filetype
```

---

i've uploaded the screenshot te my mediafire account... i don't know wich image server choose because some of them are blocked in some countries :S

http://www.mediafire.com/i/?vjzs0okeceww3sn

this conversation is three hours ago, the timestamp is the same that system time.

**Comment by Sbte** [comment]
Really weird issue this. I remember this being present in the past, but I fixed that a while ago. I also can't find any way to reproduce it. Maybe something is missing on your OS? Because the gtk theme also seems to be broken.

**Comment by ivanalejandro0** [comment]
i have the latest packages for my distro (gentoo) + emesene2 (git pull origin master && git submodule update)
here list the ones which i think could be important:
python-2.6.7
papyon-0.5.5
pysqlite-2.6.3
sqlite-3.7.7.1
pygtk-2.24.0-r1
gtk+-2.24.5-r1
gtk+-3.0.11
webkit-gtk-1.4.1-r200
webkit-gtk-1.4.1-r300
pywebkitgtk-1.1.8

am i forgetting some package that could make this behavior?

Regarding to the gtk theme maybe it's only an aesthetic problem due to some misconfiguration of the themes in my system. All my gtk applications seems to work fine.

**Comment by Sbte** [comment]
Well, your python version is older than mine, but the python documentation can't tell me of any time or datetime functions that are only present since 2.7 that we use. Could you look in the database to see if the timestamps there are right? And maybe try to do

python
import datetime
datetime.datetime.utcfromtimestamp(timestamp)

on one of them? See it that's right? i.e.

> > > import datetime
> > > timestamp=1242624334
> > > datetime.datetime.utcfromtimestamp(timestamp)
> > > datetime.datetime(2009, 5, 18, 5, 25, 34)

Just guessing in the dark for me here :P

**Comment by ivanalejandro0** [comment]
that code works fine here.
I remember some theming problem with gtk and that disabled adium output in emesene.

The problem was the text output, when i replaced to adium output all timestamps are working fine as in the past :)

in Options->Preferences->Extensions
Category: conversation output
Selected: Output text

is the one i think has the problem, adium works fine :) ... and looks better ^^

**Comment by Sbte** [comment]
I have no clue why I didn't notice that. I mean, that shouldn't be too hard right? I'll see if I can fix it later. Maybe

**Comment by darkween** [comment]
i don't know if open a new issue or post here...

i have a similar problem:
the date is correct, but when the last message or the status change is not appropriate for the time zone of my country (Argentina). The hours that I get is 2 hours after the current time (the state is changed or wrote the last words)
