### ISSUE TITLE
Add a notification when the chat history messages exceed 1000

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#738]
There are messages in the sqlite database that are not shown in the log window. 
I copy&paste all contact history to a text file and there are missing parts, but searching through 'grep' command line utility i can find some phrases that i remember.

I used sqlitebrowser to open the file and don't appears to be corrupted.

I'm using git version of emesene2.

**Comment by Sbte** [comment]
Maybe your database is corrupted? I never had any problems with this...

**Comment by ivanalejandro0** [comment]
is any way to check that?
maybe exporting to a text file and importing again will solve this.

i didn't have a good experience importing from emesene 1.x, maybe the database are corrupted from then.

**Comment by Sbte** [comment]
Maybe the conversations are too old? Or you have too many? It only displays the last 1000 messages within the set timeframe. Try if you can find them by adjusting the timeframe.

**Comment by ivanalejandro0** [comment]
Indeed, that was the 'problem'. I was unaware of this limitation of 1000 messages.
I think there should be a message in the log window displaying this info :)

**Comment by Sbte** [comment]
Maybe we could add a message (type status) on top of the chat log (get_chats_between) to say:

The amount of displayed messages is limited to 1000. If you want to see more, please change the timeframe.

if the limit is exceeded. Or we could use a nicebar to tell that.

**Comment by ivanalejandro0** [comment]
It would be useful and more easy to know what's happening :)
Also i really miss some search feature in the log history, should i open a new issue with this feature request?

**Comment by Sbte** [comment]
yes please
