### ISSUE TITLE
Feature request: search in chat log

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#741]
I would like to have a search feature in the log history. It is possible to have that someday?
Also, it would be nice to be able to search the entire history instead the 1000 messages displayed in the current log system.

Thanks for your time.

**Comment by c10ud** [comment]
for the record:

a temp solution which involves a new window for choosing stuff could be nice
choose timeframe, keywords, hit search and you get a nice listview with dates...you click on them and the webkit view is populated with that day

**Comment by shuhaowu** [comment]
I would be interested in creating something like this if I know what/where the logging mechanism is. Could someone please brief me on that?

**Comment by Sbte** [comment]
The logger is in e3.base.Logger and makes use of an SQL database. And example of use is in gui.gtkui.ContactInformation

**Comment by pepeleproso** [comment]
If you need some help with sql stuff, ask me

**Comment by hussani** [comment]
It is possible to increase the limit of messages in the history, avoiding the message "Too many messages to display"?
