### ISSUE TITLE
Incoming file transfer

### ISSUE THREAD

**Issue by hit** [emesene/emesene#744]
There is no information about incoming file transfer, except desktop notification. No accept, no decline buttons in conversation so I can't even receive a file.

**Comment by pepeleproso** [comment]
Are you using git version? it's working here.

**Comment by hit** [comment]
Always git and not working here. Also using adium if that counts something.

**Comment by Sbte** [comment]
Then it's a dupe of #499 I guess

**Comment by Sbte** [comment]
@pepeleproso: IIRC it only happened for certain clients? So I suppose it works for emesene->emesene but not for for example WLM->emesene?

**Comment by pepeleproso** [comment]
WLM ->emesene works here I tested version 2009 and 2011
emesene ->emesene works here
