### ISSUE TITLE
logger not work

### ISSUE THREAD

**Issue by zodman** [emesene/emesene#746]
https://github.com/emesene/emesene/blob/master/emesene/emesene.py#L61

needs logging.configBasic()

**Comment by Mystro256** [comment]
I'm not sure what you mean, but if you know how to fix it, feel free to make a pull request :)

**Comment by Sbte** [comment]
No, we have this:

https://github.com/emesene/emesene/blob/master/emesene/debugger.py

We do what logging.basicConfig() does, but then we create our own StreamHandler with our own Formatter.

If you want more debug channels enabled, just run emesene with -v, -vv, or -vvv
