### ISSUE TITLE
Some emoticons not shown/rendered in Adium

### ISSUE THREAD

**Issue by hit** [emesene/emesene#747]
Emoticons not rendered have filenames in format "shortcut.hash.png" ("hash.png's" are ok).

**Comment by Sbte** [comment]
@4ndreaSt4gi^

I think sync did this?

**Comment by astagi** [comment]
Yes, I just copy the files and put their name in the emoticons.info file.. this works, what is the problem??

**Comment by ghost** [comment]
@4ndreaSt4gi
You mean that if the emoticons shortcut was "?:)" that would make the filename "?:).emoticon.png"?
If so thats going to be a problem on windows computers, were some symbols not not allowed in filenames.

**Comment by astagi** [comment]
yes, but well I thought emesene 1 didn't have this bug and saved icons with a correct name... are you sure that emesene 1 allows special characters??

**Comment by hit** [comment]
Special characters are escaped (i.e colon [:] becomes "%3A"), but they still won't work.
Sync could just take the shortcut part out of the filename, if any present, and should be solved. I'll write some simple script to convert my current emoticons as well.

**Comment by astagi** [comment]
What doesn't work? please, report all the steps to reproduce the problem, thanks... are you sure that changing filnames solves your problems?

**Comment by hit** [comment]
Getting rid of shortcuts in filenames solves the problem. I guess there are too many periods in filename otherwise (shortcut DOT hash DOT png|gif).

**Comment by Sbte** [comment]
Maybe the emoticons are referenced by the hashes only?

**Comment by Sbte** [comment]
andrea, how are they referenced in emoticons.info? Only by hash like the emesene 2 ones? I can't test it because I don't have any custom emoticons.

**Comment by astagi** [comment]
I'll report my situation... in emesene 1.0 I have two custom emoticons to say "sisi" and "foto"... their file names are:

foto.116b945fc4224b6c80f557a82c5a8d6aaa8e13a0.gif
sisi.c9854853b3479a116966cebd2861c160c217266b.gif

So the format in emesene1 is shortcut.hashcode.extension. sync just copies these files in emesene2.0 config directory extrapolating the shortcut and writing in emoticons.info ( still in emesene2.0 ) what must be written, that is:

foto foto.116b945fc4224b6c80f557a82c5a8d6aaa8e13a0.gif
sisi sisi.c9854853b3479a116966cebd2861c160c217266b.gif

So emoticons.info format is something like:

shortcut1 namefile1
shortcut2 namefile2
..... ......
..... ......
shotcutN namefileN

@hit please report file names you have in emesene1 this may help... I'll solve it asap, thanks ^^

**Comment by hit** [comment]
Sorry I almost forgot this issue. I already fixed this one by renaming filenames. Those with shortcuts in them were probably some really old entries from emesene 0.x maybe and should never appear again. So I think we can close this issue :p
