### ISSUE TITLE
msn: display images do not download, having to manually enter personal message on every login

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#75]
when using msn contact's display images don't download and im having to enter my personal message on every login

**Comment by c10ud** [comment]
with papyon 0.5? not good

**Comment by SWOriginal** [comment]
yeah using papyon0.5, contacts have also told me my user name is just showing as my email address even tho it shows as my name on the main header

**Comment by c10ud** [comment]
i'm closing this issue since the problem is the same as file transfers :)
