### ISSUE TITLE
Check for broken profile and inform users

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#750]
At launch a check for broken profiles would help reduce the number of issues opened that are broken profile related.

**Comment by Mystro256** [comment]
To add to your suggestion, I figure something along the lines of a popup box like this would do:
<img src=http://i54.tinypic.com/zlu7og.png>

or the raw text:

```
Your account seems to be broken, which will cause you to experience issues with you display name, picture or personal message.

You can fix it now by following the link and re-uploading a picture, or fix later by hitting the live messenger tab in the preference window
```

**Comment by Sbte** [comment]
Yep, and a proper way to detect it.

**Comment by c10ud** [comment]
i don't think there's even a way to detect that (?) so.. time will help us, the less people use emesene1, the more will have their profile fixed

**Comment by Sbte** [comment]
I think we can try to catch the http error?

**Comment by c10ud** [comment]
i don't think papyon tells us about it

**Comment by Sbte** [comment]
Well, not in the ClientEventInterface apparently, but I was hoping there was some way to catch errors emitted from gnet.HTTP. I'll ask around.

**Comment by Sbte** [comment]
```
aug 09 12:03:28 <lfrb>  sbte: you should be able to do something like :
aug 09 12:03:47 <lfrb>  content_roaming.connect('error', callback)
aug 09 12:04:19 <lfrb>  and then check if the error is an HTTP error
aug 09 12:04:43 <sbte>  ok
aug 09 12:04:46 <sbte>  I'll check later
aug 09 12:06:58 <sbte>  lfrb, why isn't it caught in ClientEventInterface btw?
aug 09 12:07:16 <sbte>  should we really connect things outside papyon instead of using that?
aug 09 12:10:23 <lfrb>  sbte: because the content roaming object isn't created by the client
aug 09 12:10:38 <lfrb>  it's created by the application (emesene)
aug 09 12:12:13 <lfrb>  I agree it's not perfect though..
aug 09 12:14:22 <lfrb>  it might be a good idea to create it in client as the mailbox and oim stuff
aug 09 12:15:17 <lfrb>  actually it IS created by the client, my bad
aug 09 12:15:26 <lfrb>  I need to connect signals
aug 09 12:15:50 <lfrb>  sbte: I will fix that
```

So yeah, now we wait...

**Comment by c10ud** [comment]
implemented upstream waiting for emesene 2.11.7 to break ABI with older papyon and implement the new content roaming interface

**Comment by Sbte** [comment]
c10ud, we don't have to. We can just catch the errors in our ClientEventInterface. Then send an event that we handle somewhere else. With a dialog for example.

**Comment by Sbte** [comment]
That or we have to connect it inside the worker, which is a second option that works on all versions, but is more ugly. But that's the way CR works atm too.

**Comment by Sbte** [comment]
Done. If anyone has suggestions, please tell me, or fix it yourself of course. This will only work with current papyon master, which is included in the commit. Just do a git submodule update.
