### ISSUE TITLE
detect custom emoticons shotcurt

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#755]
When we want to know the name of a custom emoticons that don't appear we can click save e read,
but actually the box is empty..

would be nice to auto-retreive the name of that emoticons

**Comment by c10ud** [comment]
how about clicking on the blank icon? does that work?

**Comment by Fabioamd87** [comment]
I've tried to stay with cursor on but nothing appear, you mean left click?

**Comment by c10ud** [comment]
yes

**Comment by Fabioamd87** [comment]
I don't remember... :(

what abut the "feature" to automatically retreive shotcurt? :)

**Comment by c10ud** [comment]
and where do we put it? 

that's an html img tag iirc, and contains the shortcut. adium themes allow clicking to swap back and forth between text and the image

**Comment by Fabioamd87** [comment]
in the box to save it?

**Comment by Sbte** [comment]
I fixed it in a lame way, but couldn't find any other way to do this. It's only called when saving a custom emoticon anyway. Shouldn't happen too often...
