### ISSUE TITLE
Logviewer

### ISSUE THREAD

**Issue by hit** [emesene/emesene#756]
Maybe display logs only for current day as default and additionally cut it down to 1000 messages if exceeded?

**Comment by c10ud** [comment]
i don't quite understand this (!) where's the issue?

**Comment by c10ud** [comment]
now i got it.. i think that if we must show >1000 messages we must find a way to let the user select between "pages" of 1000s

**Comment by c10ud** [comment]
@sbte @pepeleproso @marianoguerra

**Comment by c10ud** [comment]
[23:48] <pepeleproso> maybe two buttons at bottom
[23:48] <pepeleproso> back and next
[23:48] <c10ud> yes but with: [<<] "page X of Y" [>>]

**Comment by Sbte** [comment]
I think he means adding a general log viewer not limited to one contact instead of this?

**Comment by c10ud** [comment]
i don't think so, tim

**Comment by hit** [comment]
What I really meant, was to display all logs of a contact (pm/status/chat history) for current day only as default. Not yesterday's and so on. If there are >1000 entries for that day, cut them down to 1000 or maybe even less. This way we can make whole information window loading noticeably faster(?)

**Comment by Sbte** [comment]
and usage probably more annoying. Maybe there's a way to speed up the loading though, by improving adiumtextbox.

**Comment by c10ud** [comment]
you can fake a speedup by appending messages while fetching them but my solution is still the most valid https://github.com/emesene/emesene/issues/756#issuecomment-1831106

**Comment by Sbte** [comment]
IIRC it draws after every appending message. Not sure about this though, but we might get a HUGE speedup if we only draw it when it's done.

**Comment by ivanalejandro0** [comment]
i think a combination of some ideas would be great: 
- pager (back and next buttons)
- show messages while loading (maybe this slows down the process :S)
- it would be nice to have a progress bar to see what's happening (especially for old computers)

**Comment by c10ud** [comment]
#1118

**Comment by c10ud** [comment]
#1118
