### ISSUE TITLE
Disable sound if busy or away

### ISSUE THREAD

**Issue by hit** [emesene/emesene#757]
Hearing sounds as busy - bug or (un)feature?

-- edit --
Emesene should have an option to disable sound if user is busy. And/or allow sounds _only_ if user is online? I'd prefer more this last one I guess.

**Comment by Mystro256** [comment]
I would assume you're requesting an option to toggle hearing sounds while set to busy status?

If so, please edit the title to reflect a request not a bug ;)

**Comment by hit** [comment]
Seems more like a bug tho.

e3/common/Sounds.py:
        _if self.session.contacts.me.status != e3.status.BUSY and not \_
           _self.session.config.b_mute_sounds:_

This should already take care of not playing sounds if busy or muted.

**Comment by Sbte** [comment]
Works fine here. Are you sure you actually set your status to busy?

Btw, I don't think we should implement this for away and idle, because in my opinion, the only purpose of the busy status is to exactly this.

**Comment by Mystro256** [comment]
@hit

Yeah it would make sense to make the mute option for busy status, and maybe away, as other IM's have this ability.

@Sbte

Agreed, idle busy implies "do no disturb" or "not able to answer," while away and idle implies "away from keyboard." If one was set to away, they should be able to hear a new message if they're close by. Busy should be the only one it's muted, or at least <b>by default</b>

**Comment by Sbte** [comment]
@Mystro256, can you reproduce this bug then? I can't.

**Comment by Mystro256** [comment]
I can't but I would assume @hit can. I'll play with it and try to but I haven't been able to so far.

@hit can you post any details?

**Comment by hit** [comment]
I don't know how, but somehow it got fixed by itself. Spooky.
