### ISSUE TITLE
1.6 can't login

### ISSUE THREAD

**Issue by smarliecy** [emesene/emesene#758]
it'd log out some other msn connections but unable to connect successfully
mostly happened after sleep mode
but was able to connected some times(rarely but it happened)

 File "PluginManager.pyo", line 257, in startActivePlugins

  File "PluginManager.pyo", line 232, in startPlugin

  File "C:\Program Files\emesene\plugins_base\CustomStatus.py", line 56, in start

AttributeError: 'NoneType' object has no attribute 'connect'

**Comment by Sbte** [comment]
emesene 1.x is not supported anymore. Please use emesene 2.x. See 

http://blog.emesene.org/p/downloads.html

**Comment by c10ud** [comment]
Sorry, we are not looking into emesene-1 anymore, please update to
2.x, the main focus of development

2011/8/4 hesi reply@reply.github.com:
