### ISSUE TITLE
Feature request: conversation keepalive

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#759]
Is it possibile to ad a keepalive option for multiple conversations like there was in emesene1? I noticed how much i miss this feature when i found myself chatting with people not using emesene1...

**Comment by Sbte** [comment]
What did it do?

**Comment by Soulsuke** [comment]
It prevented group chats to time out (kicking everyone out) if no messages have been sent for a while, I guess it sent some sort of signal to the server

**Comment by c10ud** [comment]
papyon doesn't have options for keepalives, it needs to be implemented in the library. It's a 10mins work, but since they don't merge our one-liners.......

**Comment by c10ud** [comment]
https://github.com/emesene/papyon/commit/f2c1b1af3902d05aa330e205e53c194d90413a25
and 
https://github.com/emesene/papyon/commit/231ede95507a9826469ae45619ffc45b6f42ba1d

waiting for review

**Comment by Soulsuke** [comment]
So.... Did anyone actually review the code or...?

**Comment by c10ud** [comment]
nope, but you can find a nicer papyon here: https://github.com/emesene/papyon

2011/9/5 Soulsuke
reply@reply.github.com:

**Comment by Soulsuke** [comment]
Sounds fair, just a noobish question: the standard papyon gets installed in /usr/lib/python2.x, if I keep this one in /usr/local/lib/python2.x, which one will actually be loaded?

**Comment by c10ud** [comment]
no idea, my suggestion is: don't mess with the system directories

2011/9/6 Soulsuke
reply@reply.github.com:

**Comment by Soulsuke** [comment]
Totally! XD
Guess I'll remove the default one and I'll keep this new one manually updated, just to be sure

**Comment by c10ud** [comment]
or put it in emesene/e3/papylib/papyon just like the submodule does

2011/9/6 Soulsuke
reply@reply.github.com:

**Comment by Soulsuke** [comment]
But the doesn't it get pulled along with emesene2 through regular git pull??

**Comment by c10ud** [comment]
no, if you do git submodule init && git submodule update it will fetch
the papyon on freedesktop.org

2011/9/6 Soulsuke
reply@reply.github.com:

**Comment by Soulsuke** [comment]
Allright, then i have to run 'git pull origin master' to get the latest emesene2 code, then another git pull to put the new papyon in e3/papylib/papyon... No more submodule init/update or setup.py install (for papyon), right?

**Comment by Sbte** [comment]
Yes, in e3/papylib/papyon just a git pull emesene-papyon master, or whatever your remote is called.

**Comment by Soulsuke** [comment]
I'm quite new to git but wouldn't it be faster to change the submodule in ..gitmodules ?

**Comment by c10ud** [comment]
yes but we haven't decided on what to do yet

2011/9/6 Soulsuke
reply@reply.github.com:

**Comment by Sbte** [comment]
I'm not sure, but I think git will tell you that you have 'unstaged changes' when you try to pull, and refuse to pull new stuff. But feel free to try.

**Comment by Soulsuke** [comment]
@c10ud: do you mean there's a chance it'll be implemented??

**Comment by c10ud** [comment]
there's a chance we get tired and put our papyon version directly in emesene code so we don't have to worry about freedesktop, ubuntu or everyone else

**Comment by Soulsuke** [comment]
Oh, I see... I guess this isn't the first time something like that happened, then

**Comment by c10ud** [comment]
papyon is now inside emesene tree, with this feature (disabled by default, probably needs a gui check for it?)

**Comment by Soulsuke** [comment]
Mmmmh... Not sure if I should open a new bug about this or not, but the setting won't get saved between emesene restarts

**Comment by c10ud** [comment]
open new one pls
