### ISSUE TITLE
cannot block in conversation menu

### ISSUE THREAD

**Issue by DarkRedman** [emesene/emesene#76]
Binary package hint: emesene

I use Ubuntu 9.10 with amd64 architecture, I've emesene 1.6

In the conversation menu the is no block function is not implemented, so if someone who is not in my contact-list talks to me, I cannot block him if I want.

it should be implemented, it's sometimes faster than to use the contact-list if this one is big.

**Comment by c10ud** [comment]
Block/unblock button in conversation toolbar.

This doesn't mean block/unblock will work, since it needs to be handled at protocol level. BONUS: implemented tooltips in conversation toolbar buttons. Closed by 1ebd83601ab3a3ef1ddbcbf45099bbbc4cc0c855
