### ISSUE TITLE
settings restored every time

### ISSUE THREAD

**Issue by neptunium** [emesene/emesene#760]
every time i close emesene,it deletes all the settings i have done at preferences,  like the font of the letters, the sounds etc.. what's wrong?? i have emesene 2.11.4

**Comment by c10ud** [comment]
update to 2.11.7 and it will work

2011/8/7 neptunium
reply@reply.github.com:

**Comment by neptunium** [comment]
i downloaded 2.11.4 because this is the version recommended for ubuntu on the site. anyway,i downloaded a file for 2.11.7 with many files and archives, but i can't find how to install it. i have the latest version of ubuntu..

**Comment by c10ud** [comment]
unfortunately our Ubuntu packagers are on vacations, we hope to have
the new packages available soon in our PPA!

p.s. our PPA already contains 2.11.5 - better than nothing :)

sudo add-apt-repository ppa:emesene-team/emesene-stable
sudo apt-get update
sudo apt-get install emesene

2011/8/7 neptunium
reply@reply.github.com:

**Comment by neptunium** [comment]
i think it's much better! Thank u!

**Comment by c10ud** [comment]
no problem, if you added the ppa you will get the 2.11.7 update as soon as the package is updated
