### ISSUE TITLE
File transfer on Windows bug (emesene 2.11.7 - install)

### ISSUE THREAD

**Issue by zakos** [emesene/emesene#761]
File transfer doesn't work on Windows 7 (Home Prof, X86) if "Sort recieved files by sender" option is checked on Options/Desktop.
If it's uchecked file transfer is OK,but i want to sort under another directory by senders.

**Comment by Sbte** [comment]
What doesn't work exactly?

**Comment by zakos** [comment]
File does not arrive, and the folder is not created.

**Comment by Sbte** [comment]
Ah, it doesn't save.

Here's your error:

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/papylib/Worker.py", line 402, in papy_ft_completed
    full_path = os.path.join(download_path, tr.sender, tr.filename)
  File "/usr/lib/python2.7/posixpath.py", line 66, in join
    if b.startswith('/'):
AttributeError: 'Contact' object has no attribute 'startswith'
```

**Comment by zakos** [comment]
And what can I do for this? How could I fix?

**Comment by Sbte** [comment]
The file does not show on your disk, but the progressbar goes right?

I'm fixing it right now btw.

**Comment by zakos** [comment]
No, I can't accept file transfer. progressbar is on 0% doesnt happen nothing. But I can deny file transfer.

**Comment by Sbte** [comment]
I just fixed the "Sort recieved files by sender" option. If it still doesn't work for you, it's probably a different issue.
