### ISSUE TITLE
Only shows one indicator when running multiple instances of emesene

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#763]
If I try to open more than one instance of emesene in my Ubuntu 11.04 I only have one indicator, for the first instance.
There should be one indicator for each instance.

**Comment by Sbte** [comment]
Indicator or messaging menu entry? Because for me the multiple messaging menu entries work..

**Comment by c10ud** [comment]
i don't think indicators allow multiple instances of the same app tho

**Comment by c10ud** [comment]
also, ubuntu doesn't want users to use indicators but IMs should use the messaging menu

**Comment by igorsantos07** [comment]
I really meant Indicators. I uninstalled my messaging menu because emesene 1 didn't supported it. Gonna install it again and see if it resolves the problem.

**Comment by Mystro256** [comment]
@igorsantos07 you can always just use the tray icon option (and white-list emesene on the tray if you're using unity).

Although, I believe @c10ud is right though; I'm pretty sure indicators have a "one per app" policy because it's for single instance apps.

**Comment by c10ud** [comment]
http://askubuntu.com/questions/14555/what-is-the-difference-between-indicators-and-a-system-tray

it's reccomended the use of MessagingMenu in ubuntu but we'll leave Indicators in the code for future reference.

also, emesene/gui/gtkui/Indicator.py:
        appindicator.Indicator.**init**(self, "emesene", "logo", \

i believe that if somehow is achieved to change the "emesene" string to something like "emesene-%s" % instance_n you could have multiple indicators for emesene, the trick would be correctly increasing instance_n with the currently active instances..and that's quite tricky..

since they shouldn't be used i guess we WONTFIX this, but if someone wants to hack a bit...

**Comment by c10ud** [comment]
if someone wants, here's a patch to try -- i cannot try it cause i'm on lucid.

diff --git a/emesene/gui/gtkui/Indicator.py b/emesene/gui/gtkui/Indicator.py
index 4bd38a6..c2e8b67 100644
--- a/emesene/gui/gtkui/Indicator.py
+++ b/emesene/gui/gtkui/Indicator.py
@@ -50,7 +50,8 @@ class Indicator(appindicator.Indicator, gui.BaseTray):
         handler -- a e3common.Handler.TrayIconHandler object
         """
         gui.BaseTray.**init**(self)
-        appindicator.Indicator.**init**(self, "emesene", "logo", \
-        app_name_hax = "emesene-%s" % handler.session._account
-        appindicator.Indicator.**init**(self, app_name_hax, "logo", \
           appindicator.CATEGORY_APPLICATION_STATUS, \
           os.path.join(os.getcwd(), handler.theme.image_theme.panel_path))

**Comment by igorsantos07** [comment]
I'm running the last dev version, I've just pulled from the repos.
Now there's no indicator, neither icon in the systray. The only way I have to know it's running is using the messages indicator - that I normally have uninstalled.

**Comment by Mystro256** [comment]
what do you have the tray option set to?

**Comment by igorsantos07** [comment]
WOW there's an option for that.
Ok sorry. Now it's working just fine.
But, seriously, do you plan to move those "extensions" options to a better place, right? They are quite hidden there.
