### ISSUE TITLE
[Feature Request] Checkbox to enable sound with busy status

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#765]
Hi all!

Thanks for your work. emesene 2.11.7 is a very nice client!

But I would like to see a feature in it. In busy status the sounds (notification) are disabled. I see why it is works like that. But for me it isn't the best. So can somebody make a checkbox (enable sound, when your status is busy) for this in the preferences?

**Comment by c10ud** [comment]
iirc that's the official client (and user-expected) behaviour.. we
already have loads of options, i'd really like to avoid this one..

2011/8/8 rockybalboa
reply@reply.github.com:

**Comment by rockybalboa** [comment]
Okay, I understand it. I use the away status instead busy, this solve my problem.
Anyway thanks all for your efforts. :)

**Comment by c10ud** [comment]
no problem
