### ISSUE TITLE
Emesene in PPA yet to be updated to 2.11.7

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#766]
I just noticed when I ran the updater on my Ubuntu computer, only 2.11.5 is available in the stable ppa, 2.11.7 still needs to be uploaded.

I'm not sure who's in charge of it so I decided to post it here ;)

**Comment by c10ud** [comment]
not an issue, we don't do packaging, we delegate :D

**Comment by Mystro256** [comment]
lol, okay, I figure it's a work in progress then? ;)

**Comment by c10ud** [comment]
we called, now we're waiting for an answer :P

2011/8/8 Mystro256
reply@reply.github.com:
