### ISSUE TITLE
Multiline Messages don't arrive

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#77]
Hi, if my contact send to me a message with several lines (mostly with copied and pasted messages) don't arrive to my chat window, and not sound is played (but I can read it on the pyNotification)
- Me: Ubuntu, Papyon 0.5
- Contact: Windows, Live Messenger.

Regards!!

**Comment by c10ud** [comment]
still happening with 0.5.1? there could be a bug when papyon is doing underlying transfers that delay chatting a lot

**Comment by EibrielInv** [comment]
Yep, just yesterday...

**Comment by EibrielInv** [comment]
Apparently the error on console is:
    *\* Message: console message: undefined @1: SyntaxError: Parse error

**Comment by c10ud** [comment]
are you using the webkit backend with adium themes? if so, i think wariano could have a look into this....

**Comment by EibrielInv** [comment]
Mmmm I don't understand completely... I'm using Adium output with Ravenant theme...

**Comment by c10ud** [comment]
yes, it's a bug in the webkit backend for showing conversation text then.. unfortunately i think only wariano has the req'd knowledge to look into this

**Comment by marianoguerra** [comment]
should be fixed, I tested sending and receiving random javascript, html and text with newlines and it worked
