### ISSUE TITLE
Make Media Message a little bit nicer

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#770]
Thanks for the media message commit, this is a basic feature. :) But this should be a litt bit nicer:

Screenshot:

http://noob.hu/2011/08/10/mediamessage_0.png

Like: 

(headphone logo) Track - Artist

Thank you all!

**Comment by rockybalboa** [comment]
Thanks, you're are very fast. ;)

**Comment by c10ud** [comment]
np, i didn't notice this styling issue when commiting :)
