### ISSUE TITLE
can't login...

### ISSUE THREAD

**Issue by smarliecy** [emesene/emesene#774]
having problem to log in almost all the time
the error message as follows:

( in fact I'm currently using emesene 2.1
and already had emesene uninstalled but it still indicate that I'm using 1.6)

Exception
You are using emesene 1.6.X - "Uberlândia undrgz" BETAFIX? so you're free to complain here:
http://forum.emesene.org/index.php/board,19.0.html
Check already existing tickets for duplicates first, please.
Traceback (most recent call last):

  File "PluginManager.pyo", line 257, in startActivePlugins

  File "PluginManager.pyo", line 232, in startPlugin

  File "C:\Program Files\emesene\plugins_base\CurrentSong.py", line 97, in start

AttributeError: 'NoneType' object has no attribute 'register'

**Comment by arielj** [comment]
You are running emesene1, plugins_base is an emesene1 folder, so is the CurrentSong.py file.

Check where's the shortcut pointing.

i it still fails, remove EVERYTHING and then install emesene2
