### ISSUE TITLE
Error on message not being sent

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#778]
```
00:09:55 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'message_waiting'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/e3/common/notification.py", line 126, in _on_message
    conversation.message_waiting:
AttributeError: 'NoneType' object has no attribute 'message_waiting'
[00:15:01 ERROR papylib.Events] Error sending message: 4 1
```

No clue where it came from though. Conversation still worked after this.

**Comment by arielj** [comment]
the first part is only a notification problem (maybe some signal not being unsubscribed when a conversation is destroyed?)

the last bit... papyon uses those codes, I remember someone saying what "4 1" means, I think there's some documentation somewhere inside papyon's code about error codes

EDIT: "4 1" just means:
    MESSAGE = 4 #message error
    DELIVERY_FAILED = 1 #failed to deliver

that could be a network problem, server problem, your contact's problem... who knows? we can't do anything about it, we can only look that notification error but it's like... random, we should close this :P

**Comment by Sbte** [comment]
I know about the papyon error, But there should be some way to prevent the traceback from happening at least. Could break notifications, because the signal is most likely unsubscribed.

**Comment by c10ud** [comment]
arielj is right, as for the conversation exception, that's a notification on a dead conversation -- we must prevent this. Maybe we're killing (already killed) the conversation when the notification is issued, if you can reproduce we can fix this (i don't use notifications, cool me!)

**Comment by Sbte** [comment]
Is there some easy way to reproduce failing messages?

**Comment by c10ud** [comment]
nope

**Comment by Sbte** [comment]
I see to things that can make this happen:

The conversation got closed (switchboard or something), which would normally trigger a new cid/conversation being generated. But because sending the message failed, it wasn't, and the notification failed, because it couldn't find similar conversations.

The information message triggered this, because it's not really a message on a conversation.
