### ISSUE TITLE
Don't upgrade papyon yet!

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#779]
...unless you want non-working file transfers and emesene using 100% CPU. Just sayin' ;)

Anyways, there is some activity on the upstream papyon branch, but don't upgrade after 7f2c9426a434a7197f6272afafa7f5d86a1aeca1. The next two commits cause severe breakage. Just putting this here so no one upgrades our submodule.

**Comment by c10ud** [comment]
w00t?

**Comment by c10ud** [comment]
with a pending file transfer (not advertised through event interface)

(16:58:39) papyon.transport:<<< BYE emesenetest@live.com;{fe799523-4b00-4cb6-991a-81cf8e046ae2}
(16:58:39) papyon.transport:<<< BYE emesenetest@live.com
(16:58:39) papyon.msnp2p.transport:Unregistering transport <SwitchboardP2PTransport peer="emesenetest@live.com" guid="fe799523-4b00-4cb6-991a-81cf8e046ae2">
(16:58:39) papyon.protocol.switchboard_manager:Closing switchboard handler <SwitchboardP2PTransport peer="emesenetest@live.com" guid="fe799523-4b00-4cb6-991a-81cf8e046ae2">
(16:58:39) papyon.protocol.switchboard:Leaving switchboard 1889449115
(16:58:39) papyon.transport:>>> OUT 10

-------------> 100% cpu starts

[...](16:59:14) papyon.transport:>>> PNG
(16:59:15) papyon.transport:<<< QNG 47
(17:00:01) papyon.transport:>>> PNG
(17:00:02) papyon.transport:<<< QNG 49
(17:00:40) papyon.protocol.switchboard:Disconnected (1889449115)
(17:00:40) papyon.protocol.switchboard_manager:Closing switchboard handler <SwitchboardConversation participants="emesenetest@live.com">

-------------> 100% cpu stops

**Comment by Sbte** [comment]
Ok, we can upgrade now.
