### ISSUE TITLE
On first .fill() of contact list. ALL contacts are passed with status offline, when isn't true.

### ISSUE THREAD

**Issue by lfottaviano** [emesene/emesene#78]
Once logged in, when the .fill() method is called (at first time), all the contacts passed to contactlist through add_contact(), have status OFFLINE. Thats the reason why groups don't organize well in first step.
It could be because we are not waiting for the update of the attributes of the contacts.

I am working on this.

**Comment by c10ud** [comment]
great! btw, which backend? papyon i guess?

**Comment by c10ud** [comment]
hello, did you finish your contact list patches?

**Comment by marianoguerra** [comment]
the first fill is with all the contacts offline because we got the contact list from the contact server but we didn't started to receive the status messages from the notification server, this is expected behavior

**Comment by lfottaviano** [comment]
yes, we only need to start filling contact list, once we have recvd the status messages. if we have all contacts offline dont fill, keep waiting. i 've no time this period, sorry for the troubles.

**Comment by marianoguerra** [comment]
the status messages take a really long time to come, it would mean ~5 or 10 seconds of an empty windows.

emesene and all the clients first display the contacts as offline and then start changing status, it worked like this until now on emesene 1 and 2 and I think it's the best way to work if not emesene would seem really slow when in fact it's just a perception.

**Comment by lfottaviano** [comment]
ok, you r right, we cant keep waiting 5 seconds, i had thought it was faster, didnt realize..  we will have to manage another contingency...
