### ISSUE TITLE
Ubuntu (new) message menu support is broken

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#780]
Sorry guys, but the Ubuntu guys f@cked up something again, so the messaging menu support is broken again.

Screenshot:

http://noob.hu/2011/08/16/emesene.png

(Ubuntu 11.10 - emesene 2.11.8-dev)

**Comment by Sbte** [comment]
Install indicator-status-provider-emesene

**Comment by rockybalboa** [comment]
I installed it. But isn't solved the problem.

Edit: It is works now, needed a reboot. :) Thanks.

**Comment by c10ud** [comment]
install indicator-status-provider-emesene or something similar and it
should work -- once someone packages emesene >= 2.11.7 this will be a
mandatory dep for ubuntu so it will work out of the box

2011/8/16 rockybalboa
reply@reply.github.com:
