### ISSUE TITLE
Email Problem

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#781]
I use Emesene 2.11.7 on Windows XP SP3. When I clic on the Email botom, Emesene don´t open my email aconunt in Internet Explorer, or Mozilla Firefox or any other browser.

**Comment by ghost** [comment]
My Windows XP is 32Bits

**Comment by c10ud** [comment]
Make sure html files are associated with a browser

**Comment by c10ud** [comment]
also note that we're using this method:

webbrowser.open(url[, new=0[, autoraise=True]])¶
Display url using the default browser. If new is 0, the url is opened in the same browser window if possible. If new is 1, a new browser window is opened if possible. If new is 2, a new browser page (“tab”) is opened if possible. If autoraise is True, the window is raised if possible (note that under many window managers this will occur regardless of the setting of this variable).

Note that on some platforms, trying to open a filename using this function, may work and start the operating system’s associated program. However, this is neither supported nor portable.

Changed in version 2.5: new can now be 2.

**Comment by ghost** [comment]
The html files are associated with a browser.

The problem continues.

**Comment by originell** [comment]
`webbrowser.open` does nothing else than passing the URL to  `os.startfile` on Windows. Which in turn results in Windows itself handling the opening of the file. I do not have access to any windows OS at the moment, but could you try doing [what MozillaZine explains here](http://kb.mozillazine.org/Default_browser#Setting_default_browser_manually)? Especially this part:

> Assign the following protocols and file types to the browser you wish to set as default:
> URL:HyperText Transfer Protocol (HTTP protocol)
> ....
> In Windows XP and earlier, you can find the URL protocols listed above in File Types, under extension "N/A" or "(NONE)".

So the problem should not be associating with _html_ files, rather it is associating with the URL scheme ;-)

The webbrowser module should be a bit smarter in those cases, that is true, but does not really have anything to do with emesene afaik. Feel free to contribute to python issue [8232](http://bugs.python.org/issue8232) ;-)

**Comment by ghost** [comment]
I reported the bug on the website of Pyton and they told me to report the bug on the Emesene website.

**Comment by ghost** [comment]
Sorry, but I'm not a programmer. I'm just a lay user. I'm just reporting the failure. I ask the developers of Emesene correct the failure. I'm reporting the failure in the right place, the right website?

**Comment by pepeleproso** [comment]
Issue should be fixed now, you will need to wait until emesene 2.11.8 is released.

**Comment by ghost** [comment]
@Butuntu
If your impatient for 2.11.8 or I am unable to package 2.11.8 in time for its release date, there is a guide on how to run it or package it your self at https://github.com/emesene/emesene/wiki/Windows-(New).
