### ISSUE TITLE
Webkit rendering lockup

### ISSUE THREAD

**Issue by markuznw** [emesene/emesene#784]
As per http://www.blogger.com/comment.g?blogID=28704147&postID=7336221184555896340 (@syst3mfailur3 request) I'm opening this since on my 3 windows 7 machines emesene 2.11.7 locks as soon as i try send a message when using webkit (adium) rendering on message windows. Don't know what i can do to help the debug, since the program just freeze completely. I found out anyway that sometimes it becomes responsive again after like... 70 seconds or more of freezing. Could it be maybe cause I use google chrome on computers (so webkit dlls are shared or something?)

**Comment by c10ud** [comment]
i think it could be a bad dll in the emesene package or something like that, unfortunately i don't have windows so i don't exactly know what's going on but if some developer does, please step up and try to debug this issue

**Comment by ghost** [comment]
I can't test this atm, but try completely removing emesene2. The unistaller in 2.11.7 should remove everything (including any registry files left by earlier versions of emesene2), but manually check program files just to be sure. Then reinstall.

I don't think it is Chrome that is causing it as I had it installed as well, though it wasn't my default browser, and didnt have any issues. Not really sure what is causing this to happen.

**Comment by c10ud** [comment]
needs to be rechecked as soon as the 2.11.11 binary is up

**Comment by arielj** [comment]
It's still happening, I guess it's some bug with loading webkit on windows 7, it doesn't lock emesene on Windows XP. If it's a webkit bug we can't do much, I'll try to find new webkit dlls or something.

**Comment by c10ud** [comment]
just tested .12-devel portable in xp sp3 and seems like webkit was working

**Comment by c10ud** [comment]
just a thought, can't we set some sort of xp compatibility mode in 7? needs to be tried, someone with 7........?

**Comment by c10ud** [comment]
#1417 shows 2.12.5 working in w7 x64, closing here
