### ISSUE TITLE
Broken contact list

### ISSUE THREAD

**Issue by hit** [emesene/emesene#788]
I guess something got messed up when @Sbte tried to improve and simplify Plus! parsing.
Shot: http://i.imgur.com/cK7hi.png

"Sky Plus" here reffers to a radio station's name which the contact is listening to. Mostly it's parsed correctly, but sometimes it messes up something.

**Comment by Sbte** [comment]
I don't see what's wrong with that name. Maybe it's the &? Or just the fact that it's a media message?

**Comment by c10ud** [comment]
emesene version, if development, emesene revision

**Comment by hit** [comment]
I've seen a lot of &'s and other characters there, but they were all fine :s One messed up song had "ää" (estonian letters) in it. 

And latest git as always.

**Comment by c10ud** [comment]
honestly the markup seems correct tho, the & is also in a name two contacts under so i don't think that's the problem

**Comment by c10ud** [comment]
trying to repr but no luck so far

♫ Sky Plus - LMFAO feat. Lauren Bennett & Go - Party Rock Aäänthem

**Comment by Sbte** [comment]
The i suspect the media message from not being converted to unicode/stripped properly? Maybe normal messages pass through some parser that media messages don't?

**Comment by c10ud** [comment]
could be some escaping issue in gtkui.ContactList relative to PMs and Media Messages being treated differently but this doesn't seem the case looking at the code

**Comment by c10ud** [comment]
pull and test, should be fix'd now

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/commit/a1e10c88307cd09a0c01197ff712aa99551c0d5a

**Comment by hit** [comment]
Okay, I'll let you know if this happens again.
