### ISSUE TITLE
Unable to see if contact is blocked or not

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#79]
unlike emesene 1\* there is no blocked icon overlay on blocked contacts, also theres also no hover tooltip thing for contact information such as:

"Blocked: Yes/No"
"Has you: Yes/No"
"live space: Yes/No"

**Comment by c10ud** [comment]
tooltips implemented

**Comment by c10ud** [comment]
we still need somekind of emblem/text in contact list and conversation window

**Comment by marianoguerra** [comment]
[$BLOCKED] is replaced by "(blocked)" if the contact is blocked and by "" if the contact isn't blocked.

you should edit the display template in preference but it's available.

closing
