### ISSUE TITLE
sync avatar with WLM client

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#798]
is possible this thing with our current msn protocol?

**Comment by c10ud** [comment]
yes, it is possible, and we're already doing it

**Comment by Fabioamd87** [comment]
it's on development or it's working right now?

**Comment by Sbte** [comment]
Also, read this: http://blog.emesene.org/p/report-issues.html

**Comment by Fabioamd87** [comment]
it works, with that trick.

the problem is if I chose a system image, the current is not saved in "used" tab...

**Comment by c10ud** [comment]
working right now since...forever (? read: emesene-2.11.x)

2011/8/23 Fabioamd87
reply@reply.github.com:

**Comment by Fabioamd87** [comment]
I've made some tests now seems work (also in both direction) sorry for the inconvenience.

ps: about the problem that I told you about?
