### ISSUE TITLE
Error when trying to open debug window

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#799]
I'm getting this error when i try to open the debug window

> Traceback (most recent call last):
> File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/MainMenu.py", line 240, in <lambda>
>    lambda *args: self.handler.on_debug_selected())
>  File "/Applications/emesene.app/Contents/Resources/emesene/gui/base/Handler.py", line 200, in on_debug_selected
>    self.debug_window = DebugWindow(debug_close_cb)
>  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/DebugWindow.py", line 36, in **init**
>    self.store = DebugStore()
>  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/DebugWindow.py", line 168, in **init**
>    self.on_message_added(message)
>  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/DebugWindow.py", line 177, in on_message_added
>    self.append([message.name, message.msg.strip(), message.levelno, message.created])
> TypeError: value is of wrong type for this column

**Comment by c10ud** [comment]
ouch, difficult to debug -- i'm not getting this :S

**Comment by ghost** [comment]
Think i've found the problem. I was using a new gtk bundle. The old one doesn't throw the error.

**Comment by c10ud** [comment]
ok not an emesene-issue then :)

**Comment by c10ud** [comment]
if you need help just ask (if we can do something tho)

**Comment by ghost** [comment]
I'll explain the problem i've got:

As you know gtk is not native to OS X, so i have two options 1. Compile my own 2. Use a prebuilt package

Up until emesene 2.11.7 i was using my own compiled one, but emesene was bound to crashing, so i switched to a prebuilt one from 0install.net

This new gtk throws the above error and it does not read os x system pics properly for the avatars

So i have a dilemma of which gtk to use. The stable one with a few issues or fully working unstable one?

**Comment by c10ud** [comment]
well, assuming you can build your pygtk version that should be better -- if you use some stable version (maybe you got some unstable code from git?)

the problem with this 0install version could be some api/abi that changed..but if we don't know in detail it's difficult to add eventual workarounds
