### ISSUE TITLE
Error upon deleting oims

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#801]
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 519, in event
    self._dispatch(method_name, *args[:-1])
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
TypeError: on_oim_messages_deleted() takes exactly 1 argument (2 given)

**Comment by c10ud** [comment]
api changed? please check

**Comment by c10ud** [comment]
well adding an arg to the callback in worker/papyevents should do the trick

some on_oim_message_deleted(self) should become on_oim_message_deleted(self, *args=None) so we keep backwards compat

**Comment by Sbte** [comment]
It's the other way round. It takes 1 instead of 2

**Comment by Sbte** [comment]
Probably due to this

http://cgit.freedesktop.org/papyon/commit/?id=450ac347abd6ac0bf719fa9110b79ae80d14c23a

**Comment by Sbte** [comment]
Ok, it's just lfrb trying to code c++ in python. Move along people, there's nothing to see here

**Comment by c10ud** [comment]
ololol LMAO

**Comment by Sbte** [comment]
c10ud, once this is implemented properly, we should probably check if all oims were received and removed properly? Because that's what lfrb is trying to allow us to do I think.

**Comment by c10ud** [comment]
i'd rather apply the "don't care" concept in that callback..if they're
not removed now, they will on next login (sometimes happens also with
other clients) so..

2011/8/25 Sbte reply@reply.github.com:

**Comment by marianoguerra** [comment]
now I understand the papyon code better..

**Comment by c10ud** [comment]
cool thing is my patches waiting in indefinite queues and that stuff going in without a single feedback

**Comment by c10ud** [comment]
"fixed" in our branch, i hope it will go upstream... anyway we need to make our OIM handler accept that extra argument that's now present
