### ISSUE TITLE
Ubuntu Tray Icon

### ISSUE THREAD

**Issue by dancross** [emesene/emesene#803]
When i launch Emesene the tray icon (indicator) should launch too. Even after i set it in settings it doesnt start.

**Comment by manuargue** [comment]
ubuntu version?

in my ubuntu 11.04 with gnome classic runs without problems..

**Comment by c10ud** [comment]
new ubuntu versions blacklist gtk trayicons for all programs except a few (skype, ..)

**Comment by Mystro256** [comment]
@dancross look up how to white-list tray icons if you don't like the indicator tray or message menu tray options.

But as c10ud said, it's blacklisted by default ;)

**Comment by dancross** [comment]
Oh wow you guys are fast to answer:D thanks

**Comment by dancross** [comment]
My bad iam using Ubuntu 11.04 with Unity 2D
