### ISSUE TITLE
Tray icon doesn't seem to use the right icon

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#804]
According to Ariel, the tray should use logo.png (located in themes/images/_themename_/panel) as the tray icon when emesene is not logged in. AS well, it would make sense for this to be the intended behaviour none the less (to make it theme-able).

Although changing logo.png doesn't seem to change the tray icon. In fact, I also tried changing the default theme (/usr/share/emesene/themes/images/default/panel/logo.png) but to no avail.

**Comment by Sbte** [comment]
It uses

/usr/share/emesene/themes/images/default/logo.png

is there a reason not to use this one but the other one? Because otherwise the panel one can probably be removed...

**Comment by Mystro256** [comment]
Oh I see, that makes sense why it wasn't working.

The issue with using that one is that it is used as the logo everywhere, not just as a tray icon.
A theme may need the denotion between a "offline/logged-out" tray icon versus the logo.

For example, I want to make a theme to use gnome style icons to integrate emesene into gnome-shell; there's an available, busy, away, idle, invisible and offline. I'm trying to make the tray set to the offline icon when emesene isn't signed in, but not replace the emesene logo in every other location it's used.

Also, does /usr/share/emesene/themes/images/default/tray.png have a use? Or is that also not used at all?

**Comment by Sbte** [comment]
If you want to figure things like those out, just Ctrl+f in ImageTheme.py and ImageThemes.py. That's what I'm doing anyway ;)

Anyway, that seems like a good reason, and it's quite easy to fix, so can you do it? You just have to add it in ImageThemes.py and ImageTheme.py and then use it in TrayIcon.py. Just do what's already done there for the other panel files.

**Comment by Mystro256** [comment]
Sure, I'll make the necessary modifications, but I'll have to look into it tomorrow evening when I'm at home.

**Comment by Sbte** [comment]
Great!

**Comment by c10ud** [comment]
can you try printing the file name when it's set?

2011/8/25 Mystro256
reply@reply.github.com:

**Comment by c10ud** [comment]
bad, bad github that doesn't send followups to my email..

**Comment by c10ud** [comment]
i think in the past trayicons preferred the panel/logo.png over the logo.png but only if that icon was avail... i think i implemented that myself, could have gone or something like that btw, not really sure (?)

also: when you're not logged in, theme is the default one because you don't have the user-defined preferences yet (iirc that's the behaviour) so it's not a bug...?

**Comment by pepeleproso** [comment]
This patch should solve the issue, I have no time this week, so if it's ok please cherry-pick
https://github.com/pepeleproso/emesene/commit/0c5b15377fbbeb00700fe92f19c18cf93da0a13f

**Comment by c10ud** [comment]
great, i'll pull it in case of positive feedback

2011/8/26 pepeleproso
reply@reply.github.com:

**Comment by Sbte** [comment]
Well, it won't work indeed, because it doesn't load user-set preferences.

I had an idea though. What if we load the config of the last logged in user at startup, and change it upon login?

**Comment by c10ud** [comment]
i think all apps have their brand and stuff, why can't we keep ours
when users are logged out? :D

2011/8/26 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
It's not only for this, but also for actually loading the tray icon. Atm, since we can't destroy the messaging menu entry, Ubuntu users will have a bugged messaging menu if they choose a different tray icon. 

Also, this would allow us to load different extensions on start, which means more freedom.

**Comment by c10ud** [comment]
well they're not supposed to choose anything but the mess-menu, since
ubuntu is designed that way

2011/8/26 Sbte reply@reply.github.com:

**Comment by Mystro256** [comment]
@c10ud Haha, well as much as there's branding and all that, some may want to make a mono-theme or something that make it look a little more like their system theme. I have gnome-shell with the default and the icon on the panel (rather than the hidden notification bar). The emesene default logo looks odd with all the black and gray on the panel, and I want to modifying the default theme, especially every time I update/install emesene ;)

I think Sbte's idea is good. Although, how bout have it per account, where the theme is loaded when an account is chosen from the "Remember Me" list? (ie when it would stick a remembered password into the password box)

**Comment by Sbte** [comment]
Mystro, no. We need the extensions as soon as we load emesene. Otherwise it's useless to do this.

**Comment by Mystro256** [comment]
Well I don't disagree with loading the extensions, just merely suggesting an idea for themes in particular
