### ISSUE TITLE
file transfer error

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#805]
when trying to transfer a file from WLM -> emesene for the first time it works fine.
but for the second file or later there is just a desktop notification and no accept button or any thing appears, and there is an error:

[23:08:41 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {41D3E74E-04A2-4B37-96F8-08ACDB610874}
/home/ammar/emesene/emesene/gui/gtkui/FileTransferWidget.py:69: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)
 btw I'm using git version.

**Comment by c10ud** [comment]
that error is because papyon doesn't support the "Share photo"
functionality -- other than that are you sure you actually received a
second "real" file transfer request? because if it's share photo, we
cannot handle it because of papyon..

2011/8/25 ammarabdulsalam
reply@reply.github.com:

**Comment by ammarabdulsalam** [comment]
after trying to share photos.
I have tried to receive files via file transfer, one at a time,
the first one received successfully, but couldn't receive the others.

**Comment by c10ud** [comment]
well, if you have more debug on the file transfer issue we can see if there's something wrong 

as for the share photo, unfortunately we cannot do anything

**Comment by ammarabdulsalam** [comment]
this is a a debug window when I tried to send the second file
(14:07:55) papyon.transport:>>> PNG
(14:07:55) papyon.transport:<<< MSG xxxxxxxxx@hotmail.com Ammar 248

```
P2P-Src: 'xxxxxxxxx@hotmail.com;{39adc5af-1efe-4d5c-8ebf-7dbd2e9cfcaf}'\r\n
P2P-Dest: 'xxxxxx@live.com.au;{c874fbff-390c-4137-a8f8-2aa27ee78773}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (1250 bytes)]
```

(14:07:55) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0x7a90393a: blob 6, SLP Message
    INVITE MSNMSGR:xxxxxx@live.com.au;{c874fbff-390c-4137-a8f8-2aa27ee78773} MSNSLP/1.0\r\n
    To: msnmsgr:xxxxxx@live.com.au;{c874fbff-390c-4137-a8f8-2aa27ee78773}\r\n
    From: msnmsgr:xxxxxxxxx@hotmail.com;{39adc5af-1efe-4d5c-8ebf-7dbd2e9cfcaf}\r\n
    Via: MSNSLP/1.0/TLP ;branch={F37FE606-1C13-4EAB-BA73-064603329072}\r\n
    CSeq: 0 \r\n
    Call-ID: {778C0449-E1A4-4BE6-AF73-FBFB269EEAFF}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 882\r\n
    \r\n
    EUF-GUID: {5D3E02AB-6190-11D3-BBBB-00C04F795683}\r\n
    SessionID: 631252680\r\n
    AppID: 2\r\n
    RequestFlags: 16\r\n
    Context: PgIAAAIAAACP3g0AAAAAAAEAAABhAGgAbgBkAF8AbgBvAHUAcgBfADIAMgA5ADMANQBfAGIAdQBzAGkAbgBlAHMAcwBfAHAAbABhAG4AXwBjADMAIABfAHMAMAA5AF8AZQBjAHAALgByAGEAcgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
(14:07:55) papyon.transport:<<< MSG xxxxxxxxx@hotmail.com Ammar 247

```
P2P-Src: 'xxxxxxxxx@hotmail.com;{39adc5af-1efe-4d5c-8ebf-7dbd2e9cfcaf}'\r\n
P2P-Dest: 'xxxxxx@live.com.au;{c874fbff-390c-4137-a8f8-2aa27ee78773}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (128 bytes)]
```

(14:07:55) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0x7a903e14: blob 6, SLP Message
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n
    \r\n
    \x00
(14:07:56) papyon.transport:<<< QNG 43

**Comment by c10ud** [comment]
wait, you used emesene to send to wlm?

2011/8/26 ammarabdulsalam
reply@reply.github.com:

**Comment by ammarabdulsalam** [comment]
no I have used wlm to send to emesene
wlm -> emesene

**Comment by c10ud** [comment]
which emesene version? can you try current git master with updated papyon submodule?

to update the submodule just run git submodule init && git submodule update from emesene root directory

**Comment by ammarabdulsalam** [comment]
I'm using 2.11.8-devel (git version) and updated to the latest papyon
the same thing but with this error for the first file:
/home/ammar/emesene/emesene/gui/gtkui/FileTransferWidget.py:69: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.pack_start(self.menu)

**Comment by arielj** [comment]
@ammarabdulsalam, can you try with latest git? reopen the issue if it's still not working
