### ISSUE TITLE
Can't receive custom emoticons from Pidgin

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#806]
I can't receive custom emoticons sent by a contact using Pidgin, tried also with two of my accounts on pidgin.

I don't know if it's our fault or papyon's, there no log of failed or successful download of the msnobj (neither download_ok or download_failed is called in the worker after the request).

Maybe papyon can't download it and we are not logging that fail?

**Comment by c10ud** [comment]
with papyon-git should work, are you using it?

git submodule init && git submodule update in emesene root

2011/8/26 arielj
reply@reply.github.com:

**Comment by arielj** [comment]
Yes, with  submodule update it now works! ;)

nothing to see here
