### ISSUE TITLE
Plugins/themes downloader

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#807]
About the plugin/themes downloader:

I currently moved it to the plugin tab, but c10ud doesn't like that, so I'll revert it tomorrow. What do you all think? Where should it go?

c10ud suggested:

Download tab -> tabview with plugins and themes.

I personally think it might be better to integrate it as a tabview in the plugins and themes tabs. 

Actually I prefer the way it is now, to prevent duplicate work, and because I think it's neat, but c10ud doesn't like it..

Please give your opinions, so I won't waste another day implementing something useless. Thanks.

**Comment by marianoguerra** [comment]
I think this should be basic functionality of emesene, downloading
plugins/themes is default on firefox and I didn't heard anyone
complaining about that :)

**Comment by Sbte** [comment]
mariano, true, but where should it be?

**Comment by pepeleproso** [comment]
I like the new plugins tab :)
All plugins stuff it's in one place, so people didn't have to go to diferent places.

**Comment by astagi** [comment]
On Sat, Aug 27, 2011 at 6:29 PM, Sbte
reply@reply.github.com
wrote:

> About the plugin/themes downloader:
> 
> I currently moved it to the plugin tab, but c10ud doesn't like that, so I'll revert it tomorrow. What do you all think? Where should it go?
> 
> c10ud suggested:
> 
> Download tab -> tabview with plugins and themes.
> 
> I personally think it might be better to integrate it as a tabview in the plugins and themes tabs.
> 
> Actually I prefer the way it is now, to prevent duplicate work, and because I think it's neat, but c10ud doesn't like it..
> 
> Please give your opinions, so I won't waste another day implementing something useless. Thanks.

I like c10ud idea, but why don't let tabs like were before?? ^^ it's
easier for us and for users.. I saw the plugin tab today, was very
confused :P just my opinion ^^

p.s.: I did some change hope to haven't broken anything... at the
moment download is blocking, I'll make it non-blocking and with a
graphical response soon...

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/807

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by manuargue** [comment]
I think the way it is now is better, because you can manage (install/download/start/stop) the plugins in one tab. But, the installed plugins should be distinguished from uninstalled to avoid confusion.

As a suggestion, would be useful show the plugin description below the name.

**Comment by Sbte** [comment]
@manuargue, that's not possible with the current implementation, because we'd have to download the files to know the description, but the purpose of this is that the user can select the files to download, so that doesn't really work. I think we need a different file in every plugin's folder for this.

@4ndreaSt4gi Not in this way, because it's more tabs than necessary. And the preferences window is already a mess. So let's do it right this time ;)

Seems like 3 out of 5 people (manuargue, pepe and me) actually like the current way, so maybe we could think of a way to improve it? It's currently a bit messy, I agree. 

Maybe put something like 'Installed' and 'Available for download' at the top of those plugins, like it's currently done with the groups in the contact list?

Also, maybe we could put the combo box in a different place or rearrange the buttons? 

If we can't think of something, we could just go back to the way andrea implemented it?

**Comment by pepeleproso** [comment]
When a plugin isn't installed preferences button should be replaced by download.

**Comment by Sbte** [comment]
Good one!

**Comment by manuargue** [comment]
To make more clean the interface I think:
- move the combo box to select the source (community|supported) and the refresh button to the left of the window.
- if the plugin is not installed, make it insensitive and dont display the preference button (like pepe said). Otherwise, make it sensitive and show the preference and start/stop button (at the right of the window).

plugin description:
instead of making a separate file with the plugin description, you can fetch the raw data of the Plugin class, and parse it to obtain the _description attribute.

**Comment by Sbte** [comment]
manuargue, already did the preference/download merge.

for the select source stuff i need to override the show_all method i think. I'll do that in a minute.

About the description, we need to fetch the raw data yes, but I'd rather see that implemented in a separate file, where we also state the version of emesene needed to run the plugin. Then we have to download less -> faster, and makes it easier to look up, because we should make it such that json can read it.

Anyway, feel free to get involved. I'm leaving in a few minutes ;)

**Comment by Sbte** [comment]
Ok, all done but the description fetching. 

@c10ud, @4ndreaSt4gi, is this less confusing? Or do you still like the old way better?

**Comment by marianoguerra** [comment]
On Sat, Aug 27, 2011 at 10:31:32AM -0700, manuargue wrote:

> I think the way it is now is better, because you can manage (install/download/start/stop) the plugins in one tab. But, the installed plugins should be distinguished from uninstalled to avoid confusion.

a filter to hide non installed plugins would be cool too

**Comment by Sbte** [comment]
Mariano, not sure what you mean, but did you look at the current implementation? I think it's already there

**Comment by c10ud** [comment]
pulled, and looks better now -- i'm fine with whatever you choose

**Comment by Sbte** [comment]
Ok, so now we need some sort of update mechanism...

**Comment by pepeleproso** [comment]
maybe a json file with plugin info like gnome-shell uses http://git.gnome.org/browse/gnome-shell-extensions/tree/extensions/example/metadata.json.in

**Comment by Sbte** [comment]
Exactly my idea ;)

I'd put:
{
'emesene version': minimum version required to run the plugin version,
'description': description,
'authors': [author list],
}

and use the github api to detect if there were any commits to the plugin. We must remember to update this file when updating a plugin though. Otherwise stuff will break...

The other way is to include a version in the dict and check if that changed. That at least makes it less likely people forget to update the emesene version field.

Opinions?

**Comment by astagi** [comment]
Yes ^^ I like the second idea...ti's easier to implement and we make sure that when the code version number is incremented we have a stable version of that plugin ( hope will be tested before increment ^^ ).. maybe the last commit can break stuff..

**Comment by Sbte** [comment]
andrea, will you do it? You already implemented the download part anyway ;) Or are you still working on having downloads in a different thread?

**Comment by astagi** [comment]
Yep I'm working on download part at the moment ^^ but there's nor problem I can do that ^^ let's decide the structure of the dict and implement it in all extensions and downloader... So sbte propose that

{
'emesene version': minimum version required to run the plugin version,
'description': description,
'authors': [author list],
'code version' : integer incremented after any stable change
}

For me it's ok, download manager have only to parse the local emesene and code version with the remote ones..

**Comment by Sbte** [comment]
well, i'd leave the 'code version' or just 'version' as a string that can be incremented in various ways, because people like that. Versions like '0.3.6.2.6.7.8.3.21.1.45.78.86.5.45'

Should be easy with a simple split('.')

Also, maybe we should group them together on the top so it's even harder to miss the emesene version change?

{
'version' : string version
'emesene version': minimum version required to run the plugin version (current devel should always work),
'description': description,
'authors': [author list],
}

**Comment by astagi** [comment]
On Sun, Aug 28, 2011 at 5:44 PM, Sbte
reply@reply.github.com
wrote:

> well, i'd leave the 'code version' or just 'version' as a string that can be incremented in various ways, because people like that. Versions like '0.3.6.2.6.7.8.3.21.1.45.78.86.5.45'
> 
> Should be easy with a simple split('.')

Uhm you let too much freedom in this way ^^ For example if someone
write for the first version 1.0.0 and for the second 1.1 parsing these
numbers after splitting by '.' will result

11 and 100 so the first version is the newest for the parser...
Android manifest files has two fileds: versionCode and versionName..
say whatever you want in versionName but put an incremental number in
versionCode ^^

> Also, maybe we should group them together on the top so it's even harder to miss the emesene version change?
> 
> {
> 'version' : string version
> 'emesene version': minimum version required to run the plugin version (current devel should always work),
> 'description': description,
> 'authors': [author list],
> }

ok

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/807#issuecomment-1924283

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by Sbte** [comment]
Not really,

You just do

```
old_version = old_version.split('.')
new_version = new_version.split('.')
for i, number in enumerate(new_version):
    if i < len(old_version) and int(old_version[i]) < int(number):
        new version is new!!!
```

**Comment by astagi** [comment]
oh I didn't think about a character by character parsing ^^ yeah it
works... ok let only the version as a string... I'll implement it
asap... for the moment update plugins and themes with the json file..

thank you ^^

On Sun, Aug 28, 2011 at 6:16 PM, Sbte
reply@reply.github.com
wrote:

> Not really,
> 
> You just do
> 
> ```
> old_version = old_version.split('.')
> new_version = new_version.split('.')
> for i, number in enumerate(new_version):
>    if i < len(old_version) and int(old_version[i]) < int(number):
>        new version is new!!!
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/807#issuecomment-1924384

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by marianoguerra** [comment]
On Sun, Aug 28, 2011 at 07:52:24AM -0700, pepeleproso wrote:

> maybe a json file with plugin info like gnome-shell uses http://git.gnome.org/browse/gnome-shell-extensions/tree/extensions/example/metadata.json.in

I have a crazier idea, the good thing about my idea is that you don't
have to write the same info twice and we can still have one file
plugins.

it involves using the ast module to load the content of the main plugin
module and parse the constants in the class.

it may sound a little hacky, I will see if I can do a prototype of that.

let me know what you think

**Comment by Sbte** [comment]
I think that it's better to keep this in a small file. If we have more plugins, we don't want people with a slow connection to wait ages for the plugin tab to load.

**Comment by marianoguerra** [comment]
On Sun, Aug 28, 2011 at 08:26:39AM -0700, 4ndreaSt4gi wrote:

> Yes ^^ I like the second idea...ti's easier to implement and we make sure that when the code version number is incremented we have a stable version of that plugin ( hope will be tested before increment ^^ ).. maybe the last commit can break stuff..

another idea, have a script at the root of the plugin folder that walks
through the plugins and extracts the metadata from them and builds a
global index in the root of the plugins, it can be a json file to
download and extract.

in this way we can set up a post commit hook or run it when we update a
plugni to generate a unique index of the plugins in that folder

in this way we have to download only one file and is generated
automatically.

thoughts?

**Comment by Sbte** [comment]
Oh, yes, I always forget about hooks. Might be a good idea, but it still requires the emesene variable to be set within the file. The version could be auto incremented by a pre-commit hook

**Comment by c10ud** [comment]
currently we're already using somekind of versioning in
emesene/gui/base/Handler.py, mind porting that hacky interface to
something stronger while you're at it? :D

2011/8/28 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
Now I think I know why I forget about hooks. They are not shared in the git repo right? So there's no point unless we have someone watching the plugins repos at all time :P

Can anyone confirm that? Or did you have something else in mind mariano?

**Comment by marianoguerra** [comment]
On Sun, Aug 28, 2011 at 8:13 PM, Sbte
reply@reply.github.com
wrote:

> Now I think I know why I forget about hooks. They are not shared in the git repo right? So there's no point unless we have someone watching the plugins repos at all time :P

didn't knew that

> Can anyone confirm that? Or did you have something else in mind mariano?

that was my idea :D

maybe small json files is the way to go

I like the idea, but I'm afraid about the out of sync between the
plugin and that file.

**Comment by Sbte** [comment]
Well, if the file is not updated, the script won't update the plugin, so no big deal. And everyone with push rights can just check if people don't forget to edit that file.

**Comment by Sbte** [comment]
Ok ,now about the themes tab:

I wanted to integrate it in the same way as with the plugins tab (with radio buttons, so you can select only one theme), but I think if I would do that, it would be a bit full. I thought maybe we can use a tabbed view with four tabs (one for every theme). That'll make it easier to integrate. Problem with this is that it is not all on one page. it does allow us to add descriptions and possibly previews though.

So, what do you think? Change it or leave it?

**Comment by arielj** [comment]
I like everything in one screen like it is now.

Description could be inside a tooltip, we save some space there and we have that information.
We can also have one "Download" button at the right of each theme section.
The "Supported" combo and the "Refresh" button would affect all sections.

**Comment by Sbte** [comment]
Ok, integration of the themes tab is done now, so tell me if you like it.

TODO is updating stuff

**Comment by zipatei** [comment]
Why refreshing extensions in themes, open 3 windows? Its expected?

Click cancel and Typeerror:

TypeError: _end_progress_cb() takes exactly 2 arguments (3 given)

**Comment by Sbte** [comment]
Fixed that error, and implemented canceling. Updating is still left as TODO

**Comment by c10ud** [comment]
so, this implementation is missing what?

**Comment by Sbte** [comment]
Updates.
