### ISSUE TITLE
Media Message

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#810]
I think now emesene's music plugin request media message in every 10 seconds. But I think it is too long. Can you decrease it to 5 sec?

**Comment by Sbte** [comment]
Should be a preference option. Should be really easy to implemented.

Next time, report plugin stuff here: https://github.com/emesene/emesene-supported-plugins/issues

**Comment by c10ud** [comment]
i think waking up less is better so 10 secs is fine, also, plugin "issue"
