### ISSUE TITLE
view profile

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#814]
is possible?

**Comment by Sbte** [comment]
What?

**Comment by Fabioamd87** [comment]
I thought it was clear to understand sorry.

right click on a contact and choose view profile (foto, info, etc..)

**Comment by ghost** [comment]
@Fabioamd87
right click contact -> View Information

**Comment by Sbte** [comment]
Or click their avatar in a conversation. Is that what you meant?

**Comment by Fabioamd87** [comment]
no, I mean msn profile.

**Comment by Mystro256** [comment]
I think he means MSN Spaces or whatever they're called these days

**Comment by Fabioamd87** [comment]
not spaces, profile... go to hotmail.com and login. you can see your profile.

**Comment by Mystro256** [comment]
Oh yeah, I took at look, they used to be called spaces before microsoft remade/chaged everything a while back. None the less, there current is not integration with profiles in emesene, although you can request it if you would like.

For clarification to others, the profiles he refers to is located on this website: http://profile.live.com
The profiles seem to follow the pattern of "http://profile.live.com/cid-" + some id number in what seems to be hex

**Comment by Fabioamd87** [comment]
the profile can be accessible also by typing the user email in the browser address bar, but I don't remember how.

**Comment by c10ud** [comment]
http://members.msn.com/default.msnw?mem=<<contact-email>>

if someone wants to implement it, it's just a matter of checking if the session is 'msn' and if so add that link somewhere

**Comment by Fabioamd87** [comment]
we can do like in the original client, there is "view..." menu and a submenu with "information" and "profile"

**Comment by c10ud** [comment]
sure, go ahead

**Comment by arielj** [comment]
We can go to msn profile if session is MSN, to facebook profile if it's facebook, what about gtalk? any idea?

**Comment by Fabioamd87** [comment]
google+ profile?

**Comment by Mystro256** [comment]
@Fabioamd87 That would make the most sense lol

**Comment by arielj** [comment]
Does anyone know how to get the id of the contact for the profile links using facabook or gtalk api?

on facebook is something like: http://www.facebook.com/profile.php?id=xxxxxxxxxx (10 digits)
on google+ is something like: https://plus.google.com/u/0/xxxxxxxxxxxxxxxxxxxxx (21 digits)
on msn is easy, just: https://profile.live.com/email@host.com

**Comment by Fabioamd87** [comment]
if the contact have a facebook nickname the profile can be reached also with facebook.com/username

**Comment by arielj** [comment]
@Fabioamd87: we should just use the id, other things can change, the id will always be the same

**Comment by marianoguerra** [comment]
maybe implement get_contact_profile_id and get_contact_profile_url in session and let every protocol implement it? if they return None then it means they don't know it or it's not supported.

what do you think?

PS: hi!

**Comment by arielj** [comment]
yes, that's something like what I was thinking, but I don't know how to get that id ussing xmppy/jabber/whatever/facebookapi, the contact object for gtalk contacts has "identifier = 0", haven't tryied facebook since I can't login

**Comment by pepeleproso** [comment]
while in theory this is simply, with jamesaxl spent two days and we couldn't find the msn id, and the email url didn't work anymore. Same for google+, we need to use it's own API to get that id.
Facebook is different because we already use it's API, but I don't think implement this for facebook only is what we want.
I'm closing this for now, until we can find a way to retrieve those profiles.
