### ISSUE TITLE
Message-box doesn't clear & message doesn't display on window

### ISSUE THREAD

**Issue by hiunnhue** [emesene/emesene#815]
- Message box in conversation window does not clear after sending a message.
- The message is sent successfully. Contact receive the message.
- The message does NOT display on the chat window.
  
  Traceback (most recent call last):
    File "/home/gecko/emesene/emesene/gui/gtkui/TextBox.py", line 229, in _on_message_send
      self.on_send_message(self.text)
    File "/home/gecko/emesene/emesene/gui/base/Conversation.py", line 354, in _on_send_message
      message, cedict, self.emcache.path, self.first)
    File "/home/gecko/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 221, in send_message
      self.view.add_message(msg, message.style, cedict, cedir)
    File "/home/gecko/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 111, in add_message
      html = self.theme.format_outgoing(msg, style, cedict, cedir)
    File "/home/gecko/emesene/emesene/gui/base/AdiumTheme.py", line 131, in format_outgoing
      return self.replace(template, msg, style, cedict, cedir)
    File "/home/gecko/emesene/emesene/gui/base/AdiumTheme.py", line 165, in replace
      template = template.replace('%message%', msgtext)
  UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 306: invalid continuation byte

**Comment by arielj** [comment]
What was the message? was there any weird character?

**Comment by hiunnhue** [comment]
No, I simply sent "sorry".

I changed the extention to Output Text, and it didn't have this problem.

**Comment by Sbte** [comment]
Can you reproduce it then? Because this error should only occur when you're sending invalid unicode text

**Comment by c10ud** [comment]
> Message box in conversation window does not clear after sending a message.

is this still happening?
which OS are you running?

**Comment by hiunnhue** [comment]
Yes, this is still happening.

Version: 2.11.8-devel from git
OS: Xubuntu 11.04 (Xfce 4.8)
Language: English

Steps:
1. Remove old emesene from git.
2. Remove /home/gecko/.config/emesene2.
3. Get a new copy from git again.
4. Open a chat window and send some words, such as "sorry" or "aaaaaa".
5. Contact got my message, the text field doesn't clear, and the chat window shows nothing.
6. Change from Adium Output to Output Text.
7. Send a message again.
8. Text field clear, and the message shows on the chat window.

PS. I also use the 2.11.7 from PPA, and it works just fine.

**Comment by Sbte** [comment]
Maybe it's your name containing weird characters? Could you try with a different name? Here everything works fine...

**Comment by c10ud** [comment]
@hiunnhue: is the debug exception still the same? also, are you using some specific locale or language other than english?

**Comment by hiunnhue** [comment]
@Sbte:
You're right, it's my nick name...

But it is really weird, because I didn't use any special character... just Chinese words...

You may copy, past, and try this "MSN你你我，他他她她" (MSN you you I, he he she she). If you delete ANY single word, "你" or "他" or "MSN" for example, then the problem is gone. And Japanese characters are the same. "MSNああいうええおお".

@c10ud:
You mean the text on terminal? Yes, they are almost the same. Just with a little difference in the very end.

I'm also using Traditional Chinese and German. 

Hier is another information on terminal, almost the same:

```
Traceback (most recent call last):
  File "/home/gecko/emesene/emesene/gui/gtkui/TextBox.py", line 229, in _on_message_send
    self.on_send_message(self.text)
  File "/home/gecko/emesene/emesene/gui/base/Conversation.py", line 354, in _on_send_message
    message, cedict, self.emcache.path, self.first)
  File "/home/gecko/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 221, in send_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/home/gecko/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 111, in add_message
    html = self.theme.format_outgoing(msg, style, cedict, cedir)
  File "/home/gecko/emesene/emesene/gui/base/AdiumTheme.py", line 131, in format_outgoing
    return self.replace(template, msg, style, cedict, cedir)
  File "/home/gecko/emesene/emesene/gui/base/AdiumTheme.py", line 165, in replace
    template = template.replace('%message%', msgtext)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 308: invalid continuation byte
```

**Comment by Sbte** [comment]
Found it. It's because utf-8 is multibit, and we just break it after a few bits like this: 

```
msg.display_name[0:DISPLAY_NAME_LIMIT]
```

which is in your case in the middle of a char.

**Comment by c10ud** [comment]
good catch!

**Comment by hiunnhue** [comment]
Thanks a lot for your effort!! :-)
