### ISSUE TITLE
Shrink convo toolbar option - tiny tweak needed?

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#816]
In   Preferences> Conversation window

There is a tickable-box option called 'Shall conversation toolbar'. I tried turning it on and off and i think it was meant to read 'Small conversation toolbar'. 

Personally, in keeping with the grammar of the options above it (beginning with verbs in the imperative as opposed to an adjective), i think it should say something like 'Shrink conversation toolbar' and be moved to just below 'Show conversation toolbar' (because they're more related options), swapping places with 'Show tabs popup menu' - what exactly does that do option do anyway? What is the 'tabs popup menu'? :S

Tiny tweak i know but every little improvement is an improvement, right? ;)

**Comment by Mystro256** [comment]
What translation are you using? In English it reads just fine.

**Comment by c10ud** [comment]
you can improve translations here https://translations.launchpad.net/emesene/+translations

**Comment by arielj** [comment]
"Tab's popup menu" is a menu that popups when you right click a tab in a
tabbed conversation. The menu shows a list of all tabs as "Page 1" "Page 2"
etc and you can change tabs there.

2011/8/30 Antonius-git <
reply@reply.github.com>

**Comment by Antonius-git** [comment]
Thanks :) I found it at translation 245 and have submitted 'Shink conversation toolbar' in place of the nonsensical 'Shall conversation toolbar' in "Current English (United Kingdom)". 

@arielj Ohhh, thanks for clearing that up! :D

Issue resolved then :)
