### ISSUE TITLE
Plugins Preference error

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#824]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/PluginWindow.py", line 114, in on_config
    pluginmanager.plugin_config(name, self.session)
  File "/home/andre/emesene/emesene/pluginmanager.py", line 216, in plugin_config
    return self._plugins[name].config(session)
  File "/home/andre/emesene/emesene/pluginmanager.py", line 137, in config
    self._instance.config(session)
  File "/home/andre/emesene/emesene/plugin_base.py", line 48, in config
    raise NotImplementedError()
NotImplementedError

**Comment by Sbte** [comment]
We can probably make this a pass, because plugins should be allowed to have no preference window.

**Comment by c10ud** [comment]
or, dialog info "this plugin has no config"

**Comment by ghost** [comment]
Or just grayout/unenable the preference button. Like what firefox does with the option button on plugins.

**Comment by Sbte** [comment]
I like that last one.

**Comment by shuhaowu** [comment]
Why don't I just hide it..

Actually, if you need to hide it, you need to rewrite the plugin_base to have a boolean somewhere that tells the plugin manager if there's an config or not.

**Comment by Sbte** [comment]
Insensitive is nicer

**Comment by shuhaowu** [comment]
> Insensitive is nicer

Alright then, I'll branch and see if I could add this attribute.

**Comment by shuhaowu** [comment]
Change is now merged to the master tree.
