### ISSUE TITLE
Smaller contact list (interface)

### ISSUE THREAD

**Issue by shokora** [emesene/emesene#827]
I recently updated to emesene 2.0 and while most of the differences are quite ok one thing that keeps irritating me is the huge amount of space names take up in the contact list. Even if you set the contact avatar to 18px there is a lot of space between two contacts. Could you add an option so you can also edit this and make it nice and tidy again?

**Comment by c10ud** [comment]
i am sorry that you're being irritated, but you just edit the contact template removing newlines and along with 18px contact pictures the list will be very tiny
