### ISSUE TITLE
Download button 

### ISSUE THREAD

**Issue by javijec** [emesene/emesene#828]
Download button does not appear on the tabs "Sound Themes" and "emoticons Themes" option in Theme Preferences

**Comment by shuhaowu** [comment]
What?! i though i fixed this issue.. 

Are you on a slow connection? Are you on the latest git version? 

The buttons are _definitely_ working for me.

**Comment by Soulsuke** [comment]
I can quite confirm this. For me, the download button only shows in the 'Audium Themes' tab. Also, pressing the 'refresh' button causes 4 different "Refresh extensions" windows to pop-up, one above the other. While the first one actually does its work and quits, the other 3 stay in place without actually doing anything, stealing the focus from other emesene2 windows... Pressing the cancel button doesn't work either, while pressing the X icon of the window manager does the trick.

**Comment by shuhaowu** [comment]
I can confirm the 4 refresh. 

![Download button working](http://i.imgur.com/jSvUi.png)

**Comment by Soulsuke** [comment]
Now... This is really weird. I just tried again and... The download button is there. But it does seem to disappear after switching from 'Supported' to 'Community', and switching back doesn't make it appear again. It doesn't disappear for the 'Audium themes' tab though

**Comment by shuhaowu** [comment]
The download/preference button (whatever button in that particular spot) gets shown when the list gets refreshed and it takes a look to see which one is selected. My bet is that when we switch from community to supported, the list doesn't get refreshed.
