### ISSUE TITLE
emesene launches a new instance instead of showing the current one to users, which confuses them (ubuntu unity)

### ISSUE THREAD

**Issue by madjr** [emesene/emesene#829]
When using ubuntu new users will frequently hit the close button in the emesene window (which minimizes to the messaging menu applet).

But since they dont know where it went (unlike with the old always visible system tray icon), they will click on the launcher again to bring it back up, but instead they get a "new instance" and then retype their user-names/passwords again, etc (yes, they actually think they were logged out!)......

i have seen some users do this up to 8+ times with 8+ running instances for the same account.....

Empathy on the other hand, when clicking on either the launcher or the shortcut on the messaging menu, will only pop up the current instance, which is what users are looking for, so they dont have this problem as with emesene.

to open another instance i propose that is only done using the menu or with an right click option in the quicklist on the launcher.

i hope this feedback makes sense with a quick solution that would greatly improve usability of emesene2 in ubuntu (and other distros like linuxmint) or when there lacks a systray

Thanks!

**Comment by c10ud** [comment]
emesene -s is what you want

2011/9/5 madjr reply@reply.github.com:

**Comment by Sbte** [comment]
This is a really difficult issue. I agree in a way that this should be the default when the launcher is used, but I think we can't have any influence on the launcher unless emesene has an opened window. Which isn't the case when you hide emesene...

And if we disable this by default, people can't login with multiple sessions that easily. 

Any ideas are welcome.

**Comment by Sbte** [comment]
Ok, sorry, I tested it in the wrong way. I think we do have access when it's hidden. I'll look if I can change the behaviour of the button.

**Comment by c10ud** [comment]
if unitylauncher: singleinstance(?)

otherwise, it's up to the users

2011/9/6 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
c10ud, then users with natty+ can never use multi instance. And I don't think ubuntu allows changing the behaviour of the unity launcher entry itself. At least the documentation doesn't say anything about it, and ayatana doesn't reply.

**Comment by Sbte** [comment]
Ok, I checked in ayatana, and no one seems to know a way to do this through the launcher API. If anyone has any ideas, or is willing to report this on launchpad as a bug (custom actions for clicking the launcher icon), please do/tell.

**Comment by Mystro256** [comment]
@Sbte have "open new session" on the quicklist perhaps?

**Comment by Sbte** [comment]
Yes, but that doesn't fix the single instance we have to use. The only solution is to enable single instance by default, but that's really annoying for people who want to use multiple instances.

An idea would be adding the -s option to the .desktop file. But other than that I have no clue...

**Comment by Mystro256** [comment]
Well, maybe add another *.desktop file to have one for single instance and the other for multi?

Or perhaps an option in preferences could help... hmmm

**Comment by Sbte** [comment]
Yeah, an option would probably be the best way to do this...

**Comment by madjr** [comment]
wow thanks guys for looking into this issue.

you dont know how important this is, i mean people have been getting so frustrated with this odd behavior that they prefer to use something like ebudy or meebo...

anyway, i have discovered that what people are looking for is something like what the systray icon did: minimize.

i think the launcher icon could act like or substitute the old systray behavior.

You just need to "minimize the app to the launcher" instead of closing/hiding it to the messaging menu.

so the close button would just minimize it by default (like it minimized to systray icon).

and option for more advance users or those who prefer it would be to close/hide to messaging menu.

The 1 instance i proposed earlier is one way to relief the confusion for regular/new users, but as you see there are other ways to do this.

Implement the one that you guys find easier and thanks again!

**Comment by Sbte** [comment]
Minimizing to the launcher isn't probably the right way either, because then the icon doesn't hide from the launcher. And that's what people who don't have emesene locked to the launcher most likely want...

**Comment by madjr** [comment]
yeah that's why there would be an option to close/hide to messaging menu instead of launcher for those that use/prefer that menu.

also is there a way to detect is the user has it locked/pinned on the launcher?

**Comment by Sbte** [comment]
No

**Comment by madjr** [comment]
i would personally prefer it to the launcher specially with the new quicklists and the nice numbers floating on the icon to display info is cooler than the old systray :)

**Comment by Sbte** [comment]
WEll, you have the minimize button for that right? :P

**Comment by ghost** [comment]
This makes me think of Mariano's "crazy idea" (http://lists.emesene.org/pipermail/dev-emesene.org/2011-April/001155.html). Multi-instance with-in a single instance, with opening a new instance of emesene being as easy as opening a new tab in firefox.

**Comment by Sbte** [comment]
syst3m, dream along ;)

**Comment by madjr** [comment]
@syst3mfailur3

haha i thought about that too.

great minds think a like!

(we just suck at coding.... so is better to let the pros handle this :D)

**Comment by madjr** [comment]
Apart from the problem mentioned in the first post (or that users dont know that emesene hides and stays running in the background), there is also another related problem: users dont know how to "log off and quit".

this is due to the global menu also being hidden...

This is a HUGE security risk, because i've found many clients open or some "nice" person from time to time lets me know (i work at an internet cafe, so i see this daily).

This bug report seems to be more about "usability and security issues with emesene in ubuntu 11+"

The problem is more info related of the "new behaviors" than anything else. So, I think that even a small message (alert or tip) upon "first time closing" the main window could help with the issue.

something like this:

-=-==-==
Alert:  Emesene is still running in the background. You can find it in the "messaging menu" |-M-| (<--envelope pic).
Is this what you want to do?
 [yes, hide] [(-) minimize, instead] [(x) log out and quit]
[ ] do not show again.
-==-==-==

or

==-
_YOUR DESIGN HERE_...
==-

**Comment by Mystro256** [comment]
Well clicking on "offline" in the message menu should log a user off, but I'm not sure if Ubunt fixed this yet

**Comment by Sbte** [comment]
@Mystro256 Yes, it logs off when clicking offline. I fixed that in the messaging menu extension that is in Ubuntu 11.10. It only works with current emesene git though. Not 2.11.7.

@c10ud, maybe we could change the .desktop file to use -s for the time being? I still don't think this is the right solution though. Maybe disable it when the unity launcher is present and implement an option in the quicklist?

@madjr, maybe you could request to Ubuntu if they can change the .desktop file, so it gets "fixed" in 11.10 too. The git version won't make it. Or ask the people in ayatana if they can make the launcher entry action overridable.

**Comment by madjr** [comment]
@Sbte

yea, is a pain that the user has to stay with an old version for 6 months unless he/she finds a ppa or similar. But there may be some progress in that regard:
https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/578045

as for .desktop file, i would love to help and submit a bug report, but with my lack of developer knowledge am not sure what to specifically request... same with ayatana, not sure what i would ask for or if i can give them any specific example/case, sorry :/

**Comment by sladen** [comment]
Sorry for the delay in responding to this.  It's really important that issues get reported in the Launchpad bug tracker;  the current list of open bugs is:

  https://bugs.launchpad.net/ubuntu/+source/emesene/+bugs

The current desktop file is in:

  /usr/share/applications/emesene.desktop

It is possible to specify the behaviour and also Quicklist items under Unity.  See examples for 'firefox.desktop' and similar where the common-case is to raise the existing window, and the uncommon case is to open a new instance.  Opening multiple simultaneous instances is more likely to be a power-user option.

For the purposes of having sane defaults, it would probably be better to make the application use a single instance model, unless the user explicitly requests otherwise.  For the Firefox example above, this means that 'firefox -new-window' is execute (either by the user at the command-line, or via a QuickList).

Please do file a bug, both the Masters of the Universe, and the Canonical/Ubuntu Design team would be more than happy to help out and make users' lives easier.

**Comment by Sbte** [comment]
I already filed a bug, and it has been confirmed. Just not against emesene.

**Comment by asvestomix** [comment]
i am a fun of emesene but i found it a bit annoying the way it works with gnome-shell (gnome 3).  Right now i am using empathy until the next version  because i really like the way it is integrated with gnome-shell

**Comment by Mystro256** [comment]
I can agree with you there, maybe a gnome-shell extension could be developed? Or maybe add it in as an emesene plugin? I'm not sure exactly how it works, but I found a gnome-shell extension that works with pidgin: https://github.com/kagesenshi/gnome-shell-extensions-pidgin

**Comment by sladen** [comment]
@Sbte thanks for filing the bug.  Could you paste/link the Launchpad bug number?

**Comment by Sbte** [comment]
https://bugs.launchpad.net/unity/+bug/876710
