### ISSUE TITLE
Need improvement for multichat (needs more information of the contact)

### ISSUE THREAD

**Issue by Mastergatto** [emesene/emesene#832]
Hi folks, I've been using emesene for years, and I've been following you since the birth of this project. Lately I wanted to switch to emesene2, but to be sure I first wanted to try it. My opinion is that emesene2 is a good product, really fast and clean, but still not very usable due to the lack of some of the features that made emesene a great program.

1) I use group conversations a lot to chat with 2 or more friends in the same window, and I find quite unsatisfying the bar that just lists the participants, and the avatar rotation on the right, that doesn't specify to which user each avatar belongs. I believe that in group conversations it's basic to have all the possible informations about the participants, such as the avatar, the e-mail address, and the status message. Is it possibile to have something like Emesene 1 had, with a list on the right showing each participant's nickname, avatar, status message and e-mail?
Also, a few concerns about the current list of participants: what happens of there are a lot of participants? It wouldn't be possible to list all of them. What if two people on my friends list have the same nickname (since many people use their first name)? I wouldn't know which one I'm talking to.

////////////// SKIP /////////////
2) An important thing that Emesene 2 lacks is the option to able/disable sound from the icon on the tray list.
3) When I want to highlight some text from the conversation to copy it, the selection disappears when a new message is received, and the focus goes back to the bottom of the conversation. Is it possible to stop this?
////////////////////////////////

That's all for now, thanks for your attenction.

**Comment by bubuntux** [comment]
I'm working in number 2 :P

**Comment by arielj** [comment]
sorry bubuntux, didn't saw your post, i've already done number 2

**Comment by pepeleproso** [comment]
You can disable autoscroll in preferences. That should fix number 3

**Comment by c10ud** [comment]
1) we're lazy
2) i think it has been fixed upstream, ofcourse if your distro
supports the gtk TrayIcon
3) you have to hax the adium theme, but i may have added a workaround
for that in the past (or not) - or just don't use the adium output

2011/9/5 Mastergatto
reply@reply.github.com:

**Comment by Mastergatto** [comment]
@c10ud: "we're lazy"? I hope you're joking. what kind of answer is that for a developer? Seriously. I can undestand that you don't have much free time for developing, but I really don't accept such a reply. I can assure you that the current bar is severly lacking, because it doesn't show fundamental informations such as e-mail address, (personal) status, and the avatar isn't associated to the user. 

@arielj: Thank you :)

@pepeleproso: Unchecking that option doesn't actually seem to do anything, it behaves exactly as before. I'd disable audium output if I could be able to change the messages layout (giving them a pidginesque style)

**Comment by c10ud** [comment]
sir, even if you don't accept it, that's the truth. i'd also add that
i personally don't care about that modification but i'd like to avoid
being rude.

ofcourse the "patches welcome" principle is always valid

2011/9/6 Mastergatto
reply@reply.github.com:

**Comment by shuhaowu** [comment]
Is group chat really that useful? I just get annoyed when people invites me on MSN as the group chat thing tends to pop up in my face.

Might be something I'll look into, but we shall see if I have time.

**Comment by arielj** [comment]
@Mastergatto, can you split this issue in two different issues (one for 1 and one for 3) so we can keep track if each separated.

**Comment by Mastergatto** [comment]
@arielj: Done.

@c10ud: I'm not good at programming, so at best i'd make a very bad patch... Yet i'd like to "contribute" as every good user should, pointing out bugs and lacks that could compromise the experiences of emesene users. Dear c10ud, if you really care about emesene2, you should consider other users' suggestion to improve emesene2, not ignore them because you don't care about some features, because some others do care.

@ultimatebuster: Unluckily, group conversations are really important if you need to chat with more people at the same time, like in a conference. Maybe you have other priorities, but I hope you'll keep this ticket in mind. Thanks.

**Comment by shuhaowu** [comment]
I believe pidgin works with group chat. You can use that for now until we come up with a new feature. I'm a new emesene developer as well, I'm currently only familiar with the extensions and plugins department, maybe I will be able to code this feature in the future.

**Comment by arielj** [comment]
@Mastergatto, try with latest git, go to preferences > extensions and choose "ContactInfoList" for the category "conversation info"

I plan to add a tooltip for each row showing more info of the contact (pm, email and other things)

What do you think? can we close this issue?

EDIT: done, the tooltip shows the rest of the info

**Comment by Mastergatto** [comment]
@arielj: Awesome job, i really appreciate your work, thank you! :D
