### ISSUE TITLE
Live Messenger Tab in preference

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#833]
You can put the mail alphabetically?

**Comment by Mystro256** [comment]
the mail? I'm sorry I don't understand what you mean

**Comment by ghost** [comment]
I think he means email addresses of contacts in the Allow/Block lists in the Live Messenger tab.

**Comment by Mystro256** [comment]
Oh I see, that makes sense now ;P

**Comment by shuhaowu** [comment]
Implemented. Commit in a moment.
