### ISSUE TITLE
CTRL+C in console

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#834]
^CTraceback (most recent call last):
  File "/home/andre/emesene/emesene/emesene.py", line 763, in on_close
    self.close_session()
  File "/home/andre/emesene/emesene/emesene.py", line 330, in close_session
    for conv_manager in self.conversations:
KeyboardInterrupt

http://effbot.org/zone/stupid-exceptions-keyboardinterrupt.htm

**Comment by c10ud** [comment]
that's related to the fact we don't handle ctrl+c for some reason i
don't really remember. otherwise i would make emesene exit nicely
instead of breaking stuff

2011/9/6 zipatei
reply@reply.github.com:

**Comment by shuhaowu** [comment]
I'll see if I can try to make it gracefully exit without breaking stuff.

Edit: Never mind. I think this is an limitation of PyGTK and Python. 

It's a GUI app, shouldn't need to CTRL+C anyway :P

Source: http://www.mail-archive.com/pygtk@daa.com.au/msg01320.html
Note: The no cleaning up makes it pointless.

**Comment by arielj** [comment]
Didn't we have something that catches ctrl+c on emesene1 with something like "press this 5 times to close emesene"? can't we use that and do something there?

**Comment by c10ud** [comment]
see emesene.py line 152 or so, we are handling them somehow but the thing's not working as expected for some issue i don't remember now
