### ISSUE TITLE
No ClearType font rendering & (seemingly) incorrect fonts on Windows

### ISSUE THREAD

**Issue by Knifa** [emesene/emesene#835]
Hello there.

Just installed emesene 2.11.7 on Windows 7 x64 (entirely clean install, with SP1 updates) and I'm having minor cosmetic issues with the conversation window.

![A screenshot](http://i.imgur.com/WxYSS.png)

Fonts don't appear to be anti-aliased using Windows' ClearType, so fonts that /need/ it like Consolas (my font, in this case) look a bit weird. 

The font used for the timestamp also seems to be wrong as I assume it's supposed to be a sans-serif font but it looks like it's switched to Courier New or something. Is it possible to change this at all? The input box font and contact list look fine.

**Comment by c10ud** [comment]
http://faq.pygtk.org/index.py?req=show&file=faq21.011.htp

21.11. Is it possible to have antialiased fonts on Win32?

Fonts on Windows are drawn by GTK+ using the native win32 calls; therefore, you need to have font smoothing enabled in Windows itself. Note that Windows will not smooth fonts within certain point sizes (6pt - 10pt for most fonts) unless you are using Windows XP.
On versions other than WinXP, you can enable font smoothing on Windows by following these steps:

Right-click on the desktop, select Properties to get the Display Properties dialog.
Choose the Effects tab.
Look for an option that mentions font smoothing, or smooth edges and enable it.
And on Windows XP:

Right-click on the desktop, select Properties to get the Display Properties dialog.
Choose the Appearance tab and click on the Effects button.
Enable "Use the following method to smooth edges of screen fonts".
From the combo box, choose "Standard" to get the same font smoothing that older versions of Window use, or "ClearType" to get smoothing of all fonts.
There is a web page for configuring ClearType (IE only): [www.microsoft.com]
Note that GTK and Pango do not use Xft on Windows, so the GDK_USE_XFT flag doesn't have any meaning there.

(James and Tim Evans)

see if with different heights the result changes

@arielj: any experience on this?

**Comment by arielj** [comment]
What happens if you change to Arial or something? do you know what type of font is that "Consolas"? TrueType? OpenType? Postscript? maybe it depends on the font type.

Can you try different font sizes?

Also, can you try with latest release (2.11.11)?

**Comment by c10ud** [comment]
just tried with 2.11.12-devel on xp sp3 font aliasing through ClearType is done correctly
