### ISSUE TITLE
No messages from emesene to Mac-LiveMSN

### ISSUE THREAD

**Issue by ErunamoJAZZ** [emesene/emesene#837]
Hello.
I have a friend in japan that uses mac, and (from the latest Git), when I write, does not get any message. That is, I read it to him, but he can not read me.
He uses LiveMSN from Mac 8.0.1

http://pastebin.com/hnU0C47r <-- the _./emesene -vvv_

PD: He only gets the nudge LOL

**Comment by Mystro256** [comment]
I believe this is a reoccurring issue with papyon and Messenger for Mac. I don't think anyone has been able to fix it yet. Maybe @c10ud or @Sbte has some info on this?

You can also take a look at the older posts: #671 #511

**Comment by c10ud** [comment]
no new info, the communication happens through microsoft servers so
having different clients shouldn't be a problem. turns out it IS a
problem, something related to papyon and/or mac messenger but
something we don't know what it is (because we cannot debug mac
messenger :))

2011/9/7 Jeremy Newton
reply@reply.github.com:

**Comment by c10ud** [comment]
@joshf sorry to ping you directly, but did you ever try talking emesene-to-LiveMessengerMAC?

**Comment by joshf** [comment]
Would be better to get some other mac users to do it. Put a message
out of blog or something. Going to be unable to test until mid June as
im travelling atm. Will have a look when i get home.

On 3 May 2012 19:08, Riccardo
reply@reply.github.com
wrote:

**Comment by c10ud** [comment]
OK.
BTW, about OP's issue, try changing the font to something other than Sans, maybe the mac messenger breaks on that (i suggested this in #511 but noone answered me)

closing the issue as incomplete
