### ISSUE TITLE
emesene crashes whilst selecting an emotion

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#839]
emesene crashes when you clicking the emotion icon in the conversation toolbar. Think its an OS X only problem.

http://pastebin.com/J85HRRD6

Emotions still work if you type their shortcuts e.g. :) :( :P

**Comment by c10ud** [comment]
yes, definitely something wrong in pygtk-quartz

**Comment by ghost** [comment]
Thought so, this is gonna be difficult to fix then.

**Comment by ghost** [comment]
Can anyone with a Snow Leopard system confirm this problem? I think it worked before i switched to Lion.

**Comment by c10ud** [comment]
i guess you just wait for a pygtk release in lion (?)

**Comment by pepeleproso** [comment]
I think this is in part related to https://bugzilla.gnome.org/show_bug.cgi?id=655087
