### ISSUE TITLE
Facebook in Emesene features

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#848]
1) Remove friend at emesene
2) Block an unblock contact works
3) PM same at facebook

**Comment by c10ud** [comment]
please be more descriptive because i don't get what this is

**Comment by Mystro256** [comment]
I think he's requesting those features...?

**Comment by pepeleproso** [comment]
reading https://developers.facebook.com/docs/chat/ these features are not avariable. We need to use facebook API
