### ISSUE TITLE
Add group in facebook not working

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#849]
Add group in facebook not working

**Comment by marianoguerra** [comment]
On Thu, Sep 8, 2011 at 3:58 AM, zipatei
reply@reply.github.com
wrote:

> Add group in facebook not working

does that feature exist on facebook?

**Comment by arielj** [comment]
I don't think so...

**Comment by shuhaowu** [comment]
I think he's talking about group chat (fb groups), or multiple user chat.

**Comment by c10ud** [comment]
```
Getting Started
Core Concepts
Advanced Topics
    Dialogs
    FQL
    Internationalization
    Ads API
    Credits
    Chat API
    Legacy REST API
    Legacy FBML
    Legacy FBJS
    Legacy Javascript SDK
SDKs & Tools
Open Graph Beta
```

Facebook Chat API
Advanced Topics › Facebook Chat API

You can integrate Facebook Chat into your Web-based, desktop, or mobile instant messaging products. Your instant messaging client connects to Facebook Chat via the Jabber/XMPP service. This document describes the features and limitations of Facebook Chat's XMPP protocol for the developer who intends to implement a Facebook Chat client.

Before reading this document, you should be familiar with the terms and concepts involved in XMPP chat clients and servers. If you anticipate that your Jabber client will host as many as 100,000 sessions, go to the Developer Help Contact Form and select Jabber to let us know.

Please do not use this API to send spammy messages to users. Facebook takes user experience and spam extremely seriously and if users report your app as using the Chat API to spam them, we will disable your app.

Features and Limitations

Facebook Chat currently supports the following features:

```
Facebook Platform authentication using the X-FACEBOOK-PLATFORM SASL authentication mechanism
Username/password authentication using the DIGEST-MD5 authentication mechanism
Sending and receiving plain-text messages (not HTML messages)
Sending and receiving typing notifications using the XEP-0085 protocol extension (not the XEP-0022 extension)
Setting the user idle using a show element in presence stanzas (there will be a delay before the user appears idle)
Receiving vCards using the XEP-0054 extension
Retrieving friends' photos (either with vCard or XMPP presence)
```

Limitations

Facebook Chat should be compatible with every XMPP client, but is not a full XMPP server. It should be thought of as a proxy into the world of Facebook Chat on www.facebook.com. As a result, it has several behaviors that differ slightly from what you would expect from a traditional XMPP service:

```
Your client cannot send or receive HTML messages
Because roster items and presence subscriptions are based on the user's Facebook friends, they cannot be created or deleted using the standard XMPP mechanisms.
Facebook Chat is terse when sending updates for new friends, because the negotiation happens outside of XMPP. Future versions of Facebook Chat may be more conformant.
The user's own Jabber ID (JID) is different from the Jabber ID that their contacts will see because the translation is done internally.
Arbitrary IQ stanzas cannot be passed between clients.
Presence probes do not currently work.
Non-SASL authentication with the jabber:iq:auth namespace as described in XEP-0078 is not currently supported.
The XML parser does not yet fully handle XML namespaces. Please stick to the same style as the examples in XMPP RFCs 3920 and 3921 when using XML namespaces.
```
