### ISSUE TITLE
Scrolldown messes up text selection in conversations

### ISSUE THREAD

**Issue by Mastergatto** [emesene/emesene#852]
From issue #832:
When I want to highlight some text from the conversation to copy it, the selection disappears when a new message is received, and the focus goes back to the bottom of the conversation. Is it possible to stop this? I also add that unchecking that option (autoscroll) doesn't actually seem to do anything, it behaves exactly as before. I'd disable audium output if I could be able to change the messages layout (giving them a pidginesque style)

**Comment by pepeleproso** [comment]
problem here is we don't check that config option in adium output before doing a execute_script("scrollToBottom()")

**Comment by c10ud** [comment]
```
    //Appending new content to the message view
    function appendMessage(html) {
        var shouldScroll = nearBottom();

        //Remove any existing insertion point
        var insert = document.getElementById("insert");

        if(insert) insert.parentNode.removeChild(insert);

        //Append the new message to the bottom of our chat block
        var chat = document.getElementById("Chat");
        var range = document.createRange();
        range.selectNode(chat);
        var documentFragment = range.createContextualFragment(html);
  var myFrag = chat.appendChild(documentFragment);
  //var frag = insert.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode;

  try {
      var fader = new Fadomatic(myFrag, 9, 0, 0, 95);
      fader.fadeIn();
  } catch(e) {
      trace(e);
  }
        alignChat(true);
    }
```

emesene/themes/conversations/renkoo.AdiumMessageStyle/Contents/Resources/Template.html

the alignChat(shouldScroll) could fix it, but who are we for fixing adium themes?
