### ISSUE TITLE
Email Opening with Wrong Browser?

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#855]
Oddly enough on my laptop my email via Emesene opens in firefox, but it should open in chromium. All my defaults for web related actions are set to chromium, including html files and what not. I don't have this issue on my desktop (same distro and all that).

 I would assume emesene just opens that temp html file, which I have tried myself opening it in nautilus and it opens in chromium :S

Any idea why this is happening?

**Comment by Sbte** [comment]
What do other links use? Like the one in the about window? Should be the same browser...

**Comment by Mystro256** [comment]
The link in the about window also opens the wrong one. As an added note, I did some testing on all my other applications and it seems this only effects emesene.

**Comment by Sbte** [comment]
Ok, then it's a bug in the webbrowser module. Nothing we can do about it I guess...

**Comment by Mystro256** [comment]
no work around?

It doesn't happen on my desktop, and the only difference between them is that my desktop is 64bit. I'm sure it's an odd configuration error somewhere...

**Comment by Sbte** [comment]
Ah, I just found the Desktop module in gui.base. It has an open function. Maybe we can use that? Could you test it mystro?

**Comment by Mystro256** [comment]
Okay, but I'm not too good with python, although if tell me what to change or make a commit and I'll test right away :)

**Comment by Sbte** [comment]
Change webbrowser.open or webbrowser.open_new_tab to Desktop.open

And don't forget to `from gui import Desktop`.

I hope it works.

**Comment by Mystro256** [comment]
Unfortunately I broke the computer I had this problem with, figures haha. So I can't test it :P

I'm going to get a new one, and if I have this issue I'll be sure to test this and pull it. Anyway, I'll close this issue for now.

Thanks for your help anyway Sven :)
