### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#856]
Hello,
there are some long messages not received with the following error: 

*\* Message: console message: undefined @1: SyntaxError: Parse error

**Comment by c10ud** [comment]
which emesene version?

**Comment by ammarabdulsalam** [comment]
latest git version
emesene 2.11.9-devel

**Comment by pepeleproso** [comment]
Sorry, this is because of my patches. I need to call post_process_message after each information message. I'll send a fix when I come back home

**Comment by pepeleproso** [comment]
if somebody want to fix this you need to add
        if msg.type == "status":
            self.last_incoming = None
at the end of _post_process_message
and then call that function on each information message in gui.base.conversation.
after the self.output.information call
