### ISSUE TITLE
Many problems after the last git pull

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#858]
It's probably been introduced in the latest commit (checked out a few minutes ago) since it wasn't happening before: whenever i type a message, if i press ctrl+enter it correctly puts a newline in the textbox where I wrote my message, yet newlines won't show in the conversation window, resulting in the second line of the message following the first one (without a space or anything visible). This also happens to the messages sent from my contacts: every message is just a huge single line. The funny thing is, the messages they receive contain the newlines, so it's just emesene that doesn't render them.
Also, right now, many messages don't get rendered in the conversation window (as for conversation with 3+ people): i hear the sound of a message received, yet nothing shows... This seem to be kind of random though, and no errors are shown...

**Comment by Soulsuke** [comment]
I add that now, in group conversations, the avatar won't rotate at all, and although the tab title is "Group conversation", the participants list only shows one e-mail address. That's if I invite other people, at least. The messages "contact has left/joined the conversation" aren't shown aswell.

**Comment by Mystro256** [comment]
Isn't it supposed to be shift+enter?

**Comment by Soulsuke** [comment]
As far as i know both keys combinations work... And the issue is still there

**Comment by Sbte** [comment]
That last issue might be fixed now. Please try again. 

Not sure about the other issue.

**Comment by Soulsuke** [comment]
I confirm the participants list, the avatar rotation and the 'left/joined the conversation' messages work normally now. The newline thing is still there though

**Comment by Sbte** [comment]
Found it. AdiumTheme line 191

**Comment by Sbte** [comment]
The most easy way to fix this is to just return template on that line, but I'm not sure what the replace was for before. And why it worked before this change and now it doesn't. @pepeleproso?

For reference:

https://github.com/emesene/emesene/blob/master/emesene/gui/base/AdiumTheme.py#L191

**Comment by pepeleproso** [comment]
Maybe we can convert \n in message by < BR>, and keep that replace

**Comment by Sbte** [comment]
Well, that'd be a way to hack around this. But I still wonder what would happen if we would remove the replace. Or why it's there.
