### ISSUE TITLE
file transfer error again :(

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#861]
(00:47:10) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0x7bc1d6ff: blob 1, SLP Message
    INVITE MSNMSGR:xxxxx@hotmail.com;{25fe5837-781b-440a-b28c-85815ac18b28} MSNSLP/1.0\r\n
    To: msnmsgr:xxxxx@hotmail.com;{25fe5837-781b-440a-b28c-85815ac18b28}\r\n
    From: msnmsgr:yyyyy@hotmail.com;{8c39ff7c-4262-4811-98eb-55c3ca4a10c6}\r\n
    Via: MSNSLP/1.0/TLP ;branch={1580C843-C4C1-4DD5-8863-E79312648EF4}\r\n
    CSeq: 0\r\n
    Call-ID: {5BFB9098-C18E-48DB-8302-B1ADE86143EE}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 882\r\n
    \r\n
    EUF-GUID: {5D3E02AB-6190-11D3-BBBB-00C04F795683}\r\n
    SessionID: 265957765\r\n
    AppID: 2\r\n
    RequestFlags: 16\r\n
    Context: PgIAAAIAAADGSg8AAAAAAAEAAABUAFYAIABUAGgAZQBtAGUAIABTAG8AbgBnAHMAIAAtACAAUwBtAHUAcgBmAHMALgBtAHAAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
(00:47:10) papyon.transport:<<< MSG yyyyy@hotmail.com Samar 251

```
P2P-Src: 'yyyyy@hotmail.com;{8c39ff7c-4262-4811-98eb-55c3ca4a10c6}'\r\n
P2P-Dest: 'xxxxx@hotmail.com;{25fe5837-781b-440a-b28c-85815ac18b28}'\r\n
Content-Type: 'application/x-msnmsgrp2p'\r\n
MIME-Version: '1.0'\r\n
[P2P message (134 bytes)]
```

(00:47:10) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0x7bc1dbd9: blob 1, SLP Message
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n
    \r\n
    \x00

**Comment by c10ud** [comment]
we didn't change anything afaik and there's no error in that trace

anyway i'll merge a papyon with a few patches soon..doubt it will
change something but..

2011/9/12 ammarabdulsalam
reply@reply.github.com:

**Comment by ammarabdulsalam** [comment]
sorry, the new error is in receiving files from wlm not sending
WLM -> emesene2 last git

the notification appears but can't show accept button

**Comment by c10ud** [comment]
if the notification appears but not the button then it's some weird bug in the ui
