### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by the98** [emesene/emesene#862]
This is what I've tried. Open your account in your computer (let's call it computer A) using emesene (of course) then open the same account in another computer (Computer B), also using emesene. Both computers will have your account opened. The problem is that, if you're using Computer B, what ever you're chatting will also appear in computer A, so this means that if you're not using computer A but someone else is, this someone will be able to read your conversation.

This could be a nice feature, maybe if you're constantly switching computer, but it can also be a bother. Maybe a button could be added in Preferences to active this feature. For instance "Allow to log in the same account in different emesene's sessions", or something.

Regards.

**Comment by Mystro256** [comment]
I see, so you want an option to disable logging in on different computers?

**Comment by the98** [comment]
Well... Let's say you log in at work. Forget to logout, go home and bash your boss with a friend in a conversation. If your boss is in the office, he could see what you were talking.

However, it's also interesting to be able to leave your emesene at home logged in so, no matter where you are your computer at home is registering your conversations in your history, so I think both options show be available.

Regards.

**Comment by ghost** [comment]
Afaik multiple presence is a feature, though I do believe it could be improved for better functionality.
1. When logged on in a new location, notifiy user that they are logged in somewhere else.
2. if possible, give the user the option to disconnect from the other location and remain logged in at the new location.

**Comment by c10ud** [comment]
iirc there's no api in papyon to handle that

**Comment by matiasdelellis** [comment]
Please..
Implement the menu option: File -> "Disconnect from other locations" when detect other connections.

The official client also displays the name and number of connections. Also would be good..

For example, I always open the web client I have that do not want to close, and usually use another computer that I need to close.

**Comment by c10ud** [comment]
if you tell me how to detect other locations, sure

2012/5/25 matiasdelellis
reply@reply.github.com:

**Comment by c10ud** [comment]
implemented in git master

2012/5/25 Riccardo (c10ud) c10ud.dev@gmail.com:

**Comment by matiasdelellis** [comment]
Wonderful.
Thanks for all!.
