### ISSUE TITLE
Quick question [solved] and bug.

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#863]
Just wondering about something - I noticed that in emesene/emesene/gui/base/Message.py on lines 53 and 59, there is 'incomming' when i think it should be 'incoming' but i'm not quite sure yet. Is this having any effect on e.g. message receiving? 

Still reading up on the code, so if anyone could offer some info on this, i'd be interested :)

**Comment by Sbte** [comment]
It's a typo that you can correct. The same typo also occurs in gui/base/Conversation.py. It shouldn't be causing any bugs though.

**Comment by Antonius-git** [comment]
Thanks :) Wanted to check that with someone.

Also, seeing as i'm here, i have a bug that pops up every now and then - i think when receiving messages? If someone could take a look at it:

Traceback (most recent call last):
  File "/home/ant/emesene/emesene/e3/base/Logger.py", line 888, in check
    callback(result)
  File "/home/ant/emesene/emesene/gui/gtkui/ContactInformation.py", line 419, in _on_chats_ready
    None, None, self.first)
TypeError: receive_message() takes exactly 3 arguments (7 given)

**Comment by Sbte** [comment]
That's #859. pepeleproso already has a fix for it in his tree.

**Comment by Antonius-git** [comment]
^_^ super fast response time! thanks again!
