### ISSUE TITLE
Some settings are lost if an extension is not found

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#866]
Implementig the ContactInfoList extension I renamed the old ContactInfo to ContactInfoRotate (to make them easier to understand).

The weird thing is that I've lost some settings like the extension chosen for the Tray Icon (it selects the default one). I had to go and chose it again.

Does someone experiment the same issue? is it only my?

My main concern is that next release will have the extension renamed and maybe all users will lost their extension's settings (I'm not sure if it resets any other setting too).

**Comment by c10ud** [comment]
no problems with 2.11.7->2.11.11 so far, closing
