### ISSUE TITLE
conversation info: Contact info list

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#867]
Ok, first off... My reaction when I saw this option for the first time > http://www.youtube.com/watch?v=Jpgy21r_dRE
Seriously, thanks a lot to whoever did this, I've been waiting for this feature for a while : D
There is a little problem though: when switching to a tab with the list of participants, the focus goes to the list, not the input textbox, like it happens with other tabs, which is kinda annoying... Also, being able to horizontally resize the list would be nice, although as it is right now is good aswell :)

**Comment by arielj** [comment]
I'll check that out when I get some free time (it shouldn't be so hard), I thought about the resizing but setting this to a fixed width was easier :P

**Comment by Soulsuke** [comment]
The resizing really isn't an issue, but I guess it could be nice.. The focus thing is annoying though XD
