### ISSUE TITLE
Launch failure on OS X 10.7 outside /Applications

### ISSUE THREAD

**Issue by GoldenDragon** [emesene/emesene#868]
emesene.app cannot be launched if it's not in the /Applications -folder. Using it should work outside the folder.

**Comment by ghost** [comment]
This is completely intentional.

GTK is hardlinked to /Applications/emesene.app/Contents/Resources/gtk

> workdir=`dirname $0`
> 
> if [ "$workdir" == "/Applications/emesene.app/Contents/Resources" ]
> then
>   sleep 0
> else
>   echo "emesene is not located in /Applications. Exiting now..."
>   exit 0
> fi

If emesene is not in /Applications gtk will not work. I know its a inconvenience but i can't change it.
