### ISSUE TITLE
Need an option for disable hotkey ESC

### ISSUE THREAD

**Issue by Mastergatto** [emesene/emesene#871]
It's quite annoying that conversation window closes when presssing ESC by mistake, and I haven't found anything (i'm sure, really) that can disable the hotkey in the emesene's preferences.

**Comment by Sbte** [comment]
Just wondering? How do you press Esc by mistake?

**Comment by Mastergatto** [comment]
For example, when you forget that the focus is on emesene's window, and you think you're about to close another window somewhere, or (un)pause a game.

**Comment by Sbte** [comment]
Eh, so you're used to closing windows with Esc, and want to do it that way (otherwise you would use Alt+F4), but because you use Esc to close windows you want to disable it. 

Go ahead and implement it yourself if you feel you need it.

**Comment by Mastergatto** [comment]
They were just two examples, the ESC button has different functions in every program, not only closing window. In my case, I need to pause/unpause games I play by pressing ESC, and when I'm about to unpause, sometimes the focus remains (user or wine's fault) on emesene conversation rather than the game window, so it closes emesene window. This is why I need that option.
Also, you said that very well, ESC button is useless for closing window, we can use alt + f4 for that, no?

**Comment by Sbte** [comment]
It closes tabs in emesene, not windows. But I see your point. You could implement it if you like.

**Comment by Mastergatto** [comment]
Ok, since it should be an easy thing to do (not for me, i'm not a programmer and I never studied programming at school!), so I accepted the challenge. Many hours after, I managed to find the code for autokey and inserted an if and an option in the preferences. It works (how did i do that?!), but I don't know how to create a patch and send it on your repository. Can you help me?

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/wiki/GitHowTo

**Comment by Mastergatto** [comment]
Ok, commit sent. #873

**Comment by Sbte** [comment]
Pulled. Thanks!
