### ISSUE TITLE
Characters not shown in chat window

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#872]
Right now ' gets changed to &apos; in the chat window... The same happens for other special characters (such as < and >), although they all look normal in the input textbox

**Comment by Soulsuke** [comment]
Oh, I should add that even links now are shown in a weird way: 
< a href="https://github.com/emesene/emesene/issues/872" >https://github.com/emesene/emesene/issues/872< /a >
UPDATE: the same goes for emoticons (both default and custom), except they use the img tag

**Comment by Sbte** [comment]
@pepeleproso ^
