### ISSUE TITLE
Disable sound when the conversation has the focus

### ISSUE THREAD

**Issue by Lilithlun** [emesene/emesene#877]
Hello, i used the old msn and liked it. Now i happilt upgraded to emesene 2.
My only problem (that really is a big issue for me) is that i cannot find a way to activate incoming message sound only when the conversation is out of focus.
With the only new options: play sound on first received message and play sound on received message i cannot see how to achieve that.
I've tried to browse closed issues but the only same question is 11 months old and does not apply to this version.
I use the latest Windows build.
Thanks.

**Comment by c10ud** [comment]
seems like the "fix" is gone with time (!)
