### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#879]
Not sure why, but  now when I receive a message there's a high probability I won't hear a sound, while everything else works fine. It's pretty random, sometimes the sound plays and sometimes not
EDIT: This seem to happen a lot especially during group conversation, but it still happens in 1-on-1 convos aswell

**Comment by Sbte** [comment]
You should hear a sound only when the conversation window is out of focus.

**Comment by Soulsuke** [comment]
Ok, that does explain most of it, but somehow receiving messages from contacts that cause the bug #685 don't trigger any sound, while they did before

**Comment by c10ud** [comment]
the sound should (and hopefully now does) play only if the conversation icon goes to new-message state, anything else is either a different bug or not a bug
