### ISSUE TITLE
Adding contacts doesn't work

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#885]
Stupid papyon bugs, or whatever. I assume M$ changed something again just to fsck with us? I remember it worked before...

Anyhow, it seems like devfil got it to work in pecan, so maybe we have to change something similar in papylib too? Or is this unrelated?

https://github.com/dfiloni/msn-pecan/commit/1820f171c4f6172e1ab9183e049199dadf1fe8ff

**Comment by shuhaowu** [comment]
Yeah. I think this thing doesn't work for a lot of other clients as well right now.

**Comment by danielgomon** [comment]
I have the same problem, even in the 1.x versions... now I'm in 2.11.9, can't add anyone.

**Comment by hit** [comment]
Delete your contact in Live Messenger tab (if present), open Live website and add your contact there. As you can see, it even fails there sometimes, so you can't expect it to work in 3rd party if even official way is pure crap!

**Comment by javijec** [comment]
I if I can add contacts on emesene git version and ubuntu 11.10

---

yo si puedo agregar contactos en emesene version git y ubuntu 11.10
