### ISSUE TITLE
Implement close_session as a signal

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#887]
Currently, close_session is passed everywhere, but it also changes names everywhere. This is really annoying, as it's used everywhere, and it's also the method that caused most bugs so far (that I know of). I suggest to implement it as a signal, so we can connect to it inside of emesene.py.

Additionally, we'd have to connect things that are added to the function while passing it around (for example in Window.py) to the same signal.

I'm not sure if this will work, but if it does, it simplifies things a lot (and probably solves some refcount issues).

Example of use in emesene.py:

```
self.session.signals.close_session.subscribe(self.close_session)
```

and from inside of a different file/class/method:

```
self.session.close_session()
```

**Comment by shuhaowu** [comment]
i'm willing to give it a shot if I'm briefed a little more on the issue, such as where the instances are (I don't know that part of the code)

Also how do I know if I'm on the dev mailing list?

**Comment by Sbte** [comment]
Well, close_session is passed as a function to a lot of other objects. You have to trace all of them down. And it's a good thing if you're sure you know what you're doing, because this is very likely to break stuff.

About the list: You should receive a conversation mail after subscribing.
