### ISSUE TITLE
'new message' sound notification doesn't work

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#889]
I have this problem in Ubuntu Lucid and ArchLinux with the 2.11.9 version. The sound notification doesn't work, only sometimes, in 2.11.7, works fine.  Also the popup notification (notify-osd and gnome-notification-daemon) doesn't work properly, only shows sometimes. I tried to run it with 'dbus-launch', but the problem persist.

Here's the terminal output:

$ dbus-launch emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"
[21:57:49 ERROR papyon.protocol.notification] Notification got error : 913 13

**Comment by Sbte** [comment]
We disabled it when the conversation is on focus. Is that what you're experiencing?

**Comment by danielgomon** [comment]
Yes, the pop-up message only works when the emesene window is minimized, but the problem with this change comes when you have several tabs open in a active window, you can't notice when a contact in the other tab writes a message. On the other hand the sound notification doesn't work, even when the conversation is not on focus.

**Comment by hit** [comment]
Also no "new message waiting" icon in tabs always so sometimes I see this "new" message half an hour later.

**Comment by danielgomon** [comment]
I'm in Ubuntu Lucid now, the sund and pop-up notification doesn't work at all. This is really weird, with the 2.11.7 version, it works (at least the sound notification, the pop-up, only sometimes)

I really miss the emesene 1.6.3 notification behavior, it was way better: always sound, always pop-up and also had a "your contact it's writing" notification. 

Why the 2.x can't be as good as 1.6.3?  The old emesene was good enough (I refer about the notification behavior), why change things like these? I really, really like emesene 2.x, Is awesome. But these changes about the notifications, are just bad.

**Comment by danielgomon** [comment]
I know this change is related to this: https://github.com/emesene/emesene/issues/877

But, can you add this as an optional feature? I would be nice if the user has the chance to change the settings according to his needs; I'm sure, I'm not the only one who thinks this...
