### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by cicciaj** [emesene/emesene#890]
2.11.9
There isn't a tray icon anymore, making emesene UNUSABLE when I close the main window.
Yes, there are people still using GNOME 2.X

**Comment by Sbte** [comment]
There should be. What does Preferences->Extensions->tray icon tell you

And what OS do you use?

**Comment by cicciaj** [comment]
purged, rebooted the system and then re-installed emesene.
And then the tray icon extension appeared, before there wasn't anything.
oh, the mistery.

**Comment by neptunium** [comment]
i'm using ubuntu 11.10 and upgraded to emesene 2.11.9
but there is not a tray icon and if i close the emesene window it seems i'm offline but i still get notifications. i chose the tray icon extension but there is nothing else to do...
heeelp

**Comment by Sbte** [comment]
In ubuntu you have the messaging menu (envelope at the top). The normal tray icon doesn't work, because ubuntu doesn't use gtk2. If you want a real tray icon, use the Indicator extension, but Ubuntu really wants to force you to use the messaging menu.

**Comment by neptunium** [comment]
no, i don't think so. about one month i go i had ubuntu 11,04 and emesene 2.11.7 and there was an emesene tray icon. the green (or whatever) circle. and now it diappeared.

**Comment by Sbte** [comment]
Did you select the indicator extension?

**Comment by neptunium** [comment]
so, on the extensions tab i select "tray icon" on "categories" and "indicator" on "selected", and i press "close".. and nothing happens..

**Comment by Sbte** [comment]
And if you restart emesene?

**Comment by neptunium** [comment]
YES! everything is fine now! thank you very much!
