### ISSUE TITLE
Links do not open in update dialog on OS X

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#892]
If you run check for updates and an update is found, you cant open the link to the emesene website. The following error is thrown:

```
/Users/Josh/Desktop/emesene/gui/gtkui/__init__.py:89: GtkWarning: Unable to show 'http://www.emesene.org': Operation not supported
  gtk.main()
```

**Comment by Sbte** [comment]
And the link in the about window?

**Comment by ghost** [comment]
Works perfectly. Its just the check for updates link. 

I want to get this working because i do not have time to maintain the shell updater i wrote for OS X, and so i want to use emesene built in checker (Check for updates...) so it works as it does on Linux and Windows.

**Comment by Sbte** [comment]
Fixed committed. Please test it, because I'm not sure if it works, but I sure hope it does ;)

**Comment by ghost** [comment]
Works perfectly. Thanks!

Just need to remove the OS X specific if in Handler.py for update checking. WIll pull soon.
