### ISSUE TITLE
Make emesene send the '...is typing a message' notification

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#898]
I'm trying this new option: https://github.com/emesene/emesene/issues/897 It works fine, the only thing is that always shows "%s" before the "is typing a message..." (I tested it with Pidign and WLM), here's a screenshot: http://inky.ws/g/mv&msg=saved

Also can you make emesene send the '...is typing a message'  notification? To complete this new feature, and make it more useful! 

This is also related to this: https://github.com/emesene/emesene/issues/809

PD: Thanks for all the recent changes, emesene2 is fuc*in' awesome!!! :D

**Comment by Sbte** [comment]
Just pushed a fix. I hope it works!

I have no idea how to do the send part btw. That'd require a lot more of my time...
