### ISSUE TITLE
Windows version 2.11.9, compiled exe can't run

### ISSUE THREAD

**Issue by mikk73** [emesene/emesene#899]
Hi!

I create windows exe from 2.11.9 official source +needed missing module: xmpppy, with this procedure: https://github.com/emesene/emesene/wiki/Windows-(New)
But emesene 2.11.9 version exe can't run, error message this:

No handlers could be found for logger "emesene.e3.common.DBus"
T:\Temp\emesene compile\Install\emesene-2.11.8-devel-20111009_0157-portable.\e3\jabber\Worker.py:27: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
Traceback (most recent call last):
  File "emesene.py", line 846, in <module>
  File "emesene.py", line 843, in main
  File "gui\gtkui__init__.pyo", line 87, in gtk_main

  File "emesene.py", line 240, in start
  File "emesene.py", line 493, in _draw_tray_icon
TypeError: 'NoneType' object is not callable

If I create windows exe from 2.11.7 official source +needed missing modules: xmpppy &papyon, this exe running without problem!

**Comment by Sbte** [comment]
Must have something to do with me moving all that to gui.common, but I have no clue why it doesn't work...

**Comment by mikk73** [comment]
Hi!

Additional information, "python emesene.py" command is working, emesene 2.11.9 is running. 
Messages, after I login with my acc, and exit:
c:\Temp\emesene\emesene>python emesene.py
No handlers could be found for logger "emesene.e3.common.DBus"
c:\Temp\emesene\emesene\e3\jabber\Worker.py:27: DeprecationWarning: the sha modu
le is deprecated; use the hashlib module instead
  import sha
C:\Python26\lib\site-packages\Crypto\Util\randpool.py:40: RandomPool_Deprecation
Warning: This application uses RandomPool, which is BROKEN in older releases.  S
ee http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
c:\Temp\emesene\emesene\gui\gtkui__init__.py:89: Warning: g_object_set_qdata: a
ssertion `G_IS_OBJECT (object)' failed
  gtk.main()

Created (compiled) exe can't run.

**Comment by Sbte** [comment]
That looks normal. I have no idea why the compiled exe doesn't work.

**Comment by c10ud** [comment]
maybe some file is missing in the package?

**Comment by mikk73** [comment]
c10ud: 2.11.5, 2.11.7 is working, created exe is running. Something wrong with 2.11.9 version, and git version. This is not my fault. 
Latest git compile log with batch file (2011-10-19): http://www.megaupload.com/?d=0CQGJJLQ

**Comment by c10ud** [comment]
reading the log:
byte-compiling c:\Temp\emesene\emesene\gui\base\stock.py to gui\base\stock.pyo
byte-compiling c:\Temp\emesene\emesene\gui\common__init__.py to
gui\common__init__.pyo
byte-compiling c:\Temp\emesene\emesene\gui\gtkui\AccountMenu.py to
gui\gtkui\AccountMenu.pyo

gui/common files ain't be "compiled"/included in the package

2011/10/19 mikk73
reply@reply.github.com:

**Comment by mikk73** [comment]
Thanks c10ud!

emesene\gui\common is new directory in 2.11.9 version. (Sbte wrote: "me moving all that to gui.common").

I'm waiting improved source code.

**Comment by Sbte** [comment]
I guess the py2exe stuff can't contain my awesome import system. Is there any way to add the files manually, or to fix the imports?

@marianoguerra

**Comment by c10ud** [comment]
i guess just add them to setup.py manually? or what else py2exe is about (!)

2011/10/20 Sven
reply@reply.github.com:

**Comment by mikk73** [comment]
OFF:
I don't know python, but I think not is the problem, because
"emesene\dist\gui\common__init__.pyo" is compiled file.

I think problem with this file:
"emesene\gui\common__init__.py"

**Comment by Sbte** [comment]
Yes, that's what we're talking about...

And I have no idea how to do that in setup.py...

**Comment by Sbte** [comment]
Try to add "gui/common/*" to the package data list. Not sure if that's not it works though, but it's the only place I could thick of of where to put it...

**Comment by mikk73** [comment]
Hi, any news, or Windows version is dropped?

**Comment by Sbte** [comment]
Did you try what I said in the comment above? That's the only thing I can think of. And I don't have a windows installation at hand, so I can't really test it myself.

**Comment by mikk73** [comment]
Hi!

Okay, I try/test this for you:

package_data = {
        "emesene": [
            "gui/common/_", 
            "themes/conversations/_/_/_/_/_",
            "themes/emotes/_/_",
            "themes/images/_/_/_",
            "themes/sounds/_/*"
        ]
    }

Nothing change.

**Comment by mikk73** [comment]
Forum engine is... well I thest this: 

```
package_data = {
        "emesene": [
            "gui/common/*",
            "themes/conversations/*/*/*/*/*",
            "themes/emotes/*/*",
            "themes/images/*/*/*",
            "themes/sounds/*/*"
        ]
    }
```

**Comment by Sbte** [comment]
Then I can't really help you...

**Comment by mikk73** [comment]
This is not help "for me", this is mean, no windows compile is possible, with this new version.

**Comment by Sbte** [comment]
Ok, I'm trying this now, but when running `python setup.py py2exe` I get `ImportError: No module named win32api`. Any clue what that can be?

**Comment by Sbte** [comment]
Ok, I just forgot to install something. I've been messing around with this for a few hours now, and I can't seem to find a way to get py2exe to understand dynamic imports. And I really don't understand how to do this in setup.py...

**Comment by Sbte** [comment]
Please try this:

https://github.com/Sbte/emesene/commits/2.11.9

It's not all that nice, because py, pyc and pyo files are included, but it's better than nothing...

**Comment by mikk73** [comment]
Hi, this is works, exe is can run.

After install portable from this new compile, in \gui\common\ no pyo files, only this: "**init**.pyo"
After run emesene.exe, all pyo files is available in in \gui\common\, except: "UnityLauncher.pyo", only "UnityLauncher.py" file is available.

**Comment by pepeleproso** [comment]
that's because UnityLauncher isn't avariable on windows

**Comment by mikk73** [comment]
```
Okay, thx. I can create windows exe and installer now from 11.9 official version.
But this is not full official, because xmppy is missing from "official" version.

Well I don't upload these installers, because all strong problem is stay (two important issues):

1. portable version is not portable, because config files here (Win7): 
"c:\Users\<user>\AppData\Roaming\emesene\emesene2\"

This error already in 2.11.7 version.

2. preferences/theme or preferences/plugin download function is bad: 

- freeze emesene2 (need taskmanager to kill)
or 
- download nothing (main screen is empty if I restart emesene2 after download and select new theme).
```

**Comment by Sbte** [comment]
1. @syst3mfailur3 can probably help with that.
2. Please file a bug for that. We can't fix something we don't know of.

Anyhow, 2.11.9 is still an improvement over 2.11.7, so I don't see any reason not to upload it. Also, xmppy should be present in the windows version of emesene, so that's good. So if you could put the installers somewhere, then I'll put them on github. Maybe @syst3mfailur3 can check if it's done correctly.

Closing because the exe now works.
