### ISSUE TITLE
setup.py can't copy Elementary/panel

### ISSUE THREAD

**Issue by Zincr0** [emesene/emesene#90]
running 
- python setup.py install
  or
- python setup.py build
  causes
  error: can't copy 'emesene/themes/images/Elementary/panel': doesn't exist or not a regular file

(panel is a folder)

**Comment by SWOriginal** [comment]
any particular reason your using the setup.py?

if your just trying to run emesene2 you can use the "emesene" file from emesene/emesene/

**Comment by Zincr0** [comment]
"./emesene" and "python emesene.py" in emesene/emesene

gives an authentication fail. But with the same user and pass using the ppa´s emesene for ubuntu 10; login is ok. I thought maybe with setup.py should work...

Thanks for your time.

**Comment by c10ud** [comment]
setup.py needs to be updated with new themes i guess, there're still some changes so i'd wait a bit

**Comment by SWOriginal** [comment]
theres only 1 theme waiting to be included and thats elementary-dark, the elementary team are still making changes then as soon as there released i'll push the changes... 

after that there will just be improvements (dimension wise) as the main window icons are still quite large :)

if/when there are future themes they will be uploaded to the emesene deviant art page (still not complete) to get the community to start providing us with awesome customisations :D

**Comment by marianoguerra** [comment]
fixed the issue
