### ISSUE TITLE
New suggestion for Talk status 

### ISSUE THREAD

**Issue by ThiagoBezzy** [emesene/emesene#900]
Hello, I would suggest a new concept to show the status of conversation.
He is inspired by the WLM.
And the link below you can see how it is.
http://img593.imageshack.us/img593/6355/emesenehc.png
.

I would also suggest that in future versions, you implement the integration with twitter and facebook.
Emesene in itself can, cause the user to give the feeds from facebook, twitter and also post some things.

Thus, the emesene become a full client.
Twitter, Facebook and Windows Live Messenger
.
Please excuse me for my bad English, because I do not speak English and then use google to translate my ideas.
.
Sincerely
Bezzy ;D

**Comment by danielgomon** [comment]
Looks nice, I really like this idea!

**Comment by ThiagoBezzy** [comment]
Thakns =]

**Comment by ThiagoBezzy** [comment]
Thanks\* rsrs

**Comment by c10ud** [comment]
won't do it, we already have plenty of indications about user status

plus (personal note) i think it's ugly

feel free to provide extensions though
