### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_pointer'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#901]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Tooltips.py", line 163, in show_tooltip
    x, y = self.computePosition(origCoords, view.window)
  File "/home/andre/emesene/emesene/gui/gtkui/Tooltips.py", line 184, in computePosition
    currentY = viewWindow.get_pointer()[1]
AttributeError: 'NoneType' object has no attribute 'get_pointer'

**Comment by djthyrax** [comment]
Probably the problem is in line 163 as I think it should be view.Window (with a capital W).

(Can't test right now, I'd like some feedback)

**Comment by Sbte** [comment]
It's not that. For some reason the widget that the popup was called from didn't have a window. I don't see how that's possible...

**Comment by c10ud** [comment]
quite a strange issue, if it happens again please reopen
