### ISSUE TITLE
Stored accounts vanished

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#902]
Yesterday, after the last update, when I logged in with my Live account emesene asked me to go to Live Profile to change my picture, since the one I was using was broken (?)
Ok, I did that, just fine.
Now I turned on my computer again and opened emesene and.... there's no account available for login. Like a brand new installation of emesene.

How can I recover my data? The files are still in ~/.config/emesene2...

**Comment by Sbte** [comment]
Are the accounts also in ~/.config/emesene2/config?

**Comment by igorsantos07** [comment]
God, no. The config file is empty.
How can I recreate it?

**Comment by Sbte** [comment]
Just log in. That should work. You could make a backup of the other files just to be sure ;)

**Comment by igorsantos07** [comment]
After login, my account settings are still vanished. Window format, tab configs, fonts, etc etc etc :(

**Comment by Sbte** [comment]
That's really weird. I don't see how the config files could have vanished...

**Comment by igorsantos07** [comment]
I've compared the backuped folder and the actual folder, and they are identical. But my chat windows are just like brand new emesene windows. :(

**Comment by Deusdies** [comment]
What is the ownership of the config folder? Do you have write permissions? Also, is the config file even created?

**Comment by igorsantos07** [comment]
Yes, the config file was created just fine. The config folder and everything
belongs to my user, they are in my home folder.

**Comment by c10ud** [comment]
sbte should have fixed this with the end-of-session config saving with correct closure of the program. try 2.11.11 and if issue persists reopen this
