### ISSUE TITLE
Bug offline messages

### ISSUE THREAD

**Issue by Mastergatto** [emesene/emesene#904]
If offline messages are received, emesene won't print messages anymore, although they are shown in notifications.

**Comment by bardok** [comment]
Same problem. 
My brother use emesene 2.11.9 on ubuntu oneiric and i use emesene 2.11.9 on voyager 11.10 (xubuntu).
We always talk while we are offline and some messages are not received by him.

**Comment by bardok** [comment]
I found this in debug what does it mean ?

(20:34:56) papylib.Events:OIM service state changed: 1
(20:34:56) papylib.Events:OIM service state changed: 2
(20:35:03) papyon.gnet.HTTP:Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
(20:35:03) papyon.service:Transport Error : HTTP Error (500): Internal Server Error
(20:35:03) papylib.Events:Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder
(20:35:07) papylib.Events:OIM service state changed: 0
(20:35:07) papylib.Events:OIM service state changed: 1
(20:35:07) papylib.Events:OIM service state changed: 2
(20:35:12) papyon.gnet.HTTP:Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
(20:35:12) papyon.service:Transport Error : HTTP Error (500): Internal Server Error
(20:35:12) papylib.Events:Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder

**Comment by bardok** [comment]
More, my brother see all the messages in conversation history... he sent me all the conversation by mail and all are present

**Comment by moneycat** [comment]
I've the same issue in version 2.11.9. The offline message will be logged but not showing in the pop-opened conversation window. Is there any extension or method to make them printed while pop up?

**Comment by moneycat** [comment]
Um..I've found another issue maybe related to this. In the popup window of offline messages which not shown, It cannot show the reply messages from the user too.

**Comment by Sbte** [comment]
Are you guys using tabs or separate windows for conversations?

**Comment by moneycat** [comment]
I'm using the tabs for conversations (the default settings?).

**Comment by bardok** [comment]
I'm using tabs for conversation too.

**Comment by c10ud** [comment]
should have been fixed by sbte's

**Comment by c10ud** [comment]
see https://github.com/emesene/emesene/commit/3dc05bfd5531d778884b05073a021068966ef68b if you're interested in code details
