### ISSUE TITLE
Messages not delivered to yahoo recipients.

### ISSUE THREAD

**Issue by Osjar** [emesene/emesene#905]
I send a message from a msn hotmail account to a yahoo account but the messages aren't delivered neither at the yahoo webmessenger nor to the yahoo webmail. I use emesene 2.11.9 on Unbuntu 11.04.

**Comment by marianoguerra** [comment]
we should ask papyon guys about support for this.

I don't know the details about the yahoo gateway, so maybe it's not
implemented or doesn't work correctly

if you turn debugging information can you see any error?

**Comment by Osjar** [comment]
It also happends when i try to send a message to another hotmail.com address. I am not sure how to turn on debugging information, do you mean the menu shown at Help > debug?.

If so i get this when i send a message to a yahoo account:

(09:58:27) papyon.transport:>>> PNG
(09:58:27) papyon.transport:<<< QNG 47
(09:59:14) papyon.transport:>>> PNG
(09:59:14) papyon.transport:<<< QNG 47
(10:00:01) papyon.transport:>>> PNG
(10:00:01) papyon.transport:<<< QNG 48

No errors, just nothing. The same happends when i try with a hotmail account, just with different numbers:

(10:00:49) papyon.transport:>>> PNG
(10:00:49) papyon.transport:<<< QNG 45
(10:01:34) papyon.transport:>>> PNG
(10:01:34) papyon.transport:<<< QNG 43
(10:02:17) papyon.transport:>>> PNG
(10:02:17) papyon.transport:<<< QNG 50

**Comment by c10ud** [comment]
with yahoo you should see UUMs being sent in debug, but i never tested em because i don't have yahoo contacts

**Comment by c10ud** [comment]
please try with current git master, i had the chance to test it for like 5 mins, so i don't know if it's working reliably

**Comment by Osjar** [comment]
Everything works perfecly now, as with yahoo as with the hotmail accounts.

**Comment by c10ud** [comment]
thanks for testing, i'm closing this issue then
