### ISSUE TITLE
Can't see self in contact list

### ISSUE THREAD

**Issue by hit** [emesene/emesene#906]
I've added myself to contacts to "see how I appear to others", but I see myself as offline instead.

**Comment by Sbte** [comment]
This is because papyon doesn't support it. I don't think it's possible with the current implementation...

**Comment by hit** [comment]
Yes I know, but since there is already emesene's own papyon...

**Comment by Sbte** [comment]
Yes, but IIRC it wasn't possible to implement it in papyon without rewriting a lot of the code.

**Comment by hit** [comment]
Alright then, didn't know that part.

**Comment by ghost** [comment]
so what about that ?
Wont be fixed?

i am also interested

**Comment by Sbte** [comment]
It's not of high priority at least.

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/issues/568

**Comment by c10ud** [comment]
iirc something related to mpop, etc. so, won't fix
