### ISSUE TITLE
Windows 2.11.7/9 portable version is not portable

### ISSUE THREAD

**Issue by mikk73** [emesene/emesene#907]
Problem with emesene 2.11.7 or 2.11.9 portable version.

Shortly:
Config directory on Win7 here: "c:\Users\username\AppData\Roaming\emesene\emesene2\", not in app directory. This is important problem.

Detail, if above information is not enough... 

Portable version mean this: Application not uses any registry settings or any files outside on application directory.

I do these steps:
1. Delete the emesene config directory "c:\Users\username\AppData\Roaming\emesene\emesene2\"
2. Install emesene 2.11.7 or 2.11.9 portable version to "C:\emesene"
3. Start emesene2. I select msn, type username, password, remember me and remember password is checked. Click to connect. Success. File menu/quit.
4. Delete emesene installed directory "C:\emesene"
5. See # 2
6. Start emesene2, and I see, username and password is already stored.

ps.: emesene 1.6.x portable version is really portable.

**Comment by pepeleproso** [comment]
arielj fixes this. please try the new binary.

**Comment by Sbte** [comment]
A portable portable version uploaded to https://github.com/emesene/emesene/downloads
