### ISSUE TITLE
Hotmail login doesn't work!

### ISSUE THREAD

**Issue by astagi** [emesene/emesene#909]
Hi all,

I'm trying to login in hotmail clicking on the mail button, but when browser is opened, login fails... Tried with aMSN and all works well... 

What is changed?? Maybe something of legacy has been removed? If so well, hotmail module needs it... 

check it out at gui.base.Hotmail.py

Regards..

**Comment by c10ud** [comment]
same here, but i don't think we changed something other than using xdg-open instead of webbrowser, the page should be still the same -- could be that auth changed?

**Comment by astagi** [comment]
no the auth mechanism is the same, I have an old version of aMSN that makes the same work and stiil working... Using the xdg-open shouldn't break anything, we just open an html file from /tmp folder with auth hash wrote in... When I did the module I remembered that Mariano said me that Emesene had some legacy fields in its library, maybe something has been removed :| @Sbte did you change anything ??

**Comment by Sbte** [comment]
I checked with 2.11.7 and it also doesn't work there. I guess ms changed something...

**Comment by astagi** [comment]
Uhm it's strange... are you sure that with 2.11.7 stable worked? I tried with aMSN and all works... someone could try with emesene 1 ?? I took the module from that version..

**Comment by Sbte** [comment]
For me emesene1 says it can't open the default browser. So I can't test it.

**Comment by astagi** [comment]
Ok tried with emesene 1 and doesn't work... what do aMSN have of special?? o.O aMSN2 (if alive) just support Hotmail? we should test it..

**Comment by astagi** [comment]
@marianoguerra do you know something about?

**Comment by marianoguerra** [comment]
On Thu, Nov 3, 2011 at 3:12 PM, Andrea Stagi
reply@reply.github.com
wrote:

> @marianoguerra do you know something about?

I didn't touched it, what you can do is get the html source of the
redirection page in amsn and emesene 2 and post it somewhere so we can
check if something changed.

**Comment by astagi** [comment]
Ok I'll try to find it..

**Comment by astagi** [comment]
Found the file... in aMSN they use the sha1 algorithm to build the token, then they pass it to https://login.live.com/ppsecure/sha1auth.srf?lc=1033... we're using MD5 and https://login.live.com/ppsecure/md5auth.srf?lc=1040 , maybe our method has been removed..

**Comment by astagi** [comment]
Tried just to hash with sha1 in Emesene but doesn't work :( there's something else..

**Comment by Sbte** [comment]
Any updates on this?

**Comment by astagi** [comment]
No :(

On Tue, Nov 8, 2011 at 6:03 PM, Sven
reply@reply.github.com
wrote:

> Any updates on this?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/909#issuecomment-2670224

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by c10ud** [comment]
tried some work in c10ud/master unfortunately no luck so far...

**Comment by c10ud** [comment]
please see what i've done and see if i missed something obvious

**Comment by astagi** [comment]
Here it is the module used in amsn for Hotmail: https://github.com/Kjir/amsn/blob/master/amsn/hotmail.tcl

Hope is helpful

**Comment by saideva** [comment]
Thanks for providing such  a wonderful information in this post, I really appreciate your hard work to bring this out into a post. I have bookmarked your blog ID for future information purpose. I have an information that, now we can solve our Hotmail problems (If any) with the help of Hotmail customer care services. We can get details of various customer care contact numbers, chat numbers, tech support numbers ( Toll Free Numbers )from the Website : http://customercaresupportnumber.com/ for variosu USA, UK and CANADA based companies along with Hotmail customer care service numbers.
