### ISSUE TITLE
Loggin failed with Internal Server Error

### ISSUE THREAD

**Issue by chy168** [emesene/emesene#91]
When I logged in msn, it shows:

[23:09:45 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
[23:09:45 WARNING papyon.service] Transport Error :500

**Comment by c10ud** [comment]
notabug

**Comment by chy168** [comment]
I change all address from "contacts.msn.com" to "omega.contacts.msn.com", and it works !
Is this a right way to patch ?

**Comment by c10ud** [comment]
it could be, but you should tell papyon developers about this see 

https://bugs.freedesktop.org/buglist.cgi?product=papyon

https://bugs.freedesktop.org/show_bug.cgi?id=31004

**Comment by chy168** [comment]
ok, I commit my solution on freedesktop bugzilla.
thanks help from c10ud :)
