### ISSUE TITLE
LEDs For Your Life!

### ISSUE THREAD

**Issue by cynthialed** [emesene/emesene#910]
GE LED Bulb For Christmas！
http://www.leddoes.com/wholesale/wholesale-ge-bulbs.html

**Comment by cynthialed** [comment]
GU10 LED Bulb
http://www.leddoes.com/wholesale/wholesale-gu10-bulb.html

**Comment by cynthialed** [comment]
12V LED Bulb For Christmas！
http://www.leddoes.com/wholesale/wholesale-12v-bulbs.html

**Comment by c10ud** [comment]
oh god, spam in gh lol

2011/11/3 cynthialed
reply@reply.github.com:

**Comment by c10ud** [comment]
btw, if you could send me some free leds..
