### ISSUE TITLE
Do You Know Anything About LED?

### ISSUE THREAD

**Issue by cynthialed** [emesene/emesene#911]
1000lm LED Bulb For Christmas！
http://www.leddoes.com/wholesale/wholesale-1000-bulb.html

**Comment by cynthialed** [comment]
T8 LED Bulb  For Christmas！
http://www.leddoes.com/wholesale/wholesale-t8-bulbs.html

**Comment by c10ud** [comment]
sir, we already have too much issues, please use some of the opened ones to sell your fscking leds

thanks in advance
