### ISSUE TITLE
Make the 'song info' display in the conversation tab

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#913]
Can you make the 'song info' display also in the conversation tab? At this moment it only shows in the main window, would be more useful if we can see it also in the conversation tab!

**Comment by Sbte** [comment]
You mean of the contact you're talking with right?

**Comment by danielgomon** [comment]
Yes, like it was in emesene 1.6.3. Make the contact 'now playing info' displays under the nickname in the conversation tab.

**Comment by Sbte** [comment]
Instead of the alias. I think that's doable.
