### ISSUE TITLE
Can't "steal" emoticons

### ISSUE THREAD

**Issue by AlineFreitas** [emesene/emesene#914]
Since I upgraded to emesene 2.*, I've noticed that I just cant steal someone else's emoticon. It's just me or everybody has this trouble?

**Comment by Sbte** [comment]
Did you try 2.11.9 or higher? Should be fixed there.

**Comment by AlineFreitas** [comment]
Well, I'm not sure, but the version I'm using is the latest one released on emesene's ppa. And now, I can't even log in! Something to do with the address book, I guess =/

**Comment by Sbte** [comment]
Ok, that's 2.11.9. The logging in is fixed in git master and should be fixed in the ppa soon.

Once you're able to login, could you tell me what exactly doesn't work and if there is any output if you run it from a terminal?

**Comment by AlineFreitas** [comment]
Here, When i ran it from a terminal, the error was the following:

Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/papylib/papyon/papyon/msnp/notification.py", line 796, in _address_book_state_changed_cb
    self._client.profile._cid = address_book.profile._cid
AttributeError: 'NoneType' object has no attribute '_

**Comment by Sbte** [comment]
I mean for the custom emoticons. The login issue is already fixed...

**Comment by AlineFreitas** [comment]
Well, there's no way that i can show you, but. Let's just say that NOW i'm using the newer develop version (emesene 2.11.10-devel), and even though by clicking with left button gives me the option to "save image as", and then it appears a window asking me to give a shortcut for the emoticon, but when i try to actually use it, it doesn't appear.

**Comment by Sbte** [comment]
And any terminal output?

**Comment by AlineFreitas** [comment]
No terminal output related to this issue, unfortunetly

**Comment by Sbte** [comment]
Does it happen with every custom emoticon?

**Comment by AlineFreitas** [comment]
Yes! Everytime i try to steal someone else's emoticon, I think I did it, but when I try to use it, it's not actually there

**Comment by AlineFreitas** [comment]
Anyone?

**Comment by c10ud** [comment]
check with 2.11.11 and see if it's in the emoticon list

**Comment by Mercilessgr** [comment]
I have the same problem here. Just tested with 2.11.11 no luck

**Comment by Sbte** [comment]
@pepeleproso, I guess you broke this with the conversation refactor?

**Comment by pepeleproso** [comment]
Please retry

**Comment by AlineFreitas** [comment]
Thanks :) It works now
