### ISSUE TITLE
Make the 'contact is typing' notification shows in the conversation window

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#916]
Would be nice if the 'contact is typing' notification shows also in the conversation window (like in emesene 1.6x and pidgin) as an Adium message!!

**Comment by Sbte** [comment]
Eh, getting that message every 5 seconds in a conversation would be really annoying. You can already see it from the icon, so I don't really see a need for this either...

**Comment by c10ud** [comment]
same as sbte, patches welcomed tho

**Comment by danielgomon** [comment]
Yes you're right. Maybe it can be placed in the window down side, like it is in WLM and emesene 1.6.x, because I think the actual icon it's not visible enough.

**Comment by danielgomon** [comment]
This can be an optional feature, like the actual pop-up message.

**Comment by danielgomon** [comment]
Can be something like this: http://static.inky.ws/image/816/image.jpg

**Comment by pepeleproso** [comment]
I implement this as a plugin.
I need to test it a little before land it into master

**Comment by pepeleproso** [comment]
Plugin commit is:
https://github.com/emesene/emesene-supported-plugins/commit/fa03e26d6a63658b0801d17bf42e829e0a496105

**Comment by danielgomon** [comment]
It works great, but can you make it don't show the plus color tags? only the nickname, like the notify-osd does (I mean the [c=] and [/c=])

**Comment by pepeleproso** [comment]
Done
