### ISSUE TITLE
The 'emesene not connecting' problem

### ISSUE THREAD

**Issue by Antonius-git** [emesene/emesene#919]
Hi guys - was just reading http://www.omgubuntu.co.uk/2011/11/emesene-not-connecting-quick-fix/

and there are some suggestions at a fix:

There is a fix for this. I had the same problem and this is how I fixed it:
Open the file /usr/share/pyshared/papyon/service/AB/**init**.py and comment out line 23. Replace it with this:

url = "http://local-bay.contacts.msn...." 

Hope this info is of any use.

**Comment by pepeleproso** [comment]
this is fixed in git master.

**Comment by c10ud** [comment]
great, you're suggesting us our quick hack (not a fix) through another
website lol

2011/11/10 Anthony
reply@reply.github.com:
