### ISSUE TITLE
emesene 1.6.3 do not connect 

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#923]
Hello i cant connect on msn
I am Ubuntu 11.04 and emesene 1.6.3 user
I also tried emesene2.11.9 but do not connect on emesene , i tried this fix : http://blog.emesene.org/2011/11/emesene-is-unable-to-connect.html but nothing happened

Is there any solution for emesene 1.6.3 ? I prefer emesene 1.6.3 because is much better

Thanks in advance :)

**Comment by c10ud** [comment]
emesene-1.6.3 development has been abandoned, sorry
