### ISSUE TITLE
conversation theme

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#924]
Is it possible to add as conversation theme the one witch is on emesene1.6.3 
I dont like so much adium themes , i'd like something more minimal , only with text

Thanks in advance :)

**Comment by arielj** [comment]
Go to preferences > extensions and choose TextOutput instead of AdiumOutput
on the proper extension category.

2011/11/11 ALdaperan <
reply@reply.github.com>

**Comment by ghost** [comment]
Yes i did that , is it now possible to modify it in order to be more compact ?
On emesene1.6.3 i could choose between gtalk theme , pidgin , default etc..

can i do this on emesene 2 ?

Thanks again :)

**Comment by c10ud** [comment]
install a minimal adium theme, not all themes are with bells and whistles

**Comment by pepeleproso** [comment]
you could try this adium theme
http://www.adiumxtras.com/index.php?a=xtras&xtra_id=1586

In order to modify text output we should add a new plugin

**Comment by ghost** [comment]
@ pepeleproso  the link toy send me do not open :(

**Comment by pepeleproso** [comment]
replace & amp; by &

**Comment by ghost** [comment]
how can i install it on ubuntu ?

**Comment by pepeleproso** [comment]
1- download the theme.
2- extract and copy the folder Simplicity.AdiumMessageStyle into /home/YOUR_USERNAME/.config/emesene2/themes/conversations

**Comment by ghost** [comment]
thank you :)
