### ISSUE TITLE
Blocked users and im groups still appears

### ISSUE THREAD

**Issue by AlineFreitas** [emesene/emesene#926]
I have some users and @groupsim.com contacts added on my Messenger, and even though I have already blocked them, their messages still come, bothering me, like they haven't even been blocked.

**Comment by c10ud** [comment]
please check with the privacy tab if they're effectively in the block list

**Comment by c10ud** [comment]
ping

**Comment by AlineFreitas** [comment]
Sorry, didn't see it. and YEAH, they are in the block list :(

**Comment by c10ud** [comment]
can you check they're not in the allow list too? this can happen if you use other clients that may mess up with your privacy lists.

we're using the strict "block" policy in emesene, so if they're really in your block list if they can talk to you it's a server error
