### ISSUE TITLE
Status icons over avatar

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#929]
Is it possible to appear the status icons over the avatars adn not on the right side ?
like emesene 1?
http://gnome-look.org/CONTENT/content-pre3/119460-3.png

**Comment by c10ud** [comment]
lots of unneeded image manipulation haxes required for this, i'm not gonna do it

**Comment by Sbte** [comment]
The blocked image still does this, so it shouldn't be too hard, but I'm not sure if we want this...

**Comment by danielgomon** [comment]
or you can do something like this: https://github.com/emesene/emesene/issues/900

**Comment by Sbte** [comment]
I'm not sure if we want that either. I like it the way it currently is, so I'm not going to do it at least. Maybe someone can implement either or even both as plugins.

**Comment by Sbte** [comment]
Someone can do this as a plugin if they feel like it. See:

https://github.com/emesene/emesene-supported-plugins
https://github.com/emesene/emesene-community-plugins
