### ISSUE TITLE
Add an option to hide/unhide the number of contacts

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#930]
Sometimes when I log-in in emesene the number of contacts doesn't appear, like in here: http://static.inky.ws/image/822/image.jpg

Sometimes they appear, like in here:  http://static.inky.ws/image/823/image.jpg

This happens randomly, with the same settings, I like to have a more 'clean' main window, without this kind of stuff; so I think that would be a good improvement if you add an option for choose to hide/unhide this, like it was in emesene 1.6.x.

**Comment by Sbte** [comment]
I've never seen this before. What options do you have enabled under Options, and under Options->Show?

**Comment by arielj** [comment]
You can modify Preferences > Main Window > Group format, the default is:

```
    [$b][$NAME] ([$ONLINE_COUNT]/[$TOTAL_COUNT])[/$b]
```

just change it to:

```
    [$b][$NAME][/$b]
```

**Comment by arielj** [comment]
I'm closing this because the option is already there, if you still have problems please reopen the issue.
