### ISSUE TITLE
Handwriting ?

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#931]
On emesene there is no option for Handwriting and i think its importan to exist
On windows live/kmess/amsn there is option for handwriting
Look the screenshot below
http://www.geomsn.com/wp-content/uploads/2011/07/Msn-Handwriting.gif

I think Handwriting shoyld be a high priority plugin-issue :)

**Comment by c10ud** [comment]
since handwriting requires an isf library and we don't want to add external deps since there's no python-isf available, this cannot be done, sorry
