### ISSUE TITLE
I do not get friends on/off notifications on facebook chat.

### ISSUE THREAD

**Issue by Osjar** [emesene/emesene#932]
I neither get any pop up notifications nor sound when a friend logs in or out in facebook chat. Emesene 2.11.11 on Ubuntu 11.04.

**Comment by Sbte** [comment]
I just pushed a fix. I don't have facebook, so please test it.

**Comment by Osjar** [comment]
The fix works, thank you very much. I didn't even have to compile, just type git clone in a terminal window :)

The pop up doesn't show a photo of the contacs though, but that might be just a fancy addition.

**Comment by Sbte** [comment]
Does the photo show in the contact list? And you're using the normal ubuntu notifications right?

**Comment by Osjar** [comment]
Yes, the photo shows in the contacts list. I don't know which notifications i use, i only know that the notification pop up and sound is the same as on pidgin.
