### ISSUE TITLE
ERROR papyon.protocol.notification

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#935]
[19:08:23 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 7d 07 06 00 00 00 00 00 00 00 00 00
7e 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
84 17 61 3a 4d c6 51 67 7e 01 00 00 00 00 00 00
[19:08:28 ERROR papyon.protocol.notification] Notification got error : 800 31
[19:08:35 ERROR papyon.protocol.notification] Notification got error : 800 32

[19:09:13 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
0b 3f 22 07 3b b2 07 00 00 00 00 00 00 00 00 00
ef 09 00 00 00 00 00 00 00 00 00 00 02 00 00 00
76 c1 4e 68 4a 3e 3e 5f ef 09 00 00 00 00 00 00

and other lines similar error

**Comment by c10ud** [comment]
http://www.hypothetic.org/docs/msn/reference/error_list.php

800's
800
Changing too rapidly
When the client tries to change the display name (REA) too rapidly, this error message will be sent in response to the commands that the server rejects. This does not affect renaming other principals.
    >>> REA 100 me@passport.com NAME\r\n
    <<< REA 100 2000 me@passport.com NAME\r\n
    >>> REA 101 me@passport.com NAME\r\n
    <<< REA 101 2001 me@passport.com NAME\r\n
    >>> REA 102 me@passport.com NAME\r\n
    <<< REA 102 2002 me@passport.com NAME\r\n
    >>> REA 103 me@passport.com NAME\r\n
    <<< REA 103 2003 me@passport.com NAME\r\n
    >>> REA 104 me@passport.com NAME\r\n
    <<< 800 104\r\n
Also when the client tries to change the status (CHG) too rapidly.
    >>> CHG 105 NLN 0\r\n
    <<< CHG 105 NLN 0\r\n
    >>> CHG 106 HDN 0\r\n
    <<< CHG 106 HDN 0\r\n
    >>> CHG 107 NLN 0\r\n
    <<< CHG 107 NLN 0\r\n
    >>> CHG 108 HDN 0\r\n
    <<< CHG 108 HDN 0\r\n
    >>> CHG 109 NLN 0\r\n
    <<< 800 109\r\n
