### ISSUE TITLE
Contact blocking

### ISSUE THREAD

**Issue by hit** [emesene/emesene#938]
Currently it is really difficult to determine wether a contact is blocked or not. I've done it accidently a couple of times.
User should see some feedback in conversation window - disabled inputbox and/or toolbar or something. Additionally there might be confirmation when using Block button in conversation to avoid accidental blocking.

I think there is no need to confirm blocking in main window.

**Comment by Sbte** [comment]
I agree on this

**Comment by c10ud** [comment]
i don't: rm is a far more dangerous command and does not require confirmation..

**Comment by Sbte** [comment]
rm is not clickable. I far too often (with that I mean more than once) accidentally hit that button.

And why not make the input inactive? Seems reasonable to me

**Comment by c10ud** [comment]
ok, go ahead
