### ISSUE TITLE
Tray icon's Quit is broken if not logged in

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#941]
I you are logged out, tray icon's Quit doesn't work because session is None, I remember someone moved everything to a session signal, can you make the Quit item from TrayIcon's LoginMenu to close emesene without the signal?

**Comment by Sbte** [comment]
My stupid mistake. I'll fix it when I'm not falling asleep behind my computer.

**Comment by arielj** [comment]
thanks! i'll wait for the fix
