### ISSUE TITLE
Avatar size in popup notification area

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#942]
The avatar in notification area seems too large. Like this figure: http://imageshack.us/photo/my-images/69/screenshottv.png/ . But sometimes it is a smaller one: http://imageshack.us/photo/my-images/189/screenshot1fl.png/ .

Is there any possible to set up it's size? Or just a special case of mine?

My environment is with emesene-2.11.11, gtk+-3.0.12, pygtk-2.24.0. And I've seem a contact's avatar is full size of the notification area but forget to screenshot it.

**Comment by c10ud** [comment]
Maybe we're passing the "raw" avatar to python-notify without even
trying to resize/whatever. We can add some resizing but it will lead
to blurry images if the starting image is too small

2011/11/16 moneycat
reply@reply.github.com:

**Comment by moneycat** [comment]
Ummm, that's true. But maybe the resizing  process can be triggered when the 'raw' image size is too large than some threshold?

I've found the contact's photo. It is a gif file with 300x300 resolution. In my environment, the popup message area is full by this message.
