### ISSUE TITLE
I can't receive files from contacts

### ISSUE THREAD

**Issue by fernandomt08** [emesene/emesene#945]
I've a issue about the file transference, when a contact send me a file I can see a message about this event, but I can see any button to accept the request, so could you help me with this problem?

**Comment by Sbte** [comment]
emesene version?

**Comment by hit** [comment]
Version: git

**Comment by fernandomt08** [comment]
I use PPA Version on Ubuntu 11.10

**Comment by Sbte** [comment]
I suppose it is the same error as with the messages that are not received. I guess it has something to do with cids.

**Comment by AlineFreitas** [comment]
Here it's the same thing. But not always.. I also use the ppa version: emesene 2.11.11

**Comment by AlineFreitas** [comment]
Anyone??

**Comment by Sbte** [comment]
@AlineFreitas: If this if this is the same bug as with the lost messages, this is the second most annoying bug ever. If we knew how to fix this, then we would.

Also note that only the people who already replied to this post get the message you just wrote in their mailbox. So that's one developer who already replied and the people who reported the bug that don't know how to fix it either. Asking every 4 days if anyone can help doesn't help at all.

**Comment by AlineFreitas** [comment]
I'm sorry, I just don't know what happen. I'm asking not if you have answers, but If you have any clue of what's wrong. See my point now?

**Comment by Soulsuke** [comment]
Just adding some informations here, from the git version: somehow, the first file transfer from a contact works flawlessly for me, both the notification and the button to accept/stop the file transfer appear, and the file is correctly received, but then it won't work again for any contact (including the one who originally sent the file) unless I close the conversation tab where the file transfer had happened, meaning I actually see the notification for the file transfer, but I have no way to accept/refuse it.
Latest git, Debian Sid x86_64

**Comment by pengshao** [comment]
I think gnome 3 somehow should take the responsibility...

**Comment by Sbte** [comment]
I just tried to reproduce this, but I can't see to manage to do that. Are there any steps that I can follow to reproduce this?

Also, it's not something with cids, because I removed those from filetransfers a while ago.

**Comment by Soulsuke** [comment]
So far, it seems that only certain clients cause this issue while sending files... At least, I'm experiencing it with contacts using older version of WLM (those who still let you choose a nickname), while it works well with Pidgin and Emesene. I'll try to reproduce it as soon as possible running emesene with -vvvv

**Comment by AlineFreitas** [comment]
Thanks for the update on this issue! Hope u can figure it out :)

**Comment by c10ud** [comment]
try with 2.12.3 and if it doesn't work reopen
