### ISSUE TITLE
Login to hotmail not working [Windows]

### ISSUE THREAD

**Issue by tsaimsbond** [emesene/emesene#947]
Today i upgraded  to the latest version (2.11.11) and i noticed that this issue remains.
For Windows users the issue is that the file "..hotmlog.htm" is missing!!! Entire "..\emesene2\data" folder is missing actually!! 

Anyway i' ve downloaded this "https://github.com/emesene/emesene/zipball/v2.11.11" and i manually copy-paste the missing folder!
Now it works fine!

**Comment by c10ud** [comment]
@arielj ^

**Comment by arielj** [comment]
I'm uploading 2.11.12-devel to github downloads
