### ISSUE TITLE
emesene doesn't show all the on-line contacts

### ISSUE THREAD

**Issue by MichaelKnight** [emesene/emesene#949]
Hi everybody. I had the impression that many of my friends were missing when I was using the ubuntu emesene client. However, using Windows 7+official Windows Live Messenger all of them are on-line.

I tried to change the way emesene groups and shows the contact list without success. Despite of all my friends where on-line only a few of them where showed on-line and the others ones off-line.

Any idea to solve this?

**Comment by Sbte** [comment]
Please try with latest git. It could be that you are experiencing 4c2c7ec2986627d16354eec9dd2a22015c4be5fd

**Comment by MichaelKnight** [comment]
Thank's for your answer but I can't find the way to install the git. Is ther any manual or howto?

sorry for the inconvenience.

**Comment by Sbte** [comment]
http://blog.emesene.org/2010/10/instructions-for-testers.html

**Comment by MichaelKnight** [comment]
Thank's for your help.

I did it and my version now is emesene 2.11.12-devel. However it still failing.

In emesene only appear 4 contacts online instead of 12 that do it in WLM official client. For an strange reason amsn is showing all of them. I think probably is a protocol matter.

**Comment by c10ud** [comment]
weird, the only thing that i can think of is a case of contacts being present both in the allow list and the block list.

Please enable all the options under Options->Show.. so you can see if your contacts are really absent or maybe they're just blocked.

If that doesn't work Option->Preferences->Live Messenger will show you your privacy lists. If any of those contacts is in the wrong list, just move them to the correct one (ALLOW)
