### ISSUE TITLE
some messages are lost in logger

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#950]
-Send 3 or more messages
-See contact history and they are there.
-Close emesene
-Open emesene and see contact history messages are gone.

Can anyone confirm this?

**Comment by Sbte** [comment]
Was your database locked?

**Comment by c10ud** [comment]
locked because of dead instances of emesene probably (!)

**Comment by pepeleproso** [comment]
yes DB was locked

**Comment by Sbte** [comment]
Could be due to the exception that happens half of the time when you close emesene (Queue not existing). Note sure how to fix that though.

**Comment by c10ud** [comment]
well, i had it when doing nasty closings with CTRL+C, but now that's
almost fixed it's strange -- maybe some unexpected exception while
developing?

2011/11/25 Sven
reply@reply.github.com:
