### ISSUE TITLE
Feature request for Music plugin

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#952]
A few things for Music plugin:
- A button to enable/disable the music plugin in my sub-message (similar to emesene's 1 plugin)
## 

I also would like to report a bug:
I was listening a music a few hours ago, I paused the music, now I'm listening another music, but still shows the older one.
I'm using rhythmbox. 
This bug used to happen in emesene 1, with the button to enable/disable I could "fix" the problem.

**Comment by pepeleproso** [comment]
please file a new bug in
https://github.com/emesene/emesene-supported-plugins/issues
for the enable/disable button.

second issue is
https://github.com/emesene/emesene-supported-plugins/issues/46
