### ISSUE TITLE
Tray Icon randomly disappears on Linux Mint 12 (Gnome 3)

### ISSUE THREAD

**Issue by dogmaxpeppe** [emesene/emesene#954]
When I receive messages on emesene, tray icon starts to flash, and it's normal... sometimes happened that, after receiving some messages, icon DISAPPEARS totally. I'm able to click on the "invisible icon" to open emesene, but I have to restart to make it appear again... I've tried to click on "Rewrite main window" (or something else, I'm using italian version so I don't know the right denomination) on extension tab, but it's useless.. I have to restart emesene.

**Comment by arielj** [comment]
I have a lot of problems with Linux Mint and panels (dissapearing volume control and other applets), I wouldn't be surprised if it's a Mint issue and not emesene's...

And now that Linux Mint moved to a modified version of gnome3 you can expect anything...

**Comment by c10ud** [comment]
issue with the os

2011/11/26 dogmaxpeppe
reply@reply.github.com:
