### ISSUE TITLE
Synchronizer Error

### ISSUE THREAD

**Issue by edwinkcw** [emesene/emesene#955]
When upgrading emesene from version 1 to 2, the sychronizer will show but it assumes that the user has used custom emoticon. That causes the emesene hangs. 

I fixed it by modifying the line 122 in emesene/e3/synch/synchronizers/emesenesynch.py to the following, so that when the map cannot be found, the program still run normally. 

try:
                fmap1 = open(os.path.join(self.__source_path,                   ..."custom_emoticons", "map"), 'r')
            except:
                fconfig.close()
                return

I would like to commit it using git but it returns 403 when I push it. I don't know how to contribute my code using git. If possible, I hope I can contribute some and help to fix some bugs. 

Best Regards,
Edwin edwinkcw@gmail.com

**Comment by Sbte** [comment]
Here's our git guide: https://github.com/emesene/emesene/wiki/GitHowTo

But I think you're missing your ssh key in your github account: https://github.com/account/ssh

Instructions can be found at the right of that page. As soon as it works, just attach a pull request to this issue, and I'll push it to emesene master ^^

**Comment by Sbte** [comment]
Pulled 873667acb1b464a3e82ca71261c36eb408b744c5
