### ISSUE TITLE
Error receiving nudges

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#957]
Here's the case:
I close the conversation pressing esc.
The user send me a nudge.
The contact window shows, but now, shows me an empty window, without the nudge message...

In console (without -vvv):

`** Message: console message: undefined @1: SyntaxError: Parse error`

Not sure if there's any relation the message with the bug...
This happened like 2 or 3 times with me.
I'm using the latest github emesene version.

**Comment by pepeleproso** [comment]
can you retest with latest git?

**Comment by Stiveknx** [comment]
Fixed!
Thanks.
