### ISSUE TITLE
Error when dragging a group

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#958]
Drag a contact or group to the empty space a the bottom (after the last contact). Then I get this exception.

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/ContactList.py", line 841, in _on_drag_drop
    pos = widget.get_dest_row_at_pos(x,y)[0][0]
TypeError: 'NoneType' object is not subscriptable
/home/sven/emesene/emesene/gui/gtkui/__init__.py:89: GtkWarning: You must override the default 'drag_drop' handler on GtkTreeView when using models that don't support the GtkTreeDragDest interface and enabling drag-and-drop. The simplest way to do this is to connect to 'drag_drop' and call g_signal_stop_emission_by_name() in your signal handler to prevent the default handler from running. Look at the source code for the default handler in gtktreeview.c to get an idea what your handler should do. (gtktreeview.c is in the GTK source code.) If you're using GTK from a language other than C, there may be a more natural way to override default handlers, e.g. via derivation.
  gtk.main()
```

GtkWarning: You must override the default 'drag_drop' handler on GtkTreeView when using models that don't support the GtkTreeDragDest interface and enabling drag-and-drop. The simplest way to do this is to connect to 'drag_drop' and call g_signal_stop_emission_by_name() in your signal handler to prevent the default handler from running. Look at the source code for the default handler in gtktreeview.c to get an idea what your handler should do. (gtktreeview.c is in the GTK source code.) If you're using GTK from a language other than C, there may be a more natural way to override default handlers, e.g. via derivation.

**Comment by c10ud** [comment]
cannot repr

**Comment by Sbte** [comment]
I can:

Drag a contact or group to the empty space a the bottom (after the last contact). Then I get this exception.
