### ISSUE TITLE
After receiving a file by msn, I have no choice but logout and login to receive another one.

### ISSUE THREAD

**Issue by gracegreen** [emesene/emesene#961]
After receiving a file from msn, I can't receive the second file, nothing will happen when I click accept button, and I have to logout and login, then another file can be received.

once it happns,It will happen always.
but it does not happen everytime.

**Comment by gracegreen** [comment]
emesene 2.11.11,ubuntu 11.10

**Comment by gracegreen** [comment]
the file request is from a microsoft live messenger 14.0.8117.416 in windows xp.

**Comment by c10ud** [comment]
#960

**Comment by c10ud** [comment]
ah, sbte closed the other one

**Comment by gracegreen** [comment]
sorry for submit twice

**Comment by c10ud** [comment]
#945
