### ISSUE TITLE
Remove "focus" from emesene window

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#962]
He's the occasion:
I open emesene, than I minimize it.
My internet goes down ..
Emesene was minimized, since my internet it's disconnected, emesene losses connection, and, focus the window without my intervention... That's reaaaaaaaly annoying, I'm doing another thing like typing something, reading some text than emesene window comes in to my face.

Would be cool if I could disable it.

**Comment by Sbte** [comment]
The main window or the conversation window?

**Comment by Stiveknx** [comment]
I mean the login window.
sorry for the bad english.

This focus shows when you disconnect and emesene try to auto-connect again
