### ISSUE TITLE
emesene makes grow .xsessions_errors up to fill the disk

### ISSUE THREAD

**Issue by jcasanov** [emesene/emesene#966]
Recentrly i got a warning from gnome indicating i had too little space left, looking to where the space was used i found that the .xsessions_errors file was 56GB and the bulk of it was this message:

(emesene:2595): GStreamer-WARNING **: gstsystemclock: write control failed in wakeup_async, trying again : 32:Tubería rota

also, i logout from emesene and cleaned up the file with "> .xsessions_errors" and half hour later it was growing again.

**Comment by arielj** [comment]
I can't reproduce it, my .xsessions_errors file is only 4kb and there's no emesene warnings/errors inside.

Maybe you have some gstreamer package missing?

What's your OS?

**Comment by jcasanov** [comment]
what gstreamer package should i need... i know removed some python related packages a few weeks ago (it was apt decision when dropping a package i was not using anymore)... i'm using debian 6

**Comment by Sbte** [comment]
You need at least python-gst (>=0.10) I think. You might have more luck asking gstreamer people about this though.
