### ISSUE TITLE
User should be able to choose where he would like to store his/her own chat history

### ISSUE THREAD

**Issue by AlineFreitas** [emesene/emesene#967]
It's just a suggestion, but maybe users should choose if they want to store their logs in a diferent way, such as html files, that are portable and easily accessible.

**Comment by pepeleproso** [comment]
This have to be done as a plugin. You need a new 'history exporter' extension that write html instead of txt files.
Maybe we can use adiumtextbox to get html write with a few lines, but it won't work if you didn't have webkit instaled.

**Comment by matiasdelellis** [comment]
Idea..
Why not make a plugin compatible with msn plus?.

**Comment by AlineFreitas** [comment]
@pepeleproso That's exactly what I'm planning to do ^^ After all, I want it, and it's about time i give sth back to Emesene :) I'll try to do it so :D As soon as i'm on vacation, of course. But i'll let you know \o

**Comment by c10ud** [comment]
#1118
