### ISSUE TITLE
After last pull, the output seems strange

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#969]
With commit: e88c900ca8cafa73644610c898cd01caaa6540e6
The output format strange: http://imageshack.us/photo/my-images/827/screenshotat20111228104.png/

Is this side-effect of recently theme changed?

**Comment by Sbte** [comment]
Could you try a `git reset --hard origin`?

**Comment by moneycat** [comment]
$ git reset --hard origin
HEAD is now at e88c900 core: Don't steal focus when disconnected

but the conversation window still the same

**Comment by Sbte** [comment]
Could you go to `emesene/themes/conversations` and do `ls -R` and post the output of that somewhere?

**Comment by moneycat** [comment]
$ ls -R
.:
Ravenant.AdiumMessageStyle/  renkoo.AdiumMessageStyle/

./Ravenant.AdiumMessageStyle:
Contents/

./Ravenant.AdiumMessageStyle/Contents:
Info.plist  Resources/

./Ravenant.AdiumMessageStyle/Contents/Resources:
Footer.html  Header.html  img/  Incoming/  javascripts/  main.css  mask_avatar.png  mask_reflection.png  Outgoing/  Status.html  Variants/

./Ravenant.AdiumMessageStyle/Contents/Resources/img:
bg.jpg  status.png

./Ravenant.AdiumMessageStyle/Contents/Resources/Incoming:
buddy_icon.png  Content.html  Context.html  NextContent.html  NextContext.html

./Ravenant.AdiumMessageStyle/Contents/Resources/javascripts:
reflection.js  scroll.js

./Ravenant.AdiumMessageStyle/Contents/Resources/Outgoing:
buddy_icon.png  Content.html  Context.html  NextContent.html  NextContext.html

./Ravenant.AdiumMessageStyle/Contents/Resources/Variants:
Avatars.css     Blue-Grey.css    Blue-Red.css    Green-Grey.css    Green-Red.css  Grey-Green.css   Grey-Red.css     Purple-Green.css  Purple-Red.css  Red-Green.css  Red-Purple.css
Blue-Green.css  Blue-Purple.css  Green-Blue.css  Green-Purple.css  Grey-Blue.css  Grey-Purple.css  Purple-Blue.css  Purple-Grey.css   Red-Blue.css    Red-Grey.css

./renkoo.AdiumMessageStyle:
Contents/

./renkoo.AdiumMessageStyle/Contents:
Info.plist  Resources/

./renkoo.AdiumMessageStyle/Contents/Resources:
Demo.html  Footer.html  images/  Incoming/  incoming_icon.png  Outgoing/  outgoing_icon.png  Renkoo LICENSE.txt  Status.html  Styles/  Topic.html  Variants/

./renkoo.AdiumMessageStyle/Contents/Resources/images:
alert.png           blueIndicatorAlt.gif  greenCurves.gif        redBackground.gif    redIndicator.gif      steelCurves.gif        steelIndicator.png    yellowCurves.png        yellowTL.png
blueBackground.gif  blueIndicator.gif     greenCurves.png        redBackground.png    redIndicator.png      steelCurves.png        typing-left.png       yellowHeading.jpg       yellowTR.png
blueBackground.png  blueIndicator.png     greenIndicator2.png    redCurves.gif        silverBackground.gif  steelHeading.jpg       typing-right.png      yellowIndicator2.png
blueCurves.gif      DummyContact.png      greenIndicatorAlt.gif  redCurves.png        silverCurves.gif      steelIndicator2.png    yellowBackground.gif  yellowIndicatorAlt.gif
blueCurves.png      greenBackground.gif   greenIndicator.gif     redIndicator2.png    steelBackground.gif   steelIndicatorAlt.gif  yellowBackground.png  yellowIndicator.gif
blueIndicator2.png  greenBackground.png   greenIndicator.png     redIndicatorAlt.gif  steelBackground.png   steelIndicator.gif     yellowCurves.gif      yellowIndicator.png

./renkoo.AdiumMessageStyle/Contents/Resources/Incoming:
buddy_icon.png  Content.html  Context.html  NextContent.html  NextContext.html

./renkoo.AdiumMessageStyle/Contents/Resources/Outgoing:
buddy_icon.png  Content.html  Context.html  NextContent.html  NextContext.html

./renkoo.AdiumMessageStyle/Contents/Resources/Styles:
alternating.css  Header.css  main.css  noname.css  Topic.css

./renkoo.AdiumMessageStyle/Contents/Resources/Variants:
Blue on Green Alternating.css   Blue on Yellow No Names Alt.css  Green on Yellow Alternating.css   Red on Steel No Names Alt.css    Steel on Red Alternating.css      Yellow on Green No Names Alt.css
Blue on Green.css               Blue on Yellow No Names.css      Green on Yellow.css               Red on Steel No Names.css        Steel on Red.css                  Yellow on Green No Names.css
Blue on Green No Names Alt.css  Green on Blue Alternating.css    Green on Yellow No Names Alt.css  Red on Yellow Alternating.css    Steel on Red No Names Alt.css     Yellow on Red Alternating.css
Blue on Green No Names.css      Green on Blue.css                Green on Yellow No Names.css      Red on Yellow.css                Steel on Red No Names.css         Yellow on Red.css
Blue on Red Alternating.css     Green on Blue No Names Alt.css   Red on Blue Alternating.css       Red on Yellow No Names Alt.css   Steel on Yellow Alternating.css   Yellow on Red No Names Alt.css
Blue on Red.css                 Green on Blue No Names.css       Red on Blue.css                   Red on Yellow No Names.css       Steel on Yellow.css               Yellow on Red No Names.css
Blue on Red No Names Alt.css    Green on Red Alternating.css     Red on Blue No Names Alt.css      Steel on Blue Alternating.css    Steel on Yellow No Names Alt.css  Yellow on Steel Alternating.css
Blue on Red No Names.css        Green on Red.css                 Red on Blue No Names.css          Steel on Blue.css                Steel on Yellow No Names.css      Yellow on Steel.css
Blue on Steel Alternating.css   Green on Red No Names Alt.css    Red on Green Alternating.css      Steel on Blue No Names Alt.css   Yellow on Blue Alternating.css    Yellow on Steel No Names Alt.css
Blue on Steel.css               Green on Red No Names.css        Red on Green.css                  Steel on Blue No Names.css       Yellow on Blue.css                Yellow on Steel No Names.css
Blue on Steel No Names Alt.css  Green on Steel Alternating.css   Red on Green No Names Alt.css     Steel on Green Alternating.css   Yellow on Blue No Names Alt.css
Blue on Steel No Names.css      Green on Steel.css               Red on Green No Names.css         Steel on Green.css               Yellow on Blue No Names.css
Blue on Yellow Alternating.css  Green on Steel No Names Alt.css  Red on Steel Alternating.css      Steel on Green No Names Alt.css  Yellow on Green Alternating.css
Blue on Yellow.css              Green on Steel No Names.css      Red on Steel.css                  Steel on Green No Names.css      Yellow on Green.css

**Comment by Sbte** [comment]
And if you remove the themes folder and `git reset --hard origin`, does it work then?

**Comment by moneycat** [comment]
Another test:
$ git checkout c1bc
...
HEAD is now at c1bccb5... Revert "Trying to fix potential segfault in webkitgtk."

And now the conversation window is fine.

But after checkout to master...It is the strange window format...

**Comment by Sbte** [comment]
Well, @c10ud had the same problem and he fixed it by deleting the themes folder and doing a `git reset --hard origin`

**Comment by moneycat** [comment]
...:~/Downloads/Program/emesene$ rm -rf emesene/themes/conversations/*
...:~/Downloads/Program/emesene$ git reset --hard origin
HEAD is now at e88c900 core: Don't steal focus when disconnected

still the same

**Comment by Sbte** [comment]
@pepeleproso ^

**Comment by c10ud** [comment]
whoops, now that i double checked it worked for one account and not for another one...wtf?

**Comment by Sbte** [comment]
Ok, that totally blows my mind...

**Comment by c10ud** [comment]
@moneycat which OS do you have?

**Comment by moneycat** [comment]
The problem one is on Ubuntu 11.10 with gnome-shell.

But my laptop, Gentoo, there is only text output. No options could change settings in preferences.

**Comment by Sbte** [comment]
What is the exact commit that broke it?

**Comment by moneycat** [comment]
Oh...I didn't try it. I just rollback to c1bccb5e65828b64619cab107d5f1c7d977896d5 and everything works fine.

**Comment by c10ud** [comment]
[13:33] <c10ud> there
[13:33] <c10ud>  [
[13:33] <c10ud>   "adium_theme_variant",
[13:33] <c10ud>   ""
[13:33] <c10ud>  ],
[13:33] <c10ud> something set that as ""

2011/12/28 moneycat
reply@reply.github.com:

**Comment by c10ud** [comment]
[13:37] <sbte> c10ud, maybe that "" set it to the default with the old
adium theme, but not with the new one
[13:38] <sbte> I think I changed the variants once, so for me that
entry is filled
[13:38] <sbte> but you probably didn't
[13:38] <c10ud> maybe, yeah, once upon a time there was no support for variants
[13:38] <sbte> so for you it always worked until the default wasn't
set by the adium theme
[13:38] <sbte> so... we fix that
[13:39] <c10ud> anyway in order not to make people cry i'd go for: if
variant == "": variant = variants[0]
[13:39] <c10ud> i think pepe knows best on this tho
[13:39] <sbte> yeah

@pepeleproso ^

2011/12/28 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by moneycat** [comment]
[
  "adium_theme_variant", 
  ""  
 ], 

Yes. This is set as "" in my config file.

**Comment by moneycat** [comment]
Solution confirmed. Thanks a lot.
