### ISSUE TITLE
KDE, tray icon mode (not message menu) raise window on click

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#976]
When you reduce to panel emesene, and click on the tray icon it disappear, when you reclick on the tray icon it appear, but reduced in the panel.

I purpose to show the window. (like transmission does in example)

I would like to try to change this behaviour, but I don't know exactly whitch file to edit and what metod to touch..

**Comment by Sbte** [comment]
You could try to add

```
window.present()
```

below this line:

https://github.com/emesene/emesene/blob/master/emesene/gui/base/Handler.py#L597

Is that what you mean?
