### ISSUE TITLE
Add a way to intercept messages

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#977]
Currently, it is not possible to use a plugin to change a message before it reaches the conversation window. It would be nice if we added a way to intercept those messages, preferably even in a way that the plugins can't conflict with each other.

The same for sending messages, or even signals in general.

**Comment by Sbte** [comment]
Ok, for sending I found a solution, but only one plugin at a time can use it:

conversation = self.session.get_conversation(cid)
conversation.input.on_send_message = self.custom_handler

Should we maybe add callback arrays everywhere where this could be necessary?

**Comment by arielj** [comment]
I'd like some signal thing, we can have two signals: message_arrived and sending_message (or something like that).

For message_arrived, we trigger the signal as soon as it arrives and let the subscribers modify the value of message.

For sending_message, we trigger the signal just after pressing enter on the conversation, subscribers should be able to modify "message" and also to stop the delivery of the message (returning false for example, so we can have something like the old emesene1 slash commands :D)

**Comment by Sbte** [comment]
@arielj, we already have that. See the cmdline plugin in the community repo.

Just signals wouldn't work. We'd also have to lock the message first, because other wise it would be sent before some other method would return false. That or the methods would have to be called in the right order. But that could cause terrible lag.

**Comment by c10ud** [comment]
@Sbte do we still need this?

**Comment by Sbte** [comment]
If we want emesene to be plugin-friendly, then yes. I don't think it can do harm to let this bug open until someone feels like fixing it.

**Comment by DragaO** [comment]
You can try something like hooks on Drupal (php-based). Tha basic idea is to have an group of functions with "special" names. I'll take the case of modify the messages before they appear.

<pre>
// this invokes all functions named "*_message_pre" and passes
// "conversation" as an argument
// all those function have the possibility to modify the "conversation" object
call_hooks('message_pre', conversation);
</pre>


I don't know Python, so I don't know if Python supports something like pointers to pass "conversation" like a pointer instead a "normal" variable. This kind of thing happens on Drupal with Hooks.

The workflow for your example would be something like this:
1. call hooks to modify the message/conversation
2. execute (show, log the message, etc; in this case)
3. call hooks again, but now to modify after message appears (like change the way it is stored in log)

this will be really useful, because i'd miss so much the cript plugin of emesene1, and having something like Drupal hooks can help to save the logs in a better way (in emesene1, the message SENT wasn't encrypted in the logs, only the message RECEIVED (which could not be read anymore)

**Comment by Sbte** [comment]
@DragaO: This can all already be done using the current signals and the method I described in 

https://github.com/emesene/emesene/issues/977#issuecomment-3404549

The only this missing is that we need a way to call functions that override the send method in the correct order. Currently there can't be two plugins relying on this that are activated at the same time. Atm there's only one plugin that uses this, so there are no problems.

What you suggested doesn't depend on this.

**Comment by DragaO** [comment]
@Sbte i've suggested a differente thing.

the method that i've suggested support two or more plugins at the "same" time (obviously must have a order).

look, i don't know python programming, but i'm suggesting that a function calls a set of another functions based on their names.
it's too hard to me to explain with words (and my english isn't that good), so, i'll try some php code to explain, ok?

<pre>
function my_module_pre_receive_message(&$message)
{
    // search for "Hi" and replaces with "Hello" in the message
    // in php, when we use "&" in a variable, this means a pointer, not the value
    $message = str_replace('Hi', 'Hello', $message);
}

function my_module_post_receive_message(&$message)
{
    // undo the "pre_receive_message"
    $message = str_replace('Hello', 'Hi', $message);
}


function receive_message()
{
    // ... do some stuffs that doesn't matter
    
    // "$message" contains the original message
    // before show in the window, we ask other functions to modify it's content
    
    // let's say that the message is the string "Hi John Doe"
    call_hooks('pre_receive_message', $message);
    // the above line calls the function "my_module_pre_receive_message" passing "$message"
    // as an argument
    
    // now the $message is "Hello John Doe"

    // ... more another stuffs
    
    // shows the message in the window
    
    // now we ask again after we showed the message in the window
    call_hooks('post_receive_message', $message);
    
    // ... maybe more another stuffs

}
</pre>


if we had another function terminating with "pre_receive_message", that will be called too at this moment; the same applies to "post_receive_message".
if you want, i can implement a version of the function "call_hooks" in php to clarify more.

what'd you say?

**Comment by Sbte** [comment]
We don't need this. We could just do

``` python
conversation.input.send_callbacks.append(callback)
```

and then

``` python
for callback in self.send_callbacks:
    callback(*args)
```

Or we could use a signal, but that would probably just make things more complicated...

The only thing we need to look into is handling plugins that are unloaded and the order of the callbacks.

**Comment by c10ud** [comment]
i think we can implement it easily, we just execute callbacks on the e3.Message before getting it going but first we sort them
[17:21] <c10ud> adding some optional priority argument
[17:21] <c10ud> 0 = prio max
[17:21] <c10ud> - whatever = prio min
[17:21] <c10ud> with default = -99 or something
[17:22] <c10ud> then if and when it will be used, we'll know what to do with it
[17:23] <c10ud> plugins take care of (un)registering themselves, problem solved

**Comment by c10ud** [comment]
plugins just set type Message.TYPE_UNK and it won't be processed by backends (we can add a check for ui also) 64f19ca72767eebdfbdd6ebe2cc36bee9fbd596f

**Comment by marianoguerra** [comment]
we could implement a generic middleware approach to message handling (and it could be generic to apply to other signals)

basically you register a middleware for one signal, so when it's emitted it's applied from first to last on input and from last to first on output (like layers on an onion), each one returns the signal (eighter modified or not) and is passed to the next one, the resulting signal is then handled by e3

some resources:

http://confreaks.com/videos/961-mwrc2012-rack-middleware-as-a-general-purpose-abstraction
http://www.python.org/dev/peps/pep-0333/#middleware-components-that-play-both-sides

one example of this could be, drop any message that contains v14gr4 in it, so you make a middleware that is registered on the incomming message signal, it checks for the word and if it's contained it can replace it for another message or return None to inform that the signal shouldn't be handled.

another middleware could be drop caps, that transforms allcaps (CRUISE CONTROL FOR  COOL) to lowecase on in/out messages.

another could apply a spell checker,  one to replace words for other ones, one to expand bit.ly links to the ones it points to, another one to add a brief description of a sent link, one to reply a nudge with another one, autoreply on busy status etc. (you get the idea :)

all of this could be generically handled by this approach and the good thing is that they are composable, you can register one after the other and they will play nice between them.

what do you think?

if I have some time I can work on it on a branch, of course, this would work at the e3 level and be independent of the UI.

**Comment by Sbte** [comment]
As long as it doesn't break the current implementation, it's all fine by me.

**Comment by c10ud** [comment]
@marianoguerra the problem here (hypotetical, since we currently don't have any consumers of this idea) is: what if i have an encryption plugin and a translate one? I want the message first translated and then encrypted...how can i make it sure they play nice with each other in a lazy way? that's why i thought of a "weighted" list.. :p

**Comment by marianoguerra** [comment]
sure, maybe a way to specify that this processor should be the last one
to transform the message and if more than one tries to be "the last one" then
fail to register them and show some king of message

Quoting Riccardo (2012-08-26 19:19:26)

> @marianoguerra the problem here (hypotetical, since we currently don't have any
> consumers of this idea) is: what if i have an encryption plugin and a translate
> one? I want the message first translated and then encrypted...how can i make it
> sure they play nice with each other in a lazy way? that's why i thought of a
> "weighted" list.. :p

**Comment by c10ud** [comment]
Looks overcomplicated to me, i'm fine with either solution (or even none) but given the current consumers or wannabes ( = 0 atm) i'd go with the simpler solution here, which means: mine.

ofcourse unless you tell me there's something really wrong with it (apart for the fact that sorting should be done when appending)

Then, if we want to add and use call hooks to/in some part of the code, we just add an extension and consume it from the plugins..

in the particular case of messages, if we don't want to pass messages to ui or backend, we just change the type (eg. TYPE_UNK, i added a check in the backends, it's already in master..messages with invalid type are discarded... we can ofcourse add some other type but we have plenty..and we can add a check in ui too)

**Comment by c10ud** [comment]
new commit with clear view on the diff

**Comment by c10ud** [comment]
work committed in the main repo

**Comment by c10ud** [comment]
sample usage: https://github.com/emesene/emesene-community-plugins/commit/91e9f0bf8298bbecb0c7640a8ef5422bee389ba3

if you want to conver some other plugin, yw
