### ISSUE TITLE
Close tabs icon disappeared

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#979]
Not sure if this is a feature or not, but the icon (X) to close conversation tabs disappeared

**Comment by Sbte** [comment]
I just noticed this too. I'll do a regressions test.

**Comment by Sbte** [comment]
a93a040d3e6483d70eb1b00a357ec0fe38643503 is the first bad commit
commit a93a040d3e6483d70eb1b00a357ec0fe38643503
Author: Jose Rostagno joserostagno@vijona.com.ar
Date:   Wed Jan 4 17:43:57 2012 -0300

```
Use new method instead of after_new_conversation_extension and add a conversation_lock property to Session
```

:040000 040000 20c820d5bb802ea69923687f5a455761d86bb355 11904a8d5d3bf4a98a9b4d6034c5e0a91f3f7fb4 M  emesene
