### ISSUE TITLE
Info in Information tab copiable

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#984]
when you right click a contact > view information, you can't copy the email to the clipboard, would be a little usability improvement to make it copiable (make a right click menu with "copy to clipboard")

i don't have time right now but i think it's not too hard so new developers can give it a try ;)

**Comment by pepeleproso** [comment]
done in https://github.com/emesene/emesene/commit/e43d69507168c4ce75bc99f77307fbcfcd3eeb69

thanks @lfottaviano

**Comment by lfottaviano** [comment]
you are welcome :)

**Comment by Sbte** [comment]
@lfottaviano, next time just write `Closes #984` in the commit message. Then GitHub will close the issue automagically. ;)

**Comment by lfottaviano** [comment]
good, no problem!
