### ISSUE TITLE
How to use jabber? How to use anything apart from MSN protocol?

### ISSUE THREAD

**Issue by mountpeaks** [emesene/emesene#985]
I have a simple question, I've installed emesene and it was written that it supports jabber, but I can't see any options for protocols except MSN and dummy. The official page says nothing, there is no good FAQ, no workarounds. Does it support AIM/ICQ? 
(I have a feeling emesene badly needs contributors)

**Comment by Sbte** [comment]
Added to the FAQ: http://blog.emesene.org/p/faq.html

So as a short answer: no, there's no AIM/ICQ support.

And yes, we need contributors. So feel free to do so ;)
