### ISSUE TITLE
Emesene and web (home.live.com or hotmail) shows different contacts

### ISSUE THREAD

**Issue by matiasdelellis** [emesene/emesene#987]
Now has emesene and www.home.live.com conected like invisible, and show diferents contacts.

A contact showed in emesene, was was eliminated in WLM 2011.
In Preferences/Live Mensseger can not find this contact in any way.. :S

Other contact (That Not know.. :S) is showed in web but not in emesene.
In Preferences/Live Mensseger this apear in "Admited" list with white, but not in the emesene list!!.

Screenshot showing this. http://db.tt/UyaKfDvQ

p.s.: Now.. When finish making the screenshotI noticed that now are 8 contacts on the website, and in emesene continue the same contacts.

**Comment by matiasdelellis** [comment]
p.s: Now I'm on windows 7 with WLM 2011.
The first contact effectively is not listed. and the second yes..

As I once said ... The tab with the list of admitted/removed/etc, in wlm 2011 not exist... So, I can not compare and I think it should be removed from emesene because it provides bad results!.

Need some type of debug?. Please explain to me how to.

Regards.

**Comment by c10ud** [comment]
we just show what the server gives us, probably microsoft is
changing/changed something with the whole wlm2011/social transition
maybe migrating to a new type of contact lists.

difficult to say what's really going on, but i must say our
preferences-live messenger tab must be coherent with what the contact
list is showing. or maybe some "desynchronization" has happened with
your list (some contacts have some flags, some don't, and the whole
thing is confused)

you could try fixing by hand e.g. add and move to block list then
delete who you don't want it, re-add who you want to keep.

not sure if it helps

2012/1/16 matiasdelellis
reply@reply.github.com:

**Comment by matiasdelellis** [comment]
Thanks c10ud.
Now test in WLM 2009 (Witout any social function) on windows Vista, and show the same contacts that web and wlm2011.

Searching in the list the first contact (The eliminated that is showed in emesene), this appaers in a new categorie "Others contacts of windows live" with a link "Invite to mensegger". But no show like conected, not show picture, nicks, etc..
If double click, launch home.live.com

Also if right click show a popup menu with the option to eliminate it. but not like to removed it again until I know what happens.

Now I'm installing pidgin and Kmess to compare.

En español..  asi me entienden mejor.. ;)
Ahora probe con WLM 2009 (Que no tiene funciones sociales) sobre windows vista, y muestra los mismos contactos que la version web y wlm2011

Cuando busco el contacto que habia eiliminado con la barra de filtrado, este aparece en una nueva categoria llamada "Otros contactos de Windows Live" con un link que dice "Invitar a menseger", pero no muestra su estado de coneccion, ni la foto de contacto, ni nada..
Cuando hago click derecho me muestra un menu con la opcion para eliminarlo, pero no lo quiero probar hasta que se solucione esto.
Tambien busque en los contactos de hotmail (que son diferentes a los de msn), pero no lo encontre ahi.

Bue.. y ahora estoy intalando pidgin y kmess para comprarar..

Gracias por todo..

**Comment by matiasdelellis** [comment]
Well..
Tenting Pidgin: No show erase contact in any way.
Testing Kmess: No show the contact.. .

Testing empathy (That use telepathy-buterfly based on papyon): Show this contact exactly like emesene.

So.. I assume a bug of papyon..

**Comment by matiasdelellis** [comment]
Any idea??.
I returned to do the tests and is the same.
Shows the same amount of contacts, but wrong. This time continues to show the contact deleted, and does not show my contact, (I have also added me to msn to see the states.: S)

The same with empathy. Kmess, pidgin and officials msn okey.

Please.. Explain to me how to make a good debug.Definitely a bug of papyon.

Regards.

**Comment by c10ud** [comment]
emesene -vvv should provide a good log, when address book is received you see all your contacts placed in the respective lists
