### ISSUE TITLE
forgets my avatar

### ISSUE THREAD

**Issue by kapcom01** [emesene/emesene#988]
Every time i login, my avatar photo reverts to the rocket photo.

**Comment by Sbte** [comment]
I suspect you have a broken profile. See Preferences->Live Messenger.

What version of emesene do you use? The latest emesene version should tell you to fix it on startup.

**Comment by c10ud** [comment]
is your profile fixed? this problem should happen when the server
rejects your picture change and usually that happens because the
profile on the server is broken: emesene should warn you about this on
start (in recent versions)
2012/1/19 Emmanouel Kapernaros
reply@reply.github.com:

**Comment by kapcom01** [comment]
I have emesene 2.11.11 and uploading my picture from live.com (Preferences > Live Messenger) it worked. But I am wondering if I have to click on the "Keep-alive conversations" and also do I have to change my picture in this way every time?

**Comment by c10ud** [comment]
keep-alive conversations doesn't have anything to do with this issue

also, if you followed the procedure 100% the picture will correctly
saved/retrieved from now on

2012/1/19 Emmanouel Kapernaros
reply@reply.github.com:
