### ISSUE TITLE
Extension updates TODO

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#989]
Just keeping a list of ideas here. Anyone who wants to work on this can do so. I won't have time in the next few weeks I think.
- ~~Make the Collections single instance. This can be done using extensions for the Collections. This probably means that we need separate classes for community and supported themes/plugins.~~
- ~~Don't download directly to the themes/plugins folders. This might cause breakage when emesene is aborted while downloading. Just download to a temp dir, and then move to the right place. If the download is an updated, rather than replacing files, old content should be removed first using the remove method.~~
- ~~Derive the UpdateList from the DownloadList. This means that the DownloadList needs a self.collections dict, which is possible now the Collections are single instance extensions. This will also mean we get a cleaner implementation of the DownloadList.~~
- Check for updates at startup. Only do this after the previous two have been implemented
- Implement a refresh button on the updates tab.

This post should be updated when something is implemented

**Comment by c10ud** [comment]
> Check for updates at startup.

i'd leave that to the user

**Comment by Sbte** [comment]
We want to make updating to a new version of emesene as smooth as possible. If that requires a new version of a plugin, then we should update it. Not that anyone is updating plugins atm...

**Comment by Sbte** [comment]
temp dir usage implemented

**Comment by c10ud** [comment]
> Implement a refresh button on the updates tab.

do we need this? clicking on updates seems to refresh already...?

**Comment by Sbte** [comment]
It doesn't refresh for real. It just acts like it does :P

So yeah, for people who always suspend instead of shut down, we need this. I think. But it can be done while integrating the progress bar into the tab.

**Comment by c10ud** [comment]
ok, so now we have progress bars inside the tab thanks to @pepeleproso 

i am a bit worried about automagically check for plugin updates though, imagine 100k requests per day or MORE to gh. (ubuntu popcon says ~100k install from users who enable popcon..then there are users which don't, then there are 3229349723 other distros, and windows -- macs are a few)

**Comment by Sbte** [comment]
We can do it like weekly and after emesene updates. And it only checks when you have installed plugins. So it'd be fine. And there could be an option to disable it.

**Comment by Sbte** [comment]
About the automatic updates:

We can not check for updates if the user has not more than 1 theme per category and no plugins. This rules out most of the users (I think). If there are updates, we can open the preferences and show the update tab. I just have to think of a friendly way of doing this without hurting the qt4ui (maybe add a show_updates_tab method on the preferences that has a pass on qt).

Also, the previous emesene version and update date have to be saved in the global config. Then we can update weekly. And there has to be an option to disable it on the general preferences tab.

**Comment by hit** [comment]
Unable to open preferences after ce5449c
Traceback (most recent call last):
  File "/home/g/Apps/emesene/emesene/gui/gtkui/MainMenu.py", line 288, in <lambda>
    lambda _args: handler.on_preferences_selected())
  File "/home/g/Apps/emesene/emesene/gui/base/Handler.py", line 133, in on_preferences_selected
    self.session)
  File "/home/g/Apps/emesene/emesene/extension.py", line 621, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, *args, *_kwargs)
  File "/home/g/Apps/emesene/emesene/extension.py", line 492, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/home/g/Apps/emesene/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(_args, *_kwargs)
  File "/home/g/Apps/emesene/emesene/gui/gtkui/Preferences.py", line 112, in **init**
    self.general = GeneralTab(session)
  File "/home/g/Apps/emesene/emesene/gui/gtkui/Preferences.py", line 1292, in **init**
    'session.config.b_check_for_updates')
  File "/home/g/Apps/emesene/emesene/gui/gtkui/Preferences.py", line 460, in append_check
    widget = self.create_check(text, property_name)
  File "/home/g/Apps/emesene/emesene/gui/gtkui/Preferences.py", line 452, in create_check
    widget.set_active(default)
TypeError: an integer is required

**Comment by Sbte** [comment]
Have you maybe logged in with a different account before this? Also, next time, please open a new issue. This one is closed.
