### ISSUE TITLE
Why emesene2 creates a folder for each contact with email address in the ./config folder?

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#991]
Hello, 

I would like to know why currently, when I see the config files created after using emesene, I see a folder for each contact and the folder name is the contacts email address. I think it doesn't look too practical and a external user using my computer can easily see email addresses of my contacts that I don't want to show too publicly.

I imagine this has some relation with the "View Information" command in the emesene program. But is there a way to disable this feature? In my case, I don't like to save chat conversations, so perhaps I could have a choice to avoid showing these folders. Or perhaps saving those settings in a simple file? Or perhaps renaming those folders, if it is definitely impossible to avoind creating them? In addition, is is possible to "clear history" in those folders with some button or command within the client (i.e., without using some external routine or program like ccleaner, bleachbit, etc)?

Thanks for your attention,

**Comment by Sbte** [comment]
Because we use them to store avatars and custom emoticons. In emesene1, we did something similar, but then we added the contact email in from of every file. Using folders for every contact is cleaner. This is not related to the "View information" window.

**Comment by c10ud** [comment]
if you care about your privacy, encrypt your home folder. we can put
everything in one file and that still would be readable, so..the only
way is encryption

as for disabling/deleting history that still not possible (we need it
for caching stuff) but i think it can be done writing an alternative
extension for logger and maybe the cache modules need to be hacked too
(not cool). ofc this is not something you can do in a day, but a guy
said he'd like to work on an history manager for emesene, that would
be a step forward

2012/1/27 Sacolevas
reply@reply.github.com:

**Comment by Sbte** [comment]
You can already disable the logger through the preferences, and you can manually delete the `log` directory in `.config/emesene2/service/account` to remove all previously logged stuff. Adding a button in the preferences to do this for you should be fairly easy.
