### ISSUE TITLE
[ERROR] status icons that do not change

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#993]
The status icons online, away, etc. ... not change either, but this only happens a few times, and do not have a complete log pultroppo but only a photo:

http://img7.imagebanana.com/img/2a9mg5wv/tmpgl.jpg

**Comment by Sbte** [comment]
Where did you change the status, and what tray icon do you use?

**Comment by KinG-InFeT** [comment]
I'm trying to change the status from the tray icon and there is no change of icon or state.
If, however, change status from the main page of emesene, the state changes but the tray icon remains unchanged.

COMPLETE LOG: http://www.supershare.net/file/412569-6149693150.html

**Comment by Sbte** [comment]
Ok, so it sounds like the tray icon is disconnected from the emesene main app. As in it doesn't do anything. Is that correct? If so then I suppose en handler session is incorrect.

**Comment by KinG-InFeT** [comment]
I agree with your diagnosis.

**Comment by KinG-InFeT** [comment]
the problem is not resolved :S

**Comment by Sbte** [comment]
Not sure what's going on then. The session is properly set in the tray icon as far as I can tell, so it should receive status changes.

I can't use a normal tray icon myself (I'm using Ubuntu), so I don't think I can help you with this...

**Comment by Sbte** [comment]
Ok, I just thought of something. We actually send the status change signal to the server, but since your account is messaged up or something (as we concluded last time), it might be that the msn servers never accept your status change. Can you confirm that it you change your status, other people don't actually see a change of your status?

**Comment by KinG-InFeT** [comment]
the problem and that it is only recently that this thing is making me .... and if I'm not mistaken I can not even talk to the people I chat ...

**Comment by Sbte** [comment]
And other messengers work properly? I still think most bugs you report here are some sort of a problem on your side, not ours. Your log is also still full of server errors.

**Comment by KinG-InFeT** [comment]
I confirm that the sys try icon is working now, I think it's an error that occurs only in some specific cases unknown to us.
