### ISSUE TITLE
No window buttons in "View Informations" window

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#995]
I admit I haven't used this feature much, so I dunno how long this issue has been there for (or if it's a feature), but in the window that appears after right-clicking on a contact and choosing "view informations" there aren't the minimize/maximize/close buttons

**Comment by Sbte** [comment]
Are you using Gnome Shell?

**Comment by Soulsuke** [comment]
Yes, I'm using gnome-shell 3.2

**Comment by Sbte** [comment]
And do you have those buttons on the preference window?

**Comment by Soulsuke** [comment]
Now that you mention it, they miss from that window as well! I probably didn't notice because of the "close" button on the bottom-right of the window

**Comment by Sbte** [comment]
@c10ud, should we make this a normal window instead of a dialog?

**Comment by c10ud** [comment]
this is a gnome-shell design decision, we either add another close button or make it a window instead of a dialog
