### ISSUE TITLE
Feature Request---- See when someone logs as offline

### ISSUE THREAD

**Issue by rodrigooo** [emesene/emesene#996]
Could someone make a plugin or something able to do it? It worked in  1.6.3, and it was the main reason I started using Emesene!

**Comment by Sbte** [comment]
I tried to write this plugin, but it seems like the MS servers don't send a notification any more when someone logs in as invisible? So maybe it's not even possible to do this any more?

**Comment by rodrigooo** [comment]
Is there a way to test it? Maybe using Windows Live Messenger....

**Comment by Sbte** [comment]
I tried WLM too, and I do not get a presence_changed signal from papyon. I did get that signal half a year ago, so I'd say it's not fixable. Probably the change happened at the same time emesene 1 stopped working.
