### ISSUE TITLE
no chat history in emesene 2.12.1

### ISSUE THREAD

**Issue by pengshao** [emesene/emesene#997]
I am using emesene under gentoo AMD64, and I have been using a git version for quite a long time before today. I can firmly remember that in the past the chat history was working fine, however today when I tried to retrieve a chat history, they are all gone. So I update my git version, no chat history, and then I rolled back to 2.12.1 ( my previous git version might be based on 2.12.1 as well, but sorry I cannot confirm this so it could be based on an earlier version ), still no luck :(

Where is the chat history usually stored? I went to .config/emesene2, and didn't find anything like chat history... Does this mean I might have lost my chat history?... 

Thank you :)

**Comment by Sbte** [comment]
This is most likely because you have multiple instances of emesene open. See #998. Emesene can only open the database once.

**Comment by pengshao** [comment]
thanks for the quick reply. I just killed all my emesene process and restarted it, now they are back. Thanks a lot! :)
