### ISSUE TITLE
[FEATURE] Press ESC button and close in try emesene

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#999]
It would be convenient (as emesene1) that when you press the ESC button on the main screen of emesene2 it is reduced in the system tray as if the premise X

**Comment by KinG-InFeT** [comment]
lol 999 issue xD (sorry off topic)

**Comment by Sbte** [comment]
I got a patch for this, but currently it breaks the search feature on the contact list. I'm not sure how to fix this atm, and I don't have much time...

**Comment by KinG-InFeT** [comment]
hours so the patch does not run the search bar?

**Comment by Sbte** [comment]
It's fixed in a different way now. I first wanted to do it using accelerators, but not I just use a key press event instead.
